### ISSUE TITLE
Error handling of SxcInstance.Render and non-existing module

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#1009]
If a skin includes a non-existing module with `SxcInstance.Render`, the whole page stops working. Make sure that the rest of the page continues working (for example, surround with try-catch).

**Comment by iJungleboy** [comment]
If we catch it inside the Render, then you cannot do a try-catch around it in your code. 
I'm not sure if this is probably not a good idea to do this inside 2sxc. What's your case that you think it should be inside 2sxc?

**Comment by raphael-m** [comment]
Solution, discussed with @iJungleboy: Create user control that calls `SxcInstance.Render` and handles errors (logging and reporting error), place in DNN7 namespace.

**Comment by iJungleboy** [comment]
This never had a priority, will close now.
