### ISSUE TITLE
FireFox Event-object issue on buttons: V8.6 RC5 more button in default toolbar doesn't work

### ISSUE THREAD

**Issue by classmaxx** [2sic/2sxc#1013]
The more button in default toolbar doesn't work. There is an js-error in Browser console.
<img width="692" alt="2sxcerror" src="https://cloud.githubusercontent.com/assets/22051626/20118679/b49c63f8-a605-11e6-9fa5-87d0a1ae1f8b.PNG">

**Comment by iJungleboy** [comment]
Can't reproduce your issue, so we need more details, please

1. ensure it's not a browser cache issue 
2. Please add ?debug=true to your URL, that will load the unminified JS. Please tell me there where the thing blows, thx!

BTW: RC5 is identical to the final release, just so you know.

**Comment by classmaxx** [comment]
the error is only in FF (V.49.0.2). In chrome and edge everything is fine. I've tested on several machines with FF, always the same. Here is the  unminified JS error:
<img width="706" alt="2sxcerror" src="https://cloud.githubusercontent.com/assets/22051626/20136554/cd557bc6-a675-11e6-9835-a022a592c542.PNG">

**Comment by iJungleboy** [comment]
Ok, firefox event issue is very common. I'll look into it.
