### ISSUE TITLE
V.8.6.0 Error when Publish an item in toolbar

### ISSUE THREAD

**Issue by classmaxx** [2sic/2sxc#1028]
I've got an error, when i try to publish an unpublished item in toolbar.

Error: Had an error talking to the server (status 400).
Message: The request is invalid.
Detail: The parameters dictionary contains a null entry for parameter 'sortOrder' of non-nullable type 'System.Int32' for method 'Boolean Publish(System.String, Int32)' in 'ToSic.SexyContent.WebApi.View.ModuleController'. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter.

**Comment by classmaxx** [comment]
addition (maybe helps): 
i've two templates, which are rendering the same data-item. i got the error only at the second template.
1. (works): this template gets the data-item with 
       artkopf = AsDynamic(Data["Default"].First(); 
All fine. (sortOrder = 0)

2. (error): this template gets the data-item over an ValueFilter and Attach the stream as follows:
	var selectedArtikel = CreateSource<ValueFilter>(allArtikel)
	selectedArtikel.Attribute = "Artikellink";
	selectedArtikel.Value = "[Querystring:Detail]";
        Data.Attach("Details",selectedArtikel);
        artkopf = AsDynamic(Data["Details"]).First();

Both templates rendering is ok, but when i publish an unpublished item the second templates got the error. (sortOrder = null)

**Comment by iJungleboy** [comment]
Thanks - this may help. Could you be more precise with which template shows the button which you click, and which one shows the error? is the error only until a refresh (only in ajax), or does it stay?

**Comment by classmaxx** [comment]
I've edited my previous text. The error is always there, if i click on the Publish-button in the toolbar.

**Comment by iJungleboy** [comment]
I can reproduce the error in certain cases - will check / fix

**Comment by iJungleboy** [comment]
There seem to be 2 issues in this that I found

1. for data-mode (not content-mode) there was no publish functionality yet - so the JS gave the module-id and the position in the list, but never just the entity-id, which is what we need in data mode
2. there was an additional bug when copying attributes from draft to published, which also cause trouble...
