### ISSUE TITLE
400 Bad Request - API (when adding elements or add/edit views)

### ISSUE THREAD

**Issue by thomassen88** [2sic/2sxc#1035]
Hi guys,

I get an error when im saving content or adding/editing views.

**This is error i get when i try to add a element:**
http://www.branko.no/desktopmodules/2sxc/api/eav/entities/savemany?appId=1 400 (Bad Request) (anonymous function)	@ VM15353 set.min.js?sxcver=8.7.0.27705:103
**Response:** {"Message":"Bad Request","ExceptionType":"System.Exception","ExceptionMessage":"There are more Presentation elements than Content elements."}
Screenshot: [https://s18.postimg.org/3mue632p3/error_adding_element.png](https://s18.postimg.org/3mue632p3/error_adding_element.png)

**And this error i get when i try to add or edit views:**
http://www.branko.no/desktopmodules/2sxc/api/eav/contenttype/GetSingle?appid=1&contentTypeStaticName=2SexyContent-Template 400 (Bad Request) (anonymous function)	@ VM15353 set.min.js?sxcver=8.7.0.27705:103
**Response:** {"Message":"Bad Request","ExceptionType":"System.NullReferenceException","ExceptionMessage":"Object reference not set to an instance of an object."}
Screenshot: [https://s18.postimg.org/8k7yr74o7/error_adding_editing_views.png](https://s18.postimg.org/8k7yr74o7/error_adding_editing_views.png)

I had an similar issue later this year, but i cant remember what i did to fix it, but i think it had something to do with the fakeurl-api in dist/dnn/ui.html

------
DNN version: 07.04.02 (216)
2sxc version: 8.7.0 (had the same issue with 8.3.6)

**Comment by iJungleboy** [comment]
This is hard to give a quick answer to. Just a few questions

1. both errors on same app?
1. both errors _not_ on other apps?
1. error one on one module only, or on many?

**IF these errors are not related, then this is what's happening on 1 adding element**
The first one is probably the easiest - assuming the error message only affects one module. In this case something internal went very wrong, and it's warning you. The background is that a ContentBlock consists of this information:
1. templateid
1. entity-field with list of content-items (item 1, item 2, item 3, ...)
1. entity field with list of presentation items (pres 1, pres 2, pres 3, ...)

Depending on the configuration of a template, there may only be one content item or many (list-mode), and the presentation items are used, or not. If the template uses presentation it must keep the items in sync - so the presentation-item-4 for content-item-4 must be in the same position in the list. 

* This also means adding an item requires it to add both an item and a presentation item. 
* This also means that to be safe, it first checks if the length of both lists are the same (the usually are). 
* this means that in your specific case (and you're the first to experience this) it doesn't match, so it warns you

So if my analysis is correct, you can just create another module and there you shouldn't see the errors. 

**if these errors are related**
But if I'm wrong - especially if your second error is on the same app - then something is wrong with the template data on this app. You could look deeper into the system by changing the scope to `2SexyContent-System` and looking an the internal data there. Here's some help:
http://2sxc.org/en/Blog/post/advanced-dynamic-data-content-understanding-content-type-scope

BTW: this sounds very installation specific, so it's more a user support than a 2sxc-issue. Please post follow-up questions on stackoverflow - http://2sxc.org/en/blog/post/moving-discussions-from-codeplex-to-stack-overflow
