### ISSUE TITLE
ValueFilter for DateTime Attributes

### ISSUE THREAD

**Issue by joshgk00** [2sic/2sxc#1057]
Hello,
I'm working with the Blog app and I see how to filter the Blog posts by year using the Visual Query Designer. I use the querystring value that has the year and in the ValueFilter and my properties are as follows:
Attribute: PublicationMoment
Value: [QueryString:year]-01-01 and [QueryString:year]-12-31
Operation: between

How would I get the posts from a specific month and year, if those values are passed via query string parameters. Because the months of the year have a varying number of days, I'm not sure how you would accomplish this in the Value field of the ValueFilter. Currently I'm passing the 2 digit month as the parameter.

I tried something like: [QueryString:year]-[Querystring:month]
Operation: contains
but the above operation doesn't really work because the datatype is a DateTime object. 

I could do it in the razor view but I'm afraid that the paging datasource would have too many pages in it since it would be based on the larger subset of posts for the given year that was passed in the querystring parameter.  

Is there any way to do this with the filter?

**Comment by iJungleboy** [comment]
This is a great question - and I would love to answer it, but I must insist on user questions being posted on stackoverflow. See you there :)
