### ISSUE TITLE
V8.8.1 Cannot insert Snippets in Template-Editor

### ISSUE THREAD

**Issue by classmaxx** [2sic/2sxc#1064]
When i click on a snippet in Template-Editor to insert nothing happens...

**Comment by iJungleboy** [comment]
This is a known bug which showed "ace is not defined" in the js console (F12). It should be fixed in 08.08.01 - see #1037 

could you verify or tell us if it's something else?

**Comment by classmaxx** [comment]
Sorry, was my fault... I have updated to V.8.8.1, but there was an open Template editor in Browser from the old version... Eyerything works fine :-)

**Comment by iJungleboy** [comment]
thx

**Comment by nicpitsch** [comment]
Often the snippets don't get inserted on click. The browser console (Chrome) then shows a warning and two errors:
warning:
`A Parser-blocking, cross-origin script, http://cdn.jsdelivr.net/ace/1.2.5/noconflict/ace.js?sxcver=8.8.1.30436, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.`
errors:
`Uncaught ReferenceError: ace is not defined
    at cdn.jsdelivr.net/ace/1.2.5/noconflict/ext-language_tools.js?sxcver=8.8.1.30436:1`
and
`TypeError: Cannot read property 'snippetManager' of undefined
    at controller.e.addSnippet (sxc-develop.min.js:1)
    at fn (eval at compile (set.min.js?sxcver=8.8.1.30436:233), <anonymous>:4:426)
    at b (set.min.js?sxcver=8.8.1.30436:126)
    at e (set.min.js?sxcver=8.8.1.30436:276)
    at b.$eval (set.min.js?sxcver=8.8.1.30436:145)
    at b.$apply (set.min.js?sxcver=8.8.1.30436:146)
    at HTMLElement.<anonymous> (set.min.js?sxcver=8.8.1.30436:276)
    at Sf (set.min.js?sxcver=8.8.1.30436:37)
    at HTMLElement.d (set.min.js?sxcver=8.8.1.30436:37)`

It happens with the latest 2sxc 8.8.1 on several DNN installations. I tried this also with a fresh DNN 07.04.02 and 2sxc 8.8.1. It is not consistent, means it may not happen always. I can't see a pattern.

**Comment by Tychodewaard** [comment]
I can confirm that I have the same issues. In 8.8.1 and both using Mac/Chrome and Windows/IE

**Comment by iJungleboy** [comment]
Ok, will re-open. 

Question: are you guys working on https when you have the problem, or on http?

**Comment by Tychodewaard** [comment]
Http

Met vriendelijke groet / Kind regards,

Tycho de Waard
Business unit manager
ICATT interactive media

020 5213 560
061 1296 227
Tycho.dewaard@icatt.nl

**Comment by nicpitsch** [comment]
http, with Chrome and FireFox. Sometimes it works the first time after login and when editing the first time.

**Comment by iJungleboy** [comment]
I believe I found the issue. The code loads...

```
            addScript({ url: "//cdn.jsdelivr.net/ace/1.2.5/noconflict/ace.js", async: false }); // must be preloaded before the ext-language-tools
            addScript({ url: "//cdn.jsdelivr.net/ace/1.2.5/noconflict/ext-language_tools.js", async: true });
```
...the first script async (kind of "no hurry") then loads the ext-language in sync-mode. My guess is that there are cases where the second one is already cached and "arrives" early. I'll set both to sync. 

Could someone please replace their `ui.html`  with the attached version to confirm that it fixes everything? You'll find the ui.html in your `desktopmodules/tosic_sexycontent/dist/dnn/` folder. 
[ui.zip](https://github.com/2sic/2sxc/files/690858/ui.zip)

**Comment by nicpitsch** [comment]
I can confirm that this change fixes everything. Thank you!
