### ISSUE TITLE
In dnn 9 new persona bar cover 2sxc admin panel

### ISSUE THREAD

**Issue by mangiove** [2sic/2sxc#1070]
Not a really issue and not urgent, but in dnn version 9 the new persona bar cover partially the 2sxc admin panel.

https://snag.gy/ARuM64.jpg

**Comment by iJungleboy** [comment]
thanks! looks odd, but important.

**Comment by raphael-m** [comment]
The DNN9 bar has a z-index value of 9999999. Okay, we'll use 99999999 now ;)
