### ISSUE TITLE
Toolbar-button contentitems should also work when a template doesn't have a content-type assigned

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#1073]
I created a Razor template that uses a query for the data source. I do not want to use the Content paradigm, and instead use Data.

The only way I can get the edit toolbar icon for Content Items / Data to appear in the toolbar is to set the Content Item type in the View to the target type, but when I do that the module ignores the query and only displays the message about there not being a Demo Item.

I understand that when the content type is selected that it looks for items that have been assigned to the instance. But when a data query is chosen, it ignores that and only displays the message about there being no demo item. When I create and assign a demo item to the view, the data appears as expected. But if a user deletes the demo item, all the data disappears and shows the "no demo item" message.

I can appreciate the sophistication of 2SXC, but sometimes as a developer I just want to use data instead of content along with a way for users to directly edit all the data items. And there doesn't seem to be a way around this issue that I can find.

**Comment by iJungleboy** [comment]
Basically if you would _not_ set the content-type, then everything would work, but you would be missing something else, right? what is it that's missing, if you don't set a content-type? I didn't quite get that. 

Note that there are actually use cases where _both_ content-type + demo-item + queries are needed.

**Comment by tpperlman** [comment]
If I don't set the Content Type, then the content items (data) icon won't appear...

![content-items-button](https://cloud.githubusercontent.com/assets/1871915/21644279/bfab797e-d25a-11e6-8b1b-24b9c5344695.jpg)

I also can't get it to appear when I try and create an Edit Toolbar like so:

`@Edit.Toolbar(actions: "contentitems", contentType: "Ovations")`

I'd like editors to be able to direct add and delete data in the app.

**Comment by iJungleboy** [comment]
So your real concern would be solved, if the content-items would appear correctly - which it apparently doesn't. Let me look into that.

**Comment by tpperlman** [comment]
Thank you for helping me zero in on the source of my issue.

**Comment by tpperlman** [comment]
Hi folks, this fix worked to display the ContentItems icon in the toolbar, but I can't get it to appear for users other than Host-level accounts. Basically, portal admins should be able to see the icon or any other security level specified as having CRUDA access I suppose.

I tried setting different security privileges on the data, query and view, but none would allow admins to view the icon on the toolbar.

**Comment by iJungleboy** [comment]
Reason is the default permission check, which you can override when you really want to. Check out our just released Mobius Forms App - it has a great example of the ContentItems button (even with a dynamic content-type name :)

http://2sxc.org/en/apps/app/mobius-forms

I'll post more about the app in a few days, but it has the toolbar-button.

```
      @Edit.Toolbar(toolbar: new object[] { 
          new { showCondition = true,
              command = new { action = "contentitems", 
                contentType = "some-type-name", 
                filters = new { ModuleId = Dnn.Module.ModuleID } 
            }
        }
      }, settings: new { hover="left", show = "hover" })
```

**Comment by tpperlman** [comment]
Worked like a charm, thank you! Here is what I ended up using to create the buttons I needed in case anyone else would benefit:

```
	@Edit.Toolbar(toolbar:
		new object[] { 
			new { 
				command = new { action = "layout" }
			},
			new { 
				command = new { action = "new", contentType = "Sponsors" }
			},
			new { 
				showCondition = true, 
				command = new { action = "contentitems", contentType = "Sponsors" }
			}
		}
	)
```

**Comment by iJungleboy** [comment]
BTW: you could also use different icons on each button if you want to - to help differentiate the "new" buttons.
