### ISSUE TITLE
V.8.8.2 Error in SQLDataSource with EntityTitle

### ISSUE THREAD

**Issue by classmaxx** [2sic/2sxc#1080]
There is a bug in V.8.8.2 with SQLDataSource:

![error datasource](https://cloud.githubusercontent.com/assets/22051626/21684672/ff58a7ea-d35e-11e6-992b-740f9812032d.PNG)

There is a column named EntityTitle in SQL.  
Same code works in V.8.8.1

**Comment by iJungleboy** [comment]
Thanks for this - we did some internal clean up and replaced strings in the code with constants. I'm guessing this was an unexpected side-effect, because of small/large case. I'll try to fix asap.

**Comment by iJungleboy** [comment]
I believe I fixed it - could you test it by placing the files in the zip attached into your web bin folder?
[eav 8.8.2b.zip](https://github.com/2sic/2sxc/files/689442/eav.8.8.2b.zip)

**Comment by classmaxx** [comment]
I've tested it and for me everything looks fine now :-)
