### ISSUE TITLE
V.8.9.0 Entitypicker-Field lose binding after editing

### ISSUE THREAD

**Issue by classmaxx** [2sic/2sxc#1090]
I've an issues with entitypicker-field.
1. I edit an Contenttype, which has one or more entitypicker-fields. The entitypicker-field(s) allowing edit Items and so on...
2. I edit the entitypicker-field and **save** it. 
3.1 (AllowMultiValue=true) Now i want to choose another value from this entitypicker-field . I get all Data from all contenttypes in the searchbox. It seems that entitypicker-field lose binding after editing.
3.2 (AllowMultiValue= false) Now I remove this value from list and choose a new one. I get all Data from all contenttypes in the searchbox. It seems that entitypicker-field lose binding after editing.

The issue is independent from the setting AllowMultiValue  true or false. It happens in both cases. If i don't save the entitypicker-field, the binding is ok.

**Comment by iJungleboy** [comment]
I don't understand, sorry. Could you add some screenshots to explain your issue?

**Comment by iJungleboy** [comment]
Haven't heard back, will close this for now. If it's still an issue, please provide more details as requested, and re-open the issue.

**Comment by classmaxx** [comment]
Ok, here we go:
1. I choose a value from an Entitytype Field.
 <img width="727" alt="binding issue 0" src="https://cloud.githubusercontent.com/assets/22051626/22148775/656a0a9e-df10-11e6-849a-690977b1618d.PNG">

2. The entitypicker-field(s) allowing edit Items and so on... 
<img width="720" alt="binding issue 1" src="https://cloud.githubusercontent.com/assets/22051626/22148790/79c6308a-df10-11e6-9ce6-ae9e3adbf562.PNG">

3. I edit this item and save it. 
<img width="727" alt="binding issue 2" src="https://cloud.githubusercontent.com/assets/22051626/22148797/8b31b79a-df10-11e6-868e-fb2e19112873.PNG">

4. Now I remove this value from the list, will choose a new one and got this:
<img width="721" alt="binding issue 3" src="https://cloud.githubusercontent.com/assets/22051626/22149051/ed660e4c-df11-11e6-8976-21372a4f3a26.PNG">

**Comment by iJungleboy** [comment]
perfect, thx. I assumes this is something related to lazy data loading - I'll check

**Comment by iJungleboy** [comment]
Can reproduce.

**Comment by iJungleboy** [comment]
I believe this is the same issue as #987  - fixed.
