### ISSUE TITLE
Missing values from Drop-down fields after upgrade to 8.7.0

### ISSUE THREAD

**Issue by andyduo** [2sic/2sxc#1093]
I upgraded the module on a site where I have an app running. The content items include several drop-down fields. After the module upgrade the Content Type Fields all say Unknown Input Type. When I go in and update the input type back to Drop-down and then try to edit the values for the drop-down in DropdownValues none of the existing values load into the values field. This means I can't add/remove/edit the existing values in the drop-downs without messing up the data in the entities that already are published. 

How can/is there a way to retrieve these values so I can keep using the App going forward?

**Comment by iJungleboy** [comment]
Your error is fairly strange - I haven't heard of it. Before investing more time, I recommend you upgrade to the latest 2sxc and see if the problem goes away. Also check the JS console (F12) to see what is reported there.

**Comment by iJungleboy** [comment]
@andyduo just fyi: since I presume this will go away by itself, I'll close this for now. Feel free to re-open if it is still an issue.

**Comment by andyduo** [comment]
Hi there, I upgraded to 8.9.1 but I still get blank values in the Drop-Down field type. When I open the settings for the drop-down it records the following in the console:
ocLazyLoad.fileLoaded //cdn.tinymce.com/4/tinymce.min.js
eav-edit.min.js?sxcver=8.9.1.13916:1 Object {required: true, label: "Name", description: b, settings: Object, header: Object…}canCollapse: falsedescription: b$$unwrapTrustedValue: ()arguments: (...)caller: (...)length: 0name: ""prototype: Objectconstructor: ()__proto__: Object__proto__: ()[[FunctionLocation]]: set.min.js?sxcver=8.9.1.13916:151[[Scopes]]: Scopes[5]__proto__: bdisabled: falsefieldGroup: undefinedfocused: falseheader: Objectlabel: "Name"langReadOnly: falseonBlur: "to.focused=false"onFocus: "to.focused=true"required: truesettings: Object__proto__: Object
eav-edit.min.js?sxcver=8.9.1.13916:1 Object {required: false, label: "Default Value", description: b, settings: Object, header: Object…}
eav-edit.min.js?sxcver=8.9.1.13916:1 Object {required: false, label: "Input Type", description: b, settings: Object, header: Object…}
eav-edit.min.js?sxcver=8.9.1.13916:1 Object {required: false, label: "ValidationRegExJavaScript", description: b, settings: Object, header: Object…}

I have no idea what any of that means unfortunatly.

**Comment by iJungleboy** [comment]
Ok - I think I know what "hit" you. In an upgrade ca. 8.0 we split the settings of the string-field into various groups. Because of this, the drop-down values are a new field - which of course is empty. To ensure backward compatibility, the now-hidden field is still operational, so this is used for your dropdown - until you add new values. 

To see the old, hidden field/data, go into debug-mode _before_ opening the field settings - you should then see the "hidden" fields as well, and/or you can then press the flash-button at the end to see the data model. See also http://2sxc.org/en/Blog/post/debugging-2sxc-8-enter-advanced-mode-with-control-click

**Comment by andyduo** [comment]
Awesome, got it. Thanks for the help @iJungleboy much appreciated.
