### ISSUE TITLE
loads of exceptions

### ISSUE THREAD

**Issue by Tychodewaard** [2sic/2sxc#1095]
Hi there

Don't know if this is something you recognize but I get loads of exceptions from 2sxc. 

Message:Object reference not set to an instance of an object

at ToSic.SexyContent.View.InitModuleActions() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\View.ascx.cs:line 160
   at ToSic.SexyContent.View.get_ModuleActions() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\View.ascx.cs:line 111

I'm on 8.5.2 for this install 

Kind regards
Tycho

**Comment by iJungleboy** [comment]
Hi @Tychodewaard - no, this is no known issue. I believe the code/version you are seeing is

https://github.com/2sic/2sxc/blob/a7594e3efac19f7f7925b2bf7c71fb4d915b909e/View.ascx.cs#L159-L163

There's not much to go on from your feedback. Could you elaborate more? Like "happens on all modules" or "only on app, but only if I choose this-and-this-app" or "this started when I did..." or "most pages work, just some don't"...

**Comment by iJungleboy** [comment]
No feedback yet, will close for now. Pls comment to re-open if it's still an issue.
