### ISSUE TITLE
Nicer message when a Data-Source doesn't have configuration

### ISSUE THREAD

**Issue by kingjordan** [2sic/2sxc#1097]
Hello,

I have reproduced this issue both locally and on a live azure server.  Both are running DNN 8.0.4 (226) and 2 sxc 8.9.0

When I try to edit a StreamFallback data source by click "Configure Data Source" button in the top left of box I get the following error:
![ice_screenshot_20170126-105447](https://cloud.githubusercontent.com/assets/5931768/22343988/87527384-e3b7-11e6-9989-02b9a92d8d0d.png)

This issue appears for both imported apps (like the blog app) or new apps with new queries that I have created.

**Comment by iJungleboy** [comment]
The fallback data source doesn't have any configuration - and all that don't have it, show that error. It's not pretty, but so far wasn't a priority. I'll retitle this to "nicer message..."

**Comment by kingjordan** [comment]
That makes sense, so the order you add the streams is the order it tries to resolve for content.  Thanks,  Perhaps the configuration button can be disabled or hidden in this situation.

**Comment by iJungleboy** [comment]
Note: not the adding-order determines the fallback, but the naming-order of the in-streams A-Z

**Comment by kingjordan** [comment]
thanks, so its alphabetical 1,2,3 a,b,c
correct?

**Comment by iJungleboy** [comment]
Correct. I often name mine something like "A, B, C, ZFallback" or something
