### ISSUE TITLE
Content Import Error

### ISSUE THREAD

**Issue by TwoHeadsBrewing** [2sic/2sxc#1101]
After many months of using 2sxc; building sites, importing content, without any problems, I'm encountering an issue when importing content to a new site.  The only error message I see is "Had an error talking to the server (status 500)."  If I use a Content export from a previous date, the import works fine.

**Comment by iJungleboy** [comment]
That very little to go on. ATM there is no known issue. Could you please

1. Post it on stackoverflow http://2sxc.org/en/blog/post/moving-discussions-from-codeplex-to-stack-overflow
2. do more research - like JS errors in the F12-Console and/or messages from the Site Events (Admin-menu, ...)

**Comment by TwoHeadsBrewing** [comment]
I agree, there isn't much to indicate what the problem actually was.  F12-console doesn't reveal much, but I've attached the .log export.  There is nothing in the Admin Events Viewer related to 2SXC, and nothing in the server event viewer either.

I'm happy to send my .zip content export for troubleshooting purposes.  It happens on both my production and test servers.  And if it helps, I can provide access to my testing server as well.

**Comment by iJungleboy** [comment]
Ok, beam it over to info you know what 2sxc.org

**Comment by TwoHeadsBrewing** [comment]
OK, thanks!  Where would you like me to send it?  I can send an email with a storage location if that works.
