### ISSUE TITLE
Form doesn't become "dirty" on certain changes in the entity picker

### ISSUE THREAD

**Issue by lucatescari** [2sic/2sxc#1104]
After creating a new entity with the entity picker, the "save or cancel" prompt does not appear to save the entity to the entity picker.

Video:
https://www.screencast.com/t/O1EuEJNGNat/

**Comment by reto-f-999** [comment]
...so the data gets lost this way, if the admin-user can only create new entities (without selecting existing entities) on a specific entity field.

**Comment by christophbuehler** [comment]
Same issue occurs when removing an existing entity ("remove from list").
