### ISSUE TITLE
V.8.9.1 Problem with fieldname 'Title' in contenttype

### ISSUE THREAD

**Issue by classmaxx** [2sic/2sxc#1105]
I have a contenttype with a field named Title. This field is not marked as titlefield (the star). The marked field is called 'name'. 
When i go in adminview of this contenttype, i see the in the first column the values of field title an dnot values of field name.
if i rename the field 'title' to maybe 'titel', everything is ok...

Is it a bug or 'by design' ... ;-)

**Comment by iJungleboy** [comment]
This would be a minor bug :)

**Comment by iJungleboy** [comment]
This is extremely low priority and would take about an hour to fix. So we won't fix this unless it's important enough to someone to sponsor this. Will close for now.
