### ISSUE TITLE
Entity picker does not update correctly after saving entity

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#1110]
After creating a new entity inside of an entity picker, the items list is not updated, which leads to a message "(element not found)".

https://www.screencast.com/t/z64P1wiy7GU

**Comment by iJungleboy** [comment]
just fyi: I believe we fixed this recently...so I'm not sure why it's "back"

**Comment by christophbuehler** [comment]
@raphael-m how can I reproduce this? It seems to be working just fine.

**Comment by lucatescari** [comment]
Tested, seems to be working

**Comment by iJungleboy** [comment]
Will close as this should resolve itself in the new angular 6/7 UI.
