### ISSUE TITLE
Exported xml data (content) sometimes truncates last characters

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#1113]
So file ends with `</SexyContentD` instead of `</SexyContentData>`

Tested it 2sxc 8.11

**Comment by raphael-m** [comment]
Probably fixed with https://github.com/2sic/eav-server/commit/a87e847c34ed24b0970ca951aa0b6f7f00ec9648 - but I haven't been able to reproduce the issue, so I'm not able to test it.
@iJungleboy, can I test it somewhere?

**Comment by iJungleboy** [comment]
I tested it, the case where I had it was fixed with this update.
