### ISSUE TITLE
V.8.11 Error when entityfield is marked as title

### ISSUE THREAD

**Issue by classmaxx** [2sic/2sxc#1115]
When i marked (with the star) an entityfield as titlefield and then try to open the data in adminmode, i got following error:

<img width="539" alt="error entityfeld" src="https://cloud.githubusercontent.com/assets/22051626/23306316/4dbbd22a-faa3-11e6-8a67-2b5ab6bde863.PNG">

console output in browser looks like:
<img width="787" alt="error entityfeld2" src="https://cloud.githubusercontent.com/assets/22051626/23306330/6196401e-faa3-11e6-8b1c-197d68f04180.PNG">

**Comment by iJungleboy** [comment]
Found cause, will fix...
