### ISSUE TITLE
If a hyperlink field has no buttons, the input field uses only a minimum of space

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#1116]
If a hyperlink field uses no buttons (i.e. adam, page picker, ...) the input field uses only a minimum of space, probably because the field does not gets in block-mode anymore. 

in this case, only a little part of an URL is visible (see screenshot)

---

![short-line](https://cloud.githubusercontent.com/assets/12188254/23361606/c2e3b496-fcf1-11e6-9396-c975c8c3068d.png)

**Comment by christophbuehler** [comment]
I've implemented a quick-and-dirty fix on top of the table-layout hack.
Might consider switching to flexbox, as it was designed with dynamic layouts in mind.
