### ISSUE TITLE
QuickEdit Toolbar 2.0. - Blur filter does not work in Internet Explorer 11

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#1117]
if you select a module with the 2sxc quick edit toolbar, the module gets a blur filter, so you can see which module if affected and so on. This works well in Chrome and Firefox.

in Internet Explorer you don't get that blur filter/effect. maybe because IE works different with blur effects (?)
http://stackoverflow.com/questions/25850100/css-blur-in-ie-11

**Comment by iJungleboy** [comment]
Is this an issue worth fixing? We're talking about an effect which is just a helper, and for a browser which is dying. How important is this, or just fyi?

**Comment by reto-f-999** [comment]
because a lot of people in Switzerland use IE 11 (CH: 11.5%, global: 3.5%), and this functional helper tells you which module you selected to decide if its the right one to i.e. delete, this is IMO important.
Source of stats: http://caniuse.com/

**Comment by iJungleboy** [comment]
I understand this - but since it will become obsolete and only affects admins using old browsers (not end-users), we probably will never fix this.
