### ISSUE TITLE
DnnSQLDataSource failing on 8.11

### ISSUE THREAD

**Issue by mryckman** [2sic/2sxc#1120]
Hello,

I upgraded to 8.11 and an existing query started failing. The error is coming from the DnnSQLDataSource. I confirmed that the script itself is working correctly. Here's the error it's showing:

Default DataSource Name: DnnSqlDataSource ---> System.NullReferenceException: Object reference not set to an instance of an object. at ToSic.Eav.ValueProvider.OverrideValueProvider.Get(String property, String format, Boolean& propertyNotFound) in C:\Projects\eav-server\ToSic.Eav.Tokens\ValueProvider\OverrideValueProvider.cs:line 30 at ToSic.Eav.Tokens.TokenReplace.RetrieveTokenValue(String sourceName, String key, String format) in C:\Projects\eav-server\ToSic.Eav.Tokens\Tokens\TokenReplace.cs:line 194 at ToSic.Eav.Tokens.TokenReplace.ReplaceTokens(String sourceText, Int32 repeat) in C:\Projects\eav-server\ToSic.Eav.Tokens\Tokens\TokenReplace.cs:line 154 at ToSic.Eav.ValueProvider.ValueCollectionProvider.LoadConfiguration(IDictionary`2 configList, Dictionary`2 instanceSpecificPropertyAccesses, Int32 repeat) in C:\Projects\eav-server\ToSic.Eav.Tokens\ValueProvider\ValueCollectionProvider.cs:line 54 at ToSic.Eav.DataSources.BaseDataSource.EnsureConfigurationIsLoaded() in C:\Projects\eav-server\ToSic.Eav.DataSources\BaseDataSource.cs:line 156 at ToSic.Eav.DataSources.SqlDataSource.EnsureConfigurationIsLoaded() in C:\Projects\eav-server\ToSic.Eav.DataSources\SqlDataSource.cs:line 180 at ToSic.Eav.DataSources.SqlDataSource.GetList() in C:\Projects\eav-server\ToSic.Eav.DataSources\SqlDataSource.cs:line 190 at ToSic.Eav.DataSources.DataStream.get_LightList() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataStream.cs:line 135 --- End of inner exception stack trace --- at ToSic.Eav.DataSources.DataStream.get_LightList() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataStream.cs:line 143 at ToSic.Eav.DataSources.DataStream.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataStream.cs:line 82 at ToSic.SexyContent.Razor.SexyContentWebPage.AsDynamic(IDataStream stream) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\SexyContentWebPage.cs:line 110 at ASP._Page_Portals_0_2sxc_Training_Views__Almost_Full_cshtml.Execute() in [path].cshtml:line 16 at System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) at ToSic.SexyContent.Engines.RazorEngine.RenderTemplate() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 76 at ToSic.SexyContent.Engines.EngineBase.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Engines\EngineBase.cs:line 85 at ToSic.SexyContent.SxcInstance.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\SxcInstance.cs:line 202

**Comment by iJungleboy** [comment]
This sounds hard to reproduce. Could you mail me an app which has the setup causing this error?

**Comment by mryckman** [comment]
Thanks Daniel... I'm not sure how I could, as it's all based on custom tables. But, the error is happening in the query. The query only has one element (other than the output), which is "DnnSqlDataSource". The query in the DnnSqlDataSource works and executes just fine in Management Studio and is just a basic select query. The DnnSqlDataSource has one output feed that goes to the view.

When I run the query, it says Error 500, and when I look at a template output, I get the error text I pasted above.

**Comment by iJungleboy** [comment]
no feedback for a week, will close. If it's still an issue, please send requested info and we'll re-open.
