### ISSUE TITLE
Fix dnn 9 install experience

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#1125]
After installing in dnn9 and adding the first time, this message appears again:

![image](https://cloud.githubusercontent.com/assets/5321186/23656471/28106582-033a-11e7-86cd-18c38cf597ae.png)

Unclear why. Pls find out and possibly fix.

**Comment by iJungleboy** [comment]
this may be related to the latest installer-corrections

**Comment by raphael-m** [comment]
I can't reproduce this - I tested installing the latest package on DNN9 several times and it always worked flawlessly.
The error should appear if the DNN code-upgrade routine does not run or stops for some reason. I think we can close this issue for the moment, but keep an eye on it.

**Comment by iJungleboy** [comment]
ok
