### ISSUE TITLE
When managing (moving) Content Lists, can't edit list item anymore

### ISSUE THREAD

**Issue by lucatescari** [2sic/2sxc#1126]
After moving a list item in the list settings, you cant edit the item anymore.

![2sxc_error](https://cloud.githubusercontent.com/assets/7703479/23658203/e0d0268c-0341-11e7-94a8-02b46869814f.gif)

**Comment by iJungleboy** [comment]
cool video - what tool did you use?

**Comment by classmaxx** [comment]
It's an gif-File

**Comment by iJungleboy** [comment]
I know, but what recording tool was used @lucatescari ?

**Comment by lucatescari** [comment]
@iJungleboy I used Techsmith SnagIt (it has a video function). It puts out an MP4 file which i converted to a GIF so that I can embed it directly.
