### ISSUE TITLE
Cannot copy from another locale

### ISSUE THREAD

**Issue by ech01** [2sic/2sxc#1134]
Hello - 

This happens on all 2sxc content throughout the site. Upgraded to latest (8.11) thinking there might be a patch that fixed this but we still get the same result. 

When unlinking fields and copying from another locale, we receive the following error in the console:
ReferenceError: vs is not defined
    at Object.copyFrom (eav-edit.min.js?sxcver=8.11.0.28810:1)
    at l (eav-edit.min.js?sxcver=8.11.0.28810:1)
    at Object.copyFrom (eav-edit.min.js?sxcver=8.11.0.28810:1)
    at fn (eval at compile (set.min.js?sxcver=8.11.0.28810:233), <anonymous>:4:574)
    at b (set.min.js?sxcver=8.11.0.28810:126)
    at e (set.min.js?sxcver=8.11.0.28810:276)
    at b.$eval (set.min.js?sxcver=8.11.0.28810:145)
    at b.$apply (set.min.js?sxcver=8.11.0.28810:146)
    at HTMLAnchorElement.<anonymous> (set.min.js?sxcver=8.11.0.28810:276)
    at Sf (set.min.js?sxcver=8.11.0.28810:37)
(anonymous) @ set.min.js?sxcver=8.11.0.28810:118
(anonymous) @ set.min.js?sxcver=8.11.0.28810:90
$apply @ set.min.js?sxcver=8.11.0.28810:146
(anonymous) @ set.min.js?sxcver=8.11.0.28810:276
Sf @ set.min.js?sxcver=8.11.0.28810:37
d @ set.min.js?sxcver=8.11.0.28810:37

The field does not copy. 

Furthermore, when I edit any 2sxc content (just clicking edit pencil), I receive this error in the console. Does not prevent anything from saving, but it may be helpful

TypeError: Cannot read property 'setAttribute' of null
    at toggleDisable (set.js:43)
    at set.js:142
    at set.min.js?sxcver=8.11.0.28810:158
    at e (set.min.js?sxcver=8.11.0.28810:45)
    at set.min.js?sxcver=8.11.0.28810:48

Let me know if you need anything else. I'm not sure where to start, but I def need the ability to inherit data from a language

Thanks!

**Comment by ech01** [comment]
Looking where the error is: vs is not defined
at Object.copyFrom (eav-edit.min.js?sxcver=8.11.0.28810:1)

In this script:
https://github.com/2sic/2sxc/blob/master/dist/edit/eav-edit.js
Line: 1397 the variable vs is referenced, but not declared. 

Shouldn't this be present just like with the share/usefrom functions? 
var vs = vm.fieldModel.getVsWithLanguage(languageKey);

**Comment by iJungleboy** [comment]
Could you open the dialog with shift-click so you can edit the url, then add &debug=true and reload everything? this will load the JS un-minified, helping you debug it.

**Comment by ech01** [comment]
That does not appear to load anything unminified. 
Did you see the other comment up there^^ about the no declaration for vs variable?

**Comment by iJungleboy** [comment]
Ok, got it. Looking at https://github.com/2sic/2sxc/blob/master/dist/edit/eav-edit.js#L1396-L1400 shows that the variable should be called "value", not "vs"

**Comment by ech01** [comment]
Thank you! Will wait for an upgrade package.

**Comment by ech01** [comment]
When will this fix be available?

**Comment by iJungleboy** [comment]
@ech01 not 100% sure - we're doing some deep refactoring internally to prepare the move to Entity Framework Core. This will require more through testing before releasing, but I would assume towards the end of next week.
