### ISSUE TITLE
The import failed. Could not import the app / package: Sequence contains more than one matching element

### ISSUE THREAD

**Issue by jaxuk** [2sic/2sxc#1135]
Hi I've run into an issue importing an app I have just built on a different DNN installation.

Error message is: 

Could not import the app / package: Sequence contains more than one matching element.

Any ideas on how to work around this?

**Comment by jaxuk** [comment]
In event log, this is what is shown for the error:
```
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at ToSic.SexyContent.ImportExport.ZipImport.ImportZip(Stream zipStream, HttpServerUtility server, PortalSettings portalSettings, List`1 messages) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\ZipImport.cs:line 99
```

**Comment by iJungleboy** [comment]
I can't give you a clear answer, but this is the code

https://github.com/2sic/2sxc/blob/master/SexyContent/ImportExport/ZipImport.cs#L99-L102

It appears that the `app.xml` in the ZIP seems to have two parent nodes - could you check this? I don't know how it could happen, but you could at least probably work around it by manually changing the file for now.

**Comment by jaxuk** [comment]
It only has one top level element of "SexyContent"...

But it does have multiple elements of "Entity" with the attribute: "AttributeSetStaticName" that equals "2SexyContent-App" - should there only be one of these?

**Comment by iJungleboy** [comment]
Yes, it should only have one. This is the node which describes the app-name, folder, version, etc. Best look at them, and delete the wrong one.
