### ISSUE TITLE
Unpublished Items are not editable in entity picker

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#1138]
Steps to reproduce

1. Edit a content item with an entity picker
2. Create an entity in entity picker, save
3. Edit the entity, and set publish state to "hide", save
4. Try to edit the entity again -> Result: entity shows "Element not found", clicking on edit has no effect anymore

**Comment by iJungleboy** [comment]
I understand this issue, but it's not something that should work. Non-existing items shouldn't be in use yet, so this is by design. 

If you see an important use case, feel free to update this and we may re-open it.

**Comment by reto-f-999** [comment]
ok - fortunately removing (and i also guess deleting) the item is still possible, even if editing isn't.
