### ISSUE TITLE
Provide list of modules / pages where a template or app is used

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#114]
Like the DNN extensions list, we should provide a way to get a list of modules / pages where a template or app is used. This would be helpful for testing after updates etc.

**Comment by iJungleboy** [comment]
Would be nice but not a priority. If it's sponsored, we can go for it. Work is at least a day, because we would need to plan where to put it in the UI, create the stats, show them, i18n etc.

**Comment by iJungleboy** [comment]
Close till someone wants to sponsor / implement this

**Comment by iJungleboy** [comment]
was implemented in 11.02
