### ISSUE TITLE
DNN8 - Translate DNN TinyMCE Default not always working

### ISSUE THREAD

**Issue by marcingarbarczyk** [2sic/2sxc#1143]
I have two langauges: Polish (firstly) and English(gb). Sometimes I have problem with translate to English using your module.  I make changes in English, but after saving them I can not see them. When I edit again, I do not see any changes.

When I change site language to English and start making changes it's ok (small bug, when I change langauge my first langauge is selected not english, but English is in editor).

**Comment by iJungleboy** [comment]
This will be fixed with the new angular UI, so I'll close this for now.
