### ISSUE TITLE
2sxc stopped working angularjs error 414

### ISSUE THREAD

**Issue by imhobie** [2sic/2sxc#1156]
Using 2sxc 8-12 and DNN 9 also Evoq 9....
getting the following is the console error grab with any button i click "edit template, admin, etc."

[http://stackoverflow.com/questions/43583023/2sxc-stopped-working-angularjs-error-414](url)

`http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=DialogHost&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.5.8%2F%24injector%2Fmodulerr%3Fp0%3DSxcAdminUi%26p1%3DError%253A%2520%255B%2524injector%253Amodulerr%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.5.8%252F%2524injector%252Fmodulerr%253Fp0%253DMainSxcApp%2526p1%253DError%25253A%252520%25255B%252524injector%25253Amodulerr%25255D%252520http%25253A%25252F%25252Ferrors.angularjs.org%25252F1.5.8%25252F%252524injector%25252Fmodulerr%25253Fp0%25253DEavConfiguration%252526p1%25253DError%2525253A%25252520%2525255B%25252524injector%2525253Anomod%2525255D%25252520http%2525253A%2525252F%2525252Ferrors.angularjs.org%2525252F1.5.8%2525252F%25252524injector%2525252Fnomod%2525253Fp0%2525253DEavConfiguration%2525250A%25252520%25252520%25252520%25252520at%25252520http%2525253A%2525252F%2525252Fdnndev.me%2525252Fdesktopmodules%2525252Ftosic_sexycontent%2525252Fdist%2525252Flib%2525252Fangular%2525252Fset.min.js%2525253Fsxcver%2525253D8.12.0.29346%2525253A6%2525253A412%2525250A%25252520%25252520%25252520%25252520at%25252520http%2525253A%2525252F%2525252Fdnndev.me%2525252Fdesktopmodules%2525252Ftosic_sexycontent%2525252Fdist%2525252Flib%2525252Fangular%2525252Fset.min.js%2525253Fsxcver%2525253D8.12.0.29346%2525253A25%2525253A99%2525250A%25252520%25252520%25252520%25252520at%25252520b%25252520(http%2525253A%2525252F%2525252Fdnndev.me%2525252Fdesktopmodules%2525252Ftosic_sexycontent%2525252Fdist%2525252Flib%2525252Fangular%2525252Fset.min.js%2525253Fsxcver%2525253D8.12.0.29346%2525253A24%2525253A142)%2525250A%25252520%25252520%25252520%25252520at%25252520http%2525253A%2525252F%2525252Fdnndev.me%2525252Fdesktopmodules%2525252Ftosic_sexycontent%2525252Fdist%2525252Flib%2525252Fangular%2525252Fset.min.js%2525253Fsxcver%2525253D8.12.0.29346%2525253A24%2525253A385%2525250A%25252520%25252520%25252520%25252520at%25252520http%2525253A%2525252F%2525252Fdnndev.me%2525252Fdesktopmodules%2525252Ftosic_sexycontent%2525252Fdist%2525252Flib%2525252Fangular%2525252Fset.min.js%2525253Fsxcver%2525253D8.12.0.29346%2525253A39%2525253A471%2525250A%25252520%25252520%25252520%25252520at%25252520q%25252520(http%2525253A%2525252F%2525252Fdnndev.me%2525252Fdesktopmodules%2525252Ftosic_sexycontent%2525252Fdist%2525252Flib%2525252Fangular%2525252Fset.min.js%2525253Fsxcver%2525253D8.12.0.29346%2525253A7%2525253A355)%2525250A%25252520%25252520%25252520%25252520at%25252520g%25252520(http%2525253A%2525252F%2525252Fdnndev.me%2525252Fdesktopmodules%2525252Ftosic_sexycontent%2525252Fdist%2525252Flib%2525252Fangular%2525252Fset.min.js%2525253Fsxcver%2525253D8.12.0.29346%2525253A39%2525253A319)%2525250A%25252520%25252520%25252520%25252520at%25252520http%2525253A%2525252F%2525252Fdnndev.me%2525252Fdesktopmodules%2525252Ftosic_sexycontent%2525252Fdist%2525252Flib%2525252Fangular%2525252Fset.min.js%2525253Fsxcver%2525253D8.12.0.29346%2525253A39%2525253A488%2525250A%25252520%25252520%25252520%25252520at%25252520q%25252520(http%2525253A%2525252F%2525252Fdnndev.me%2525252Fdesktopmodules%2525252Ftosic_sexycontent%2525252Fdist%2525252Flib%2525252Fangular%2525252Fset.min.js%2525253Fsxcver%2525253D8.12.0.29346%2525253A7%2525253A355)%2525250A%25252520%25252520%25252520%25252520at%25252520g%25252520(http%2525253A%2525252F%2525252Fdnndev.me%2525252Fdesktopmodules%2525252Ftosic_sexycontent%2525252Fdist%2525252Flib%2525252Fangular%2525252Fset.min.js%2525253Fsxcver%2525253D8.12.0.29346%2525253A39%2525253A319)%25250A%252520%252520%252520%252520at%252520http%25253A%25252F%25252Fdnndev.me%25252Fdesktopmodules%25252Ftosic_sexycontent%25252Fdist%25252Flib%25252Fangular%25252Fset.min.js%25253Fsxcver%25253D8.12.0.29346%25253A6%25253A412%25250A%252520%252520%252520%252520at%252520http%25253A%25252F%25252Fdnndev.me%25252Fdesktopmodules%25252Ftosic_sexycontent%25252Fdist%25252Flib%25252Fangular%25252Fset.min.js%25253Fsxcver%25253D8.12.0.29346%25253A40%25253A222%25250A%252520%252520%252520%252520at%252520q%252520(http%25253A%25252F%25252Fdnndev.me%25252Fdesktopmodules%25252Ftosic_sexycontent%25252Fdist%25252Flib%25252Fangular%25252Fset.min.js%25253Fsxcver%25253D8.12.0.29346%25253A7%25253A355)%25250A%252520%252520%252520%252520at%252520g%252520(http%25253A%25252F%25252Fdnndev.me%25252Fdesktopmodules%25252Ftosic_sexycontent%25252Fdist%25252Flib%25252Fangular%25252Fset.min.js%25253Fsxcver%25253D8.12.0.29346%25253A39%25253A319)%25250A%252520%252520%252520%252520at%252520http%25253A%25252F%25252Fdnndev.me%25252Fdesktopmodules%25252Ftosic_sexycontent%25252Fdist%25252Flib%25252Fangular%25252Fset.min.js%25253Fsxcver%25253D8.12.0.29346%25253A39%25253A488%25250A%252520%252520%252520%252520at%252520q%252520(http%25253A%25252F%25252Fdnndev.me%25252Fdesktopmodules%25252Ftosic_sexycontent%25252Fdist%25252Flib%25252Fangular%25252Fset.min.js%25253Fsxcver%25253D8.12.0.29346%25253A7%25253A355)%25250A%252520%252520%252520%252520at%252520g%252520(http%25253A%25252F%25252Fdnndev.me%25252Fdesktopmodules%25252Ftosic_sexycontent%25252Fdist%25252Flib%25252Fangular%25252Fset.min.js%25253Fsxcver%25253D8.12.0.29346%25253A39%25253A319)%25250A%252520%252520%252520%252520at%252520http%25253A%25252F%25252Fdnndev.me%25252Fdesktopmodules%25252Ftosic_sexycontent%25252Fdist%25252Flib%25252Fangular%25252Fset.min.js%25253Fsxcver%25253D8.12.0.29346%25253A39%25253A488%25250A%252520%252520%252520%252520at%252520q%252520(http%25253A%25252F%25252Fdnndev.me%25252Fdesktopmodules%25252Ftosic_sexycontent%25252Fdist%25252Flib%25252Fangular%25252Fset.min.js%25253Fsxcver%25253D8.12.0.29346%25253A7%25253A355)%25250A%252520%252520%252520%252520at%252520g%252520(http%25253A%25252F%25252Fdnndev.me%25252Fdesktopmodules%25252Ftosic_sexycontent%25252Fdist%25252Flib%25252Fangular%25252Fset.min.js%25253Fsxcver%25253D8.12.0.29346%25253A39%25253A319)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fdnndev.me%252Fdesktopmodules%252Ftosic_sexycontent%252Fdist%252Flib%252Fangular%252Fset.min.js%253Fsxcver%253D8.12.0.29346%253A6%253A412%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fdnndev.me%252Fdesktopmodules%252Ftosic_sexycontent%252Fdist%252Flib%252Fangular%252Fset.min.js%253Fsxcver%253D8.12.0.29346%253A40%253A222%250A%2520%2520%2520%2520at%2520q%2520(http%253A%252F%252Fdnndev.me%252Fdesktopmodules%252Ftosic_sexycontent%252Fdist%252Flib%252Fangular%252Fset.min.js%253Fsxcver%253D8.12.0.29346%253A7%253A355)%250A%2520%2520%2520%2520at%2520g%2520(http%253A%252F%252Fdnndev.me%252Fdesktopmodules%252Ftosic_sexycontent%252Fdist%252Flib%252Fangular%252Fset.min.js%253Fsxcver%253D8.12.0.29346%253A39%253A319)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fdnndev.me%252Fdesktopmodules%252Ftosic_sexycontent%252Fdist%252Flib%252Fangular%252Fset.min.js%253Fsxcver%253D8.12.0.29346%253A39%253A488%250A%2520%2520%2520%2520at%2520q%2520(http%253A%252F%252Fdnndev.me%252Fdesktopmodules%252Ftosic_sexycontent%252Fdist%252Flib%252Fangular%252Fset.min.js%253Fsxcver%253D8.12.0.29346%253A7%253A355)%250A%2520%2520%2520%2520at%2520g%2520(http%253A%252F%252Fdnndev.me%252Fdesktopmodules%252Ftosic_sexycontent%252Fdist%252Flib%252Fangular%252Fset.min.js%253Fsxcver%253D8.12.0.29346%253A39%253A319)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fdnndev.me%252Fdesktopmodules%252Ftosic_sexycontent%252Fdist%252Flib%252Fangular%252Fset.min.js%253Fsxcver%253D8.12.0.29346%253A39%253A488%250A%2520%2520%2520%2520at%2520q%2520(http%253A%252F%252Fdnndev.me%252Fdesktopmodules%252Ftosic_sexycontent%252Fdist%252Flib%252Fangular%252Fset.min.js%253Fsxcver%253D8.12.0.29346%253A7%253A355)%250A%2520%2520%2520%2520at%2520g%2520(http%253A%252F%252Fdnndev.me%252Fdesktopmodules%252Ftosic_sexycontent%252Fdist%252Flib%252Fangular%252Fset.min.js%253Fsxcver%253D8.12.0.29346%253A39%253A319)%0A%20%20%20%20at%20http%3A%2F%2Fdnndev.me%2Fdesktopmodules%2Ftosic_sexycontent%2Fdist%2Flib%2Fangular%2Fset.min.js%3Fsxcver%3D8.12.0.29346%3A6%3A412%0A%20%20%20%20at%20http%3A%2F%2Fdnndev.me%2Fdesktopmodules%2Ftosic_sexycontent%2Fdist%2Flib%2Fangular%2Fset.min.js%3Fsxcver%3D8.12.0.29346%3A40%3A222%0A%20%20%20%20at%20q%20(http%3A%2F%2Fdnndev.me%2Fdesktopmodules%2Ftosic_sexycontent%2Fdist%2Flib%2Fangular%2Fset.min.js%3Fsxcver%3D8.12.0.29346%3A7%3A355)%0A%20%20%20%20at%20g%20(http%3A%2F%2Fdnndev.me%2Fdesktopmodules%2Ftosic_sexycontent%2Fdist%2Flib%2Fangular%2Fset.min.js%3Fsxcver%3D8.12.0.29346%3A39%3A319)%0A%20%20%20%20at%20http%3A%2F%2Fdnndev.me%2Fdesktopmodules%2Ftosic_sexycontent%2Fdist%2Flib%2Fangular%2Fset.min.js%3Fsxcver%3D8.12.0.29346%3A39%3A488%0A%20%20%20%20at%20q%20(http%3A%2F%2Fdnndev.me%2Fdesktopmodules%2Ftosic_sexycontent%2Fdist%2Flib%2Fangular%2Fset.min.js%3Fsxcver%3D8.12.0.29346%3A7%3A355)%0A%20%20%20%20at%20g%20(http%3A%2F%2Fdnndev.me%2Fdesktopmodules%2Ftosic_sexycontent%2Fdist%2Flib%2Fangular%2Fset.min.js%3Fsxcver%3D8.12.0.29346%3A39%3A319)%0A%20%20%20%20at%20cb%20(http%3A%2F%2Fdnndev.me%2Fdesktopmodules%2Ftosic_sexycontent%2Fdist%2Flib%2Fangular%2Fset.min.js%3Fsxcver%3D8.12.0.29346%3A43%3A336)%0A%20%20%20%20at%20c%20(http%3A%2F%2Fdnndev.me%2Fdesktopmodules%2Ftosic_sexycontent%2Fdist%2Flib%2Fangular%2Fset.min.js%3Fsxcver%3D8.12.0.29346%3A20%3A390)%0A%20%20%20%20at%20Bc%20(http%3A%2F%2Fdnndev.me%2Fdesktopmodules%2Ftosic_sexycontent%2Fdist%2Flib%2Fangular%2Fset.min.js%3Fsxcver%3D8.12.0.29346%3A21%3A179`
```
Error: [$injector:modulerr] http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=DialogHost&p1=Error…ent%2Fdist%2Flib%2Fangular%2Fset.min.js%3Fsxcver%3D8.12.0.29346%3A21%3A179)
    at set.min.js?sxcver=8.12.0.29346:6
    at set.min.js?sxcver=8.12.0.29346:40
    at q (set.min.js?sxcver=8.12.0.29346:7)
    at g (set.min.js?sxcver=8.12.0.29346:39)
    at cb (set.min.js?sxcver=8.12.0.29346:43)
    at c (set.min.js?sxcver=8.12.0.29346:20)
    at Bc (set.min.js?sxcver=8.12.0.29346:21)
    at Object.e.bootstrap (set.min.js?sxcver=8.12.0.29346:418)
    at 2sxc4ng.min.js?sxcver=8.12.0.29346:185
    at b (set.min.js?sxcver=8.12.0.29346:189)
(anonymous) @ 2sxc4ng.min.js?sxcver=8.12.0.29346:188
b @ set.min.js?sxcver=8.12.0.29346:189
Sf @ set.min.js?sxcver=8.12.0.29346:37
d @ set.min.js?sxcver=8.12.0.29346:37
```

**Comment by iJungleboy** [comment]
Note: this was apparently resolved, seems to have been some kind of internal redirection on the specific user installation.
