### ISSUE TITLE
Issues while installing / deinstalling the module

### ISSUE THREAD

**Issue by mcshorty** [2sic/2sxc#1157]
DNN 9.0.2
Module version 08.12.00 

Following issues are found during install and deinstall:

**install**
dependency to /install/config/BindingRedirect.config found

**deinstall**
following db objects are not deleted
- ToSIC_EAV_ChangeLogAdd
- ToSIC_EAV_ChangeLogGet
- ToSIC_EAV_ChangeLogSet
- ToSIC_EAV_DeleteApp
- ToSIC_EAV_LogToTimeline

Thanks

**Comment by iJungleboy** [comment]
I don't understand the install issue. What's this depedency on BindingRedirect.config? I'm not aware of something like this, so I need to know what you mean.

**Comment by mcshorty** [comment]
Regarding the issue "missing BindingRedirect.config":
For security reasons I remove all files from the Install folder and place placeholder.txt inside these folders.

Further informations:
- The "App" module was installed
- The "Content" module was not installed
- No other module (the ones that I use) had a problem with this empty Install folder structure

This was the reason why I assumed that there is a dependency to this file.

**Comment by iJungleboy** [comment]
Just a short note: most of these stored procedures will most likely be removed completely in 2sxc 9.1 or 9.2, so I'll close this issue for now, is it will become irrelevant.
