### ISSUE TITLE
Can't use .icon- prefix in font-icon-picker due to conflicts

### ISSUE THREAD

**Issue by raphir** [2sic/2sxc#1170]
Case 2sic website: linearicons are in use. This font has .icon- as prefix.  Is there a solution worth to be planned?

![font-icon-picker-3](https://cloud.githubusercontent.com/assets/19209321/25806436/6e51972e-3403-11e7-9cd8-f2c018003a1e.png)

![font-icon-picker](https://cloud.githubusercontent.com/assets/19209321/25806369/361993fc-3403-11e7-8409-df8fefebcaaa.png)

![font-icon-picker-2](https://cloud.githubusercontent.com/assets/19209321/25806372/3b8c8ba0-3403-11e7-8fba-311c89b43f35.png)

**Comment by iJungleboy** [comment]
I don't have a quick answer for this. Can you just change your icon-font to use another prefix like "icn-" or something?
