### ISSUE TITLE
IsPublished not accepted during create?

### ISSUE THREAD

**Issue by mryckman** [2sic/2sxc#1173]
I may be using it incorrectly, but it looks like "IsPublished" isn't being accepted during a create operation through the API. Here's the code;

...
            vals.Add("IsPublished", false);
            App.Data.Create("Event", vals);
...

vals is a dictionary and all of the other fields added work - the event saves as expected. The only thing is that the event goes in as published.

**Comment by iJungleboy** [comment]
That's a good question - I'll have to look into it...

**Comment by iJungleboy** [comment]
I have a fix ready in a test-release of 2sxc 9.1 - would you be able to test it if I sent you the beta?

**Comment by mryckman** [comment]
Sorry I was late responding. I can test it. Is it in the 9.1 beta?

**Comment by iJungleboy** [comment]
yes, 9.1 beta

**Comment by iJungleboy** [comment]
We were able to test it, and 9.1 beta still has a bug. will release 9.1 today ,that should work.
