### ISSUE TITLE
Error in App selection "toolbar"

### ISSUE THREAD

**Issue by lucatescari** [2sic/2sxc#1182]
I can't recreate the circumstances under which this happend.
I dragged an App into an empty page, and then this error message appeared:

![image](https://cloud.githubusercontent.com/assets/7703479/25935625/5b27380c-3624-11e7-9118-c6351d97ec95.png)

**Comment by iJungleboy** [comment]
The reason is fairly complex, but it's actually multiple bugs.

The first is that the iframe for "Getting Started" is opened, and trying to load a page on 2sxc.org. 

Then there's an error in that page, causing the yellow bar.

**Comment by iJungleboy** [comment]
Note: I just fixed the error on that gettings-started page, so that's ok. You should now accidentally see getting-started - which is another bug - related to #1168 

Since I fixed the error - and the other problem is already in an issue, I'll close this.
