### ISSUE TITLE
Can't rename Content Type Fields

### ISSUE THREAD

**Issue by lucatescari** [2sic/2sxc#1183]
When I try to rename fields in my Content Type, I get the following error:
![image](https://cloud.githubusercontent.com/assets/7703479/25942474/3d189202-363d-11e7-83d4-95fa83b94646.png)

2sxc 9.00.00 and 9.00.01 (tested on both)
DNN 8.0.4

**Comment by iJungleboy** [comment]
Please always give more information - version of 2sxc, dnn etc.
