### ISSUE TITLE
Insert Content should not show install-app dialog

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#1188]
Situation: I have apps installed, but no content yet. Added a content-block, and it shows me the gettings-started of apps:

![image](https://cloud.githubusercontent.com/assets/5321186/26128832/0f218e58-3a8e-11e7-9298-2e78c964b950.png)

**Comment by christophbuehler** [comment]
Happens only in inner content.
Server API only takes module id (and not cbid) into acccount.

**Comment by iJungleboy** [comment]
modified to put "isContentApp" into api-call...
