### ISSUE TITLE
Unable to select Content Type - v9.01.00

### ISSUE THREAD

**Issue by SteveTeece** [2sic/2sxc#1197]
When attempting to add a new Content module, the new tiles UI shows up, but a content type (Basic Content, Person, etc) cannot be chosen.

![image](https://cloud.githubusercontent.com/assets/9351980/26338168/61ddcc78-3fc1-11e7-8f0d-424344d3665b.png)

**Comment by andyduo** [comment]
+1 for this issue. I have DNN 9.1 and 2sxc 9.1. Clicking on a content type tile seems to do nothing.

**Comment by iJungleboy** [comment]
We can reproduce the bug and already have a fix. Should be released today. 
@andydue We'll still have to fine-tune interactions on DNN 9 + right now as people are upgrading, some modules are in a state they won't be in any more with future inserts. So we're working on it :)
