### ISSUE TITLE
Feature: How to assign permissions to edit per language

### ISSUE THREAD

**Issue by ech01** [2sic/2sxc#1198]
Hello - 

Looking for some instructions on how to setup editing by locale. My default language is english and should only be editable by Administrators. I have translator roles that have page edit rights. The translator roles should only be able to edit their own language. How do I set this up? I created a security rule for a content type and gave the following permissions
en-us: SecurityAccessLevel.Admin 
es-es: SecurityAccessLevel.Edit 
es-mx: SecurityAccessLevel.Edit

Expected: Only admin user roles can edit en-us content
Actual: All translator roles can edit en-us

**Comment by iJungleboy** [comment]
The current version doesn't offer this yet, sorry.

**Comment by ech01** [comment]
Why are there options in 2sxc for setting the rights for each language? 

Also, doesn't this break the DNN security model by allowing editors to edit content on pages they may not have access to?

**Comment by iJungleboy** [comment]
@ech01 what settings are you referring to?

**Comment by ech01** [comment]
When creating permissions on the "data" or "presentation", you can set them for each culture.  

However, it does not work or I am doing it incorrectly.

**Comment by iJungleboy** [comment]
These settings are (currently) relevant only to REST APIs. I like the idea of using them to also manage permissions on the UI, but we actually never thought about this till now :)

**Comment by ech01** [comment]
I have a case where there are multiple translators and multiple translator roles. However, they should not have access to edit other languages content. Is there any way to lock the admin down so they can only copy content from one language to another, and only edit entries in their prescribed locales. It would make sense to follow the DNN pattern here the permission is page based. A translator having edit rights to another localized version is kind of a security backdoor. 
Just bringing this up again in hopes it can be included.

**Comment by iJungleboy** [comment]
Just to be transparent: At the moment this is not on our priorities. It's something we would like to do some time, but since we ourselves don't have a project which really needs this (and therefor helps pay for it), it's not likely to be implemented for another while.

**Comment by ech01** [comment]
We've tried to disable the language tabs via css and js, which is fruitless since the editor is loaded in an iframe. 

This is a security flaw. It is absolutely a back door for editors to edit content on pages where they do not have permission.
