### ISSUE TITLE
Cannot use force-delete on Entitys which are in use in 2sxc 9.1.2

### ISSUE THREAD

**Issue by lucatescari** [2sic/2sxc#1201]
Cannot force-delete entitys which are in use. When trying to use force-delete, the following error appears:

![image](https://cloud.githubusercontent.com/assets/7703479/26624507/5ff4f36a-45f1-11e7-9554-1461109b9eeb.png)

DNN: 8.0.4
2sxc: 09.01.02

**Comment by iJungleboy** [comment]
I just tried a force delete and it worked. Could you maybe give more details / show me the use case?

**Comment by iJungleboy** [comment]
never got feedback, close.
