### ISSUE TITLE
Add functionality for inner content in inner content

### ISSUE THREAD

**Issue by lucatescari** [2sic/2sxc#1202]
If you use the Accordion App in inner content, you cannot add content to the accodion app due it already being in the inner content. This would be inner content in inner content.

**Comment by iJungleboy** [comment]
I believe this is simply not implemented yet. ATM the situation for inner content does this:
1. use the module-context to talk to the server-api
1. use the modules main item to find the field where it attaches the inner-content
1. use the content-block id to save data, and if it generates a new one, attach it to the the correct field in the module-context

Basically what would have to change is that the system would have to also pass in the parent-item (which is often the module-item, but not always), to then update that.

**Comment by iJungleboy** [comment]
I was able to add accordion in accordion in accordion - and then add a content block. So I think this already works as it should. Please re-check your work to be sure that it's not your template which is missing something...

![image](https://cloud.githubusercontent.com/assets/5321186/26754087/0b344440-4874-11e7-9d35-f49b0881b560.png)
