### ISSUE TITLE
Toolbar disappears after adding new item to list

### ISSUE THREAD

**Issue by 2000tl** [2sic/2sxc#1203]
When I add an item to a template which supports lists (e.g. in the 2sic bootstrap content templates, the image max 2, 3 and 4 templates), the 2sxc toolbar (the one for editing the current item) disappears on all items -> When I hover it would not show up anymore.
A page reload fixes this.

**Comment by iJungleboy** [comment]
Please add more information: dnn version and 2sxc version

**Comment by 2000tl** [comment]
DNN 9 / 2sxc 9.1
