### ISSUE TITLE
Buttons not there yet

### ISSUE THREAD

**Issue by Tychodewaard** [2sic/2sxc#1228]
Installed 9.3 pre on DNN 804, using Chrome / Surface pro3

In the versioning section on the bottom right, you'll find that the button is not quite a button yet :-)

![schermopname_ 98](https://user-images.githubusercontent.com/9091997/27984230-381ad1e6-63d0-11e7-9c29-bf1a10015417.png)

**Comment by iJungleboy** [comment]
This seems to be the same issue as #1227 regarding the UI language not correctly reverting to EN. Will close this issue.
