### ISSUE TITLE
Cannot deserialize dialog parameters. Please refresh the editor page.

### ISSUE THREAD

**Issue by nicpitsch** [2sic/2sxc#1231]
**I'm submitting a ...**  
```
- [x] bug report
```

**...about**  
```
- [x] edit experience / UI
```

**Current behavior**
* As you open the *Image Manager* or *Document Manager* for a *Link* content type the (RadEditor) popup window contains the message "Cannot deserialize dialog parameters. Please refresh the editor page." but no functionality.

**Minimal reproduction of the problem with instructions**
* Set a *File Filter* like this: \*.pdf,\*.doc\*,\*.txt

**Solution, workaround**
* Don't use the asterix at the end of the file respectively doc extension (\*.doc instead of \*.doc\*).

**Tested with**
* **2sxc:** 8.12.0, 9.2.0
* **DNN:** 09.01.00, 09.01.01

**Comment by iJungleboy** [comment]
thx. We're about to replace file picking but we'll look into this and see how we'll resolve it, because of this I'm adding a note to #1241 and closing this.
