### ISSUE TITLE
Install: Object reference not set to an instance of an object. (DNN 9.1.1)

### ISSUE THREAD

**Issue by skarpik** [2sic/2sxc#1232]
**I'm submitting a ...**  
```
- [x] bug report => search github for a similar issue before submitting 
- [ ] feature request
- [ ] support request => do not submit here, see https://2sxc.org/en/blog/post/moving-discussions-from-codeplex-to-stack-overflow
- [ ] not sure
```

**...about**  
```
- [ ] edit experience / UI
- [ ] admin experience UI
- [ ] Razor templating
- [ ] JS development
- [ ] Content Types or data management
- [ ] APIs like REST
- [ ] DNN parts
- [X] other / unknown
```

**Current behavior**
Error adding 2SXC App to page:
General Exception - Object reference not set to an instance of an object.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

1) Started with a fresh installation of DNN v9.1.1
2) Installed 2XSC v9.2.0. 
3) Created a new page and added the 2XSC App which did not seem to work and resulted in a General Exception in the Admin Log.

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:f0d53287-105d-4eef-b116-0280b1d8d617
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:hgyysw9pp1hkRAol7pdVLEGnEeE=
Message:Object reference not set to an instance of an object.
StackTrace:
at ToSic.SexyContent.View.InitModuleActions() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\View.ascx.cs:line 160 at ToSic.SexyContent.View.get_ModuleActions() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\View.ascx.cs:line 111
InnerMessage:
InnerStackTrace:
Source:ToSic.SexyContent
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: TURING

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10 version 1703 (64 bit)
IIS 10
SQL Express (version 12.0.5546)

* **2sxc version(s):** 9.X.X  
* **Browser:** [all]
* **DNN:** [9.X.X ] 
* **Language:** [English ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Musth check, could be related to #1240

**Comment by iJungleboy** [comment]
Seems to be duplicate and also just related to DNN 9.1.1. Will close this and continue work on #1240
