### ISSUE TITLE
rad editor creates an error - without the editor the file management doesn't work

### ISSUE THREAD

**Issue by dnastone** [2sic/2sxc#1233]
i get this script error on every dnn installation but when i deinstall the rad editor the file management doesn't work anymore.

![script error](https://user-images.githubusercontent.com/11678580/28260215-45cd9704-6ada-11e7-8053-51d1cb34751d.jpg)

what can i do?

cause the script error stops every other script too at my site.

thanks

best regards

michael

**Comment by iJungleboy** [comment]
Thanks - we're looking into a replacement for this and created a specific task for it as #1241, so will close this.
