### ISSUE TITLE
Entity Relationships Not Saving

### ISSUE THREAD

**Issue by joshgk00** [2sic/2sxc#1235]
**I'm submitting a ...**  
```
- [ x ] bug report => search github for a similar issue before submitting 
- [ ] feature request
- [ ] support request => do not submit here, see https://2sxc.org/en/blog/post/moving-discussions-from-codeplex-to-stack-overflow
- [ ] not sure
```

**...about**  
```
- [ ] edit experience / UI
- [ ] admin experience UI
- [ ] Razor templating
- [ ] JS development
- [ x ] Content Types or data management
- [ ] APIs like REST
- [ ] DNN parts
- [ ] other / unknown
```

**Current behavior**

I have a Entity field type defined for a Content Type. I select the Entity from the list and click Save. The page reloads but when I edit the content type gain the Entity hasn't been saved.

**Expected behavior**

When selecting the entity from the list and clicking save, when editing the content type again, the previously selected entity should already be selected in the list

**Minimal reproduction of the problem with instructions**

Here's a screencast of the issue happening, https://www.screencast.com/t/usmuxAxeJN1R

**What is the motivation / use case for changing the behavior?**

I would like to categorize some content to be able to apply filtering

**Please tell us about your environment:**

Server: Windows 2012 R2, IIS 9, SQL 2016 Express

* **2sxc version(s):** 9.3.0  
* **Browser:** [all | Chrome  59.|
* **DNN:** | 9.1.0 ] 
* **Language:** [any/all | English ]

**Anything you would like to add**
I'm also seeing a 400 error when trying to edit the field that is of the Entity type
https://www.screencast.com/t/0H6lpwP6Wbw

**Comment by michaelcunningham1974** [comment]
I am having a similar problem as well. DNN 9.1.1 SXC 9.3

Couple of things to add : 

1. This happens on number types as well with the same symptoms (Entry saves but ignores numbers and entities, 400 Error editing entity type). 
2. I CAN export the content make the change in XML and re-import and it works.
3. Existing items work until edited
3. This happens on stock Blog app (Categories and Tags) and on a content item containing only 2 fields (string and number)
4. This happens on both old and new items.

**Comment by edmacfly** [comment]
Having the exact same issue with my development and live sites, both on version 9.1.1 of DNN and 9.3 of 2SXC. Has broken my modified version of the demo Blog app - unable to add new articles while the issue with Entity datatypes exists. Cannot remove the data types from the content field types either as a desperate attempt to get around this issue.

**Comment by iJungleboy** [comment]
thx! will look into this the next few days.

**Comment by iJungleboy** [comment]
Can reproduce - will prioritize.

**Comment by edmacfly** [comment]
Entity relationships are now saving correctly again which is great, but this has potentially introduced a new issue. I'm not having any luck running the stock Blog App or my modified version of it using the new release. Following error message displaying when I try to run the Blog App:

`Error: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference at CallSite.Target(Closure , CallSite , Object , String ) at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1) at ASP._Page_Portals_0_2sxc_Blog_App__list_item_cshtml.Execute() in c:\Websites\dnndev.me\Portals\0\2sxc\Blog App\_list-item.cshtml:line 18 at System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) at System.Web.WebPages.WebPageBase.<>c__DisplayClass7.<RenderPageCore>b__6(TextWriter writer) at System.Web.WebPages.WebPageBase.Write(HelperResult result) at ASP._Page_Portals_0_2sxc_Blog_App__1_Main_blog_view_cshtml.Execute() in c:\Websites\dnndev.me\Portals\0\2sxc\Blog App\_1 Main blog view.cshtml:line 48 at System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) at ToSic.SexyContent.Engines.RazorEngine.RenderTemplate() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 75 at ToSic.SexyContent.Engines.EngineBase.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Engines\EngineBase.cs:line 87 at ToSic.SexyContent.SxcInstance.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\SxcInstance.cs:line 204`

Possibly related to issue #1242 as well as I am also unable to delete the Blog data items.

**Comment by iJungleboy** [comment]
@edmacfly we'll work on #1242 asap. 

Regarding your other issue, It's probably a bug in your template. could you post most of _list-item.cshtml and mark line 18 - as that is the line that "blows up"?

**Comment by edmacfly** [comment]
Thanks for the prompt reply. The issue I'm experiencing occurs with your Blog App, in it's unedited form. It loads correctly when I am not in edit mode / logged in but the error persists otherwise.

Line 18 is as follows: `<h2>@post.Title</h2>` 

Whole file below:

'@{	
	var lib = CreateInstance("_library.cshtml"); 
	var post = PageData["Post"];
    var author = (post.Author.Count > 0) ? post.Author[0] : lib.unknownAuthor;
}
    <hr>
    <article class="app-blog-item">
	        <div class="app-blog-col1 sc-element">
		    	@Edit.Toolbar(post, toolbar: new { 
                    entityId = post.EntityId, 
                    entityGuid = post.EntityGuid, 
                    entityTitle = post.EntityTitle }
                )
		
		
            <a href="@Link.To(parameters: "post=" + post.UrlKey)" title="@post.Title" class="app-blog-link">
                <img class="app-blog-person-mobile" src="@author.Image.ToLower()?w=40&amp;h=40&amp;mode=crop&amp;scale=both" alt="@author.FullName" />
                <h2>@post.Title</h2>
                <time pubdate datetime='@post.PublicationMoment.ToString("d")'>@post.PublicationMoment.ToString("d")</time>
                @if(!String.IsNullOrEmpty(post.Image)){
                     <div style="text-align:center; padding-bottom:8px;">
					    <img @Html.Raw(post.ImageSquare != true ? "style='width:100%;'" : "" ) class="app-blog-article-img" src="@post.Image.ToLower()?w=790&amp;h=300&amp;mode=max&amp;scale=both" alt="@post.Title" />
                     </div>          
                }
                <div class="Normal">
					@Html.Raw(post.Teaser)
                </div>
            </a>
            <div class="app-blog-categories">
                <strong> @(post.Categories.Count > 1 ? @App.Resources.Categories : @App.Resources.Category): </strong>
                @{
                        var categoryList = (post.Categories as IEnumerable<dynamic>)
                            .Select(cat => "<a href='" + Link.To(parameters: "category=" + cat.Key) + "' title='" + cat.Name + "'>" + cat.Name + "</a>").ToArray(); 
                }
                @Html.Raw(string.Join(", ", categoryList))
          </div>
        </div>
        <div class="app-blog-col2">
            <div class="app-blog-person">
                <a href="@Link.To(parameters: "author=" + author.FullName)">
                    <img src="@author.Image.ToLower()?w=64&amp;h=65&amp;mode=crop&amp;scale=both" alt="@author.FullName" />
                    <h4>@author.FullName</h4>
                </a>
            </div>
            <hr />
            <div class="app-blog-tags">
                <strong> @(post.Tags.Count > 1 ? @App.Resources.Tags : @App.Resources.Tag): </strong>
                @{
                        var tagsList = (post.Tags as IEnumerable<dynamic>)
                            .Select(tag => "<a href='" + Link.To(parameters: "tag=" + tag.Tag) + "' title='" + tag.Name + "'>" + tag.Name + "</a>").ToArray(); 
                }
                @Html.Raw(string.Join(", ", tagsList))
            </div>
        </div>
    </article>'

**Comment by iJungleboy** [comment]
my guess: you have some (faulty) demo- or unpublished data which the template only receives when logged in - and that's where it breaks. could you check that? for example by commenting out most of the template so you stop getting errors, then adding some test-code to check what's in the variable.

**Comment by edmacfly** [comment]
Okay, will give that a go and report back. Thanks again.

**Comment by edmacfly** [comment]
Thanks for all the help with this. I removed my previous news post data items and added them all back and whatever was going wrong before seems to have been sorted. Thanks again. and sorry if my solution isn't very helpful!
