### ISSUE TITLE
Can't connect to the dialog

### ISSUE THREAD

**Issue by SamuelHadsall** [2sic/2sxc#1236]
**I'm submitting a ...** 
[x ] bug report => search github for a similar issue before submitting 
[ ] feature request
[ ] support request => do not submit here, see https://2sxc.org/en/blog/post/moving-discussions-from-codeplex-to-stack-overflow
[ ] not sure

**...about** 
[ ] edit experience / UI
[ ] admin experience UI
[ ] Razor templating
[ ] JS development
[x ] Content Types or data management
[ ] APIs like REST
[ ] DNN parts
[ ] other / unknown

**Current behavior**
When clicking on the image Manager I some times get a Alert window that specifies that Telerik is not installed since I am running a new version of DNN8. However, I do have Telerik installed and I have verified that the DLL's are in the Bin folder. I am also getting a Cross Domain error when trying to access the file manager popup. I actually upgraded from 2sic module 8.1 to 9.2 and the problem still exists

**Expected behavior**
When Clicking on the image Manager It should popup a Image Manager Modal, to select images from.
![imagemanager](https://user-images.githubusercontent.com/6413981/28419718-8f0d3224-6d25-11e7-9634-2ea00d49c177.jpg)

**Minimal reproduction of the problem with instructions**
From a Data type edit modal, click on Adam Image Manager Dropdown and select Image Manager.
![adamimagemanager](https://user-images.githubusercontent.com/6413981/28418985-500a3b6e-6d23-11e7-95c0-43df123b75eb.jpg)

When clicking on the Image Manager Link, I get redirected back to the home page with a failure on 'connectBridge', and Uncaught DomException (cross-origin frame).
![cross-origin-error](https://user-images.githubusercontent.com/6413981/28419123-b6f77a26-6d23-11e7-90ed-10629dfa84e9.jpg)

**Please tell us about your environment:**
Operating System: Windows 10
IDE: N/A
Package Manager: N/a
HTTP Server: IIS 8

* **2sxc version(s):** 9.2.0
* **Browser:** [all]
* **DNN:** [7.4.2] 
* **Language:** [English ]

**Comment by redapollos** [comment]
The above example is from DNN version 7.4.2. The behavior is actually that the modal is loading the current page and the "w" variable in the example above is null because the page has been reloaded and doesn't appear to have scope loaded anymore.  

Also, the PagePicker from the line below is also loading the page into the iframe, but the base page is being loaded as well, though it doesn't freeze the page like the image manager does.

**Comment by iJungleboy** [comment]
Thanks! We're about to provide a new file picker #1241 which will eliminate telerik and also resolve this issue, so I'll close this for now.
