### ISSUE TITLE
IE 11: Icons not displayed properly

### ISSUE THREAD

**Issue by d-trattner** [2sic/2sxc#1246]
**I'm submitting a ...** 
```
- [x] bug report => search github for a similar issue before submitting 
```

**...about**  
```
- [x] edit experience / UI
- [x] admin experience UI
```

**Current behavior**
Icons not displayed properly:
![grafik](https://user-images.githubusercontent.com/27424165/29119651-539131cc-7d07-11e7-8bbb-39ac6dac65aa.png)

**Expected behavior**
Icon displayed correctly

**Minimal reproduction of the problem with instructions**
Install 2sxc  v09.03.00-pre3 on DNN 9.1.1
Add array find polyfill to the skin: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/find
This is to prevent modules.find error.
Installation has to be completed when adding the first app.
After that, you can see the first icon as chinese symbol.

**What is the motivation / use case for changing the behavior?**
Having icons

**Please tell us about your environment:**
DNN 8.x / 9.1.1
2sxc v09.03.00-pre2
IIS 8.5
.NET 4.5.2
SQL Server 2014

* **2sxc version(s):** 9.1.1  
* **Browser:** [IE 11]
* **DNN:** [8.0.3 | 9.1.1 ] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**
Has to do with IE, works in chrome

**Comment by d-trattner** [comment]
Update:
![grafik](https://user-images.githubusercontent.com/27424165/29126243-0d0f81ec-7d1e-11e7-8cae-4bd471e9d35b.png)
Its working local in IE11, could really be mime-types issues

**Comment by iJungleboy** [comment]
In this case it's a server-setting - your server is sending the wrong mime-type for certain font files. I'll close this issue in this case. thx!

**Comment by d-trattner** [comment]
I tried these mime-types:
https://github.com/EnlightenAgency/Server-Setup-MIME-Types-Headers/blob/master/font-mimetypes.txt
Still no success.

I'm trying the following recommondations now to find a solution:

https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#im-hosting-fonts-on-my-server-and-icons-dont-show-up

https://github.com/FortAwesome/Font-Awesome/issues/3286

**Comment by iJungleboy** [comment]
to be on the safe side, I would watch your traffic using fiddler - check the one that works, and compare it to the one that doesn't work - then adjust the headers. my guess is that your woff or woff2 is missing a setting.

**Comment by d-trattner** [comment]
Just for documentation, IE does not request any font.
[fiddler_chrome.txt](https://github.com/2sic/2sxc/files/1212059/fiddler_chrome.txt)
[fiddler_ie11.txt](https://github.com/2sic/2sxc/files/1212058/fiddler_ie11.txt)

I tried made a test folder in my dnn installation and tried different things...
- removed pragma, cache-control and expires headers in web.config
- removed version control in url(font.woff?...)
[test.zip](https://github.com/2sic/2sxc/files/1212070/test.zip)

IE - the busykeeper :)

**Comment by d-trattner** [comment]
Finally.. you never believe me, it had nothing to do with any incompatibility or IIS.
Issue was caused here:
![grafik](https://user-images.githubusercontent.com/27424165/29160119-52531ea6-7db1-11e7-9770-b310db0b3b8e.png)

**Comment by iJungleboy** [comment]
this is pretty crazy - and thanks for the info :)
