### ISSUE TITLE
Cannot save or update fields with a number type

### ISSUE THREAD

**Issue by michaelcunningham1974** [2sic/2sxc#1249]
**I'm submitting a ...**  
```
- [x] bug report => search github for a similar issue before submitting 

- [x] admin experience UI
- [x] Content Types or data management

```

**Current behavior**
Cannot save or update fields with a number type either in content or management screens. 

Saving works for all fields except of number type and no error is logged on server or js console but number field is not retained after save

This happens on all entities containing number fields  and also when editing the properties of a number field to set defaults/min/max values.

If set to be required the field does pass form validation but still does not save.

**Expected behavior**
Number field should save properly with other fields.

**Minimal reproduction of the problem with instructions**

Create a new data type with 2 fields no view is needed
MyTitle [Text]
MyNumber [Number]

Attempt to set default value or min/max value to field definition:
Text and other types are retained.
Number based settings are not retained.

Attempt to add a new entity (from admin) .
MyTitle - Saves
MyNumber - Does Not

**What is the motivation / use case for changing the behavior?**
To make all entity types save properly,

**Please tell us about your environment:**

Server 2008R2, IIS7

* **2sxc version(s):** 9.3.B 1da386b 

* **Browser:** [all 

* **DNN:**  9.1.1 ] 
* **Language:**

 [any/all | English

**Anything you would like to add**
Originally I had assumed that this was related to #1235 Entity Relationships Not Saving as the issue was similar in nature but the newest patch fixed that issue without correcting this one.

**Comment by iJungleboy** [comment]
thanks! will prioritize and try to fix within 48h

**Comment by michaelcunningham1974** [comment]
Thanks! You guys do a great job making the development process transparent.

**Comment by iJungleboy** [comment]
I can reproduce the issue.
