### ISSUE TITLE
IE 11: 'webpackJsonp' is undefined, inline.bundle loading slower than polyfill - when in IE Dev Mode

### ISSUE THREAD

**Issue by d-trattner** [2sic/2sxc#1251]
**I'm submitting a ...**  
```
- [x] bug report => search github for a similar issue before submitting 
```

**...about**   
```
- [x] edit experience / UI
- [x] admin experience UI
```

**Current behavior**
Adding a new app not possible

**Expected behavior**
Sucessfull adding an app

**Minimal reproduction of the problem with instructions**
'webpackJsonp' is undefined, when clicking the "new content" icon
![grafik](https://user-images.githubusercontent.com/27424165/29174388-776e2296-7de6-11e7-999e-7fc539174c1e.png)
Reason could be, that inline.bundle.js, where webpackJsonp is defined, is loading slower than polyfills.bundle.js

Fiddler:
![grafik](https://user-images.githubusercontent.com/27424165/29175631-d6f54048-7de9-11e7-8422-b76778d67ada.png)

**What is the motivation / use case for changing the behavior?**
Getting 2sxc working on IE11

**Please tell us about your environment:**
DNN 8.x / 9.1.1
2sxc v09.03.00
IIS 8.5
.NET 4.5.2
SQL Server 2014

* **2sxc version(s):** 9.3.0
* **Browser:** [ IE11 ]
* **DNN:** [ 9.1.1 ] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
thx! we'll look into it

**Comment by d-trattner** [comment]
Update:
It only happens, when developer tool are opened, they seem to interfere... o_O

**Comment by iJungleboy** [comment]
So is it correct, that actually normal behaviour works, you just run into problems with the dev-toolbar enabled on IE?

**Comment by d-trattner** [comment]
Exactly

Am 11.08.2017 18:13 schrieb "iJungleboy" <notifications@github.com>:

So is it correct, that actually normal behaviour works, you just run into
problems with the dev-toolbar enabled on IE?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/2sic/2sxc/issues/1251#issuecomment-321855250>, or mute
the thread

**Comment by iJungleboy** [comment]
As you know IE11 is not on our core focus, but of course we want to ensure people can work with it. In this case, people _can_ work, but if issues arise you'll have difficulties reporting these issues. 
We'll look into it but won't prioritize this.

**Comment by d-trattner** [comment]
I absolutely understand, I will see what I can find out, and test how it
would impact my work. I already installed my apps from previous dnn and
2sxc versions and they seem to work, so as long I can install them, should
be ok.
In the meantime, thank you alot.

Am 12.08.2017 13:38 schrieb "iJungleboy" <notifications@github.com>:

**Comment by iJungleboy** [comment]
Question: does the bug prevent you from actually debugging, or is it just an annoying message which feels like something is broken, but everything works?

**Comment by d-trattner** [comment]
At that time, the bug prevented from debugging. I went on and used chrome
for further testing Angular (4) integration.
I'm currently on vacation and could test the latest version in about 2
weeks.
Greetings from France :)

Am 08.09.2017 14:00 schrieb "iJungleboy" <notifications@github.com>:

Question: does the bug prevent you from actually debugging, or is it just
an annoying message which feels like something is broken, but everything
works?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/2sic/2sxc/issues/1251#issuecomment-328084738>, or mute
the thread

**Comment by d-trattner** [comment]
Now I can give feedback..

The bug still occurs with the latest version (09.05.01) when...
- Clicking on the "new content" glass icon
- For an already existing app, clicking Pencil -> Change Template/Layout

Apps have to be added and/or the template changed without opened devtools.

I would not say, that it prevents debugging the apps itself.. just a thing to keep in the back of the head..

**Comment by iJungleboy** [comment]
ok thx!
