### ISSUE TITLE
Numbers cannot be edited

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#1258]
**I'm submitting a ...**  

- [x] bug report => search github for a similar issue before submitting 

**...about** 

- [x] edit experience / UI

**Current behavior** 

* add a number field 
* edit entity and set a number
* save

The number is not saved.

**Expected behavior**
The number is saved

* **2sxc version(s):** 9.3.3. and 9.4.0

* **DNN:** [ 8.X| 9.X ] 
* **Language:** [any]

**Anything you would like to add**

Nope

**Comment by iJungleboy** [comment]
most likely related to #1249 - which should be fixed. Is it a multi-language setup or single language?

**Comment by SCullman** [comment]
Single language. 
It is still broken in 9.4.0 pre

**Comment by iJungleboy** [comment]
do you get errors, or does it just keep the old number, or does it actually reset the number?

**Comment by iJungleboy** [comment]
Note that I can't reproduce it, as in my setup the number is saved and updated. Do you have more details which could help figure it out?

**Comment by SCullman** [comment]
It wipes out the number.

I am now at home and tried to reproduce on a different machine. Fresh dnn 9.1.1, no content.
Installed 2sxc 9.4.0, tested and numbers are working.
Uninstalled 2sxc9.4.0 and installed 2sxc9.3.3 - still working as expected.
Weird!

**Comment by SCullman** [comment]
Installed 9.4.0 on production, issue is fixed. Strange!

**Comment by iJungleboy** [comment]
cool! glad to hear that

**Comment by SCullman** [comment]
Thank you for your support, very much appreciated
