### ISSUE TITLE
cannot save data at with the accordion app since version 9.4.1

### ISSUE THREAD

**Issue by dnastone** [2sic/2sxc#1264]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] other / unknown

**Current behavior**

it depends to the accordion app. since i installed the version 9.4.1 i can't save content to an app which depends to an accordion.

**Expected behavior**

i create a new accordion entry and then put a new app to the content.
i use the content only text from your bootsraps templates. i see the demo content, but when i create a content and save it i see the demo entry and not the saved data.
i have no error message at the event protocoll.
i testet it at a local installation too and the same happend there too.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

the latest dnn version and the latest 2sexy app version + accordion app
language german
browser latest google chrome

* **2sxc version(s):** 9.X.X  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [all | 7.4.2 | 8.X.X | 9.X.X ] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
I can reproduce it - sorry about this. Will look into it as quickly as possible...

**Comment by dnastone** [comment]
thanks a lot

**Comment by iJungleboy** [comment]
Current analysis suggests, that it's a problem with IDs being passed from the edit-buttons to the GUI, I believe it's picking up the wrong ID causing invalid assignments. So the content is created but not "placed" in the right spot. Working on it.

**Comment by dnastone** [comment]
io found a other problem. i don't know of this is the same problem.
at your boostrap templates the google maps template doesn't render anymore since 9.4.1

**Comment by iJungleboy** [comment]
Please open a separate issue for the google-maps question, and please check first if it's a 2sxc issue or a maps-issue. thx

**Comment by bastrou** [comment]
I have a similar error with accordion app. I cannot save anything in the content place of the app (like text). The error occurs is 

Had an error talking to the server (status 400)
Message: Bad Request
Detail: The template with id 1646 does not exist

version of app is 9.6 and DNN version is 9.01.01

By the way great project Thank you

**Comment by iJungleboy** [comment]
@bastrou please provide more details and open a new issue. thx
