### ISSUE TITLE
All 2SXC Modules are Failing to appear (Data is missing error)

### ISSUE THREAD

**Issue by TwoHeadsBrewing** [2sic/2sxc#1266]
I'm submitting a ...

- [x] bug report => search github for a similar issue before submitting 
- [x] DNN parts
- [ ] other / unknown

**Current behavior**
On only one portal on my server, suddenly no modules are showing data and throwing the following error:
"Error: System.Exception: Data is missing - usually when a site is copied but the content / apps have not been imported yet - check 2sxc.org/help?tag=export-import"

This site has been up and running for quite some time with no problems, and I see that there is data for this site in the database.  When going to "Manage Apps" there is only "Content" displaying, but no Data or Views are appearing.

**Expected behavior**

**Log Error Details**
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:f2ee3647-cbe6-4cd5-a062-247321643ac7
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:NHvxTo1pFicqflQNAP/+hQ==
Message:Data is missing - usually when a site is copied but the content / apps have not been imported yet - check 2sxc.org/help?tag=export-import
StackTrace:
InnerMessage:
InnerStackTrace:
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: WIN-VGD4FFTN042

**Please tell us about your environment:**

* **2sxc version(s):** 8.4.2 
* **Browser:** [all]
* **DNN:** [ 8.X.X | 9.X.X ] 
* **Language:** [any/all ]

**Comment by TwoHeadsBrewing** [comment]
Additional info:  When looking into the Zones table, I show two records for this portal (ZoneID 84 and 149).  

There are no records for Zone 149 which explains why I'd get this error.  All of the data that should be displaying is for ZoneID 84.  But the query string on the page for the modules is referencing Zone ID 149.

**Comment by iJungleboy** [comment]
If it is what you describe, I believe somehow the portal setting with the ZoneId got lost. I've never heard of this before, but go to the Portal-Settings table in DNN and update the row with the ZoneId back to 84, and you should be good to go.

**Comment by TwoHeadsBrewing** [comment]
Now all of the portals on this server are showing the error:
"A critical error has occurred. Please check the Event Viewer for further details."

No DNN login screen or anything is showing so I'm unable to view the Event Viewer.

**Comment by iJungleboy** [comment]
Ok - I believe remembering some kind of caching issue which made 2sxc not see the existing portal-id, and generating a new one. I think your best bet is to update to 8.12

**Comment by TwoHeadsBrewing** [comment]
Is there a way to update 2sxc to the new version when I'm unable to load any page on any site?

**Comment by iJungleboy** [comment]
basically any admin-page won't have 2sxc components, so you shouldn't run into errors there. no if you access /admin you should be fine, or something like /Host/Extensions/

**Comment by TwoHeadsBrewing** [comment]
I've attempted to get admin and host pages to load, but I get the same error so it must be something on the DNN side.  I'm going to look at the change logs and rebuild manually from a previous backup just so sites are up and running.   I'm hoping you can help me with one more question:  in what table to do I find the association of the Values and the ModuleID?

**Comment by iJungleboy** [comment]
Here's more documentation regarding module > entity mapping https://github.com/2sic/2sxc/wiki/Concept-Dnn-Module
