### ISSUE TITLE
Bug: Decimal numbers lose the comma because of culture encoding - google maps from bootstrap template brings an error

### ISSUE THREAD

**Issue by dnastone** [2sic/2sxc#1267]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] Razor templating

**Current behavior**

i installed the content bootstrap template version 2.3.0 and 2sexy version 9.4.1 (with dnn 9.1.1)
since version 9.4.1 the google maps template brings an error (adress with map):

Error: System.OverflowException: Der Wert für einen Int32 war zu groß oder zu klein. bei System.Decimal.FCallToInt32(Decimal d) bei CallSite.Target(Closure , CallSite , Type , Object ) bei System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1) bei ASP._Page_Portals_0_2sxc_Bootstrap__Location___Address_with_Map_50_50_cshtml.Execute() in c:\inetpub\wwwroot\dnn9\Portals\0\2sxc\Bootstrap\_Location - Address with Map 50-50.cshtml:Zeile 37. bei System.Web.WebPages.WebPageBase.ExecutePageHierarchy() bei System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) bei ToSic.SexyContent.Engines.RazorEngine.Render(TextWriter writer) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:Zeile 64. bei ToSic.SexyContent.Engines.RazorEngine.RenderTemplate() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:Zeile 74. bei ToSic.SexyContent.Engines.EngineBase.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Engines\EngineBase.cs:Zeile 87. bei ToSic.SexyContent.SxcInstance.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\SxcInstance.cs:Zeile 204.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **2sxc version(s):** 9.X.X  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [all | 7.4.2 | 8.X.X | 9.X.X ] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Could you look a bit deeper to see if it could be a culture issue - as your error is in german? maybe it's a number conversion (comma, dot) or something?

**Comment by lucatescari** [comment]
I could reproduce this.
The value doesn't get saved as number into the database, instead it gets saved with a comma (,) instead of a point (.)

**Comment by iJungleboy** [comment]
It seems to be a culture issue - the data is stored with a comma in certain DE environments, and when reading it from the DB, it just drops the comma, resulting in very large numbers

**Comment by iJungleboy** [comment]
Found and fixed - was missing a System.Globalization.CultureInfo.InvariantCulture when serializing.

**Comment by iJungleboy** [comment]
Note that you may still have issues on the demo-data, if the app was imported with the bug in 2sxc - so the DB contains numbers with a comma. Just go to app-admin and re-edit the records (move the pin a bit) and this will fix the broken data.

**Comment by iJungleboy** [comment]
Note: will release tomorrow when also fixing another important bug.
