### ISSUE TITLE
Save inner content block not working

### ISSUE THREAD

**Issue by marcingarbarczyk** [2sic/2sxc#1269]
**I'm submitting a ...**  
[x] bug report
**...about**
[x] Content Types or data management

**Current behavior**
I have Content Item with Content Inner field. When I add Content Inner my options are not saving. Still see demo values for this Inner Content.

**Expected behavior**
After "save" click should be my data in this Inner Content Block, not demo data.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **2sxc version(s):** 9.04.02  
* **Browser:** [all]
* **DNN:** 8.0.4
* **Language:** [any/all]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Thanks - I think this is related to #1264  - it has our highest priority.
