### ISSUE TITLE
Number field type is not saving value

### ISSUE THREAD

**Issue by marcingarbarczyk** [2sic/2sxc#1272]
**I'm submitting a ...**  
[x] bug report 

**...about**   
[x] Content Types or data management

**Current behavior**
When I use Number field type value is not saved.

**Expected behavior**
When I set Number field value module should remember my decision.

**Minimal reproduction of the problem with instructions**
Create new content type and add Number field type.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **2sxc version(s):** 9.4.3  
* **Browser:** [all]
* **DNN:** | 8.0.4 |
* **Language:** [any/all]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
related to #1271 - will prioritize asap.
