### ISSUE TITLE
Adjusted Row Count won't get saved to database

### ISSUE THREAD

**Issue by raphir** [2sic/2sxc#1273]
**I'm submitting a ...**  
[x] bug report 

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**

Row Count won't get saved to database

![saving_error](https://user-images.githubusercontent.com/19209321/29827797-42ec43a0-8cdb-11e7-86d1-1c85093a2f6e.png)

**Expected behavior**
Save row count to database

**What is the motivation / use case for changing the behavior?**
Make multi-line headings

* **2sxc version(s):** 9.4.3  
** Tested: Works in 9.4.1 with DNN 9.X.X **
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [7.4.2] 
* **Language:** [any/all | English | German | other ]

**Comment by iJungleboy** [comment]
I believe this is related to #1272 could you check if this is the same issue?

**Comment by iJungleboy** [comment]
if it is the same bug, pls try the release of today - https://github.com/2sic/2sxc/releases/tag/v09.04.03-pre3
I'll close the issue, as it's 99% that case.
