### ISSUE TITLE
Feature Request: Add existing item directly through toolbar

### ISSUE THREAD

**Issue by jncraig** [2sic/2sxc#1278]
Feature request:  I would like to be able to add an existing content item to a list.

You can add a new item, but you can't directly add an existing items.  This will greatly simplify the process of building out a list.

There is also the List Management item, which allows you to rearrange a list or edit an item.  It would be nice to be able  to add from this list, or do a replace instead of an edit.

Thanks.

_From iJungleboy:_
- [ ] an icon, which doesn't confuse people and doesn't get confused with the already existing two different add-buttons
- [ ] decision where to put it - I think the logical place would be the second set of buttons
- [ ] code changes to the toolbar system - ca. 0.5-1h
- [ ] code changes to the replace-dialog - ca. 0.5-1h
- [ ] code changes to the web api - ca. 1h

**Comment by iJungleboy** [comment]
I understand the idea. Here's what we would need

- [ ] an icon, which doesn't confuse people and doesn't get confused with the already existing two different add-buttons
- [ ] decision where to put it - I think the logical place would be the second set of buttons
- [ ] code changes to the toolbar system - ca. 1h
- [ ] code changes to the replace-dialog - ca. 1h
- [ ] code changes to the web api - ca. 1h

**Comment by jncraig** [comment]
I would be happy just to have this added on the "list management" popup,
along with a delete function.  Right now there is only an edit icon.  You
could extend that to include add, add existing, and delete.

Yes, I do understand that messy issue of many icons and not confusing
people.  It took we quite a while to realize that the two add icons on the
toolbar actually were different.

**Comment by eXistenZe** [comment]
Sorry to bump other people's thread, but I would prefer an "add existing item" than a replace (if too many buttons is an issue).

Never actually needed to replace anything, but it's frequent to need to add. Plus, it's very fast to add one item and delete another if needed, but creating one, replacing it and deleting the dummy in admin is tedious.

Just an opinion. Thanks.

**Comment by iJungleboy** [comment]
We've got it ;)

**Comment by iJungleboy** [comment]
All done, hope you love it. Will be in 11.01

**Comment by iJungleboy** [comment]
This is what the new button looks like for now:
![image](https://user-images.githubusercontent.com/5321186/81345812-6f5df700-90b9-11ea-88d8-f3bab05ce83c.png)

**Comment by jncraig** [comment]
Perfect.  You guys just do better and better!

**Comment by perezandres** [comment]
Is this feature correctly working? When I press that button (version 11.2.0) I see the Replace Content Item dialog and, in fact, it replaces item.

**Comment by eXistenZe** [comment]
Me too. But the whole "content" management needs a new screen to manage.
Add and remove data could be a simple drag and drop operation (data on the
left, content on the right).
