### ISSUE TITLE
AJAX issue: New element shows demo content instead new content before refresh

### ISSUE THREAD

**Issue by marcingarbarczyk** [2sic/2sxc#1279]
**I'm submitting a ...**  
[x] bug report

**...about**   
[x] edit experience / UI
[x] Content Types or data management

**Current behavior**

When I put new element to page and add my content instead demo page does not refresh.

**Expected behavior**

I should see my new content before refresh page.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **2sxc version(s):** 9.4.3  
* **Browser:** [all]
* **DNN:** [all 8.0.4] 
* **Language:** [any/all]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Thanks. Could you provide a few more details: when you say "add my content" are you using the replace-feature, or just doing standard +button and save?

**Comment by marcingarbarczyk** [comment]
Thank you for your response Sir. These steps:
1. Add module Content
2. Choose my content type
3. Edit content
4. Fill fields and click save button
5. Content not refreshed
6. CTRL + F5 content refreshed

**Comment by iJungleboy** [comment]
I think I can reproduce - something seems to fail on the ajax call...

**Comment by iJungleboy** [comment]
found issue - will create new release tomorrow.
