### ISSUE TITLE
2sxc Translation Problem

### ISSUE THREAD

**Issue by websystemsoftware** [2sic/2sxc#1281]
I want to Translate my Website from German to English in 2sxc
i go to translate (unlink) and set the English Text
when i want to save after i become always the following Error!
  
Had an Error talking to the Server (status 400).
Message: Bad Request
Detail: found languages in save which are not available in environment-
used has 1 target has 0 used-list: 'en-us'

if u are an advanced user you can learn more about what went wrong-
discover how on 2sx.org/help?=debug 

**I'm submitting a ...** 
[x] bug report => search github for a similar issue before submitting 

**...about**  
[x] edit experience / UI
[x] admin experience UI

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
WinServer 2012, DNN 9.1.1, IIS 8.5

* **2sxc version(s):** 9.04.03
* **Browser:** [all]
* **DNN:** [9.1.1 ] 
* **Language:** [any/all]

**Comment by websystemsoftware** [comment]
i see now i must activate the languages also in 2sxc
Thanks

**Comment by iJungleboy** [comment]
no problem :)

**Comment by Tychodewaard** [comment]
For others as well: 
configuration app - global - activate languages
