### ISSUE TITLE
Number field outputting with commas instead of dots

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1282]
I'm submitting a bug report / not sure about edit experience / UI / admin experience UI.

I created a form with some number fields which I need to do some calculations with.
The problem is that the numbers are input with dots (number fields does not even allow commas), but output with commas in my view. When I try to pass the @Content.number to a js calculation, it will not work since js needs numbers with dots. Since I cannot add a @Content.field.replace (it would conflict with the 2sxc field name), I am unable to fix this issue.

I can guess it has something to do with localization / culture, but I cannot change my DNN settings just to fix this issue (it would create a lot others).

DNN 9.1.1
2sxc 9.04.01

**Comment by eXistenZe** [comment]
Correction: even if I set app culture to en-US. this problem persists.

**Comment by iJungleboy** [comment]
This is a browser-culture issue - the web server adapts to your browser settings, because it wants to show you numbers in your format. To get them unformatted, you would either have to work with other ToString() commands in dotnet, or use the same trick we use in the google-maps template: https://github.com/2sic/2sxc-content-bootstrap3/blob/master/_Location%20-%20Full%20Size%20Map.cshtml#L33-L38

**Comment by eXistenZe** [comment]
Never thought this could be a client side issue.
Thanks a lot.

**Comment by eXistenZe** [comment]
Got another issue related to this problem.
I can replace commas with dots for JS use, but then I cannot reverse the effect. 
When I try to send a js numeric var with dots into the rest api (post), with will ignore the dot and store the number without it (like "3.14" -> "314").
Seems like an impossible issue (js needs dots, so I cannot replace it without converting to string, and if I convert it to string, rest api will complain about storing a string in a numeric field).

**Comment by iJungleboy** [comment]
@eXistenZe please research the issue to be sure it's a 2sxc thing and that we can reproduce it, then open a new issue for that

**Comment by eXistenZe** [comment]
Can't say, since you may not be able to reproduce a (server?) culture with
commas.
If I send a decimal var with dot (js) to the API to a numeric field, it
will be stored the digits without the dot or comma.
