### ISSUE TITLE
[Feature request] - Search box and sorting capabilities

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1283]
I'm submitting a feature request about edit experience / UI.

It would be very nice to be able to simply add a search box the way FnL does to restrict the content shown in a table list.

Also, automated sorting options would be very nice (sorting the table/list by clicking on the header).

Best regards,
João

**Comment by iJungleboy** [comment]
searching is already built in in the admin view - so that's done. 

Sorting ist too - so all completed :)

![image](https://user-images.githubusercontent.com/5321186/30027347-cccb369a-9180-11e7-8881-897433c30c75.png)

**Comment by eXistenZe** [comment]
Sorry... I meant in view templates.

**Comment by iJungleboy** [comment]
since the view templates are 100% your code, adding such a thing is very dependent on your solution. For example, some people have angular-grids, others use plain html etc. So it's not exactly something we can provide from the platform.
