### ISSUE TITLE
Export Content / Data - most data is empty

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1285]
I'm submitting a bug report about admin experience UI.

In admin menu when I try to Export Content / Data to an XML file, half of the data shows fine (example 1), but the other half shows empty (example 2).

DNN 9.1.1
2sxc 9.04.01

```
  <Entity Type="farmped">
    <Guid>b0af5970-1664-47ad-9cfd-370db9128bf5</Guid>
    <Language></Language>
    <Farmaco>Sulfato Mg 20%</Farmaco>
    <Cat>1</Cat>
    <Diluicao>1 amp (200mg) até 200ml</Diluicao>
    <Concentracao>200</Concentracao>
    <Dosekg>50</Dosekg>
    <dosemax>2000</dosemax>
    <dosemaxudd>mg</dosemaxudd>
  </Entity>
```

```
  <Entity Type="farmped">
    <Guid>dd836033-c763-42fa-8ced-64a6c2580087</Guid>
    <Language></Language>
    <Farmaco>[]</Farmaco>
    <Cat>[]</Cat>
    <Diluicao>[]</Diluicao>
    <Concentracao>[]</Concentracao>
    <Dosekg>[]</Dosekg>
    <dosemax>[]</dosemax>
    <dosemaxudd>[]</dosemaxudd>
  </Entity>
```

**Comment by iJungleboy** [comment]
Please look into it a bit more. I believe you are either in a multi-language scenario or you are running into something. If you give us more details to help us corner the problem, we'll try to fix it. This is too vague and would take us too much (unpaid) time to corner. thx :)

**Comment by eXistenZe** [comment]
Just one language and one (default) culture.
If I select "Keep references to other languages (for re-import)", some valid data entries are replaced with empty ones. If I select "Replace references with values", all valid data is exported, plus some empty ones.
No errors on logs.

**Comment by iJungleboy** [comment]
To me it looks like you have an empty entity, without any data. Could that be?

**Comment by eXistenZe** [comment]
Nope. Two entities, both with data.
I did have others before (when I messed up force deleting a row and you suggested deleting the module and start again), but not anymore. Could it be they left remnant data? Is it possible to actually see all the source data of 2sxc (the "icache" I guess) and delete the ones that shouldn't exist?

**Comment by iJungleboy** [comment]
All the existing items are visible in the normal data-admin section. Could you mouse-over the ID in the table, to see if one of them has the guid above (dd836033-c763-42fa-8ced-64a6c2580087)? 

![image](https://user-images.githubusercontent.com/5321186/30361586-1a88216c-9858-11e7-942c-fbb18b7f5655.png)

**Comment by eXistenZe** [comment]
If I select: Value references to other languages ->Replace references with values
All content visible in the admin UI is properly exported as:

```
  <Entity Type="farmped">
    <Guid>dd836033-c763-42fa-8ced-64a6c2580087</Guid>
    <Language></Language>
    <Farmaco>Adrenalina 1:10 000</Farmaco>
    <Cat>1</Cat>
    <Diluicao>1 ml / 1 mg até 10 ml</Diluicao>
    <Concentracao>0.1</Concentracao>
    <Dosekg>0.1</Dosekg>
    <dosemax>1</dosemax>
    <unidade>mg</unidade>
  </Entity>
```
However, there are a lot of empty ones like:
```
  <Entity Type="farmped">
    <Guid>78e84a8b-9e28-40d9-9aa2-90f0d50916c5</Guid>
    <Language></Language>
    <Farmaco>[]</Farmaco>
    <Cat>[]</Cat>
    <Diluicao>[]</Diluicao>
    <Concentracao>[]</Concentracao>
    <Dosekg>[]</Dosekg>
    <dosemax>[]</dosemax>
    <unidade>[]</unidade>
  </Entity>
```
In this case, the GUID 78e84a8b-9e28-40d9-9aa2-90f0d50916c5 (one of the empty ones) does not match any row/content visible from the admin UI.

If I select: Value references to other languages -> Keep references to other languages (for re-import)
Most valid content is replaced by empty ones:

```
  <Entity Type="farmped">
    <Guid>dd836033-c763-42fa-8ced-64a6c2580087</Guid>
    <Language></Language>
    <Farmaco>[]</Farmaco>
    <Cat>[]</Cat>
    <Diluicao>[]</Diluicao>
    <Concentracao>[]</Concentracao>
    <Dosekg>[]</Dosekg>
    <dosemax>[]</dosemax>
    <unidade>[]</unidade>
  </Entity>
```
And some valid like:
```
  <Entity Type="farmped">
    <Guid>82c79282-ad5d-4c2e-95a6-75b5d03d96f4</Guid>
    <Language></Language>
    <Farmaco>Gluconato Ca 10%</Farmaco>
    <Cat>1</Cat>
    <Diluicao>[""]</Diluicao>
    <Concentracao>100</Concentracao>
    <Dosekg>50</Dosekg>
    <dosemax>2000</dosemax>
    <unidade>mg</unidade>
  </Entity>
```
Notice how dd836033-c763-42fa-8ced-64a6c2580087 is porperly exported in the first case, but not the second.

In both cases, 78e84a8b-9e28-40d9-9aa2-90f0d50916c5 exists with empty fields, and is it not shown in the admin UI.

There is a possibility that the old entity I deleted along the app/module had the same name (farm_ped, which is exported as farmped).

**Comment by iJungleboy** [comment]
Thanks, I believe you are correct - I think it's exporting deleted items (without data, as that's deleted). I'll look into it again.

**Comment by eXistenZe** [comment]
Thanks.
