### ISSUE TITLE
WYSIWYG "Link to another page" page selector does not create link after selecting page

### ISSUE THREAD

**Issue by lucatescari** [2sic/2sxc#1291]
**I'm submitting a ...**  
[x] bug report

**...about**   
[x] edit experience / UI

**Current behavior**

When using the WYSIWYG editor, and you try to create a link to an internal page, It doesn't work. The page selector opens, but as soon as you select a page, the selector closes, but the link does not appear.

**Expected behavior**

After clicking (chosing) a page in the page selector, a link to the page should appear.

**Minimal reproduction of the problem with instructions**

Steps to reproduce: 
Open Edit Dialog whith WYSIWYG
Highlight text
click on triangle on the right of the link symbol
select "Link to another Page"
Chose a page

**What is the motivation / use case for changing the behavior?**

If you want to link internal pages in your Content, this feature is of use.

**Please tell us about your environment:**

* **2sxc version(s):** 9.4.3  
* **Browser:** all
* **DNN:** 7.4.2
* **Language:** any/all

**Comment by tpperlman** [comment]
I can also confirm this issue. Here is the error in the console:

```
TypeError: i is not a function
http://.../desktopmodules/tosic_sexycontent/dist/sxc-edit/sxc-edit.min.js?sxcver=9.5.0.23058
Line 1, Column 7563
```
