### ISSUE TITLE
Feature: Custom user/group permissions for each type of entity manipulation (CRUD)

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1294]
**Following this topic:**
https://stackoverflow.com/questions/46151566/2sxc-toolbar-edit-permissions-by-dnn-roles

**I'm submitting a** 
[x] feature request

**about**
[x] edit experience / UI
[x] admin experience UI
[x] Razor templating.

**Current behavior**
Toolbar only renders if the user has edit permissions to the module.

**Expected behavior**
In certain situations, defined by view permissions and/or razor (if user is in role -> toolbar visible), the toolbar should be visible to all users with specified permissions, even if they do not have edit permissions to the page/module.
Is it a security risk to set permission to the view template (condition-> View, grant CRUD), but lock the toolbar in a @if (@Dnn.User.IsInRole("Content editors") == true)?

This way, other module editor features are prevented, like showing the personna bar, allowing template change, even the 2sxc add app/content floating bar showing on mouse over on empty sections on the page.

**Comment by iJungleboy** [comment]
The toolbar wouldn't be the only issue - because the save-API would refuse the data, if the user has no edit permissions. 

The way I see it, you would like another level of permission, but I'm not quite sure what I would call it. Could you give more details regarding the story you're trying to handle? What kind of people are these, why should they not have edit permissions but still be allowed to edit?

**Comment by eXistenZe** [comment]
The only thing they have/need to edit is data on fields (create a record, edit record), nothing else. FnL does this very well: https://pasteboard.co/GKmKOx2.jpg

These people are not part of design or any other DNN role. They just manage content in forms/views I provide. They are very important to the project itself as they manage content people need/want to see, but they are not designers, page editors or module editors.

Here are two simple examples:

1. I created a simple view to manage drugs dosage. I am responsible for every step of designing it (that's why it looks horrible :) ) and providing it. However, the content (the research data on each drug) is the responsability of a team of nurses/medics. They just create the rows of data and edit them if necessary, nothing else, so definitely no page permissions. https://servicodeurgencia.pt/Centro-de-conhecimento/10-F%C3%A1rmacos/107-C%C3%A1lculos-de-f%C3%A1rmacos-por-peso

2. Some staff needs web access to forms so that they can input research data and then see some statistical stuff (mostly sql queries). I develop some forms/lists/reports so that they can do this easily, but they can only access data insertion/editing, nothing else.

They must have access to data creation/editing through forms, but not a single step above that.

**Comment by eXistenZe** [comment]
(Coughing a lot)... Did I mention I do all this for free? :)

I would gladly do all this, just for the fun of learning it (did I mention I am a nurse?), but the custom API is completely out of reach for now (just too complex c# stuff involved).

**Comment by iJungleboy** [comment]
no problem :) - I too am a samaritan, working for thousands of hours for free - so I know the feeling ;)

**Comment by eXistenZe** [comment]
One quick question about custom APIs. I need to learn from working examples, and I believe the only demo app 2sxc has on custom CRUD form with custom API is 2sxcApp_TutorialWebAPI_01.00.06.
However, in 2 Api Calls with Parameters.html, CategoriesController.cs and categories.js I found two problems:
1. The "Edit this category" creates a new category instead of editing the existing one.
2. The "Delete this category" does not work.

Is it possible to fix these problems so that I can try creating my own webAPI?
Thanks.

**Comment by iJungleboy** [comment]
That demo is pretty old, so I don't know what's inside it, and I won't find the time to create a newer one. So I can't support you here, sorry :(

The main thing you need to know is that App.Data has various commands which you would use to do what you want. Some docs are http://2sxc.org/en/docs/Feature/feature/3360 and https://github.com/2sic/2sxc/wiki/Razor-App#edit-app-data-content-items

**Comment by eXistenZe** [comment]
Without a working and simple example with crud (like this demo) on custom form and api, there is no way for me to fix my initial issue.

**Comment by iJungleboy** [comment]
I understand, sorry about that :(
I could let an employee of mine take care of you, but it's quickly half a days work - http://2sxc.org/en/contact

**Comment by eXistenZe** [comment]
Half a day to fix the demo? They are fairly small files...

**Comment by iJungleboy** [comment]
I already invested more than 15 minutes :) - and  it always takes longer, especially because you'll have additional questions or wish for more documentation - that's just real life :)

**Comment by eXistenZe** [comment]
Not really... If I get working examples, I will make my best efforts to replicate the examples to my needs, and I promise I will give you the full app I develop (if I actually do develop it).

Let's make it two coffees?

**Comment by iJungleboy** [comment]
sorry, there's just a limit to the free support for a free product

**Comment by iJungleboy** [comment]
I'll close this for now, and move it to the milestone of "wishes which require a sponsor"

**Comment by eXistenZe** [comment]
Ok. I'm going to give up.

The code looks fine in both demo apps 2sxcApp_TutorialWebAPI_01.00.06 (the angular JS one) and 2sxcApp_TutorialWebAPI-FeedbackForm_01.01.02 (plain js and jquery), however the same behavior happens in both:

The "Edit stuff" creates a new item with empty content instead of editing the existing one.
The "Delete stuff" does not work. It doesn't even complain "authorization denied" when I'm not logged in. It just does nothing. It doesn't even proceed to the reload instruction(s).

You can see here your demo working:
http://2sxc.org/dnn-app-demos/en/Apps/Tutorial-WebApi-Feedback-Form

And here my demo not working:
https://servicodeurgencia.pt/tests

Unless you can remember something that could cause this that is not the code (perhaps some update or some other setting in DNN), I'm going to give up.

**Comment by eXistenZe** [comment]
When I click "delete" I get the log:
405 (Method Not Allowed)
with or without admin login.
Full log: https://drive.google.com/file/d/0B-4bmuuNWVx2M2dGc1hwNmUyQkk/view?usp=sharing

**Comment by eXistenZe** [comment]
DELETE method problem fixed with:
```
<system.webServer>    
  <modules>        
    <remove name="WebDAVModule" />    
  </modules>    
  <handlers>        
    <remove name="WebDAV" />    
  </handlers>
</system.webServer>
```
Now only the edit problem persists.

**Comment by iJungleboy** [comment]
I believe most of this was implemented in 2sxc 9 and 10.
