### ISSUE TITLE
Cannot change template in app (9.5 specific?)

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1296]
**I'm submitting a ...**
[x] bug report

**...about**
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
When I create an app with 2 views, the change template bottom bar shows (either toolbar or module edit), I can click the templates, it shows a message with "refreshing (new view selected)" but then the old view is shown. No error is output in browser console, admin logs or resources logs.

**Expected behavior**
Change template changes to new template.

**Please tell us about your environment:**
**2sxc version(s):** 9.5.1 
* **Browser:** Chrome 60 | Edge 40
* **DNN:** 9.1.1 
* **Language:** [English]

This feature worked fine in 9.4.1

**Comment by TopCat6** [comment]
I experience the same issue, as described.

**Comment by iJungleboy** [comment]
thx, will look into it...

**Comment by iJungleboy** [comment]
Are you getting a JS error?

**Comment by eXistenZe** [comment]
Nope. Nothing.

**Comment by eXistenZe** [comment]
Any temporary fix I can apply while the bug is fixed? Revert to latest 9.4.1?

**Comment by iJungleboy** [comment]
The information is stored internally in an entity, which is a ContentBlock, to be found in the Scope 2SexyContent-System. So you could actually change in the admin UI, but you could end up creating invalid configurations (like a template which expects a content-type X, and now gets a content-item of type Y). 

So you can easily do it - just google how to change scopes - but be careful of what you're doing.

**Comment by eXistenZe** [comment]
Definitely not easy at all... I guess I'll wait for a proper fix...

**Comment by eXistenZe** [comment]
Just one small related problem:
If I create a new view, set Content: none, and enable list view, it does not show on template selection. If I set a content type, it shows in template selection but the but reported in first post occurs.
