### ISSUE TITLE
Title field appears as "- no title -" in Manage Content / Data list

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1302]
**I'm submitting a ...**
[x] bug report

**...about** 
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
"title" fields appear to have some special query to the table. All other fields display fine, but title field shows "- no title -" (it is filled and mandatory as shown).

Also, notice how it caps the first letter (T). Both my field and label are not with caps (just "title"). 

https://pasteboard.co/GL6y4ho.jpg

**Expected behavior**
Title field shows normally on the list.

* **2sxc version(s):** 9.5.1
* **Browser:** [all]
* **DNN:** [9.1.1 ] 
* **Language:** [English]

**Comment by iJungleboy** [comment]
I believe this is related to #859 - most likely this occurs because the field is named "Title" but lower case. It's still a bug, but could you test/verify that? So my guess is that if you rename the field to "Title" or to anything completely different like "Spaghetti" it will work.

**Comment by eXistenZe** [comment]
Indeed. Anything other than "title" works.
Thanks.
