### ISSUE TITLE
Import process does not complete, rendering a 500 Internal Server Error

### ISSUE THREAD

**Issue by TwoHeadsBrewing** [2sic/2sxc#1305]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**  
[x] admin experience UI

**Current behavior**
The import process does not complete, rendering a 500 Internal Server Error

**Expected behavior**
The import process should proceed

**Minimal reproduction of the problem with instructions**
1. Create a template of a current site
2. Export 2sxc Content (check Include Content, for copying entire site)
3. On the new site, log in
4. Go to 2sxc Admin, and click the "Import" button
5. Choose the file (I've exported the 2sxc Content with included files as per the import/export documentation)
6. Click "Import"
7. A 500 Internal Server Error appears and the import does not proceed

**What is the motivation / use case for changing the behavior?**
N/A

**Please tell us about your environment:**
Evoq 8.4.1, 2sxc 9.5.1
Amazon AWS EC2 instance with RDS SQL Server back end

* **2sxc version(s):** 9.5.1 <
* **Browser:** all
* **DNN:** 8.4.2 
* **Language:** any

**Anything you would like to add**
The odd thing is that I can use a previous content export, from many months ago and it works fine.  But I can't use that because it's missing a lot of content for my template site.  It doesn't appear that the call to import the file is even being processed.

This is the message when I inspect the page:
POST http://test.pintiva.biz/desktopmodules/2sxc/api/app-sys/ImportExport/ImportApp 500 (Internal Server Error)

**Comment by iJungleboy** [comment]
Could you post the error message in your event-log (admin-section of dnn)? There you should see on which line in explodes.

**Comment by TwoHeadsBrewing** [comment]
Another odd issue:  I can import other apps (like a recent export of the Blog App) without any errors, and like I mentioned before I can import an older Content export.  Is there perhaps a file size limit to the export files?  The contents of both export.zip files look OK, (header, entities, attributes, file locations,etc).  The only difference is the file sizes (7MB vs. 23MB).

Here's the error message from the log:
Url Processing Exception:Exception in Url Rewriting Process
Http Status:500 Internal Server Error
Original Path:http://test.pintiva.biz/desktopmodules/2sxc/api/app-sys/ImportExport/ImportApp
Raw Url:/desktopmodules/2sxc/api/app-sys/ImportExport/ImportApp
Final Url:null
Rewrite Result:[no rewrite]
Redirect Location:[no redirect]
Action:Continue
Reason:Exception
Portal Id:-1
Tab Id:-1
Http Alias:Null
Debug Message 1:Exception: Maximum request length exceeded.
Debug Message 2:(TRUNCATED TO 500 CHARS): Stack Trace: at System.Web.HttpRequest.GetEntireRawContent() at System.Web.HttpRequest.GetMultipartContent() at System.Web.HttpRequest.FillInFormCollection() at System.Web.HttpRequest.EnsureForm() at System.Web.HttpRequest.get_Form() at System.Web.HttpRequest.get_Item(String key) at DotNetNuke.Services.ClientCapability.ClientCapabilityProvider.GetClientCapability(HttpRequest httpRequest) at DotNetNuke.Entities.Urls.FriendlyUrlController.IsMobileClient() at DotN
Debug Message 3:Inner Ex : null
Exception Type:System.Web.HttpException
Message:
Maximum request length exceeded.
Stack Trace:(TRUNCATED TO 500 CHARS): at System.Web.HttpRequest.GetEntireRawContent() at System.Web.HttpRequest.GetMultipartContent() at System.Web.HttpRequest.FillInFormCollection() at System.Web.HttpRequest.EnsureForm() at System.Web.HttpRequest.get_Form() at System.Web.HttpRequest.get_Item(String key) at DotNetNuke.Services.ClientCapability.ClientCapabilityProvider.GetClientCapability(HttpRequest httpRequest) at DotNetNuke.Entities.Urls.FriendlyUrlController.IsMobileClient() at DotNetNuke.Entiti
Server Name: WIN-VGD4FFTN042

**Comment by TwoHeadsBrewing** [comment]
I tried changing the max file size in the Host Settings from 12MB to 25MB.  I now get a different error when trying to import:

AbsoluteURL:/desktopmodules/2sxc/api/app-sys/ImportExport/ImportApp
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:84ca3c99-3a9b-4a2e-88f1-65382429c770
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:pB1p86vb6qkoyoWZQYgzHQ==
Message:The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
StackTrace:
   at ToSic.Eav.Apps.ImportExport.ZipImport.ImportZip(Stream zipStream, String temporaryDirectory)
   at ToSic.SexyContent.WebApi.ImportExportController.ImportApp() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Sxc WebApi\ImportExportController.cs:line 169
InnerMessage:
InnerStackTrace:
Source:ToSic.Eav.Apps
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: WIN-VGD4FFTN042

**Comment by iJungleboy** [comment]
Two things (for the last message)

1. The c:\projects path is only a debug-information, to tell us which code-file caused the bug. It's not looking for that file, so this is fine. So it's this line which breaks: https://github.com/2sic/2sxc/blob/master/Sxc%20WebApi/ImportExportController.cs#L169
2. For some reason the temp-path is too deep, which causes trouble. My guess is your site has a very deep root path (causing the total url to become too long), and/or your package has a very long name. Could you check that?

**Comment by TwoHeadsBrewing** [comment]
This is my portal directory:  C:\inetpub\wwwroot\GOTRCMS\Portals\1-Test2
This is the package directory path and name:  C:\GOTR Files\2sxc New Site\ContentImport.zip
This is the package directory path and name with the older import file that does actually work:  
C:\GOTR Files\2sxc New Site\2sxcApp_Content__withPageContent_2017-01-23T0624.zip

So if this really is a file path too long issue, why would the longer file name work while the shorter file name throw the error?

**Comment by iJungleboy** [comment]
I can't give you an answer but I'll add more extensive logging to the import process - probably tomorrow...

**Comment by iJungleboy** [comment]
The latest pre-release has much more intense logging, it could help you. 

It's described here how you can use it to log web-api calls (which is what you have when importing)

Note that your problem is probably deep folders in the zip, which in the end returns long paths. but I added detailled logging to warn you about that once paths hit 240 chars.

I'll close this for now, as it's an issue specific to your import, and not a general 2sxc bug but a limitation of the windows file system.
