### ISSUE TITLE
App.Data.Update creating new record instead of updating

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1310]
**I'm submitting a ...** 
[x] not sure

**...about** 
[x] APIs like REST
[x] other / unknown

**Current behavior**
I implemented your feedback demo app here: https://servicodeurgencia.pt/tests
Everything works as intended except "Complete" (App.Data.Update), which is creating a new entry instead of updating the current one.

Here is the view:
```
    @foreach(var f in AsDynamic(App.Data["Feedback"])){
      ...
      <a href="javaScript:feedbackCompleted(@Dnn.Module.ModuleID, @f.EntityId)">Complete</a>
      ...
      }

function feedbackCompleted(moduleId, id) {
        $2sxc(moduleId).webApi.get("Feedback/Complete", id)
            .then(function (result) { showOkAndReload() });
    }
```

And the controller:
```
    [HttpGet]
    [DnnModuleAuthorize(AccessLevel = SecurityAccessLevel.Anonymous)]
    [ValidateAntiForgeryToken]
    public void Complete(int id)
    {
        var editSet = new Dictionary<string, object>();
        editSet.Add("Status", "Completed");
        App.Data.Update(id, editSet);
    }
```
App.Data.Create and App.Data.Delete works fine.
I tried quite a few demos (and custom API) and they all have this problem.

**Expected behavior**
App.Data.Update updated the record instead of creating a new one.

**Minimal reproduction of the problem with instructions**
You can test it here: https://servicodeurgencia.pt/tests it has Anonymous level.

* **2sxc version(s):** 9.4 - 9.5.2
* **Browser:** [all]
* **DNN:** [9.1.1 ] 
* **Language:** [English]

**Comment by iJungleboy** [comment]
I don't have a clear answer yet, but I'll add a bunch of logging details to the next release to help you corner it...

**Comment by eXistenZe** [comment]
That would be awesome. Thanks.

**Comment by eXistenZe** [comment]
Where exactly is the log? I can see the "2sxc-Api:Auto-Log ModuleId:994", but no details there.

**Comment by iJungleboy** [comment]
we're adding more and more logs by the hour - and the next release will also show what endpoint was used and more of what parameters were processed.

**Comment by iJungleboy** [comment]
Officially released 9.6 - pls try and check debugging https://github.com/2sic/2sxc/releases/tag/v09.06.00
to see what's happening in web-apis, you must temporarily enable extensive logging, as explained inhttp://2sxc.org/en/blog/post/releasing-2sxc-9-6-with-extensive-logging

**Comment by eXistenZe** [comment]
Nothing. Just this info on admin log:
2sxc-Api:/API/2sxc/app/auto/api/Feedback/Complete?id=2380

**Comment by iJungleboy** [comment]
I can reproduce, will look into it.

**Comment by iJungleboy** [comment]
found and fixed, will be in 9.6.1

**Comment by iJungleboy** [comment]
Here's a pre-release of 09.06.01 (still labeled as 09.06.00) which should fix it. Please test and give feedback, thx!
[2sic_2SexyContent_09.06.00_Install.zip](https://github.com/2sic/2sxc/files/1340968/2sic_2SexyContent_09.06.00_Install.zip)

**Comment by eXistenZe** [comment]
Can't. My DNN host crashed while editing a view with 2sxc. Getting 500 error now.





Kidding. It's having some trouble connecting to the DB. When it's back up I'll test it. Thanks.

**Comment by iJungleboy** [comment]
;) - thx

**Comment by eXistenZe** [comment]
Fixed. Thanks.

**Comment by Constantine-Ketskalo** [comment]
Just stumbled upon this exact issue while using 2sxc v. 12.10.0. Don't know if it matters but I'm trying to update entity that is used as demo item.

**Comment by iJungleboy** [comment]
@Constantine-Ketskalo if you discovered a fresh problem, please open a new task as this is many years old and wouldn't be useful to keep oversight.
