### ISSUE TITLE
Using Module in another page is not showing information

### ISSUE THREAD

**Issue by ufoloko** [2sic/2sxc#1314]
I have created an app, with respective query to show all items for my custom type and a view using that query.

I have added some items and are normally showing in current page or tab, if I add same app with same template in another page, no items are showed.

If I created my custom query and used in view, I dont know why is this happening, i think is a bug, because i cant find any other setting to show contents for any module.

**Comment by TopCat6** [comment]
Just a thought, but ensure you are using the 'Data' interface and not the 'Content' interface. The first allows you to access the same data from different pages and views, while the second keeps all your data separate for each instance/occurrence of your module or page. See: http://2sxc.org/en/Docs/Feature/feature/9266

**Comment by ufoloko** [comment]
Im using Visual Query Datasource, but is not showing any of items into pages.

Im Attaching my app, maybe you can find what is wrong

1- I Have a type Image
2- I Have a query called AllImages
3- I Have a template called _AllImages.cshtml and this uses query AllImages
4- I Have uploaded items in Data Tab
5- I Add this app in same pages but no one is showing information

Thanks

[2sxcApp_ArtImages_00.00.01.zip](https://github.com/2sic/2sxc/files/1345436/2sxcApp_ArtImages_00.00.01.zip)

**Comment by iJungleboy** [comment]
@ufoloko this is a support request, not a bug/feature. we want to keep this very separate, so please post this on stack-overflow.
