### ISSUE TITLE
Template/view changing problem

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1317]
**I'm submitting a ...**
[x] bug report

**...about** 
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
I have an app with a new "section" with 2 views:
_createpool.cshtml is a simple view with dropdowns that open a link with parameters to _quizpool.cshtml , a list view that catches the parameters. This second view opens with the urlkey "newquiz/create".
https://pasteboard.co/GN76igq.jpg

When I tested mysite.com/myapppage/newquiz/create it opened the second view with no problems and it catches the parameters fine, however, once I returned to mysite.com/myapppage it no longer showed the first view.

It is now locked on the second view and even the template changer now only shows two views (instead of the 7 available in app). It's only showing the templates with one associated content (quiz_pool) and not the others.
https://pasteboard.co/GN76acW.jpg

**Expected behavior**
Opening mysite.com/myapppage should show the first view and template changer should show all templates available.

* **2sxc version(s):** 9.6.0
* **Browser:** [all]
* **DNN:** [9.1.1 ] 
* **Language:** [English]

**Comment by iJungleboy** [comment]
I believe you ran into something intended: once someone starts editing content, you cannot switch to any view, as only the views are still provided, which expect the same combination of content-configuration. So say you start with a view which shows "person" data - once you add such data, you cannot switch to a view which expects "blog" data as it would get messed up by the existing "person" data

**Comment by eXistenZe** [comment]
That doesn't actually make sense to me. So an instance must be locked to a content type? What harm could come from using a view with no content itself?

**Comment by iJungleboy** [comment]
you can usually change around views as much as you want - until you start editing content. Then this module-instance has content assigned to it, and will only allow switching to views which expect this kind of content.

**Comment by eXistenZe** [comment]
So if I need to pull data from multiple entities in different views, I must assign the same content to all and then forced to work with data in all others.

**Comment by iJungleboy** [comment]
@eXistenZe I believe you are doing something which I don't understand - and asked a question about it which led me to think you're doing something else. Please describe what you're trying to achieve, ideally using real terms like "I have 3 content-items showing quiz-configurations, and 1 which is a quiz-result, and I'm trying to do xxx which is why I wanted to change the view...".

**Comment by eXistenZe** [comment]
No no. Sorry. The problem I have right now is exactly what I posted first
and you answered.

However I plan to use and learn 2sxc for a long while and I feel I am just
getting started, so I'm trying to understand the full implications of this
feature.

My last question in this matter is this: if I need one app to use two views
which pulls data from two entities (let's say two lists, for example), they
must both have the same content assigned, but one of them will have to use
data, right?

**Comment by iJungleboy** [comment]
Sorry, I don't understand your question :)

Basically changing views is something you don't do a lot, because once you put something on a page it usually stays there. So view-changing is something you do a lot in content, while in apps it's fairly rare - and you can always just add another module again to get another view.

**Comment by eXistenZe** [comment]
So your suggestion is to link to another page (with another module
instance) instead of another view in the same page, whenever I need to work
with different content (or from content to no content)?

On Oct 3, 2017 09:37, "iJungleboy" <notifications@github.com> wrote:

Sorry, I don't understand your question :)

Basically changing views is something you don't do a lot, because once you
put something on a page it usually stays there. So view-changing is
something you do a lot in content, while in apps it's fairly rare - and you
can always just add another module again to get another view.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/2sic/2sxc/issues/1317#issuecomment-333776976>, or mute
the thread

**Comment by iJungleboy** [comment]
sorry, still confused, and don't want to give you a misleading answer. please explain what you're trying to do.
