### ISSUE TITLE
After update to 06.06.00 the Image Manager shows no files/folders

### ISSUE THREAD

**Issue by mconta** [2sic/2sxc#132]
Hello,

After the update to version 06.06.00 when editing an Item the Image Manager shows no files/folder and is empty.

Can you provide some tips on how to fix this problem?

Is related to the web.config settings? 

![image](https://cloud.githubusercontent.com/assets/2010201/5718629/37f6d39e-9b10-11e4-92d9-b5e6c9fdc829.png)

**Comment by mconta** [comment]
The fields are Hyperlink fields configured with these values:

![image](https://cloud.githubusercontent.com/assets/2010201/5719864/ce3d14f6-9b1c-11e4-9f37-bcbec247975f.png)

The check/uncheck of the "ShowImageManager" doesn't solve the problem.

**Comment by 2sicProgrammers** [comment]
maybe a path issue. Could you try adding a path?

**Comment by mconta** [comment]
Thank you for your suggestion,

I did some test:  using a path in this format it seems to work again:

My folder is under 

<dnnfolder>/portals/2/images/myfolder

I added the path with this value:

Images/myfolder

And it works.

It seems that in the past the 2sic dll used a default for the images folder... Can you tell me how to change this default path? Now I have to reconfigure all the modules adding this path to the hyperlink field types.

The only change I did on my DNN configuration was the default image folder for the cke editor, is this connected in some way with this problem?

**Comment by raphael-m** [comment]
If no path is specified, 2SexyContent should use the default configuration of the HTML editor provider (which is, as default value, the portal's home directory). I'll test this with CKE editor and update this issue as soon as I know more.

**Comment by rmartin77** [comment]
Hi I install 2sexy version 7 in a new fresh dnn 7.4 
I install OWL ImageSlider (Carousel) app
http://2sxc.org/en/Apps/Details?AppGuid=b1a62298-9c72-44f0-bfee-dfecdab6fe69
but during the editing of image i found that Image manager is complete empty.
i try to add path in hiperlink definition.... but never

any one have the same issue?
Fabio

**Comment by iJungleboy** [comment]
Check that 
a) the folder exists and DNN knows about it (re-sync just to be sure)
b) DNN knows what security to apply (to be sure, apply at a folder above and re-apply to all subfolder automatically)

**Comment by rmartin77** [comment]
aaaaaaaarrrrggggg!
I found this in log:
InnerStackTrace:   at DotNetNuke.Providers.RadEditorProvider.TelerikFileBrowserProvider.AddChildDirectoriesToList(DirectoryItem radDirectory)
   at DotNetNuke.Providers.RadEditorProvider.TelerikFileBrowserProvider.ResolveRootDirectoryAsTree(String path)

So i go on file manager, refresh all directory structure and it work!!!!!!!!!!!
I hope this help to other like me
Thansk
Fabio

**Comment by iJungleboy** [comment]
classic :)
