### ISSUE TITLE
2sexy version 9.6.0 destroys the add module function at DNN 9.1.1

### ISSUE THREAD

**Issue by dnastone** [2sic/2sxc#1321]
**I'm submitting a ...** 
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] DNN parts
[x] other / unknown

**Current behavior**

when i installed the version 9.6.0 i can't add any module to a pane.
i made a test and installed a dnn 9.1.1 version with the latest security update. and everything worked fine.
then i installed 2sexy 9.6.0 and i can't add any module to a pane.

Browser google chrome
* **DNN:** 9.1.1
![screen_error](https://user-images.githubusercontent.com/11678580/31195118-84c6a57e-a949-11e7-97ca-4f5a214a813f.jpg)

* **Language:** german

**Comment by michaelcunningham1974** [comment]
A couple of other related items.... 

When attempt to add the module the HTML module is initally missing from the Add module dialog. If you scroll down then up the module reappears.

It appears that 2sxc JS is being loaded on pages without any 2sxc modules.

2 JS errors:
inpage.min.js:99 Uncaught TypeError: Cannot read property 'current' of undefined
VM4674:1 Uncaught TypeError: Cannot read property 'toolbars' of undefined

**Comment by michaelcunningham1974** [comment]
This can be partially mitigated by having another 2sxc module on the page.

**Comment by iJungleboy** [comment]
We'll look into it...

**Comment by iJungleboy** [comment]
is in pre-release 3 of 9.6.1
