### ISSUE TITLE
Hide (unpublish) view in admin panel removes it

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1328]
**I'm submitting a ...** 
[x] bug report

**...about**
[x] admin experience UI

**Current behavior**
I was trying to hide a view from the template selection, so I went to the admin panel, edited the view, selected "hide this item" it the bottom, saved, and the view no longer appears on the list (the admin panel view section), so I cannot re-enable it.

https://pasteboard.co/GNXLCpN.jpg
https://pasteboard.co/GNXLJDs.jpg
https://pasteboard.co/GNXLOp6.jpg

**Expected behavior**
Hidding a view should only hide from template selection. In the admin panel, it should be visible and marked with the "eye" icon.

* **2sxc version(s):** 9.6.1
* **Browser:** [all]
* **DNN:** [9.1.1 ] 
* **Language:** [English]

**Comment by iJungleboy** [comment]
this is not a bug, but it is an unexpected use. To just hide a template, please use the switch _hide from editor_ instead. 
To restore your work, just switch the context to "2SexyContent-System" and manually correct the data. If you've never done this, read http://2sxc.org/en/blog/post/advanced-dynamic-data-content-understanding-content-type-scopes

**Comment by eXistenZe** [comment]
Thanks. Solved.
