### ISSUE TITLE
I can not insert text app (or anything else) inside accordion 

### ISSUE THREAD

**Issue by bastrou** [2sic/2sxc#1334]
[x] bug report => "template "number" does not exist"

**Current behavior**
I added a new accordion app and after I edited title I am  tried  to insert a text app in it. When I did that error happened 

**Expected behavior**
To accept the text app

* **2sxc Version:** [9.6 ]
* **Browser:** [Edge Chrome ]
* **DNN:** [9.1.1  ] 
* **Language:** [English ]

Great project thank you

**Comment by iJungleboy** [comment]
Is this sitll an issue? or was it something with your installation?

**Comment by bastrou** [comment]
I replaced my cms with WordPress. I haven't try anything.

**Comment by iJungleboy** [comment]
ok, thn for the feedback, in that case I'll close this.

**Comment by iJungleboy** [comment]
I believe I was able to reproduce the issue - will handle as high-priority

**Comment by bastrou** [comment]
If you fix it. It will be major good fro DNN. I like asp.net I like DNN but it became very expensive. No free blog no nothing. I am a programmer too and I would like to help but sometimes time and money is the only thing that matters. Please keep up the good work.

**Comment by iJungleboy** [comment]
I think I'm almost there. It looks like we missed something when we refactored for typescript - a special case where "this" was used differently inside a function...

**Comment by iJungleboy** [comment]
I think I fixed it. Should in in 2sxc 9.10, to be released Monday or Tuesday

**Comment by iJungleboy** [comment]
fyi: released 9.10 pre2 yesterday - should be fixed. Would a appreciate it if you test/confirm.

**Comment by bastrou** [comment]
I will do it first thing when I will install it again. Right now I have not DNN anywhere. Thank in advance for your effort.
