### ISSUE TITLE
Feature: Creating several fields -> Return to filled form on error

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1335]
**I'm submitting a ...** 
[x] feature request

**...about**
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
When creating several fields at once in entity admin, 10 at most by form limit, if you fill everything, click the "check" button, and some error occurs (like a field name already exists), nothing else is saved and the form closes.

**Expected behavior**
2sxc could return to the form with all fields info still filled so that no time is wasted filling all the info again. Or the errors could be checked before actually closing the form.

**Comment by iJungleboy** [comment]
Thanks for the input. Just fyi: it's a few hours of work, and ATM we're focused on other features, so we won't prioritize this
