### ISSUE TITLE
Empty field -> group do not show on (new) form (special chars?)

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1336]
**I'm submitting a ...** 
[x] bug report

**...about**  
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
I have several empty fields for grouping purposes, with exactly the same settings, but only half of them show up when creating a new record.
https://pasteboard.co/GODboug.jpg
https://pasteboard.co/GODbuvs.jpg
https://pasteboard.co/GODbz5f.jpg

After checking with browser console it seems special char related:

```
set.min.js?sxcver=9.6.1.24532:118 Error: [$parse:lexerr] http://errors.angularjs.org/1.5.8/$parse/lexerr?p0=Unexpected%20next%20character%20&p1=s%209-9%20%5B%C3%A7%5D&p2=A.%20Avalia%C3%A7%C3%A3o%20da%20pele
    at set.min.js?sxcver=9.6.1.24532:6
    at jc.throwError (set.min.js?sxcver=9.6.1.24532:217)
    at jc.lex (set.min.js?sxcver=9.6.1.24532:215)
    at s.ast (set.min.js?sxcver=9.6.1.24532:221)
    at td.compile (set.min.js?sxcver=9.6.1.24532:231)
    at kc.parse (set.min.js?sxcver=9.6.1.24532:260)
    at g (set.min.js?sxcver=9.6.1.24532:125)
    at h (set.min.js?sxcver=9.6.1.24532:453)
    at u (set.min.js?sxcver=9.6.1.24532:453)
    at set.min.js?sxcver=9.6.1.24532:453
```

**Expected behavior**
All fields show up on the form. If special chars are not allowed in field names, block the use when creating the field. Since it was just a grouping field I did not pay attention to the name.

* **2sxc version(s):** 9.6.1
* **Browser:** [all]
* **DNN:** [9.1.1] 
* **Language:** [English]

**Comment by iJungleboy** [comment]
Here's what's happening: the nice labels shouldn't be the field name. Basically the field-names should be programming-safe, meaning no spaces, no dots, etc. You can always give it a nice label (in many languages). To "rename" the internal name, click the widget-button on the right of the row, give it a safe name, and you're good to go.

**Comment by iJungleboy** [comment]
Created new issue with the real cause #1339
