### ISSUE TITLE
[Feature request] Ability to output a field label or help text in razor view

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1337]
**I'm submitting a ...**
[x] feature request

**...about**
[x] edit experience / UI

**Expected behavior**
There could be a way to output a field label and help text. IE:
fieldA, "This is field A label", "This is field A helper text"
fieldA, @fieldA:label, @fieldA:desc
When creating custom forms with huge amount of fields, this would help avoiding to edit a field label in two different places (field config and view).

**Comment by iJungleboy** [comment]
Actually this can be done, but it's not well documented and possibly confusing at first. I won't have the time to provide much more documentation ATM and we're actually reworking a part of it. 

If you want to use it now, you can already do it using @YourItem.Type which is the _ContentType_ containing all the definitions. The inner properties of fields are located in the metadata, but 2sxc 9.7 or 9.8 will actually introduce a breaking change to metadata handling (as nobody except for us is currently using it, it won't hurt anybody except for you, if you start using it now). 

So either you wait for 9.7 or 9.8, or you already use it now, knowing that you'll have to rename some objects when you upgrade.
