### ISSUE TITLE
Cannot use any date format in webApi.post

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1338]
**I'm submitting a ...** 
[x] bug report 

**...about** 
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
I'm guessing this is another culture thing that makes it impossible to store data.

I'm trying to pass a js var to a date field. I use a simple code to create the date:
`$todaydate = today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate();`

I can see the headers at post
`data_new:"13-10-2017"`

However, the row is filled with an empty data_new field.

Until yesterday I was able to pass dates with this format:
`$todaydate = today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate();`
but it no longer works since 13 is not a valid month and I see the error on log.

Once again the server demands one format, and the browser/js another, which makes it impossible to solve (like the other numeric problem with commas and dots).

Is the only workaround placing dates in string fields?

**Comment by iJungleboy** [comment]
dates in JSON are always a problem (not 2sxc specific). Please use the international ISO standard. basically yyyy-mm-dd

**Comment by eXistenZe** [comment]
I can't. In that format the field is stored empty.
Using string for now.

**Comment by iJungleboy** [comment]
This is strange, will investigate...

**Comment by iJungleboy** [comment]
closed because of inactivity
