### ISSUE TITLE
[Documentation/Issue] Access data without working DNN install

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1340]
**I'm submitting a ...** 
[x] feature request
[x] support request
[x] not sure

**...about...**
[x] Content Types or data management
[x] other / unknown

**Current behavior**
I know this is not the right place to ask, but it is a crucial question I can't find the answer for.

Where and how is 2sxc entity data stored? I can't find any info on  this. I can see it, export it and query it with a working dnn and sxc install, but what if my host fails somehow? I suddenly get a 500 error I will not be able to solve in a week. Can I retrieve or access the  data with access to the files with ftp or the database with plesk or smss?

I learned the basics of content/data usage, lists management, views and templating, querying with visual and linq, but I still lack any info on data actual structure.

Can you give some info on this topic?

Thanks.

**Comment by iJungleboy** [comment]
Just a short answer: At the moment it's an EAV-data model in the SQL server. You'll have too google that a bit to understand the exact setup, but basically it's a bit like this

1. Table Entities has the ID, the type etc.
2. Table Values has the values - one value per row
3. Various tables are also needed to manage Attributes, ContentTypes, Apps, Zones etc.

So yes, you can export it all and if you have DB experience, it's also fairly easy to "build" another table from it. Or you would just copy-paste the tables to another DNN installation and continue there. 

BUT: 2sxc 9.7 and 9.8 will introduce some new features https://github.com/2sic/2sxc/projects/7

In these, we'll store some of the items as JSON-Microdocuments - and depending on the performance we'll see, it may also be that we'll migrate the entire internal data-format to that.

**Comment by eXistenZe** [comment]
Can you give me the name of the tables?

**Comment by iJungleboy** [comment]
Pls look in the DB. All tables start with ToSic_...
