### ISSUE TITLE
webApi.post "$2sxc is not defined" when not logged in as admin

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1347]
**I'm submitting a ...**
[x] bug report
[x] not sure

**...about** 
[x] edit experience / UI
[x] admin experience UI
[x] JS development
[x] other / unknown

**Current behavior**
Using this minimized view:
```
function save() {
            function postData() {
                return {
                data: "2"
                }
            }
            
            var newItem = postData();
            $2sxc(@Dnn.Module.ModuleID).webApi.post('app/auto/content/audits', {}, newItem);
}
```

I get the js error at save():
`Uncaught ReferenceError: $2sxc is not defined`
But only when I am not logged in as admin.
I gave anonymous CRUD permissions to the entity.

* **2sxc version(s):** 9.6.1
* **Browser:** [Chrome | Edge]
* **DNN:** [9.1.1 ] 
* **Language:** [English]

**Comment by eXistenZe** [comment]
Solved.

Including
<script src="/desktopmodules/tosic_sexycontent/js/2sxc.api.min.js"></script>

**Comment by iJungleboy** [comment]
Note that since 2sxc 13+ you should use the IPageService.Activate("2sxc.JsCore");

See https://docs.2sxc.org/net-code/razor/services/page-service-activate.html

**Comment by skarpik** [comment]
That's perfect. Thank you.
