### ISSUE TITLE
Provide Test-Link to the test the published data-stream

### ISSUE THREAD

**Issue by 2sicProgrammers** [2sic/2sxc#135]
The link used to be in the module-settings. Now it can't be found any more. Pls add comment & link to here:
![image](https://cloud.githubusercontent.com/assets/6663382/5779658/e9408096-9da4-11e4-9300-35b2c2e981d9.png)

Comment first "The following link will deliver the JSON-data, but only if you already saved this record with publishing enabled, AND if this module you're currently on actually shows this template."

**Comment by raphael-m** [comment]
Put that back because the data-url might change to Web API...

**Comment by iJungleboy** [comment]
Close this for now, as we'll actually move to visual query as the preferred method of publishing JSON
