### ISSUE TITLE
[Feature request] Access other app's entities

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1350]
**I'm submitting a ...** 
[x] feature request

**...about**
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
Entities are only accessible within the app itself.

**Expected behavior**
In some contexts, entities are common to a group of apps. For example, I use a list of departments in my institution for at least 4 apps (different projects that cannot and should not be merged in a single app). Another example is the type of employes or even the list of employees. These entities need to be copied into every single app that needs it, and when changed, it needs to be done in every copy.

Is it possible to create an entity accessible to every app in an easy and fast way?

Thanks.

**Comment by iJungleboy** [comment]
Yes, and it's mostly documented in the App DataSource. If you have further questions, please post it on stack-overflow.

**Comment by eXistenZe** [comment]
I searched it, but can't find it. Is it the dotnet external use?

// the app idvar appId = 42;
 // create a simple app object to then access datavar appSimple =
ToSic.SexyContent.Environment.Dnn7.Factory.App(appId);
 // example getting all data of content type Tagvar tags =
appSimple.Data["Tag"];

**Comment by iJungleboy** [comment]
Pls post on stack-overflow, as it's important that such answers will be public to other people searching.

**Comment by eXistenZe** [comment]
Done.
https://stackoverflow.com/questions/47018881/2sxc-access-other-apps-entities
