### ISSUE TITLE
JS: Get built-In 2sxc-controller to deliver data with promise (maybe new API)

### ISSUE THREAD

**Issue by 2sicProgrammers** [2sic/2sxc#136]
I'm not sure about this, but I need to be able to call a 2sxc(moduleid).data... and get a promise back. Can this already be done? I think our "on-load" was more or less a way to create own promises - we wouldn't need it if we had real promises. 

What do you think? is it already included? Can we support both mechanisms in parallel so that old code still works?

**Comment by raphael-m** [comment]
Discussed with Daniel: We create a separate API for requests to pipelines, working with promises.
```
$2sxc(moduleId).pipeline(settings)
.then(function(data) {
    // Do something with data
})
```

**Comment by iJungleboy** [comment]
normal pipeline is now delivering promises! :) 
so we won't change the in-page behavior...
