### ISSUE TITLE
IE 11 - Not working for amin & edit - method 'assign' doesn't support property.

### ISSUE THREAD

**Issue by GwendolinePouet** [2sic/2sxc#1376]
**I'm submitting a ...** 
[x] bug report  

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] JS development

**Current behavior**
2sxc 9.6.0 and 9.8.0 not working on IE because method 'assign' doesn't support. I try to use a prolyfill for method 'assign' but it's not working when eav-admin.min.js is called. This is logs after click on edit button : 
![image](https://user-images.githubusercontent.com/15940924/32782988-871fd25c-c94a-11e7-995b-35b81aa0cf66.png)

**Expected behavior**
It's OK for Chrome, Firefox and Edge.

**Minimal reproduction of the problem with instructions**
Install 2sxc on IE.

**What is the motivation / use case for changing the behavior?**
10% of web users (desktop) use IE.

* **2sxc version(s):** 9.6.0 ans 9.8.0
* **Browser:** IE 10 & 11
* **DNN:** 7.4.2

**Anything you would like to add**
I know you consider IE bugs as minor but there are still user, I hate this browser but it's not unimportant in my opinion.

**Comment by iJungleboy** [comment]
This should be solved with a polyfill. Could you look for a good polyfill to save us some time?

**Comment by GwendolinePouet** [comment]
Ok I try again but will you solve the problem for the next versions ?

**Comment by iJungleboy** [comment]
If you post a link to the best polyfill we'll fix it asap in 9.8.1 or 9.9

**Comment by GwendolinePouet** [comment]
Thanks :)
