### ISSUE TITLE
ListPresentation is null after upgrading from 9.52 to 9.8

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#1377]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 
**...about**   

[x] Razor templating
**Current behavior**

A lot of my razor scripts are failing as they don't test whether ListPresentaion is null or not.
However, ListPresentation is set. it is only null within the Razor script.

**Expected behavior**

My sites are looking the same as before the upgrade.

I fixed the most important Razor scripts, now the content is shown again, but as the configuration is missing, it looks rubbish!

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **2sxc version(s):** 9.8.0  
* **Browser:** all 
* **DNN:**   8.X.X 
* **Language:** any

**Comment by SCullman** [comment]
And all unfixed scripts are easy to tag for everyone, even vor anonyous guests    

![image](https://user-images.githubusercontent.com/5693190/32907835-ca5a4ec2-cb01-11e7-94f2-b02847a6b6f9.png)
:-(

**Comment by SCullman** [comment]
Looks like I have to update my scripts and replace 
``ListPresentation`` with ``ListContent.Presentation``

**Comment by iJungleboy** [comment]
Very sorry about this. This is not intended - the ListContent.Presentation is the newer syntax (since ca. 2sxc 8+) but the other one should still work, because a lot of code out there uses that old syntax. I'll try to fix & release this weekend.

**Comment by iJungleboy** [comment]
I found the issue:
```
public dynamic ListPresentation => AppAndDataHelpers.ListContent?.ListPresentation;
```
Should be 
```
public dynamic ListPresentation => AppAndDataHelpers.ListContent?.Presentation;
```
Visual Studio couldn't catch this, because ListContent is dynamic.
