### ISSUE TITLE
Can't delete Entity Field when in use

### ISSUE THREAD

**Issue by lucatescari** [2sic/2sxc#1378]
**I'm submitting a ...**  
[x] bug report

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**

When I have a contenttype with an entity field, which is in use (has values in some data recrods) I cannot delete the entity field.
When I remove the values from all data records, I can delete the field.

**Expected behavior**

2sxc should prompt me, and ask me if I really want to delete the field, since it's in use.

**Minimal reproduction of the problem with instructions**

1. Create ContentType with Entity field
2. Create a few data records
3. Try to delete the entity field

**What is the motivation / use case for changing the behavior?**

Should be standard 2sxc behavior that this works.

**Please tell us about your environment:**

* **2sxc version(s):** 9.8  
* **Browser:** [all]
* **DNN:** [9.1.X ] 
* **Language:** [any/all]

**Comment by eXistenZe** [comment]
I second this issue with 2sxc 9.10. Getting 400 error when trying to delete a used field.

**Comment by iJungleboy** [comment]
For a temporary workaround, go to the items which have content and remove the children, then delete the field. mass-changes could be done with export/import.

**Comment by eXistenZe** [comment]
No need. The extra field does not bother anything.

**Comment by eXistenZe** [comment]
This is an old issue but still present in v13. We cannot delete a field of entity type that has content. Since there are hundreds of entries in the table, deleting one by one is not an option.
