### ISSUE TITLE
Handling of Null for Numbers

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#1383]
**I'm submitting a ...**  
[x] bug report 

**...about**   
[x] edit experience / UI
[x] Razor templating
[x] Content Types or data management

**Current behavior**

* Add a field with datatype ``number`` (not required)
* Add a record but leave the number field blank
* Edit the record again, and you will notice that the input is set to "0" (wrong)
* The value is shown as blank in "Manage Content/ Data" (correct)
* The value is 0 within razor scripts

**Expected behavior**
* The input field in the edit form should be blank
* the field should be ``null`` within Razor scripts.

**Please tell us about your environment:**

* **2sxc version(s):** 9.8.0

**Comment by iJungleboy** [comment]
Yes, I can reproduce this. Has various side effects, must be fixed asap.

**Comment by iJungleboy** [comment]
I tried it - but then again I can't reproduce it right now. Not sure where it's going wrong... the number stays empty in the admin-GUI...

**Comment by iJungleboy** [comment]
Ok, I think a can half-reproduce it:

* Add a field with datatype number (not required)
* Add a record but leave the number field blank
  * the number is still null, even after saving and re-loading and re-editing
* Edit the record again, set to zero
* edit the record again, remove the zero
  * if I now edit again, it is not blank any more, but "0" (wrong)
* The value is shown as blank in "Manage Content/ Data" (correct)
* The value is 0 within razor scripts

So yes, something is wrong. Let me try to find out how/why...

**Comment by SCullman** [comment]
Thanks :-)
