### ISSUE TITLE
Feat: Input field - string - multiple selection (list or radio)

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1399]
**I'm submitting a ...** 
[x] feature request

**...about** 
[x] edit experience / UI
[x] admin experience UI
[x] Razor templating

**Current behavior**
You can create a multiple selection with entity field type, but requesting that data in a template is quite bothersome.

**Expected behavior**
A simple string field could be used to store multiple selection data, with the same form format the "entity" one does, or with radio buttons. Data could be stored with a default separator or a custom one (would be awesome).

**What is the motivation / use case for changing the behavior?**
It would be great to be able to call the content of that field with @Content.field in a template to replace a custom <br> separator for example.

**Comment by iJungleboy** [comment]
this is related to #1385 as there a similar need will exist

**Comment by eXistenZe** [comment]
Can't talk about specifics since I don't have to knowledge to do so, but it could use the same field properties as a dropdow (list the options in a textarea). It just generates radio buttons instead of a dropdown.

**Comment by iJungleboy** [comment]
just fyi: we're just adding a string-dropdown-query which isn't exactly what you asked for, but probably 99% of the way. The only difference is that the values don't come from a text-box configuration, but from entities in the system... - see #1385

**Comment by eXistenZe** [comment]
As long as I can call the content of the field easily in razor...

**Comment by iJungleboy** [comment]
That is given :). Try 9.11, I just released it. I think you'll love it...

**Comment by eXistenZe** [comment]
Does't work yet: https://github.com/2sic/2sxc/issues/1404
