### ISSUE TITLE
2sxc 9.10 breaks Simple Parent/Child app

### ISSUE THREAD

**Issue by andyduo** [2sic/2sxc#1403]
**I'm submitting a ...**  
[x] bug report

**...about**   

[x] Razor templating
[x] other / unknown

**Current behavior**

Adding the Simple Parent/Child app to a page generates the following exception:
Error: System.Web.HttpCompileException (0x80004005): 
CS0815: Cannot assign method group to an implicitly-typed local variable at System.Web.Compilation.AssemblyBuilder.Compile() at System.Web.Compilation.BuildProvidersCompiler.PerformBuild() at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound) at System.Web.Compilation.BuildManager.GetCompiledType(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetCompiledType(String virtualPath) at ToSic.SexyContent.Engines.RazorEngine.CreateWebPageInstance() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 71 at ToSic.SexyContent.Engines.RazorEngine.InitWebpage() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 106 at ToSic.SexyContent.Engines.RazorEngine.Init() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 26 at ToSic.SexyContent.Engines.EngineBase.Init(Template template, App app, ModuleInfo hostingModule, IDataSource dataSource, InstancePurposes instancePurposes, SxcInstance sxcInstance, Log parentLog) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Engines\EngineBase.cs:line 58 at ToSic.SexyContent.SxcInstance.GetRenderingEngine(InstancePurposes renderingPurpose) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\SxcInstance.cs:line 265 at ToSic.SexyContent.SxcInstance.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\SxcInstance.cs:line 222

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Win server 2012 r2 

* **2sxc version(s):** 9.10 
* **Browser:** [all ]
* **DNN:** [ 8.0.4] 
* **Language:** [ English ]

**Anything you would like to add**
I posted this on Stackoverflow but think maybe this is an introduced bug? Is it possible to get this App working again? It's a good starting point for creating a simple Parent child app in 2sxc.

**Comment by iJungleboy** [comment]
this is probably due to the breaking change we introduced. which app did you use ? we'll then update it to the latest version.

**Comment by andyduo** [comment]
Thank you so much. It was the Parent Child app
[https://2sxc.org/en/apps/app/simple-parent-child-app-with-2-pages](url)

I used this as the basis for my app which is giving the same error so I'm hopeful I could bring the changes across.

**Comment by iJungleboy** [comment]
just fyi: i'm assembling a blog with guidelines how to fix this. I'll also fix the app, but here's the current draft of the blog: https://2sxc.org/en/blog/post/fixing-the-breaking-change-in-2sxc-9-8-list-instead-of-dictionary

**Comment by andyduo** [comment]
Thanks for this. I'm having trouble getting this to work and wonder if you could point me in the right direction? This is lifted from the APP but my attempts to rewrite it have failed so far:

@using ToSic.Eav.DataSources
@{
	var filterById = CreateSource<EntityIdFilter>();
	filterById.EntityIds = "[QueryString:ID]";
	var a = filterById.List.FirstOrDefault().Value;
}

**Comment by iJungleboy** [comment]
you're close, just drop the .Value

`var a = filterById.List.FirstOrDefault();`

**Comment by andyduo** [comment]
Hmm OK, that then gives me an error on this line:  
// 1. leave the simple API, go to the power API of entities, must be typed to work
        ToSic.Eav.IEntity ent = AsEntity(details);

error CS0234: The type or namespace name 'IEntity' does not exist in the namespace 'ToSic.Eav' (are you missing an assembly reference?)

**Comment by andyduo** [comment]
I think I fixed it by just commenting out the line ToSic.Eav.IEntity ent = AsEntity(details);

**Comment by iJungleboy** [comment]
use either
ToSic.Eav.Interfaces.IEtity ent = ...

or 
ToSic.Eav.Data.Entity ent =

**Comment by andyduo** [comment]
Got it! Thanks a bunch for helping me get this sorted @iJungleboy Much appreciated.

**Comment by iJungleboy** [comment]
just released a completely updated version. 
App catalog: https://2sxc.org/en/apps/app/simple-parent-child-app-with-2-pages
Github: https://github.com/2sic/app-tutorial-parent-child-2views

**Comment by andyduo** [comment]
Hi @iJungleboy I'm trying to update my code for the latest version of 2sxc similar to the Parent Child App but the following code breaks:

@using ToSic.Eav.DataSources
@{
	var filterById = CreateSource<EntityIdFilter>();
	filterById.EntityIds = "[QueryString:ID]";
	var a = filterById.List.FirstOrDefault().Value;
}

Looking at the blog post you did on this and attempting to update the above I'm unsuccessful at getting it to work. Could you possibly give an example of this case?

**Comment by iJungleboy** [comment]
@andyduo this is most likely due to the breaking change https://2sxc.org/en/blog/post/fixing-the-breaking-change-in-2sxc-9-8-list-instead-of-dictionary

A newer version of 2sxc would have pointed you to that link. If I'm right, just remove the ".Value" at the end and you're good to go.

**Comment by andyduo** [comment]
@iJungleboy Thank you for that. I got the app working however I have an issue with it which I have asked about at the bottom of this thread [#1284](https://github.com/2sic/2sxc/issues/1284) regarding 'Non-negative number required'

**Comment by iJungleboy** [comment]
see answer I wrote there.
