### ISSUE TITLE
"Fields of this content-type" button does not work in data mode

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1407]
**I'm submitting a ...**
[x] bug report

**...about**
[x] admin experience UI

**Current behavior**
When I click "Fields of this content-type" green button on the toolbar, the page stops working and nothing happens (like a blank div opens on top). This only happens when using data mode - if no content is associated with the view.

**Expected behavior**
I think the button should not show when a content is not associated with the view, since 2sxc has no way to know what entity to show.

**Minimal reproduction of the problem with instructions**
Described above.
This error shows in console:
```
set.min.js?sxcver=9.11.0.22902:118
TypeError: Cannot read property 'Header' of undefined
    at eav-admin.min.js?sxcver=9.11.0.22902:2
    at set.min.js?sxcver=9.11.0.22902:131
    at m.$eval (set.min.js?sxcver=9.11.0.22902:145)
    at m.$digest (set.min.js?sxcver=9.11.0.22902:142)
    at m.$apply (set.min.js?sxcver=9.11.0.22902:146)
    at l (set.min.js?sxcver=9.11.0.22902:97)
    at J (set.min.js?sxcver=9.11.0.22902:102)
    at XMLHttpRequest.t.onload (set.min.js?sxcver=9.11.0.22902:103)
```

* **2sxc version(s):** 9.11
* **Browser:** [Chrome 66 | Edge]
* **DNN:** [9.1.1 ] 
* **Language:** [English]

**Comment by iJungleboy** [comment]
thx!

**Comment by iJungleboy** [comment]
I believe this is not an isuse any more, but we didn't verify. Pls post if it's relevant. will close for now.
