### ISSUE TITLE
Improve installation to keep web.config small

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#1425]
**I'm submitting a ...**  
[x] feature request

**...about**   
[x] installation

**Current behavior**
The changes in the web.config comment out previous items in the web.config. Because of this, the Web.config keeps on growing, and after many, many upgrades will exceed the default limit of web.config size. 

**Expected behavior**
Should not grow the web.config, as this would affect too many users. 

**Please tell us about your environment:**

* **2sxc version(s):** 9.12

**Comment by raphael-m** [comment]
The comments added when upgrading 2sxc are a result of assembly redirects being added to the web.config. DNN automatically adds those if an assembly has a PublicKeyToken.
How the Xml-Merge behaves upon collision is defined in the template `\Install\Config\BindingRedirect.config`, which is not in our control.
