### ISSUE TITLE
Manage Content/Data not showing on all App - 2sxc 9.12

### ISSUE THREAD

**Issue by erw13n** [2sic/2sxc#1427]
**I'm submitting a ...**  
[x] bug report
[x] not sure

**...about**   
[x] admin experience UI
[x] Content Types or data management
[x] APIs like REST

**Current behavior**

Test on Fresh install DNN 8 & 9, install all App, testing add Blog App into content.
When show Current Data, it throw an error
![image](https://user-images.githubusercontent.com/792847/33809879-39822fa4-de30-11e7-8b70-225eb3ad7786.png)

**Expected behavior**

Show all items/data

**Minimal reproduction of the problem with instructions**

Add App Blog module to content, go to configure/manage apps, click Blog app > Data, and click on Author, Blog Post, Category, etc always gave same error.
Testing on the other app also do gave same error.

**Admin Log**
![image](https://user-images.githubusercontent.com/792847/33810033-26120d84-de32-11e7-88a0-85bca8aba191.png)

**Please tell us about your environment:**

Windows 10 & Windows Server 2012

* **2sxc version(s):** 9.11 & 9.12  
* **Browser:** Currently test on [Chrome | Firefox | Edge | IE XX ]
* **DNN:** [all | 8 | 9 ] 

**Anything you would like to add**
Strange behavior, on different computer, create new simple App, sometimes able to show Data/items sometimes not. But still all of Installed App not able to see Data.

**Comment by iJungleboy** [comment]
never got this error report before, so I'm guessing it's something in your system. could you try enabling extensive logging and post the journal: https://2sxc.org/en/blog/post/releasing-2sxc-9-6-with-extensive-logging

**Comment by erw13n** [comment]
@iJungleboy here's the logging
![image](https://user-images.githubusercontent.com/792847/33831086-3460048c-dea9-11e7-9460-75c942b23272.png)

![image](https://user-images.githubusercontent.com/792847/33831098-3d47aeba-dea9-11e7-8b0b-70db0469aa11.png)

Not know why, but it happen on multi sites. Still happen on Fresh DNN site.

I can give you access to it, if you want to check.

**Comment by iJungleboy** [comment]
access would help - info@2sxc.org

**Comment by erw13n** [comment]
OK, just did

**Comment by slicksystems** [comment]
I can produce it every time by doing the following:

1. Install latest DNN9 (DNN_Platform_9.1.1.129-232_Install)
2. Install latest 2sxc (9.12)
3. Delete demo content from fresh dnn site homepage
4. Add 2sxc App Module to page
5. Install recommended 2sxc apps
6. Add the Blog App to the page

Try to view any list of content items from here:
![image](https://user-images.githubusercontent.com/13353102/33847657-84146770-de68-11e7-8299-0fb814172547.png)

Results in this error:
![image](https://user-images.githubusercontent.com/13353102/33847825-10432d6c-de69-11e7-955f-ff45d7e2b6b1.png)

**Comment by iJungleboy** [comment]
thx. I'll try to review within the next few hours

**Comment by erw13n** [comment]
Thank you, looking forward to it

Best Regards,
Erwin Yulianto S W

**Comment by iJungleboy** [comment]
I can reproduce the issue - give me a few hours, should get fixed asap :)

**Comment by iJungleboy** [comment]
Should be fixed - pls try https://github.com/2sic/2sxc/releases/tag/v09.13.00-pre1

**Comment by erw13n** [comment]
Seems working but **only for current App** that put into Page Content.

If I go to **Manage All App** and try to show data that's not on Page Content.

![image](https://user-images.githubusercontent.com/792847/33887821-a9b3d2de-df7d-11e7-82ac-2cef8edaed91.png)

**Comment by erw13n** [comment]
Same error :

**StackTrace:**
at ToSic.SexyContent.Security.PermissionController..ctor(IContentType targetType, IEntity targetItem, Log parentLog, ModuleInfo module) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Security\PermissionController.cs:line 62 at ToSic.SexyContent.WebApi.SxcApiController.PerformSecurityCheck(String contentType, PermissionGrant grant, Boolean autoAllowAdmin, IEntity specificItem, Boolean useContext, Nullable`1 appId) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Sxc WebApi\SxcApiController.cs:line 204 at ToSic.SexyContent.WebApi.EavApiProxies.EntitiesController.GetAllOfTypeForAdmin(Int32 appId, String contentType) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Sxc WebApi\EavApiProxies\EntitiesController.cs:line 216

**Comment by eXistenZe** [comment]
Second this issue.

**Comment by iJungleboy** [comment]
just released 9.13 which fixes this.

**Comment by slicksystems** [comment]
The issue still exists if you are trying to "Manage Content" for apps
outside of the one that you clicked "Apps Management" from.

For example, on the page below, I click "Apps Management" from the
Accordion app:

[image: Inline image 1]

Then from the Manage Apps in this Zone page, I click on another App in the
list (Blog).

[image: Inline image 3]

From there, try to Mange the data for the Blog:

[image: Inline image 1]

Result:

[image: Inline image 2]




*Steve Chaba*
*SlickSystems Technology *Inc.
403.819.5774

[image: Slick Systems Technology Inc.] <http://www.slicksystems.ca>

**Comment by slicksystems** [comment]
The issue still exists in 9.13 if you are trying to "Manage Content" for apps outside of the one that you clicked "Apps Management" from.

For example, on the page below, I click "Apps Management" from the Accordion app:

![image](https://user-images.githubusercontent.com/13353102/34055377-25add3ac-e18c-11e7-8a35-d46ca0b82adf.png)

Then from the Manage Apps in this Zone page, I click on another App in the list (Blog).

![image](https://user-images.githubusercontent.com/13353102/34055389-39e4cd3a-e18c-11e7-9439-3cc9d93bdc3f.png)

From there, try to Mange the data for the Blog:

![image](https://user-images.githubusercontent.com/13353102/34055385-2e77248e-e18c-11e7-9536-49accaba047a.png)

Result:

![image](https://user-images.githubusercontent.com/13353102/34055401-41d9e11a-e18c-11e7-84ee-09b4421ab550.png)
