### ISSUE TITLE
[BUG] REST calls from external return error "Unauthorized"

### ISSUE THREAD

**Issue by Eudoxe** [2sic/2sxc#1432]
**I'm submitting a ...** 
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] APIs like REST

**Current behavior**
In tutorial "Tutorial - JavaScript - using the REST API" (and in my code), the external calls (View 10+ and 13+) return an error "Authorization has been denied for this request" even is the permission condition "SecurityAccessLevel.Anonymous" is set to "Read" (the configuration set out of the box)

**Expected behavior**
We should get a JavaScript of the content

**Minimal reproduction of the problem with instructions**
1. Install "Tutorial - JavaScript - using the REST API" and set a 2sxc application in a page
2. Select template "10+ Get list using REST from "external"
3. Press button "Press to run"

Selecting "13+ Get a query through REST from "external" gives the same error

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **2sxc version(s):** 9.12.0.16156
* **Browser:** [all]
* **DNN:** DNN PLatform v. 09.01.01 (129)
* **Language:** [any]

**Comment by iJungleboy** [comment]
just to be sure - could you log the url used in the app, and are you using it from externa (a non-dnn page) or from the dnn-page?

**Comment by Eudoxe** [comment]
It's the application I downloaded at: https://2sxc.org/en/apps/app/tutorial-javascript-rest-api-using-jquery-and-angularjs (v. 08.10.01 e96af4d0-ccee-45df-8fa2-0159cfcb267a)

The call is made to www.exemple.com/api/2sxc/app/Tut-JS-REST/content/Category

Your application is installed in a DNN page but uses the mechanisms of external calls ($2sxc... working well).

**Comment by eXistenZe** [comment]
I remember I had this issue too in the demo app.

**Comment by iJungleboy** [comment]
I can recreate the issue - thanks for reporting. 
I believe it's a change we made in the permission detection in 9.11 or so, I'll fix asap...

**Comment by iJungleboy** [comment]
fixed in prerelease of 9.14, please test and confirm.
