### ISSUE TITLE
Duplicate apps

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1434]
**I'm submitting a ...** 
[x] feature request
[x] not sure

**...about**
[x] admin experience UI

**Current behavior**
If you try to copy-paste an app folder, it will not be recognized.
If you try to install it again after exporting, it will fail.
If you try to export the content into a new empty app it gives error 500.

**Expected behavior**
There could be an easy way to copy-paste an app (like the mobius forms) or intall it multiple times since it's easier to keep entities separated in apps than havinng them into one giant mess.

**Comment by iJungleboy** [comment]
This is related to #195

**Comment by eXistenZe** [comment]
Any viable workaround?

**Comment by iJungleboy** [comment]
Yes, fairly easy to do. There are 2 things that must be different

1. the folder
2. the app guid

To have a new guid, export the app and reset the guid to null (it's a special checkbox in the export). 

To rename the folder, you need to change it in 2 places - the app-settings and the folder name itself. you'll have to fiddle around a bit (like rename, export, rename back, then import).

**Comment by iJungleboy** [comment]
I'll close this BTW, to make sure we're not tracking the same questions in multiple issues.

**Comment by eXistenZe** [comment]
Thanks. It works.
Btw, the contact form I send about mobius forms and CC based field, please ignore it. Figure it out yesterday. Very simple.

**Comment by iJungleboy** [comment]
perfect :)
