### ISSUE TITLE
Bug: Can't delete ContentBlock in InnerContent

### ISSUE THREAD

**Issue by lucatescari** [2sic/2sxc#1435]
**I'm submitting a ...**  
[x] bug report 

**...about**   
[x] edit experience / UI

**Current behavior**

When I try to delete or move an entry in InnerContent (Using the 2sic Accordion app), I get some errors:
When trying to move:
![image](https://user-images.githubusercontent.com/7703479/34111080-f6dd8552-e408-11e7-8973-a41f96a2b074.png)
When trying to delete:
![image](https://user-images.githubusercontent.com/7703479/34111107-0955968e-e409-11e7-806e-d69570074e5b.png)

**Expected behavior**

I should be able to move or delete InnerContent elements.

**Minimal reproduction of the problem with instructions**

1. Install accordion
2. Create InnerContent
3. Try to move / delete

**What is the motivation / use case for changing the behavior?**

Is a standard feature which should work.

**Please tell us about your environment:**

* **2sxc version(s):** 9.13.0  
* **Browser:** [all]
* **DNN:** [9.X.X ] 
* **Language:** [any/all]

**Comment by iJungleboy** [comment]
ok. As a workaround for a quick-fix, change the field configuration to be visible in the edit-dialog and remove the item there.

**Comment by iJungleboy** [comment]
fixed in prerelease of 9.14, please test and confirm.
