### ISSUE TITLE
[Feat request] Purge entity

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1436]
**I'm submitting a ...** 
[x] feature request

**...about** 
[x] admin experience UI

**Current behavior**
There is no way to quick delete all entries in an entity (perhaps with some complex export->import)

**Expected behavior**
A button could be created for each entity (in the right block of buttons) to purge an entity (perhaps hidden from normal use and shown only in debug mode).

**What is the motivation / use case for changing the behavior?**
When developing a new app, the entities that receive the data from forms will fill with quite a few dozens of test entries. Deleting one at a time is quite slow.

**Comment by iJungleboy** [comment]
At the moment you'll have to use export/re-import, as such a feature won't be implemented in the near future. So i'll close this for now.
