### ISSUE TITLE
"1a" Invalid field name

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1442]
**I'm submitting a ...**  
[x] Not sure

**...about**
[x] admin experience UI

**Current behavior**
When trying to create a new field in an entity, with the name "1a" it gives this error:
Attribute static name "1a" is invalid. Only alphanumerics and underscore is allowed, first char must be alphabetic or underscore.

**Expected behavior**
Is there any reason why the first char must be alphabetic?

**Comment by raphael-m** [comment]
Yes! 2sxc follows the C# specifications of what a valid identifier is, because attributes of an entity must be accessible through attributes of a C# dynamic object. Please find more here: https://stackoverflow.com/a/950656/496950

**Comment by eXistenZe** [comment]
Thanks. Everything okay with Daniel? He's out for some time.

**Comment by iJungleboy** [comment]
yes, I was just on x-mas ;)
