### ISSUE TITLE
Select from query string unable to connect to numeric fields

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1443]
**I'm submitting a ...**
[x] bug report

**...about**
[x] admin experience UI
[x] Content Types or data management

**Current behavior**
I use quite a few fields with the new dropdown-query input type and they all work fine.
Today I found an issue with it. If I select string fields as my source (value and label like the field "auditor"), they work fine, but if one of them is a numeric field (like the "Id"), it will say no records found when trying to use the dropdown.

[Image of bug1](https://pasteboard.co/GZZnI9d.jpg)
[Image of bug2](https://pasteboard.co/GZZnQnQ.jpg)
[Image of bug3](https://pasteboard.co/GZZnVOv.jpg)

No errors on log.

**Expected behavior**
Numeric fields shoud work, since they will be concatenated into the final string field.

**Minimal reproduction of the problem with instructions**
Select a numeric field as value or label in dropdown-query config.

* **2sxc version(s):** 9.14
* **DNN:** [all | 7.4.2 | 8.X.X | 9.1.1 ] 
* **Language:** [English]

**Comment by eXistenZe** [comment]
Oh... Nevermind. The issue is not with the field type.
It's the name and the Title status.
Changed the name to qid and it works.

**Comment by iJungleboy** [comment]
thx! will close

**Comment by eXistenZe** [comment]
Has a general rule, perhaps 2sxc should not allows fields named "id" since they will conflict with the "id" from the visual query.
