### ISSUE TITLE
Copy a row from entity does not refresh the list

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1444]
**I'm submitting a ...**  
[x] bug report

**...about**
[x] Content Types or data management

**Current behavior**
When you click the copy button inside an entity over a record/row of data, it opens that record and when you click save it adds the new record. However, the list does not refresh and you cannot see the record you just entered. Exiting and reentering shows the record.

* **2sxc version(s):** 9.14

**Comment by iJungleboy** [comment]
This is fixed in 10.02
