### ISSUE TITLE
Cannot edit App Settings / Resources when accessing Admin through Manage-All-Apps

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#1451]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   

[x] admin experience UI

**Current behavior**
If I click on eddit App Settings or App Resources, I get an Error 404

config: Object { method: "GET", transformRequest: […], url: "//APATHONASERVER/desktopmodules/2sxc/api/eav/entities/GetAllOfTypeForAdmin", … }
data: "Could not find Content Type 'App-Resources'. 

config: Object { method: "GET", transformRequest: […], url: "//APATHONASERVER/desktopmodules/2sxc/api/eav/entities/GetAllOfTypeForAdmin", … }
data: "Could not find Content Type 'App-Settings'.

**Expected behavior**

Should work
* **2sxc version(s):** 9.14.0. LTS  
* **DNN:** 8.X.X

**Comment by iJungleboy** [comment]
thx! I have a guess...could you give a bit more details

* is this a new installation
* is this a new app on an existing installation

thx

**Comment by SCullman** [comment]
- It is both an old installation and an old app. 
- it already has resources

and I saw the same error again after importing 4 apps into a new portal. The apps were shown, but I couldn't open them and got a 404.
When I click on "Configure Apps/ Apps verwalten", none of the apps are listed. But they are imported and they are working.

**Comment by SCullman** [comment]
![2sxc-apps](https://user-images.githubusercontent.com/5693190/35101501-16477e42-fc60-11e7-90d6-c81690fab7e3.gif)

**Comment by SCullman** [comment]
Weird as I cannot reproduce my initial issue.

**Comment by iJungleboy** [comment]
in this case I'll close this for now, but if it pops up again, please just post it here.

**Comment by SCullman** [comment]
Ok, I think I can see a pattern:

If a site has multiple apps, it depends whether I use _configure_ ![image](https://user-images.githubusercontent.com/5693190/35157406-2901b1e0-fd34-11e7-8cc8-a7909744b5e6.png)  or _manage apps_ ![image](https://user-images.githubusercontent.com/5693190/35157422-3ac7d440-fd34-11e7-8694-1ab74f68d5c5.png)

It always works for _configure_. If I uses manage apps, I cannot edit any deeper content:

- I see the cotent types and I can edit the fields, but I cannot access the data anymore.
- I can configure App Settings and App Resouces, but I can't edit them.

**Comment by iJungleboy** [comment]
ok, thx. I'll change the title...

**Comment by SCullman** [comment]
Merci

**Comment by SCullman** [comment]
Can you please increase the priority on this issue? The problem annoys me almost every day in my work.

**Comment by iJungleboy** [comment]
fixed it - will be in 2sxc 9.23
