### ISSUE TITLE
[Documentation request] Running SQL queries in razor templates

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1452]
**I'm submitting a ...** 
[x] feature request

**...about** 
[x] Content Types or data management

I'm gonna be that client again, that demands top of the line features and documentation on a free app with free support :)

Would it be possible  for you to give us a plain, simple and working example on how to run and output an SQL query in the middle of a razor template in 2sxc?

**A little background:**
As discussed before, I use 2sxc for reasearch projects, and statistics is the most important part of the work I do. With link and visual queries I can do 90% of the work with no hassle at all. However, there are times where I need the optimized database table (with a field - value structure), for example to do a search over multiple columns on a single run (counting the number of "yes" in all questions for example). With a little fiddle I can get this type of data with the following query:
```
SELECT dbo.ToSIC_EAV_Attributes.StaticName, dbo.ToSIC_EAV_Values.Value
FROM dbo.ToSIC_EAV_Values
LEFT JOIN dbo.ToSIC_EAV_Attributes
ON dbo.ToSIC_EAV_Values.AttributeID = dbo.ToSIC_EAV_Attributes.AttributeID
LEFT JOIN dbo.ToSIC_EAV_AttributesInSets
ON dbo.ToSIC_EAV_Values.AttributeID = dbo.ToSIC_EAV_AttributesInSets.AttributeID
WHERE dbo.ToSIC_EAV_AttributesInSets.AttributeSetID = <my entity SetID>;
```
What I don't have is the c# knowledge to implement this on a view code in 2sxc.
How can I output the table that this query outputs?
And if I add a simple SELECT COUNT how can I place the result in a c# var?

I hope I'm not being a complete jackass requesting this stuff, I assure it's a humble request, and if you don't have the time to create an example, could you point me to some documentation I can read on this matter?

BTW, thanks again for this awesome (and free) tool.

Best regards,
João

**Comment by iJungleboy** [comment]
This is something you should post on stackoverflow, as it's not even a feature request ;)

**Comment by eXistenZe** [comment]
True... The feature request would be next :)
First things first then: https://stackoverflow.com/questions/48307868/running-sql-queries-in-2sxc-razor-templates
