### ISSUE TITLE
[Feature request] Content - plain code box

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1454]
**I'm submitting a ...**
[x] feature request

**...about**
[x] edit experience / UI

**Expected behavior**
Sometimes we only need a very good html editor.
DNN editor is a joke for code.
2sxc app works wonders, but it is a way more advanced feature than needed (creating an app, template, etc).
Content sort of works, but it is designed to "design" text and images.

Is it possible to create some sort of template/module that creates a plain and simple HTML/JS/CSS big box editor with only two options: edit code, save, see results? Nothing else or fancy, just add the module, click edit, paste, save.

**Comment by iJungleboy** [comment]
basically there is the html-snippet app for that :) https://2sxc.org/en/apps/app/snippet-inject-html-fragment-css-js-etc

**Comment by eXistenZe** [comment]
That's still like 20 clicks more than a two click solution.

A simple and direct code editor would have a huge audience. At the same
level of app and content modules.

**Comment by eXistenZe** [comment]
DNN lacks a good live code editor.
HTML module is awful (bad indenting and formatting, small window, only HTML, JS has to be in module footer).
Most HTML modules out there are also bad.

Sometimes I just have a code I need to test (a JS fiddle work for example) or update very frequently. Most programmers use VS or similar, but some of us do most codding live on a real site.
Some people come to me and ask me to do just this little change, or fix this detail and whatever. From any computer with no apps installed I can access my site but have no good tools to quickly open and change the code.

2sxc app main editor is just awesome (big window, syntax highlight, quick open and save, etc), but it depends on creating an app and templates. Most of these apps don't even need database access, just a place to open, write, save. No need to fill the 2sxc app list with unwanted content.

Imagine a 2sxc module where you could just open the editor with one click, write the app, save and run. I would find it awesome.

**Comment by iJungleboy** [comment]
I understand the need now. 

I'm pretty sure we won't add this anytime soon, because it's a very technical use case - and we're very focused on keeping things simple to cater to the 95% users who probably don't do this. So please don't expect anything like this soon :(

**Comment by eXistenZe** [comment]
Anyone who does not use VS or codes in a lot of different computers would like this idea.
I understand it's a lot of work for a very specific need, so no problem.

I already use 2sxc as a reference for all my little projects now. It's so easy to create and implement all my ideas (from scratch or from SO examples). Here's some small stuff with my childish codding:

Demo research project 1: https://investigar.pt/Demos/Demo-1-Auditoria-Higiene-m%C3%A3os
Demo research project 2: https://investigar.pt/Demos/Demo-2-Investiga%C3%A7%C3%A3o-Recomenda%C3%A7%C3%A3o-local-trabalho
Drugs admin guide with simple popup on row click: https://servicodeurgencia.pt/centro-de-conhecimento/10-farmacos/101-farmacos-no-su
Drugs calcs by weigth: https://servicodeurgencia.pt/centro-de-conhecimento/10-farmacos/107-calculos-de-farmacos-por-peso
Clinical cases demos: https://servicodeurgencia.pt/formacao/casos-clinicos
Quizs (with live forms it would take me a whole morning to do a single quiz, now with 2sxc I need 15 minutes): https://servicodeurgencia.pt/formacao/quiz-testes-de-conhecimento
Quiz (alternative model): https://servicodeurgencia.pt/formacao/temas-de-formacao/formquiz/formvni

Thank you again for your contribution to the DNN community :)

**Comment by iJungleboy** [comment]
cool stuff. BTW (still secret :) - we're currently working on getting write operations to be 2-10x faster. I think this was something that was on your mind previously as well.

**Comment by eXistenZe** [comment]
If that means that I would no longer have to write a 200ms timeout between every webapi post, awesome :)

**Comment by iJungleboy** [comment]
that's the goal - yes :)
