### ISSUE TITLE
Library of files : CreatedOnDate = 1/1/0001 12:00:00 AM

### ISSUE THREAD

**Issue by pircjernej** [2sic/2sxc#1463]
**I'm submitting **  
[x] bug report 

**...about**   
[x] Content Types or data management

**Current behavior**
When you add files to Library of files and check field name : "CreatedOnDate"
the value is : 1/1/0001 12:00:00 AM

**Expected behavior**
The field shuld have created date

* **2sxc version(s):** 9.14.0  
* **DNN:** [9.1.1 ]

**Comment by iJungleboy** [comment]
thx, we'll check - low priority though. 
As a workaround, you can simply use the standard .net API to check the date

**Comment by pircjernej** [comment]
I don't know how? Can you give me some guidance how to do this?

**Comment by iJungleboy** [comment]
http://lmgtfy.com/?q=c%23+get+file+creation+date :)

**Comment by pircjernej** [comment]
@iJungleboy  Hi, If there is a "done" label, do I need to close this isue?

**Comment by iJungleboy** [comment]
Note that it's not in a released version yet. Will probably release 2sxc 9.15 this or next week containing the fix
