### ISSUE TITLE
Order related entities with drag and drop results in curious/random order

### ISSUE THREAD

**Issue by BeniGemperle** [2sic/2sxc#1465]
**I'm submitting a ...**
[x] bug report => search github for a similar issue before submitting 

**...about**
[x] edit experience / UI
[x] Content Types or data management

**Current behavior**
An entity field with multiple entities can be reordered in the edit-dialog using drag and drop. The first entity is ordered/positioned where expected but following entities move to anywhere.

**Expected behavior**
Reordering entities in the edit-dialog using drag and drop should save the position where dropped.

**Minimal reproduction of the problem with instructions**
![89188f9d-5a0f-40e4-9142-ac54b0182ac1](https://user-images.githubusercontent.com/6669093/35869768-343506e0-0b60-11e8-9e98-7f3a0948f799.GIF)

**What is the motivation / use case for changing the behavior?**

Have a list of people and assign them when they work usually (like monday morning/afternoon, tuesday morning/afternoon, etc.)

**Please tell us about your environment:**
* **2sxc version(s):** 9.14.0
* **Browser:** Chrome 63
* **DNN:** 9.1.0 
* **Language:** German

**Comment by iJungleboy** [comment]
This is a real (and annoying) bug, but we'll close this because it should be resolved in the upcoming angular 6/7 UI.
