### ISSUE TITLE
2sxc on DNN 9.x prevents adding new modules with Firefox

### ISSUE THREAD

**Issue by VashJuan** [2sic/2sxc#1467]
I'm submitting a ...
[x] bug report

...about
[x] edit experience / UI
[x] admin experience UI

Current behavior
Only if 2sxc is installed, when I edit any page and try to add a new module, or copy an existing module, I SHOULD be able to grab the module 'preview' and drag it to the pane on the page where I want it located.

Instead, I can't "grab" it. The appearance is also altered: there's a shadow, but not the 'x' at the upper right.

**Minimal reproduction of the problem with instructions**
see image below

**Please tell us about your environment:**
Running DNN 9.1x on Managed.com.  

* **2sxc version(s):** Most Recent, although I've been seeing this for ~3-4 months.

* **Browser:** Firefox most recent, OH, it does not happen with Chrome - or Edge. YEAH!!!
* **DNN:** 9.x
* **Language:** English 

**Anything you would like to add**
This happens on multiple web sites (same portal though), including base web sites with nothing fancy or any content. If I uninstall 2sxc, the site returns to good behavior. Reinstallign 2sxc then reintroduces the evil behavior.

I've tried it on 2 standard skins: Gravity & Xcellion and it still happens.  

![1-2-2018 at 2 16 57 pm](https://user-images.githubusercontent.com/8594671/36441003-295ee580-1626-11e8-979e-a1fc998736b9.jpg)
![2-20-2018 at 9 47 02 am](https://user-images.githubusercontent.com/8594671/36441035-3aa8f10a-1626-11e8-88e9-cfeb1d580ccc.jpg)

**Comment by eXistenZe** [comment]
I stopped using firefox since it has so many issues with dnn/2sxc and many other sites.

**Comment by iJungleboy** [comment]
Thx for the info and the note about firefox. So it seems to be something related to 2sxc + firefox on DNN 9+

**Comment by VashJuan** [comment]
Yes. Since I mainly use Firefox I seemed HUGE (quoting Trump), but knowing there's an *easy* work around, makes it seem trivial (like his mental powers). The reporting process forced me to check some options I hadn't!

**Comment by michaelcunningham1974** [comment]
I have this same problem with Chrome but only adding ActionForm Modules.

**Comment by iJungleboy** [comment]
I believe it's fixed in 2sxc 9.20, where we refactored all the inpage code to Typescript. Could you verify?
