### ISSUE TITLE
Auto-Configure of Content broken

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#1471]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   

[x] admin experience UI
[x] Content Types or data management

**Current behavior**

* Fresh Install of 2sxc 9.1.4 LTS
* Place content for the first time to the website
* It offers content templates:
   * Bootstrap 3 packages
   * simple packages
* Bootstrap 3 packages will fail
![image](https://user-images.githubusercontent.com/5693190/36976647-9b0af068-207e-11e8-9852-01e08e9d8a84.png)

**Minimal reproduction of the problem with instructions**
Fresh DNN9.1.x, fresh 2sxc install, just start...

* **2sxc version(s):** 9.1.4 LTS
* **Browser:** all

**Comment by iJungleboy** [comment]
is it possible, that the server doesn't have internet access? because the server downloads the packages and installs them.

**Comment by SCullman** [comment]
Only the Bootstrap 3 package fails. I thought both are failing. I  have seen this on two installations.

**Comment by iJungleboy** [comment]
I can reproduce, but don't know why yet...maybe windows 10 has new firewall settings for local?

**Comment by iJungleboy** [comment]
Seems to be Github - probably because of DDOS. I temporarily created a new storage for these and we'll publish a copy there whenever we create new releases - also briefed @lucatescari . Should work now. 

Thanks so much for publishing!
