### ISSUE TITLE
Icon Picker shows no icons if used in "edit child entity" mode

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#1474]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI

**Current behavior**
if I edit an entity which has a child entitiy field, and that child entity uses an icon picker field, and I edit this entity by the edit popup from the parent entity, the Icon Picker does not show icons to pick. If I select the same entity directly (i.e. with separate 2sxc-Toolbar for this entity) it shows up normally.
(see Screencast below)

**Expected behavior**
the Icon Picker show icons to pick, regardless if I edit an entity with Icon Picker directly or by parent entity (as a child entity).

**Minimal reproduction of the problem with instructions**
1. create two (2) content types (CT)
2. create entity field in CT 1 for CT 2
3. add icon picker field on CT 2 (Child)
4. create entries/items in both CTs
5. edit any item in CT 1, and then edit a child entity (CT 2) direclty from edit popup
6. try to pick an item from the icon picker in CT 2

**What is the motivation / use case for changing the behavior?**
it should make no difference if I edit an item directly or via parent item.

**Please tell us about your environment:**
* **2sxc version(s):** 8.12. - not sure if still an issue in 9.x
* **Browser:** [Chrome]
* **DNN:** [7.4.2] 
* **Language:** [any/all]

**Anything you would like to add**
![icon-bug](https://user-images.githubusercontent.com/12188254/37087530-da9b52ae-21fa-11e8-8185-14adfc2513c9.gif)

**Comment by iJungleboy** [comment]
As we're completely rebuilding the UI with Angular5, it will probably be fixed there. So I'll close this for now, as we won't prioritize this before the Angular5 UI.
