### ISSUE TITLE
REST API Call from "External" - Failing in DNN9

### ISSUE THREAD

**Issue by birksy89** [2sic/2sxc#1478]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   

[x] APIs like REST

**Current behavior**
"Unauthorised" Alert Appears / Postman - Authorisation Error

**Expected behavior**
Return JSON Data Via postman / Append HTML items in Demo

**Minimal reproduction of the problem with instructions**
Clean DNN911 Installation
Install 2sxc 9.14
Install App [REST Tutorial](https://2sxc.org/en/apps/app/tutorial-javascript-rest-api-using-jquery-and-angularjs)
Load **10+ Get List using REST from "external"** OR **13+ Get a query through REST - from external**
Try to retrieve data.

**What is the motivation / use case for changing the behavior?**
Trying to build a React Application

**Please tell us about your environment:**
Windows / Local Dev environment / DNN911 / 2sxc 9.14

* **2sxc version(s):** 9.14  
* **Browser:** [all  ]
* **DNN:** [ 9.X.X ] 
* **Language:** [any/all ]

**Anything you would like to add**
The "10+" demo doesn't work on DNN8 either, but "13+" does.

**Comment by iJungleboy** [comment]
Could you check what error you're getting. Is it the wrong endpoint, is it an http-error, or is the resulting data different?

**Comment by birksy89** [comment]
This is the REST tutorial app
https://2sxc.org/en/apps/app/tutorial-javascript-rest-api-using-jquery-and-angularjs

The error is a 401 (Unauthorized) message when hitting:
http://localhost/api/2sxc/app/Tut-JS-REST/content/Category (Example 10+)
http://localhost/api/2sxc/app/Tut-JS-REST/query/EverythingSorted (Example 13+)

I have not altered the demo app. I re-tested on a clean version of DNN 9.1.1 and reproduced the same result.

Any help would be greatly appreciated.

**Comment by birksy89** [comment]
Permissions:
![Imgur](https://i.imgur.com/5Oun8jx.png)
Query Permissions:
![Imgur](https://i.imgur.com/KCtgVDw.png)

**Comment by iJungleboy** [comment]
I think I found it and fixed it. Seems that DNN changed the behavior of some security checks. The fix will be in 2sxc 9.23 end of this week or early next week. Would appreciate if you could confirm.

**Comment by birksy89** [comment]
This now works great. Thank you.
