### ISSUE TITLE
Fix Incompatibilities with DNN 9.2

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#1494]
**I'm submitting a ...**  
[x] feature request

**...about**   
[x] DNN parts

**Current behavior**
Some things break - we'll try to collect them here for fixing

* Import App fails, because of incompatible SharpZipLib included in DNN 9.2

**Affected Versions**

* **2sxc version(s):** 9.14 and earlier

**Comment by Accuraty** [comment]
Is this actually incompatible or can it be fixed manually with a binding redirect in web.config?

**Comment by iJungleboy** [comment]
The Zip issue is completely incompatible - a redirect will not solve it. DNN Corp and the Community Technology Team are trying to find a solution around it, as it will affect all components that have some kind of zipping included.

**Comment by Accuraty** [comment]
Wow, that is surprising - I understand they are being aggressive about modernizing, but this seems like a heavily used library. So... based on my understand of 9.14.xx, does this mean we will see a 9.14.01 to address this soon?

**Comment by iJungleboy** [comment]
In terms of release management, we fist have to find a strategy how to do it - because there is no clean solution. Basically modules compatible with DNN 9.1 are incompatible with 9.2 and visa versa. So our priority will be to release a large 9.20 (we're skipping some version numbers, so people realize it's a very large release) and we'll probably try to resolve it there, before we try to provide a stable update to 9.14 LTS, as we don't want to experiment on the LTS editions.

**Comment by iJungleboy** [comment]
To all who read this

1. A quick fix to get 9.14 to run (not all bugs known yet) is to copy the SharpZipLib.dll from a DNN 7/8 into the 9.2, and it should probably work. 

The solution we'll probably use is to change our distribution to include the new SharpZipLib (which is in DNN 9.2) and include it in DNN 7/8.

**Comment by iJungleboy** [comment]
I think we're ready, will publish today...
