### ISSUE TITLE
Modified don't work

### ISSUE THREAD

**Issue by pircjernej** [2sic/2sxc#1495]
**I'm submitting a ...**  
[x] bug report 

**...about**  
[x] Razor templating
[x] Content Types or data management
[x] other / unknown

**Current behavior**
When I using Modified field it return created value

**Expected behavior**
I expected update time value

* **2sxc version(s):** 9.14  
* **DNN:** [9.1.1 ]

**Comment by iJungleboy** [comment]
thx, will look into it

**Comment by pircjernej** [comment]
It seems that is not implemented yet and is very hard to found who make some mistake... For now, the only way for me is to check database directly and look for ChangeLogCreated and that way I can find Timestamp and User in ToSIC_EAV_ChangeLog.. But this is very hard.
