### ISSUE TITLE
9.21.0 with dnn 9.2.0 install errors

### ISSUE THREAD

**Issue by jncraig** [2sic/2sxc#1510]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] other / unknown

**Current behavior**

I instaled the .21 version in a relatively clean DNN 9.2.0.  I ran into some issues trying to install the Blog module after installing all of the recommended modules.

Deleting the module (app and content) doesn't remove all components, even if Delete Files is selected.  I have lots of .pdb files.  Also I have 3 desktop modules folders:  ToSIC_Imazen_ImageResizer, ToSIC_SexyContent, tosic_sexycontent_.

I reinstalled the module and got the message that it was already installed, with choices to repair, etc.  I selected Repair and all went well.  I deleted and reinstalled a second time with no hiccups.

Reinstalling the recommended modules resulted in an error.  "An error occurred" in a popup.  And with this in the event log:

04/06/2018 12:59:14
Admin Alert
host 
 
2sxc-Api Auto-Log Exception 2sInst(05 install package:http://2sxc.org/Port 
2sxc-Api:Auto-Log Exception

2sInst(05):install package:http://2sxc.org/Portals/0/adam/AppCatalog/5EMutByRNEWtODu1sMkpDg/Download/2sxcApp_Blog_03.00.02.zip

2sInst(05)Zip.Imp(30):import zip from url:http://2sxc.org/Portals/0/adam/AppCatalog/5EMutByRNEWtODu1sMkpDg/Download/2sxcApp_Blog_03.00.02.zip, isApp:True

2sInst(05)Zip.Imp(30):try to download:http://2sxc.org/Portals/0/adam/AppCatalog/5EMutByRNEWtODu1sMkpDg/Download/2sxcApp_Blog_03.00.02.zip to:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\0vepwmue.3dt.zip

2sInst(05)Zip.Imp(30):import zip temp-dir:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe

2sInst(05)Zip.Imp(30):extract zip to:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe

2sInst(05)Zip.Imp(30):will create temp dir len:155 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\2sexy\assets\scripts.js

2sInst(05)Zip.Imp(30):will create temp dir len:154 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\2sexy\assets\style.css

2sInst(05)Zip.Imp(30):will create temp dir len:156 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\2sexy\assets\tinysort.js

2sInst(05)Zip.Imp(30):will create temp dir len:148 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\2sexy\.gitignore

2sInst(05)Zip.Imp(30):will create temp dir len:150 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\2sexy\app-icon.png

2sInst(05)Zip.Imp(30):will create temp dir len:147 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\2sexy\debug.log

2sInst(05)Zip.Imp(30):will create temp dir len:145 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\2sexy\LICENSE

2sInst(05)Zip.Imp(30):will create temp dir len:147 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\2sexy\README.md

2sInst(05)Zip.Imp(30):will create temp dir len:162 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\2sexy\_1 Main blog view.cshtml

2sInst(05)Zip.Imp(30):will create temp dir len:156 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\2sexy\_Feed (RSS).cshtml

2sInst(05)Zip.Imp(30):will create temp dir len:153 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\2sexy\_library.cshtml

2sInst(05)Zip.Imp(30):will create temp dir len:155 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\2sexy\_list-item.cshtml

2sInst(05)Zip.Imp(30):will create temp dir len:151 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\2sexy\_pager.cshtml

2sInst(05)Zip.Imp(30):will create temp dir len:158 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\2sexy\_Post Details.cshtml

2sInst(05)Zip.Imp(30):will create temp dir len:164 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\2sexy\_Post micro preview.cshtml

2sInst(05)Zip.Imp(30):will create temp dir len:161 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\2sexy\_Posts by author.cshtml

2sInst(05)Zip.Imp(30):will create temp dir len:167 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\2sexy\_Tag Cloud - Automatic.cshtml

2sInst(05)Zip.Imp(30):will create temp dir len:204 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\PortalFiles\adam\Blog App\BWSkTym0m06Ys1M-FU_HEw\Image\Dnn Blog Logo.png

2sInst(05)Zip.Imp(30):will create temp dir len:208 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\PortalFiles\adam\Blog App\He6UU4TUSkafV9gGCkzg2w\Image\Apps for the Blog.png

2sInst(05)Zip.Imp(30):will create temp dir len:197 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\PortalFiles\adam\Blog App\oIsyjlMOf0uYH28aJpPMJA\Image\header.jpg

2sInst(05)Zip.Imp(30):will create temp dir len:220 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\PortalFiles\adam\Blog App\pakAC6Rvrk6QaJ5baLxgvg\Image\Banner New Blog App Version 3.jpg

2sInst(05)Zip.Imp(30):will create temp dir len:221 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\PortalFiles\adam\Blog App\pF96QbLyR0uypVZwY-q2kQ\Image\Banner may the fourth for blog.png

2sInst(05)Zip.Imp(30):will create temp dir len:217 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\PortalFiles\adam\Blog App\SYmjgbF4jEK6DSeirPTi0w\Image\Daniel Mettler Profile MVP.png

2sInst(05)Zip.Imp(30):will create temp dir len:139 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\App.xml

2sInst(05)Zip.Imp(30):will create temp dir len:151 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\App installation instructions.txt

2sInst(05)Zip.Imp(30):will create temp dir len:129 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\License.txt

2sInst(05)Zip.Imp(30):will create temp dir len:134 path:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\ReleaseNotes.txt

2sInst(05)Zip.Imp(30):folder:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps

2sInst(05)Zip.Imp(30):folder:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App

2sInst(05)Zip.Imp(30):xml file:C:\Users\Joe\Documents\Websites\dnn920\Website\desktopmodules\tosic_sexycontent_\1b01da91-8706-4f61-a1ee-31c8292c8bbe\Apps\Blog App\App.xml

2sInst(05)Zip.Imp(30)Xml.ImpFil(aa):is compatible check

2sInst(05)Zip.Imp(30)Xml.ImpFil(aa):is compatible completed

2sInst(05)Zip.Imp(30):will do app-import

2sInst(05)Zip.Imp(30):check version requirements eav:08.09.00, host:07.02.00

2sInst(05)Zip.Imp(30):version check completed

2sInst(05)Zip.Imp(30):had found errors during import, will throw

Server Name: jnc

**Expected behavior**
no errors

**Minimal reproduction of the problem with instructions**
Described above

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
windows 10, dnn 9.2.0, 2sxc 9.21.0

* **2sxc version(s):** 9.X.X  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [all | 7.4.2 | 8.X.X | 9.X.X ] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**

**Comment by jncraig** [comment]
Clearing out folders in Portals/0 allowed me to reinstall the suggested apps.

**Comment by jncraig** [comment]
Add odd to odd, and you still get odd.

I went to lunch.  On my return, the problem was solved ... I did nothing.

**Comment by iJungleboy** [comment]
@jncraig This has to do with DNN and how it handles files. It has real files on the folder, + a DB index listing these. If the files exist OR the DB doesn't know they don't exist any more, you'll run into problems. So usually such a clean-up requires deleting the files and refreshing the index in the file management. Sorry :(

**Comment by jncraig** [comment]
No problem!
