### ISSUE TITLE
Unable to add new items to list in App

### ISSUE THREAD

**Issue by andyduo** [2sic/2sxc#1511]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   

[x] Content Types or data management

**Current behavior**

Trying to SAVE a new item to a list gives the following error:
Bad Request
There are more presentation elements than content elements

The item is still created on SAVE but not shown on the site.

**Expected behavior**

A new entity should be saved to the list and shown on the site.

**Minimal reproduction of the problem with instructions**

**Please tell us about your environment:**

Win Server 2012R2 

* **2sxc version(s):** 8.5.6  
* **Browser:** [all]
* **DNN:** [ 9.00.02 ] 
* **Language:** [English]

**Anything you would like to add**
In debug mode >2SexyContent-ContentGroup I can see that there are 24 items under Content and 25 under Presentation but have no idea how to remove the extra Presentation item or if this would fix the issue.

**Comment by iJungleboy** [comment]
This is an old issue in some releases of 2sxc. Please check https://github.com/2sic/2sxc/issues/1158
