### ISSUE TITLE
Editing an app with no items raises the exception "Specified argument was out of the range of valid values.Parameter name index"

### ISSUE THREAD

**Issue by mconta** [2sic/2sxc#153]
An App defined with a template but with no content type shows the menu button "Edit".

If the button is clicked the page is reloaded with the exception : Specified argument was out of the range of valid values.Parameter name index.

The edit button should be disabled if the App has no content type.

**Comment by iJungleboy** [comment]
I believ this is fixed - at the very least 7.3+
