### ISSUE TITLE
Copy Entity should also copy private child entities as new/separate entities

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#1530]
**I'm submitting a ...**  
[x] bug report OR
[x] feature request

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management

**Current behavior**

If you use the 2sxc "manage content items" view to copy an existing entity, which has private child entities, and you delete the private child entities on the copy, they will be deleted also on the original entity.

![manage-copy-button](https://user-images.githubusercontent.com/12188254/38812171-d76e8f5a-418b-11e8-97ee-734dcb7786ea.jpg)

**Expected behavior**
The private child entities will also be copied as separate entities, so deleting them will have no affect on the original.

**Minimal reproduction of the problem with instructions**
1. create 2 content types (CT1-Parent and CT2-Child)
2. on CT1-Parent: create a entity field for private entities from CT2-Child
3. create a new entity (E1) in CT1-Parent, and create some new private entities, save
4. open the 2sxc "manage content items" view, and copy your new entity (E1) -> E2
5. edit E2, and delete the private entities, hit hard delete (as you mostly have to)
6. check E1: the entities are gone now

BTW: generally the same would happen, if I would edit the private child entities via E2, so the entities would also change for E1.

**What is the motivation / use case for changing the behavior?**
Make sure that the system does what's expected -> I would not expect from copied data that it still has any connection to the original data. Happened to me: today I was very surprised as I realized that some of my  data has disappeared, and then I remembered that I removed some of the private child entities from the copy. I had no possibility to restore the data :( luckily I realized it at all.

**Please tell us about your environment:**
DNN 7.4.2.
2sxc 8.12

* **2sxc version(s):** 8.12., probably 9.x too
* **Browser:** [all]
* **DNN:** [all] 
* **Language:** [any/all]

**Comment by iJungleboy** [comment]
At the moment this is almost impossible to do, because the children don't really belong to the parent, so there is no clear way to know that they are "privately" used. 

So basically I'll keep this in mind but on the short term I don't see any fix for this, so I'll close this issue.
