### ISSUE TITLE
Cannot add item

### ISSUE THREAD

**Issue by IbizaLin** [2sic/2sxc#1536]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management

**Current behavior**

When I click add item button it doesn't work.

![image](https://user-images.githubusercontent.com/21231896/39083019-7da1a59a-458f-11e8-9d16-de3e6fa57c39.png)

![image](https://user-images.githubusercontent.com/21231896/39083069-761a7738-4590-11e8-8984-de16f1e13a2e.png)

* **2sxc version(s):** 9.23.0  
* **Browser:** [Chrome 65.0.3325.181]
* **DNN:** [9.01.01] 
* **Language:** [English]

**Anything you would like to add**

**Comment by pircjernej** [comment]
Did this work in version 9.14 ?

Can you add template and also show ContentSpecs

**Comment by iJungleboy** [comment]
@pircjernej to 99% it's actually working, but your template only shows the first item @Content and doesn't loop through the list. Check the @foreach(var item in AsDynamic(Data["Default"]) { ... } snippet in the template designer :)

**Comment by pircjernej** [comment]
@iJungleboy this is not my template. I was thinking the same this is why I ask him to get more code :-)

**Comment by iJungleboy** [comment]
@pircjernej thx :) - I read it too quickly, thought it was you who asked :). @IbizaLin check my comment above.
