### ISSUE TITLE
Tutorial Error - DB using Razor

### ISSUE THREAD

**Issue by TopCat6** [2sic/2sxc#1547]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] Razor templating

**Current behavior**

After update to DNN 9.2 Razor template fails with error. Online demo also fails with error:
https://2sxc.org/dnn-app-demos/en/Apps/Tutorial-Work-with-data-from-the-Internal-DB-using-Razor
My error msg:
Error: System.Web.HttpCompileException (0x80004005): c:\DotNetNuke\Website\[0]\2sxc\Tutorial - Work with data from the Internal DB using Razor\_3. Filter by ID and or Type.cshtml(18): error CS1061: 'object' does not contain a definition for 'EntityId' and no extension method 'EntityId' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?) at System.Web.Compilation.AssemblyBuilder.Compile() at System.Web.Compilation.BuildProvidersCompiler.PerformBuild()
**Expected behavior**

Tutorial demo would work without errors.

**Minimal reproduction of the problem with instructions**

Visit:  https://2sxc.org/dnn-app-demos/en/Apps/Tutorial-Work-with-data-from-the-Internal-DB-using-Razor

**What is the motivation / use case for changing the behavior?**

DNN 9.2
**Please tell us about your environment:**

2sxc 9.22, DNN 9.2, Windows 10 Pro, 
* **2sxc version(s):** 9.22  
* **Browser:** Firefox 59.0.2
* **DNN:** [ 9.2.0 ] 
* **Language:** [English ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
thx - I'll look into it.

**Comment by iJungleboy** [comment]
Looks like it's the breaking change https://2sxc.org/en/blog/post/fixing-the-breaking-change-in-2sxc-9-8-list-instead-of-dictionary

So the two lines 17/18 need to remove the `.Value` and various cases of `.List.Count` need to be replaced with `.List.Count()`.

I'll try to update the examples ASAP but before I distribute it, I'll have to make changes to the App Catalog so people know it's for the newer version of 2sxc. I'll work on it...

**Comment by iJungleboy** [comment]
Updated all code and created new release

https://2sxc.org/en/Apps/app/work-with-raw-internal-data-in-razor-v2

and

https://github.com/2sic/app-tutorial-working-with-eav-data-in-code/releases
