### ISSUE TITLE
Filtering by a date in Visual Query does not work

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#1549]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   

[x] Content Types or data management

**Current behavior**
My content item has a value of datetime "ShowBy", and I want to query only items which a bigger date than today.
I can filter within the razor script, but I fail to do the same within Visual Query

_ShowBy >= 2018-05-03_ works, but not _ShowBy >= [datetime:now|yyyy-MM-dd]_

**Expected behavior**
_ShowBy >= [datetime:now|yyyy-MM-dd_] should work as filter.

**What is the motivation / use case for changing the behavior?**
I want to show a list of current job ads

* **2sxc version(s):** 9.23
* **Browser:** all
* **DNN:** 9.2.0
* **Language:** English

The issue was also reported in Stackoverflow: https://stackoverflow.com/questions/40256490/2sxc-filtering-by-a-date-in-visual-query-does-not-work#

**Comment by iJungleboy** [comment]
Just fyi: I believe it will only fail ATM during design - and you could work around it by providing a test-value in the test values using `[Datetime:now]=2018-05-07`

at runtime it should work. am I right?

**Comment by SCullman** [comment]
Confirmed:
- it works at runtime
- test value [Datetime:now]=2018-05-07 works during design.

I guess all [tokens] are not available at design time and must be set as test values? 
In that case it is not a bug but should be documented?

**Comment by iJungleboy** [comment]
As of now you are correct - all tokens at dev-time must be specified as test values. I'm just not sure where I could document it, that people would get it... gotta think about this.
