### ISSUE TITLE
Default Query in Visual Query not working

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#1550]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] Content Types or data management

**Current behavior**
Create a new app, define some content and add some items.
Create a new query and try to execute.

An error window pops up:
![image](https://user-images.githubusercontent.com/5693190/39584385-91e3fed8-4ef2-11e8-8af6-c7dafdfb8731.png)

**Expected behavior**
It should query some or no data

* **2sxc version(s):** 9.23

**Comment by mvanlaar** [comment]
This is the same error as bug #1548

**Comment by iJungleboy** [comment]
are you sure you are using this with a module that has some kind of data? for example, if a module doesn't have a content-type, it cannot supply any information anyhow.

**Comment by SCullman** [comment]
I did a fresh install of dnn9.2, 2sxc9.23.
New app "test", content item test, new view with demo item. 
Added to page, edit item and saved it.
then i created the query, same error.

**Comment by iJungleboy** [comment]
I think I can reproduce, let me research some more

**Comment by iJungleboy** [comment]
found and fixed! will be released tomorrow :)
