### ISSUE TITLE
JS errors with mobius forms 2sxc 9.30

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1563]
**I'm submitting a ...**
[x] bug report

**...about**
[x] JS development
[x] other / unknown

**Current behavior**
Console reports these errors with mobious app:

```
Uncaught TypeError: Cannot read property 'init' of undefined
    at HTMLDocument.<anonymous> (Nova-QCE-modelo-2?draft=6880:1944)
    at mightThrow (js:209)
    at process (js:211)
```

* **2sxc version(s):** 9.30 
* **Browser:** [Chrome]
* **DNN:** [ 9.2 ] 
* **Language:** [any/all |

**Comment by eXistenZe** [comment]
Sorry, not a 2sxc direct issue.

**Comment by eXistenZe** [comment]
The first error was not 2sxc related.

The real one is caused by this line on mobious app:
`$(function(){ window.appJqF.init(); });`

**Comment by eXistenZe** [comment]
Another error:
- When clicking the toolbar:

Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null
    at more.ts:51
    at new Promise (<anonymous>)
    at Object.code (more.ts:17)
    at e.run (engine.ts:94)
    at e.detectParamsAndRun (engine.ts:44)
    at Cms.ts:41
    at e.do (Cms.ts:52)
    at e.run (Cms.ts:40)
    at t.run (instance-engine.ts:14)
    at HTMLAnchorElement.onclick (Cinesi-2:1)

**Comment by iJungleboy** [comment]
please post mobius issues on that git-repo, as it's not related to 2sxc

**Comment by eXistenZe** [comment]
Sorry. Didn't know there was a git for the app.
There already is an issue for this problem created a month ago...

Not to be pesky and ungratefull, but please mark the 2sxc release with a note: mobious app is broken in this release.

**Comment by eXistenZe** [comment]
Please take a look at the toolbar error. It happens in all 2sxc apps.

**Comment by iJungleboy** [comment]
@eXistenZe could we have access to a system where this happens? otherwise we cannot quickly reproduce this second issue wiht addEventListener.

**Comment by eXistenZe** [comment]
Not possible.  Had to revert to a backup 5 days ago.

**Comment by eXistenZe** [comment]
Please try creating a new empty view and add only
`@Edit.Toolbar(Content, settings: new { hover = "left" })`
Without <div class="sc-element">
