### ISSUE TITLE
Content app ignores views

### ISSUE THREAD

**Issue by Tychodewaard** [2sic/2sxc#1574]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] Content Types or data management
[x] other / unknown

**Current behavior**
When I have added a content module and add basic content (image, title, text), the image is always on the right. Also when I select one of the views image on the left.
This is with the xcillion (bootstrap 4) theme, the koi.json added after install.
If I set the same with on NVquicksite (Bootstrap 4 and koi.json already on board) the behaviour is as expected.

**Expected behavior**
If I select the view "image left" the image is on the left.

**Minimal reproduction of the problem with instructions**
Install DNN 804 and 2sxc 932 pre release, install content module and 
select image left

**What is the motivation / use case for changing the behavior?**
There are still bootstrap 3 sites out there (if that's what is causing it...)

**Please tell us about your environment:**
Local install, DNN 804 - English , 2sxc 932 LTS pre release, chrome

I was recording a 'how to ' video when I detected this. It's on https://www.youtube.com/watch?v=wV33Dn9d6Lc 
Won't be using this for the customer :-)

**Comment by iJungleboy** [comment]
Thanks for the video - that's always awesome to better understand stuff. 

I believe I was able to reproduce your issue, but it's probably a mistake on your side :)

the xcillion-theme is Bootstrap 3. If you give it a koi saying it's bootstrap 4, the output will not match, and result in the effect you're describing. As soon as you tell Koi that it's "bs3" things work as they should (at least that was my impression). 

What do you think?

**Comment by iJungleboy** [comment]
Awesome :)

I love issues that I don't have to fix

**Comment by iJungleboy** [comment]
...and a beer would be just great...
