### ISSUE TITLE
Page freezes in chrome when hundreds of toolbars are on page + large memory use (leak?)

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1576]
**I'm submitting a ...**
[x] not sure

**...about** 
[x] other / unknown

**Current behavior**
When using 2sxc app admin panel, if I start editing data inside an entity with around 500 records, memory consumption in windows slowly spikes from 2gb to 8gb until it becomes unusable. If I close the admin windows and return to app page, problem persists. If I move to another non 2sxc page, issue solves.

**Expected behavior**
Not sure if this is 2sxc related or just chrome being chrome.

**Minimal reproduction of the problem with instructions**
Open app settings, go to entities, open the records of a big entity, edit data.

* **2sxc version(s):** 9.32 
* **Browser:** [ Chrome 66 ]
* **DNN:** [9.2 ]

**Comment by iJungleboy** [comment]
Could you check if it's the edit-dialog, or the in-page stuff. For example, it could be the many hundred 2sxc toolbars on a page - so maybe not related to the edit-dialog. could you check?

**Comment by eXistenZe** [comment]
I did. It happens in pages where there is only one toolbar (but the admin
panel will show the hundreds of records).

**Comment by iJungleboy** [comment]
So I believe it's part of the sxc-inpage system - @tvatavuk could you look into this?

**Comment by iJungleboy** [comment]
found and fixed, will be in next RC
