### ISSUE TITLE
Importing and Exporting Modules

### ISSUE THREAD

**Issue by kieran23101** [2sic/2sxc#1577]
**I'm submitting a ...**
[x] bug report

**...about**
[x] admin experience UI

**Current behavior**
I have made Google maps module that will allow me to selected a different view depending if I was a list and use multiple marker ect.
I export the module and it works fine and I can place the zip in my version control system however when i then go to import this to any other site I get an error with the following wording...

**Could not import the app / package: Sequence contains no elements**

I also used the newest version and got this error:

**Could not import the app / package: An error occurred while updating the entries. See the inner exception for details.**

The app is extremely simple, im unsure why it cant import/export

**Expected behaviour**
What i expect to happen is for the app to import and then allow me to select it to display it to a page. I

**Minimal reproduction of the problem with instructions**
1) Simply make an app with some app settings, multiple views and a couple content types.
2) Head over to the admin of your new app.
3) Click "Export this entire app"
4) Select the top checkbox to include entities etc (This is so you get everything)
5) Go to another DNN installation and try to import this app

* **2sxc version(s):** [9.14.00], [9.31.00]  
* **Browser:** [Chrome 66]
* **DNN:** [8.0.04] 
* **Language:** [English]

**Comment by iJungleboy** [comment]
@kieran23101 thanks for submitting this. I think it was an older error - so what version did you use to export it? because there was some import-export issue related to languages which I believe was fixed in 9.32. Could you check? So actually the export was a bit wrong, but 9.32 also imports the wrong export correctly. could you check?

**Comment by iJungleboy** [comment]
I'll close it for now, as I believe it's fixed. Pls write if this is not the case.
