### ISSUE TITLE
DotNetNuke.Common.Globals' enthält keine Definition für 'IsTabPreview

### ISSUE THREAD

**Issue by websystemsoftware** [2sic/2sxc#1578]
[x] bug report => search github for a similar issue before submitting 

[x] other / unknown

**Current behavior**

I upgrade a DNN 9.1 Installation to 9.2 
after this i become all full with Errors in all 2sxc Modules
it is not possible to show some content
after this i upgrade 2sxc to 09.32.00 and the same Errors......

you can see the error in the atached Printscreen

the Error comes in the HTML Module and also in the Slider App

![2sxc-error](https://user-images.githubusercontent.com/19758307/40832573-eede9544-658b-11e8-8f5d-31e3c6ff1fc2.JPG)

**Comment by iJungleboy** [comment]
thanks for closing - I assume it was not a 2sxc issue, correct?
