### ISSUE TITLE
App-installer in 9.32 puts files into wrong folder 

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#1579]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] app install

**Current behavior**
assets land in /portals/x/[appname]/adam/[appname]/... instead of /portals/x/adam/[appname]/... cause not yet know. 

This then makes the automatic number corrections in the install fail, because it doesn't find the files, so it leaves the old file numbers in the fields. 

_I believe it's related to the multi-app install feature, which probably sets a variable incorrectly for the path_

**Please tell us about your environment:**

* **2sxc version(s):** 9.32.0 Pre1 

Est: ca. 2h

**Comment by tvatavuk** [comment]
I introduced this bug in commit https://github.com/2sic/eav-server/commit/88be1ea913d2b5dc5fc4f20ffa60c1aa03570942 for https://github.com/2sic/2sxc/issues/1554
It was easy to fix, but had to add more functionality for https://github.com/2sic/2sxc/issues/1554
- rename app folder name in temp/.../PortalFiles/adam/ from original to new
- update app.xml in PortalFolders and PortalFiles nodes to use new app folder name instead original
Spent: 5:30h

**Comment by iJungleboy** [comment]
thx!
