### ISSUE TITLE
Missing Visual Query Tab

### ISSUE THREAD

**Issue by sloyer** [2sic/2sxc#1580]
**I'm submitting a ...**  
[x] bug report 
[x] not sure

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Razor templating
[x] Content Types or data management

**Current behavior**
The Visual Query Tab is missing in my admin Editor for Content Types

**Expected behavior**
I should go into the Admin editor of my content types/views and see the query editor tab

**Minimal reproduction of the problem with instructions**
https://i.stack.imgur.com/ET6WO.png
https://i.stack.imgur.com/Fsium.png
https://i.stack.imgur.com/B5Cjy.png

**Please tell us about your environment:**

* **2sxc version(s):** 9.14.0
* **Browser:** all 
* **DNN:** 9.1.1

**Comment by iJungleboy** [comment]
You are currently in the content app. As you can see in the third screenshot https://i.stack.imgur.com/B5Cjy.png there is a note "Important... only for Apps, not for Content".

This is because the UI for app/content are different, and so queries in the content-area would cause many side-effects.

**Comment by sloyer** [comment]
Thank you for the help on this.

I have @iJungleboy  one follow up to this, I have made an app, I have content with fields. 
Then I have a view set up, but I can not get it to spit out content unless I dont have have a content type set, then I can get text to least spit out. 

However when I select a content type, nothing spits out and it says it has no demo item. 

No content type selected - I can get text to show, it wont loop through my four pieces of content or render tokens.
https://imgur.com/R5dzLyg
https://imgur.com/KLqIr5H
https://imgur.com/fnakNcw

If I select content type - it just says no demo content
https://imgur.com/UR3DZdp
https://imgur.com/f9EII10

If I select a demo content
https://imgur.com/2pJPfoE

If I select demo content and not content type
https://imgur.com/2pJPfoE

Im sure I am msising something small and I really appreciate your videos on this, i am missing the connection here, I come from a Drupal background, so I love the idea of this .

**Comment by iJungleboy** [comment]
that's a great question and I love to help BUT you'll need to post it on stack-overflow.

**Comment by sloyer** [comment]
@iJungleboy Oops thank  you for clearing that up, knew that from reading rules in post.
