### ISSUE TITLE
Blog posts not saving - Could not find stored procedure ‘toSIC_EAV_ChangeLogAdd’

### ISSUE THREAD

**Issue by valius79** [2sic/2sxc#1582]
**I'm submitting a ...** 
[x] not sure

**...about**  
[x] other / unknown

**Current behavior**
The module doesn't save posts anymore. When in Manage Content/Data I can see the post, but it is not rendering once you get out. This is the error when we click save now, and we did not upgrade the site. It just stopped working. *Had an error talking to the server (400)), Bad request, Could not find stored procedure ‘toSIC_EAV_ChangeLogAdd’. *

**Expected behavior**
Post should render on the page, and we should be able to save the new ones. 

**Minimal reproduction of the problem with instructions**
Log into the DNN, go to the Blog page, open see all posts, open a single post, click save (not working). Error: *Had an error talking to the server (400)), Bad request, Could not find stored procedure ‘toSIC_EAV_ChangeLogAdd’. * The stored procedure ToSIC_EAV_changeLogSet is still there.

**What is the motivation / use case for changing the behavior?**
It just stopped working.

**Please tell us about your environment:**

Windows 10, HTTPS, Amazon AWS, Visual Studio.

* **2sxc version(s):** 9.32.0 - Upgraded to this version after the issue happened. Still not saving.
* **Browser:** ALL
* **DNN:** 9.1.1
* **Language:** English

**Anything you would like to add**
I already submitted to the StackOverflow and DNN site, and nobody is answering. I see many views but no answers. If somebody please could at least point me in the right direction, it would be greatly appreciated.

**Comment by iJungleboy** [comment]
So I never saw this before - my guess is something happened in the DB, maybe someone deleted a SP or set permissions to this stored procedure or something making it unavailable.  I don't think it's a 2sxc issue. Could you check some more?

Also: you're mentioning that it's looking for `...ChangeLogAdd` and saying that `...ChangeLogSet` is there. That's of course not the same thing. If someone deleted the ChangeLogAdd, try running this:

```
USE [dnn920c]
GO

/****** Object:  StoredProcedure [dbo].[ToSIC_EAV_ChangeLogAdd]    Script Date: 08.06.2018 17:18:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[ToSIC_EAV_ChangeLogAdd] 
	-- Add the parameters for the stored procedure here
	@User nvarchar(255) = null
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	--SET NOCOUNT ON;

	-- Insert statements for procedure here
	INSERT INTO [dbo].[ToSIC_EAV_ChangeLog] ([Timestamp] ,[User])
	 VALUES (GetDate(), @user)

	DECLARE @ChangeID int
	SET @ChangeID = scope_identity()
	EXEC ToSIC_EAV_ChangeLogSet @ChangeID

	SELECT *
	FROM [dbo].[ToSIC_EAV_ChangeLog]
	WHERE [ChangeID] = @ChangeID
END

GO



```

**Comment by iJungleboy** [comment]
Any update on this? As I'm pretty sure someone just deleted the SP on your installation, I'll close this now. Please give feedback, and if it's still an Issue we'll look into it again.

**Comment by valius79** [comment]
This solved our issue. Thank you so much for your time!
