### ISSUE TITLE
Weird layout of 9.32 LTS Release Candidate 2 in DNN 9.2

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#1587]
**I'm submitting a ...**  

[x] bug report => search github for a similar issue before submitting 

**...about** 
[x] other / unknown

**Current behavior**

*** fresh DNN9.2. page ***

![image](https://user-images.githubusercontent.com/5693190/41281949-04f59c60-6e33-11e8-857e-0b1ccefd0180.png)

*** and now with Content placed in Content pane after selecting Simple Content ***

![image](https://user-images.githubusercontent.com/5693190/41282220-dac2816e-6e33-11e8-9400-6c2a4aa9a188.png)

**Minimal reproduction of the problem with instructions**
-  fresh DNN9.2
-  9.32 LTS Release Candidate 2
-  default templates
-  Koi.json doesn't help

**Comment by iJungleboy** [comment]
this looks like a DIV tag isn't closed properly somewhere. Could you check?

**Comment by SCullman** [comment]
I don't think so. Look at the menu, is now also arranged as a column.

**Comment by SCullman** [comment]
Well, I made a typo in the file name of _koi.json_ (it was just ko.json).  
     
I suggest to render less or a more conservative css in the case of a missing (or wrong) koi.json file.

**Comment by iJungleboy** [comment]
ok thx! so in that case, this issue can be closed?

**Comment by iJungleboy** [comment]
What I don't understand is this: if koi.json is missing, you will see a message about that. Why didn't your setup show that message?

**Comment by SCullman** [comment]
Well, it is there, shifted to the right and unreadable.

iJungleboy <notifications@github.com> schrieb am Di., 12. Juni 2018, 20:32:

**Comment by iJungleboy** [comment]
Since DNN 9.2.1 will include a koi.json, I believe this won't usually be an issue any more. So for the moment, we won't do anything yet. If more people run into this, we'll reopen.
