### ISSUE TITLE
Issue when exporting and importing module in another page

### ISSUE THREAD

**Issue by ufoloko** [2sic/2sxc#1592]
[x] bug report 

[x] admin experience UI

**Current behavior**
After export app from one site with version 9.32, when try to instal app in another site, same dnn version and same 2sxc version i receive error /package: The sequence contains no elements

**Expected behavior**
To be able to install without problem an app

**Minimal reproduction of the problem with instructions**
export an app from one dnn 9.2 with 2sxc version 9.32 and try to import on another site, with same versions

Im attaching module trying to install in new site

[2sxcApp_Inmobiliario_00.00.02.zip](https://github.com/2sic/2sxc/files/2164271/2sxcApp_Inmobiliario_00.00.02.zip)

**Comment by wchaspuri** [comment]
I don't exactly have the same issue as @ufoloko but I can't seems to export app at all.   I keep getting the message "Had an error talking to the server (404)". 

The url it is trying to hit is /desktopmodules/2sxc/api/app-sys/ImportExport/ImportContent. 

Importing xml works fine though.

**Comment by iJungleboy** [comment]
this was a bug in an older 2sxc version and should be fixed a while back. I'll close this now.
