### ISSUE TITLE
Text is backwards when i'm editing the Content.

### ISSUE THREAD

**Issue by chipyang** [2sic/2sxc#1597]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI

**Current behavior**
When I try to edit the content it is showing up backward I can use the advance mode, but that defeats the purpose of quick edits. I can edit the Header field and the text will show up fine. This is just not a single module, but across the whole website.

**Expected behavior**
It is supposed to show normal text when typing.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Because it changed.

**Please tell us about your environment:**
Windows Server 2012 R2

* **2sxc version(s):** 9.X.X  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** 08.00.03
![dnn](https://user-images.githubusercontent.com/41443778/42953816-d361572c-8b40-11e8-88ad-13d85e12b5fe.PNG)

* **Language:** English

**Anything you would like to add**

**Comment by Tychodewaard** [comment]
I had the same issue. Upgrading 2sxc to 9.32.1 LTS fixed the problem for me.


Op do 19 jul. 2018 om 17:47 schreef chipyang <notifications@github.com>

**Comment by reto-f-999** [comment]
see here: https://github.com/2sic/2sxc/issues/1594 

[duplicate]
