### ISSUE TITLE
Toolbar does not show before the Page hasn't been reloaded

### ISSUE THREAD

**Issue by lucatescari** [2sic/2sxc#1602]
**I'm submitting a ...**  
[x] bug report

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
When I insert a 2sxc App into the current page, 2sxc won't show me the Toolbars of the current Template (which is chosen automatically by 2sxc).
I have to reload the page, after that, the toolbar gets shown.

**Expected behavior**
The toolbar should get shown without having to reload.

**Minimal reproduction of the problem with instructions**
Steps to reproduce: 
Insert a 2sxc app on a page
try to get the toolbar to show up

**What is the motivation / use case for changing the behavior?**
It is a frustrating bug for new users who are not too familiar with 2sxc.

**Please tell us about your environment:**

* **2sxc version(s):** 9.32.01  
* **Browser:** [all ]
* **DNN:** [ 7.4.2 | 9.1.0 ] (not tested on DNN 8.X.X)
* **Language:** [any/all ]

**Comment by iJungleboy** [comment]
This one is annoying and probably slipped in with an optimization we did - we'll look at it.

**Comment by tvatavuk** [comment]
Reproduced bug for apps that have enabled "Support Ajax Reload" in App Package Definition.
Yes, I assume that problem is related to optimizations in module-bootstrapper.

**Comment by iJungleboy** [comment]
@tvatavuk  But it's not just ajax, it's also js (like the timeline) - which load with page reload.

**Comment by tvatavuk** [comment]
Issues is fixed. Problem was not related to optimizations in module-bootstrapper.

After 2sxc app is added to page, I noticed attribute `data-disable-toolbar="true"` in following html code:
```html
<div class="sc-viewport sc-content-block" data-cb-instance="1575" data-cb-id="1575" data-edit-context="..." data-disable-toolbar="true">
```

Solution was to change value of last parameter in command from `true` to `false`:
```
reloadAndReInit: () => reloadAndReInitialize(getContext(), true, false),
```
https://github.com/2sic/2sxc-inpage/blob/752f034101f69be69f3e6de5fa895877fcc992b6/src/quick-dialog/quick-dialog.ts#L205

**Comment by iJungleboy** [comment]
do you know why it's data-disable-toolbar=true? that sounds wrong... why does it add that to the html?

**Comment by iJungleboy** [comment]
When something is in preview, the app is kind of not final. The user could accidentally use the menu and "make it final" without wanting to, that's why the toolbar shouldn't appear in preview. That's by design. Only when the admin finalizes his choice (by hitting the check button) should it become final. 

So please don't change that functionality.

**Comment by tvatavuk** [comment]
> @tvatavuk But it's not just ajax, it's also js (like the timeline) - which load with page reload.

@iJungleboy please can you check my fix for TimelineJS?

I updated [scripts.js](https://github.com/2sic/app-timelinejs/commit/061275ec90f2e42cb019625c5c26cd2625dcadc6#diff-5ae5afcef25aadb51bfb937ea66beb32) because it looks that old JS code was not compatible with 2sic 9.x.

Old code:
```javascript
var listToolbar = $2sxc(moduleId).manage.getToolbar({ "entity": listContent, "action": "edit" });
```

Updated code
```javascript
var listToolbar = $2sxc(moduleId).manage.getToolbar({"action":"edit","sortOrder":-1,"useModuleList":true});
```

**Comment by iJungleboy** [comment]
this change doesn't look right. Because it's possible to use the entity-id in the toolbar, the list-mode isn't required. Could you re-check? maybe we used to have a property "entity" which is now "entityId" or something?

**Comment by tvatavuk** [comment]
Did a test with JS code in TimelineJS app that use `entityId` where was `entity`.

```js
// var listToolbar = $2sxc(moduleId).manage.getToolbar({ "entity": listContent, "action": "edit" });
var listToolbar = $2sxc(moduleId).manage.getToolbar({"entityId":listContent.EntityId, "action":"edit"});

// var toolbar = $2sxc(moduleId).manage.getToolbar([{ "entity": entry, "action": "edit" }, { "entity": entry, "action": "new" }]);
var toolbar = $2sxc(moduleId).manage.getToolbar([{"entityId":entry.EntityId, "action":"edit"}, {"contentType": "Timeline Entry", "action":"new"}]);
```

After this change, 'Edit' button is working with app data, directly updating Demo item for Content or ListContent and 'New' button is adding new entity item, but item is missing in timeline.

![image](https://user-images.githubusercontent.com/2724850/46349074-4fe72880-c651-11e8-84f6-85e6c56b3b25.png)

Installed 2sxc v8.4.3 to see how TimelineJS works (It looks that TimelineJS app is using content items to populate `Timeline Entries`, and first item of ListContent for `Timeline Settings`). Based on this I updated 'edit' and 'new' buttons to work with content items, with intention to make minimal code changes, but I do not know more elegant solution that that.
