### ISSUE TITLE
ValueSort unable to use URL Parameters 2sxc 9.32.1

### ISSUE THREAD

**Issue by LR38108** [2sic/2sxc#1607]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] Content Types or data management

**Current behavior**

When using ValueSort located in DataSources under "Directions" field it clearly states that "if you have multiple fields to sort by, switch to manual entry in the field". However I am unable to acces anything other than the default dropdown list (asc, desc, 0, 1).

**Expected behavior**

I would like to be able to use my URL Parameters as it is stated here https://github.com/2sic/2sxc/wiki/DotNet-DataSource-ValueSort

**Please tell us about your environment:**

* **2sxc version(s):** 9.32.1  
* **Browser:** [Chrome XX]
* **DNN:** [ 8.00.04 ] 

**Anything you would like to add**
It seems that "Enable Free Text" in ValueSort's settings is not enabled.
![valuesort](https://user-images.githubusercontent.com/35312597/43834503-9d546da8-9b0e-11e8-9e39-735b2e925279.PNG)

**Comment by iJungleboy** [comment]
@LR38108 why did you close this?

**Comment by LR38108** [comment]
Accidentally. Re-opened now

**Comment by iJungleboy** [comment]
fixed, will be in the next release. For a quick fix (if it's urgent), just replace the new `System.Config ToSic.Eav.DataSources.ValueSort.json` in the `ToSIC_SexyContent\.data\contenttypes` from the commit above and restart your DNN.
