### ISSUE TITLE
OWL Slider App shows no images in 2sxc 9.32LTS

### ISSUE THREAD

**Issue by websystemsoftware** [2sic/2sxc#1608]
[x] bug report => search github for a similar issue before submitting 
[x] other / unknown

2sxc version(s): 9.32LTS
Browser: Chrome XX
DNN:9.X.X
Language: any/all

Hello,
I install 2sxc 9.32LTS on a DNN 9.01.01 Installation

i want to use the OWL ImageSlider (Carousel) App

when i insert this App on a Page it shows no Images > see Sreenhot
it shows not the Demo Image and also when i upload a Image it shows no Image

is this a Bug??

lg
Benny
![2sxc-owl-error](https://user-images.githubusercontent.com/19758307/43884747-383e9246-9bb7-11e8-85fe-0dd351b4af8f.JPG)

**Comment by iJungleboy** [comment]
Can anybody reproduce this?

**Comment by eXistenZe** [comment]
Tested the app.
Shows the red flowers image.
Adding new images also works.

**Comment by tvatavuk** [comment]
Vanila install of DNN v9.1.1; 2sxc 9.32.1 and autoinstalled ImageSlider v1.0.2 (OWL ImageSlider (Carousel)) works without problems at my comp. Didn't see any problems while adding new slides.

![image](https://user-images.githubusercontent.com/2724850/44036852-13621af6-9f13-11e8-92fd-df32fff63e0d.png)

![image](https://user-images.githubusercontent.com/2724850/44036968-769613b6-9f13-11e8-9109-2b604fbdd65c.png)

**Comment by iJungleboy** [comment]
@tvatavuk thx. 

@websystemsoftware as others don't experience the same issue, I assume it's something with your environment, so I'll close this.

**Comment by websystemsoftware** [comment]
hi @iJungleboy,
yes i found the problem...
it was some javascript problem in my project....

your product has no problem....

thanks
