### ISSUE TITLE
DNN 2sxc blog sharing parent page's meta title and description

### ISSUE THREAD

**Issue by valius79** [2sic/2sxc#1610]
**I'm submitting a ...**  
[x] not sure

**...about**   
[x] other / unknown

**Current behavior**
something.com/blog/post/examplePostName/ is showing meta title and description of the something.com/blog/ parent page. When we view the source for each of these two pages everything looks correct meta, og:graph, twitter card, but the sharer on the page (AddThis) is still not pulling the right stuff.

**Expected behavior**
Facebook AddThis sharer should show correctly each blog's metadata, not parent main blog page.

**Anything you would like to add**
I already posted on the Stackoverflow to no avail. I thought this might be something you guys have seen before and could be an easy fix. I viewed source on your blog https://2sxc.org/en/blog and everything works as expected when I get in each post. Could it be that we missed someting in the App Settings?
Could you please at least point us in the right direction?

**Comment by iJungleboy** [comment]
could you post the stack-overflow question? I think it would be better to answer it there

**Comment by iJungleboy** [comment]
@valius79 I mean could you paste the link to your question - so I can answer it on SO?

**Comment by iJungleboy** [comment]
could you also post that info to your SO question, so it's "closed" there as well?

**Comment by valius79** [comment]
Did that yesterday. https://stackoverflow.com/questions/51864978/dnn-2sxc-blog-sharing-parent-pages-meta-title-and-description 
Thanks again! Great module!
