### ISSUE TITLE
Template Custom Button Error

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#1611]
**Bug Report about JS Development**

There must have been a recent change in custom buttons because I am getting a new error in old code for a custom button.

**Current behavior**
Custom button code results in an error:

> event is not defined : inpage.min.js:8:15183

**Expected behavior**
The custom code should perform whatever action is requested.

**Minimal reproduction of the problem with instructions**
Add the basic custom button code from the wiki into a template and click the button:

```
<ul class="sc-menu" data-toolbar='{
    "groups": [{ 
        "buttons": [{ 
            "command": { 
                "action": "custom", 
                "customCode": "alert(\"custom button!\")"
            }
        }]
    }]
}'></ul>
```

* **2sxc version(s):** 99.32.1
* **Browser:** all
* **DNN:** 9.2.1
* **Language:** any

**Comment by iJungleboy** [comment]
ok, we'll check.
