### ISSUE TITLE
Error adding a new folder in Image Manager v9.32.01 LTS DNN  9.01.00

### ISSUE THREAD

**Issue by andyduo** [2sic/2sxc#1613]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI

**Current behavior**

Using the image manager in a content item click on the New Folder button, give the folder a name and click OK. Error message give a Bad Request pop up with a 400 bad request. Details: Object reference not set to an Instance of an object. Console shows the error occurs relating to set.min.js?sxcver=9.32.1.40885:103. The folder is being created but you don't see it until you refresh the page and go back into edit the content item.

**Expected behavior**

A new folder should be created for the user.
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Win Server2012r2
* **2sxc version(s):** 9.32.01 LTS  
* **Browser:** [Chrome Version 68.0.3440.106 | Microsoft Edge 42.17134.1.0 ]
* **DNN:** [9.01.00 ] 
* **Language:** [English]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
This should resolve itself in the upcoming angular 6/7 edit UI, so I'll close for now.

**Comment by andyduo** [comment]
Just tried 9.35 but still has this error. Should this be resolved?

**Comment by iJungleboy** [comment]
It's not fixed yet, but we should be releasing a completely new UI in about 4-6 weeks, so we don't want to invest any time fixing things in the old ui.

**Comment by andyduo** [comment]
OK thanks for that. just checking it wasn't just me. New UI sounds exciting!
