### ISSUE TITLE
When inserting a new app the template selection gets skipped

### ISSUE THREAD

**Issue by rf-999** [2sic/2sxc#1615]
**I'm submitting a ...**  
[x] bug report

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
if I insert a new 2sxc App module, I can select the app type, but the template selection gets skipped. It automatically chooses the first template. (probably because of an automatic page reload?)

**Expected behavior**
Show the template selection, to make the user select the desired template.

**Minimal reproduction of the problem with instructions**
1. Insert new 2sxc App module
2. Choose app with different templates
3. wait for the template selection which never comes up

**What is the motivation / use case for changing the behavior?**
straight editing process?

**Please tell us about your environment:**
2sxc 9.32.1

* **2sxc version(s):** 9.32.1  
* **Browser:** [Chrome, probably also other ones]
* **DNN:** [7.4.2, probably also 8 and 9] 
* **Language:** [any/all]

**Comment by iJungleboy** [comment]
thx. We can reproduce it and it's not sexy :). we'll look into it.

**Comment by iJungleboy** [comment]
Closed because of inactivity, will reopen if it surfaces again.
