### ISSUE TITLE
"Clear formatting" button not working

### ISSUE THREAD

**Issue by LesiaDesign** [2sic/2sxc#1618]
**I'm submitting a ...**
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI

**Current behavior**
Pressing of the Clear Formatting button does not remove formatting such as H1, H2, H3, Bold, and probably whatever other formatting might be in there.

**Expected behavior**
Pressing Clear Formatting should remove all formatting and leave simply default body text.

**Minimal reproduction of the problem with instructions**
1) Edit
2) Create a few headings or text styles (h1, H2, H3, and bold etc.)
3) Press "Clear formatting"
4) Observe as nothing happens

**What is the motivation / use case for changing the behavior?**
Clients constantly mess up formatting and we can't rely on them using the paste as plain text button so I've been training them to use these types of buttons before saving newly pasted text from word, email, etc. 

**Please tell us about your environment:**

* **2sxc version(s):**   9.32.1
* **Browser:** Chrome Version 69.0.3497.81 (Official Build) (64-bit)
* **DNN:** v. 09.02.00 (366) 
* **Language:** English

![clear-formatting-not-working](https://user-images.githubusercontent.com/30938703/45113681-a32c9080-b110-11e8-882a-a4466eeb72ac.JPG)

**Comment by iJungleboy** [comment]
Hi @LesiaDesign - we can look into this, I'm not sure if clear formatting is meant to do exactly that, or primarily kill any css / font-tags floating around. 

Just to understand your issue: AFAIK the users can't paste formatted text anyhow (unless the feature is actively enabled, which I assume it's not). Can you tell me how they paste formatted text - this seems to be a loophole.

**Comment by LesiaDesign** [comment]
@iJungleboy  ahhh I see. If the intended behaviour is to simply strip stray css/font tags we can't necessarily see, but somehow retain the headings/bolding added by the editor itself, then I suppose it might be working "as intended".  However, in a few other WYSIWYG editors, this same/similar button typically removes _all formatting_.  I just tested from pasting in a word document and the module seems to strip pretty much everything out anyway (great!) and pressing the "Clear Formatting" button appears to make no changes from the front-end at least. So, I suppose stripping all the formatting that's been applied through the editor itself would still be the expected behavior from my own usability standpoint.

**Comment by iJungleboy** [comment]
Thx. For now we'll close this, as it's the way it's done in TinyMCE, so we won't change anything. thx!
