### ISSUE TITLE
Modal dialog close when dragging and releasing the mouse outside dialog #2

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#1620]
**I'm submitting a ...**  
[x] bug report

**...about**   
[x] edit experience / UI

**Current behavior**
When a user selects text on an edit dialog and releases the mouse outside of the modal window, the modal window closes if it wasn't dirty (which is annoying).

We had the same issue earlier: https://github.com/2sic/2sxc/issues/678

**Expected behavior**
the modal window should not close in this case, but only when user does a full click outside of the window (intension = close modal window)

**Minimal reproduction of the problem with instructions**
1. open any modal window (edit something), i.e. with wysiwyg field which has text inside
2. do not change anything!
3. select the text inside wysiwyg, and release the cursor outside the modal popup (which happens often at working normally in fast tempo)

**What is the motivation / use case for changing the behavior?**
avoid closing of windows when there was no intention closing it.

**Please tell us about your environment:**

* **2sxc version(s):** 9.32.1  
* **Browser:** [Chrome, probably all]
* **DNN:** [all ] 
* **Language:** [any/all]

**Comment by iJungleboy** [comment]
This is a bug, and we'll fix it in the next angular 6/7 UI. So i'll close this for now, thx!
