### ISSUE TITLE
Dropdopwn from query - angular error on some fields

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1632]
**I'm submitting a ...**
[x] bug report 

**...about**
[x] admin experience UI
[x] Content Types or data management

**Current behavior**
I created a query that selects all items in a 2sxc entity.
I then use (in a separate entity) a field with a dropdown query with the query above.
I can see and select any field that the query gets.
When I try to add or edit some data in that entity, I see this error if I select some fields and the dropdown shows empty:
```
set.min.js?sxcver=9.32.1.40885:118 Error: [ngRepeat:dupes] http://errors.angularjs.org/1.5.8/ngRepeat/dupes?p0=item%20in%20%24select.items%20track%20by%20item.Value&p1=&p2=%7B%22Value%22%3A%22%22%2C%22Text%22%3A%22%22%2C%22Id%22%3A11520%7D
    at set.min.js?sxcver=9.32.1.40885:6
    at set.min.js?sxcver=9.32.1.40885:302
    at set.min.js?sxcver=9.32.1.40885:142
    at m.$digest (set.min.js?sxcver=9.32.1.40885:143)
    at m.$apply (set.min.js?sxcver=9.32.1.40885:146)
    at l (set.min.js?sxcver=9.32.1.40885:97)
    at J (set.min.js?sxcver=9.32.1.40885:102)
    at XMLHttpRequest.t.onload (set.min.js?sxcver=9.32.1.40885:103)
```
Other fields work fine.
I cannot take a guess in what the bad fields have in common.

**Expected behavior**
Dropdown field works with all fields.

* **2sxc version(s):** 9.32
* **Browser:** [Chrome]
* **DNN:** [9.2.1 ] 
* **Language:** [English]

**Comment by iJungleboy** [comment]
Note: this usually means that your list contains the same entities multiple times, or contains multiple null-entries. Could you verify this?

**Comment by eXistenZe** [comment]
Care to elaborate?

**Comment by iJungleboy** [comment]
A dropdown can usually only contain the same item once, as it's identified by the ID. This is used to mark already selected items (just as an example) and for other things. If you use F12 to see what items are returned in the API-call, you'll probably see all the items coming from the query, and my guess is your query returns some items more than once, leading to this issue. If you can verify this, I can give you tips how to resolve.

**Comment by eXistenZe** [comment]
You are correct.
One of the fields contains empty records, and the other a duplicate entry.
Thanks.
