### ISSUE TITLE
2sxc Permissions for basic editors

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#1633]
**I'm submitting a ...**  
[x] not sure

**...about**   
[x] edit experience / UI

**Current behavior**
I am trying to setup editors for just 2sxc managed content; users with a certain role but no extra dnn based permission. They should only be able to do all "blue" actions. Edit content, add new items to existing lists, arrange them, switch views etc. 
However they should not be able to add new content/ app to the pages.

Therefore I tried to setup 2sxc permissions:

- Enabled feature "Permission by Group / Role" AND "Permissions on User".     
(It looks like both are required, even if you only deal on Role level?)
- On view level:
  - (r) Permission for SecutityAccessLevel.view
  - (crudap) for RoleId
  =>did not work at all

- On app level
  - (crudap) for RoleId
  => now users can add and edit items. However, they can not do any oprations on th e order, and they even can't delete items.    
  => the UI also offers these users to add new content oor apps, however this fails. (I hide that option now with CSS)

 
**Expected behavior**
It would be nice to get any blue button to work for users with 2sxc permissions.
I don't wann give them any DNN permissions, as I wanna hide persona bar or the "black" dnn edit controls. 

**What is the motivation / use case for changing the behavior?**
I wanna set up pages for several comittees, where the head of the committee is able to manage their items without any additional help or instrustion manuals.

* **2sxc version(s):** 9.32.1
* **DNN:** 9.2.2
* **Language:** [any/all ]

**Comment by iJungleboy** [comment]
Hi Stefan

I'll see if this is something that could be added. But for now, you can actually do this with the appropriate code in the template. There are two challenges

1. get the JS to be included - for this, you should call the @Edit.Enable based on the condition you have, as described on https://github.com/2sic/2sxc/wiki/razor-edit.enable
1. get the toolbar to appear - this also requires edit.enable
1. ensure the permissions allow the changes - I think you already figured that out.

Can you give it a try and then give me feedback?

**Comment by SCullman** [comment]
One new issue on first sight: If the feature forms is disabled, edit.enable thwows an exception, regardless whther forms is true or false....

**Comment by SCullman** [comment]
At first the dialog, followed by the error message:
![image](https://user-images.githubusercontent.com/5693190/46999665-94c98f80-d126-11e8-9a3c-c20e4c983152.png)

**Comment by iJungleboy** [comment]
This may be a dialog we never tested. I presume it's the move-items? does edit itself work, but move does not?

**Comment by SCullman** [comment]
Same error message for
- Add demo
- Remove 
- Move up or down
- Sort/ Manage list
- Replace

History pops up with an empty list.

**Comment by iJungleboy** [comment]
Can you confirm that normal edit works? 
+ tell me what version you're using (because the latest RC has some changes to the security checks, and I think some cases may already be fixed)

**Comment by SCullman** [comment]
* Basic Editing  including ADAM is working
* still on latest LTS (9.32.1).

**Comment by SCullman** [comment]
As I did not want to risk a change in production, I installed a brand new dnn9.22 with 2sxc9.33.RC.
I did not install any apps but startet with a new one: I cannot add a single new content type :-(

**Comment by iJungleboy** [comment]
this is not good - thanks for testing. we'll try to fix asap. As of now, we're still in the middle of enhancing something larger (the quick-edit-dialog at the bottom), and this will need a few more days. So the next RC will probably come out in a week or so.

**Comment by iJungleboy** [comment]
Fixed the create-issue, was a minor bug where the app-id was wrong, so it actually created the content-type in a hidden / internal app instead of the one requested.
