### ISSUE TITLE
Items in Version History have wrong date/time

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#1635]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI

**Current behavior**
Version history shows wrong date/time of changes, differs about 1 month and a few hours.

**Expected behavior**
date/time matches with exact time of pressing the save button after inserting the changes.

**Minimal reproduction of the problem with instructions**
1. create any module with any content type
2. insert data, save
3. change any data, save
4. check version history: date/time is wrong, in my case exactly 1 month and a few hours.

**What is the motivation / use case for changing the behavior?**
reliable date/time for correct protocol and comprehensibility reasons

**Please tell us about your environment:**
2sic Standard

* **2sxc version(s):** 9.32.1  
* **Browser:** [Chrome, probably any ]
* **DNN:** [all | 7.4.2, probably any ] 
* **Language:** [any/all]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
thx, will look at this

**Comment by iJungleboy** [comment]
The data seems to be correct (except for maybe the UTC offset), but the display is wrong. Will look into it.

**Comment by iJungleboy** [comment]
the month issue is fixed now. The hour won't get fixed in near time, because it has to do with time zones and would need a lot of extra work.
