### ISSUE TITLE
Error using ValueFilter in an App that previously worked

### ISSUE THREAD

**Issue by andyduo** [2sic/2sxc#1636]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 
[x] not sure

**...about**   

[x] Content Types or data management

**Current behavior**

I have an app I use on a few sites to show a list of Projects filtered by a property 'Slider'. I've just installed it on a new portal but get an error when selecting the template:
`Error: System.Exception: Error getting List of Stream. Stream Name: Default DataSource Name: ValueFilter ---> System.NullReferenceException: Object reference not set to an instance of an object. at ToSic.Eav.DataSources.ValueFilter.GetEntities() in C:\Projects\eav-server\ToSic.Eav.DataSources\ValueFilter.cs:line 151 at ToSic.Eav.DataSources.ValueFilter.GetEntitiesOrFallback() in C:\Projects\eav-server\ToSic.Eav.DataSources\ValueFilter.cs:line 91 at ToSic.Eav.DataSources.DataStream.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataStream.cs:line 106 --- End of inner exception stack trace --- at ToSic.Eav.DataSources.DataStream.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataStream.cs:line 114 at ToSic.SexyContent.Razor.SexyContentWebPage.AsDynamic(IDataStream stream) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\SexyContentWebPage.cs:line 109 at ASP._Page_Portals_1011_2sxc_Projects__ProjectSlider_cshtml.Execute() in c:\inetpub\vhosts\zzzzz.co.nz\httpdocs\Portals\1011\2sxc\Projects\_ProjectSlider.cshtml:line 6 at System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) at ToSic.SexyContent.Engines.RazorEngine.Render(TextWriter writer) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 65 at ToSic.SexyContent.Engines.RazorEngine.RenderTemplate() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 92 at ToSic.SexyContent.Engines.EngineBase.Render() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\SexyContent\Engines\EngineBase.cs:line 92 at ToSic.SexyContent.SxcInstance.Render() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\SexyContent\SxcInstance_Render.cs:line 58`

The data is being filtered using a property called Slider == Yes in the Default data stream which normally works but in this case if I try to use ValueFilter on any property within the app it errors out as above. If I remove the ValueFilter the data stream returns all results as expected. It appears that the error occurs when I try to use any of the properties I've added to the App. If I leave the default values when first adding the ValueFilter no error is thrown.

**Expected behavior**

The data returned should be filtered to content items that have Slider value set to Yes only.

**Minimal reproduction of the problem with instructions**

Set up an app with a Default data source and try to filter the data returned used Visual Query Designer and ValueFilter on a property.  

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **2sxc version(s):** 9.32.1 
* **Browser:** all
* **DNN:** 09.02.00 (366)
* **Language:** English

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Could you 

1. add a screenshot of the query to give me a better idea what you're doing
1. add a screenshot of the settings of the value-filter
1. look at all the data (maybe do a quick excel-export) and check if all the items have data in that column

just fyi: the value-filter must guess what kind of comparison it will do, and for speed improvements it only checks this on the first record (otherwise each compare would first have a lot of type-checking). in rare situations a first entity going through the filter could have a different signature (like a same-named-field with a different type) which would then mess up following filters.
