### ISSUE TITLE
[Feature request] Do not replace field name with "Title" on entity's admin panel

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1639]
**I'm submitting a ...**
[x] feature request

**...about**   
[x] admin experience UI
[x] Content Types or data management

**Current behavior**
When you see the entity's content in admin panel, 2sxc replaces the Title entity name with "Title".

**Expected behavior**
This could be an optional feature, since 99% of times, I want to see the field name, and not "Title". I don't even use the Title feature for anything, I just select it cause it's mandatory.

**Comment by Accuraty** [comment]
This seems very related IMHO:
https://github.com/2sic/2sxc/issues/1638

**Comment by eXistenZe** [comment]
I don't have the knowledge to understand that ticket, but if you feel it's
included there please feel free to close this one.

**Comment by iJungleboy** [comment]
It's related but not the same, so I'll leave this open.

**Comment by iJungleboy** [comment]
Solved in 11.01 ;)
