### ISSUE TITLE
[Feature request] Content Type, any Field, Settings add option for Notes to be initially On/Open

### ISSUE THREAD

**Issue by Accuraty** [2sic/2sxc#1642]
I'm submitting a 

[x] feature request

...about
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
Field Notes have to be click on to be seen/read.

**Desired behavior**
We can set the initial state to displayed/visible (and user could still hide it).

See screenshot mockup.

![image](https://user-images.githubusercontent.com/653301/47928349-f7938880-de93-11e8-8f76-0ece22bf42ed.png)

**Comment by iJungleboy** [comment]
I like the idea.

Note that we're at 80% of building the new Angular 7 UI, and there the helper-text will always be visible for 1 full line right below the input field, and only if there is more text is a click required to reveal it all. Would this feature still be important then?

**Comment by Accuraty** [comment]
That sounds interesting, but it is again a single use case trying to match all needs. Given what you have described, now I want to modify my feature request. In the new Angular7 UI (I am assuming there will or should be) there are now 3 states to the display of the Notes; 1) hidden, 2) first line, and 3) all. You pick the default (as you said above, you've picked 2). But we need the option to have the initial state revert back to current (default which is hidden and just the "i" circle showing) or show the full content of the Notes initially.

**Comment by iJungleboy** [comment]
The new UI is a bit different, as we're following material conventions. In these, the note is below the input field, fairly tiny, which is also where we put the icon. So hiding it initially won't save any space, since the height of that line is used by the icon anyways. So I believe "hidden" wouldn't make sense. I'll try to post a screenshot soon.

**Comment by Accuraty** [comment]
Obviously I cannot see what you are describing, but a big part of UI is sometimes just being uncluttered. So anyhow, I will just wait and see what you've come up with. Thanks for discussing!

**Comment by iJungleboy** [comment]
Please review the new implementation in the new Angular UI on 2sxc 10. I believe it's good enough that your need is covered. 

In cases where it's really critical, I suggest you start the first line with a highlighted text (wysiswyg works) telling the user he must really read this.
