### ISSUE TITLE
Feature request: make Modal Edit PopUp draggable/movable

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#1646]
**I'm submitting a ...**  
[x] feature request

**...about**   
[x] edit experience / UI

**Current behavior**
if you edit any data, the modal popup for editing shows up. It is not possible to move the popup.

**Expected behavior**
It would be helpful if the popup could be moved by dragging.

**Minimal reproduction of the problem with instructions**
Edit any data. Try to move the popup window for editing.

**What is the motivation / use case for changing the behavior?**
In some cases you want to see another information or something on the website, without opening another tab with the same address. This was suggested by one of our end users and I agree that this would be helpful (also missed it earlier).
And: DNN Modal PopUp ist also movable. So this would match with standard DNN functionality and therefore be consistent.

**Please tell us about your environment:**
2sic Standard

* **2sxc version(s):** 8 + 9 
* **Browser:** [all | Chrome]
* **DNN:** [all ] 
* **Language:** [any/all]

**Comment by iJungleboy** [comment]
I understand the need but I believe this implementation would cause a lot of trouble. People accidentally moving the dialog and then not knowing how to get it back into the middle etc. 

ATM people can already shift-click the edit button to open a new window. Would that not suffice for most people needing to see the page while working in the dialog?

**Comment by reto-f-999** [comment]
did not knew that function :-) but I do not think that it would solve the problem, because when you realize you want to see something, it's already too late. 

Another possibility would be a "minimize window" function like in the OS (Win/Mac), with toggling the window to the upper part (close button, languages). 

Just a thought. But you can close this reqest it if it's not necessary enough atm, I won't mind :-)

**Comment by iJungleboy** [comment]
ok, I'll close this for now.
in future, I have other ideas, incl. inline editing or side-panel popups
