### ISSUE TITLE
Site in Edit mode very slow TTFB

### ISSUE THREAD

**Issue by Sorencys** [2sic/2sxc#1652]
I'm submitting a bug report
About edit experience / UI, admin experience UI, DNN parts

**Current behavior**
At the moment the website loads very slow when in Edit mode, when out of edit mode this does not happen. The TTFB (Time To First Byte) takes up to 40 seconds to load the first part op the website.
We have seen that every content app we add almost 3 to 4 seconds get added in the TTFB.
See the image for the time, note that this is a fully empty page except for a maximum of 3 basic apps.
![image001](https://user-images.githubusercontent.com/11991459/48907181-0358e600-ee67-11e8-9e12-8ebb8d591707.gif)

**Expected behavior**
A loading time with TTFB no higher then a second.

**Minimal reproduction of the problem with instructions**
You login on the website and enter Edit Mode.
If you then reload the website the reloading will be very slow.

**What is the motivation / use case for changing the behavior?**
It is just to long for loading, our client can not work on this.

**Please tell us about your environment:**
2sxc version(s):** 9.32.1
Browser:** [all]
DNN:** 8.0.4 
Language:** [any/all

**Anything you would like to add**
If needed a account can be made so you can see the issue yourself.

**Comment by iJungleboy** [comment]
This is not normal behavior - 2sxc editing is usually super-fast. Could something in your environment be special? because we have really not seen this otherwise.

**Comment by iJungleboy** [comment]
Just for comparison: we just launched a brand new, sophisticated site with 10+ modules on each page, and if we enter edit-mode, it takes about 1 second.

**Comment by Sorencys** [comment]
The server has no spikes as there are several other websites on the server which preform as normal.
The website has no other special features.
We are getting the idea that maybe the DNN edit mode module action bar is the cause, do you have any experience with that? We never had problems with the preformance of the module action bar.

**Comment by eXistenZe** [comment]
150-180ms TTFB.
Edit mode does increase the load time by 1-2s, but it does not affect TTFB for me.
9.2.2 and 2sxc LTS.

**Comment by iJungleboy** [comment]
@Sorencys Sorry, can't say that we have any issues there. Does adding other modules (non-2sxc) also increase load time? 
Please also note that DNN 8 is a not-so-commonly used release. Maybe updating will automatically fix everything (and resolve various security loopholes :)

**Comment by iJungleboy** [comment]
Closed because of inactivity.
