### ISSUE TITLE
"Name" should change name instead of just label of field on edit form for content type fields

### ISSUE THREAD

**Issue by CyberSiggi** [2sic/2sxc#1653]
Hi,

**I'm submitting a...**
[x] bug report => search github for a similar issue before submitting 
[x] feature request

**...about**
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
In the admin ui of Content module in the window for editing the fields of a content type when you click on a field name it opens the edit form that also allows to change the "Name" of that field but what you enter there changes only the label and not really the name. That's somehow misleading.

**Expected behavior**
I would suggest that in the form it also says "Name" and "Label" as in the overview list.

**Minimal reproduction of the problem with instructions**
Open the edit form on an existing field and change the name. You can see the change of the label instead of the name immediately on the overview list.

**What is the motivation / use case for changing the behavior?**
It unfortunately happens often that a field a name consisting of spaces or dashes was entered initially and has to be changed to be conform for template refence. It's not intuitive to use the gearwheel icon to do so when the edit form suggests you could change the name there.

* **2sxc version(s):** 9.33.0

**Comment by eXistenZe** [comment]
Just a note: you can change the name in the "settings" like button to the right. Changing a field name should not be taken lightly, but changing "Name" to "Label" may be a better option to clarify.

**Comment by iJungleboy** [comment]
I understand this issue + I'm sure you realize why editing that (also in multi-language) doesn't really change the name. I'll think of what we could do to improve it, but changing the real name usually breaks templates, so it is a "more advanced" operation which will remain more hidden than simply editing the basic UI data.

**Comment by iJungleboy** [comment]
We'll try to enhance the UI for this.
