### ISSUE TITLE
Edit Toolbar - Delete action returns 405 "Method Not Allowed" Error as Host Admin

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#1654]
I'm submitting a bug report about the Edit/WebAPI experience using the Toolbar in a razor template.

**Current behavior**
I have the following code in a template that is designed to allow a user to delete an item:
```
@Edit.Toolbar(toolbar: new object[] { 
	new { 
		command = new { 
			action = "delete", 
			entityId = photo.EntityId, 
			entityGuid = photo.EntityGuid, 
			entityTitle = photo.EntityTitle
		} 
	}
})
```
When the "Delete" action is run with the resulting URL from 2SXC using the DELETE method as a Host Admin:
```
http://somedomain.com/API/2sxc/app-content/any/f6a93bb0-32be-491c-b2bb-272fceb95455?zoneId=2&appId=13
```
IIS returns the following error:
```
HTTP/1.1 405 Method Not Allowed
Cache-Control: private
Allow: GET, HEAD, OPTIONS, TRACE
Content-Type: text/html
Set-Cookie: dnn_IsMobile=False; path=/; HttpOnly
X-Powered-By: ASP.NET
X-Powered-By-Plesk: PleskWin
Date: Tue, 27 Nov 2018 15:55:35 GMT
Content-Length: 1110
```

**Expected behavior**
The WebAPI should accept the DELETE method and delete the item.

**Minimal reproduction of the problem with instructions**
Create a new Content Type and add an item. Create a razor template that grabs the item and add the custom EDIT.TOOLBAR to the page with the delete action.

**What is the motivation / use case for changing the behavior?**
We allow users to add/edit/delete photos (a separate Content Type) that are posted for an article. The add and edit actions work fine, but the delete method returns the error.

**Please tell us about your environment:**
IIS 8.5 / Plesk shared hosting

**2sxc version(s):**
9.33

**Browser:**
all

**DNN:**
9.2.2

**Language:**
English

**Comment by iJungleboy** [comment]
A question: in your root web.config the allowed HTTP verbs are listed (GET, PUT, POST, etc.) is DELETE allowed?

**Comment by tpperlman** [comment]
Hi Daniel, thanks for the reply. This is a pretty vanilla DNN install, and comparing it to another DNN install of the same version there aren't any noticeable differences in the verbs.

Are you referring to the ExtensionlessUrl handler? If so, here is what it contains:

```
  <system.webServer>
    ...
    <handlers>
      <remove name="ExtensionlessUrl-Integrated-4.0" />
      <add name="ExtensionlessUrl-Integrated-4.0" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
      ...
    </handlers>
    ...
  </system.webServer>
```

**Comment by iJungleboy** [comment]
that's about right. and looks good to me. let's try something different - do you see any dnn site logs? in the admin-menu...

**Comment by tpperlman** [comment]
Unfortunately there are no event log entries, and nothing in the log4net logs. Since it is a shared hosting server, I can't check the server log either.

**Comment by tpperlman** [comment]
As an additional test, I did deploy a copy of the site to my development machine and the delete action works as expected. I am just having a problem in the production environment.

**Comment by iJungleboy** [comment]
so that sounds like it's something in the prod environment. Maybe they have a firewall or something that blocks this?

**Comment by iJungleboy** [comment]
Will close because of inactivity. Probably a installation specific issue.

**Comment by tpperlman** [comment]
In follow-up, I ran into this same issue on a new hosting company (interserver) and was able to resolve it using this SO posting:

[https://stackoverflow.com/questions/4413455/why-does-http-delete-verb-return-405-error-method-not-allowed-for-my-restful-w](url)

**Comment by iJungleboy** [comment]
@tpperlman awesome, thx!

**Comment by tpperlman** [comment]
I keep coming back to this thread, and at the risk of the SO solution going away I would like to document it here:

> In case anyone having the same issue.
> 
> Here is another way you can try.
> 
> in web.config

```
<system.webServer>
    <modules>
      <remove name="WebDAVModule" />
    </modules>
    <handlers>
      <remove name="WebDAV" /> 
    </handlers>
</system.webServer>
```

**Comment by 10PoundGorilla-ChrisBehling** [comment]
The solution noted above by @tpperlman did the trick in one of our instances where we were experiencing this issue today.

DNN: 9.0.8
2sxc: 11.11.2

**Comment by cpalmergig** [comment]
> I keep coming back to this thread, and at the risk of the SO solution going away I would like to document it here:
> 
> > In case anyone having the same issue.
> > Here is another way you can try.
> > in web.config
> 
> ```
> <system.webServer>
>     <modules>
>       <remove name="WebDAVModule" />
>     </modules>
>     <handlers>
>       <remove name="WebDAV" /> 
>     </handlers>
> </system.webServer>
> ```

Adding the above configuration to our web.config worked for me also, on our DNN 9..2.0, 2SXC 12.2.1 installation.
