### ISSUE TITLE
[Feature Request] Content Type, any Field, Settings option to show/hide field in Edit UI based on another field

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#1655]
I'm submitting a

[x] feature request

...about
[x] edit experience / UI
[x] admin experience UI

Current behavior
When editing a Content Type, all fields show up.

Desired behavior
When a record (Content Type) is used for multiple purposes in a project, the content editor is often confused when seeing fields they do not need. For example, we have a Content Type of People. This has a field named Type (use; what type of People). There are many but to keep my example simple, lets just say that the type can be Board or Staff in an organization. Staff can be assigned a Department. Board can have Credentials and a Proper Name (e.g. John J. Smith instead of staff just getting John Smith). The Content Type has 17 other fields so far. All 17 are used for both Staff and Board types, so we don't want to create two different Content Types (especially since at least 3 People are both on the Board and Staff (meaning we also need to account for a Both type)),
 
We need a way to have fields show or hide after the edit user selects the Type field. If it defaults to Staff, then when they change it to Board, the Department field should hide and the Proper Name and Credentials fields should appear (since they were hidden initially because Type defaulted to Staff),
 
Also note: the implementation in Action Form is is great, please check it out. They have a show/hide option that is evaluated true/false and you can put all kinds of useful expressions in there for the initial state as well as the interactive state (Binding).
 
Maybe the real answer is to give us a way to attach some JavaScript (Angular?) to the field so we can show/hide based on another field (or possibly many other things)?

2sxc 9.33 is current as I write this.
 
Note that this was mentioned as the 2nd bullet item in the examples on this RFC, but I felt it was specific enough to pull it out as a stand-alone Feature Request. Cheers!

**Comment by iJungleboy** [comment]
This is the same as #2181 so I'll close this.
