### ISSUE TITLE
Adam seems to inset duplicate entry in folders table

### ISSUE THREAD

**Issue by sleupold** [2sic/2sxc#1656]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] Content Types or data management
[x] DNN parts

**Current behavior**

in log4Net, an error is logged about failed SQL Statement
[D:2][T:18][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [4] Error executing SQL: ;Exec dbo.AddFolder @0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13
Cannot insert duplicate key row in object 'dbo.Folders' with unique index 'IX_Folders_FolderPath'. The duplicate key value is (0, adam/Content/7axDIy-p5kqlv8zTxZaowg/).
The statement has been terminated.

**Expected behavior**

no bug is logged.

**Minimal reproduction of the problem with instructions**

just from the log, steps I don't know

**What is the motivation / use case for changing the behavior?**

there should be no error logged / not being tried to insert duplicate entry

**Please tell us about your environment:**

DNN 9.2.2 on WinS 2016, Client Win10

* **2sxc version(s):** 9.33.0  
* **Browser:** [Edge | IE 11 ]
* **DNN:** [9.2.2 ] 
* **Language:** [ German ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
There's probably something wrong when ADAM checks if the folder already exists. Would be great if someone would look into this & contribute.

**Comment by iJungleboy** [comment]
closed because of inactivity - probably already fixed.
