### ISSUE TITLE
file manager ignores file access rights and root path

### ISSUE THREAD

**Issue by CyberSiggi** [2sic/2sxc#1657]
**I'm submitting a ...**  
[x] bug report

**...about**   
[x] admin experience UI
[x] Content Types or data management

**Current behavior**
Content type field of type Hyperlink is set to show file manager but opening the file manager always shows all files from the portal root. We have set restricted rights which show up correctly in any other file picker and also set the root path to a subdirectory under "Paths" in "Advanced Settings" in the content type admin window. Both seem to have no effect whatever we tried.

**Minimal reproduction of the problem with instructions**
Just create a content type of type hyperlink that doesn't use adam but the file picker under the "..." button, and set a subdirectory under "Paths" in "Advanced Settings". When opening the content edit window for an instance of that content type click on the "..." and open the file manager and you see all files of the portal root instead of just those of the provided subdirectory.

**What is the motivation / use case for changing the behavior?**
We cannot use adam at this point because of the need for restricted access to predefined folders to select a document from.

* **2sxc version(s):** 9.33.0
* **Browser:** all
* **DNN:** 9.2.2

Thank you very much for your help!

**Comment by CyberSiggi** [comment]
Please help. We would urgently need the file manager to work as expected. Maybe I did something wrong or there's a workaround possible? Thank you very much! And happy new year!

**Comment by iJungleboy** [comment]
We'll look into this soon, but I can't give you a specific date. I would suggest you try a few combinations with trailing or leading slash or something, just to try the combinations.

**Comment by iJungleboy** [comment]
Comments for the developer resolving this

## Issue 1 - correct starting path

* [ ] note that this only applies to "normal" file fields, and is not relevant for libraries
* [ ] Pls verify that it is an issue, or alternately if it just requires a special syntax, which isn't clearly documented
* [ ] once fixed, also coordinate w/2dm so the comments in the entity-schema (for the editor of the field) are updated to reflect changes in both EN and DE
