### ISSUE TITLE
When getting data from query with 2sxc webApi "Guid" field is not included

### ISSUE THREAD

**Issue by josip8** [2sic/2sxc#1660]
**I'm submitting a ...**  
[x] bug report

**...about**   
[x] Content Types or data management
[x] APIs like REST

**Current behavior**

* When I create visual query and run it I get the following results which contain `"Guid"` field:

![Visual Query Results](https://i.imgur.com/ok9nDpW.png)

* But when I get data from that same query with `sxc.WebApi.get(url).success()` there is no `"Guid"` field:

![2sxc webApi Results](https://i.imgur.com/SNRlOe5.png)

**Expected behavior**

Getting `"Guid"` field with 2sxc webApi.

**Minimal reproduction of the problem with instructions**

* Create simple visual query with ContentTypeFilter
* Run query, then get data from query with 2sxc webApi
* Compare the results

**What is the motivation / use case for changing the behavior?**

For fetching files with 2sxc webApi, `"Guid"` field is needed.

**Please tell us about your environment:**

* **2sxc version:** 9.33.0  
* **Browser:** Chrome 71.0.3578.98
* **DNN:** 09.02.01

**Comment by iJungleboy** [comment]
I'll review this. I believe the default to not include the guid is an additional security, but I understand if you want to include it. It won't be here quickly though, as it may require a new feature to configure a query to provide this. 

If you need a quick workaround, you can always create an own API which gets the data from the query using something like below, and reconfigure the serializer to include it. Here's how the AppQueryController.cs does it:

```
var query = App.Data.Query["your-queryname"];
var serializer = new Serializer(Sxc) { IncludeGuid = includeGuid };
return serializer.Prepare(query);
```

**Comment by josip8** [comment]
Thank you for quick response 😄 . 
Your workaround works perfectly, just small modification on first line:
 `var query = App.Query["your-queryname"];`
