### ISSUE TITLE
Error in query editor (DnnSqlDataSource): Error getting List of Stream

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1661]
**I'm submitting a ...**
[x] bug report
[x] not sure

**...about** 
[x] Content Types or data management
[x] other / unknown

**Current behavior**
Trying to run this query in visual query designer:
```
SELECT *
FROM dbo.EventLog
LEFT JOIN dbo.Exceptions ON dbo.EventLog.ExceptionHash = dbo.Exceptions.ExceptionHash;
```
This gives me "Error getting List of Stream. Stream Name: Default DataSource Name: DnnSqlDataSource"

The query runs in DNN sql console.

If I specify the fields like "SELECT LogTypeKey, LogConfigID, LogUserName, LogPortalName, LogCreateDate, LogProperties", the query will run fine.

* **2sxc version(s):** 9.32.1
* **DNN:** [ 9.2.2 ]

**Comment by iJungleboy** [comment]
Please give us more debug info. For example, what does the DNN admin log reports for this request?

**Comment by iJungleboy** [comment]
Ok, thanks for this. We'll consider skipping duplicate fields - I wasn't aware this is even possible.

**Comment by iJungleboy** [comment]
For now I'll actually just ensure that duplicate column names are skipped. This will result in the developer realizing that he'll have to modify his SQL to get the other columns that are still missing.
