### ISSUE TITLE
Entity export does not keep the field order

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1662]
**I'm submitting a ...**
[x] feature request

**...about** 
[x] Content Types or data management

**Current behavior**
When exporting an entity to xml, it seems to use the creation field order.

**Expected behavior**
The current arranged order should take precedent.

* **2sxc version(s):** 9.32

**Comment by iJungleboy** [comment]
Which export do you mean? the table export in the tab _Data_ or the special export in the _App_?

**Comment by eXistenZe** [comment]
The export buttons in the entity/data list. The ones that export a single
table in xml.

**Comment by iJungleboy** [comment]
I understand the wish but it won't be on our priorities, so I'll mark as needing contributions and close for now. 

Estimated work: add UI option to enable/disable this, implement in export ca. 4h.
