### ISSUE TITLE
All numeric fields used as decimals in template

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1663]
**I'm submitting a ...** 
[x] not sure

**...about** 
[x] Content Types or data management

**Current behavior**
Whenever I use a numeric field type, despite having 0 decimals configured, 2sxc treats them as decimals when I use them in a razor template. This require quite a few casts in my case, when I don't even use decimals.

**Expected behavior**
Perhaps create a new field type just for "int" field type.

**What is the motivation / use case for changing the behavior?**
In my day-to-day apps, I don't use decimals, just ints, so it's extra work and space to cast them all.

* **2sxc version(s):** 9.32

**Comment by iJungleboy** [comment]
I understand the need. As of now, implementing this would be a lot of work, so we won't address this any time soon.
