### ISSUE TITLE
Problem with EVOQ Basic

### ISSUE THREAD

**Issue by ufoloko** [2sic/2sxc#1664]
**I'm submitting a ...**  
[x] bug report => Im not able to add new items for current apps

**...about** 
[x] edit experience / UI
[x] admin experience UI

**Current behavior**

I have a professional DNN installation and I installed initially version 9.14 of 2sxc. After some time I upgraded to version 9.32 and now im not able to add new items.

When you create a new module with app for first time, you can add items without any problem. If you have a created module before 2sxc update, you can add items without any problem. But if you add items, and you click on publish button, then you are not able to add more items to that module. You receive a Javascript alert message

Had an error taking to the server (status 400)
Message: Bad Request
Detail: Sequence contains no elements

Same if you try to delete an item. I thing is some issue related with publish flow

**Expected behavior**

After add an item, this new item should appear in module or app

**Minimal reproduction of the problem with instructions**

Add a new app into a page, and then add 1 or more items.

Click on publish button to show current app.

Try to add more items to that app, you will have an error.

**Please tell us about your environment:**

Windows server 2008 with SQL Server 2012
Evoq Basic 9.02.00
2sxc initial version: 9.14, update 9.32 and then 9.33 (same problem)
Browser all
Language Spanish

I can give you access to the portal to check if you need. but i will need your public ip to grant access.

**Comment by iJungleboy** [comment]
This would take some time to resolve and we would need to look at your installation in detail and work out a solution. It won't be on our priorities, so if you want this, you'll need to get normal support.

**Comment by ufoloko** [comment]
Hi, i just sent you an email to try to get normal support. Let me know if we can have some kind of diagnistics first. Thanks

**Comment by iJungleboy** [comment]
To look at the issue more in depth, I think we should look at it. This will probably take 2-4 hours of diagnostics from our side.

**Comment by ufoloko** [comment]
Thanks IJungleboy, if you need some other information please let me know

**Comment by cgarrett** [comment]
We seem to be having a similar issue, I believe. Existing apps will no longer allow you to add content. Not seeing the Bad Request error, it just does nothing.

When you click Add Item, this appears in the console:
```
before
after
Cms.Api(nc) - log was reset
Cms.Api(nc)Cmd.Exec(md) - detecting params and running - has 4 params
Cms.Api(nc)Cmd.Exec(md) - might cycle parameters, in case not all were given. third is event=false
Cms.Api(nc)Cmd.Exec(md) - adapting settings; name is string: true; name = add
Cms.Api(nc)Cmd.Exec(md) - adapting settings; name is string: false; name = [object Object]
Cms.Api(nc)Cmd.Exec(md) - will add defaults for add from buttonConfig
Cms.Api(nc)Cmd.Exec(md) - run command add for type undefined
Cms.Api(nc)Cmd.Exec(md) - button.dialog method missing, must be old implementation which used the action-name - generating method
Cms.Api(nc)Cmd.Exec(md) - command might change data, will wrap in pre-flight to ensure content-block
```

**Evoq Basic: 9.1.1
2sxc 9.32.1 LTS**

**Comment by iJungleboy** [comment]
@cgarrett thanks for the info. ATM we don't have resources to prioritize this as free work. If it's important to you, please request support.

**Comment by ufoloko** [comment]
@cgarrett i updated 2sxc to 9.33.0 version and the problem is solved now.

**Comment by iJungleboy** [comment]
Now that's a pleasure to hear ;)
