### ISSUE TITLE
Id always return null in App.Data["xxx"]

### ISSUE THREAD

**Issue by adaosantos** [2sic/2sxc#1665]
**I'm submitting a ...**
[x] not sure

**about...**
[x] Razor templating
[x] APIs like REST

**Current behavior**

When i try access AsDynamic(App.Data["BlogPost"]).FirstOrDefault().Id is return null
**Expected behavior**
When i try access AsDynamic(App.Data["BlogPost"]).FirstOrDefault().Id is return Id-as-int

**Minimal reproduction of the problem with instructions**
WebApi Controller or Razor template.

* **2sxc version(s):** 9.32.1  
* **Browser:** [all]
* **DNN:** [9.1.1 ] 
* **Language:** [Portuguese ]
![001](https://user-images.githubusercontent.com/4481171/50855149-35b69800-136e-11e9-9645-59ef346a4a4b.JPG)
![002](https://user-images.githubusercontent.com/4481171/50855151-35b69800-136e-11e9-82fc-73140f35a516.JPG)

**Comment by iJungleboy** [comment]
I think you're trying to access EntityId :)

**Comment by adaosantos** [comment]
Some error
![003](https://user-images.githubusercontent.com/4481171/50856477-f8540980-1371-11e9-808a-e6920991da7c.JPG)

**Comment by iJungleboy** [comment]
Is line 22 the one in the screenshot? or is it something else? because entities have EntityId, but I want to be sure I'm looking at the right line. Ideally also post the error as you see it in the admin-events.

**Comment by adaosantos** [comment]
![image](https://user-images.githubusercontent.com/4481171/50917694-57268b00-1425-11e9-82bb-f17e174ca928.png)

**Comment by Accuraty** [comment]
Is it possible in line 22 you are just missing the "p." ?

`select new { EntityId = p.EntityId, Title ...`

**Comment by iJungleboy** [comment]
@Accuraty that looks about right :) 👍
