### ISSUE TITLE
Slashes not getting replaced in UrlKey Field

### ISSUE THREAD

**Issue by lucatescari** [2sic/2sxc#1666]
**I'm submitting a ...**  
[x] bug report 

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**

When an UrlKey field is created, and you type slashes (/) in the field from which the UrlKey should be generated from, some slashes will be replaced with hyphens, and some won't. It looks like the first one always works, and the following ones won't work anymore.

![image](https://user-images.githubusercontent.com/7703479/51103467-13e06980-17e3-11e9-8923-087007492d23.png)

**Expected behavior**

All slashes should be replaced with hyphens.

**Minimal reproduction of the problem with instructions**

- Create an app with a content type
- Create a title field and an UrlKey field
- Type a string with slashes in the title field, and see the result in the UrlKey field

**Please tell us about your environment:**

* **2sxc version(s):** 9.32.1 LTS  
* **Browser:** [ Chrome ]
* **DNN:** [ 7.4.2 ] 
* **Language:** [any/all]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
ok, will try to fix in angular 7 UI

**Comment by iJungleboy** [comment]
should be fixed in v10
