### ISSUE TITLE
quickE move per select and paste moves to one element too much below

### ISSUE THREAD

**Issue by CyberSiggi** [2sic/2sxc#1672]
**I'm submitting a ...**  
[x] bug report

**...about**   
[x] edit experience / UI

**Current behavior**
When selecting a content element with the QuickE select arrow and clicking on the insert icon at another content element the selected element appears not at this position and not even below this element but one more element further down.

**Expected behavior**
I would expect the selected element to be inserted at the position where I click on the insert icon or at least below that element.

**Minimal reproduction of the problem with instructions**
See current behavior description.

**What is the motivation / use case for changing the behavior?**
Correct/expected behavior.

* **2sxc version(s):** 9.33.0  
* **Browser:** all
* **DNN:** 9.2.2

Thank you very much for your help!

**Comment by iJungleboy** [comment]
Some comments for resolving

* [ ] ensure that we can first reproduce the issue. My guess is that the modules have a slightly different numbering scheme from DNN 7 to 9, and that this is the primary issue.
