### ISSUE TITLE
HTML Editor - Empty UL list items removed

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#1677]
**I'm submitting a ...**
[x] bug report

**...about**   
[x] edit experience / UI

**Current behavior**
When you have a content type of text/string using the "wysiwyg editor (recommended)" input type, "empty" list items are removed. The editor perceives list items without text as empty, even though there may be links and other markup in them. Adding the HTML code in source view also results in their removal.

**Expected behavior**
The editor should not delete list items that it perceives as empty.

**Minimal reproduction of the problem with instructions**
Create a new content type, add a text/string field and choose the "wysiwyg editor (recommended)" input type. Create a new item, switch to advanced mode, click the source code button, and add html text like this that includes fontawesome icons typically used in navigation:

```
<ul class="footerSocial">
	<li>
		Social Links
		<ul>
			<li><a href="#"><i class="fa fa-facebook"></i></a></li>
			<li><a href="#"><i class="fa fa-instagram"></i></a></li>
			<li><a href="#"><i class="fa fa-heart"></i></a></li>
			<li><a href="#"><i class="fa fa-youtube"></i></a></a></li>
		</ul>
	<li>
</ul>
```
Notice that after you click OK, all the code is removed.

**What is the motivation / use case for changing the behavior?**
List items are commonly used in HTML markup for structured content and navigation items, and this error precludes us from creating content in 2sxc for this purpose.

* **2sxc version(s):** 9.33
* **Browser:** all
* **DNN:** 09.02.02 
* **Language:** English

**Comment by iJungleboy** [comment]
This seems to be TinyMCE behavior. Could you @tpperlman do some research to tell us what switch we should change on TinyMCE to make this happen?

**Comment by tpperlman** [comment]
Thanks, I hadn't looked into which HTML editor was used. Anyway, after looking at some stackoverflow articles it appears that TinyMCE has an optional parameter called verify_html that can be set to false. I am not sure if this is the cause, but the article at:

[https://stackoverflow.com/questions/10467480/how-to-prevent-tinymce-from-stripping-empty-tags-from-input](https://stackoverflow.com/questions/10467480/how-to-prevent-tinymce-from-stripping-empty-tags-from-input)

...helped shed some light. I'll have to leave it up to you to decide if you want to disable HTML verification considering non-coders are using the editor too.

A work-around I found in another article mentioned adding an empty space in the element to keep it from being removed. I was able to confirm this works:

```
<ul class="footerSocial">
<li>Be Social
<ul>
<li><a class="fa fa-facebook" href="#">&nbsp;</a></li>
<li><a class="fa fa-instagram" href="#">&nbsp;</a></li>
<li><a class="fa fa-heart" href="#">&nbsp;</a></li>
<li><a class="fa fa-youtube" href="#">&nbsp;</a></li>
</ul>
</li>
</ul>
```

...but I don't like how it throws off the layout of the FontAwesome icon so I ended up creating a new alternate ContentType using the DNN editor, which doesn't strip the HTML tags.

**Comment by iJungleboy** [comment]
I think turning of verify_html is dangerous - I assume it's also responsible for script-filtering and closing tags. So not a good solution. There should be a simpler "empty-html" or empty_tag switch or something.

**Comment by iJungleboy** [comment]
Note: I believe we added the <i> tag to be allowed to be empty. Could you check if this would work?
```
<ul class="footerSocial">
<li>Be Social
<ul>
<li><a href="#"><i class="fa fa-facebook" ></a></li>
...
</ul>
</li>
</ul>
```

**Comment by tpperlman** [comment]
I agree with your comment above about being potentially dangerous (law of unintended consequences).

I tried your code above and the empty list item is still being removed.

**Comment by iJungleboy** [comment]
I can see that the code gives tinymce a special "also regard the i tag as valid" so it should work, sorry if it doesn't :(. This would take some more research. If you can find a solution, we'll add it.

**Comment by iJungleboy** [comment]
Closed due to inactivity.
