### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by adaosantos** [2sic/2sxc#1679]
**I'm submitting a ...**  
[x] feature request
[x] not sure

**...about**   
[x] Content Types or data management
[x] other / unknown

**Current behavior**
Dont have provider for Sitemap

**Expected behavior**
I user 2sxc Blog app, but i need a Sitemap provider. Have any workaround about this ?

* **2sxc version(s):** 9.3.33  
* **Browser:** [all]
* **DNN:** [9.2.2 ] 
* **Language:** [any]

**Comment by iJungleboy** [comment]
So this issue would be about the blog app - not about 2sxc in general. So after my brief answer I'll close this. 

Basically I don't have a quick workaround - I guess you would have to program one yourself. But I don't actually think you would ever need one - the Sitemap is not very useful AFAIK, so I don't think it's worth investing anything into.
