### ISSUE TITLE
Advanced / debug mode shorcut - intrusive

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1680]
**I'm submitting a ...**
[x] feature request

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management

**Current behavior**
The current advanced / debug mode shortcut is ctrl + left mouse click.
When editing data anywhere in the app, we use ctrl - c/v/x a lot with mouse pointing the place. This causes a lot of undesired advanced / debug mode activations.

**Expected behavior**
Use a less intrusive shortcode (more complex). Something like ctrl + shift + something.

**Comment by iJungleboy** [comment]
we'll probably change it to ctrl+alt+shift + click in 2sxc 10.

**Comment by iJungleboy** [comment]
will close this, as it's already in development on another repo.
