### ISSUE TITLE
Multi-Language App - Custom controller returns default language

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1681]
**I'm submitting a ...**
[x] bug report
[x] not sure

**...about**
[x] Razor templating
[x] Content Types or data management
[x] APIs like REST

**Current behavior**
When using a custom api controller: api/demoController.cs (Razor) and posting some data: 

`$2sxc(@Dnn.Module.ModuleID).webApi.post("demo/returnSomeRecomendations",` {}, newItem, true).then(handleStuff);

It does not use the current language (witch is applied fine in the template) and uses the default one. Every data it gets from the entities, like
`AsDynamic(App.Data["demoLinks"])`
returns in the default language.

**Expected behavior**
The controller should use the same language as in the template sending the post data.

* **2sxc version(s):** 9.35
* **DNN:** [all | 7.4.2 | 8.X.X | 9.2.2 ] 
* **Language:** [ Portuguese | English ]

**Comment by iJungleboy** [comment]
This is a bug/feature in dnn. Basically DNN gives the language, and in many cases it does so correctly and automatically. If it does not, you can always set the correct language by setting the thread-culture early in your code (before you do anything `AsDynamic(...)` and everything will work.

**Comment by eXistenZe** [comment]
The best I came up with was
`Thread.CurrentThread.CurrentCulture = new CultureInfo(Dnn.Portal.CultureCode);`
It works, but is this the best way?

**Comment by iJungleboy** [comment]
yes. DNN should do most of it automatically, if your API call goes through the url which has the specific portal, but it may not always work as expected, so this is your safe bet. 
Important that you do this _before_ you do `AsDynamic(....)` as that will already access the current culture.
