### ISSUE TITLE
Improvements to TinyMCE on Tables

### ISSUE THREAD

**Issue by BeniGemperle** [2sic/2sxc#1691]
**I'm submitting a ...**
[x] feature request

**...about**   
[x] edit experience / UI

**Current behavior**
* Copy/Paste with content having table looses any formatting, also the entire table-structure
* Inserting a new table: table has no width, so it's almost not visible
* Context Menu _Table_ has white background and white text-color, so it's not usable (there's a css rule having `!important` causing that issue)

**Expected behavior**
* Copy/Paste a table should preserve the table (as default in TinyMCE v4)
* a new table should have a default-width of 100% (as default in TinyMCE v4)
* Table-Menu should be readable (as default in TinyMCE v4)
* Option to customize default Toolbar, either globally or per field/content type. Sometimes I need to have the tables-menu by default for a field.

**What is the motivation / use case for changing the behavior?**
I have a customer who needs to use tables regularly (e.g. for race-results in a news-entries).

**Please tell us about your environment:**

* **2sxc version(s):** 9.33.0
* **Browser:** all
* **DNN:** all 
* **Language:** any/all

**Anything you would like to add**

![image](https://user-images.githubusercontent.com/6669093/53636180-93a18680-3c1f-11e9-9d72-46550b7e16ed.png)

**Comment by iJungleboy** [comment]
fixed in v10

But we'll have to re-check once we update to TinyMCE 5.x
