### ISSUE TITLE
Improvements on Image-Handling (single image and file-library)

### ISSUE THREAD

**Issue by BeniGemperle** [2sic/2sxc#1692]
**I'm submitting a ...**  
[x] feature request

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
* Only an anchor can be specified for an image but no cut/crop-area
* a file-library-field can only be sorted in low-level ways (filename, file-date or metadata), but no drag and drop sorting

**Expected behavior**
* Provide support for selecting a cut/crop-area (maybe with support for https://imageresizing.net/docs/v4/plugins/croparound?). For a single image and for a file-library.
* Provide support for individual file-sorting on a file-library (maybe save the desired file-order/ids to a hidden/metadata-field)

**What is the motivation / use case for changing the behavior?**
* Provide more comfort for image gallery and news

**Comment by iJungleboy** [comment]
These wishes make sense, but are very hard to implement in a generic way. So as for now, we won't address it. So to keep the issues-list clean, I'll tag it as "needs contribution" but it's very complex to do in a long-term stable way, so talk to us before you try to do this. 
If you want to do this, also please wait for the angular 7 UI.
