### ISSUE TITLE
Change WebApi to only deliver json (not xml) as that always fails, and makes quick debugging much harder

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#1693]
**I'm submitting a ...**  
[x] change request

**...about**   
[x] APIs like REST

**Current behavior**
WebApi behaves as the default asp.net webApi, delivering xml by default. This almost never works, as some data types cannot be serialized, so when accessing an api-endpoint with the browser, you almost always get an error - it only works from JavaScript.

**Expected behavior**
Basically only json works anyhow, so let's just remove xml from the serializers and only provide JSON. This way, even a normal browser-call to the url will return a valid json, and everybody is happy. 

**Please tell us about your environment:**

* **2sxc version(s):** 9.35

## Note about Breaking Change##

This is a change in the core functionality. Our evaluations make us believe, that nobody will be impacted, as the XML output never worked anyhow. Yet there is a small chance that a developer may have made a custom WebApi endpoint which explicitly wanted xml. If this is the case we recommend to move on to json, but if you really want to keep that, you can always create a C# attribute and decorate your class to re-enable the xml-formatter. You'll find various guides to configuring formatters in the internet.

**Comment by Rodien** [comment]
Hi iJungleboy,

I am trying to activate XML without success. 

We have a client who wants the XML data for RSS. 

Is there any blog post you can point me to on how to activate xml  back again?

**Comment by iJungleboy** [comment]
@Rodien 

From what I can see you have these options:

1. Add a custom attribute which re-attaches the XML serialization which is removed by default here: https://github.com/2sic/eav-server/commit/e5dc0bb0f7d70978146a7303819ad090dcb6c1f5
2. Optimize that JsonResponseAttribute in the link before to behave differently when the header asks for it - and then push your changes to 2sxc
2. Use a different WebAPI base class which doesn't have this attribute by default
3. Create a razor page to deliver the XML, similar to how the RSS feed is created in the blog app

**Comment by Rodien** [comment]
Thanks for your response @iJungleboy 

Here is the code we used to accomplish this. (In case anyone else needs this information)

`  [HttpGet]				
	public object artikelenxmlv1()
	{
        StringBuilder sb = new StringBuilder();
        
	    
	    sb.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
	    sb.Append("<rss version=\"2.0\" xmlns:atom=\"http://www.w3.org/2005/Atom\">\n");
	    sb.Append("<channel>\n"); 
	    
	    sb.Append("<title>De Schiedammeronline</title>\n");
        sb.Append("<link>{domain}</link>\n");
        sb.Append("<description>RSS feed</description>\n");
	    
	    
	    var query = App.Data["News"];
        var arts = AsList(query).OrderByDescending(x => x.Date).Take(50);
        foreach (var art in arts){
            var imageUrl = Text.Has(art.Image) ? art.Image : App.Resources.PlaceholderMissingImage;
           
            sb.Append("<item>\n");
            sb.Append("<title><![CDATA[" + art.Title + "]]></title>\n");
            sb.Append("<link><![CDATA[{domain}/artikel/details/" + art.UrlKey + "]]></link>\n");
            sb.Append("<description><![CDATA[" + SecurityElement.Escape(art.Teaser) + "]]></description>\n");
          
            sb.Append("<pubDate>" + AsString(art.Date) + "</pubDate>\n");
			sb.Append("<enclosure url=\"{domain}" + Tags.SafeUrl(imageUrl) + "\" length=\"12216320\" type=\"image/jpeg\"/>\n");
			sb.Append("<guid>" + "{domain}" + art.UrlKey + "</guid>");
            sb.Append("</item>\n");
        }
        sb.Append("<atom:link href=\"{domain}/api/2sxc/app/News4/api/RSSfeed/{apiname}\" rel=\"self\" type=\"application/rss+xml\" />");
	    sb.Append("</channel>\n");
	    sb.Append("</rss>\n");

	   //return sb.ToString();
	   
	   var res = Request.CreateResponse(HttpStatusCode.OK);
	    
	   res.Content = new StringContent(sb.ToString(), System.Text.Encoding.UTF8, "text/xml");
	   return res;
	}
	
	 private static string AsString(DateTimeOffset dateTime)
        {
          
          
            var thisString = dateTime.ToString("ddd, dd MMM yyyy HH:mm:ss zzz", CultureInfo.InvariantCulture);

            StringBuilder builder = new StringBuilder(thisString);
            builder.Remove(builder.Length - 3, 1);
            return builder.ToString();
        }`

**Comment by iJungleboy** [comment]
@Rodien Thanks a bunch!

To all others: In summary the solution to return a string is the simplest and easy to do. If you prefer to use an XmlDocument object that would work as well and ensure that the XML is always valid.
