### ISSUE TITLE
Bug: Connections lines in Visual query seem to jump around

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#1694]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] admin experience UI
[x] Visual query

**Current behavior**
Recently the lines connecting the data sources seem to (visually) reconnect the wrong dots if the mouse moves over these lines. Internally the data doesn't change - but the display seems broken. I believe it has to do with a chrome update about 2 months ago. 

**Resolution probabaly**
Probably update to the latest jsPlumb library and fix problems - going from 2.1.7 to 2.9.0

**Please tell us about your environment:**

* **2sxc version(s):** 9.35
* **Browser:** Chrome (latest), others not tested

**Comment by raphael-m** [comment]
Issue does not occur on Firefox (65.0.1)

**Comment by iJungleboy** [comment]
So it seems to be a latest-chrome-issue, which may be fixed by Google. Let's backlog this for now.

Note: we also tried updating to the latest js-plumb (2.9.0) but the problem still occurred.

**Comment by iJungleboy** [comment]
close for now, no priority.
