### ISSUE TITLE
On multilanguage editing enable one save action for all the languages.

### ISSUE THREAD

**Issue by mconta** [2sic/2sxc#170]
When translating an item on N languages it should be useful to maintain the state of the translated version without the need of saving each language every time and save all the versions only with a single Save click.

Today when translating we need to : 

1) find an item from the list (on long lists this takes time)
2) click Edit 
3) choose the language
4) unlock the value we need to translate
5) edit the value
6) click on save 
the page redirects again to the items list

6 steps x language, with 4 additional languages 24 steps.

Here is an alternative management:

1) Find an item from the list  
2) click Edit on the item 

3) choose the language
4) unlock the value we need to translate
5) edit the value
.... iteration
6) choose another language....

--- final steps
N)  click on save (saves all the languages)

With this alternative management we have 3 actions x 4 languages = 12 action + the initial "find & click on edit (2 steps)" + the last click on save = 15 actions VS 24 actions.

On large list the continuous returning to the main list is really disturbing and time consuming.

**Comment by iJungleboy** [comment]
This is super easy (unless i got the question wrong). Don't press save - just click on another tab. It'll ask if you want to save and swith language.

**Comment by mconta** [comment]
You are right when editing the single app from the page.

If you load "App Management", "Manage", "Content", click on "Show Items", and then "EDIT" appears the editing window with a combobox on with the languages.

The change of the language doesn't save the changes done on the fields.

![image](https://cloud.githubusercontent.com/assets/2010201/6558648/aa70a8c6-c67d-11e4-91ab-2a9171889f44.png)

![image](https://cloud.githubusercontent.com/assets/2010201/6558671/d993c692-c67d-11e4-95b8-5bdce7b5b3a1.png)

I use this view because it permits to show all the apps and gives a simple access to all the items.

**Comment by iJungleboy** [comment]
Ok, I get your problem. 

Your easiest solution is to create your own list-page in 2sxc. That's easy to do, and will then automatically open the "standard" lightbox.

ATM we won't rework the admin-UI because we first need to create a full-featured (but secure) Web-API to load/save all data. That will take another while, so admin-UI won't get any attention for quite another while.

**Comment by mconta** [comment]
Ok, it makes sense. 
But I found that the popup doesn't appear also in some situation when editing HTML content, no save request appears and the content is lost.

If you change for example the image url using the HTML editor dialog, no popup appears.

**Comment by iJungleboy** [comment]
multi-language editing now possible in 7.3 beta :).
