### ISSUE TITLE
Emojis Cause Errors

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#1701]
**I'm submitting a ...**  
[x] bug report

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management

**Current behavior**
If a content editor uses emojis such as 🏆 in a content type using the string-default data type, the Manage Content / Data screen will fail to open with a 500 error. However, when viewing the data in a template, the emojis appear properly.

**Expected behavior**
The emojis should not affect the display of Content Items.

**Minimal reproduction of the problem with instructions**
Create a Content type using the string-default data type. Add content items with some emojis in the string-default field. Then try to open the Manage Content / Data screen and notice the 500 error.

**What is the motivation / use case for changing the behavior?**
Users may wish to use emojis in their content items.

**Please tell us about your environment:**
Windows 2012 R2 Server, IIS

* **2sxc version(s):** 9.33.0
* **Browser:** [all ]
* **DNN:** [8.0.4] 
* **Language:** [English]

**Comment by iJungleboy** [comment]
I tried it but couldn't reproduce the problem. Both in the title as well as in the body. 
Could you provide more details, maybe error messages (JS, Server, what API endpoint etc.)?
