### ISSUE TITLE
quick-edit-config generates error CS1061: 'ToSic.Sxc.Edit.InPageEditingSystem.IInPageEditingSystem' does not contain a definition for 'Attribute'

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1702]
**I'm submitting a ...**
[x] bug report

**...about** 
[x] Razor templating

**Current behavior**
Adding this line to the view:
`<div @Edit.Attribute("quick-edit-config", new { modules = new {  enable = false }})></div>`

generates this error:
`CS1061: 'ToSic.Sxc.Edit.InPageEditingSystem.IInPageEditingSystem' does not contain a definition for 'Attribute' and no extension method 'Attribute' accepting a first argument of type 'ToSic.Sxc.Edit.InPageEditingSystem.IInPageEditingSystem' could be found (are you missing a using directive or an assembly reference?) at System.Web.Compilation.AssemblyBuilder.Compile() at System.Web.Compilation.BuildProvidersCompiler.PerformBuild() at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound) at System.Web.Compilation.BuildManager.GetCompiledType(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetCompiledType(String virtualPath) at ToSic.SexyContent.Engines.RazorEngine.CreateWebPageInstance() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 109 at ToSic.SexyContent.Engines.RazorEngine.InitWebpage() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 126 at ToSic.SexyContent.Engines.RazorEngine.Init() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 30 at ToSic.SexyContent.Engines.EngineBase.Init(Template template, App app, IInstanceInfo hostingModule, IDataSource dataSource, InstancePurposes instancePurposes, SxcInstance sxcInstance, Log parentLog) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\SexyContent\Engines\EngineBase.cs:line 59 at ToSic.SexyContent.SxcInstance.GetRenderingEngine(InstancePurposes renderingPurpose) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\SexyContent\SxcInstance_Render.cs:line 119 at ToSic.SexyContent.SxcInstance.Render() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\SexyContent\SxcInstance_Render.cs:line 58`

* **2sxc version(s):** 9.40.1

**Comment by iJungleboy** [comment]
thx! I think we accidentally renamed a public API method - will fix ASAP and republish 9.40.02

**Comment by eXistenZe** [comment]
A global setting for disabling quick edit would be greatly appreciated. Having to add the line to all views is bothersome.

**Comment by iJungleboy** [comment]
just fixed the code, will probably release tonight. 

to disable it at a global level, just add that attribute (see the resulting html) to something around everything - like in the theme.

**Comment by iJungleboy** [comment]
@eXistenZe so basically adding something like this attribute should already do it: 

`quick-edit-config='{ "enable": false }'`
