### ISSUE TITLE
Error on import app

### ISSUE THREAD

**Issue by adaosantos** [2sic/2sxc#1709]
**I'm submitting a ...**  
[x] bug report

**...about**   

[x] Content Types or data management

**Current behavior**

When i try import a app from other portal
![image](https://user-images.githubusercontent.com/4481171/54150000-3921da80-4416-11e9-98c2-caf402b2c74d.png)

**Expected behavior**
Finish with success

**Minimal reproduction of the problem with instructions**
Import one large app entire app.
**Please tell us about your environment:**

IIS 10

* **2sxc version(s):** 9.33.0  
* **Browser:** [all ]
* **DNN:** [9.02.02 ] 
* **Language:** [any/all]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Based on the error, I assume you have something special in the path of either your installation or your app. Maybe it's an Umlaut or something unusual? Please research that and post your findings, if it turns out to be a 2sxc error, I'll reopen the issue.
