### ISSUE TITLE
Cannot delete 2sxc App after installing it

### ISSUE THREAD

**Issue by lucatescari** [2sic/2sxc#1714]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] admin experience UI
[x] other / unknown

**Current behavior**

If you install a 2sxc App, you are not able to delete it in the Apps Management anymore.

**Expected behavior**

It is expected to be able to delete 2sxc Apps.

**Minimal reproduction of the problem with instructions**

- Install a 2sxc App
- Try to delete it

**Please tell us about your environment:**

Windows 10

* **2sxc version(s):** 9.42  
* **Browser:** [all]
* **DNN:** [all] 
* **Language:** [any/all ]

**Anything you would like to add**
After looking into the database, I found out that the issue is that the EntityRelationship of the app does not get deleted. If you delete this manually in the DB, you can delete the App afterwards through the 2sxc UI.

**Comment by Accuraty** [comment]
I have experienced this recently too. If the fix is not easy or likely to come in a near-term release, could you please post a brief set of steps needed to do this manually?

**Comment by iJungleboy** [comment]
we'll look at this asap. @lucatescari can you give me more details, what must be done manually (so I can automate it), when it doesn't work?

**Comment by iJungleboy** [comment]
Found the solution. It's a complex interplay between json-entities in the DB, so basically it seems to mainly occur on apps with inner content (like with the accordion)
