### ISSUE TITLE
Installing the same app with new name shows warning even though it works

### ISSUE THREAD

**Issue by lucatescari** [2sic/2sxc#1715]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] admin experience UI
[x] other / unknown

**Current behavior**

If you try to install a 2sxc App again (which is already installed), you will instantly get an error message.

**Expected behavior**

It is expected that a prompt appears, telling you that this app is already installed, and asking you if you want to install it with another name.

**Minimal reproduction of the problem with instructions**

- Install a 2sxc App
- Try to install the same 2sxc App again

**What is the motivation / use case for changing the behavior?**

This is a feature which was very handy, which used to work. 

**Please tell us about your environment:**

Windows 10

* **2sxc version(s):** 9.42  
* **Browser:** [all]
* **DNN:** [all] 
* **Language:** [any/all]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
I just tried this - temporarily I saw an error, but a few seconds later it completed. Can you check/verify that 

a) you're using 9.42
b) it really doesn't work - it should ask you in a js-input for a new name, then use tha

**Comment by lucatescari** [comment]
You are right, I've now tried on other installations of DNN & 2sxc too. The error does show, but it also shows the js dialog. After reload i saw that the import did work.

**Comment by iJungleboy** [comment]
that's great. so we just have to fix to not show an error, if it actually works...

**Comment by iJungleboy** [comment]
Should be fixed now, got cleaned up when we did #1842
