### ISSUE TITLE
Improve view permission error log

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1716]
**I'm submitting a ...**
[x] feature request

**...about**
[x] admin experience UI

**Current behavior**
When a user accesses a view without the permission to do so, a generic error is logged:
This view is not accessible for the current user. To give access, change permissions in the view settings. See http://2sxc.org/help?tag=view-permissions

**Expected behavior**
If the error contained the app id/name and the view in question, we could fix the error without needing input from the user.

**What is the motivation / use case for changing the behavior?**
Improve app logging so that errors can be fixed asap.

* **2sxc version(s):** 9.41.1

* **DNN:** [ 9.3 ]

**Comment by iJungleboy** [comment]
I believe the new insights should solve most of this, will close for now.
