### ISSUE TITLE
FAQ with Categories throws error after upgrade to DNN 9.3.1

### ISSUE THREAD

**Issue by TopCat6** [2sic/2sxc#1718]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] Razor templating

**Current behavior**

After upgrade to DNN 9.3.1 I get this error using 9.32.01 LTS
`ExceptionHash:WCCVXJbGkoyI+6qP5TJqg/P/ujE=

Message:Search: Error while indexing module 3476 on tab 1429, portal 27

StackTrace:

InnerMessage:An item with the same key has already been added.

InnerStackTrace:

at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value) at ASP._Page__0__2sxc_FAQ_with_Categories__Split_view_part_2___Questions_list_filtered_by_URL_Param_cshtml.CustomizeData() in c:\DotNetNuke\Website\[0]\2sxc\FAQ with Categories\_Split view part 2 - Questions-list filtered by URL-Param.cshtml:line 12 at ToSic.SexyContent.Engines.RazorEngine.CustomizeData() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 143 at ToSic.SexyContent.Environment.Dnn7.Search.SearchController.GetModifiedSearchDocuments(IInstanceInfo instance, DateTime beginDate) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Search\SearchController.cs:line 75`

After upgrading 2sxc to version 9.42, no joy but now this error:
`AbsoluteURL:/dotnetnuke/API/PersonaBar/Extensions/GetInstalledPackages

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:81eaddd5-979e-448b-9f29-b40575daa988

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:ALLxDIpz1CxjEaHHusOe1YbSu3M=

Message:The process cannot access the file 'C:\DotNetNuke\Website\DesktopModules\ToSIC_SexyContent\Upgrade\Log\2019-04-05 00-38-02-4661319-13816-5.log.resources' because it is being used by another process.

StackTrace:

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) at ToSic.SexyContent.Environment.Dnn7.Installation.Logger.OpenLogFiles() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Environment\Dnn7\Installation\Logger.cs:line 55 at ToSic.SexyContent.Environment.Dnn7.Installation.InstallationController.UpgradeModule(String version) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Environment\Dnn7\Installation\InstallationController.cs:line 66 at ToSic.SexyContent.Environment.Dnn7.DnnBusinessController.UpgradeModule(String version) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Environment\Dnn7\DnnBusinessController.cs:line 88 at DotNetNuke.Entities.Modules.EventMessageProcessor.UpgradeModule(EventMessage message)

InnerMessage:

InnerStackTrace:

Source:mscorlib`

**Expected behavior**

Click on FAQ question and answer appears
**Minimal reproduction of the problem with instructions**

Template file is:  _All questions (sorted) of a selected category.cshtml
**What is the motivation / use case for changing the behavior?**

Bug
**Please tell us about your environment:**

Windows 10, DNN 9.3.1, 2sxc 9.42, Firefox 66.0.2, English
* **2sxc version(s):** 9.X.X  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [all | 7.4.2 | 8.X.X | 9.X.X ] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
These errors don't have anything in common. The can't-access-message may come when you are running iis with multiple threads, but that causes loads of problems anyhow, so nobody I know does that. Did you try a server restart?

**Comment by TopCat6** [comment]
I did try a server restart (this is on localhost) and the errors in the log no longer appear. However, the answers in the FAQ still do not appear when the questions are clicked, and when edition a question the Content section will not expand. The Blueimp Gallery also shows this problem with the Content section not expanding to show any content. All this with no error messages.

**Comment by iJungleboy** [comment]
so I would assume the initial bugs you had are gone and I wouldn't focus on them any more. ATM I think you're running into some trivial JS issue. I suggest you temporarily disable client-dependency management or at least update the number, I think that will fix it.

**Comment by TopCat6** [comment]
Ok, thanks. I incremented the number, but still get the same behaviour. I checked the console for error messages and found two:

**ReferenceError:** initFaqSection is not defined[Learn More] Content-Test-Page:422:3
onmozfullscreenchange is deprecated. export-bundle.js:98:521152
onmozfullscreenerror is deprecated. export-bundle.js:98:521152
Object { lineWidth: 4, strokeStyle: "#009688", joinstyle: "round", outlineColor: "white", outlineWidth: 2 }
eav-admin.min.js:2:492
openEditItems: partOfPage: true  publishing: DraftOptional eav-admin.min.js:2:16294
ocLazyLoad.fileLoaded ../edit/extensions/field-string-wysiwyg-tinymce/set.js set.min.js:118:8
The resource at “http://cdn.tinymce.com/4.6/tinymce.min.js” was blocked because content blocking is enabled.[Learn More] Content-Test-Page

**Error:** Unable to load //cdn.tinymce.com/4.6/tinymce.min.js
n.buildElement/d.onerror@http://localhost/DotNetNuke/desktopmodules/tosic_sexycontent/dist/lib/angular/set.min.js?sxcver=9.42.0.30459:418:9546

**Comment by iJungleboy** [comment]
Just to clarify: the dnn page loads normally, I presume you get the error when you enter edit mode - correct? because it seems to have an loading the wysiwyg-editor tinyMCE from a CDN. Is this correct, or am I missing something?

**Comment by iJungleboy** [comment]
are you using chrome?

**Comment by TopCat6** [comment]
Yes, the page seems to load normally, however the console shows these errors in Firefox:

Loading failed for the <script> with source “http://localhost/DotNetNuke/dotnetnuke/[0]/2sxc/FAQ%20with%20Categories/assets/faq.js?cdv=1178”.

ReferenceError: initFaqSection is not defined[Learn More] 
    <anonymous> http://localhost/dotnetnuke/Modules-Being-Tested/2sxc-Test-Page/Content-Test-Page:368
    jQuery

After logging in, the same messages appear. Clicking a FAQ item does nothing. Clicking the edit pencil produces these errors:
The resource at “http://cdn.tinymce.com/4.6/tinymce.min.js” was blocked because content blocking is enabled.
Error: Unable to load //cdn.tinymce.com/4.6/tinymce.min.js
n.buildElement/d.onerror@http://localhost/DotNetNuke/desktopmodules/tosic_sexycontent/dist/lib/angular/set.min.js?sxcver=9.42.0.30459:418:9546
set.min.js:118:

Therefore, since it sees //cdn.tinymce.com/4.6/tinymce.min.js as a 'tracker' I disabled content blocking and then the full edit pop-up appeared showing the question, answer and categories.

However, the FAQ still does not work... clicking on the question (non-edit mode) produces no answer. Presumably, this has something to do with the message:
Loading failed for the <script> with source “http://localhost/DotNetNuke/dotnetnuke/[0]/2sxc/FAQ%20with%20Categories/assets/faq.js?cdv=1178”

A previous message states:
The script from “http://localhost/DotNetNuke/dotnetnuke/[0]/2sxc/FAQ%20with%20Categories/assets/faq.js?cdv=1178” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.

In Edge browser, the error appears as:
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - http://localhost/DotNetNuke/dotnetnuke/[0]/2sxc/FAQ%20with%20Categories/assets/faq.js?cdv=1178

In looking at the URI again, there is an extra 'dotnetnuke' in the path. The proper path would be:
http://localhost/DotNetNuke/[0]/2sxc/FAQ%20with%20Categories/assets/faq.js?cdv=1178

I think this must be the reason for the failure. Perhaps something in DNN 9.3.1 has changed since 9.2.2 that returns the wrong path in the URI.

**Comment by iJungleboy** [comment]
So the core issue is that it's not loading the JS it needs. Why it's not doing that isn't sure, but I see two issues: 

1. for some reason, it seems that your server says the js file is text/html - so it refuses it. The reason seems to be the `[0]` in the url, which looks wrong. a `0` could be right, but `[0]` doesn't seem ok. How is that url generated? 
1. for probably a different reason, it thinks the CDN JS is blocked by firefox because it thinks it's an advertising system. That seems to be a tough security setting in firefox, which you can loosen.

**Comment by TopCat6** [comment]
2. Yes, as I mentioned, I loosened the security setting and the CDN JS was no longer blocked, allowing the Edit process to work properly.

1. The [0] is the correct path. There are two script references for 2SXC just before the end of the Head section:

<script src="/dotnetnuke/[0]/2sxc/Content/GettingStarted/assets/scripts.js?cdv=1178" type="text/javascript"></script><script src="/DotNetNuke/dotnetnuke/[0]/2sxc/FAQ with Categories/assets/faq.js?cdv=1178" type="text/javascript"></script>

The first one is constructed properly, but the second one has an extra 'dotnetnuke/' directory listed in the path section. I don't know where these `<script>` statements are generated.

**Comment by iJungleboy** [comment]
In your files of the app, you see a few cases of 

```
<script src="@App.Path/assets/faq.js" data-enableoptimizations="true"></script>
```

That's where it's generated. Maybe somebody modified it on your installation? Otherwise I have no idea why the extra DotNetNuke is added. Basically the `App.Path` finds the folder where the app is located, and uses DNN configuration to figure out what the root is.

**Comment by iJungleboy** [comment]
Note that I'll close this task for now, as I believe it's not relevant to other user. Feel free to post Updates, I'll keep an eye on it.

**Comment by TopCat6** [comment]
I've checked and none of the files have been modified. Here's the difference:

In '\GettingStarted\Address-AddressList.html' you use the method of [App:Path] which works fine:
`<script type="text/javascript" src="[App:Path]/GettingStarted/assets/scripts.js" data-enableoptimizations="true" />`

In '\FAQ with Categories\_Manuall selection of existing questions.cshtml' you use the method of @App.Path which adds the extra directory to the path:
`<script src="@App.Path/assets/faq.js" data-enableoptimizations="true">`

Since these files used to work fine in previous DNN releases, do you think this means that some code has changed in the `@App.Path` code for DNN 9.3.1?

**Comment by TopCat6** [comment]
Apparently, this was a known problem in Angular cli 1.3.2 but fixed in 1.4.0.  But now 1.6.3 seems to have the same problem again. See:  
Angular cli Generates Wrong Directory Path in app.module.ts 
[https://github.com/angular/angular-cli/issues/7135](url)

**Comment by iJungleboy** [comment]
Sorry, I'm still confused. 
So first of all - App.Path uses the DNN path for the portal root, and adds the app-part to it. I haven't heard of a case where this changed in dnn 9 or 2sxc 9. Also, the [App:Path] and @App.Path behave identically AFAIK. Since the path is in the html-source (or at least I assume it is), Angular isn't involved yet. Am I missing something?

**Comment by TopCat6** [comment]
Well, `@App.Path` seems to add an extra level to the path. Here is the evidence:

At the top of this page, I have the 2sxc demo content for 'Getting Started'. Note that the path for the image is constructed properly:
`<img class="co-image" src="/dotnetnuke/[0]/GettingStarted-Examples/Penguins.jpg?w=980&amp;h=250&amp;mode=crop" alt="Penguins - This image will be cropped by the FullWidth template. Look at the parameters after [Content:Image] in the template.">
`

That module is followed by the 2sxc FAQ module:
`<li class="sc-element faq-set" data-tags="715">
    <a class="faq-question" style="cursor: pointer">
        Can this be modified?
    </a><div class="faq-answer" style="display: none"><p>Yes, if you can code.</p></div></li>
`

The Firefox Console, however says that the initFaqSection is not defined.
`<script>
	$(document).ready(function() {
		initFaqSection("DnnModule-" + 3527, "slide");
	});
</script>`

Looking in the head section, we see script tags for loading the scripts (I include the jquery one here for reference):
`<script src="/DotNetNuke/Resources/libraries/jQuery-UI/01_12_01/jquery-ui.js?cdv=1178" type="text/javascript"></script>`
`<script src="/dotnetnuke/[0]/2sxc/Content/GettingStarted/assets/scripts.js?cdv=1178" type="text/javascript"></script>`
`<script src="/DotNetNuke/dotnetnuke/[0]/2sxc/FAQ with Categories/assets/faq.js?cdv=1178" type="text/javascript"></script>`

The 'GettingStarted' one is generated properly and it work in the page just fine.
The 'FAQ with Categories' script tag has an extra level in its path name.

Looking at the source files, the only difference I can see it that the one that works is an .html file that uses `src="[App:Path]/ ` (in file `\GettingStarted\Address-AddressList.html`), while
the FAQ source is in a .cshtml file and uses `src="@App.Path/` which results in an extra level being introduced into the path name.

That extra level causes the script file to be not found, since the local path on the disk is:
`C:\DotNetNuke\Website\[0]\2sxc`
and IIS Manager shows:
`Virtual Path`      `Physical Path`
`/DotNetNuke`    `C:\DotNetNuke\Website`

That is the evidence that `@App.Path` is introducing an extra level.
