### ISSUE TITLE
Can't drag and drop in DNN9

### ISSUE THREAD

**Issue by ICATT** [2sic/2sxc#1721]
**I'm submitting a ...**
[x] bug report

Seems similar to [963](https://github.com/2sic/2sxc/issues/963) and [1137](https://github.com/2sic/2sxc/issues/1137) but these are resolved in older versions.

**...about**
[x] edit experience / UI

**Current behavior**
* Apps are always added to default contentpane when dragging and dropping a new app to a page.
* Apps can't be dragged to another pane.

**Expected behavior**
Dragging and dropping works like other DNN modules.

**Minimal reproduction of the problem with instructions**
* Drag a new app to any pane but the default pane. The app will be added to the default pane anyway.

OR

* Use the DNN move to context menu to move the app to another pane. This will work. Try dragging it to another pane. This won't work.

**Please tell us about your environment:**

* **2sxc version(s):**
9.32.1
* **Browser:**
All
* **DNN:**
9.2.2
* **Language:**
Dutch
* **Skin**
Probably all, but reproducible in Xcillion

**Comment by iJungleboy** [comment]
we'll look into this

**Comment by marcingarbarczyk** [comment]
I have this problem again (earlier in DNN8). You can move it only by moving other modules unfortunately.

**Comment by iJungleboy** [comment]
Thx. Anybody have an idea why this is? does DNN show any bugs/errors?

I assume move with quickE still works, right?

**Comment by iJungleboy** [comment]
closed because of inactivity.
