### ISSUE TITLE
[Feature request] For Views, Move the Photo/Icon assignment to View Management

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#1724]
[x] feature request

[x] edit experience / UI
[x] admin experience UI

**Current behavior**
To assign an icon/image to a View, right now you create a PNG and name it identical to the .cshtml file. This causes the icon/image to show automatically in the Change Template (View) UI.

**Desired behavior**
When in Admin/Views and editing the view, you should be able to use the well-established 2sxc pattern of having a field for this and adding/assign an image to use as the icon for the view. Nicer still if it supported PNG, JPG, GIF, SVG, and others. 
 
The current method is hacky and tedious and breaks easily as projects evolve. It prevents ending up in production situations that look clunky and unplanned because the current method for assigning/providing these UI elements is not obvious or intuitive.

Environment: n/a
2sxc version(s): requesting based on 9.42 
Browser: all/any
DNN: all, Language: any/all
 
IMHO this would have huge ROI for agencies like us creating customized, highly effective client-managed CMS scenarios.

**Comment by iJungleboy** [comment]
Needs sponsoring, so added to #2107 and will close unless someone contributes or sponsors this.

**Comment by iJungleboy** [comment]
We're reopening because new features in 12.02 would benefit from this.

**Comment by iJungleboy** [comment]
It's now implemented that you can

1. Just drop a file using ADAM
2. or specify an alternate icon in the app folder using `[App:Path]/some-icon.png`

**Comment by iJungleboy** [comment]
Note: also related to #2430

**Comment by jeremy-farrance** [comment]
> 2\. or specify an alternate icon in the app folder using `[App:Path]/some-icon.png`

Is it still only PNG or will it detect JPG too?

**Comment by iJungleboy** [comment]
Any pic should work.
