### ISSUE TITLE
Fields named "Body" in xml-export causes trouble in Excel

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1736]
**I'm submitting a ...**
[x] feature request

**...about** 
[x] other / unknown

**Current behavior**
Some 2sxc apps have a field named "Body", like Blog or News app.
When we export the table/entity of the posts, most of the apps will not open it since the <Body> tag is not expected as a field.

**Expected behavior**
In the next versions, is it possible to change the field names?

**Comment by iJungleboy** [comment]
Sorry, I'm confused. Is "Body" a protected term in xml or what is happening?

**Comment by eXistenZe** [comment]
I think it's not xml itself, but the way apps deal with the tags.
Excel for example will say the file is corrupt.
Changing Body to something else fixes the "issue".

**Comment by iJungleboy** [comment]
ok, we'll look into it.

**Comment by iJungleboy** [comment]
We'll rename the field to "Content" in the Blog App V4 - to be release the next few days ;)
