### ISSUE TITLE
Method to access code in .cs files from pages and web-api

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#1743]
**I'm submitting a ...**  
[x] feature request

**...about**   
[x] Razor templating

**Current behavior**
It's very hard to share code between files, so this should be made easier. 

**Expected behavior**
Ideally I can do something like have a .cs file with shared code, and call it ca. like this:

```
dynamic Shared = Compile("shared.cs");
```

**What is the motivation / use case for changing the behavior?**
Improve shared code experience for developers. 

**Please tell us about your environment:**

* **2sxc version(s):** 9.43

**Anything you would like to add**

Here some sample code on which we will build this feature

```
private dynamic InstantiateClass(string name){
    var fileName = name + ".cs";
    var path = System.IO.Path.Combine("~", App.Path, getEdition() , "api/Parts", fileName);
    var assembly = BuildManager.GetCompiledAssembly(path);
    var compiledType = assembly.GetType(name, true, true);

    object objectValue = null;
    if (compiledType != null)
    {
      objectValue = RuntimeHelpers.GetObjectValue(Activator.CreateInstance(compiledType));
      return ((dynamic)objectValue);
    }
    throw new Exception("Error while creating class instance.");
  }
```

## What should be improved on this

1. use a better term like `Compile`
2. if possible, auto-attach current context like the Dnn, App, etc. objects

**Comment by Accuraty** [comment]
I am not sure this is the type of solution you are looking for OR that is does not have performance penalties or other concerns, but we do this using a .cshtml file in the /App_Code folder. Here are my notes on it. We are using this successfully in 4 or 5 projects and it allows the methods to be called from both Razor and normal .ascx files. So its very useful. It feels hacky...

From my personal dev notes:

[ little known? ] Fact: you can put a .cshtml Razor file in DNN's /App_Code folder with "public static functions" and they will be available for use across all scripts in both 2sxc and RazorScript (RazorHost).

DNS Lookup of Host Name and getting the visitor's IP addr:
```
_my-razor-script.cshtml
@if ( @ASLHelpers.GetIpAddress() == "111.11.123.12" ) { 
    <h5>DEBUG >>> Visible Only to WAN IP @ASLHelpers.GetIpAddress()</h5>
    <h6>Server Now: @DateTime.Now.ToString("F")</h6>
    <h6>accuraty.net resolves to @ASLHelpers.GetIpFromHostname("accuraty.net")</h6>
    <h5>DEBUG >>> END OF DEBUG</h5>
}
```

The above REQUIRES that the GetIpAddress() (or any methods) be available in the CSHTML file in /App_Code. The ASP.NET site will have it compiled and ready to use, referenced by the filename (like a namespace?).

Here is the contents of ASLHelpers.cshtml as of 10/15/2018

```
@* Changes and updates: 
- added GetIpFromHostname(); resolve a DNS entry (FQDN)
- added GetIpAddress() of the website visitor
- New 20181015 JRF 
Recap: Accuraty's shared standard utility functions
Reminder: the secret is "public static"
*@
@using System.Net
@using System.Net.Sockets
@functions {
//Get IP address of the visitor method
public static string GetIpAddress() {
string stringIpAddress;
stringIpAddress = Request.ServerVariables["HTTP_X_FORWARDED_FOR"];
if (stringIpAddress == null)
{
stringIpAddress = Request.ServerVariables["REMOTE_ADDR"];
}
return stringIpAddress;
}
//Get IP from Hostname (FQDN)
public static string GetIpFromHostname(string Hostname) {
string ip = "";
try
{
IPHostEntry ipHostEntry = Dns.GetHostEntry(Hostname);
if ( ipHostEntry.AddressList.Length > 0 )
{
//ip = ipHostEntry.AddressList[0].Address.ToString();
ip = ipHostEntry.AddressList[0].ToString();
}
else
{
ip = "No information found.";
}
}
catch ( Exception )
{
ip = "An unspecified error occured.";
return ip;
}
return ip;
}
}
```

**Comment by iJungleboy** [comment]
@Accuraty that functionality is very limited for what we need. So basically anything an app uses should be self-contained (so deploying the app includes the shared bits). 
So far we always used Cshtmls which can easily be accessed from other razor files with CreateInstance, but we were not able to share the code with webapis...

**Comment by Accuraty** [comment]
Agreed, it is a hacky convenience. :)

**Comment by iJungleboy** [comment]
almost done :)
