### ISSUE TITLE
[Feature request]Allow free folder and file creation

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1749]
**I'm submitting a ...**
[x] feature request

**...about** 
[x] DNN parts
[x] other / unknown

**Current behavior**
You can only create files at template creation and and template code edition. And only within app root folder.

**Expected behavior**
2sxc could allow for a free file and folder creation anywhere within the app folder.
If you need to create an API folder and a controller for example, you can't do it in 2sxc.

**Comment by iJungleboy** [comment]
We'll consider this. ATM not too high a priority, but I understand the need.

**Comment by iJungleboy** [comment]
closed because of inactivity
in future, the code editor will be enhanced, but that's a separate big milestone.
