### ISSUE TITLE
Pipeline Designer: Add buttons for the various edit-actions on a DataSource

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#175]
Buttons we need
* Edit Title (not really necessary, because it's not important, and if you do try it, you'll find it)
* Edit Description (not really necessary, because it's not important, and if you do try it, you'll find it)
* Edit Settings - important - glyphicon-list-alt - maybe in the top left corner? and enable single click on it...
* New Output (the orange box) - add the glyphicon-plus into the box, or replace the box with a glyphicon-plus-sign (the circle plus)
* Input (maybe - the green circles) glyphicon glyphicon-circle-arrow-up
* output (maybe - green circles) glyphicon glyphicon-circle-arrow-up (same symbol)
* maybe then remove the arrows on the lines, as they look nasty when there is little room...

Approx like this
![image](https://cloud.githubusercontent.com/assets/5321186/6683334/0a8b95f6-cc85-11e4-88d2-03d540aabc88.png)

**Comment by BeniGemperle** [comment]
Having Glpyh
