### ISSUE TITLE
Link for "help here" on Hyperlink settings fails

### ISSUE THREAD

**Issue by Accuraty** [2sic/2sxc#1750]
I'm submitting a bug report about admin experience UI, specifically Content Type management.
 
See screen clip, when you are editing the fields of a Content Type like Hyperlink, under the Buttons field when you clieck the "help here" link, the URL is broken. It is probably just a relative URL that needs to have the whole thing in there, "https://..."
 
When you click the link you get a URL like this and therefore a 404

http://mysite.myserver.ws/desktopmodules/tosic_sexycontent/dist/dnn/2sxc.org/help?tag=field-hyperlink

The correct/intended URL is probably
https://2sxc.org/help?tag=field-hyperlink 

Running on 2sxc 10.00.00
All browsers
DNN 9.03.02
Any Language

![image](https://user-images.githubusercontent.com/653301/58372816-da361280-7ee8-11e9-9e44-d118244e71f2.png)

**Comment by iJungleboy** [comment]
thx.
