### ISSUE TITLE
Memory leak on 2sxc app management - data - multiple items editing

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1756]
**I'm submitting a ...**
[x] not sure

**...about**  
[x] edit experience / UI

**Current behavior**
In the data tab, if I open an entity, edit dozens of records in succession, memory use in ff spikes from 1gb to 6+ gbs until it becomes unusable. Reloading the page solves the issue.

* **2sxc version(s):** 10
* **Browser:** [ Chrome XX | Firefox 67 ]
* **DNN:** [9.3.2 ]

**Comment by iJungleboy** [comment]
Just a question: does this seem to be an issue of the list, or of the form? Because we believe the form is destroyed every time it's closed, but just want to confirm.

**Comment by eXistenZe** [comment]
Both it seems.
Small increases on list scroll. But keeps increasing.
10-20mb increase for each row opened and closed.

Only fully closing 2sxc windows (return to view) decreases mem to normal.

**Comment by iJungleboy** [comment]
ok thx. 

This is basically the main AngularJS-Admin UI (the old tech), which we'll hope to replace within a few months. So we won't address this till then, which is why I'll close this.
