### ISSUE TITLE
[Feature request] Calculated fields

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1757]
**I'm submitting a ...** 
[x] feature request

**...about**  
[x] Content Types or data management

**Current behavior**
I believe the only way to use calculated fields in 2sxc is inside a template with c# and linq.

**Expected behavior**
3 ways this could be implemented:
- True calculated field, dynamic. When creating a field, allow a new type "calculated" and ask for a formula in the config. Some basic functions like sum, concatenation, etc could be preconfigured, or fully support any operation like access, excel, spss, etc.
- Within a query. Add a new function that allows creating new fields into the stream based on a calculation.
- Allow selection multiple "labels" in a dropdown from query field (like access does). Not related to the 2 solutions above, but very helpful in some situations.

**What is the motivation / use case for changing the behavior?**
I work with a lot of content analysis and analyzing relationships requires two fields concatenated into a new one.

**Comment by iJungleboy** [comment]
Hi @eXistenZe - I understand what you would like. I assume to really be good, this shouldn't be form depend, but at runtime - so that imported data would also result in calculations, not just data that is being edited by a user, correct?

**Comment by eXistenZe** [comment]
Many many things to consider on implementation, but it needs proper app knowledge, which I don't  have.

If it's a query implementation, no further decisions needed, it calculates the values when the query runs. It does not mess with tables.

If it's a true calculated field, two routines are needed. One for calculating the field when the record is being created or updated (run at start, run on values change) and one for updating all the records in the table. When should the global calculation be run? When it causes less trouble... A manual option is always welcome (update only when requested by button and confirmation). An automatic one could be enabled or disabled on some situations, but they can cause severe issues (if the table is huge, running an update will slow the app/server).

For a simple and effective start without any risk to break anything, the query and manual update could work.

Another important issue is how the app will deal with errors? What will the field store if the calculation fails? A divide by zero? A math operation on strings? Store an error? Store an empty value? Serve an error an do not allow to proceed?

**Comment by iJungleboy** [comment]
Will be in 12.01 - to be released on Towel-Day. If you have time we would appreciate it if you could test it and give us feedback.

**Comment by iJungleboy** [comment]
Just fyi: 12.01 will contain formulas which are calculated fields / settings in the UI. They are not server-side but run at the time of user edit.
