### ISSUE TITLE
[Feature request]When editing an item with toolbar, do not reload the page if no changes were made

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1759]
**I'm submitting a ...**
[x] feature request

**...about** 
[x] Razor templating
[x] other / unknown

**Current behavior**
When viewing a template with a toolbar for each item (inside a loop for example), if you click to edit an item (pencil icon), when exiting the page reloads to show the changes, even if no changes were made.

**Expected behavior**
Reload the page only if "save" button is pressed. Do not reload if clicked outside the window without changes or choosing "do not save" if changes were made.

**What is the motivation / use case for changing the behavior?**
Time saving.

* **2sxc version(s):** 10

**Comment by iJungleboy** [comment]
I assume this affect is primarily in a custom app. Have you tried enabling ajax on the app?

**Comment by eXistenZe** [comment]
Nope. Simple form, default 2sxc forms.
But enabling ajax does prevent reloading and updates the field if simple things are changed (like strings).
Things that need a reload like changing a category that will move an item from one table to another will not work, but a manual reload fixes it (I like it better this way).
Thanks.

**Comment by eXistenZe** [comment]
Nevermind. Even changing categories and content places work. I didn't use any special code, just simple tables with loops. But they update fine without reloading. I don't even know what ajax is, but I really like it.

**Comment by iJungleboy** [comment]
awesome :)
AJAX means that it loads the part of the page by itself, without rebuilding the whole page. It's the default experience on any normal content and optional for Apps, because these could have some complex JS that might make the preview look wrong, so it's optional.
