### ISSUE TITLE
[Small issue] Save button minimizing to icon animation is not very user friendly

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1760]
**I'm submitting a ...**
[x] not sure

**...about**
[x] Content Types or data management

**Current behavior**
The new "save" button minimizes to an icon after a couple seconds.
This sometimes leads to the button "running away" from the mouse when you are trying to save.

**Expected behavior**
Choose either the full button or the icon. Animations are for kids, not proper programmers :)

* **2sxc version(s):** 10

**Comment by iJungleboy** [comment]
thanks for the input. for now we are going to leave it this way, because we actually want it small, but need people to discover what it does, and that ctrl+s will work. If we get a lot of this kind of feedback, we'll reconsider :)

**Comment by eXistenZe** [comment]
A tooltip could do the job.
