### ISSUE TITLE
Export should not include PortalFiles and PortalFolders

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#1763]
I'm submitting a bug report admin or other

**Current behavior**
I often re-use an existing Content-Type by using an Export, then hand edit the XML, then Import. (aside: sure would be nice if we had a copy/clone/duplicate feature for a Content-Type like we do for a data/record type)
 
This means I go to Admin, App, then Export Parts. By default, nothing is checked. I simply check 1 top level item (for example, in the Content-App 3.x, Location) and NO views or records (Templates or Entities (gosh the terminology swapping is hard sometimes)). I run the export (thank you for fixing this in 10.01) and I get my XML file, but it contains all the file and folder IDs and RelativePaths for (apparently) all the existing Entities that I did not include. 

**Expected behavior**
I believe when no Entities are exported for the Type, you should only see (if they are necessary for the import):
```
<PortalFiles />
<PortalFolders />
```
 
**Minimal reproduction of the problem with instructions**
see steps above

2sxc version(s): 10.01.00
Browser: all/any
DNN: 9.3.x 
Language: any/all

Did I mention how much time it would save to be able to clone, copy, or duplicate a Content-Type (or View/Template) like you can a record?

**Comment by iJungleboy** [comment]
We'll look into it, thx. 
And yes, a copy-feature would actually be even better. We'll have to wait a bit though, because we're trying to avoid adding features to the current admin-UI since its the old AngularJS, and everything we do we'll have to do twice.

**Comment by jeremy-farrance** [comment]
Things work differently here in 2023 (v14+) so if this comes up again it should be redone as a new issue. Closing.
