### ISSUE TITLE
[Feature request] Add prefill to public forms

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1765]
**I'm submitting a ...** 
[x] feature request

**...about**
[x] Content Types or data management

**Current behavior**
Prefill seems to work only with 2sxc own toolbars.
Tried tweaking some manage.run to apply it to public forms, but it seems to be not supported.

**Expected behavior**
Is it possible to implement prefill in public forms?

**Comment by iJungleboy** [comment]
We'll check - I think it should behave just the same way, but maybe we missed something. could you provide some sample code, and also check if the prefill-data lands in the url or not?

**Comment by eXistenZe** [comment]
Nevermind.
I tried again and it was my mistake. I was using the "new" behind the object like the razor code, but it doesn't need it.
This workd:

```
$2sxc.cms.run(
    tag,
    {
        action: "new", 
        contentType: "dxs",
         prefill: { idn: @nextIdDx }
    }
);
```
