### ISSUE TITLE
TagToolbar does not work

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1766]
**I'm submitting a ...**
[x] bug report 

**...about** 
[x] Razor templating

**Current behavior**
Added this line to template:

`@Edit.TagToolbar(actions: "new", contentType: "dxs")`

It gets replaced with this html:
`sxc-toolbar='{"toolbar":{"contentType":"dxs","action":"new","settings":null}'` 

**Expected behavior**
Creating a toolbar.

* **2sxc version(s):** 10.1

**Comment by iJungleboy** [comment]
@eXistenZe this is basically how the toolbar works - the server adds the attribute to the tag, and a JS picks this up and shows a hovering toolbar. The TagToolbar is an improvement to the previews Toolbar, which needed you to set an "sc-element" class and then add the toolbar inside it, which was often implemented incorrectly. 

Note that the toolbar should only appear on hovering over the item.

1. If I understand you correctly, the attribute is added, but you don't see the toolbar appear on screen. is this correct?
1. Do you have any JS errors popping up?
1. could you maybe export/upload your app, so we can check?

Thanks

**Comment by eXistenZe** [comment]
I don't understand what you meant.
Here's the code and the output:

```
Old: @Edit.Toolbar(actions: "new", contentType: "dxs")
New: @Edit.TagToolbar(actions: "new", contentType: "dxs")
```
https://pasteboard.co/IhFUxgI.jpg

**Comment by iJungleboy** [comment]
I get it :). The TagToolbar is meant to be used inside a tag, as it creates a floating toolbar which "follows" you. So this is how you would use it

```
<div @Edit.Tagtoolbar(...)>
   ...Contents...
</div>
```
If you just want to add a button which is always visible, the @Edit.Toolbar is still the correct choice.

**Comment by eXistenZe** [comment]
Oh. Perhaps the snippet could use the full needed code then (with the divs).
That would help.

**Comment by iJungleboy** [comment]
thx, I'll keep that in mind when I update the snippets!
