### ISSUE TITLE
Public forms only work for host

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1768]
**I'm submitting a ...**
[x] bug report
[x] not sure

**...about** 
[x] Razor templating
[x] JS development
[x] Content Types or data management
[x] other / unknown

**Current behavior**
I activated public forms on 2sxc features manager.
I gave my entities/tables view => full controll for testing. Also tested just read schema and Create Draft like shown on the tut.

Here's my code:
```
@Edit.Enable(api: true, forms: true, context: true, autoToolbar: false)
<i onclick="addDx(this)" aria-hidden="true"></i>
@foreach something... {
    <i onclick="editEntity(this, @dx.EntityId)" aria-hidden="true"></i>
}
<script>
    function addDx(tag) {
        $2sxc.cms.run(
            tag,
            {
                action: "new", 
                contentType: "dxs",
                prefill: { idn: @nextIdDx }
            }
        );
    }
    
    function editEntity(tag, EntityId) {
        $2sxc.cms.run(
            tag,
            {
                action: "edit", 
                entityId: EntityId
            }
        );
    }
</script>
```
The form works fine for my host login, but for a normal user when I click the buttons I get a browser login prompt with "DNNAPI" message, and if I esc I get a 2sxc 401 message.

**Expected behavior**
Form shown on button click.

* **2sxc version(s):** 10
* **Browser:** [ Firefox XX  ]
* **DNN:** [ 9.3.2 ]

**Comment by eXistenZe** [comment]
Also, I tested another app that was previously working with public forms, now also stopped working.

**Comment by iJungleboy** [comment]
BTW: the new form isn't ready for public forms yet, because we must ensure that it's stable enough. For public form you still need to use the classic (old) form.

**Comment by eXistenZe** [comment]
Can we switch to the old ui in the meantime?

**Comment by iJungleboy** [comment]
yes, just enable the feature for the old ui - see https://azing.org/2sxc/r/eJo6y-f-

**Comment by eXistenZe** [comment]
Working. Thanks.

**Comment by iJungleboy** [comment]
Will work on 10.06
