### ISSUE TITLE
401 error with public forms and ajax reload

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1769]
**I'm submitting a ...**
[x] bug report

**...about**
[x] other / unknown

**Current behavior**
In one app, I enabled AJAX reload (amazing feat) and public forms (another amazing feat).
After switching to the old edit UI, public forms now work properly, however I get a 401 error when I exit the form and it does not update the values (does not "reload").
The values are saved properly, the page just does not reload.
This only happens when ajax reload is enabled.

**Expected behavior**
AJAX reload works fine.

* **2sxc version(s):** 10.1

**Comment by iJungleboy** [comment]
I'll close this to avoid duplicate issues.
