### ISSUE TITLE
[Feature request] Custom snippets

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1770]
**I'm submitting a ...**
[x] feature request

**...about**
[x] edit experience / UI

**Current behavior**
There are quite a few snippets implemented in 2sxc.

**Expected behavior**
Perhaps allowing implementing some custom snippets based on a app/global file would quite improve the edit experience for those who use live editing a lot.
A simple bootstrap content or table? A js loop? Linq complex queries?
Some things that just repeat several times in the app?
Entity fields and tables? Files names?

Perhaps this is just too much trouble, but it would allow for user snippets creation and would take a load of your shoulders when updating snippets, since users can just create their own if they are not happy.

**Comment by Accuraty** [comment]
We really need this. It would be great if they were easy to manage and add and edit and export and import. And I realize they are 'in there in a spreadsheet' - but mere mortals cannot figure out how to get that updated and then processed "in to" being usable in 2sxc. Needed. Wanted. Please?

**Comment by iJungleboy** [comment]
I like the idea, but won't be able to do anything since I just have too many priorities. If someone wants to pick this up, I would be glad to give guidance.

**Comment by eXistenZe** [comment]
Think of it as 2sxc v12 features :)
Nothing major, but it would be welcome if it gets implemented.

**Comment by eXistenZe** [comment]
I know this is still v11, but do you think this is possible to implement on the next versions?

**Comment by iJungleboy** [comment]
It's on our road map. Basically the code editor now has the UX that can handle it. 
In terms of priority I assume it's not going to make it the next 3 months though, as there is quite a bit we'll work on first. Then again it's not a huge thing, so if someone wants to contribute a few hours...

**Comment by iJungleboy** [comment]
Needs sponsoring, so added to #2107 and will close unless someone contributes or sponsors this.
