### ISSUE TITLE
[Thoughth about] When the original field content is deleted, shouldn't the translated ones also become empty and untranslated?

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1771]
**I'm submitting a ...**
[x] not sure

**...about** 
[x] Content Types or data management

**Current behavior**
When an original language content is deleted, making the field empty, and the form saved, the translated fields remain translated.

**Expected behavior**
I know this may be situational, but in my apps and cases, if I delete the original content and save, the translated fields should become empty and untranslated.

**Comment by iJungleboy** [comment]
By deleted I assume you mean "made empty". In this case the behavior should be identical to when you type something into the original language:

1. if the other languages inherit the value, they should contain the same thing, whether it's a value or empty
1. if the other languages translate (don't inherit), they should remain unmodified by changes in the primary language. 

Are you running into other behavior?

**Comment by eXistenZe** [comment]
No no. It behaves exactly like that. It's number 2 that in my usecases  don't help much. But perhaps it's just for me and other users need to keep the translated fields no mather if the original one was made empty.
