### ISSUE TITLE
Bug (minor): Admin-list of Data: show values in current language, maybe even show translation state

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1772]
**I'm submitting a ...** 
[x] feature request

**...about**
[x] admin experience UI

**Current behavior**
In multi language apps, when you browser content / data in administration data tab, it always shows the original language, even if another language is set in url.

**Expected behavior**
Show content in the language defined in the url / currently in use.

* **2sxc version(s):** 10.1

**Comment by iJungleboy** [comment]
thx!

**Comment by PagnoDunadan** [comment]
I took these steps and form appears to be working correctly. Tell me if I'm doing something wrong. Could it be that your translation is still missing?

1. Set language to English
1. Open 2sxc Administration, then Data tab, then desired Content type, then first entity
Result:
![2019-06-12 08_34_05-Window](https://user-images.githubusercontent.com/7113033/59328588-00332380-8ced-11e9-80e7-9628dadb0184.png)

1. Set language to Deutsch
1. Repeat steps to open the same entity
Result:
![2019-06-12 08_36_51-Window](https://user-images.githubusercontent.com/7113033/59328696-54d69e80-8ced-11e9-9fc0-f8086654c4d8.png)

**Comment by eXistenZe** [comment]
I was referring to the list, not the item view.
If you are seeing the app in DE, when you open the admin panel the data tab should also show the translated DE content, I believe. Or is it intented to always show the original language?

**Comment by PagnoDunadan** [comment]
List of content types:
![2019-06-12 12_20_57-Window](https://user-images.githubusercontent.com/7113033/59343723-c540e800-8d0c-11e9-912f-7b75f9e8f56c.png)

List of entities in a content type:
![2019-06-12 12_23_19-Window](https://user-images.githubusercontent.com/7113033/59343771-e4d81080-8d0c-11e9-8900-2644d095df19.png)

Can you please post a screenshot?

**Comment by eXistenZe** [comment]
This: List of entities in a content type

**Comment by PagnoDunadan** [comment]
![2019-06-12 12_28_01-Window](https://user-images.githubusercontent.com/7113033/59344080-a000a980-8d0d-11e9-9a4c-482b5957c846.png)

Is there something wrong here?

**Comment by eXistenZe** [comment]
Weird. Mine always shows the default language.
I'll take some screens later on for you to check.

**Comment by PagnoDunadan** [comment]
Sure :)

**Comment by iJungleboy** [comment]
I believe this was never fully specified, since the admin-view is more for the techies and not usually used by content-editors, this has never been an issue.

**Comment by eXistenZe** [comment]
Think of it this way: how do translators know their job is done?

**Comment by iJungleboy** [comment]
@eXistenZe yes, that makes sense. 

Just to sync expectations: ATM we're still prioritizing the new form which will certainly take a few more weeks, and then we have various other priorities. So we won't address this for quite another while. If someone wants to contribute, pls contact me as we're planing a new UI for this section too, and these enhancements should be made there.

**Comment by iJungleboy** [comment]
Needs sponsoring, so added to #2107 and will close unless someone contributes or sponsors this.
