### ISSUE TITLE
[Feature request] Get list of files and folders in visual query

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1773]
**I'm submitting a ...**
[x] feature request

**...about** 
[x] Content Types or data management

**Expected behavior**
One useful datasource for visual query would be a list of files OR folders within the app root (one layer only perhaps at one time). Lets's say an app has a root folder, an API folder, images folder and shared folder. User would select what folder he wants to get the file list from (or folder list from). He would even be able to build one pipeline for each folder if needed.

Use cases example:

- Fully working folder polymorph based on an app setting: just set a new app setting, dropdown from query, get the query that lists the folders on the app root (lets say there is a appv1 and appv2 folder). On a 2s click, an admin could change the working app folder from v1 to v2. Since it's an app setting, there is no need to change any code within as all lines (like the web api calls or whatever) could use the @razor code to get the folder name within the path. Want to change live app with dev app? Easy, and with no need to change any line anywhere, since the folder name is now dynamic with the app setting var.

- Fully working individual file versioning: like the above, but if the app has only a few files (let's say less than a dozen or so), users could create a query pipeline for each file (using a value filter after the datasource), and an appsetting for each file. Again in a few seconds, an admin could change the live files with one screen and no coding. Instead of hardcoding the files names, use the @App.Settings.fileAName.

Lot's of neat features could come from this. CSS swaps on the go to show clients? No problem. Different combinations of menus, colors, APIs, footers, etc. Just point and click. 

This is sort of dependent on the other feature request about free file and folder creation. Now a duplicate folder with also be neat.

**Comment by iJungleboy** [comment]
This sounds like a great idea. I'm not sure if I understand the examples though, maybe you could elaborate: Just getting the files won't change them or switch a polymorph or something. How would this help?

**Comment by eXistenZe** [comment]
I'll build a basic demo with a simple dropdown instead of query so you can see the effect.
But the magic will come from an automated query to get files and folders automatically.

**Comment by iJungleboy** [comment]
I closed this accidentally. Where can we see the demo?

**Comment by eXistenZe** [comment]
I still have to build it. I'll send it when it's done.

**Comment by iJungleboy** [comment]
thx!

**Comment by eXistenZe** [comment]
Demos done.
But cannot export the apps:
https://github.com/2sic/2sxc/issues/1776

**Comment by eXistenZe** [comment]
Nevermind. Tried again and it exported.
Here: https://drive.google.com/drive/folders/1O9swloXK_HD8Els8G0yFoF2MHqsm6A5b?usp=sharing
One for simple folder versioning.
One for file versioning with some dynamic data too.

**Comment by iJungleboy** [comment]
@eXistenZe I'm very tight on time right now, with 2sxc 10 fine-tuning and azing-release. Could you maybe just create a short video showing it, so I can save myself a lot of time guessing what it's for etc.?

**Comment by eXistenZe** [comment]
It's a very very basic app. 30s install, 20 lines or so of code. It would be longer to watch a video.

**Comment by eXistenZe** [comment]
Also you can take the example and improve the polymorph guide to something more than admin/not-admin switch.

**Comment by iJungleboy** [comment]
Thx. I looked at it and I think I get the idea, but I'm not sure how that would help with polymorphism. Note that because of summer vacation coming up, we wouldn't be able to invest anything into this till at least middle of August.

**Comment by eXistenZe** [comment]
What better way to change versions than with a simple setting? Way better than code changing in the middle of a presentation or testing. Fast and effective.

**Comment by iJungleboy** [comment]
Version change through settings sounds attractive, but doesn't directly relate do visual-query providing files/folders.

**Comment by eXistenZe** [comment]
The query would just improve the dropdowns. Instead of creating them by memory (or see and copy with ftp), just get the file names automatically.

**Comment by iJungleboy** [comment]
I believe this isn't necessary any more, now that Polymorphism is a full feature in 2sxc. Will close for now.
