### ISSUE TITLE
In Filter is not working with array of result

### ISSUE THREAD

**Issue by ufoloko** [2sic/2sxc#1774]
**I'm submitting a ...**  
[x] bug report 

**...about**  
[x] admin experience UI

**Current behavior**
I have a RelationshipFilter with filter [In:Filter:Name], but Filter is result from other stream with more than one results, actually is working just with first result in array  

**Expected behavior**
Relationship filter should work with any of results in array for In filter

**Minimal reproduction of the problem with instructions**
I have a stream with an array of results, for example, some categories that accomplish with some other previous filters. I use this Stream as "In" filter for a RelationshipFilter. with more than one result.

* **2sxc version(s):** 9.X.X  
2sxc version is 10

* **Browser:** 

**Anything you would like to add**
Maybe is something i´m missing ?

**Comment by iJungleboy** [comment]
Probably now fixed with #2581
