### ISSUE TITLE
entity 2 doesn't have attributes

### ISSUE THREAD

**Issue by ufoloko** [2sic/2sxc#1775]
**I'm submitting a ...**  
[x] bug report 

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
I have two data tipes, one State with field Name, and have another City with field Name, and field State. State field is an attribute field, to select State for each city.

**Expected behavior**
You should be able to define datatype for entity field but when you try to save you have an error message. Internal log says "entity 2 doesn't have attributes"

**Minimal reproduction of the problem with instructions**
Create a Datatype named State with text field Name
Create a Datatype named City with text field Name and entityfield named State
Try to set EntityTipe for EntityField State, and just try to save. Not working

* **2sxc version(s):** 
10.0.1
* **Browser:** 
All

* **DNN:** 
9.3.2

**Anything you would like to add**

**Comment by ufoloko** [comment]
Just for your information, I have tested version 9.43.1 and everything is working as espected. Problem is for version 10.0.1

**Comment by iJungleboy** [comment]
ok thx. you can always open the old UI using alt-click. does it work in that?

**Comment by ufoloko** [comment]
You mean alt(key) + click, or you mean secondary mouse button ?

**Comment by ufoloko** [comment]
Oh, I got it, is alt key + mouse click, thanks is working now

**Comment by Accuraty** [comment]
Not sure if I am alone or not, but on my keyboard, this only works with the RIGHT ALT key, not the left one.

**Comment by ufoloko** [comment]
Im on a Mac, so, i don´t know how is working on PC.

**Comment by iJungleboy** [comment]
I think the alt-key is culture specific / device specific. For example German Keyboards use the right-Alt for another purpose, it's kind of not an alt-key.
Would you be able to export the app causing the problem so we could reproduce the issue?

**Comment by iJungleboy** [comment]
We'll just release 10.02, could you check if this is still an issue?

**Comment by iJungleboy** [comment]
Never got feedback, will close this.
