### ISSUE TITLE
Clarify what names are given to stuff in 2sxc

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1778]
**I'm submitting a ...**
[x] not sure

**...about**
[x] other / unknown

**Current behavior**
Ok... Here goes another farfetched request to think about im the next major versions.

It's based on one heavy difficulty I felt when adapting to 2sxc.

Some things are named in a unique way when there are other more commonly used names for those things. Other things have the same name when they are not related.

"Entities" seems to be the name of everything. Tables, rows, items, variables, etc (and in theory that's correct, anything that exists is an entity). In a pratical level diferent things need diferent names.

If the data tab is a group of 2sxc app tables, why not call them app tables?

"Data" is also used everywhere, for Data mode, rows, etc. 

Content is used for content mode, or even an entity that is associated to a view to fetch a demo rows.

List are something else used for settings, queries, etc.

In half my support requests here, when I use the name used in the window I'm seeing, you will need clarification in where exactly am I seeing it, cause the name exists in multiple contexts.

Whould a deep naming clarification help turning 2sxc a more user (and n00b users) friendly experience?

**Comment by iJungleboy** [comment]
This is tricky. For example, we explicitly choose _data_ because it is data :) and in many use cases it's not meant to be regarded as a table of something (like when working with content, where the fact that it's in a table doesn't mean much). But we'll ponder this.

**Comment by eXistenZe** [comment]
Well. Everything is data and everything is content. That's why it's so confusing.
A table is more specific (but not perfect) and it's relatable to many other apps.
As for data vs content mode, it seems more like an app-data and module-data separation.

**Comment by iJungleboy** [comment]
I'll close this because of inactivity. 
If someone wants to pick it up and create a glossary in the docs, ping me.
