### ISSUE TITLE
GPS picker does not work on HTTPS sites

### ISSUE THREAD

**Issue by pascalmoser** [2sic/2sxc#178]
Remove http: here: https://github.com/2sic/2SexyContent/blob/035f1b2143054d2f9b82c286e2198bb7f38513df/SexyContent/EAV/Controls/ItemForm.js#L678

`$.getScript("//maps.googleapis.com/maps/api/js?sensor=false&callback=Eav.Gps._initMapApiCallback");`

**Comment by iJungleboy** [comment]
should be fixed on monday
