### ISSUE TITLE
[Feature request] Create and manage API controllers inside 2sxc

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1781]
**I'm submitting a ...**
[x] feature request

**...about** 
[x] admin experience UI
[x] APIs

This is probably on the works for quite a while now, but may as well bump the issue a bit.

**Current behavior**
You can only create controllers with FTP.

**Expected behavior**
A simple duplication of the views panel could work for controllers. Less settings, but important like access permissions, and different folder (api instead of root).
For now it would be enough. Latter more settings and features could be added.

**Comment by iJungleboy** [comment]
Done in 11 ;)
