### ISSUE TITLE
[Feature request] Fields with unique content

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1783]
**I'm submitting a ...** 
[x] feature request

**...about**
[x] Content Types or data management

**Current behavior**
There is no option to limit  a field content to be unique

When using a custom API, I can easily check for any field if the value already exists in that field. For example when we are creating auto IDs or even manual var names and other string fields that must be unique (when we create a row inside a table for a dropdown from query - there cannot be any duplicates).
But, when using the 2sxc forms (admin or public), I cannot implement such features.

**Expected behavior**
When using the 2sxc form, a new setting like "Force unique values" could be added. When creating or editing a row, 2sxc would then check for that value agains the list of values in that field, if it exists, do not allow saving.

This is related to the autoID request from a while back, since you could also prefill that int field with .Max() + 1.

**Comment by iJungleboy** [comment]
This is of course a useful idea, and there are many cases where we would like it too :). ATM we just can't invest resources yet - so requires contribution to get this in soon.

**Comment by iJungleboy** [comment]
Needs sponsoring, so added to #2107 and will close unless someone contributes or sponsors this.
