### ISSUE TITLE
HTML box should have focus when HTML dialog is displayed in new 10.x UI

### ISSUE THREAD

**Issue by michaelcunningham1974** [2sic/2sxc#1786]
**I'm submitting a ...**  
[x] feature request

**...about**   
[x] edit experience / UI

**Current behavior**

When user clicks an HTML box dialog box displays but doesn't have focus. User must click field again to begin typing.

**Expected behavior**

Cursor should focus on HTML box when field is edited and user should be able to begin typing immediately.

**Minimal reproduction of the problem with instructions**

Any 10.1 HTML dialog.

**What is the motivation / use case for changing the behavior?**

Speed editing process.

**Please tell us about your environment:**

IIS Server 2012

* **2sxc version(s):** 10.X.X  
* **Browser:** [all]
Web Browser | iOS XX Safari ]
* **DNN:** 9x
* **Language:** [any/all | English | German | other ]

Its a small thing but is annoying.

**Comment by Accuraty** [comment]
Yup, driving me crazy too. Sorry I didn't post about it sooner!

**Comment by iJungleboy** [comment]
good point! we'll check
