### ISSUE TITLE
Custom GPS Field is not working in version 10.0.0

### ISSUE THREAD

**Issue by ufoloko** [2sic/2sxc#1794]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] admin experience UI

**Current behavior**
If you add a Custom GPS Field, if you select a new location, lat and long values are not updated. If you set related fields to update values those values aren´t updated too.

Lastly, if you set some default value for map, for example { latitude: -2.901607, longitude: -79.0042817 }, default value is not working.

This is happening with new interface and with old (alt press + click) interface

**Expected behavior**
Custom GPS Should be working fine

**Minimal reproduction of the problem with instructions**
Just set a field with Custom GPS Field value, and then try to an item, GPS Field is not working

**Comment by iJungleboy** [comment]
just to verify, are you sure that it doesn't work in the old UI? because AFAIK we never changed anything there in a long time.

**Comment by iJungleboy** [comment]
Should be fixed in 10.3
