### ISSUE TITLE
Export content app fails with "{"Message":"Authorization has been denied for this request."}"

### ISSUE THREAD

**Issue by sleupold** [2sic/2sxc#1795]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] admin experience UI

**Current behavior**
I am trying to Export all Content templates, according to the documentation by selecting admin > app > Export App, including the content groups.

**Expected behavior**
zip is generated without errors

**Please tell us about your environment:**

* **2sxc version(s):** 9.43.1 LTS  
* **Browser:** [Chrome and Edge]
* **DNN:** [9.2.2 ] 
* **Language:** [German ]
* **Server:** Windows 2016 without Outbound Internet connection

**Anything you would like to add**
Seemed to work in 9.42

**Comment by david-poindexter** [comment]
Was there a pull request to resolve this?  I am not seeing it mentioned above.

**Comment by david-poindexter** [comment]
Nevermind - I just found the [release that addresses this](https://github.com/2sic/2sxc/releases/tag/v09.43.02-LTS).
