### ISSUE TITLE
Toast error message appearing while editing fields

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#1796]
**I'm submitting a ...** 
[x] bug report

**...about** 
[x] admin experience UI

**Current behavior**

I created a simple Content module for very basic content: Title (string), ShowTitle (boolean), Text (wysiwyg), and Anchor (string).

When editing the Boolean field or the Text/WYSIWYG field in the admin, I keep getting a toast "Error" message when trying to save my changes. The change I'm simply making is changing the label of Show Title and setting a default value, and making the Text field required. When I try to save the changes, the toast "Error" appears and it doesn't let me save. I then have to discard changes to get out of the modal and the changes are not saved.

**Expected behavior**

Changes to the field settings should save. I've done these same steps countless times with earlier versions of 2SXC and it works.

**Minimal reproduction of the problem with instructions**
1. Go to Admin
2. Data tab
3. Create a content type or edit an existing one. 
4. Click on the Fields button to edit the fields
4. Try editing a boolean field or a WYSIWYG field and the Error toast will appear and you won't be able to save changes.

<img width="1008" alt="Screen Shot 2019-08-16 at 11 58 13 AM" src="https://user-images.githubusercontent.com/8751936/63191362-293da080-c01d-11e9-9d3c-9356ae06abd1.png">

**What is the motivation / use case for changing the behavior?**
Module bug?

**Please tell us about your environment:**
Brand new DNN 9.3.2 on Azure. Fresh install of 2SXC 10.2.0. This is the first content type I've added to the website.

* **2sxc version(s):** 10.2.0 Pre-release
* **Browser:** [all probably?]
* **DNN:** [9.3.2] 
* **Language:** [any/all ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Thanks for this, @PagnoDunadan will check this.

**Comment by PagnoDunadan** [comment]
Frontend was trying to save items without fields and new backend blocked it assuming it was a mistake to send empty items. Should be fixed now :)

![2019-08-22 14_46_54-My Website _ testing edit ui](https://user-images.githubusercontent.com/7113033/63515851-0f540000-c4ec-11e9-9dd6-b9276a576d9e.png)

**Comment by iJungleboy** [comment]
fixed in 10.04
