### ISSUE TITLE
9.43.02 LTS has no Installer Zip?

### ISSUE THREAD

**Issue by Accuraty** [2sic/2sxc#1799]
[9.43,02 LTS](https://github.com/2sic/2sxc/releases/tag/v09.43.02-LTS)
https://github.com/2sic/2sxc/releases/tag/v09.43.02-LTS
 
[x] not sure
[x] other / unknown

**Current behavior**
Installer missing

**Expected behavior**
Installer

**Minimal reproduction of the problem with instructions**
Go to link above.

**What is the motivation / use case for changing the behavior?**
I want to install 9.43.02 LTS.

**Please tell us about your environment:**
* **2sxc version(s): 9.43.02 LTS
* **Browser: any
* **DNN: any
* **Language: any

**Comment by iJungleboy** [comment]
thx - must have missed it :)
