### ISSUE TITLE
"Edit List" dialog should not show presentation items

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#180]
1. It shows "no demo row" even if a demo entity is defined for the template
2. Presentation entites are shown in the list (only Content entites should be visible)

![image](https://cloud.githubusercontent.com/assets/5171884/6729017/cca1d61e-ce2e-11e4-9e16-534b0069a62f.png)

**Comment by iJungleboy** [comment]
Should be fixed in 2sxc 7.0 on Monday, May 4th.
