### ISSUE TITLE
Export is Missing Templates and Including Files/Folders

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#1801]
I'm submitting a 
[x] bug report 

about
[x] admin experience UI
[x] Content Types 

**Current behavior**
I go to the Admin, then Apps tab, and select Export from "Export or Import parts of this App." See the screenclip below, I am exporting a Content Type (Content in the 2sxc Content App) with the expectation of editing the XML file and using it as an Import to create a NEW Content-Type. I do this so I can re-use the existing Views (for Content with my new Content-Type by leaving the common field names the same).
 
So all I selected was [x] Content and 1 Template. Nothing else, no Entities or anything else is checked. When I created the export, right away I noticed there was a problem because the XML file size was almost 600 KB.
 
1) it did NOT include the checked Template.
 
2) it did include entries for hundreds of files and thousands of folders; examples:
`<File Id="649" RelativePath="adam\Content\ c_0gV85erU2azgGG8cRD5A\Text\JuriedArtShowApplication2019.pdf" />
`
`    <Folder Id="5520" RelativePath="adam/Content/254Tg_xOvEiiTGpa0Ocy_Q/PageSourceLink/" />
`
I assume I can safely delete the sections <PortalFiles> and <PortalFolders>?
 
I also see that the EntityGUIDs are in there for the various EAV Field Properties. Do I need to manually change those so they don't conflict? My intention is to import this in to the same DNN instance/portal, so this seems like a problem?

![image](https://user-images.githubusercontent.com/653301/63969920-919e7000-ca68-11e9-91b8-6551c93633ce.png)

**Expected behavior**
Exports should work or do something close to what they say and not include unwanted things like Files/Folders. Maybe these need to be in the UI to select for inclusion if wanted/needed? I expected the Template would get exported. 

**Minimal reproduction of the problem with instructions**
Included above.
 
**What is the motivation / use case for changing the behavior?**
I want a simple way to Clone an existing Content-Type either in the same project or to another DNN instance/portal.

**Please tell us about your environment:**

2sxc version(s): 10.00.02-Pre
Browser: Chrome latest
DNN: 9.03.02
Language: any/all

**SIDENOTE: I did also try going to Admin, Data tab and clicking Export for the Content content-type.** For Export Data I answered, "No, just export a blank data schema (for new data import)". This also seemed like what I wanted but here is the ENTIRE content of the XML file that generated. Seems useless, no? Where are all the field property settings? And why are there 2 identical copies of the same Entity?
```
<SexyContentData> 
  <Entity Type="Content"> 
    <Guid></Guid>
    <Language></Language>
    <Title></Title>
    <Text></Text>
    <Image></Image>
    <ImageCaption></ImageCaption>
  </Entity>
  <Entity Type="Content">
    <Guid></Guid>
    <Language></Language>
    <Title></Title>
    <Text></Text>
    <Image></Image>
    <ImageCaption></ImageCaption>
  </Entity>
</SexyContentData>
```

**Comment by iJungleboy** [comment]
@Accuraty sorry about this.

## Partial App Export
The partial app-export is a very old feature and hasn't had any love for a while now. Unfortunately, it won't be in our focus for another 2-3 months even though it's probably simple to fix, so we would need some community help here. 

## Data Export
exporting in admin-data: this is meant to export either the table of data (for Excel-mass-modifications or similar and re-import), or to create an empty xml making it easier to mass-import stuff. 

I did try a schema export like you did, and it worked (empty xml). It creates two items so people can open it in Excel and Excel regards it as a table. if we only added one item, then the schema-detection in excel wouldn't behave correctly.

## Content-Type Schema export/import
There is a new feature (ca. 1 year old) to export a schema as json. That is the future way we want to use - similar to the Query export/import. It's just that so far only the export is implemented. Import would be easy to add, but we haven't found time for it either, sorry. We'll try to speed this up, but it too will take a while as we're still very busy with other parts ATM.

**Comment by iJungleboy** [comment]
In 11.07 we'll implement

1. View export - configuration incl. file and thumbnail as json
1. View import - just drop the previously exported json unto the views
1. Content-type export (as json)
1. Content-type import (just drop the content-type json unto the data-list)

**Comment by iJungleboy** [comment]
1. export / import type works
1. export / import view works

Note: to clone a type, there is currently no UI yet, as we plan a more advanced feature to copy fields from one type to another. 

But if you need this, you can always export the type, edit the json manually and change the guid with a new guid using something like https://www.guidgenerator.com/ and then importing it.
