### ISSUE TITLE
Cannot Manage Features in 9.43.2 or 10.04

### ISSUE THREAD

**Issue by Accuraty** [2sic/2sxc#1806]
I'm submitting a bug report about admin experience UI and/or other or unknown.

**Current behavior**
I click on Manage Features and the list displays... until I move the mouse, then I suddenly get an error. This is happening on 3 DNN 9.03.02 sites, one with 2sxc 10.04 and the other two on 9.43.2.
 
Very specifically, I go to Apps Management, and switch to the Features tab (1)

![image](https://user-images.githubusercontent.com/653301/64791457-61150680-d53d-11e9-851d-7306705c3a7a.png)

Then I click on the Manage Features button (2) - and I do NOT move the mouse - the "no items found" changes to (3):

![image](https://user-images.githubusercontent.com/653301/64791666-a9ccbf80-d53d-11e9-954f-d7ca13814617.png)
 
The moment I move the mouse anywhere over the UI, it switches back to "no items found" (4) and displays the popup alert/error (5), "server reported that save feature failed"

![image](https://user-images.githubusercontent.com/653301/64792089-5eff7780-d53e-11e9-8f64-97a0254ec583.png)

**Expected behavior**
**What is the motivation / use case for changing the behavior?**
I should be able to manage features and click those checkboxes.

**Minimal reproduction of the problem with instructions**
Follow steps above?

**Please tell us about your environment:**
Windows 10, Chrome latest

### IMPORTANT: this does NOT happen in Firefox 69 (latest)!!

2sxc version(s): 9.43.2 and 10.04
Browser: Chrome 76 
DNN: 9.03.02
Language: any/all

**Comment by iJungleboy** [comment]
I just tried this with 2sxc 10.05 pre-release (but that doesn't have changes to this feature) and current chrome, and I can't reproduce it. 
I first tried with Version 76.0.3809.132 (Official Build) (64-bit)
now my chrome updated and I have Version 77.0.3865.75 (Official Build) (64-bit)

could you try again?

**Comment by Accuraty** [comment]
Okay to close, I have tested this on other similar machines and it is not happening. Cannot isolate it, but I assume there is a plugin or some other Chrome extension causing this. I can't reproduce it on any other machine except my workstation. Sorry for the distraction!

**Comment by iJungleboy** [comment]
ok thx!
