### ISSUE TITLE
Content Html Editor with iframe code gets lost

### ISSUE THREAD

**Issue by madceb** [2sic/2sxc#1810]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI

**Current behavior**

Edit Content with Html, edit content and in html editor adds an iframe (html editor works) then return to main window and the html content is blank and not saved.

**Expected behavior**

Returning to main content window it should preview the html edited content as usual. in 9.x it works.

**Minimal reproduction of the problem with instructions**

1. Edit a content element, 
2. click html text 
3. Add content in html editor and a iframe code
4. click return, preview is blank

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **2sxc version(s):** 10.3,  10.4, 10.5
* **Browser:** Chrome 77
* **DNN:** 9.3.1 
* **Language:** Tested in English

**Anything you would like to add**

**Comment by iJungleboy** [comment]
We just switched to tinymce 5, so my guess is this is a security feature. We'll look into it - to work around it, just quickly build an iframe app.

**Comment by madceb** [comment]
Thank you, Also another workaround, I switched to edit as textbox the text/html field temporarily to edit the html.
Regards!

**Comment by iJungleboy** [comment]
@PagnoDunadan could you check this - probably we need to whitelist iframe in tinymce as an allowed DOM element

**Comment by PagnoDunadan** [comment]
Fixed in next version. Problem was with the way data was read from tinymce.
