### ISSUE TITLE
ClientDependency <link> stylesheet detection does not work with HTML5 link tags

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#1811]
**I'm submitting a ...**  
[x] bug report

**...about**   
[x] Razor templating

**Current behavior**
In HTML5, a correct <link> tag might look like this: `<link href="main.css" rel="stylesheet">`. 2sxc does not detect link tags without a trailing slash (`/>`) so the link is not added through ClientDependency.

**Expected behavior**
HTML5 link (stylesheet) tags should be correctly picked up by 2sxc.

**Minimal reproduction of the problem with instructions**
Create an app with a file named `test.css` and create a CSHTML or Token template, then add a reference to the css file:
```<link data-enableoptimizations="true" href="@App.Path/test.css" rel="stylesheet">```
Check the source code in Chrome - the stylesheet is not added with ClientDependency.

**Comment by iJungleboy** [comment]
@raphael-m thx - can you fix this yourself?

**Comment by iJungleboy** [comment]
too risky to fix quickly, and too much work if we solve it nicely, so will close as no priority.
