### ISSUE TITLE
TinyMCE toolbar could show h4,h5,h6 and unordered lists by default

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#1817]
**I'm submitting a ...**  
[x] design suggestion

**...about**   
[x] edit experience / UI

**Current behavior**

When you're editing content using the TinyMCE, the toolbar has h1, h2, h3 and then a dropdown for h4, h5, h6, and paragraph. There's also the ordered list and then a dropdown with the unordered list and the indent buttons. Seems like there's plenty of space to show all of the heading #s and both the ordered and unordered lists.

![Screen Shot 2019-09-19 at 8 02 22 AM](https://user-images.githubusercontent.com/8751936/65256608-a5138880-dab4-11e9-9d6d-75126695ba1b.png)

**Expected behavior**
Show all the headings, paragraph, and unordered list button in the default toolbar.

**Minimal reproduction of the problem with instructions**
Try editing content using the TinyMCE editor. Go to make a heading 4 or heading 5. And make an unordered list. You have to click the dropdown which is extra clicks.

**What is the motivation / use case for changing the behavior?**
There seems to be extra steps when there probably doesn't need to be. In most cases, ideally, I don't want my users to need the advanced toolbar setting so by giving them most of what they need right in front of them it simplifies their editing experience.

**Please tell us about your environment:**
DNN 9.3.2 on Azure. Fresh install.

* **2sxc version(s):** 10.4.0  
* **Browser:** [all ]
* **DNN:** [all | DNN 9.3.2] 
* **Language:** [any/all]

**Comment by iJungleboy** [comment]
I think the un-ordered List shouldn't be a problem, especially since our new editor now has a good fallback for mobile use, where there is less space. 
Regarding the headings i'm not so sure. The reason is that many people shouldn't actually use H4 - H6, for various reasons and this does encourage best-practice for inexperienced editors.

**Comment by ajplopez** [comment]
Good point but I would say that giving them control over h1 is probably not a good practice either as the h1 is usually elsewhere on the page. Heading 2, Heading 3, Heading 4 are maybe the most common my users would use. And it's good to give them the Paragraph one in case they want to convert a heading back to normal.

That said, these are relatively minor so I don't have my heart set on it. But yeah, the unordered list one would be good.

**Comment by iJungleboy** [comment]
I agree about the H1, but I'm sure that some people will not like that. So probably the perfect thing to do is:

1. By default, 
    1. have P, H2, H3, H4 (so P first)
    1. and a dropdown showing P, H1-H6, BlockQuote (order P first for consistency, so nobody is confused)
    1. Show numbered list, bulleted list, indent, outdent
1. Provide option to override and provide H1 in the main bar after all

**Comment by ajplopez** [comment]
Oh yes, I should clarify: I think users should still be able to make heading 1, but I was just saying it's not that common so it shouldn't be the main thing.

I totally agree with that above approach you suggested. I think that would be ideal.

**Comment by iJungleboy** [comment]
In 10.22 we'll release H2-H4 as the default, and provide H1-6 in the dropdown :)
