### ISSUE TITLE
Improve module controls for Admins and Content Editors

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#1822]
**I'm submitting a ...**  
[x] design suggestion

**...about**   
[x] admin experience UI

**Current behavior**
As a Content Editor (a non-SuperUser role), my editors can see "Change Template / Layout" and "Edit Template" in the module controls. 

![Screen Shot 2019-09-19 at 1 22 32 PM](https://user-images.githubusercontent.com/8751936/65278768-a313ee80-dae1-11e9-9e9c-c56298fdf870.png)

**Change Template / Layout**
For me and my users, the content editors would never change the template / layout on modules that are setup. I think taking it out of this module control and leaving it to the template actions would be better so I can control if I want them to be able to do that or not. It would still show for SuperUsers or Admins, of course.

**Edit Template**
As just a Content Editor, they would never modify the templates. If they try, they get a permissions error anyway. So "Edit Template" shouldn't be there for users who can't.

**MISSING: Edit List**
There used to be "Edit List" which I found really handy because I don't always show the List Header in all my templates. Typically I show the "instance-list" icon in listings so they can always modify the list, but it can be a little confusing to my content editors. A centralized "Edit List" button in the module control would be really useful, I think.

**Expected behavior**
Add "Edit List" back into the module control dropdown for lists. And remove the controls that don't pertain to Content Editors - change template / layout and edit template.

**Minimal reproduction of the problem with instructions**
Add a simple 2SXC Content module to the page. Make it a simple list. Go into Edit mode in DNN. Hover over the pencil icon on the module. View the dropdown controls.

**What is the motivation / use case for changing the behavior?**
Improve the UX for the Content Editors and non-SuperUser accounts

**Please tell us about your environment:**
Any

* **2sxc version(s):** 10.4.0 
* **Browser:** [all ]
* **DNN:** [all | 9.3.2 ] 

**Anything you would like to add**

**Comment by iJungleboy** [comment]
most of what you want can already be done :). 
Check out this recipe: https://azing.org/2sxc/r/t104-orQ

**Comment by ajplopez** [comment]
Ahh, good to know! Thanks Daniel.

**Comment by ajplopez** [comment]
I tried it out and it looks good so far. But what about the "Edit List" functionality. Is that something that might make it back into the module?

**Comment by iJungleboy** [comment]
@ajplopez just for my understanding: that is in the normal rotating toolbar. For us, the menu-toolbar is only a fallback in emergecies where for whatever reason the template can't be rendered. We also never train our users to go into edit-mode, because it's slow and the preview is off. 

Why would you want the list-button there?

**Comment by ajplopez** [comment]
@iJungleboy The more I think about it, the more I realize it's not terribly important.

To answer your question - some of my content editors are Admins and they can see and use those module controls. For them, hovering over the pencil icon to manage content is something they're used to. And this is just my personal feeling, but I never really liked having the instance-list icon inside each content item in a list because it feels repetitive and not immediately intuitive. I always have to train content editors that if they want to reorder their items they can click on any of the "1,2,3" icons which, while not super difficult to remember, it's not really obvious. And because the icon exists in each content item, it looks like an icon that will only modify that specific item (at first).

The other thing is that I don't always show the ListHeader content in my templates - I use ShowTitle toggles to determine if the ListHeader fields are shown or not. So if the user turns it off, they can no longer find the edit controls for the ListHeader.

Overall, I don't have super strong feelings about it and I think it works fine as is. Just something I've always noticed. :)

**Comment by iJungleboy** [comment]
ok, thanks. In that case we probably won't address it.
