### ISSUE TITLE
BUG: Editing Library Metadata Content Types

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#1824]
**I'm submitting a ...**
[x] bug report

**...about**
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
When editing a library item's meta tags when using metadata content types, the edit window fails to appear after editing and saving the first item. Any and all subsequent attempts to edit any other item's metadata fails to open the window, but the items do become grayed out. This only occurs when you go to add new metadata, you can still edit multiple the metadata of multiple items if they already have data.

**Expected behavior**
The edit metadata window should appear each time the tag is clicked.

**Minimal reproduction of the problem with instructions**
Create a content item with a library of files. Create another content item for the metadata. Close to refresh the page, otherwise the Metadata Content Type field won't appear. Link the first content item's library field for metadata content types with the name of the second content type. Upload a couple of files into the library. Close and save. Then re-open the data item and try and click on each different file's blue tag to access the metadata and notice the edit window doesn't appear after editing the first one.

**What is the motivation / use case for changing the behavior?**
None.

**Please tell us about your environment:**
Windows 10

* **2sxc version(s):** 10.5.0
* **Browser:** Chrome 77.0.3865.90, Firefox 69.0.1
* **DNN:** 9.4.0
* **Language:** English

**Comment by iJungleboy** [comment]
thanks, we'll look at this _after_ the next release.

**Comment by PagnoDunadan** [comment]
Fixed in next version.
