### ISSUE TITLE
Replace and Copy Doesn't Refresh Entity List

### ISSUE THREAD

**Issue by michaelcunningham1974** [2sic/2sxc#1837]
**I'm submitting a ...**  
[x] bug report 

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
If user clicks the replace icon on an entity and try to duplicate an existing entity the new entity is created but not available to select from the dialog. The user must exit out click the replace button again and choose item from the list. This  is an APP.

No js errors generated.

**Expected behavior**
Once user copies template and edits the new template should be selected.

**Minimal reproduction of the problem with instructions**

See Screencast at:
http://www.mdrealtor.org/Portals/0/video/2sxc_replace_isssue.mp4

**What is the motivation / use case for changing the behavior?**
Proper functionality

**Please tell us about your environment:**
Windows Sever 2012, 

* **2sxc version(s):**Latest
* **Browser:** [Chrome]
* **DNN:**  9.X.X ] 
* **Language:** English

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Thanks - this is annoying. We're currently reviewing to update all dialogs to the new angular, and we would probably do this at the same time. I'll keep you posted.

**Comment by iJungleboy** [comment]
Done in 11
