### ISSUE TITLE
2sxc 10.6 Cannot set the wysiwyg editor type on a data type = string

### ISSUE THREAD

**Issue by andyduo** [2sic/2sxc#1838]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**

Cannot set the wysiwyg editor on a data type = string. Changing it on the Content Type Fields screen does not change the editor that is displayed to the user.
**Expected behavior**

Wysiwyg edit should show the editor that is set by admin
**Minimal reproduction of the problem with instructions**

Create a content type with a field for text.
Edit the input type to be a different editor and click save.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **2sxc version(s):** 2sxc 10.6.0

* **DNN:** [all | 7.4.2 | 8.X.X | 9.X.X ] 
9.03.01

* **Language:** [any/all | English | German | other ]

**Anything you would like to add**
Thanks

**Comment by iJungleboy** [comment]
Could you add screenshots - as this is confusing and I can't see why this would happen.

**Comment by andyduo** [comment]
![editor1](https://user-images.githubusercontent.com/358112/66789530-820bb580-ef48-11e9-98ae-c66e541b259a.JPG)
![editor-setting](https://user-images.githubusercontent.com/358112/66789531-820bb580-ef48-11e9-9a9a-ecf13bc7b326.JPG)

I get the same editor interface regardless of what the setting is for the content item. Behavior is repeatable on two sites so far.

It seems to be just for the editors as selecting Drop down seems to work fine.

**Comment by iJungleboy** [comment]
the wysiwyg-full was an idea that was added years ago, but actually never implemented. We decided to not remove it, because it could break existing configurations, but it always was the same thing as the default wysiwyg. This may change once but has absolutely no priority, so I'll close this issue.

**Comment by andyduo** [comment]
wysiwyg-full was just what I chose for the example here. The issues is the same if I select wysiwyg-dnn.

This is with wysiwyg-dnn set as the input type:
![editor2](https://user-images.githubusercontent.com/358112/66873709-9792e500-f005-11e9-8a4f-1a254a3e7edb.JPG)

**Comment by iJungleboy** [comment]
wysiwyg-dnn used to show the DNN wysiwyg (like with the old html editor). At the moment we didn't implement this and we're not sure if we will. 
I created a new issue to hide these #1845
