### ISSUE TITLE
BUG: Unable to edit a field whenn using microsoft Edge (2sic_2SexyContent_10.06.00)

### ISSUE THREAD

**Issue by Rodien** [2sic/2sxc#1839]
**I'm submitting a ...** 
[x] bug report => 

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
I can enter edit modus but when I click on a field to edit it does not work. 
This only occurs when using Microsoft Edge. 

**Expected behavior**
To be enabled to edit a field when in edit modus using Micro
![2sxcEdit](https://user-images.githubusercontent.com/50739829/66473532-bb977900-ea8f-11e9-8749-b217ae4e7218.png)
soft Edge. 

**Minimal reproduction of the problem with instructions**

Upgrade from 2sxc from 9.32.1 to 2sic_2SexyContent_10.06.00
Open 2sxc app and click on a field to make changes.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

2sxc version(s): 10.6.0
Browser: Microsoft Edge 44.18362.387.0
DNN: 9.3.2
Language: Dutch

**Comment by iJungleboy** [comment]
We are not testing the UI on Edge, as it's a dead browser and we don't want to invest the resources into supporting it. Please use Chrome or FireFox, or turn on the feature to use the old UI if you can't use a modern browser. Here's a recipe to prefer the old UI: https://azing.org/2sxc/r/VEAhAmEY

**Comment by iJungleboy** [comment]
I'll just pre-release a 10.08 for this - could you check/verify that it works and doesn't break anything?
