### ISSUE TITLE
Can't Change App Template in Dropdown

### ISSUE THREAD

**Issue by grayspace** [2sic/2sxc#185]
I have an app that won't let me change the template in the UI dropdown. The templates are token based, and the only difference between the two is one css class on a div. Both are shown in the dropdown list.

Was able to get errors/warnings from Firefox console...

* no element found SaveTemplateId:1:1
* Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead Telerik.Web.UI.WebResource.axd:1133:0
* Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.js:3346:0

The issue occurs for me in Chrome, Firefox & IE, and using 2sxc versions 6.6.5 & 6.6.4. DNN version is 7.03.04.

I can add a new app to page, and use desired template from the start, but cannot change it. I also tried creating a new template, but cannot set the app to use it either.

**Comment by iJungleboy** [comment]
This seems to be a bug in 2sxc 6.6.4+, we've had it reported a lot. Should be fixed in 7.0 on Monday.
