### ISSUE TITLE
also show 2sxc version in edit-ui when in debug mode

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#1858]
here:
![image](https://user-images.githubusercontent.com/5321186/67484602-b712b900-f668-11e9-81f7-eb0b85fe7210.png)

**Comment by PagnoDunadan** [comment]
Done in https://github.com/2sic/eav-item-dialog-angular/commit/ad3e99d7da0565dac040ec2567f7a680fc44d553
