### ISSUE TITLE
Content-Type Selection behaves wrong when app-settings are opened through the generic apps-management.

### ISSUE THREAD

**Issue by JoeAiken** [2sic/2sxc#1861]
**I'm submitting a ...** 
[x] bug report 

**...about** 
[x] Content Types or data management

**Current behavior**
When importing either an entire or partial App and going into the imported View the Content Type fields (under Content Specs, Presentation Options, and List Settings) are auto-populated with the imported Content Type GUID value, not its name. Clicking the Content Type drop down fields the drop down lists are empty. 

**Expected behavior**
When importing either an entire or partial App expecting to see the Content Types from the imported App available in the Views Content Type drop down fields (under Content Specs, Presentation Options, and List Settings). 

**Minimal reproduction of the problem with instructions**
Import entire App (have same result with partial app too) > click the View tab > click on the imported View > scroll to the **Content Specs** section and notice the Content Type field is auto-populated with the imported Content Type GUID value and not its name (the same is true for the Content Type fields under Presentation Options and List Settings) > click on the Content Type field and notice the lists are empty and do not include any of the imported Content Types > Can also try manually filling in the Content Type field with the proper content type name and save, but field is still empty. 

**What is the motivation / use case for changing the behavior?**
To import entire or partial Apps

**Please tell us about your environment:**

* **2sxc version(s):** 10.09.01
* **Browser:** all
* **DNN:** 9.4.1  
* **Language:** English

**Anything you would like to add**
I noticed the Demo Item fields are populating correctly with the imported Demo items. If you click on any of the Demo Item fields you will see the different demo item options which came from the App import.

**Comment by JoeAiken** [comment]
NVM, I found I had to first place the imported App into a pane in order for the Content Type options to appear in the View/template. No bug to report

**Comment by JoeAiken** [comment]
@iJungleboy Thanks for the reply! I started with only 'Content' in my Apps list. In order to get to the Apps Management window I must first place 'Content' in a pane. Once I access the Apps Management window through 'Content',  I click import app, click on the imported apps name to access its View settings and experience the issue of the GUID showing:

![2sxc](https://user-images.githubusercontent.com/31485614/67587281-85a9f400-f721-11e9-9b10-f7c64709ee3d.PNG)


If I exit out of the Apps Management window and switch 'Content' to the newly imported app I am then able to click Apps Management, go to the View settings and the Content Type field is correctly populating with the imported Apps content type names. It seems if you access Apps Management window through one 2sxc App and import a new app, you cannot update the View settings of the newly imported app unless you access the Apps Management window through that particular app.  I can probably put together a short video of the issue if I am still not explaining it well enough. Thanks again for the help!

**Comment by iJungleboy** [comment]
Gotcha. I believe this may be a bug, but more related to how the app-configuration was opened than related to the dialog itself. I'll rename the issue. 

Note that we're recreating these dialogs in angular 8 right now, so a fix will have to wait till that is done - which could take 2-3 month.

**Comment by iJungleboy** [comment]
is fixed in upcoming 2sxc 11 release with the new ui
