### ISSUE TITLE
Linking to Permission Locked Resources

### ISSUE THREAD

**Issue by 10PoundChris** [2sic/2sxc#1862]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] DNN parts

**Current behavior**

When you link to a file in a directory that is locked to specific user roles, 2sxc is not validating if the file is not within a protected directory and not generating the correct link to a file.

**Expected behavior**

When you are using a Hyperlink data type, 2sxc should validate if the file is located within the site, and if it is housed within a protected directory. If both are true, it should run the LinkClick function to generate the correct link path.

This is critical because with protected directories enabled, the link 2sxc currently generates results in a "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." page because all resources uploaded in protected directories have their extension updated to .resource. 

**Minimal reproduction of the problem with instructions**

https://www.dropbox.com/s/us62vw26i79ynh7/2sxc-protected-directories.mov?dl=0

**What is the motivation / use case for changing the behavior?**

Ensuring that 2sxc is generating the correct link for users when linking to files that are housed within protected directories is critical to ensure links are not pointing to invalid/broken pages.

**Please tell us about your environment:**

* **2sxc version(s):** 10.X.X  
2sxc 9.43.1

* **Browser:** [all ]
* **DNN:** [all] 
* **Language:** [all]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
We'll look at this asap.

**Comment by iJungleboy** [comment]
@tvatavuk could you look into this? Basically the goal is that files in a protected directory - both normal files in portals, as well as if a folder in adam were protected - generate links through the standard DNN Linkclick.

**Comment by tvatavuk** [comment]
@iJungleboy can we talk about solution for fixing this issue?

**Comment by iJungleboy** [comment]
I think we have a solution for 10.10. Note that we changed quite a bit of the internals, nothing should break, but we'll have to make a pre-release.
