### ISSUE TITLE
Adam instead of Page Picker

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#1864]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI

**Current behavior**

1. Add a Field of type link
2. Edit field to be a page picker:   
![image](https://user-images.githubusercontent.com/5693190/67633431-131b4e80-f8b0-11e9-8c4b-a359f3226fe0.png)

Result in Editor:   
![image](https://user-images.githubusercontent.com/5693190/67633439-3e05a280-f8b0-11e9-8dac-1835db53c263.png)

**Expected behavior**

- A page picker should be shown

**Please tell us about your environment:**

* **2sxc version(s):** 10.9.1
* **DNN:* *9.4.1

**Comment by iJungleboy** [comment]
Thanks for this - we'll look into it asap.

**Comment by PagnoDunadan** [comment]
Fixed in next update:
![image](https://user-images.githubusercontent.com/7113033/67751503-83051280-fa31-11e9-8e6e-a89068818de5.png)

**Comment by SCullman** [comment]
Thank you
