### ISSUE TITLE
Entity picker only for new items

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#1866]
**I'm submitting a ...** 

[x] feature request

**...about**   
[x] edit experience / UI

**Current behavior**

![image](https://user-images.githubusercontent.com/5693190/67684331-41258f00-f993-11e9-90bc-22e577485672.png)

I want to have this interface without the ability to `add existing items`.

**Expected behavior**
If I enable Create New Items, and disable Add Existing items   
![image](https://user-images.githubusercontent.com/5693190/67684530-a7121680-f993-11e9-9668-86bdbac4d402.png)
   
the Add button should be visible. But it is not:

![image](https://user-images.githubusercontent.com/5693190/67684677-eb051b80-f993-11e9-8eac-079e2781c56e.png)

**What is the motivation / use case for changing the behavior?**
I only want to add new statements to an entity.

**Please tell us about your environment:**
* **2sxc version(s):** 10.9.1

**Comment by iJungleboy** [comment]
Looks like an oversight on our side, thx.

**Comment by PagnoDunadan** [comment]
Fixed in next update.
