### ISSUE TITLE
Module title can not be more than 1 word

### ISSUE THREAD

**Issue by Tychodewaard** [2sic/2sxc#1867]
[x] bug report => search github for a similar issue before submitting 

[x] DNN parts

**Current behavior**
If you put some text in the module settings (DNN) and apply a simple H2 container, It does not show the module title if it is more than one word. 
So, it is not the same as #1446 , I guess ?

**Expected behavior**
To show the title of the module settings. 

**Minimal reproduction of the problem with instructions**
Use the link app in the content apps.
Create a module title called "I am too sxy"
Create the link title "for this shirt"
Apply a container with title
It shows Link title.
Now, change the module title to Iamtoosxy and it will show Iamtoosxy

**Please tell us about your environment:**
DNN 9.3.2.
2sxy 10.8

**Comment by iJungleboy** [comment]
2sxc rarely uses the real module title - but can of course. We usually don't use containers with titles, but get the title to visualize in the razor template. 

Here's how it _should_ work: When an editor changes content, the title is automatically copied to the module - so any container that actually tries to show it will show it. So if you write an own module title and edit content, it would replace the title in the module automatically. Basically the title would normally not be edited at the module level, but only at the content-level, and in most cases you would show it with the template, not with the container. 

Now I'm not sure what you ran into. Could you check what I wrote and see if this still is an issue, and maybe add some screenshots?

**Comment by Tychodewaard** [comment]
You can verify on https://www.tjeps.com/admin/tools 
I use the default content app - link list

**Comment by iJungleboy** [comment]
I tried to reproduce it, but can't.

1. I have a content module with some title - with many words in it
1. the settings have the same title
1. changed the title with many words
1. the module has the new title, with many words

Am I missing something?

**Comment by iJungleboy** [comment]
Haven't heard anything - will close. If still an issue, I'll re-open.
