### ISSUE TITLE
Font-Icon picker does not display list of icons

### ISSUE THREAD

**Issue by JoeAiken** [2sic/2sxc#1869]
**I'm submitting a ...** 
[x] bug report
 
**...about**
[x] edit experience / UI

**Current behavior**
When creating a new App or importing one the Font-Icon picker input type does not seem to be working properly. After double checking the File path was correctly pointing to a font-awesome css file containing the icons I was still not able to get the Font-Icon picker input to display a list of font-awesome icons I could search through.

**Expected behavior**
Clicking the Font-Icon picker displays a list of icons which is searchable. 

**Minimal reproduction of the problem with instructions**
Create a new App or import one with a field that uses the Font-Icon picker input type. Set the File path to point to a css file containing your icons. Try going to the App using the Font-Icon picker and edit that field and nothing will happen. The field functions as a basic text input. 

**What is the motivation / use case for changing the behavior?**
Allowing users to easily search and use custom icons.

**Please tell us about your environment:**

* **2sxc version(s):** 10.09.01
* **Browser:** Chrome | Firefox
* **DNN:** 9.4.1
* **Language:** English

**Comment by iJungleboy** [comment]
@PagnoDunadan I can partiall reproduce this. Please check. 

## Reproduce

1. Create a new sub-portal, install default content-templates
1. add a link-item to the page
1. enter edit mode - far below there is an icon-picker  
![image](https://user-images.githubusercontent.com/5321186/67779741-5bc83880-fa65-11e9-8973-60c1b4773ea4.png)
1. as far as I can see, the preview during search is often off...
1. ...and once I pick an icon, the preview in the icon-line doesn't work

**Comment by Accuraty** [comment]
This has been a problem for a while, I didn't report it because we have FontAwesome Pro in all our current project atm. Any chance you can also test this through so that it still works whether Free or Pro is the only thing on the page as well as both? I realize both shouldn't happen, but it does sometimes when folks (web-builders) aren't paying attention. Thanks!

**Comment by Accuraty** [comment]
So you are saying that if we want to use FontAwesome Pro we'd need to build a custom picker that knows about FontAwesome Pro?

**Comment by iJungleboy** [comment]
@Accuraty nope. You would have to configure the icon-picker to use the CSS file which lists all the pro icons. Otherwise it doesn't offer the pro icons in the picker for the editor. That's a field-configuration on the icon-picker (you could use any icon font BTW, not just font-awesome).
