### ISSUE TITLE
Search and Display 2sxc data (Using Dnn Sharp search Booster)

### ISSUE THREAD

**Issue by Rodien** [2sic/2sxc#1871]
**I'm submitting a ...** 
[x] not sure

**...about**   
[x] Content Types or data management
[x] other / unknown

**Current behavior**

I have a 2sxc app that inserts and display products. And now I wish to search and display the products with their photos. 

I want to use DnnSharp Search Boost for this. 

So I asked them if it's possible to search and display 2sxc data with Search boost. 

And this was their response: 
"
How is the content from 2sxc indexed?

If you're using database rules then this can be done simply with a custom Description Template where you can add the image with a href attribute and use the [Field:<ColumnName>]  token by referencing the column from where the image path is being retrieved:
https://www.screencast.com/t/WvFRhrvQckeu

Otherwise it might require a Custom Search Results template, but that needs to be tested first.

Best Regards

"

**Expected behavior**

To be able to search and display 2sxc data with Dnn sharp search boost or Dnn search engine. 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

2sxc version(s): 9.43.0
Browser: Google Chrome Version 78.0.3904.70
DNN: 9.3.2
Language: Dutch

**Anything you would like to add**
Where can I find an article about 2sxc database schema? 

Is there maybe another way to search and display data?

**Comment by iJungleboy** [comment]
Hi @Rodien 

## Using DNN Search Index

First of all, 2sxc does deliver the data to the dnn search engine. There's a default behavior and additionally you can customize everything - https://github.com/2sic/2sxc/wiki/Razor-SexyContentWebPage.CustomizeSearch

So if your Dnn Sharp Search Boost uses dnn search data, you're good to go. 

Alternatively you can probably do one of the following...

## Custom Connector

I don't know DNN Sharp Search Boost, but there is probably a plugin system. With that you could create a DLL or something that has the data-provider or something. Some helpers will get you the whole app (if you know the ID) and return it to you. You can then deliver the data to Dnn Sharp as you need to.

## SQL - hard, but possible

2sxc uses an EAV data model, where each value is in another row in SQL. You would need to build a SQL to combine it specifically for the fields you need, to then query it using SQL. This would need some SQL skills to do.
