### ISSUE TITLE
App Resources editing - doubleclick switch translate mode

### ISSUE THREAD

**Issue by ropalko** [2sic/2sxc#1881]
**I'm submitting a ...** 
[x] bug report

**...about**
[x] edit experience / UI

**Current behavior**
When you have multilanguage App Resources and you doubleclick an entry, its switch between "translate/don't translate" every time.

**Expected behavior**
When the entry is not translated yet, the doubleclick should switch to "translate". Doubleclicking again its shouldn't switch back to "don't translate".

**Minimal reproduction of the problem with instructions**
* Open App Resources
* Switch to not default language
* Choose not translated entry
* Doubleclick it (switched to translate)
* Dobuleclick it again (switched to dont translate)

**What is the motivation / use case for changing the behavior?**
Proper functionality

**Please tell us about your environment:**
* **2sxc version(s):**Latest
* **Browser:** [all]
* **DNN:**  9.X.X ] 
* **Language:** all

**Comment by iJungleboy** [comment]
we'll look into this :)

**Comment by PagnoDunadan** [comment]
https://github.com/2sic/eav-item-dialog-angular/issues/149

Fixed :)
