### ISSUE TITLE
Preview of RTF Content hidden 

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#1882]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 
**...about**   
[x] edit experience / UI

**Current behavior**
![image](https://user-images.githubusercontent.com/5693190/68392410-09280400-016a-11ea-9acc-de83b3556257.png)

RTF Content is not shown.

**Expected behavior**
The content is shown directly:
![image](https://user-images.githubusercontent.com/5693190/68392652-7f2c6b00-016a-11ea-9858-df2699c7a72c.png)

**Minimal reproduction of the problem with instructions**

It doesn't happen every time with every RTF content. 

First sighting was with the help texts:
![image](https://user-images.githubusercontent.com/5693190/68392900-198cae80-016b-11ea-9590-ed161e2ac0e7.png)

* **2sxc version(s):** 10.9.1

**Comment by SCullman** [comment]
Sometimes the RTF Content appears while editing any other field.

**Comment by iJungleboy** [comment]
Thanks - I think we just fixed it in 10.20. 
Note that it's basically the same as 10.09.01 but we made a big version jump because we're renaming internal APIs and want people to be careful with the upgrades. But we tested it on all our apps and our work and believe it's non-breaking.
