### ISSUE TITLE
Forum mising absolutely necessary

### ISSUE THREAD

**Issue by Scippy** [2sic/2sxc#1895]
I think this is a great project but it is absolutely necessary to have a forum to dedicate to it.
It is not possible to use stackoverflow to discuss everything, it is not the right place, as indeed here.
The information is messy and replicated and much more is missing also in basic information and the community could help in this if there was a dedicated forum.
For example, I used the new GPS Picker custom field in a test project to learn the product. I could find a generic link that describes it here: https://2sxc.org/en/Docs/GPS-Picker (I was able to find it by Google and not with 2SCX site navigation) but nowhere could I find how to access only the latitude or longitude in separate way using the @content in the view and I'm no able to go on. Little help could help me a lot!

**Comment by iJungleboy** [comment]
Hi @Scippy 

StackOverflow was a strategic decision, to ensure that we can reach a broad audience and don't have to invest into a forum - both creating and maintaining it. It has a huge community - more than we could ever build up, and many questions actually end up being C# or Razor questions, for which we don't want to create a new Q&A system. 

So far it has served us well and most questions get answered very quickly. If you post your question there, I'm sure you'll get the answer very quickly.

Please understand that writing (and maintaining) docs, in addition to guides, best-practices, recipes etc. is super intensive - it takes just about the same resources and writing the code. Just now we're finishing a new [api section](https://api.2sxc.org) which will also help a lot. 

Many thanks, 
Daniel

**Comment by Scippy** [comment]
Thank Daniel, how you’ve suggested I’ve posted my question on StackOverflow two week ago but at today any response!
