### ISSUE TITLE
Azure Web App Server Error Using 2SXC v10+ with Application Insights Enabled

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#1904]
**I'm submitting a ...** 
[x] bug report

**...about**
[x] DNN parts

**Current behavior**
Running 2SXC higher than v10.00.00 on a web app hosted at Azure with Application Insights enabled returns an ASP.NET Server Error:

```
Server Error in '/' Application.
Could not load type 'System.Diagnostics.Activity' from assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.TypeLoadException: Could not load type 'System.Diagnostics.Activity' from assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[TypeLoadException: Could not load type 'System.Diagnostics.Activity' from assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.]
   Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule.Application_BeginRequest(Object sender, EventArgs e) +0
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.<>c__DisplayClass285_0.<ExecuteStepImpl>b__0() +26
   System.Web.StepInvoker.Invoke(Action executionStep) +101
   System.Web.<>c__DisplayClass4_0.<Invoke>b__0() +22
   Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule.OnExecuteRequestStep(HttpContextBase context, Action step) +64
   System.Web.<>c__DisplayClass284_0.<OnExecuteRequestStep>b__0(Action nextStepAction) +54
   System.Web.StepInvoker.Invoke(Action executionStep) +85
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +9979713
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +71


Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3429.0
```

**Expected behavior**
No error should be present after upgrading 2SXC to v10 or above.

**Minimal reproduction of the problem with instructions**
Setup a new Azure Web App and SQL database, noting that Application Insights is enabled. Install the latest version of DNN (e.g. v09.04.02) and then install a 2SXC version above v10.00.00.

**What is the motivation / use case for changing the behavior?**
Application Insights is enabled by default on Azure Web Apps.

**Please tell us about your environment:**
Azure Web App

* **2sxc version(s):** Any 2SXC version above v10.00.00
* **Browser:** all
* **DNN:** v9.4.2 
* **Language:** any/all

**Anything you would like to add**
I came across a related article at [https://techcommunity.microsoft.com/t5/Azure-Monitor-Status/Issues-with-Net-Core-web-applications-in-App-Services-monitored/ba-p/1003392](https://techcommunity.microsoft.com/t5/Azure-Monitor-Status/Issues-with-Net-Core-web-applications-in-App-Services-monitored/ba-p/1003392), which led me to verify that it is caused by Application Insights.

**Comment by iJungleboy** [comment]
This is interesting. Can you confirm that if you disable application insights, then the error goes away?

I believe this would be easy to fix but would take a few hours, basically these DLLs would have to be placed in a subfolder - just like some other DLLs we use from .net core, and then we need to add redirects in the web.config.

**Comment by tpperlman** [comment]
Thank you, I can confirm:

**Application Insights Disabled:**

![insights off](https://user-images.githubusercontent.com/1871915/69434496-c3dc0880-0d0b-11ea-8238-42b83742dddd.jpg)

**Application Insights Enabled:**

![insights on](https://user-images.githubusercontent.com/1871915/69434519-d0f8f780-0d0b-11ea-8e6f-5405e3275637.jpg)

**Comment by iJungleboy** [comment]
Have you tested it with any 2sxc 10.09+ ? 
I just want to verify that we're chasing the right issue, because all newer versions of 2sxc actually put the diagnostics DLL in a subfolder.

**Comment by tpperlman** [comment]
The site has been running 2SXC v10.9.1, and I do see the DLLs in the subfolder.

**Comment by iJungleboy** [comment]
are they also in the main bin/ ? because I would understand if that would cause a problem, but not if it's in a subfolder. But they could be in both places, if the 2sxc had been upgraded from a previous version that still put it in the main bin.

**Comment by iJungleboy** [comment]
so they are _not_ in the main bin folder, but in the subfolder only?
Because in that case, I'm not sure if it can be fixed :(. that's normally how DLL version compatibilitiy issues are solved.

**Comment by tpperlman** [comment]
The DNN/2SXC install is the same as I have on other hosts. It appears that Azure loads the System.Diagnostics as a part of Application Insights. Maybe you can raise the issue with them to resolve, or you can create a free azure web app to test it out as well. Either way, the only way I can run 2SXC v10+ on Azure is to disable Application Insights.

**Comment by iJungleboy** [comment]
@tpperlman thanks for this. It would be great if you could contact them so they could tell us what we must change. 
Do you think this will affect many people - otherwise we may need to blog about it or something.

**Comment by tpperlman** [comment]
@iJungleboy I will have to create a new test account at Azure to do this since the client's site that was experiencing the issue is preparing to go live and I don't want to mess with it.

As far as a blog is concerned, I wouldn't know how to estimate how many DNN sites are running on Azure Web Apps with 2SXC 10+ installed. This would only be a problem for users with Application Insights enabled, which is the default.

**Comment by tpperlman** [comment]
I opened an issue with the Azure team at [https://social.msdn.microsoft.com/Forums/en-US/5593262d-4314-4d97-83cd-2497bba1913d/application-insights-causes-error-in-dnn-application-with-2sxc-module?forum=ApplicationInsights](url).

Let's see if they have any thoughts.

**Comment by tpperlman** [comment]
I also created a new Web App using a fresh install of the latest DNN and 2SXC so we can test, and can confirm the issue persists.

**Comment by iJungleboy** [comment]
sounds great, thanks! I just read the post and the intermediate answers, but I'm not sure if it's getting anywhere. If they want to talk to us directly (which would be awesome), just give them the info@ mail of 2sxc.

**Comment by imhobie** [comment]
Conflict is in the version of System.Diagnostics.DiagnosticSource. If you want to keep using both Azure Insights and 2sxc then follow these steps:

1. Change the version in the webconfig from 4.0.1.0 to 4.0.2.0 
2. Replace the System.Diagnostics.DiagnosticSource.dll  with version 4.0.2.0 in the bin directory.

You have todo this after every update of 2sxc.

**Comment by iJungleboy** [comment]
@imhobie this sounds like useful information. So you're saying that if this file is a newer version, it should work?
BTW: as of now it is in the subfolder of /bin/2sxc, does the problem still occur then? or is the redirect-binding the problem?

@tpperlman could you reproduce this recommendation from @imhobie ?

**Comment by iJungleboy** [comment]
@imhobie where do you get the 4.0.2.0 version of this DLL? I checked nuget but it doesn't seem to list this version: https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/

**Comment by imhobie** [comment]
@iJungleboy @tpperlman  we use the following DLL and it works
https://drive.google.com/file/d/1R1Eo7mxuqUIAUdrhmOu5Uoq2u_c17sPC/view?usp=sharing

Along with the webconfig edits, you need to replace the file in /bin directory and not in /bin/2sxc

**Comment by iJungleboy** [comment]
@imhobie I'm gratefull for the file, but would need a more official source before I can include it in 2sxc. Where did you get this from? Nuget? or a special distribution of .net ?

**Comment by imhobie** [comment]
When we encountered the problem the tech support provided this solution. So i'm not really sure of the source.

**Comment by iJungleboy** [comment]
@imhobie AFAIK the version you have seems to be 4.4.0, based on the signature date 27. June 2017. https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/

The funny thing is that it's used by other parts, but to actually get this version you have to nuget it by itself - I'll look into that, and maybe upgrade it to 4.7

**Comment by iJungleboy** [comment]
@imhobie could you paste your redirect in the web.config so I can see what exactly it does?

**Comment by iJungleboy** [comment]
@tpperlman and @imhobie I probably have a solution, but need your help to test. Here's what I did

1. I upgraded the code to use the DiagnosticSources v. 4.7
1. Ran into various problems so I had to fiddle around with redirects till it worked
1. I then changed the web.config to assume a DLL version redirect to 4.0.5 - this doesn't make sense, but the versions of the package don't match the real DLL versions. 
1. Now it seems to work - I'm attaching a special build just for this. Please test and verify!

Thanks guys
[2sic_2SexyContent_10.25.01_Install.zip](https://github.com/2sic/2sxc/files/4065010/2sic_2SexyContent_10.25.01_Install.zip)

**Comment by stu-ball** [comment]
I've tried updating to the special build 10.25.01, however I'm still getting the same error when enabling App Insights:
`[FileNotFoundException: Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.]`
Any suggestions?

**Comment by iJungleboy** [comment]
@stu-ball thanks - I cannot explain it. First of the latest 2sxc should add a redirect in the web.config, resulting in it lookin for version 4.0.5.0 - not 4.0.1. So if it's looking for 4.0.1, maybe the redirect didn't make it to the web config? Could you check -  you should see this:

```
      <dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" />
        <bindingRedirect oldVersion="0.0.0.0-4.32767.32767.32767" newVersion="4.0.5.0" />
        <codeBase version="4.0.5.0" href="bin\2sxc\System.Diagnostics.DiagnosticSource.dll" />
      </dependentAssembly>
```

**Comment by stu-ball** [comment]
@iJungleboy sorry, I should have provided more context. Here's what I've got in my web.config:
```xml
      </dependentAssembly>
      <!--Upgraded by 2SexyContent version 10.25.0 - Date: 1/14/2020 8:41:56 AM-->
      <!--<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1"><assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" /><bindingRedirect oldVersion="0.0.0.0-4.32767.32767.32767" newVersion="4.0.1.0" /><codeBase version="4.0.1.0" href="bin\2sxc\System.Diagnostics.DiagnosticSource.dll" /></dependentAssembly>-->
      <!--Upgraded by 2SexyContent version 10.25.1 - Date: 1/16/2020 2:50:06 AM-->
      <!--<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1"><assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" /><bindingRedirect oldVersion="0.0.0.0-4.32767.32767.32767" newVersion="4.0.1.0" /><codeBase version="4.0.1.0" href="bin\2sxc\System.Diagnostics.DiagnosticSource.dll" /></dependentAssembly>-->
      <dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" />
        <bindingRedirect oldVersion="0.0.0.0-4.32767.32767.32767" newVersion="4.0.5.0" />
        <codeBase version="4.0.5.0" href="bin\2sxc\System.Diagnostics.DiagnosticSource.dll" />
      </dependentAssembly>
```

I've attached a screenshot of the DLL from the /bin/2sxc subfolder:
<img width="303" alt="DiagnosticSourceDll" src="https://user-images.githubusercontent.com/34940456/72515537-0c86ec80-388b-11ea-866e-ac61e2978587.png">

Please let me know if there's anything I should do to test/troubleshoot?

**Comment by iJungleboy** [comment]
@stu-ball Thanks - everything seems right - which is super-confusing why your error says it can't find 4.0.1.0 - since all access should be looking for 4.0.5.0 because of the redirect. 

When are you seeing the error - just one big splash loading the page, or at the module level or elsewhere? Does it say what's requesting this 4.0.1.0?

**Comment by imhobie** [comment]
As soon as you enable Application Insights, the whole site just stops working and gives server error. 

The error is different than the earlier one, as now its states _System.**Memory**_ where earlier it used to say about _System.**Diagnostics.DiagnosticSource**_:

```
Server Error in '/' Application.
Could not load file or assembly '**System.Memory**, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
```

**Comment by imhobie** [comment]
> @imhobie AFAIK the version you have seems to be 4.4.0, based on the signature date 27. June 2017. https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/
> 
> The funny thing is that it's used by other parts, but to actually get this version you have to nuget it by itself - I'll look into that, and maybe upgrade it to 4.7

Yes you are correct, i downloaded 4.4.0 version from https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/4.4.0 and replaced it in bin/2sxc/ and it works but have to use 4.0.2.0. The ApplicationInsights.dll just works with this version

```
<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" />
        <bindingRedirect oldVersion="0.0.0.0-4.32767.32767.32767" newVersion="4.0.2.0" />
        <codeBase version="4.0.2.0" href="bin\2sxc\System.Diagnostics.DiagnosticSource.dll" />
      </dependentAssembly>
```

**Comment by iJungleboy** [comment]
@imhobie could you check - because usually a redirect should also work with newer versions. could you try to use the 2sxc package in this thread and see if that works? because usually these redirects should function properly, and I'm afraid to delivering exactly 4.0.2, because then a future version of Insights will suddenly need a newer version, and then everything breaks again.

**Comment by iJungleboy** [comment]
@imhobie I just read your previous comment - thanks for that. So I guess 4.0.5 needs System.Memory in a different version :(. Let me see if I can make a 4.4.0 = 4.0.2 release - I'll be back soon...

**Comment by iJungleboy** [comment]
Here's a new release with 4.0.2 (actually 4.4.0) - could you test this? thanks!
[2sic_2SexyContent_10.25.01_Install.zip](https://github.com/2sic/2sxc/files/4071233/2sic_2SexyContent_10.25.01_Install.zip)

**Comment by stu-ball** [comment]
@iJungleboy thank you so much - the new release works for me!

**Comment by iJungleboy** [comment]
@stu-ball thanks for the feedback - awesome!

**Comment by stu-ball** [comment]
Hi @iJungleboy 

Today we tried installing the AppInsights module for DNN Platform from here: https://github.com/davidjrh/dnn.appinsights

Now we get errors within the 2sxc modules on our pages. Should we not be using the AppInsights module for DNN Platform?

We've tried updating 2sxc to 10.25.02 however the result is the same. Here's the error message we're seeing:

Error: System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. File name: 'System.Diagnostics.DiagnosticSource, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. File name: 'System.Diagnostics.DiagnosticSource, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog]. at Microsoft.EntityFrameworkCore.Infrastructure.RelationalServiceCollectionExtensions.AddRelational(IServiceCollection services) at Microsoft.Extensions.DependencyInjection.SqlServerServiceCollectionExtensions.AddEntityFrameworkSqlServer(IServiceCollection services) at Microsoft.EntityFrameworkCore.Infrastructure.Internal.SqlServerOptionsExtension.ApplyServices(IServiceCollection services) at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_1.<GetOrAdd>b__2(Int64 k) at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options) at Microsoft.EntityFrameworkCore.DbContext.GetServiceProvider(DbContextOptions options) at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options) at ToSic.Eav.Persistence.Efc.Models.EavDbContext..ctor(DbContextOptions`1 options) in C:\Projects\eav-server\ToSic.Eav.Persistence.EFC11\Models\EavDbContext.cs:line 32 --- End of stack trace from previous location where exception was thrown --- at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument) at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider) at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType) at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider) at ToSic.Eav.Factory.Resolve[T]() in C:\Projects\eav-server\ToSic.Eav.Core\Factory.cs:line 84 at ToSic.Eav.Caching.AppsCache.get_Zones() in C:\Projects\eav-server\ToSic.Eav.Core\Caching\Apps\AppsCache.cs:line 31 at ToSic.Eav.Apps.ZoneRuntime.Languages(Boolean includeInactive) in C:\Projects\eav-server\ToSic.Eav.AppEngine\ZoneRuntime.cs:line 24 at ToSic.Sxc.Dnn.Run.DnnZoneMapper.CulturesWithState(Int32 tenantId, Int32 zoneId) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Dnn\Run\DnnZoneMapper.cs:line 0 at ToSic.Sxc.Dnn.Web.ClientInfos.ClientInfosLanguages..ctor(PortalSettings ps, Int32 zoneId) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Dnn\Web\ClientInfos\ClientInfosLanguages.cs:line 20 at ToSic.Sxc.Dnn.Web.ClientInfos.ClientInfosAll..ctor(String systemRootUrl, PortalSettings ps, IContainer mic, ICmsBlock cms, UserInfo uinfo, Int32 zoneId, Boolean isCreated, Boolean autoToolbar, ILog parentLog) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Dnn\Web\ClientInfos\ClientInfosAll.cs:line 30 at ToSic.Sxc.Dnn.Web.DnnRenderingHelpers.UiContextInfos(Boolean autoToolbars) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Dnn\Web\DnnRenderingHelpers.cs:line 84 at ToSic.Sxc.Dnn.Web.DnnRenderingHelpers.ContextAttributes(Int32 instanceId, Int32 contentBlockId, Boolean includeEditInfos, Boolean autoToolbar) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Dnn\Web\DnnRenderingHelpers.cs:line 75 at ToSic.Sxc.Dnn.Web.DnnRenderingHelpers.WrapInContext(String content, String dontRelyOnParameterOrder, Int32 instanceId, Int32 contentBlockId, Boolean editContext, String tag, Boolean autoToolbar, Boolean addLineBreaks) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Dnn\Web\DnnRenderingHelpers.cs:line 55 at ToSic.Sxc.Blocks.CmsBlock.Render() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Blocks\CmsBlock_Render.cs:line 77

**Comment by iJungleboy** [comment]
It's a DLL version issue.
Best use the newest necessary DLL, and adjust the redirect-bindings in the web.config.

**Comment by stu-ball** [comment]
I'll give that a try - thanks again!
