### ISSUE TITLE
REQUIRED field doesn't work in combination with CKEditor

### ISSUE THREAD

**Issue by a-git-hub** [2sic/2sxc#1913]
Hello,

**I'm submitting a ...** 

[x] bug report 

**...about**   
[x] admin experience UI
[x] Content Types or data management

**Current behavior**
The field "Text" is set as **REQUIRED**. Also the **CKEditor** is connected with this field. 
But one can save without filling out the field "Text" ==> REQUIRED feature doesn't work in this case. 

**Expected behavior**
An empty REQUIRED field should  prevent saving.

**Minimal reproduction of the problem with instructions**
The field "Text" is set as REQUIRED. Also the CKEditor is connected with this field. 
But one can save without filling out the field "Text" - REQUIRED doesn't work. 

Screenshot 1:
![image](https://user-images.githubusercontent.com/20930019/70313956-d4fe3c80-1816-11ea-99b8-8c4e2722c4a3.png)

Screenshot 2:
![2sxc-Text-field-required-sc1](https://user-images.githubusercontent.com/20930019/70312305-a92d8780-1813-11ea-9ea9-0323763acc7b.png)

Screenshot 3:
![2sxc-Text-field-required-sc2](https://user-images.githubusercontent.com/20930019/70312329-b9ddfd80-1813-11ea-9bc4-25efedfda4b9.png)

**What is the motivation / use case for changing the behavior?**
REQUIRED field should work.

**Please tell us about your environment:**
Windows 10, IIS

* **2sxc version(s):** 9,43,2
* **Browser:** Chrome newest | IE 11 
* **DNN:** 9.3.2
* **Language:** English | German

Sorry, we don't use 2sxc v. 10 yet because it looks completely different than v. 9 (which means we would need to change all of our CMS documentation with screenshots for our customers) + it looked very buggy (e.g. not possible to switch off Adam - tested in Sept 2019).

**Comment by iJungleboy** [comment]
Since we never use the CK editor, this is not on our priorities. If someone wants to contribute, please do. 

Note that I believe the CK editor is also not implemented in the new UI, so this would be necessary as well.

**Comment by iJungleboy** [comment]
I'll close this for now, as I assume nobody will actually invest the time for this.
