### ISSUE TITLE
the 'Current window' option for links does not work. Links are always opened in a new tab. 

### ISSUE THREAD

**Issue by ICATT** [2sic/2sxc#1945]
**I'm submitting a ...** 

[x] bug report 

**...about**   
[x] edit experience / UI

**Current behavior**
The 'Current window' option in the hyperlink editor (in the rich text editor) is being ignored. Links are always opened in a new tab.

**Expected behavior**
Links should open in the current browser window when they have the 'Current window' option selected in the hyperlink editor

**Minimal reproduction of the problem with instructions**
1 create an app with a normal string field
2 place an instance of the app on a page
3 add a link to the content using the rich text editor.
4 select 'Current window' in the 'Open link in ..' dropdown 
5 save
6 click the link. it opens the url in a new browser tab instead of the current window

**What is the motivation / use case for changing the behavior?**
it doesn't work

**Please tell us about your environment:**

* **2sxc version(s):** 10.9.1  
* **Browser:** [all ]
* **DNN:** [9.4.1] 
* **Language:** [any ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Does this still occur in 10.24 LTS? is it a wysiwyg problem (does the wysiwyg still write a _blank target?

**Comment by ICATT** [comment]
Yes, the problem still occurs in 10.24 LTS.
All links get a _blank target
note: when you go back to the link editor, the field 'Open link in ..' is back at it’s default value.

Met vriendelijke groet,

Mark Stoker
Developer

ICATT interactive media
Nieuwezijds Voorburgwal 120-126
1012 SH Amsterdam
tel: +31 (0)20 6383068
direct: +31 (0)20 5213538
mark.stoker@icatt.nl<mailto:mark.stoker@icatt.nl>
www.icatt.nl<http://www.icatt.nl/>


Van: iJungleboy <notifications@github.com>
Verzonden: Thursday, January 2, 2020 12:23 PM
Aan: 2sic/2sxc <2sxc@noreply.github.com>
CC: ICATT <scrumteams@icatt.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [2sic/2sxc] the 'Current window' option for links does not work. Links are always opened in a new tab. (#1945)


Does this still occur in 10.24 LTS? is it a wysiwyg problem (does the wysiwyg still write a _blank target?

**Comment by iJungleboy** [comment]
@PagnoDunadan could you check this? it seems that TinyMCE seems to "force" all external links to be _blank, when it should only do that if no target is specified yet.

**Comment by PagnoDunadan** [comment]
This is a bug with TinyMCE (https://github.com/tinymce/tinymce/issues/5135). Apparently it's fixed in version 5.1.3. released on December 4th, 2019, but Cloudflare doesn't yet host this version. Latest version they have is 5.1.2. which I've tested and can confirm that in that version bug still exists.

**Comment by iJungleboy** [comment]
just fyi: we're working on it right now - but seems to be quite a thing because so much changed...

**Comment by iJungleboy** [comment]
fixed. But because the tinymce update required quite a few changes, we won't release it in the LTS but in 10.26.

**Comment by ICATT** [comment]
Good to hear. Thanks for fixing this. we're looking forward to the 10.26 release.

**Comment by iJungleboy** [comment]
fyi: released.
