### ISSUE TITLE
Import an app although the folder already exists

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#195]
The app import does not allow importing an app if an app-folder with the same name already exists in the 2sxc directory. It would be a great enhancement if the user could change the app name before importing.

**Comment by iJungleboy** [comment]
...and it would be nice if
1. if the app-folder exists, but doesn't have an app to it (because it was deleted by accident) the "old" folder would just get renamed from "Original" to "Original 2015-04-24 1332"...
1. and if it exists because there is such an app, then ask for rename

**Comment by iJungleboy** [comment]
Note / idea from Raphael for same issue (duplicate)
Rename existing [PortalHomeDirectory]/2sxc folders to something like 2sxc-Archived-2015-05-07-13-23 when the module is installed. This would prevent errors when the module has been uninstalled and installed again.
