### ISSUE TITLE
Editing test-values kills wiring-information

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#196]
when I edit test-values (like [Module;ModuleID] etc. saving that content-item "kills" existing wiring which was in a hidden field.

**Comment by BeniGemperle** [comment]
Has to do with different DimensionIds padded to UpdateEntity()

**Comment by BeniGemperle** [comment]
Issue still occurs. Hidden Fields are always removed as soon as DimensionIds are set on UpdateEntity()
