### ISSUE TITLE
Can't find API root - Mozilla Firefox only

### ISSUE THREAD

**Issue by josip8** [2sic/2sxc#1962]
**I'm submitting a ...** 
[x] bug report

**...about**
[x] JS development
[x] APIs like REST
[x] other / unknown

**Current behavior**
Error occurs only in Mozilla Firefox:
![image](https://user-images.githubusercontent.com/26368640/72538654-6f25bb80-387e-11ea-8ddd-3d237e918674.png)
this line --> `const sxc = $2sxc(@Dnn.Module.ModuleID);` causes error

**Minimal reproduction of the problem with instructions**

Add this code to your view:

`<script>
  const sxc = $2sxc(@Dnn.Module.ModuleID);
</script>`

---
2sxc version: 10.25.0
Browser: [ Firefox 72.0.1 ]
DNN: [ 9.4.4 ]

**Comment by iJungleboy** [comment]
Thanks - short questions: 

1. does the problem also occur on Chrome visiting the same page? just so we know if it's a browser or general issue. 
2. is it a new app / code or something older which was upgraded
1. is it online - so could I browse it to see the bug?

**Comment by josip8** [comment]
1. Only Firefox has this issue, on chrome everything works as expected
2. It is new DNN 9.4.4 installation and new 2sxc 10.25 version
3. Unfortunately not online yet, site is in development
4. It is custom app I made
5. I got error logged on, didn't test it anonymously
---
I tried again with new DNN 9.4.4 installation, 2sxc 10.25, created app, created view and issue is still the same (logged on and anonymously)
- on chrome no issues
- on firefox on every reload i get error
- on edge I get error only on first load, and then after reload no more errors

Here is barebones app i created:
[2sxcApp_Test_0.0.1.zip](https://github.com/2sic/2sxc/files/4073652/2sxcApp_Test_0.0.1.zip)

**Comment by iJungleboy** [comment]
I believe it's fixed - here's a pre-release of 10.25.01 I just made 10 minutes ago. I believe it's fixed - can you try it? it's in the releases - Pre-Release 2
https://github.com/2sic/2sxc/releases/tag/v10.25.01b

**Comment by josip8** [comment]
Great! Now works in every browser 😃

**Comment by iJungleboy** [comment]
awesome!
