### ISSUE TITLE
Cannot read property 'componentType' of undefined

### ISSUE THREAD

**Issue by josip8** [2sic/2sxc#1968]
**I'm submitting a ...** 

[x] bug report
[x] not sure

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management
[x] other / unknown

**Current behavior**

When trying to open edit window or adding new item to ContentType i get this error:

![image](https://user-images.githubusercontent.com/26368640/72879432-21d1a000-3cfd-11ea-9fa2-704073becd44.png)

This only happens with new form (introduced with 2sxc v10). When opening edit/new window with old form everything works as expected.

**Minimal reproduction of the problem with instructions**

This is how ContentType fields look:

![image](https://user-images.githubusercontent.com/26368640/72879719-be943d80-3cfd-11ea-9c3b-521b24ca3834.png)

Probably ContentType field "ContentType" causes issues?

**Please tell us about your environment:**

* **2sxc version(s):** 10.25.0  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [ 9.4.4 ] 
* **Language:** [any/all]

**Comment by iJungleboy** [comment]
Hi josip8, this is a history-problem :) thanks for spotting it. 
It was a special internal feature that we temporarily made in 2sxc 8 to get Mobius to work, but since then has been replaced with a standard feature. 
To upgrade, use this recipe: https://azing.org/2sxc/r/EcFsyXqB
