### ISSUE TITLE
CreateSource<EntityTypeFilter>() gives error in v10.25.04

### ISSUE THREAD

**Issue by TopCat6** [2sic/2sxc#1981]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] Razor templating
[x] JS development
[x] Content Types or data management

**Current behavior**

Unchanged source from previous version now gives this error:
`Error: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary. at System.Collections.Generic.Dictionary'2.get_Item(TKey key) at ToSic.Sxc.Code.DynamicCodeRoot.get_ConfigurationProvider() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Code\DynamicCodeRoot.cs:line 120 at ToSic.Sxc.Code.DynamicCodeRoot.CreateSource[T](IDataSource inSource, ILookUpEngine configurationProvider) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Code\DynamicCodeRoot.cs:line 131 at ToSic.SexyContent.Razor.SexyContentWebPage.CreateSource[T](IDataSource inSource, ILookUpEngine configurationProvider) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\SexyContentWebPage.cs:line 141 at ASP._Page__0__2sxc_Quotes__QuoteEditor_cshtml.Execute() in c:\DotNetNuke\Website\[0]\2sxc\Quotes\_QuoteEditor.cshtml:`**line 7** `at System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) at ToSic.Sxc.Engines.RazorEngine.Render(TextWriter writer) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\Engines\Razor\RazorEngine.cs:line 81 at ToSic.Sxc.Engines.RazorEngine.RenderTemplate() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\Engines\Razor\RazorEngine.cs:line 90 at ToSic.Sxc.Engines.EngineBase.Render() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Engines\EngineBase.cs:line 108 at ToSic.Sxc.Blocks.BlockBuilder.Render() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Blocks\BlockBuilder_Render.cs:line 61`
The referenced line 7 is:
`var allQuotes = CreateSource<EntityTypeFilter>();`
**Expected behavior**

Normally, the code runs without error.
Has support for EntityTypeFilter changed in this version?
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **2sxc version(s):** 10.25.04  
* **Browser:** [ Firefox XX  ]
* **DNN:** [ 9.4.4 ] 
* **Language:** [ English ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
I won't have time to look at it this week - could you include some code of the _QuoteEditor.cshtml?

**Comment by TopCat6** [comment]
Here it is:

```
@using ToSic.Eav.DataSources
<div class="BasicContentWithPreview sc-element">
	@Edit.Toolbar(ListContent)
	<h2><span class="QuoteTitle">@Dnn.Module.ModuleTitle</span></h2>
	@{
		// A source which can filter by Content-Type (EntityType)
		var allQuotes = CreateSource<EntityTypeFilter>();
		allQuotes.TypeName = "Quotation";
	}
	<h6>Quotations</h6>
	<ol>
		@foreach (var q in allQuotes.List)
		{
			var quote = AsDynamic(q);
			var pub = "Show";
			if (!quote.IsPublished)
			{
			    pub = "Hide";
			}
			<li class="sc-element">@Edit.Toolbar(quote)<small>[@quote.EntityId (@pub)]</small> @quote.Quotation</li>
		}
	</ol>
</div>
```

**Comment by iJungleboy** [comment]
Note that there seems to be something wrong with picking up the configuration provider. 
What version did you upgrade from?
Does this view have something special? like a query to provide it with data? because internally it's looking for Data["Default"] to get the configuration provider, and your Data doesn't seem to have a "Default" stream.

**Comment by TopCat6** [comment]
Thanks for the insight! The previous version I upgraded from was 10.25.02 LTS. It was working fine. There is no query. The data source is normally from a Content-Type and Data source called Quotation, but somehow during the update it got changed to another source called Quotes. Changing it back to the proper one fixed the issue.

Much thanks!

**Comment by iJungleboy** [comment]
you're welcome ;)
