### ISSUE TITLE
[Feature request] Allow string variable in App.Data["ContentType"]

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1982]
**I'm submitting a ...** 
[x] feature request

**...about** 
[x] Razor templating

**Current behavior**
App.Data["ContentType"] needs the content type name to be typed inside [].

**Expected behavior**
Code could be improved so that variables are accepted:
string contentTypeName = "myContent";
var dynContent = App.Data[contentTypeName];

**What is the motivation / use case for changing the behavior?**
I know I ask for very strange stuff, but this would actually be very useful to me.
I have a content type that has some input tokens that point to another content type and an item inside. I need to be able to select the linked content type on razor. Right now I have a bunch of if - then. A var content name would do the trick.

**Comment by PagnoDunadan** [comment]
Doesn't this already work?
```
@inherits ToSic.Sxc.Dnn.RazorComponent
@{
  var stream = "BasicContent";
}
@AsList(App.Data[stream]).ToList()[0].EntityTitle
```

**Comment by eXistenZe** [comment]
Well... This is what happens when you test things in the middle of the night...
Yes. It does work. Yesterday it was complaining about dynamic inside []. My bad.
Thanks.
