### ISSUE TITLE
Wish: Item History modal UI/UX could be vastly improved

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#1984]
**I'm submitting a ...** 
[x] wishlist item

**...about**   
[x] edit experience / UI

**Current behavior**
The item history modal has a strange UI/UX. When you open a item-history panel to try to revert to an older item, here are the following UI/UX issues:

1. The fields aren't sorted by the same order as they are in the actual content type modal
2. The fields show the field names and not the field labels so the content editor won't necessarily see the same labels
3. The ability to expand fields is not obvious - and clicking on any field inserts an asterisk * but I'm not sure what that is. Even empty fields are clickable in this view
4. The field values for things like dropdowns and images show the field values instead of the friendly names. For example, I have a dropdown called "Target" and the option/values are New tab:_blank. It shows "_blank" which doesn't mean anything to a non-technical content editor. Same with filenames uploaded through ADAM as they show "file:192994" instead of the actual file path and name.
5. The field type is shown on the right hand side [String] [Hyperlink] etc. This doesn't mean anything to a content editor and is perhaps unnecessary.
6. It doesn't seem to include Presentation Settings on the item either

**Expected behavior**
I think this interface is a bit confusing and might be a bit daunting for an average non-technical Content Editor. Perhaps making it look more similar to the edit modal would be a good solution.

**Minimal reproduction of the problem with instructions**
1. Go to a 2sxc content module
2. Click the "item-history" icon on an item
3. The modal for item history appears. "History of this item"
4. Once you click on "Version N" it expands and you see the fields.

**What is the motivation / use case for changing the behavior?**
While the content is there, and so is the ability to "RESTORE" it doesn't seem very user friendly. Content Editors would be confused by this UI and they might make a mistake because not all of the fields are obvious. For example, they see "file:38272" for the background image but they don't know what image that is without restoring that version and checking the page.

**Please tell us about your environment:**
n/a

* **2sxc version(s):** 10.25.2 
* **Browser:** [all]
* **DNN:** [all ] 
* **Language:** [any/all ]

**Anything you would like to add**

![Screen-Shot-2020-02-21-at-1 23 42-PM](https://user-images.githubusercontent.com/8751936/75073588-9d666e80-54ae-11ea-9079-82dd76e3763f.png)

**Comment by ajplopez** [comment]
I should add another item to this: it would also be useful to know the author of each version so I can know who made the changes.

**Comment by iJungleboy** [comment]
I totally agree with the wishes. Just as of now, we have about 50 other things that will be prioritize, so if someone really wants this done soon, it needs a contribution.

**Comment by iJungleboy** [comment]
Needs sponsoring, so added to #2107 and will close unless someone contributes or sponsors this.
