### ISSUE TITLE
Content type Field metadata breaks if some Field has metadata added twice

### ISSUE THREAD

**Issue by PagnoDunadan** [2sic/2sxc#1987]
**I'm submitting a ...** 
[x] bug report

**...about**   
[x] admin experience UI

**Current behavior**
You can add metadata to content type field, e.g. string-default field
![image](https://user-images.githubusercontent.com/7113033/75555570-c94c9b80-5a3c-11ea-8f1a-84350a243d81.png)

If two admin dialogs attach metadata to the same field, e.g. when two users have content type opened and didn't refresh list of fields to notice that field already has metadata attached, field will break resulting in error:
![image](https://user-images.githubusercontent.com/7113033/75555809-40822f80-5a3d-11ea-9cec-19492cf1df84.png)
![image](https://user-images.githubusercontent.com/7113033/75555897-6c9db080-5a3d-11ea-9e4c-ecb15ec1fc83.png)
From there fields for that content type can't be edited and content type probably has to be deleted.

**Expected behavior**
Backend should block duplicate metadata entries.

**Please tell us about your environment:**
* **2sxc version(s):** 9 and 10 have the same problem
* **Browser:** all
* **DNN:** 7.4.2
* **Language:** any/all

**Comment by iJungleboy** [comment]
thx. but we'll put this as low priority, as it's very rare to happen

**Comment by iJungleboy** [comment]
won't fix for now, but we'll keep it in mind...
