### ISSUE TITLE
iFrame causes ALL content to be stripped out of a rich text (long text field) when saving the content of 2sxc content template.

### ISSUE THREAD

**Issue by INNO-Software** [2sic/2sxc#1996]
I'm submitting a ... [x] bug report
[x] edit experience / UI

**Current behavior**
In 2sxc 10.4.0 using a template with a long text field editor we are able to add standard text and images, etc. When we add content in an iframe into the SOURCE view of the text, we cannot save and exit the record without it AUTOMATICALLY stripping out the **entire** field. (Including the other text, etc. that was NOT surrounded by the <iframe> tags.

**Expected behavior**
I'd expect the content to be saved. If iFrames cannot be saved by design, then in the very least they should only strip _themselves_ out of the field, not the value of the WHOLE field.

**Minimal reproduction of the problem with instructions**
Add something like this to a standard text template.

<p>Below is a video in an iFrame. Both IT and the text I am putting in this paragraph will be removed when I try to save+exit editing the record in a 2sxc template.</p>

<iframe width="1903" height="800" src="https://www.youtube.com/embed/Yhc2Tp9h5OI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**What is the motivation / use case for changing the behavior?**
To use iFrames, as we expect to be able to. OR, to not have ALL content stripped where one is accidentally included.

**Please tell us about your environment:**
DNN 9.3.2 / 2SXC 10.4.0 / Windows 2016 / SQL 2017 Web

* **2sxc version(s):** 10.4.0  
* **Browser:** [all]
* **DNN:** [9.3.2 ] (haven't checked others)
* **Language:** [English] (haven't checked others)

**Comment by ajplopez** [comment]
I'm curious if this is still an issue in newer versions of the module.

**Comment by INNO-Software** [comment]
> I'm curious if this is still an issue in newer versions of the module.

It does **NOT** occur in 2sxc 9.14.0 on DNN 9.2.1. So if it is fixed in a newer version, the issue was introduced between these two version. Alternatively, the environment/settings/template/etc. could be a factor only on the site where this issue occurs.

Be it environmental, or _only_ version 10.4.0 (and/or) DNN 9.3.2 - this would be a value to everyone to be aware of.

**Comment by iJungleboy** [comment]
@INNO-Software could you tell me does this happen

1. in the old UI (angularJS)
1. only in the new UI 10.x+ (Angular 8 + tinymce 5.0)
1. only in the latest release ca. 10.26 (Angular 8 + tinymce 5.1)?

**Comment by INNO-Software** [comment]
I tested in 2sxc 10.25.2 on DNN 9.4.1 and it behaved as expected. The iFrame was **not** stripped out. (If I find an older version on one of my instances I'll try it.)

As mentioned though, as early as 9.14.0 WORKS.
**IF** it failed prior to 9.14.0 then it'd have
a) _FAILED_ in old UI (not known)
b) _WORKED_ in 9.14 (confirmed)
c) _FAILED_ in 10.4.0 (confirmed, original case)
d) _WORKED_ again in 10.25.2 (confirmed)

FYI: The client may decide to just upgrade to 10.25.2 to remove the possibility that it is environmental. If I learn anything meaningful, I'll add it to this ticket.

**Comment by iJungleboy** [comment]
this sounds good - so if it works in the latest version I'll flag this as done. 
Please don't hesitate to add new findings here, as it will help other users.

**Comment by INNO-Software** [comment]
@iJungleboy FYI: I applied the 10.25.2 version to the failing 10.4.0 and it _corrected_ the behavior. So it may be an issue only with that specific version. (At least, without anyone else confirming seeing it in another build.)

**Comment by iJungleboy** [comment]
thx
