### ISSUE TITLE
Use the new AsList in a custom API

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2002]
**I'm submitting a ...** 
[x] support request 

**...about** 
[x] Razor templating

**Current behavior**
I can use
`@inherits ToSic.Sxc.Dnn.RazorComponent`
in a view, but I can't find a way to implement this on a controller. 

Is it possible to implement this on an api?

* **2sxc version(s):** 10.25

**Comment by iJungleboy** [comment]
Sorry, not clearly documented - you must inherit from the new https://docs.2sxc.org/api/dot-net/ToSic.Sxc.Dnn.ApiController.html

See also https://2sxc.org/dnn-tutorials/en/razor/webapi110/page

**Comment by eXistenZe** [comment]
I still don't get it.

**Comment by iJungleboy** [comment]
Here's how: Check out the tutorial example, there you have this WebApi controller:

```
using System.Web.Http;		// this enables [HttpGet] and [AllowAnonymous]

[AllowAnonymous]			// define that all commands can be accessed without a login
// Inherit from ToSic...ApiController to get features like App, Data or Dnn - see https://r.2sxc.org/CustomWebApi
public class BasicController : ToSic.Sxc.Dnn.ApiController
{

	[HttpGet]				// [HttpGet] says we're listening to GET requests
	public string Hello()
	{
		return "Hello from the basic controller in /api";
	}


	[HttpGet]				// [HttpGet] says we're listening to GET requests
	public int Square(int number)
	{
		return number * number;
	}


}
```

this line
`public class BasicController : ToSic.Sxc.Dnn.ApiController`
means it inherits from `ToSic.Sxc.Dnn.ApiController` - that has the same effect as the `@inherits ...RazorComponent`.

**Comment by iJungleboy** [comment]
They syntax is just a bit different, because a controller is a normal `.cs` class, whereas a razor `.cshtml` file has the unusual `@inherits` syntax.

**Comment by eXistenZe** [comment]
Got it.
Please don't forget the controller creation implementation in the admin panel.
A simple button to create the api folder and file with a controller name wound be awesome. And the file could have a demo itself with best practices.
