### ISSUE TITLE
Has your Website Certificate just expired?

### ISSUE THREAD

**Issue by VashJuan** [2sic/2sxc#2008]
**I'm submitting a ...**
[x] bug report
[x] not sure

**...about**
[x] admin experience UI
[x] other / unknown

**Current behavior**
Updated to 10.25.2, tried to install the latest Accordian for Collapsable Sections App. When I clicked on the Configure App I got the following two dialogs that, if I read right, indicate you've a certificate that expired on 20 March this year:
<img width="305" alt="3-22-2020 at 6 16 16 PM" src="https://user-images.githubusercontent.com/8594671/77270738-0423a700-6c6a-11ea-8ed3-e365caf60659.png">

<img width="376" alt="3-22-2020 at 6 16 52 PM" src="https://user-images.githubusercontent.com/8594671/77270750-0e45a580-6c6a-11ea-871f-ff22500c82cf.png">

Hopefully it is an error with me (Win 10 Pro & latest Firefox) but maybe you've got to fix it on your end.

**Comment by iJungleboy** [comment]
Seems to be our mistake - a redirector domain just expired yesterday. we'll try to fix asap.

**Comment by iJungleboy** [comment]
it's fixed now, thx!
