### ISSUE TITLE
WYSIWYG Editor Inline Images - Cannot Change Position by Dragging or Cutting/Pasting

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#2011]
**I'm submitting a ...** 
[x] bug report

**...about**
[x] edit experience / UI

**Current behavior**
When edit HTML content using the built-in WYSIWYG editor, inline images cannot be moved to different parts of the content by either dragging and dropping, or cutting and pasting to the new cursor position. The only way to move an inline image is by switching to HTML view and moving it in the code to a new location.

**Expected behavior**
Once an image is placed, it should be able to be dragged and repositioned.

**Minimal reproduction of the problem with instructions**
Create a data type with a text/string type using the default WYSIWYG editor. Add a new item, and put in some HTML text (p, h1, etc). Drag in or use ADAM to insert the inline image and then try to drag it or copy/paste to a new location. Notice how the image does not move, and cutting/pasting simply removes the image all together.

**What is the motivation / use case for changing the behavior?**
Inline images should be able to be repositioned without having to modify the HTML code.

* **2sxc version(s):** 10.26.0
* **Browser:** Verified in Firefox, Chrome, Edge
* **DNN:** 09.05.00
* **Language:**all

**Anything you would like to add**
I have tried the other WYSIWYG editors, but they all appear to have the same interface.

**Comment by iJungleboy** [comment]
Can confirm. does copy paste work - it does in my case.

**Comment by PagnoDunadan** [comment]
I don't think this ever worked in TinyMCE. I've tried their demo app and if image is loaded from an external source and is not a blob, dragging it doesn't work.

**Comment by iJungleboy** [comment]
If I simulate it on https://www.tiny.cloud/ it seems to work though.

**Comment by PagnoDunadan** [comment]
Weird. Sometimes it indeed works, but sometimes it deletes the img tag.

**Comment by tpperlman** [comment]
Hi guys, I just tried again in the latest FF and Chrome. Dragging the image into the "drag" area at the bottom of the editor does place the image wherever the cursor is positioned, but you cannot move it by drag/drop or copy/paste.

**Comment by iJungleboy** [comment]
@PagnoDunadan could it be that our drag-drop intercepts this?

**Comment by PagnoDunadan** [comment]
This is the case. Drag and drop for the Dropzone somehow stops image dragging inside TinyMCE from working.

**Comment by eXistenZe** [comment]
You guys would trust a front editor to move an image? How do you place it in the exact div/whatever?

**Comment by tpperlman** [comment]
Of course, if the have the ability to add a picture, why not choose where to put it? For more advanced layouts, I create razor templates that have separate pre-designated areas for photos that can be uploaded successfully. That is the whole point of 2sxc. But to allow uploads without positioning is only a half-solution that causes more issues for editors.

**Comment by eXistenZe** [comment]
Two different subjects.
One think is to design a razor template with predefined places for 2sxc fields to fill. The image placeholder is still defined by proper code.
Another thing is to place and move objects with a design editor like WYSIWYG. For me it would be a nightmare to place it right and style it.

**Comment by tpperlman** [comment]
If you don't want editors to have any ability to manipulate images or affect HTML, then you should ideally be using a multi-line textbox instead of HTML. If I am giving someone an HTML editor, they should be able to move images the same as text. If they mess something up, they can revert to previous version.

Point is, this is by-design functionality in the TinyMCE editor that isn't working... and that has nothing to do with your concern if it gets fixed since it used to work.

**Comment by eXistenZe** [comment]
There is no concern on my end. Just trying to understand the usecase, since there are other possibilities that seem more efficient (either use code in the template, or use a proper app for web design).
WYSYWYG seems more inclined for basic stuff like bold, lists, headings, etc.

**Comment by tpperlman** [comment]
I build websites for clients, and although we try to account for every situation how content will be laid out and used we can't cover 100%. So when they want to place a floating image somewhere, who am I to tell them they can't. Every use case is different, and since this already exists in TinyMCE these comments are somewhat moot unless 2sxc creates its own editor or uses one that does not allow image manipulation. In my opinion, it is a feature I need. But if you feel that you don't want to allow editors to move images then that is your choice but I shouldn't lose functionality over it.

**Comment by iJungleboy** [comment]
I think the normal image-use in wysiwyg is primarily for Blog- and News scenarios, where the content tends to be an article with a longer, variable content.

**Comment by eXistenZe** [comment]
I am not a 2sxc dev. Just a normal user :)
In any way, is wysisyg capable enough for blog posts? Placing images is just one step. How do you make them responsive (size and placement)? Inline CSS?

**Comment by tpperlman** [comment]
@eXistenZe for something like a blog, I use separate fields for text/html content and images. The images are managed separately so there are no layout/resizing issues. The issue in the original post relates to ad-hoc images that are more of an exception than a rule.

**Comment by PagnoDunadan** [comment]
Move is fixed in Chrome, but in Firefox image is copied and original one has to be manually removed.
I can't figure out why this happens and we will have to live with this for now. I will check for TinyMCE updates from time to time to see if this behavior changed.
