### ISSUE TITLE
[Admin - data] Some numeric fields do not show in the entity data list

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2012]
**I'm submitting a ...** 
[x] bug report 

**...about** 
[x] admin experience UI
[x] Content Types or data management

**Current behavior**
I can't quite pin this to a specific cause, but in some entities with a numeric fields, these fields do not show in the data tab. See pics.

**Expected behavior**
All fields should show the data.

**Minimal reproduction of the problem with instructions**
See pics.

**What is the motivation / use case for changing the behavior?**
This is a minor issue. The values are there and stored, they just don't show in the data tab.

* **2sxc version(s):** 10.36  
* **DNN:** [9.5 ] 
* **Language:** [English | Portuguese ]

![1](https://user-images.githubusercontent.com/26518879/77439965-a0bb8580-6ddf-11ea-8e02-578e99a6257d.jpg)

![2](https://user-images.githubusercontent.com/26518879/77439985-a618d000-6ddf-11ea-8149-ad534ab8b7d7.jpg)

![3](https://user-images.githubusercontent.com/26518879/77439998-a87b2a00-6ddf-11ea-83f1-455a88be3b6c.jpg)

**Comment by PagnoDunadan** [comment]
![image](https://user-images.githubusercontent.com/7113033/77441914-4a077900-6dea-11ea-9f70-e32309f4bd31.png)
**Id, Guid, _RepositoryId, IsPublished, _Title and Title** are fields used by 2sxc and if your field has the same name it will be ignored.

**Comment by eXistenZe** [comment]
Makes sense. It's an habit to make everything "i" and "id".
