### ISSUE TITLE
WYSIWYG Editor - Create Link to Portal Page Always Opens in New Window

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#2019]
**I'm submitting a ...** 
[x] bug report

**...about**
[x] edit experience / UI

**Current behavior**
When using the Page Picker in the TinyMCE HTML Editor, links to internal pages using the Page Picker are created to open in a new window.

**Expected behavior**
Internal links should open in the current window.

**Minimal reproduction of the problem with instructions**
In an HTML editor, type some text, highlight it, and then choose the Page Picker from the toolbar. Select a page on the site and the link is created. If you view source or click on it to Edit the link, you will notice the the target for the link is _blank and the rel attribute is set to noopener.

**What is the motivation / use case for changing the behavior?**
It is typical case for all internal links on a website to open in the current window.

**Please tell us about your environment:**
Any

* **2sxc version(s):** 10.27.1
* **Browser:** all
* **DNN:** 9.4.4
* **Language:** any/all

**Anything you would like to add**
Internal links could be set to default to the current window, and/or perhaps a target drop-down could be added to the page picker. A Create Link button could be used so that the page picker window doesn't close before the editor selects a target.

**Comment by iJungleboy** [comment]
I agree, this shouldn't be. 

We're just on a fairly big change on the editor - because we are just finishing up the brand new admin-ui in Angular 9 and Ivy. So this may take 1-2 weeks, sorry.

**Comment by PagnoDunadan** [comment]
Fixed.
