### ISSUE TITLE
Critical error when uploading an image via ADAM - and form doesn't have String-fields

### ISSUE THREAD

**Issue by MS-BSI** [2sic/2sxc#2024]
Hi,

**I'm submitting a ...** 
[x] bug report

**...about**   
[x] edit experience / UI

**Current behavior**
When we upload any image via ADAM, we got that errors in console log :

(Same error for both adam.service.ts and core.js.pre-build-optimizer.js)
Http failure response for https://ourdomainname.com/desktopmodules/2sxc/api/app-content/04663000-1112-8888-0004-000000000026/4efbe806-b75f-4c78-ac0c-5ab5ac1c4edc/ourappname/items?subfolder=Images/TopFullImage&usePortalRoot=false&appId=5: 400 Bad Request

The file is however correctly uploaded (visible on the server) but it's not possible to validate the modification. The save button has no effect (no error in the logs and no request sent).

**Expected behavior**
No error + form correctly validated.

**Minimal reproduction of the problem with instructions**
If necessary we can communicate you an access to a test site (by private message)

**Please tell us about your environment:**

* **2sxc version(s):** 10.27.01 - 
* **Browser:** All
* **DNN:** 8.0.4
* **Language:** Any

**Anything you would like to add**
No error with 10.25.x versions, it started right after updating to the latest version a few days ago.

Thank you ;)

**Comment by iJungleboy** [comment]
So can you clarify that I understood the problem

1. the upload works 
1. you see a console error
1. the UI doesn't show an error
1. the result contains the new image

is that right? does it hapen in wysiwyg, or in a file-field?
BTW: I just uploaded an image on my latest system, and I don't see any errors. Any way we could reproduce?

**Comment by MS-BSI** [comment]
1. The upload works
2. I see the 2 errors on the console log
3. No error showed on the UI but I can't save the change
4. The result contains the previous image (save doesn't work)

It's on a file field.

I will send you credentials via email ;)

**Comment by MS-BSI** [comment]
Hi,

Did you receive my email (for confirmation) ?

The “save” bug seems to occurs on various 2sic modules, more informations (+ testing website) in my latest email.

Thank you !

**Comment by iJungleboy** [comment]
Will be solved in 10.30 with the new Edit/Admin-UI
Until then please use workaround - just add a string field to the form.
