### ISSUE TITLE
Error with 2sxc 10.27.1

### ISSUE THREAD

**Issue by jncraig** [2sic/2sxc#2030]
**I'm submitting a ...** 
[x] bug report => search github for a similar issue before submitting 

**...about**   

[x] other / unknown

**Current behavior**

DNN 9.5.0 (clean install)
2sxc 10.27.1
empty page with default Xcillion skin

If I add either App or Content module to a page, the Console window shows an error: TypeError: e is undefined

This happens before or after I select an App.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **2sxc version(s):** 10.X.X  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [all | 7.4.2 | 8.X.X | 9.X.X ] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
is functionality reduced, or is the error just logging something?

**Comment by iJungleboy** [comment]
I tried to reproduce
1. have DNN 9.44
1. 2sxc 10.27.01
1. new page, nothing on it yet
1. added content module

I don't see an error. I'm going to guess it's not related to 2sxc or something new in 9.5 - I'll try that as well...

**Comment by iJungleboy** [comment]
could you give me more information on the bug? like what js file or what line of code seems to be the problem

**Comment by iJungleboy** [comment]
no input for 3 days, so I'll close for now. pls re-open if something useful pops up.

**Comment by jncraig** [comment]
Sorry I haven’t gotten back to it.  Will check later.

**Comment by tpperlman** [comment]
I am seeing this error too. I have a DNN v9.5.0 site with 2SXC v10.28.0 installed.

To diagnose, I created a blank skin page with a ContentPane. When I add an app and drag it to the pane, the circle app icon appears but the bottom app selection window doesn't appear. When I click the circle app icon, the Choose App appears. I created a blank app or testing, and when I select it to be added to the page, the page refreshes and I get the following console error:

```
TypeError: e is undefined
inpage.min.js:1:31230
    code https://MyHostname/desktopmodules/tosic_sexycontent/dist/inpage/inpage.min.js?v=10.28.0.33869:1
    run https://MyHostname/desktopmodules/tosic_sexycontent/dist/inpage/inpage.min.js?v=10.28.0.33869:1
    detectParamsAndRun https://MyHostname/desktopmodules/tosic_sexycontent/dist/inpage/inpage.min.js?v=10.28.0.33869:1
    l https://MyHostname/desktopmodules/tosic_sexycontent/dist/inpage/inpage.min.js?v=10.28.0.33869:1
    do https://MyHostname/desktopmodules/tosic_sexycontent/dist/inpage/inpage.min.js?v=10.28.0.33869:1
    run https://MyHostname/desktopmodules/tosic_sexycontent/dist/inpage/inpage.min.js?v=10.28.0.33869:1
    run https://MyHostname/desktopmodules/tosic_sexycontent/dist/inpage/inpage.min.js?v=10.28.0.33869:1
    tryShowTemplatePicker https://MyHostname/desktopmodules/tosic_sexycontent/dist/inpage/inpage.min.js?v=10.28.0.33869:1
    initAllInstances https://MyHostname/desktopmodules/tosic_sexycontent/dist/inpage/inpage.min.js?v=10.28.0.33869:1
    initialize https://MyHostname/desktopmodules/tosic_sexycontent/dist/inpage/inpage.min.js?v=10.28.0.33869:1
    <anonymous> https://MyHostname/desktopmodules/tosic_sexycontent/dist/inpage/inpage.min.js?v=10.28.0.33869:1
    jQuery 2
        e
        t
```

After the module is on the page, I continue to see the same error when I refresh...

**Comment by iJungleboy** [comment]
I think this is the same as #2045 - fix should be released tonight or tomorrow
