### ISSUE TITLE
Bug: empty module sometimes doesn't auto-open the view-picker

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#2038]
**I'm submitting a ...** 
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI

**Current behavior**
A side-effect of a new feature in 10.26 or 10.27 causes the automatic layout-picker to not always open, depending on the version of DNN (jquery).

**Please tell us about your environment:**

* **2sxc version(s):** 10.28

**Comment by classmaxx** [comment]
I have the same problem on multiple Sites after updating with DNN 9.5.0 and 2sxc 10.28. Layout Picker doesn't load always on all sites, so i couldn't add new content...
Any Workaround available ???

**Comment by iJungleboy** [comment]
For now you should be able to just copy these files here https://github.com/2sic/2sxc/tree/10.30x/ToSIC_SexyContent/js
to your "js" folder. 
for safety reasons, just copy your original js first, in case something else breaks which we didn't anticipate.

**Comment by classmaxx** [comment]
Sorry, that doesn't change anything. Debugger shows old code for layout.ts...

**Comment by iJungleboy** [comment]
this is the same as #2045 - should be released tonight or tomorrow.
