### ISSUE TITLE
WYSIWYG Editor Advanced Mode Drop-Down Menus Do Not Work in Safari

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#2041]
**I'm submitting a ...** 
[x] bug report

**...about**
[x] edit experience / UI

**Current behavior**
In Safari, the advanced drop down menus (e.g. file, edit, view, insert...) do not work.

**Expected behavior**
The drop-down menu items should appear like in other modern browsers.

**Minimal reproduction of the problem with instructions**
Edit a text/html data type, switch to Advanced Mode, and notice how none of the drop down menus work.

**What is the motivation / use case for changing the behavior?**
Some clients do use Macs or iPads to manage sites, so perhaps this can be investigated.

**Please tell us about your environment:**
MacOS Catalina 10.15.1

* **2sxc version(s):** 10.28.0
* **Browser:** iOS 13.0.3 Safari
* **DNN:** 9.05.00
* **Language:** any

**Comment by iJungleboy** [comment]
Thanks for this. We don't regularly test on Safari but we'll look into this.

**Comment by PagnoDunadan** [comment]
TinyMCE update fixed this and should no longer be an issue in next release of 2sxc.
