### ISSUE TITLE
DNN page edit mode => change template generates "Uncaught TypeError: Cannot read property 'target' of undefined"

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2045]
**I'm submitting a ...** 
[x] bug report

**...about**  
[x] admin experience UI
[x] DNN parts

**Minimal reproduction of the problem with instructions**
Open a page with a 2sxc app module.
Enter DNN edit page mode
Mouse over pencil icon (edit)
Click Change template / layout

Browser logs this error and nothing happens:
```
layout.ts:19 Uncaught TypeError: Cannot read property 'target' of undefined
    at code (layout.ts:19)
    at e.run (cms-engine.ts:101)
    at e.detectParamsAndRun (cms-engine.ts:52)
    at Cms.ts:43
    at e.do (Cms.ts:53)
    at e.run (Cms.ts:41)
    at e.t.run (sxc-instance-engine.ts:19)
    at e.n.changeLayoutOrContent (dnn-inpage-edit.ts:22)
    at <anonymous>:1:29
```

2sxc menubar => change template works fine.

* **2sxc version(s):** 10.28
* **DNN:** [all | 9.5 ]

**Comment by iJungleboy** [comment]
Seems to be an issue with DNN 9.5 - we already have a fix - should be released today or tomorrow.
