### ISSUE TITLE
Problems Selecting a View after Adding Module 

### ISSUE THREAD

**Issue by michaelcunningham1974** [2sic/2sxc#2047]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI
**Current behavior**

After upgrade to 10.28 when adding an App module to page, Admin can add app successfully but first view is automatically chosen and alternate views are not available. A JS error is thrown.

See Video of behavior at:
[https://www.youtube.com/watch?v=lvZ2oE6qCG4]

`jquery.js?cdv=261:3869 Uncaught TypeError: Cannot read property 'target' of undefined
    at code (layout.ts:19)
    at e.run (cms-engine.ts:101)
    at e.detectParamsAndRun (cms-engine.ts:52)
    at Cms.ts:43
    at e.do (Cms.ts:53)
    at e.run (Cms.ts:41)
    at t.run (sxc-instance-engine.ts:19)
    at e.tryShowTemplatePicker (bootstrap.ts:148)
    at e.initAllInstances (bootstrap.ts:50)
    at e.initialize (bootstrap.ts:33)
code @ inpage.min.js?v=10.28.0.33869:1
e.run @ inpage.min.js?v=10.28.0.33869:1
e.detectParamsAndRun @ inpage.min.js?v=10.28.0.33869:1
(anonymous) @ inpage.min.js?v=10.28.0.33869:1
e.do @ inpage.min.js?v=10.28.0.33869:1
e.run @ inpage.min.js?v=10.28.0.33869:1
t.run @ inpage.min.js?v=10.28.0.33869:1
e.tryShowTemplatePicker @ inpage.min.js?v=10.28.0.33869:1
e.initAllInstances @ inpage.min.js?v=10.28.0.33869:1
e.initialize @ inpage.min.js?v=10.28.0.33869:1
(anonymous) @ inpage.min.js?v=10.28.0.33869:1
mightThrow @ jquery.js?cdv=261:3583
process @ jquery.js?cdv=261:3651
setTimeout (async)
jQuery.readyException @ jquery.js?cdv=261:3868
(anonymous) @ jquery.js?cdv=261:3888
mightThrow @ jquery.js?cdv=261:3583
process @ jquery.js?cdv=261:3651
setTimeout (async)
(anonymous) @ jquery.js?cdv=261:3689
fire @ jquery.js?cdv=261:3317
fireWith @ jquery.js?cdv=261:3447
fire @ jquery.js?cdv=261:3455
fire @ jquery.js?cdv=261:3317
fireWith @ jquery.js?cdv=261:3447
process @ jquery.js?cdv=261:3671
setTimeout (async)
(anonymous) @ jquery.js?cdv=261:3689
fire @ jquery.js?cdv=261:3317
fireWith @ jquery.js?cdv=261:3447
fire @ jquery.js?cdv=261:3455
fire @ jquery.js?cdv=261:3317
fireWith @ jquery.js?cdv=261:3447
ready @ jquery.js?cdv=261:3920
completed @ jquery.js?cdv=261:3930`

**Expected behavior**

**Minimal reproduction of the problem with instructions**

[https://www.youtube.com/watch?v=lvZ2oE6qCG4]

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **2sxc version(s):** 10.28  
* **Browser:** [all ]
* **DNN:** [ 9.4.1 ] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Thanks - and great job with the helpful video. This is related to #2045, will be fixed tonight or tomorrow.

**Comment by michaelcunningham1974** [comment]
Thanks as always for your awesome response time. 

You guys need to offer a product so we can pay you for your work.

My employer won’t cover donations but if it was a product....

Thanks

**Comment by iJungleboy** [comment]
thanks for that ;). 

It's hard making a free product - but it's also hard to then make it partially free. We'll try to find ways to up-sell ;)
