### ISSUE TITLE
Translator permissions on public forms

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2058]
**I'm submitting a ...** 
[x] feature request

**...about**  
[x] Content Types or data management

**Current behavior**
Normal users are not able to translate in public forms.

**Minimal reproduction of the problem with instructions**
Create a template with public forms.
Give access to a non admin.
Give the user the DNN translator role.
Second language tab apears in the form, but it's greyed out.

**What is the motivation / use case for changing the behavior?**
Public forms is still a better way to allow user to create/edit content (the alternative is to give them DNN page edit permissions, which brings the persona bar.

* **2sxc version(s):** 10.28

**Comment by iJungleboy** [comment]
I think this is a different issue. To 99% the initial language has not been completed, so translate is not available. Could you check/verify. Otherwise I'll reopen.

**Comment by eXistenZe** [comment]
Not the case. But a clear cache and restart solved the issue. Weird stuff.
Thanks.
