### ISSUE TITLE
"@" character in template editor still breaks js syntax highlighting

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2065]
**I'm submitting a ...** 
[x] feature request

**...about** 
[x] edit experience / UI

**Current behavior**
This is not a new issue, but since you have a new template editor, perhaps this could receive some attention.
When you use a "@" inside the script section of the code, syntax highlight for JS stops.

**Expected behavior**
Syntax highlight for JS keeps working.

**Comment by iJungleboy** [comment]
Just some background: we're using the ace9 editor https://ace.c9.io/

So to enhance this, we would either have to enhance/fix the razor definition there, or replace the editor. Both are things that sound fairly difficult and time-consuming, so I don't assume this will be done any time soon.

**Comment by eXistenZe** [comment]
Do you think they could fix it if I reported it?

**Comment by iJungleboy** [comment]
I seriously don't know. It's a very popular product so I assume there is also quite some activity. I would certainly appreciate it if you tried it.

**Comment by iJungleboy** [comment]
Note: i'll tag this as low priority because this could take forever.

**Comment by iJungleboy** [comment]
ATM I don't see that this will get fixed any time soon, as we're relying on a third-party component. I'll close this for now.
