### ISSUE TITLE
Issues with multiple site alias

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2066]
**I'm submitting a ...** 
[x] not sure

**...about**  
[x] Content Types or data management

**Current behavior**
Ok... This is a weird one.

I have a site with two alias. They are not redirecting one another, they both access the same site.
I have an app in a page from that site. Both alias access the app fine.
The issue occurs when data is changed in one site: the other one does not match those changes, like they're now two versions of the database. If I manually restart the server, the changes propagate to the other site.

* **2sxc version(s):** 11
* **DNN:** [ 9.6 ]

**Comment by iJungleboy** [comment]
Hi Joao - I saw your post on FB. to 99% this is not a 2sxc issue. 2sxc uses a simple static cache to keep all the data together - and if you have 2 separate caches (which seems to be the case) it appears that you have to separate .net processes running, each with it's own cache. 
So this is either a misconfiguration of IIS, or something new/buggy in 9.6 - but I think even a bug in 9.6 couldn't cause this.
