### ISSUE TITLE
Edit Source-Code of app breaks if opened through App-Management of other app

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#2067]
**I'm submitting a ...** 
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] Razor templating

**Current behavior**
New code editor is awesome - but opening the code of another app (coming through App-Management) doesn't work, because it tries to use the wrong AppId.

**Please tell us about your environment:**

* **2sxc version(s):** 10.11

**Comment by PagnoDunadan** [comment]
Fixed
