### ISSUE TITLE
Any chance of restoring the site?

### ISSUE THREAD

**Issue by Tychodewaard** [2sic/2sxc#2072]
**I'm submitting a ...** 
[x] not sure
[x] cry for help

**...about**   
[x] DNN parts
[x] other / unknown

What I did: 
I upgraded DNN from 9.3.2 to 9.5, not aware that there was a page with 2SXC 9.32 on it. When I discovered that, I tried to uninstall 2SXC but this made the entire install crash. 

**Current behavior**

Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.

Source Error: 
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Assembly Load Trace: The following information can be helpful to determine why the assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' could not be loaded.

[FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.]
   DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication.Application_Start(Object sender, EventArgs eventArgs) +0

[HttpException (0x80004005): Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +10100435
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +123
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +181
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +228
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +314

[HttpException (0x80004005): Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +10080656
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +99
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +263
--

**Expected behavior**

1. Most importantly, is there a way to revive the website apart from restoring a backup ?
2. It would be a great thing if modules could be uninstalled without crashing the site

**Comment by iJungleboy** [comment]
This is caused by a DLL which 2sxc already had a long time ago, and later DNN added the same DLL in a newer version. 
So when you uninstalled 2sxc, it cleaned up it's DLLs (as it should) but didn't know that DNN had already added the same DLL in a newer version - so you're missing that DLL. 

Best compare your bin folder with the one of a normal DNN 9.5 and copy the missing Microsoft.* DLLs.

**Comment by Tychodewaard** [comment]
Thanks for putting me in the right direction.
Microsoft.Extensions.DependencyInjection.Abstractions.dll and Microsoft.Extensions.DependencyInjection.dll where the files that were missing.
