### ISSUE TITLE
Feat: Show how often a view or entity is used in the data model

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#2077]
**I'm submitting a ...** 
[x] feature request

**...about**   
[x] admin experience UI

**Current behavior**
It's impossible to know if views or entities are used anywhere. 

**Expected behavior**
Would be nice to see stats, or even a list of uses. The list of uses is hard to implement (but possible), but for now we would be happy to show some usage statistics. 

**Please tell us about your environment:**

* **2sxc version(s):** 11.01

**Comment by 10PoundGorilla-ChrisBehling** [comment]
Is it possible to also display which page specific entities or views are displaying on?

We currently use a SQL query to do this for us, which can be very useful when you are looking to add a new control to a content type and want to test out the display across all instances where the content lives.

**Comment by iJungleboy** [comment]
@10PoundGorilla-ChrisBehling we're actually working on that ;). 
So this issue is about views, but we're also considering doing the same for entities 🚀

**Comment by iJungleboy** [comment]
@10PoundGorilla-ChrisBehling We'll close this for now, because the views are ready and we'll release that on towel day ;). 
Please open another issue for the entities.

**Comment by jeremy-farrance** [comment]
So this accomplishes this StackOverflow inquiry from back in Jan?
https://stackoverflow.com/questions/59596426/how-can-i-get-a-list-of-pages-where-a-view-is-in-use

**Comment by iJungleboy** [comment]
yep 🚀
