### ISSUE TITLE
Error rendering template

### ISSUE THREAD

**Issue by skarpik** [2sic/2sxc#2079]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   

[x] other / unknown

**Current behavior**

**Error rendering template** (for Basic Content -> Image | Text)

DNN Version: v9.06.01 (new installation)
2SXC  Version: v11.01.00

**Expected behavior**

Should not encounter this error.

**Minimal reproduction of the problem with instructions**

In a new DNN v9.6.1 installation, I created a new page and added 2SXC content (Basic Content / Image | Text template) to a DNN panel (Xcillion theme /  NoTitle container) and I get the following error message:

Error: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot convert null to 'bool' because it is a non-nullable value type at CallSite.Target(Closure , CallSite , Object ) at ASP._Page_Portals_0_2sxc_Content_bs3_Content__ContentImage_cshtml.Execute() in d:\Websites\dnn-9-6-1\Website\Portals\0\2sxc\Content\bs3\Content\_ContentImage.cshtml:line 28 at System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) at System.Web.WebPages.WebPageBase.<>c__DisplayClass7.<RenderPageCore>b__6(TextWriter writer) at System.Web.WebPages.WebPageBase.Write(HelperResult result) at ASP._Page_Portals_0_2sxc_Content_bs3_Content__Image_text_cshtml.Execute() in d:\Websites\dnn-9-6-1\Website\Portals\0\2sxc\Content\bs3\Content\_Image text.cshtml:line 15 at System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) at ToSic.Sxc.Engines.RazorEngine.Render(TextWriter writer) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\Engines\Razor\RazorEngine.cs:line 84 at ToSic.Sxc.Engines.RazorEngine.RenderTemplate() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\Engines\Razor\RazorEngine.cs:line 94 at ToSic.Sxc.Engines.EngineBase.Render() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Engines\EngineBase.cs:line 147 at ToSic.Sxc.Blocks.BlockBuilder.Render() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Blocks\BlockBuilder_Render.cs:line 61

**What is the motivation / use case for changing the behavior?**

I was testing both DNN v9.6.1 and 2SXC v11.01.00 before employing them in a production website.

**Please tell us about your environment:**

* **2sxc version(s):** 11.1.0  
* **Browser:** [Chrome 81.0.4044.138 | Firefox 76.0.1 | Edge 81.0.416.72  ]
* **DNN:** [ 9.6.1 ] 
* **Language:** [ English ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
ok, this doesn't sound good. is this problem new in 9.6.1, or did the same template cause trouble in 9.5 or 9.6.0? because null != boolean sounds like a fairly standard problem that shouldn't have slipped past us...

**Comment by iJungleboy** [comment]
I can reproduce the issue 😟

**Comment by iJungleboy** [comment]
I found the problem - it's in the Bootstrap 3 templates only. 
So if you have a BS4 it won't matter, but we'll have to address this ASAP. Of course we can't modify templates that were already installed, but we have to fix the originals and guide people to the solution if they need it.

@SirAjZellweger Pls check & fix the content templates on BS3 ASAP

**Comment by iJungleboy** [comment]
New release created: https://github.com/2sic/2sxc-content-app/releases
testing/verifying on our side

@skarpik it should work now. You can verify this by creating a sub-portal and installing the content-templates again. 

To "fix" the previous installation, just copy the "bs3" folder from the new content templates and you should be good to go.

**Comment by skarpik** [comment]
Fixed the problem perfectly. Thanks!
