### ISSUE TITLE
Layout issues with link fields

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2080]
**I'm submitting a ...** 
[x] bug report

**...about**  
[x] Content Types or data management

**Current behavior**
![2sxclinks](https://user-images.githubusercontent.com/26518879/82098471-e9ffc580-96fc-11ea-8f8f-e68d8a4550e7.jpg)
This looks really bad. What's the point of the blue link?

* **2sxc version(s):** 11.1

**Comment by iJungleboy** [comment]
Thanks for this. The blue link can be clicked to see what's inside, as often the real like is `file:75` or something. 
I guess we haven't tried it with such a long name yet. 

We'll try to fix some time, but it won't have a high priority.

**Comment by PagnoDunadan** [comment]
Fixed. Floating URL will only be there for files and pages
