### ISSUE TITLE
Published / Draft for Entities not working

### ISSUE THREAD

**Issue by dustinp26** [2sic/2sxc#2093]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**

If you have an entity as a field type, if you edit it and change to draft it does not work and publishes it to all users. The RepoID is the same even though it shows the item in draft mode.

**Expected behavior**

It should only show the draft version to admin users or users with the role necessary to see draft content.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

So editors can preview content before the publish it in Community Edition.

**Please tell us about your environment:**

DNN 9.6.1, 2sxc latest release.
* **2sxc version(s):** 11.X.X  
Yes issue in most recent version 11
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
All Browsers
* **DNN:** [all | 7.4.2 | 8.X.X | 9.X.X ] 
9.6.1
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
I assume you have a model something like this

1. Parent object (which is published)
    1. Child objects (some of which are draft)

If this is your scenario, it's important to know that the published filter only applies to data which is pre-fetched / pre-processed for the view. So in this case, Parent objects would be filtered. But if you access the App.Data directly, no filter is automatically applied. The same is for child objects - if you access `Parent.SomeChildList` these are not auto-filtered. 

We're not doing this for various reasons - complexity and performance are of course an issue, but there is a greater risk that things would break unexpectedly in templates.

If this is your scenario, and you wish for this to be respected in the template, just use the `IsPublished` property in your `foreach` to decide if you want to show it. 

Pls feedback if this is what you needed.

**Comment by iJungleboy** [comment]
I'll close for now assuming it's fixed, otherwise feel free to ping, i'll reopen then.

**Comment by dustinp26** [comment]
I think so, basically want edtiors to see the Child objects when in draft mode, the actual draft version and if logged out the last published version yet I am not sure how to achieve that even in the foreach statement.

**Comment by iJungleboy** [comment]
Really, really simple. 

You have a foreach kind of like

```@foreach(var category of Something.Categories) {
   if(category.IsPublished) {
      //show
   }
}
