### ISSUE TITLE
WYSIWYG DNN or Advanced not working on Version 11.02

### ISSUE THREAD

**Issue by ufoloko** [2sic/2sxc#2094]
**I'm submitting a ...** 

[x] bug report

**...about** 
[x] admin experience UI

**Current behavior**
If you set a text field with WYSIWYG-DNN or WYSIWYG-Advanced, in edition you see TinyMCE Editor, is not possible to show other editors.

**Expected behavior**
You should be able to see WYSIWYG-DNN or WYSIWYG-Advanced fields if you set in a text field.

**Minimal reproduction of the problem with instructions**
Just add a text field and set WYSIWYG-DNN or WYSIWYG-Advanced, then try to add a item.

**Please tell us about your environment:**
Windows 2016 Server, IIS10

* **2sxc version(s):** 11.02.00  
* **Browser:** all
* **DNN:** 9.5.0
* **Language:** any

Just for your information, if you click alt when add or edit item, text field is showed as espected, problem is just with new interfaces

**Comment by iJungleboy** [comment]
This is related to #1845 - basically these field-types never really did anything, they were placeholders. Best switch to wysiwyg-default and you'll be fine.

**Comment by ufoloko** [comment]
Use case is when you have a blog and you have a field for blog contents, you need to add images, tables and some html content, in this case DNN wysiwyg editor is a little better than editor used for 2sxc. Some current user ask me for this, and in some cases needs to open another DNN editor, set text, copy html and then move html to 2sxc field, but i think is not a good practice. Thanks anyway

**Comment by iJungleboy** [comment]
@ufoloko Thanks for the feedback. 

BTW the tinyMCE does have tables, image-drag-drop etc. so I think it probably would do everything you need, but we hide most buttons by default. just hit the graduation-hat to see more.

**Comment by ufoloko** [comment]
Hi, sorry to refresh this issue again, I know just tinyMCE is supported for now, but is there any option to get WYSIWYG-DNN field working again. Just like I mentioned, I have a customer with a blog with very complex contents, and we tried to move from DNN editor to tinyMCE editor, with very bad results, for example, actually he can add additional information for a link, like custom css, alternative options, etc, without html edition, in tinyMCE that option is not available. Same for other elements.

Please confirm if i can achieve this. Im stopped to upgrade 2sxc version for this reason

Thanks

**Comment by iJungleboy** [comment]
As of now none of the volunteers working on 2sxc has this on the radar, so I assume nobody will tackle this for now. You have quite a few options though.

You might have missed some newer tinyMCE features

1. include Custom CSS 
2. Active the advanced toolbar by default on a specific type (like on your blog)

...or some of the newer custom input field features: 

1. you can create custom inputs - in which you could also integrate Dnn WYSIWYG yourself 
2. or customize a TinyMCE in such a way that all your needed features are enabled

...then of course you could 

1. contribute the feature to 2sxc
2. sponsor it
