### ISSUE TITLE
2sic sample Media Directory App is missing views?

### ISSUE THREAD

**Issue by VashJuan** [2sic/2sxc#2095]
**I'm submitting a ...** 
[x] bug report 

**...about**
[x] other / unknown

**Current behavior**
[**Sorry to put this here**, I asked at
https://stackoverflow.com/questions/61945871/there-are-no-views-in-the-2sic-app-media-directory-application-sample
10 days ago & am awaiting any comments.]

Download App-Media Directory 1.0.0.7 from https://2sxc.org/en/apps/app/media-directory-app-for-dnn-dotnetnuke.

It installs fine, but in Apps Management there are NO Views (or Queries or WebAPIs), and I believe I've seen references to List View and Press Release View.

**Expected behavior**
Are there not sample views for this? The Demo photos made it look like there was.

**Please tell us about your environment:**
Win 10 Pro Desktop with latest OS & 2SXC on DNN 9.1, English

**Comment by iJungleboy** [comment]
This is a very old app, but I believe it still works. 

My guess is that it hasn't been updated for such a long time, that the xml-schema is like 5-6 years old and you would need to import it with a 2sxc 8.x and re-export it for it to be importable in a newer 2sxc. I just did the import/export but didn't test on a newer 2sxc: 

[2sxcApp_MediaDirectory_01.08.00.zip](https://github.com/2sic/2sxc/files/4715531/2sxcApp_MediaDirectory_01.08.00.zip)

As it has no priority and hasn't been maintained in a long time, I recommend you look at it closely before you do anything ;).
