### ISSUE TITLE
Permissions dialog: simplify with dropdown to select users and groups

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2097]
**I'm submitting a ...** 
[x] feature request

**...about**
[x] Content Types or data management

**Current behavior**
Public forms require admin to set permissions for data access. Since all users can view, and only admins cam edit the page, this leaves content editors with only one choice: permissions by role or user.
The current setup requires the admin to manually query the database for users and roles ID and input the ints in a text fields, comma separated.

**Expected behavior**
2sxc has evolved so much since these beta feats where implemented, that jumping into a fully featured dropdown multiple selection seems a very small step.

**Comment by iJungleboy** [comment]
Here are the steps we would need to implement this done correctly:

1. Create two DataSources, one to provide user groups, one to to provide Users (I believe the second one exists)
1. Create a query which accesses both and merges the result
1. Change the input field to become a string-dropdown-from-query using that query

All in all I'm afraid it still almost 1 day of work done properly. So ATM not a priority, but we're open to contributions!

**Comment by iJungleboy** [comment]
Needs sponsoring, so added to #2107 and will close unless someone contributes or sponsors this.
