### ISSUE TITLE
Minor form improvements when adding new fields

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2101]
**I'm submitting a ...** 
[x] feature request

**...about*
[x] admin experience UI

**Current behavior**
This form as two issues that troubles me quite a few times.
![formsimp](https://user-images.githubusercontent.com/26518879/83905948-88120900-a75a-11ea-987a-79376b0a1827.jpg)

1. The save icon is hidden bellow the form. This makes me try clicking add (+) icon to save, which leads to 2.
2. When you click anywhere outside the form, it closes without saving without confirmation. This leads to heavy data loss.

**Expected behavior**
1. Save icon should always be visible.
2. When clicking outside the forma, ask to discard changes.

**Comment by PagnoDunadan** [comment]
Fixed. All similar dialogs will also have scrolling content in the middle.
![image](https://user-images.githubusercontent.com/7113033/87678794-a9afd880-c77b-11ea-8ab6-c31ef38f8449.png)

![image](https://user-images.githubusercontent.com/7113033/87678961-e11e8500-c77b-11ea-961e-d89fdd3f3077.png)
