### ISSUE TITLE
Reversed export import icons

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2102]
**I'm submitting a ...** 
[x] feature request

**...about**
[x] Content Types or data management

**Current behavior**
It may just be me, but aren't export-import icons reversed?

![icons](https://user-images.githubusercontent.com/26518879/83906504-9ad90d80-a75b-11ea-8161-477fa9c1bc0c.jpg)

**Comment by iJungleboy** [comment]
We had an internal discussion about these about 2 months ago - same reason, Basically we're using it as "export/download from the cloud " and "import/upload into the cloud". This is fairly common, but other people sometimes use them differently.
