### ISSUE TITLE
Feature Request: WYSIWYG Controls Configuration

### ISSUE THREAD

**Issue by 10PoundGorilla-ChrisBehling** [2sic/2sxc#2103]
**I'm submitting a ...**
[x] feature request

**...about**   
[x] edit experience / UI

**[Current behavior](https://www.dropbox.com/s/1mae3gbegkdgxru/WYSIWYG-Full.png?dl=0)**
Currently when you give a site edit/administrator the ability to edit content in a WYSIWYG editor, you have to give them access to controls like list items, and heading controls.

In many (I would argue 75%) of the cases we run into, we’d love to have the ability to [limit what controls they have access to](https://www.dropbox.com/s/nhugvr0bpd062xx/WYSIWYG-Slim.png?dl=0). Consider the following examples:

**[Example 1: Inline bold](https://www.dropbox.com/s/01383blu7emitmv/Example-1.png?dl=0)** 

In this example, there are effectively 3 options for allowing the end-user to make “Next Steps:” bold with the remaining “Save Time & Money” light.

- Require they input html markup (never ideal)
- Make this an entity control so they can add 2 text entities that allow them to input both text and font weight (multi-step process, not very user friendly)
- Give them a WYSIWYG editor and pray they don’t try adding a ul/ol or heading elements that completely blow up the design.

**[Example 2: Inline bold & font size adjustments](https://www.dropbox.com/s/p0jofkyvkv5cci6/Example-2.png?dl=0)**

This example is a bit more complex than the previous. In this example, we’d likely consider using the strong html attribute to control both the font size and weight with our CSS. With proper notes in the 2sxc UI this will be clear enough for the user as it is more stylistic than anything.

This example still suffers from the same problems as Example 1. We wouldn't force the user to put in html markup to achieve and manage this design. Also, managing 3 text entities to string them together in this instance is not user friendly at all.

**Expected behavior**
Have a few more controls in the WYSIWYG editor configuration to further limit which toolbar controls are available.

**What is the motivation / use case for changing the behavior?**
By providing a bit more flexibility to the WYSIWYG editor you can provide a better editing experience and reduce the chance for unintended content entry by the end-user.

The 2sxc WYSIWYG editor already has 2 controls for customization which allow you to control the editing experience. 1 for limiting the display of the code editor, and another for determining if the ui should open in a popup. If this could be expanded to control other input fields like heading, list items, documents, etc, it could provide much needed flexibility for content editing.

**Comment by iJungleboy** [comment]
You should be able to do all of this using custom input fields https://docs.2sxc.org/how-to/customize-edit-ux/input-fields.html

**Comment by 10PoundGorilla-ChrisBehling** [comment]
@iJungleboy, could you point me in the direction of the demo app for the custom input fields? I've been looking through the documentation and can't seem to find it, nor on the 2sxc app listings. I'd love to play around with this more.

**Comment by iJungleboy** [comment]
It's part of the tutorial app. latest release https://github.com/2sic/app-tutorial-razor/releases/tag/v11.02.01

**Comment by 10PoundGorilla-ChrisBehling** [comment]
@iJungleboy, I've been able to get the micro version implemented but for the life of me I can't get an additional version to have a middle-ground for the editing controls. 

Looking to implement:
`
    configureOptions(options) {
      options.plugins = "lists";
      options.toolbar = "undo redo | list | numlist bullist outdent indent";
      return options;
    }
`

The list controls will not build with or without the **options.plugins** declaration. Looking at /ToSIC_SexyContent/system/field-string-wysiwyg/index.js I see there is reference for the toolbar controls of numlist, bulllist but they still won't seem to build for me.

Could you provide any more insight on this?

**Comment by iJungleboy** [comment]
@10PoundGorilla-ChrisBehling glad you got it to work. 
Yes, always work with F12 open. 
Note also that you can open 2sxc dialogs with shift+click (from the page), and most dialogs use routing - so while you're testing you should be able to always just F5 and see the results immediately, because it will go back to the dialog which contains your custom field ;)
