### ISSUE TITLE
Needs Sponsoring

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#2107]
## Issues / Wishes needing Sponsoring

Many ideas and wishes must wait very long to be implemented because the people contributing to 2sxc (and EAV for that matter) are either volunteers picking their own priorites or someone is paying for them. A large part of the development is directly sponsored / paid for by [2sic](https://www.2sic.com) or by the customers of 2sic wishing for new features. 

For that matter, we must often take a wish / request and mark it as `needs contribution or sponsoring`. If someone contributes a solution we are glad to incorporate it into our code base - assuming the quality etc. is reasonable enough that we can maintain it in the future. But since most wishes don't come with a solution, we will comment and tag them, and then _close the issues_ since many of them won't find a sponsor any time soon. 

Here we will list most of these issues - in case someone would like to sponsor one of them. The numbers in brackets (#-#d) represent the estimated days to implement, test and deploy this feature. If you wish to sponsor something, please [contact us](https://2sxc.org/en/contact).

## Code Editor Wishes

1. Code editor should show snippets for all known content-types and fields #1596 (1d) 
1. Custom Snippets (not for sharing) #1770 (1-2d)

## Edit Dialog Wishes

1. Time only field #996 (0.5d)
1. Enhance Icon-Picker to support icons with Glyphs like Material Icons #2105
1. Fields with unique content #1783 (ca. 1d)

## Image and Files Wishes (ADAM)

1. Convert and resize images as they are uploaded #1546 (2-3d)
1. Set a hotspot area / crop-area on an image #1692 (ca. 1-2d)
1. Determine file sorting order in any ADAM folder #1692 (ca. 1d)
1. Sometimes ADAM causes error because it tries to create a folder which already exists #1656 (0.5d)

## In-Page Editing Wishes

1. In-Page Toolbar - hide "move down" button on last item #882  (ca. 0.5d)

## App Admin Wishes

1. Clone /duplicate a view with all the settings and the file associated with it #1556 (0.5d)
1. Permission dialog - enhance so it's easier to use #2097 (1d)
1. Improve entity/item history in many ways an allow partial restore #1984 (1-3d)
1. Admin - show data of entities in various languages or even with translation progress #1772 (2-3d)
1. View-icon should be assigned to view-data, not auto-pickup based on file name #1724 (0.5d)

## Unsorted Wishes

1. Event notifications on data changes (like for sending mails) #965 (2-3d)
1. Mass delete all items/entities #1436 (2-4h)
1. Enhance export to also export un-published items #1466 (1d)
1. Support DNN installations using custom object qualifier #1366 (2-4d)
1. Export certain items directly from the in-page toolbar #1591 (1-2d)
1. Create API for mass-changes of data in the EAV #1717 (3-5d)
1. Fully support additional cloud-file providers #1851 (1-3d)

**Comment by iJungleboy** [comment]
Will close to make it go away from open list of tasks.

**Comment by jeremy-farrance** [comment]
The 1st item above under App Admin wishes is linked to the wrong issue, should 1558, not 1556.
