### ISSUE TITLE
Error: System.Exception: Data is missing

### ISSUE THREAD

**Issue by webshareinfo** [2sic/2sxc#2109]
**I'm submitting a ...** 
[x] bug report => similar issue #1266 however there was no resolution posted

**...about**   
[x] Content Types or data management

**Current behavior**
all modules on portal produce an error - Error: System.Exception: Data is missing - usually when a site is copied but the content / apps have not been imported yet - check 2sxc.org/help?tag=export-import 

**Expected behavior**
This is an old site which has been working fine for many years and has not had any modules or dnn updates in a long time

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
unknown as far as we know no-one has updated the data on this site for a week or more - no exports have been done or new setup 

**Please tell us about your environment:**
Win server 2012

* **2sxc version(s):** 8.4.8  
* **Browser:** [all ]
* **DNN:** [ 7.4.2  ] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**
this must be a simple data issue as another portal in same dnn install with 2sxc on it works fine,however I cannot diagnose the data issue as the structure is convoluted - its not really possible to do any upgrades to this site without a huge undertaking - it has been fine for years this really happened out of the blue and the customer hasnt a clue what triggered it

**Comment by iJungleboy** [comment]
This seems fairly unique, and doesn't give us anything to go on. 

Basically I would assume that this cannot be resolved through github issues, I believe you'll need support for this - ca. 4h. Pls check https://2sxc.org/en/contact for details.

**Comment by webshareinfo** [comment]
do you have the sql data structure documented anywhere? This has to be something ultra simple as to why its not picking up any of the data for this portal only - if it has eaten all the data for this portal is gone then little point in continuing on with the product

**Comment by iJungleboy** [comment]
There is no official documentation for the structure, but it's fairly simple. 

I just thought of something: probably the Zone to Portal map is broken. Basically 2sxc has Zones and the IDs are not the same as the portal, so there is a reference in `dbo.PortalSettings` for each portal with a key called `ToSIC_SexyContent_ZoneID`. That points to a Zone. 

2sxc will create a zone for each portal and then set this number. But I do remember that once there was a DNN caching bug, where DNN would not have the PortalSettings loaded, and 2sxc believed it needed to create a zone. If this happens, a new zone is created and the setting is stored again - pointing to a now empty Zone. 

So I think if you check these IDs you'll find your culprit ;)

**Comment by iJungleboy** [comment]
I just added some minimal documentation about this https://docs.2sxc.org/specs/data/index.html

**Comment by webshareinfo** [comment]
that fixed it
thanks
