### ISSUE TITLE
Installing 2sxc 11.02.00

### ISSUE THREAD

**Issue by Sorencys** [2sic/2sxc#2111]
**I'm submitting a ...** 
[x] bug report => search github for a similar issue before submitting 

**...about** 
[x] DNN parts
[x] other / unknown

**Current behavior**
When installing the 2sxc 11.02.00 release on our website it gives us an error which is in the attachments since it is huge!
We are not sure but it gives an error that the table already exists.
Maybe there was an old version of 2sxc (not visible in Modules) with some leftover tables or something.
But I would expect that I can just install 11.02.00 without any problems.

**Expected behavior**
Installing the module without any problems.

**Minimal reproduction of the problem with instructions**
Go to extentions > Wizard > Select the 11.02.00 installation zip file.

**What is the motivation / use case for changing the behavior?**
We would love to use 2sxc on this website.
But it is such a big installation (66 portals) that we can't just make a new install and place over the websites.

* **2sxc version(s):** 11.02.00 
* **Browser:** all
* **DNN:**  8.0.4 
* **Language:** [any/all ]

**Anything you would like to add**
[SQL error by install.docx](https://github.com/2sic/2sxc/files/4813090/SQL.error.by.install.docx)

**Comment by Sorencys** [comment]
The error later also includes lines like "There is already a newer version of this file" but I am installing the newest release?

**Comment by iJungleboy** [comment]
@Sorencys This is almost certainly a support request. These things should always be posted on stackoverflow with keyword 2sxc. Otherwise future users won't find it. 

Pls post it there and drop the link here, so I'll look at it then.
