### ISSUE TITLE
Razor Snippet for List Presentation Fields Uses ListContent.Presentation instead of Header.Presentation

### ISSUE THREAD

**Issue by joshgk00** [2sic/2sxc#2112]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] Razor templating

**Current behavior**

When you're working with a list and you use the snippets to insert the Presentation fields for the list, the snippets are using the depricated ListContent instead of Header object, which causes errors in the template display. See video below

**Expected behavior**

The snippet should use Header.Presentation.FIELD_NAME

**Minimal reproduction of the problem with instructions**

https://www.screencast.com/t/lyn1pEnu

**What is the motivation / use case for changing the behavior?**

Causes confusion to the developer/programmer. The predefined snippets should insert the correct object

**Please tell us about your environment:**

Windows Server 2012, SQL Server 2016

* **2sxc version(s):** 11.2.0  
* **Browser:** [all ]
* **DNN:** [9.6.1 ] 
* **Language:** [any]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Thanks for the video, that helped a lot. Love these kinds of issues 👍
