### ISSUE TITLE
Problem with App Export/Import

### ISSUE THREAD

**Issue by jncraig** [2sic/2sxc#2114]
**I'm submitting a ...** 
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] admin experience UI
[x] DNN parts
[x] other / unknown

**Current behavior**

DNN 9.6.1 2sxc 11.2.0

I have a dev and production site that are (more or less) copies of one another.

I created a 2sxc app on the dev site and built some pages. I need to move the pages and the app to the production site.

    I exported the app from the dev site and imported it into the production site with no problems.
    I exported (with content) pages containing the app from the dev site, and then transferred the page templates to the production site.
    I then created new pages on the production site specifying the appropriate template for the page.
    The new page(s) get created, with 2sxc apps in the correct places, but I get messages on the screen saying that the data hasn't been initialize or is empty.
    I can delete the app, add a new app, specify the app template and manually add the data (that came over with the app) and all is fine. Except that this is a pain having to manually re-create lists of content items.

If I use an page template exported on the dev site to create a new page page on the dev site, the new page is created perfectly.

So, I think that this is a problem with the app export/import process.

**Expected behavior**

Page should be created without error on production site.

**Minimal reproduction of the problem with instructions**

I outlined the problem above.  I can provide files, examples, access to site if needed.

**What is the motivation / use case for changing the behavior?**

Need to move App and pages that use the app from dev to prod.  The App moves "fine,"  Created a page with a page template has errors, but not if done on the dev site.

**Please tell us about your environment:**

* **2sxc version(s):** 11.2.0  (also on previous version of 2sxc -- I upgraded to be sure.
* **Browser:** [all | 
* **DNN:**  9.6.1 
* **Language:** English (others not in use)

**Anything you would like to add**

Nope, other than to heap praise on 2sxc.

**Comment by iJungleboy** [comment]
Hi @jncraig 

## Basics

So before we start, I need to make sure you understand the core concepts which differentiate data from content. 

1. Data is just data - your code can sort it etc. and just work with it like records
1. Content is data which was manually placed on a page, in the order the content-editor wanted it in. This bundle of items and their order is stored in a `ContentBlock`

Now before we continue, I recommend you read https://docs.2sxc.org/specs/content/index.html and https://docs.2sxc.org/specs/content/dnn-integration.html which explain how DNN modules point to a content block. 

## Your Issue Re-Explained

From what I understand I believe that your setup is using content. 

1. So in your source system DNN1 you had a module M1 pointing to an App A1 containing a ContentBlock CB1. 
1. You then exported A1 - probably without checking "include ContentBlocks" in the App-Export, which would include CB1
1. reimported it on DNN2. 
1. You created a new Module M2 - this doesn't have a content block yet, so it created a new one CB2. 
1. Now you were stuck with manually recreating the list of items in the new CB2

Is that about right? 

## Understanding Site Export-Import

If you are migrating a site, then you would export the site-template which would still include M1. M1 would still point to App1 and CB1 but wouldn't find it - and you would then see a message that it couldn't find it yet. In this scenario, you would then export A1 _with the checkbox to include ContentBlocks_ and import it in DNN2 - and everything magically works. This is also explained here: https://2sxc.org/en/learn/copy-duplicate-an-entire-site

## Using this for your own setup

If you plan on doing this export/import of the app multiple times, I suggest that you 

1. First of all always export the app with the _ContentBlocks_ included. 
1. On DNN2 add an M2 (which creates a CB2-refence) and then **manually** go to the DNN sql table and replace the _ModuleSetting_ of this new module to point to the original (now re-imported) content-block CB1. This is a GUID that you could look up on the source system.

Once you do this, re-importing the app many times will always point to that original CB1, and everything should work ;)

**Comment by jncraig** [comment]
Daniel,

Thank you for the detailed explanation.

If I understand correctly (and I will read the items you referenced) and
with reference to this image from the Export window:

[image: image.png]
what you are saying is that I need to check the first box: "Include all
content groups ..."

Is that the correct understanding?

Thanks so much.

Joe

**Comment by iJungleboy** [comment]
yep.
