### ISSUE TITLE
Add existing button (toolbar) doesn't work

### ISSUE THREAD

**Issue by perezandres** [2sic/2sxc#2121]
I'm submitting a bug report about edit experience / UI

**Current behavior**
When clicking Add existing button on toolbar, I see the Replace Content Item dialog and, in fact, it replaces item.
I detected it on version 11.2.0 and I have waited until 11.3.0, but the issue is still there.

**Expected behavior**
I guess it should let me choose an existing item, and add them as a new content item to module.

* **2sxc version(s):** 11.2.0 - 11.3.0
* **Browser:** all (i doesn't seem to be browser related)
* **DNN:** 9.6.1
* **Language:** any

**Comment by iJungleboy** [comment]
finally fixed, sorry for letting you wait so long.

**Comment by perezandres** [comment]
![image](https://user-images.githubusercontent.com/6237180/93719786-1c2aa380-fb85-11ea-855e-8e47438afd0e.png)
Hi Daniel,
Now the button is working, and it adds an item from the list of exixting ones, but the title and text in the dialog are the same as when clicking the Replace Content Item button, and this is quite confusing ;-)

**Comment by iJungleboy** [comment]
thx, we'll enhance this.
