### ISSUE TITLE
Can't upload image with ADAM

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#2125]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI

**Current behavior**
I want to upload an image and I get that error:

 _Upload failed because: subfolder adam/Content/kV4T4sw6bUaKfU_-xD1tHg/Bild/Bilder/not found_

* **2sxc version(s):** 11.3.0 (It worked before with 11.x)

**Comment by SCullman** [comment]
Workaround: It still works in the old UI; just press the ALT-Key when you click on edit.

**Comment by ajplopez** [comment]
I just upgraded a site from 10.25.2 to 11.3.0. I noticed that I get the same uploader failed error on portals that have very old (circa 2016) content types where I set the path for the image (in the days that I had images in folders under Site Assets). So I edited the field in the content type to remove the "Paths" field.

I did this by going to my content type, editing the field, scrolling to the bottom of the modal and expanding the "Advaned Settings" and removing the content of the "Paths"

Hope that helps.

![Screen Shot 2020-07-13 at 3 04 33 PM](https://user-images.githubusercontent.com/8751936/87358245-407d5a80-c51a-11ea-842e-b45f5af017d9.png)

**Comment by PagnoDunadan** [comment]
ADAM was rewritten in 11.03. to improve performance and a bug with Paths slipped through. Paths should be applied only if using Portal Root, but in 11.03. it's applied when using ADAM only for a field too. It's fixed and will be in the next version.
