### ISSUE TITLE
2sxc v11.03.00 fails on clean DNN 9.6.2 install

### ISSUE THREAD

**Issue by joshgk00** [2sic/2sxc#2126]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   

[x] DNN parts

**Current behavior**

Installed DNN 9.6.2 using nvQuickSite. Installed the 11.03.00 of 2sxc and the install fails citing v9 is not present
**Expected behavior**

2sxc v11.03.00 would install cleanly with no errors on a fresh install of DNN 9.6.2
**Minimal reproduction of the problem with instructions**

1. Use nvQuickSite to setup a clean install of DNN 9.6.2
2. Try to install the module 2sxc v11.03.00
Here's a screencast of what happened
https://www.screencast.com/t/FPDtOlidQNN

**What is the motivation / use case for changing the behavior?**

If I want to create a new site and use the latest version of 2sxc I am currently not able to

**Please tell us about your environment:**

Windows 10 
IIS 10
.NET 4.7.2
SQL 2017 Developer Edition

* **2sxc version(s):** 11.03.00  
* **Browser:** [all ]
* **DNN:** [9.6.1 | 9.6.2 ] 
* **Language:** [any/all]

**Anything you would like to add**

**Comment by bash862** [comment]
I have the same error of @joshgk00 during the installation of 2sxc v11.03.00 in the same environment (my log of installation is the same of the video)

**Comment by bash862** [comment]
I tried with an environment with only a clean installation of DNN 9.6.2 (without nvQuickTheme_2.2.0) and have same problem. 
There are some compatibility problems with 2sxc v11.03.00 and DNN 9.6.2?

**Comment by david-poindexter** [comment]
I can confirm this also happens on a clean install of DNN 9.6.1.

**Comment by david-poindexter** [comment]
Now I can't install 11.02.00 on the site, as there are remnants of the attempted 11.03.00 installation leftover.  Now we have to start over on this new site, which will cost a couple of hours. ☹️

**Comment by david-poindexter** [comment]
Okay, it was a bit painful, but I finally got 11.02.00 installed without starting over.  I'll post my steps here just in case it is able to help someone else.

### Step 1
Uninstall (check "Delete files") the following two leftover Libraries:
- ToSic.Razor
- ToSIC_Imazen_ImageResizer

### Step 2
Manually delete ALL "ToSIC_" prefixed database tables

### Step 3
Manually delete ALL "ToSIC_" prefixed database stored procedures

### Step 4
Install 11.02.00

**Comment by iJungleboy** [comment]
I can reproduce - something with SQL isn't working as expected. 
Installing 2sxc 10.30 works, but 11.02 /11.03 fails. 
Upgrading to 11.02 from 10.30 works. 

It seems an initial check to verify something is or isn't installed - working on it.

**Comment by iJungleboy** [comment]
I believe I found the cause - but don't yet know how to fix it. 

Reason is that 2sxc previously (incorrectly) said it included the `imageresizer.dll` - which is actually included in another package. So the assignment was wrong. This caused DNN to assume that imageresizer.dll also had a very high version number (11+) when it actually was V4. 

To correct this, we added a section like this: 
```
        <!-- 
          2020-06 2dm: Previously 2sxc also included the copy-image-resizer 
          which causes issues on update, because DNN thinks that image resizer was included with the 
          version which 2sxc has, like V9 or V10. That's why we must say we don't use it any more
        -->
        <component type="Assembly">
          <assemblies>
            <assembly action="UnRegister">
              <name>ImageResizer.dll</name>
            </assembly>
          </assemblies>
        </component>
```
It appears that this is also run on first-install scenarios, and causes DNN to believe that the entire installation failed :(

working on it...

**Comment by iJungleboy** [comment]
I implemented a workaround. 

2sxc will now pretend to need the file, then unregister it again. Unsexy, but necssary :(. 

Here's a test pre-release for this - pls test / verify - thx! 
[2sic_2SexyContent_11.03.01_Install.zip](https://github.com/2sic/2sxc/files/4982115/2sic_2SexyContent_11.03.01_Install.zip)
