### ISSUE TITLE
Wish: UI toggles for setting up simple parent-child relationship with list and details views (similar to "Enable List" toggles)

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2128]
**I'm submitting a ...** 
[x] Wish Item

**...about**  
[x] admin experience UI
[x] Content Types or data management

**Current behavior**

I want to set up a listing of items which then the user can click on and it opens a new, friendly URL that loads a different template with the full details. So like this:

mywebsite.com/careers > Listing
mywebsite.com/careers/dairy-farmer > details view

Based on the demo videos I've seen on YouTube, to set up a simple parent-child relationship in an App module seems more complicated than it should be.

**Expected behavior**

I wish there a much simpler way of setting up parent-child relationships for content in 2sxc (Content or App). In the same way you can enable "list" mode on a template, it would be nice if there was a way to enable parent-child. So I could create a content type and then have two templates associated to it: listing and details. And it would be good, too, if it knew how to handle the URLs out of the box and display the content accordingly.

**Minimal reproduction of the problem with instructions**
N/A

**What is the motivation / use case for changing the behavior?**

I feel like setting up list and details modules should be way simpler for the developer. In the same way that I can set up "Enable List" with a toggle and some settings, it would be nice if I can set up a parent-child relationship through the admin UI easily.

**Please tell us about your environment:**

All

* **2sxc version(s):** all
* **Browser:** [all ]
* **DNN:** [all  ] 
* **Language:** [any/all ]

**Anything you would like to add**

Here's my question on Stackoverflow: 

https://stackoverflow.com/questions/62942865/how-can-i-set-up-a-super-simple-listing-and-details-module-that-uses-simple-urls

Here's the YouTube video I tried following: 

https://www.youtube.com/watch?v=RtmOYvaeJpo

**Comment by eXistenZe** [comment]
List and details is a more advanced setup than a simple button toggle. An app can have dozens of detail views triggered by different links or querystrings. Or even multiple lists in a single view.

However, details views could be simplified if we could bypass the needed query. Just selecting the content type and the linked field should be enough (the query string is already set).

**Comment by ajplopez** [comment]
@eXistenZe I agree that an app _could_ be very complicated. My thinking is that in the same way that a "list" is a common thing, a "list and details" is also a pretty common starting point for all things we build. Anytime we can lower the bar and make it easier (and faster) for developers to set up, the better.

PS. Thanks for the demo app - looks good so far and I'll be digging into it!

**Comment by eXistenZe** [comment]
For basic users, the best approach right now is to save a demo, and then import it whenever you need. List and details is just one of thousands of possible applications of 2sxc. For intermediate users it takes like 15 minutes to setup (I took like 20 mins to setup the demo I sent).

If lots and lots of people asked for a one click solution (perhaps with a new module like the content and app ones), who knows what the team might do :)

But it's still very situational.

**Comment by iJungleboy** [comment]
As of now I don't think we'll change much. All the alternatives I can think of don't reduce complexity, as the details page must still have some kind of parameter to detect which id to show, and there is also no clear way to determine which data should the be filtered by this ID. 

So for now I don't think we'll change anything, and I'll close this task.
