### ISSUE TITLE
Edit Dialog (New UI) Shows wrong field when field has ContentBlocks

### ISSUE THREAD

**Issue by joshgk00** [2sic/2sxc#2129]
**I'm submitting a ...** 
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI

**Current behavior**
When you setup a content type that has a field that uses ContentBlocks inside the WYSIWYG editor, clicking the Edit button in the UI it shows the wrong field for editing and therefore, you're unable to edit the HTML. The only way to work around this is to use the old Edit UI or go through the Admin UI and edit the individual content item (see screencast)

**Expected behavior**
When you have a content type that uses ContentBlocks, when clicking the edit button in the new Edit UI it should allow you to edit the HTML source in the WYSIWYG editor

**Minimal reproduction of the problem with instructions**
I've attached a screencast that shows the bug. 
https://www.screencast.com/t/fP8CuL16tWR

**What is the motivation / use case for changing the behavior?**
This fix would create a better edit experience and would be a more streamlined approach to editing the content

**Please tell us about your environment:**

Windows server 2012
IIS 10
SQL Web 2017

* **2sxc version(s):** 11.00.03
* **Browser:** [all]
* **DNN:** [all] 
* **Language:** [any/all]

**Comment by iJungleboy** [comment]
Thanks for the Video - this helps. The problem seems to be that the field is opening the dialog of another field. 

@PagnoDunadan it seems that the wysiwyg-preview is opening the wrong dialog - specifically of the second entity in the form, not the first one. Can you please check and maybe fix?

**Comment by PagnoDunadan** [comment]
Nice catch! Fixed in next release 🙂
