### ISSUE TITLE
No folders showing in Image Manager

### ISSUE THREAD

**Issue by renderfarmer** [2sic/2sxc#2130]
**I'm submitting a ...** 
[x] bug report

**...about**
[x] edit experience / UI

**Current behavior**
After updating to 2SXC 11.3.0 we cannot change folders anymore when using the image/link fields file browser (not Adam). No folders are visible, also not able to see folders that are created inside the edit window.

**Expected behavior**
Should be able to change folders and access subfolders. 

**Minimal reproduction of the problem with instructions**
This is not a new DNN install. It used to be a DNN 8 that has been upgraded and 2SXC had also been updated several times. Had no problems in version 11.2.0

**What is the motivation / use case for changing the behavior?**
Select Image from specific file folder.

**Please tell us about your environment:**
...

* **2sxc version(s):** 11.3.0 
* **Browser:** [ Chrome 84.0.4147.89 ]
* **DNN:** [ 9.6.1 ] 
* **Language:** [German]

**Comment by iJungleboy** [comment]
You may still have a setting in the configuration which was ignored for a long time (by accident) and is re-implemented. Pls check issue https://github.com/2sic/2sxc/issues/2125 and see if your problem is solved. Otherwise pls add some more info - ideally an example link of the server API call (with F12) trying to request the files.

**Comment by PagnoDunadan** [comment]
I can confirm this bug. Folders were filtered out in Image Manager in 11.03. I've already fixed this like 2 days after 11.03. was released so next update will have the fix.

**Comment by renderfarmer** [comment]
Still have the problem in some DNNs that I can't see/navigate into subfolders in 11.07.03 - on others this problem is not appearing. Any ideas what could be the reason behind this?

**Comment by iJungleboy** [comment]
Did you check the configuration of the field? because that may limit subfolders to 1 or 0, not allowing subfolders.

**Comment by renderfarmer** [comment]
Funny, I just solved the issue by removing the custom file extensions: *.jpg,*.bmp,*.png,*.gif,*.svg
I didn't think this would affect folders from being shown.
