### ISSUE TITLE
2SXC don't work anymore with Open Url Rewriter

### ISSUE THREAD

**Issue by Scippy** [2sic/2sxc#2144]
With latest DNN 9.6.2 and 2SXC 11.04.00 I'm no more able to add Template/Layout to the Module content.
The problem comes from the fact that I use it with [Open Url Rewriter Module](https://github.com/sachatrauwaen/OpenUrlRewriter)
Everything worked well until DNN 8.0.4 with 2SXC 10.25.2 also with Open Url Rewriter
Is there any chance to make it work again? Or I must find the solution on Open Url Rewriter Module update?
thanks

**Comment by iJungleboy** [comment]
I can't figure out what would cause this. could you add more information, screenshots, maybe redirected urls or something for clarity?

**Comment by Scippy** [comment]
Hi Daniel, the problem is using Open Url Rewriter, this is [latest release 1.4.4](https://github.com/sachatrauwaen/OpenUrlRewriter/releases/tag/v144) and here [my branch](https://github.com/Scippy/OpenUrlRewriter) to make compatible with latest DNN releases
But with latest 2SXC release and DNN 9.6.2 something is not working, is no more possible to add a new 2SXC Template/Layout.
Looking at ethernet request I can see a 404 resource not found, but I think to solve it we must search on OpenUrlRewriter module.
![Screenshot_1](https://user-images.githubusercontent.com/16607338/89633415-1c583380-d8a4-11ea-9d32-1ccd515425e4.png)

**Comment by iJungleboy** [comment]
thx. Pls keep searching and keep us posted. 

I suggest you also review the IIS logs - usually you can see how the rewritten request arrived. 

Pls also check if other api calls fail, there is probably a pattern.

**Comment by Scippy** [comment]
Thanks Daniel, yes the problem was rewrite rule for api calls.
I've fixed it on [my fork](https://github.com/Scippy/OpenUrlRewriter) of Open Url Provider

**Comment by iJungleboy** [comment]
@Scippy thx! Could you maybe coordinate with @sachatrauwaen what/why you had to fix things, so he can update the original?
