### ISSUE TITLE
WYSIWYG + HTML Source

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#2147]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI

**Current behavior**
There is no way to edit the source of a text field.
![image](https://user-images.githubusercontent.com/5693190/90250609-9b1d1580-de3c-11ea-8dbc-aff17aec1009.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/5693190/90250528-732db200-de3c-11ea-8136-c7ab04352aac.png)

**What is the motivation/use case for changing the behavior?**
Normally we enter content in a structured and uniform form. Now, we are not always satisfied with the result, so we also allow the placing of free text as an alternative and optimize locally. For this, we also have to edit to the HTML source.

A formating option would be overkill.

**Please tell us about your environment:**
* **2sxc version(s):** 11.4.0

**Anything you would like to add**
I would expect that I can switch between different WYSIWYG types.
Currently `WYSIWYG editor (default)`, `WYSIWYG fill (not recommended)`, `WYSIWYG - DNN Standard`, and `WYSIWYG Tiny MCE` behave all the same.

**Comment by iJungleboy** [comment]
This is already possible 😊

If you take the default editor, and set the settings to inline, these buttons can be activated/deactivated easily. 

This is the default
![image](https://user-images.githubusercontent.com/5321186/90258382-c148b280-de48-11ea-93c9-37f0c156a715.png)

If you then set these settings:
![image](https://user-images.githubusercontent.com/5321186/90258468-eb01d980-de48-11ea-8318-6634f886fb78.png)

You get this
![image](https://user-images.githubusercontent.com/5321186/90258495-f3f2ab00-de48-11ea-8396-3200c45d46e0.png)

**Comment by SCullman** [comment]
@iJungleboy, thank you. 
My biggest problem was to find the settings dialog in the new UI. It is confusing that rename is behind the gear wheel, but the settings are available by clicking on the name. Should be the other way.

**Comment by iJungleboy** [comment]
I don't understand the wheel / name which should be reversed. Can you give me a screenshot?

**Comment by SCullman** [comment]
![image](https://user-images.githubusercontent.com/5693190/90409246-387c8180-e0a9-11ea-9f17-ef2bd0ab90ec.png)
