### ISSUE TITLE
Nested Content not working in 11.4

### ISSUE THREAD

**Issue by e1-sistemi** [2sic/2sxc#2152]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] other / unknown

**Current behavior**

When I try to add nested content, I get error: "Bad Request: Object reference not set to an instance of an object"
If I examine specific view in edit mode, I can see few (no title, ID) elements in Nested Content group, but they are not presented or editable.

**Expected behavior**

I had version 11.2 which was working as expected. Test upgrade to 11.3 - also OK. New content items would be added and all edit functionality for NestedContent available (add, delete, edit).

**Please tell us about your environment:**

Windows, VSCode, npm

* **2sxc version(s):** 11.4.0  
* **DNN:** [8.X.X | 9.X.X ] 
* **Language:** [any/all]

**Comment by iJungleboy** [comment]
could you provide a short video, just to make sure we're talking about the same thing?

**Comment by e1-sistemi** [comment]
Hi Daniel, here it is: https://youtu.be/ofDAesr1B-4

**Comment by iJungleboy** [comment]
thx, I'll check

**Comment by iJungleboy** [comment]
I tried the accordion app https://2sxc.org/en/apps/app/accordion-v3-for-2sxc and couldn't reproduce your issue.

Could you test with that app to verify that this is an issue?

**Comment by iJungleboy** [comment]
ping @e1-sistemi

**Comment by e1-sistemi** [comment]
Sorry for not responding sooner @iJungleboy 
I tried the accordion app you mentioned and I get exactly the same error as before.

**Comment by iJungleboy** [comment]
Here's a pre-release of the latest 2sxc - I don't have any problems  -but a co-worker who had a similar issue on an 11.04 said it went away with this release. could you check? pls don't use on production yet
[2sic_2SexyContent_11.05.01_Install.zip](https://github.com/2sic/2sxc/files/5218167/2sic_2SexyContent_11.05.01_Install.zip)

**Comment by e1-sistemi** [comment]
I confirm issue is gone. Both accordion application and my test app worked with no problem!
