### ISSUE TITLE
File manager doesn't show folders after stabilization update

### ISSUE THREAD

**Issue by kieran23101** [2sic/2sxc#2170]
**I'm submitting a ...** 

[x] bug report

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management

**Current behavior**

After updating to the newest update from today called "Stabilization update" the adam file manager seems to create folders correctly however the folders are not shown in the editor.

**Expected behavior**

Beforehand this worked and the folders would be listed and you could navigate through folders and upload an image and select it.

**Minimal reproduction of the problem with instructions**

Install the new update from today (18/09/2020) and then try to upload an image into a folder that is not the root "/portals/0" folder

**Please tell us about your environment:**

* **2sxc version(s):** 11.0.6  
* **Browser:** all
* **DNN:** 9.6.2
* **Language:** English

**Comment by iJungleboy** [comment]
@kieran23101 thanks for this issue, I'll check ASAP :)

**Comment by iJungleboy** [comment]
Could you add just a bit of more infos - is it in ADAM or the template editor where you ran into problems?

**Comment by kieran23101** [comment]
It is in ADAM, when you click "..." and then click "Image Manager" or "File Manager" :D

**Comment by iJungleboy** [comment]
Thx, can reproduce. Working on it...

**Comment by kieran23101** [comment]
Perfecto, thank you.

I'll keep an eye out for the update so I can update my website!

**Comment by iJungleboy** [comment]
Fixed, will release 11.06.01 in ca. 1 hour ;)

**Comment by iJungleboy** [comment]
released :)

**Comment by kieran23101** [comment]
The release doesnt show for me just yet, thank you for the fast fix though!

**Comment by iJungleboy** [comment]
sorry, was draft 🤦‍♂️
