### ISSUE TITLE
Update from 11.04 to 11.06.1 gives 500 error on DNN 9.6.2

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2174]
**I'm submitting a ...** 

[x] bug report 

**...about** 
[x] other / unknown

**Current behavior**
Update from 11.04 to 11.06.1.
Immediatly got a 500 error after the restart.
Even with custom errors off, I get no error message.
No errors on portal logs os IIS.

**Expected behavior**
Update complete.

**Anything you would like to add**
Seems to be a web.config misconfig.
Are there any potential breaking changes on dependencies or alikes?

**Comment by eXistenZe** [comment]
Nevermind.
Thousands of "Upgraded by 2SexyContent" comments gave a 500.19 "Cannot read configuration file because it exceeds the maximum file size".

Perhaps the install could verify if the line actually needs replacement, since most times it's actually the same.

**Comment by iJungleboy** [comment]
thx.
Yes, this sucks, but ATM we just don't have the resources to address this. It's tricky, because it relies on DNN internal modifications of the web.config.
