### ISSUE TITLE
Content-Type Fields - When Data Type Empty is set to Not Visible, it still shows up

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2179]
I'm submitting a bug report about edit experience / UI and admin experience UI as well as Content Types.
 
To quickly understand and reproduce this, use the Content App, Locations. Edit Fields, at the bottom change both the label and field - Directions and LabelDirections - so the UI Settings are Invisible. When you go back and edit the Content Items, the "label" (Directions field of type Empty) still shows.

**Expected behavior**
Invisible means it should not appear in the record editing form.

2sxc v11.6.1, DNN 9.07.02
![Mnar7NDP4d](https://user-images.githubusercontent.com/653301/94280622-3a8cf800-ff13-11ea-8bc8-aeb2ac215622.gif)

**Comment by iJungleboy** [comment]
@PagnoDunadan seems that groups don't respect visible/invisible. pls check
