### ISSUE TITLE
Can't create new out-connections (button doesn't seem to work)

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#218]
this button should create new streams, but it doesn't

![image](https://cloud.githubusercontent.com/assets/5321186/7417151/6705d218-ef64-11e4-81ee-2a7040a07707.png)

**Comment by BeniGemperle** [comment]
Maybe because of different version of AngularJS

**Comment by BeniGemperle** [comment]
Seems to be a browser issue only in Chrome on Daniel's computer.
