### ISSUE TITLE
Conversion to JSON with DataToDictionary().Convert() is not outputting the new GPS Coordinates data correctly

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2180]
I'm submitting a bug report about the GPS Coordinates getting encoded to JSON incorrectly when doing this
`ToSic.Sxc.Conversion.DataToDictionary(false).Convert(App.Data["Location"]);`

[x] JS development
[x] Content Types or data management
[x] APIs like REST

**Current behavior**
As you can see on line 15 of this output, the GPS coordinates are being encoded as a string with the quotes escaped. Compare that to line 24 and the output of the _2sxcEditInfo
![image](https://user-images.githubusercontent.com/653301/94372217-8382af00-00c1-11eb-8e1e-4e701a88d0e1.png)
 
**Expected behavior**
Though obviously we can code around it, I believe this is a bug and needs to be fixed so that the results at line 15 look like this with lattitude and longitude as numbers (not strings).
```
        "GPS": {
            "lattitude": 40.123123123,
            "logitude": -88.321321321
        }
```

**Minimal reproduction of the problem with instructions**
Just output the 2sxc Content-App 11.03 Location content-type using .Convert() (see above) to JSON. 

**Please tell us about your environment:**
2sxc 11.6.1 on DNN 9.07.02, 2sxc Content App is 11.03 from appx May 15.

**Comment by iJungleboy** [comment]
I agree with what you're describing. 

ATM the serializer doesn't know that GPS is a json field, internally it's a string (containing json). 

So for now please work around it, but do a type-check in your code in case we fix this later on, that it won't explode then :)

**Comment by jeremy-farrance** [comment]
Since you are in the section and working on this stuff, just a wishlist reminder that we could really use a one-button Clone for both Content-Types, and Views.

**Comment by iJungleboy** [comment]
So the plan is to implement export/import - to move from one app to another. 
How would you need to use clone?

**Comment by jeremy-farrance** [comment]
A use case I run in to regularly is wanting a variation of an existing Content-Type. Imagine I want to use Locations for a park district where (in the Content-App) Locations are already in use. So Clone the existing Locations to LocationsPlus and make changes and new views without affecting all the existing work. Same case with Person. We were already using that CT for hospital staff in 2 existing views. So cloning Person to Physician and then making changes saves a LOT of time.

**Comment by iJungleboy** [comment]
Ok, must check if we can fit that in. 

BTW: in a near-to-come release we'll add formula rules to generate values and show/hide or conditional required. Would you then still need cloning content-types?

**Comment by jeremy-farrance** [comment]
Yes, because - you are right - some changes are light/minor. But in the two cases above, fields were added, deleted, and renamed. It's also hard to answer because your implementation of 'formula rules' may also fall way short of my expectations. ;)

**Comment by iJungleboy** [comment]
as of now, I don't think we should or can quick-fix this, simply because it's hard to guess what would break in the wild. Since the value is also a string in razor, requiring `AsDynamic(item.GPS)` to work as an object, we believe it should be clear what's happening. 

So we'll leave it as is. 

If somebody would like it to be optimized as pure json coming from the server, just create your own backend.
