### ISSUE TITLE
Functionality to change order of attributes in attribute list of a content type

### ISSUE THREAD

**Issue by reaxx999** [2sic/2sxc#219]
Can you put a drag&drop functionality or "to top" and "to bottom" buttons here?
![moving](https://cloud.githubusercontent.com/assets/12188254/7418171/198476f4-ef6c-11e4-9900-8908baecba1b.png)

Thank you in advance! :)

**Comment by iJungleboy** [comment]
Currently not on our priority list - but you could contribute it. If you want to help, please use AngularJS as that is our standard for any UI we're building today.

**Comment by iJungleboy** [comment]
improved a lot in 7.3 - close...
