### ISSUE TITLE
Feature request: Drag'n'drop sorting file library items

### ISSUE THREAD

**Issue by e1-sistemi** [2sic/2sxc#2192]
**I'm submitting a ...** 
[x] feature request

**...about**   
[x] admin experience UI

Drag'n'Drop sorting of FileLibrary items.
This feature would be very useful when working with larger set of documents or images that require user defined sort order.
At the moment we use metadata number to sort on, but native angular drag'n'drop to sort would be much more user friendly.

**Comment by iJungleboy** [comment]
I have a good idea how we could implement this, but it would take 4-8 hours to do well. 

As it's not a priority for us, I don't think we'll do this any time soon. if you would want to contribute the code, that would be awesome, just discuss it with me before you start 😎 so it's in line with 2sxc conventions.

**Comment by iJungleboy** [comment]
Closing this, linking from the main task which lists everything needing sponsoring.
