### ISSUE TITLE
2SXC BUG in adding existing items from list

### ISSUE THREAD

**Issue by Alfakom-MK** [2sic/2sxc#2200]
**I'm submitting a ** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] admin experience UI
[x] other / unknown

**Current behavior**

I just want to report a bug whenever i'm creating a simple app with  a list view,
and try to add to the list existing data, it is showing:
"Replace Content Item 
By replacing a content-item you can make a other content appear in the slot of the original content."

**Expected behavior**

I guess that it should state something like: Add existing content item...

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Server 2019 eval

* **2sxc version(s):** 11.6.1  
* **Browser:** [all]
* **DNN:** [all | 9.X.X ] 
* **Language:** [any/all | English | ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
This was enhanced / fixed in 11.07 :)
