### ISSUE TITLE
Security Issue - XSS in /tosic_sexycontent/dist/dnn/ui.html

### ISSUE THREAD

**Issue by burninatorsec** [2sic/2sxc#2208]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 
[] feature request
[] support request => do not submit here, see https://2sxc.org/en/blog/post/moving-discussions-from-codeplex-to-stack-overflow
[] not sure

**...about**   
[] edit experience / UI
[] admin experience UI
[] Razor templating
[] JS development
[] Content Types or data management
[] APIs like REST
[] DNN parts
[x] other / unknown

**Current behavior**
I am not sure if this is the proper channel to disclose a security vulnerability, since these tickets are publicly viewable.

**Expected behavior**
It would not execute XSS (Javascript) payloads in the user's browser.

**Minimal reproduction of the problem with instructions**
I am not sure if this is the proper channel to disclose a security vulnerability, since these tickets are publicly viewable.

**What is the motivation / use case for changing the behavior?**
Security

**Please tell us about your environment:**
Reproducing this vulnerability should work on most modern browsers, the issue is independent of operating system, etc.
DNN Evoq 9.6.3
 
* **2sxc version(s):** 11.X.X  not certain
* **Browser:** [Chrome XX | Firefox XX ]
* **DNN:** [9.X.X ] 
* **Language:** [English]

**Anything you would like to add**

Please reach out as soon as possible so I can provide details privately - thank you for your help!

**Comment by iJungleboy** [comment]
Hi @burninatorsec - thanks - and thanks for the discretion - please mail me the details on info - 2sxc.org

**Comment by burninatorsec** [comment]
Sorry, I'm not clear on what email address I should use for it, and it doesn't look like GitHub has private messages anymore. Is there a public email I could use?

**Comment by burninatorsec** [comment]
My apologies, I just found it, thanks! security@2sxc.org

**Comment by burninatorsec** [comment]
Hello - Just wanted to add this was actually found in version 9.32.1 and we will be upgrading to 11 and testing again. Thanks!

**Comment by iJungleboy** [comment]
btw: I don't think we got a mail from you yet on security - but you could also try info@.

**Comment by burninatorsec** [comment]
Just sent another email to info@2sxc.org, I'll also try the 2sic contact form

**Comment by iJungleboy** [comment]
Got it! just reviewing it right now, thx so much!
I'll get back to you asap.
