### ISSUE TITLE
Arrow loop in Visual Query designer on itself that can't be deleted.

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [2sic/2sxc#2209]
**I'm submitting a ...** 

[x] bug report => did search github for a similar issue before submitting and didn't find one

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management

**Current behavior**

Sometimes I make misclick and accidentally connect wiring to same block. That creates wiring in a loop that has start and finish in the same place. When I click that place trying to remove the wiring, it just creates new one for me, since it's the start. And I can't delete that.
![3HwwxRNUSM](https://user-images.githubusercontent.com/21691213/95457110-113f8380-0979-11eb-9e79-1a207fe7be1a.png)

Attempt to run produces 400 bad request error with message, that some wirings were not created.
![chrome_J00Fta6Fwp](https://user-images.githubusercontent.com/21691213/95457149-20263600-0979-11eb-8cb8-aa7b065239ca.png)

**Expected behavior**

Either not being able to connect wiring to the same block, or improved logic for enabling loops, which will not break the query in general.

**Minimal reproduction of the problem with instructions**

Drag output point of the block, so you have some new wiring.
Drop it on the same block that it starts from.

**What is the motivation / use case for changing the behavior?**

If you make a misclick, you might break your logic and you'll need to fix it, otherwise this query won't work. There are 3 workarounds for now:

- hit reload and lose all last changes so that you reset wiring without this loop (works if you didn't hit save or run using your reflexes)

- create new query from scratch (not good if you have some decent logic there already).

- delete glitched block and add it again. You still need to add and adjust it correctly.

**Please tell us about your environment:**

Windows 10
IIS Manager v 10.0
built-in editor for Visual Queries

* **2sxc version(s):** 11.05  
* **Browser:** Chrome 85
* **DNN:** 9.6.1
* **Language:** English

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Thx for this, we'll look into it.

**Comment by PagnoDunadan** [comment]
Fixed
