### ISSUE TITLE
Custom DataSource - cannot make it work in newer versions of 2sxc

### ISSUE THREAD

**Issue by josip8** [2sic/2sxc#2211]
**I'm submitting a ...** 

[x] bug report
[x] not sure

**...about**   
[x] Custom DataSource

I tested custom datasources in 2sxc 9.13 and everything works great.
In version 11.6.1 I cannot make it work. It appears in visual query, but it is unusable
Is custom datasource still supported?
If it is supported, can you provide me with barebones example that works?

I followed 

- https://2sxc.org/en/blog/post/tutorial-custom-datasources-for-eav-2sxc-9-13-part-1
- https://2sxc.org/en/blog/post/migrating-custom-datasources-to-2sxc-10-20
- https://github.com/2sic/dnn-datasource-form-and-list/blob/master/ToSic.Dnn.DataSources.FnL/DnnFormAndList.cs
---
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [all | 8.X.X | 9.X.X ]

**Comment by iJungleboy** [comment]
Absolutely - thanks for asking. Custom data sources are technically the same like built-in data sources. 

The API got reworked a bit in 10x somewhere. I think you should take any EAV or 2sxc or DNN data-source in the system and work from there. 

Some good places to start from

1. https://github.com/2sic/eav-server/blob/master/ToSic.Eav.DataSources/DataSources/EntityIdFilter.cs - very simple, almost the minimum of a data-source but with configuration. 
1. https://github.com/2sic/eav-server/blob/master/ToSic.Eav.DataSources/DataSources/External/DataTable.cs - more complex and generates own data
1. https://github.com/2sic/eav-server/blob/master/ToSic.Eav.DataSources/DataSources/External/CsvDataSource.cs

Things I would look out for are:

1. what you inherit from
1. How streams are provided - in the old case it often changed "Out" but you shouldn't do that any more, just use `Provide(listmaker)` or `Provide(name, listmaker)`
1. Configuration now uses `ConfigMask(...)` in constructor and `Configuration.Parse();` in the list-getter to ensure that the placeholders were replaced. 

I'll close this task as it's not really relevant to others, but do continue posting questions if you need help.
