### ISSUE TITLE
Bug: 2SXC Content layout (v11.07.03 & 11.04.00)

### ISSUE THREAD

**Issue by skarpik** [2sic/2sxc#2212]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] Razor templating
[x] Content Types or data management
[x] other / unknown

**Current behavior**

Discovered this bug in a live site (DNN v9.6.1/2SXC v11.04.00).

Added Basic Content (Image | Text) to empty page. Works perfectly. When I added an Image (2SXC single image) immediately below the Image | Text object, top navigation gets messed up (see attached screen grabs).

Looked for bug in the following test websites (Xcillion skin, Inner Layout):

- DNN v9.6.1/2SXC v10.25.02 => no bug
- DNN v9.61/2SXC v11.04.00 => bug
- DNN v9.6.1/2SXC v11.07.03 => bug

**Expected behavior**

Adding content elements (image | text, image, etc.) should not cause top navigation to break.

**Minimal reproduction of the problem with instructions**

Please see attached screen shots. Top navigation is broken when two Content items are added to a page. Works perfectly for just one.

**What is the motivation / use case for changing the behavior?**

Something is broken in 2SXC (maybe related to bs3?)

**Please tell us about your environment:**

Windows 10
DNN v9.6.1
Bug seen in 2SXC v11.04.00 and v11.07.03 (OK in v10.25.02) - not tested in other versions of 2SXC
Bug seen in Chrome, Edge and Firefox (screenshots are from Windows 10 Chrome)
Bug was discovered in a bilingual English/French website. Testing done in unilingual English.
No JavaScript errors in Console.

![2sxc-10-25-02 - 2 elements](https://user-images.githubusercontent.com/3846223/95790475-719e3000-0cad-11eb-9356-c97e61c2b065.JPG)
![2sxc-11-04-00 - 1 element](https://user-images.githubusercontent.com/3846223/95790476-719e3000-0cad-11eb-955c-8b24eb7cc723.JPG)
![2sxc-11-04-00 - 2 elements](https://user-images.githubusercontent.com/3846223/95790477-7236c680-0cad-11eb-969d-1592b647a2a7.JPG)
![2sxc-11-07-03 - 1 element](https://user-images.githubusercontent.com/3846223/95790478-7236c680-0cad-11eb-8733-e906cbfbf23b.JPG)
![2sxc-11-07-03 - 2 elements](https://user-images.githubusercontent.com/3846223/95790479-72cf5d00-0cad-11eb-9a23-9a74229e0ac2.JPG)

* **2sxc version(s):** 11.X.X  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [all | 7.4.2 | 8.X.X | 9.X.X ] 
* **Language:** [any/all | English | German | other ]
**Anything you would like to add**

**Comment by iJungleboy** [comment]
thanks for this. could you find out what's causing this? maybe...

1. an unclosed DIV
1. some enforced width
1. some style that is introduced / overwritten by accident?

**Comment by skarpik** [comment]
I discovered this in a skin that I developed so I immediately suspected that my skin was defective. So that's why I used the Xcillion skin. I looked for a cause but did not find anything. Now that you've given me some suggestions of what to look for, I will investigate more closely.

**Comment by skarpik** [comment]
I may have found the problem. I created two DNN v9.6.1 websites. In one I installed 2SXC  v10.25.02. In the other, I installed 2SXC v11.07.03. I then created the same webpage in each - 1 basic content (1:1 image/text) with a 2SXC Content image just below. Comparing the view-source code, I found that the v10.25.02 code referenced:

<link href="/Portals/_default/Skins/Xcillion/skin.css?cdv=35" type="text/css" rel="stylesheet"/>
<link href="/Portals/0/2sxc/Content/dist/bs3.min.css?cdv=35" type="text/css" rel="stylesheet"/>

whereas the v11.07.03 code references:

<link href="/Portals/_default/Skins/Xcillion/skin.css?cdv=35" type="text/css" rel="stylesheet"/>
<link href="/Portals/0/2sxc/Content/dist/bs3.min.css?cdv=35" type="text/css" rel="stylesheet"/>
<link href="http://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css?cdv=35" type="text/css" rel="stylesheet"/>
<link href="/Portals/0/2sxc/Content/dist/bs4.min.css?cdv=35" type="text/css" rel="stylesheet"/>

and then a little later there is:

<script src="http://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js?cdv=35" type="text/javascript"></script>

The Xcillion skin includes the correct koi.json file (i.e. specifies bs3). But for some reason in 2SXC v11.07.03 we are seeing references to bs4. Likewise 2SXC v11.04.00 is including references to bs4 in Xcillion which is a bs3 skin.

So my guess is that 2SXC Content for v11.04.00 and v11.07.03 is not paying attention to the koi.json file and mistakenly including references to bs4 (this is a wild guess since I don't really have a good grasp on a deep on how 2SXC works).

Does any of this make sense?

**Comment by iJungleboy** [comment]
The behavior sounds like Koi is assuming an unknown CSS Framework, in which case teh content-templates have rules to fallback to including bootstrap4 from a CDN

So the rules are: 

1. If the skin is BS3 use BS3 styles
1. If the skin is BS4 use BS4 styles
1. If it's anything else then use BS4 styles and import BS4 styles to ensure things look ok - this is mostly meant for first-install scenarios, before people do any real work. 

It sounds like you're hitting case 3

But note: if it is case 3, you would also see a warning that you should add the koi.json (when logged in) but you're not seing it. 

I just checked our dev environment and simulated BS3 - and I can confirm the issue! We'll fix within a few days. 
Thank you so much!

**Comment by iJungleboy** [comment]
So I found the cause, Koi was ok, but some entry-files were missing for BS3 

In https://github.com/2sic/2sxc-content-app/tree/master/bs3/Image

It only had the top 2 files, the other ca. 6 were missing. So Koi tried to find out if BS3 has the same view, but didn't find it. 

You can quick fix it by just adding those files to your installation. We'll release an updated app in a few days and put it into the default installation. 
Many thanks again!

**Comment by skarpik** [comment]
Thanks!
