### ISSUE TITLE
Visual Queries in/out point renaming issue.

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [2sic/2sxc#2213]
**I'm submitting a ...** 

[x] bug report => searched github for a similar issue before submitting, but didn't find one

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management

**Current behavior**

I was editing existing visual queries and I needed to rename wiring output point in visual query. At the same time another visual query was already using first one and it had reference to it's output point as input point for wiring. After I renamed it in first one, app became inaccessible, so I couldn't even fix it. The only way out was to revert all changes in git. I managed to edit it anyway, but only by opening both visual queries at the same time, then editing target points and saving it with minimum possible time delay between clicks on "Save" buttons in both tabs.

**Expected behavior**

Even if something is broken in visual queries developer should still be able to fix his error.

**Minimal reproduction of the problem with instructions**

For instance you have queries "Query1" and "Query2", Query1 contains output point "TargetPoint" and Query2 refers same point in Query1 as data source.

- Go to Query1.

- Rename "TargetPoint" to anything else in Query1.
- Save changes and close tab.
- Go to page with application and try to open window with list of visual queries for that app.

You'll see alert with error message "Had an error talking to the server (status 400). Message: Bad Request. Detail: Trouble with connecting query from [Query1 id]:TargetPoint to Out:TargetPoint

**What is the motivation / use case for changing the behavior?**

If someone renames out point in one query and doesn't do the same in another one, which refers to it, application stops working at all and you have no way to fix it.

**Please tell us about your environment:**

Windows 10
Google Chrome 86.0.4240.75
Visual Query editor in admin panel

* **2sxc version(s):** 11.0.5  
* **Browser:** Chrome 86.0.4240.75
* **DNN:** 9.6.1
* **Language:** English

**Comment by iJungleboy** [comment]
We're releasing a lot of improvements to VisualQuery in 2sxc 11.13. Not sure if this is still an issue, so we'll close it for now. 

If it's still there, pls post here so that we can re-open. Ideally include 2-3 screenshots.
