### ISSUE TITLE
Upgrading from 10.25.2 to 11.7.3 made a DNN 9.2.x website unusably slow

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2218]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] other / unknown

**Current behavior**
I had a DNN 9.2.X (either 0 or 2, can't remember) and I performed a DNN upgrade to 9.6.2. Then I installed 2sxc 11.7.3 and it was fine.

However, when I went to upgrade on the live website, I upgraded 2sxc from 10.25.2 *before* upgrading DNN to 9.6.2 and the it installed successfully and when the website went to restart it took a few minutes for the page to load. I thought it had completely bugged out but it just kept spinning for minutes but then the page would load. When I browsed to another page, the page would take forever to load again. The hosting company noticed the CPU was going crazy and so we had to revert to a backup and then perform the DNN upgrade first, and then the 2sxc upgrade and it worked.

The odd thing was that there was no error or anything like that. Just an incredibly slow website that took minutes to load for each page.

**Expected behavior**

2sxc compatability on DNN 9.2.x

**Minimal reproduction of the problem with instructions**
REPRO STEPS:

On a DNN 9.2.X (either 0 or 2), upgrade from 2sxc 10.25.2 to 11.7.3 and see if it makes the site unusably slow. If it is slow, then try reverting and try upgrading DNN first, and then installing 11.7.3 to upgrade.

**What is the motivation / use case for changing the behavior?**
I got around the issue by upgrading DNN first and then 2sxc so it's not a problem for me but I thought I would bring it up to you in case other people have the same experience.

**Please tell us about your environment:**
Dedicated hosting.

* **2sxc version(s):** 11.7.3  
* **Browser:** [all ]
* **DNN:** [9.2.0 / 9.2.2 ] 
* **Language:** [any/all]

**Anything you would like to add**
This might be just a fluke issue that I had with my particular DNN website and the combination of modules I had. It's probably an edge case for users but I thought I would bring it up so you're aware of it in case it's a real problem.

**Comment by iJungleboy** [comment]
So far I can't confirm this. We have 11.7.3 or newer on various sites already. 

Can you check what insights says - how long a module is being built? there is a timer information on every call.

**Comment by ajplopez** [comment]
I can't reproduce the problem because I don't have a staging site anymore. So I will just close this in case someone else stumbles across the same problem.

**Comment by jeremy-farrance** [comment]
The plot thickens. :) I am glad something similar came up elsewhere.

**Comment by jeremy-farrance** [comment]
@ajplopez - Aaron, can you please provide a carefully detailed list of the OTHER modules that are installed? Only 3rd party stuff like DNN Sharp's ActionForm, etc. And please include the exact version? Hopefully its not too many.

**Comment by ajplopez** [comment]
@jeremy-farrance I don't have that old staging anymore, so I'm not sure what things were on when we did the upgrade. But now we have:

1. Action Form 5.9.11 
2. DNNSharpMailChimp 5.0.15 
3. EasyDNNnews 10.8.0 
4. EDN UrlProvider 2.9.6 
5. Live Content 7.0.1
6. I also have some old custom modules that were installed 5 years ago but I'm not sure if they have anything to do with it

**Comment by jeremy-farrance** [comment]
Here is mine for comparison. I am somehow suspicious that ActionForm is playing a role in this. But its not based on anything specific yet.

DNN 9.03.02, 
DNNBackup 8.7.2 
2sxc 9.43.2 (not in use) upgraded to 11.7.3
ActionForm 5.0.739
DNNSharp MailChimp 5.0.15
EDNews 10.6.0 (URL provider not installed)
Form 'n List 6.5.4

**Comment by MS-BSI** [comment]
Hi,

Same problem here with a DNN 8.0.4 version.
No problem with previous versions (from 10.27.1 to 11.02), the website becomes slow when installing version 11.03 or any higher version.

A simple request to a txt file take many seconds.

I got ActionForm (5.0.739) and EasyDNNnews (10.1.2) too on that website (+ various modules but these are the ones in common).

**Comment by jeremy-farrance** [comment]
> Same problem here with a DNN 8.0.4 version.
@MS-BSI, its a long read with tangents, but can you [review the related/open issue](https://github.com/2sic/2sxc/issues/2199) and see if there are any other commonalities or things mentioned that appear to be worth investigating and reporting on from what you've seen? Since its Open still, you might want to post on that issue also, just to give it a bump. Thanks!!

**Comment by MS-BSI** [comment]
@jeremy-farrance : I read it before coming to this topic ;)
I'll be doing a lot of cross-testing, but the slowness makes it take time !

**Comment by iJungleboy** [comment]
Just some ultra-basic questions

1. Is CPU high during this time, or is it waiting for something?
1. What about memory - busy/high, or nothing special?
1. Is the DB being hit like crazy?

+ it would be very interesting to see the top 3-4 lines of 2sxc insights - where it shows how many seconds it took to render a 2sxc block. Usually it's within a few MS, but if the 2sxc rendering itself is taking long, this would be good to know. 

And also: if you have such a site without confidential info, and could we-transfer it to me, I would like to take a look.

**Comment by MS-BSI** [comment]
1 / 2 / 3 . No, normal behaviour for my part.

Like I said, a simple request to a txt file (in order to avoid any "DNN effect") takes many seconds.
If I rename the web.config file, it's instant !

**Comment by jeremy-farrance** [comment]
Same here, the rest of the server/sites are all normal. Only the affected/upgraded site gets slow. The only really consistent thing is that if you watch tasks or the process monitor, the csc.exe keeps re-launching every 20 seconds or so until the page finally displays. Which can be up to a full 3+ mins in some cases.

**Comment by jeremy-farrance** [comment]
@MS-BSI, sorry, I was just trying to get the convo on the Open issue since this is the closed/related/older one.

**Comment by iJungleboy** [comment]
@MS-BSI  & @jeremy-farrance  agree - let's continue there. I'll post another hint there related to the web.config.
