### ISSUE TITLE
Create New Entity (Relation) adds new entry multiple times

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#2221]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI

**Current behavior**
A content type A has a field of type Entity  (Type B). This field is configured for multiple items.
When I edit/add an entry for A and create a new item of type B, 
![image](https://user-images.githubusercontent.com/5693190/96700414-b6058c00-138f-11eb-8684-693cf94fe019.png)

this new item is added multiple times.
![image](https://user-images.githubusercontent.com/5693190/96700464-c289e480-138f-11eb-9de1-4a84644a43cf.png)

**Expected behavior**
It should be added only a single time.

**What is the motivation / use case for changing the behavior?**
This is an annoying bug.

**Please tell us about your environment:**

* **2sxc version(s):** 11..7.3
* **Browser:** [l | Chrome XX | Edge XX  ]
* **DNN:** [ 9.7.2 ] 
* **Language:** [ English  ]

**Anything you would like to add**
The number of added items seems to match the number of entries of type A

**Comment by iJungleboy** [comment]
@PagnoDunadan could you pls check/verify this?

**Comment by PagnoDunadan** [comment]
I will need an example app to check the exact details because I can't reproduce the issue:

![multipleentities](https://user-images.githubusercontent.com/7113033/96726386-35a45280-13b2-11eb-95cf-54572a7613fd.gif)

**Comment by SCullman** [comment]
I am going to set up an example app for you including video.

**Comment by SCullman** [comment]
Example App:    
[2sxcApp_MultibleBs_0.0.1.zip](https://github.com/2sic/2sxc/files/5417374/2sxcApp_MultibleBs_0.0.1.zip)

Video:   
![My-Website-_-dev-und-2-weitere-Seiten-Persönlich-–-Microsoft_-Edge-2020-10-21-18-33-45](https://user-images.githubusercontent.com/5693190/96750915-d7389d80-13cc-11eb-8ea9-cd1c59c1d46b.gif)

**Comment by PagnoDunadan** [comment]
Can confirm that it sometimes happens in 11.7.3. LTS, but it doesn't happen in dev build which means it was fixed at some point but I don't remember changing anything that would affect this. I will try to figure out why it happens in LTS.

**Comment by PagnoDunadan** [comment]
Fixed. This problem must have existed for a while now. Thanks for reporting :)
