### ISSUE TITLE
Possible localization bug (2SXC v11.7.3)

### ISSUE THREAD

**Issue by skarpik** [2sic/2sxc#2222]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management

**Current behavior**

In a bilingual en-ca/fr-ca website, 2SXC content in the two languages are not independent (for instance, change made in a Basic Content Test|Image module made on the English page is propagated to the Content module on the French page).

**Expected behavior**

For other modules (for instance, HTML), a change to a module on an English page is not a automatically pushed to the French page (i.e. the English page can have English language text and the French page can have French language text).

**Minimal reproduction of the problem with instructions**

1) Created DNN v9.7.2 website with default home page (en-us default language
2) Added a page "2sxc1", added English language text to an HTML module
3) Followed normal procedure to make a multi-language site (added en-ca and fr-ca, made en-ca the default language, disabled en-us, selected "Allow Content Localization", activated fr-ca).
4) Verified that text in the newly created fr-ca page (2sxc1-fr-CA) could be translated to French leaving the text on the English page (2sxc1) unchanged - verifies that localization is working properly.
5) Installed 2SXC.
6) Added a 2SXC Content module to the English page (2sxc1). Installed all Content module. Made the new Content module of type Basic Content / Image|Text (1:1). Added a photo to the Image|Text module and added English text.
7) In page properties for 2sxc1, used the Localization tab to copy the Content module from the English page to the French page.
8) Edited text in the Content module on 2sxc1-fr-CA to make it French language.
9) Jumped back to the English page where I found French language text. The 2SXC Content module seems not to respect localization.

**What is the motivation / use case for changing the behavior?**

To be consistent with core modules like HTML, localization should mean that the content in parallel pages should be independent. If this is not possible, localization doesn't serve users well (some modules are properly localized, others are not).
**Please tell us about your environment:**

OS: Windows 10
DNN Version: 9.7.2
2SXC Version: 11.7.3
Browser: Edge, Chrome and Firefox (current releases)
Other Versions: First discovered behaviour this behaviour in a DNN v9.6.1, 2SXC v11.4.0 website

* **2sxc version(s):** 11.X.X  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [all | 7.4.2 | 8.X.X | 9.X.X ] 
* **Language:** [any/all | English | German | other ]
English (en-ca), French (fr-ca)
**Anything you would like to add**
It is entirely possible that I need select some option (that I'm not aware of) to tell 2SXC to allow for localized content. If this is a bug (not a feature) and/or I haven't missed an important step, I can create a video of the steps that I followed to illustrate the issue.

**Comment by iJungleboy** [comment]
Basically the system should work as you describe it - once translated, the language doesn't auto-copy any more. That's what it's for :)

So I'm not sure where you hit an issue - a short video would help :)

**Comment by skarpik** [comment]
OK. I will create one either later today or tomorrow (too many Zoom meetings).

**Comment by skarpik** [comment]
I have created a video which you can download from:

https://www.dropbox.com/s/l6zjpubi8ltytpu/20201027120839.mp4?dl=0

Here is my annotation for the video:

**2SXC Localization Test**

1) Created DNN v9.7.2 website (http://dnn-9-7-2b.dnndev.me/) using Default Template (US English)
2) Installed 2SXC v11.07.03
3) Add new page called Page1 
4) On Page1, populated an HTML module with a demo English language text.
5) Added a 2SXC Basic Content module (Text | Image 1:1). Added demo English text and image.
6) Add alternate languages to the portal - en-ca and fr-ca.
7) Make en-ca the default language. Disable en-us.
8) Localize the website.
9) Navigate to the French side of the website and translate text Page1-fr-ca (the HTML module and the 2SXC content).

[At this point the localization for DNN seems to have a glitch. I thought I was editing the HTML module on the French page but I was actually editing the English content. The URL http://dnn-9-7-2b.dnndev.me/fr-ca/Page1 was as wrong (a phantom byproduct of the localization?). 

Going back and forth between the English and French, I got to http://dnn-9-7-2b.dnndev.me/fr-ca/Page1-fr-CA. So the video may look a bit confusing at this point.]

By 11:10, the localization glitch seems to be resolved (i.e. localization works properly for English and French HTML modules). However at 11:30, a 2SXC message pops up that might indicate the source of the problem:

"We have switched language to default en-ca because it's missing some or all values"

10) Finally, checking text on Page1. HTML module text on Page1 is in English (correct) and 2SXC text on Page1-fr-CA is in French (wrong).

So the page that was created through the localization of the website has the English and French content totally coupled. Now test whether localization is broken for a new page.

11) Add new page called Page2 
12) On Page2, populated an HTML module with a demo English language text.
13) Added a 2SXC Basic Content module (Text | Image 1:1). Added demo English text and image.
14) Through page properties, add fr-ca language to Page2 (creates Page2-fr-ca)
15) Translate text Page2-fr-ca (the HTML module and the 2SXC content).

At 20:07, editing the French 2SXC content on Page2-fr-CA, I got the same warning error:

"We have switched language to default en-ca because it's missing some or all values"

16) Checking text on Page2, I see that the HTML module text is in English (correct) but 2SXC text is in French (wrong).

My guess is that a side-effect of the warning message that I saw is that the localization is somehow getting messed up.

If if would be helpful, I can do an Evotiva backup of my test website and send you those files.

**Comment by websystemsoftware** [comment]
i have the same Problem with 2sxc 11.7.3
translation works not anymore....

what can we do?

**Comment by iJungleboy** [comment]
Sorry for the late reply - been busy building 2sxc for Oqtane

From what I can see you didn't activate the languages in 2sxc

![image](https://user-images.githubusercontent.com/5321186/98646114-3128e500-2333-11eb-8465-00749e774c15.png)

The languages must be activated per site - you can find it in the Apps-Management (the green toolbar button with the many small boxes).

Does it fix your issue?

**Comment by websystemsoftware** [comment]
Hi Daniel, thanks yes is working now...

**Comment by skarpik** [comment]
Thank you very much. I'm not sure how I missed that switch.
