### ISSUE TITLE
Translation works not in Version 11.7.3

### ISSUE THREAD

**Issue by websystemsoftware** [2sic/2sxc#2237]
**I'm submitting a ...** 

[x] bug report

[x] other / unknown

**Current behavior**
Translation works not in Version 11.7.3

* **2sxc version(s):** 11.7.3  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** 9.7.2 
* **Language:** [any/all 

Translation works not in Version 11.7.3
in the normal Standard HTML Modul from DNN the Translation works, but with the 2sxc HTML Modul no translation works anymore... it shows also no Language selector in the Modul like it was before...

![2sxc-NoLanguageSelector](https://user-images.githubusercontent.com/19758307/98634052-edc67a80-2322-11eb-9c4f-cd9b88621c82.jpg)
![2sxc-ContentAdmin](https://user-images.githubusercontent.com/19758307/98634053-ee5f1100-2322-11eb-9033-769b38e680a6.jpg)

**Comment by iJungleboy** [comment]
Since the languages are actually a global setting, we moved it away from the App and only show it in Apps-Management. 

You can find it there (it's the toolbar-button with little boxes)
