### ISSUE TITLE
Error Status 400 Bad Request in Version 11.7.3

### ISSUE THREAD

**Issue by websystemsoftware** [2sic/2sxc#2238]
[x] bug report  

[x] other / unknown

**Current behavior**
when i click in a 2sxc Modul to Admin i come to >> Content Admin
on the Content Admin Settings Page i go to App >> and there i click on configure App Settings

i come not inside (Configure App Settings)
It comes always a Error : Bad Request status 400 like you can see in the attached Printscreen 

* **2sxc version(s):** 11.7.3 
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** 9.7.2  
* **Language:** [any/all | English | German | other ]

![2sxc-App-Error2](https://user-images.githubusercontent.com/19758307/98634718-10a55e80-2324-11eb-9518-0b706e0a5c4a.jpg)

**Comment by iJungleboy** [comment]
Could you include more information? like what url was requested ( check F12) and what was the response. 

+ info from Dnn Events or Insights, how far it got till it failed.

**Comment by iJungleboy** [comment]
Closed because of inactivity.
