### ISSUE TITLE
Retrieve TabID from HyperLink Page Chooser

### ISSUE THREAD

**Issue by hereswhatidid** [2sic/2sxc#224]
Currently there is no way to retrieve the TabID from a HyperLink field type. I'm using 2sxc to generate a tabbed sub navigation content type and would like to be able to highlight the current tab within that list. When using a URL rewriter module I'm getting different values between the Dnn.Tab.FullURL value and the value within the 2sxc hyperlink field.  If I could get the tab id from the 2sxc field I could then compare that to the Dnn.Tab.TabID value to test if the current page is active.

**Comment by iJungleboy** [comment]
Are you using razor?
If yes, you can access the "raw data" if you cast your dynamic object to AsEntity(your original object) and then go through the attributes structure. You can also use the GetBestValue(...) function to skip navigating the objects.

**Comment by hereswhatidid** [comment]
I ended up going with this solution:

```
string activeClass = "";

if ( e.Content.Entity.Attributes["TabURL"]["TypedContent"].Contains( "Page" ) ) {
        var tabIDString = e.Content.Entity.Attributes["TabURL"]["TypedContent"].Replace( "\"", "" );
        var linkTabID = Int32.Parse( tabIDString.Split( ':' )[1] );
        activeClass = ( Dnn.Tab.TabID == linkTabID ) ? "active" : "";
}
```

**Comment by iJungleboy** [comment]
Thanks for sharing the solution!
