### ISSUE TITLE
Multilingual dropdowns don't show the other language

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2240]
**I'm submitting a ...** 

[x] bug report
[x] maybe my misunderstanding

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management

**Current behavior**
I have a multilingual DNN website. I created a multilingual app in 2sxc. My website is in both English and French. In my app, I have some content types which are dropdowns. For example, I have a school subject dropdown:

Arts Ed
Career Ed
ELA
Health Ed
Math
PAA
Science
Social Studies

And on the field settings, I've updated the FRENCH to be the French translations of the dropdown:

Arts Ed
Carrière Ed
ELA
Santé Ed
Math
PAA
Science
Études sociales

![Screen Shot 2020-11-10 at 9 45 48 AM](https://user-images.githubusercontent.com/8751936/98711276-a697b400-2339-11eb-8f05-27da56b7ccc3.png)

But when I go to edit a School Subject for French, the field is disabled and the text "in all languages" is red so I can't change it.

![Screen Shot 2020-11-10 at 9 47 54 AM](https://user-images.githubusercontent.com/8751936/98711437-d3e46200-2339-11eb-9d41-6af008d3a92f.png)

I have another dropdown which is set up the same way, but when I go to edit it, it allows me to change it, but it doesn't show the French translated dropdown options. It just shows me the same English options.

![Screen Shot 2020-11-10 at 9 48 41 AM](https://user-images.githubusercontent.com/8751936/98711551-f70f1180-2339-11eb-9ee1-ebd8224fd4ba.png)

So I'm confused about how this should work. Basically, I want to be able to select different dropdown options for the different languages and I seemingly have it set up correct but it doesn't let me change it for one reason or another.

**Expected behavior**
I would think that if I have translated a dropdown, then the editor would allow me to choose between the two different languages for dropdown options. But maybe I'm misunderstanding this or I have set it up incorrectly?

**Minimal reproduction of the problem with instructions**
Create an app that is multilingual on a multilingual DNN website. Create a content type with a dropdown that has two sets of options for each language. Then try to edit the content for each language. You will either find that you can't edit the other language dropdown or it will let you but it will be in the primary language.

**What is the motivation / use case for changing the behavior?**
Trying to understand how to translate dropdowns.

**Please tell us about your environment:**
Hosted my Managed.

* **2sxc version(s):** 11.4.0  
* **Browser:** [all ]
* **DNN:** [9.4.1 ] 
* **Language:** [ English | French ]

**Anything you would like to add**
Please let me know if this is a bug and I just need to upgrade. Or let me know if I'm just misconfiguring it.

**Comment by iJungleboy** [comment]
I believe you have two separate issues. 

The first being a dropdown which is blocked in another language - my belief is that you probably toggled the field to not be translated. It would be in one of the folded sections above in the field settings. 

The second being that values shown are in EN only. Now this should work - there's even a "key:local-text" syntax so that you can store the same information in any language, but show the user values in his language. 

Can you verify that they are two separate issues, and that the first is probably quickly fixed? maybe give some more screenshots for the second issue.

**Comment by ajplopez** [comment]
I have not disabled translations for any field. I double checked the UI Settings collapsed section and translations are enabled.

One thing to note is that this site was originally in EN-US. I started developing my app and my content. Then later on, I enabled EN-CA and FR-CA and switched the site's primary language from EN-US to EN-CA and then disabled the EN-US language completely. So now the site is only in EN-CA and FR-CA. I do notice a quirk where I have to essentially re-save my content that existed as EN-US a few times before I'm able to properly set the EN-CA and FR-CA languages. Perhaps that is a symptom of the issue I'm running into?

**Comment by iJungleboy** [comment]
that's very likely. 

If you hit ctl+alt+shift+click somewhere you'll see a debug bar appear below - where the internal object/value structure is shown. My guess is you have some leftovers from when the primary language was a different one. the UI probably has a hard time figuring out what to do with that.

**Comment by ajplopez** [comment]
Ah, I think it's starting to work now that I've re-saved my entities. Thanks Daniel.

**Comment by iJungleboy** [comment]
BTW: We just ran into a similar issue here at 2sic - upgrading a site which was ca. 4-5 years old. 

I believe we figured out the cause - basically historical problem, not easy to do right. But I think I have a solution and will include a fix in 11.08 - #2243
