### ISSUE TITLE
@Dnn.Portal.PortalName doesn't display the portal name, it shows "DotNetNuke.Entities.Portals.PortalAliasInfo"

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2241]
**I'm submitting a ...** 

[x] bug report
[x] not sure

**...about**  
[x] Razor templating

**Current behavior**
I want to display the portal name in a view. But when I put in @Dnn.Portal.PortalName (added via the sidebar in the template editor) it doesn't display the portal name, it just shows "DotNetNuke.Entities.Portals.PortalAliasInfo"

**Expected behavior**
I think it should show my active portal's alias. So when I'm on domain.ca/en-ca I would think it should show that.

**Minimal reproduction of the problem with instructions**
Make a 2sxc razor template and add @Dnn.Portal.PortalName and see what shows up

**What is the motivation / use case for changing the behavior?**
Seems like a bug.

**Please tell us about your environment:**
Hosted on Managed

* **2sxc version(s):** 11.4.0 
* **Browser:** [all ]
* **DNN:** [9.4.1 ] 
* **Language:** [English and French ]

**Anything you would like to add**
I have a multilingual site

**Comment by iJungleboy** [comment]
I just did a quick check on a DNN 7.4.2 and it seems that the DNN API has changed for this object. 

So it's something in DNN that has changed. I'll see how I can update the snippets, but you should be able to find the latest correct DNN API on http://dnndocs.org/.
