### ISSUE TITLE
Visual query not working (no lines, no option to connect)

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2242]
**I'm submitting a ...** 
[x] bug report

**...about**  
[x] admin experience UI
[x] Content Types or data management
[x] other / unknown

**Current behavior**
All my queries (new and old) show the workflow boxes, but no lines and no option to create connections.

![image](https://user-images.githubusercontent.com/26518879/98997466-73694680-252c-11eb-94d2-d2b216b1b7c1.png)

* **2sxc version(s):** 11.7.3
* **Browser:** [Firefox]
* **DNN:** [9.7.2 ] 
* **Language:** [English | Portuguese ]

**Comment by iJungleboy** [comment]
Could you 

1. Check if it works in chrome
2. tell us if you see an JS errors in F12 debug

**Comment by eXistenZe** [comment]
Yes. I'm guessing you moved jsPlumb to an external resource in the last updates.
My CSP was blocking it.
Thanks.
