### ISSUE TITLE
Translating QS path in the view settings, the QS name from the query value filter and the QS value to find, all fail in multilanguage app

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2244]
**I'm submitting a ...** 
[x] bug report

**...about**
[x] Content Types or data management
[x] other / unknown

**Current behavior**
I'm trying to make a multilang app work with a single query, single view but different QS and content. I'm finding three different issues:
1. In the view settings, you are able to translate the URL path, but this will not work. Only the original language QS will be recognized. We can bypass this creating two views with the same file, but different paths.
2. In the visual query, we can translate the value from [QueryString:qsname], but this will also have no effect on the app. We can bypass this by creating two value filters and merging them.
3. Even if we do all this, the query will only get the value from the QS in the original language. For example page-en/qs-en/qsvalue-en will fail, but page-en/qs-en/qsvalue-pt will work. PT is the main language and EN the second language.

**Please tell us about your environment:**

* **2sxc version(s):** 11.7.3
* **DNN:** [9.7.2]
* **Language:** [ English | Portuguese ]

**Comment by ajplopez** [comment]
I'm also seeing this issue. In my setup, I have a multilingual site with EN-CA (primary) and (FR-CA) enabled. My 2sxc app has languages enabled and is a listing of careers with a details view: _listing.cshtml and _details.cshtml

I have a query set up that filters on the career query string. And a URL-Part field to give each language a unique, localized URL. In my details template, I have it filtering on career/*.

/en-ca/students/build/career/aquaculture-harvest-labourer (this works as expected and shows the details view in English)

/fr-ca/eleves/construire/career/manoeuvre-de-recolte-d-aquaculture (this doesn't work - it doesn't show the French translation - it shows as null)

**Comment by iJungleboy** [comment]
Some background:

The entity-value filter ATM always uses the primary language - that's why it works in with the EN fragment. 

We can't just change this - as it would break other stuff. Basically to fully change it we would have to introduce a setting if the value filter should respect the current language - but again I'm not sure what unexpected behavior that would cause. 

As a short term fix I recommend

1. either set the url-key field to not-translatable
1. or query the data in LINQ in the razor

**Comment by eXistenZe** [comment]
This is actually a shame since it prevents sites from going full 2sxc multilanguage. Most pages use location specific QS name and value. It improves the SEO and becomes user friendly.
A /this-page/this-subject/this-specific beats /this-page/this-subject/03636-or-some-untranslated-string anytime.
Linq is an alternative, but it demands coders and becomes out of reach for some content developers.

**Comment by iJungleboy** [comment]
@eXistenZe totally agree. Just wasn't a priority up to now.

**Comment by ajplopez** [comment]
Ah ok. So just so my understanding is correct: even on your multilingual websites, you don't translate the URLs for your details views? So if you're using the blog app. does it show something like this: /en-ca/news/hello-world and /fr-ca/nouvelles/hello-world ?

**Comment by iJungleboy** [comment]
@ajplopez that's the default ATM, yes. 

To be honest, most customers don't actually have the resources to really do multi-language blogs or news - so usually it's just published in the primary language. Then some customers have a setup where they publish in one language or the other - in that case we often have a "show-in-language" toggle or something - where each item is also just in 1 language. 

The final case - where it's really the same item in many languages - there we just write 3 lines of LINQ, but so far that was very rare - less than once per year.

**Comment by ajplopez** [comment]
Makes sense. In my case, I'm building an app that is truly multilingual where the content editors will translate every "career" for both English and French. Do you have an example of the 3 lines of LINQ to at least point me in the right direction?

**Comment by iJungleboy** [comment]
I'll try to address this in the next minor release.

**Comment by iJungleboy** [comment]
Was way tougher than expected - took me 10 hours with writing tests and verifying that nothing breaks in the chain...

I also did it for both

1. Value Filter
1. Value Sort (this also only respected the primary language so far)

Oh well, the fields will still default to primary-only, but you now have a setting to choose the current-language or a specific language in the configuration - or you can also get the language from the url or something. 

![image](https://user-images.githubusercontent.com/5321186/99499921-e5e98480-2979-11eb-87c2-7219858113d9.png)

![image](https://user-images.githubusercontent.com/5321186/99499946-f00b8300-2979-11eb-91e3-fe0b1f7273ad.png)

I really need your help to verify everything works - please give it a spin - attached is a temporary release just for you:

[2sic_2SexyContent_11.10.01_Install.zip](https://github.com/2sic/2sxc/files/5558498/2sic_2SexyContent_11.10.01_Install.zip)

**Comment by eXistenZe** [comment]
Only number 3 was fixed for me. The parameter value is now searched in the current language.
However:
- The parameter name is not translated (we need two value filters and a merge). 
- The parameter in view settings still does not work. We need two views.

**Comment by iJungleboy** [comment]
I don't really understand the Questions 1 & 2. I'm pretty sure it's easy to fix, but I don't want to chase you down the wrong rabit hole. Could you explain them in more detail?

**Comment by eXistenZe** [comment]
1. Translating this does not work:
![image](https://user-images.githubusercontent.com/26518879/99525373-a038b600-2991-11eb-8808-12e9444c3256.png)

So we need to do this:
![image](https://user-images.githubusercontent.com/26518879/99525448-bba3c100-2991-11eb-977a-05a5ab5ec989.png)

2. Translating this does not work:
![image](https://user-images.githubusercontent.com/26518879/99525527-da09bc80-2991-11eb-9fca-af2d2eafd0f0.png)

So we need to duplicate the filter (add the additional language):
![image](https://user-images.githubusercontent.com/26518879/99525600-f1e14080-2991-11eb-8c3e-fdf4ec7853bf.png)

![image](https://user-images.githubusercontent.com/26518879/99525638-032a4d00-2992-11eb-9461-fbd8c980a0c4.png)

**Comment by eXistenZe** [comment]
Chasing down the wrong rabbit hole could get ugly :)
If you need more details I'll try to be more precise.

**Comment by iJungleboy** [comment]
There are a few things that confuse me here

1. Why use separate id-parameters? Basically the site already has a different root, so the page knows what language it's in. You don't need to create multiple view definitions and you don't need multiple parameters at all. 
1. If you do need to stack parameters, you can also use one filter and do `[QueryString:Param1||[QueryString:param2]]`

Can you tell me why you even went the way to use 2 url parameters, and 2 view definitions with the same view? again I think it's completely unnecessary.

**Comment by eXistenZe** [comment]
It's all about friendly urls, not functionality.

The parameter name is as important as the value. So you have two choices:
1. mywebsiteaboutcooking.com/lang/cool-recipies/**some-cookies-but-untranslated**/awesome-sweet-caramel
2. mywebsiteaboutcooking.com/lang/cool-recipies/**some-great-translated-cookies**/awesome-sweet-caramel

I love the second one. Translating the parameter name creates a nice effect. This implies 2sxc knowing 2 different parameters for the same view. And different filters in the query.

**Comment by iJungleboy** [comment]
ok. then I guess having two view-definitions makes sense, so just use the simple token-trick to "fallback" to the other token if the first one is empty.

**Comment by eXistenZe** [comment]
Sorry. Can you explain this "trick" to a non-tech user?

**Comment by iJungleboy** [comment]
Tokens have a source and a value. `[QueryString:id]` means it should come from `QueryString` and get the value `id`. In addition, you can specify a format - usually only used in dates - like `[DateTime:Now|yyyy]` which would use the C# string-format placeholders. 

But you can add another `|` and specify what to use if nothing is found. so `[QueryString:id||0]` would default to `0` if the url returns null/empty. Or `[QueryString:id||[App:Settings:DefaultId]]` would evaluate the second token as a fallback, getting the App-setting for the default id. 
So the example above checks one parameter, and if it's empty, checks the other one. 
See also https://2sxc.org/en/docs/Feature/feature/4677

**Comment by eXistenZe** [comment]
So can I use [App:Settings:qsname] in view settings URL key and value filter? To get the parameter name from the settings or resources? Will it get the current language value?

**Comment by iJungleboy** [comment]
You can only use it in the query. That's what it's for. Not sure about languages.

But you should actually use this: `[QueryString:career-en||[QueryString:careen-pt]]` - the app-settings was just an example.

**Comment by eXistenZe** [comment]
Could you double-check the syntax, please?
I've tried [QueryString:career-pt||QueryString:career-en] and [QueryString:career-pt]||[QueryString:career-en]
None work.

**Comment by iJungleboy** [comment]
Basic token: `[QueryString:career-en]`

Basic Token with Fallback: `[QueryString:career-en||VALUE-TO-USE-INSTEAD]` - must be within the `[original||fallback]` brackets
So you should use `[QueryString:career-en||[QueryString:careen-pt]]`

So `[token1:key1||fallback]` where fallback can be any text, or another token - `[token1:key2||[token2:key2||[token3:key3]]]` is also valid, but from [token1:key1||[token2:key2],[token3:key3]]` etc. (the last example would get two tokens and separate with a `,` if the initial token was blank/null.
