### ISSUE TITLE
Overwrititing of ImageResizing.NET DLLs and web.config settings

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#2248]
**I'm submitting a ...** 
[x] feature request
[x] not sure

**...about**
[x] other / unknown

**Current behavior**
Upgrading 2SXC overwrites all custom <resizer>...</resizer> configurations and licensing in the web.config file and all newer DLLs. We have a licensed version on a customer site with additional plugins like RemoteReader that result in version conflicts.

**Expected behavior**
When 2SXC updates, it should only upgrade older DLLs and not overwrite newer ones. Perhaps it can also merge in updates to the web.config rather than overwriting any existing configurations.

**Minimal reproduction of the problem with instructions**
Start with a site using an older version of 2sxc. Install the latest version of ImageResizing.NET from NUGET in a custom module and notice the DLLs in the bin directory. Make updates to the <resizer>...</resizer> section of web.config, along with licenses and other plugin settings. Upgrade 2sxc and notice that the DLLs and web.config are overwritten.

**What is the motivation / use case for changing the behavior?**
We would like to be able to upgrade 2sxc continually without having the backup/restore DLLs and web.config settings each time.

* **2sxc version(s):** 11.10.00
* **DNN:** 9.8.0

**Comment by iJungleboy** [comment]
Unfortunately this is really, really hard to do in DNN - we have almost no control over it. 

DNN has a fairly odd way of tracking DNN versions and how the dependencies work, and our code is very restricted during installation. So even though we could probably do it technically, it would mean a few days of work - and even then it's not clear if all would be successful. 

So unfortunately we cannot do this :(.

**Comment by tpperlman** [comment]
Thank you for the quick reply, I do appreciate the limitations of DNNs install routine. I logged this issue partly for your feedback, and also for others to consider when using more advanced implementations of ImageResizing.NET.
