### ISSUE TITLE
Get other languages in templates

### ISSUE THREAD

**Issue by josip8** [2sic/2sxc#2259]
**I'm submitting a ...** 

[x] feature request

**...about**   
[x] Razor templating
[x] JS development
[x] APIs like REST

Is it possible get other languages iz razor and/or 2sxc api?

For example something like this, where we can pass language:

```
const sxc = $2sxc(@Dnn.Module.ModuleID);
const language = 'en';
sxc.webApi.get(`${language}/app/auto/query/AllOZPData/SortedDescAll`).success(data => console.log(data));
```
I know it can be fetched like this:
```
const headers = { tabid: '193', moduleid: '604' };
const language = 'en';
fetch(`${window.location.origin}/${language}/api/2sxc/app/auto/query/AllOZPData/SortedDescAll`, { headers })
```
But here with this approach I need to put `tabid` and `moduleid` in request headers. 
It would be also great if there is a razor way.

**Comment by iJungleboy** [comment]
AFAIK there are a few solutions

1. if you give it the full path and use sxc.webapi it should still add the headers but not modify the url
1. you can also add `?tabid=193&moduleid=604` to the url to not need the headers
1. in razor you can always convert the dynamic entity into a real entity (which doesn't have .FirstName etc. but is a mighty object). Example: `AsEntity(yourDynamicEntity).GetBestValue("FirstName", new [] { "it-IT" }) should get what you need. Check out the docs for more details on GetBestValue https://docs.2sxc.org/api/dot-net/ToSic.Eav.Data.Entity.html#ToSic_Eav_Data_Entity_GetBestValue_System_String_System_String___
