### ISSUE TITLE
TinyMCE has expiry message

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2269]
**I'm submitting a ...** 
[x] not sure

**...about**   
[x] edit experience / UI

**Current behavior**
When my content editor edits content that uses TinyMCE, he gets: "Your access to TinyMCE will expire on 25 Februrary 2021. Please either contact your administrator or upgrade your account using the instructions available here."

**Expected behavior**
No warning

**Minimal reproduction of the problem with instructions**
Make a content type with TinyMCE and then go edit it

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **2sxc version(s):** 9.40.1 
* **Browser:** [all ]
* **DNN:** [all | 9.3.1 ] 
* **Language:** [any]

**Anything you would like to add**

![large](https://user-images.githubusercontent.com/8751936/101060950-d440d900-3544-11eb-8d31-d5542df3103c.png)

I'm assuming that upgrading to the latest LTS will correct this issue but I thought I would mention it.

**Comment by iJungleboy** [comment]
I had never seen this before, thanks for reporting it. I would never have expected such a message to suddenly appear. 

Could you check your F12 and tell us what CDN is being used for this? Just to check if we're hopefully using a different one today.

**Comment by PagnoDunadan** [comment]
I think 2sxc 9 uses `cdn.tiny.cloud`. Newer 2sxc uses `cdnjs.com`.

**Comment by ajplopez** [comment]
Looks like it's using https://cdn.tinymce.com/4.6/tinymce.min.js

**Comment by jeremy-farrance** [comment]
Glad this is already reported. If we are staying on the LTS, does that mean there will be an 11.7.4 with the fix?

**Comment by ajplopez** [comment]
FYI: I upgraded to the latest version, 11.10.1 and the issue was resolved.

**Comment by iJungleboy** [comment]
@jeremy-farrance basically any version 11 (and probably 10 already) have that fixed. We accidentally used the tinyMCE CDN for a while in V9, but that was unintended, as TinyMCE tries to motivate users to license the product.

**Comment by jeremy-farrance** [comment]
@iJungleboy, I have an Intranet site stuck on Dnn 8.00.04 and 2sxc 9.43.2 that is now showing the expiration method. Upgrading is not an option due to the environment. Can you give me enough details so I can manually get this fixed?

**Comment by iJungleboy** [comment]
I'll try to create instructions for this...

**Comment by iJungleboy** [comment]
I created a checklist which will probably work- could you try and post your feedback?

https://azing.org/2sxc/r/Ay7TYQxx

**Comment by jeremy-farrance** [comment]
This worked, thank you!!

> I created a checklist which will probably work- could you try and post your feedback?
> 
> https://azing.org/2sxc/r/Ay7TYQxx

**Comment by jeremy-farrance** [comment]
This is failing again now. Looks like they really turned off the site and something in Angular is point at cdn.tinymce.com. I have this happening on 2 separate sites, both still using 2sxc 9.43.2 on Dnn 8.00.04.

![image](https://user-images.githubusercontent.com/653301/116159650-3f3aaa00-a6b6-11eb-9305-cf825239e09d.png)

**Comment by jeremy-farrance** [comment]
Also, just to see if anything might somehow be different, I switch the config.js and config.min.js to point to the jsdeliver versions. As expected, made no difference.

```
                            case "string-wysiwyg-tinymce":
                                config.Assets = "//cdn.jsdelivr.net/npm/tinymce@4.6.7/tinymce.min.js\n" +
                                    "../edit/extensions/field-string-wysiwyg-tinymce/set.js";
                                applyChanges = true;
                                break;
```

**Comment by jeremy-farrance** [comment]
On one of the sites I was able to upgrade to fix this. Some of my older apps needed a little help to get working again (e.g. added `@using ToSic.Sxc.Data` to handle an older use of "as List<DynamicEntity>" and a few other small things like that.

**Comment by jeremy-farrance** [comment]
**WORKAROUND**

For a quick and simple fix you can simply switch the WYSIWYG field input type to the default Dnn one.
![image](https://user-images.githubusercontent.com/653301/116259776-b8301500-a73b-11eb-9acb-143e33683b53.png)

To do this, simply go in to the app's Admin panels, Data tab, for the Content-Type edit the Fields. Under Input Type, change "wysiwyg" to the Dnn Standard one.
 
Only down side is that you will possibly need to do this in dozens and dozens of fields across many content-types.

**Comment by iJungleboy** [comment]
@jeremy-farrance I agree that all this can be done, but an update would be much, much better and would get you the latest, greatest and securest 2sxc. 

> So i really urge people to update - don't monkey patch your systems 🙈

**Comment by jeremy-farrance** [comment]
I completely agree, but upgrades are not always easy. They can require backups, code changes, and hours or work. Often, having a) a quick workaround, b) a near term fix, and c) the later option to upgrade is the best fit here in reality. :)
