### ISSUE TITLE
Normal "Edit" seems to fail

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#227]
In an app with a template (has content type and default /demo enttiy)

Tried pressing edit, fails:
![image](https://cloud.githubusercontent.com/assets/5321186/7445417/886ac4d6-f1b2-11e4-8c74-9785c3076ec8.png)

Message in debugger 
![image](https://cloud.githubusercontent.com/assets/5321186/7445419/91d718ee-f1b2-11e4-9eb7-7222d364a17c.png)

**Comment by raphael-m** [comment]
Can't reproduce - tested with latest PreV7 branch.

**Comment by iJungleboy** [comment]
I'll demo on my PC - edit-list seems to work, edit-item not.

**Comment by raphael-m** [comment]
Sorry my mistake, I can reproduce it now...
