### ISSUE TITLE
Cannot use menu bar after upgrade to 11.11.0

### ISSUE THREAD

**Issue by TopCat6** [2sic/2sxc#2283]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   

[x] admin experience UI

**Current behavior**

Getting '404 not found' when clicking the toolbar icons

**Requested URL**	   http://localhost:80/dotnetnuke/dotnetnuke/desktopmodules/tosic_sexycontent/dist/ng-edit/index.html?sxcver=11.11.0.19903
**Physical Path**	   C:\DotNetNuke\Website\dotnetnuke\desktopmodules\tosic_sexycontent\dist\ng-edit\index.html

The URL should only have one 'dotnetnuke/' and the Physical Path should not have a 'dotnetnuke\\' after 'Website\\'
**Expected behavior**

The menu would appear instead of a 404 error page
**Minimal reproduction of the problem with instructions**

Create an installation of DNN at  C:\DotNetNuke\Website
Install 2sxc 11.11.0
Try to use the Edit bar

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10
* **2sxc version(s):** 11.11.0  
* **Browser:** [Firefox 83 ]
* **DNN:** [9.8.0 ] 
* **Language:** [English ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Just so we're looking for the right culprit

Is DNN running in a sub-folder of IIS, or is this a sub-portal called "dotnetnuke"

**Comment by TopCat6** [comment]
DNN is running in a sub-folder of IIS.  All sub-portals have URLs like this: //localhost/dotnetnuke/portal-name
Here is the folder layout... folders like bin are located in the Website folder:

![image](https://user-images.githubusercontent.com/17517455/101808154-d4078700-3aca-11eb-8de4-651f3174848a.png)

Here is the IIS Manager layout:

![image](https://user-images.githubusercontent.com/17517455/101808218-ec77a180-3aca-11eb-93ef-67bfd22e6a6f.png)

**Comment by iJungleboy** [comment]
found and fixed, will release in a few mins.

**Comment by iJungleboy** [comment]
No, it's in 11.11.02 - not quite published yet - will come today :)

**Comment by TopCat6** [comment]
Confirm fixed in 11.11.02. Works well. Thanks.
