### ISSUE TITLE
ADAM doesn't accept correct extension if uppercase.

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [2sic/2sxc#2284]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management

**Current behavior**

If you create field of type Hyperlink and you attempt to upload image with acceptable extension but uppercase it's not accepted.

**Expected behavior**

Windows treats extension without case sensitivity, so I think ADAM should as well.

**Minimal reproduction of the problem with instructions**

 - create some entity or open existing 
 - add field of type hyperlink
 - adjust field settings:
   - default dialog: Image Manager
   - Show Image Manager
  - Show Adam
  - buttons: adam,more
 - save changes
 - create new entity of this type or open existing one
 - try to upload image with extension ".JPG" and you'll get this error:
![chrome_wfdxVhzuPA](https://user-images.githubusercontent.com/21691213/101803881-ad247180-3b19-11eb-9832-4618e0dffa33.png)
 - try to upload image with extension ".jpg" and it will upload successfully

**What is the motivation / use case for changing the behavior?**

People usually expect extensions to not be case sensitive because that's default behaviour of Windows. So this ADAM's behaviour is confusing.

**Please tell us about your environment:**

Windows 10
Local website

* **2sxc version(s):** 11.5.0  
* **Browser:** Chrome Version 87.0.4280.88 (Official Build) (64-bit)
* **DNN:** 9.6.1
* **Language:** English

**Comment by iJungleboy** [comment]
thx for spotting this, we'll try to resolve in near future.

**Comment by iJungleboy** [comment]
Found and fixed. 

It only occured if you only specified `jpg` instead of `*.jpg` - but it's fixed in 11.11.02
