### ISSUE TITLE
App Import - "Toggle Success Messages" doesn't show anything

### ISSUE THREAD

**Issue by BeniGemperle** [2sic/2sxc#229]
![toggle success messages](https://cloud.githubusercontent.com/assets/6669093/7449983/d98f5330-f23f-11e4-9420-cad8785da24c.png)

After a successful App Import nothing happens when clicking "Toggle Success Messages". Nothing is logged to the console. Probably the jQuery-Selector ".dnnFormSuccess" finds no DOM-Element to toggle.

**Comment by iJungleboy** [comment]
no priority - will close for now.
