### ISSUE TITLE
Can't connect to the dialog and didn't activate the old Telerik

### ISSUE THREAD

**Issue by rthoeni** [2sic/2sxc#2291]
**I'm submitting a ...** 

[x] not sure

**...about**   
[x] other / unknown

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

Steps for this note: create a link to a website in the text field.
Can't connect to the dialog - you are probably running a new DNN(v.8 +) and didn't activate the old Telerik components. Please install these in the host > extensions to get this to work

<img width="617" alt="Bildschirmfoto 2020-12-14 um 11 58 35" src="https://user-images.githubusercontent.com/12658708/102073894-4696a080-3e04-11eb-8d72-d16847a0fbae.png">

I can wait approximately 2-3 min and after the Selection field with the sides is displayed.

<img width="717" alt="Bildschirmfoto 2020-12-14 um 12 05 22" src="https://user-images.githubusercontent.com/12658708/102074757-89a54380-3e05-11eb-9114-ac142cb17b2b.png">

**What is the motivation / use case for changing the behavior?**

in the DNN 9.8.0 fresh install I have remove the Telerik in my DNN. 
Telerik will no longer be used in the future.
**Please tell us about your environment:**

* **2sxc version(s):** 11.11.1  
* **Browser:** [iOS 14.0.1 Safari ]
* **DNN:** [9.8.0 ] 
* **Language:** [German ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
I agree. Basically it sees to work as expected, but the error shouldn't be shown. 

Probably best to have @PagnoDunadan have a look at this.

**Comment by iJungleboy** [comment]
Fixed in EditUI for 11.11.03 (after quick-1 release)
