### ISSUE TITLE
Cannot delete content types or fields in content types

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2303]
I*I'm submitting a ...** 
[x] bug report

**...about**   
[x] admin experience UI

**Current behavior**
I'm using the Content module and I added a content type and added some fields to that content type. I decided I didn't need certain fields so I tried to delete them but I get an error saying that there was a status 405 error. Moreover, I tried to delete the whole content type and I got the same error. So it seems like if a field is added, it's there forever and I can't delete it.

![Screen Shot 2020-12-15 at 10 19 10 AM](https://user-images.githubusercontent.com/8751936/102256078-c766a280-3ebf-11eb-86cd-6c1e0d569bed.png)
![Screen Shot 2020-12-15 at 10 19 15 AM](https://user-images.githubusercontent.com/8751936/102256088-c9c8fc80-3ebf-11eb-971d-ae2870c3d8e5.png)

**Expected behavior**
I need to clean up my content types and fields by deleting old fields and content types. I've been able to do this in the past, just not with this new version of 2sxc.

**Minimal reproduction of the problem with instructions**
1. Create a content type
2. Create a few fields in it that perhaps have spelling mistakes or are redundant
3. Create a template that uses this content type
4. Try to delete the content type or even just the fields and you'll get errors.

**What is the motivation / use case for changing the behavior?**
Cleanup and maintenance

**Please tell us about your environment:**
Shared hosting

* **2sxc version(s):** 11.11.13  
* **Browser:** [all ]
* **DNN:** [9.7.2 ] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**
It's a new site that was always DNN 9.7.2. I originally had 11.11.0 and just today upgraded to 11.11.13 and the problem persists.

**Comment by iJungleboy** [comment]
ok, we'll check this asap.

**Comment by iJungleboy** [comment]
I just tried this and cannot reproduce the issue. Deleting fields and content-types worked without a problem. 

Almost certainly a repeat of the WebDav issue #2205 - pls check, otherwise we'll re-open this issue.

**Comment by ajplopez** [comment]
Thanks, turns out it was the same as #2205 - I have followed Jeremy's suggestion of adding the <remove> tags from the web.config and it fixed the issue. For anyone else searching, take a look here: https://github.com/2sic/2sxc/issues/2205#issuecomment-705647892

**Comment by jeremy-farrance** [comment]
Closure

In case someone else finds this problem and does NOT have access to the server-wide IIS/dotnet config, you can also do it per site in Dnn's web.config:

See [Issue 2303](https://github.com/2sic/2sxc/issues/2303)
 
![image](https://user-images.githubusercontent.com/653301/102403635-30c3df80-3fac-11eb-9643-4c50ae0872d0.png)
