### ISSUE TITLE
Content Editors role cannot edit content

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2313]
**I'm submitting a ...** 
[x] bug report

**...about**   
[x] edit experience / UI

**Current behavior**
When I log in as a Content Editor (custom DNN role that just has edit permissions), the page pops up a 403 error.

See attached screenshots.

![Screen Shot 2020-12-18 at 5 18 45 PM](https://user-images.githubusercontent.com/8751936/102677068-74a61880-4155-11eb-9d1a-7045e71c613b.png)

Error from the toolbar.

![Screen Shot 2020-12-18 at 5 20 37 PM](https://user-images.githubusercontent.com/8751936/102677070-75d74580-4155-11eb-8934-83ea0e8e10ac.png)

**Expected behavior**
To be able to edit content with a user in the Content Editors role.

**Minimal reproduction of the problem with instructions**
Create a role called "Content Editors".

Using your SuperUser account, create any type of content or app and drop it on the page.

Using your Content Editor user, log in and then try to edit the content and there's an error.

![Screen Shot 2020-12-18 at 5 18 45 PM](https://user-images.githubusercontent.com/8751936/102677025-34df3100-4155-11eb-9851-9d616a41f8af.png)

**What is the motivation / use case for changing the behavior?**
Seems to be a bug.

**Please tell us about your environment:**
Shared hosting. For what it's worth, this is the same site where I witnessed an issue with deleting content types/fields.

* **2sxc version(s):** 11.11.2  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [all | 9.7.2 ] 
* **Language:** [English]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Thx for this, we'll check. But probably can't fix before x-mas.

**Comment by ajplopez** [comment]
Another update: I upgraded a completely different website with 11.11.3 and the Content Editors role gets the same edit issue. I had to upgrade the user to be an Administrator and that worked. So there seems to be a problem for the non-admin roles.

**Comment by iJungleboy** [comment]
@ajplopez could you tell me how these users have edit-permissions? maybe show me the role and page configuration so I can see what to work on.

**Comment by ajplopez** [comment]
See screenshots.

![Screen Shot 2021-01-13 at 8 35 51 AM](https://user-images.githubusercontent.com/8751936/104481318-80310780-557a-11eb-8eda-5d4d4a63ce15.png)
![Screen Shot 2021-01-13 at 8 36 40 AM](https://user-images.githubusercontent.com/8751936/104481323-81623480-557a-11eb-8815-a451f72c7c6b.png)

It's a very standard set up where I have a Role called "Content Editors" and then I made my homepage "viewable and editable" by content editors via the page settings. All of the modules on the homepage inherit the settings from the page.

![Screen Shot 2021-01-13 at 8 37 54 AM](https://user-images.githubusercontent.com/8751936/104481478-b1a9d300-557a-11eb-8595-b36609f11989.png)

**Comment by iJungleboy** [comment]
thx, we'll check.

**Comment by SCullman** [comment]
Same here, same procedure. All content editors are locked out....

**Comment by iJungleboy** [comment]
I can reproduce...

**Comment by iJungleboy** [comment]
was accidentally introduced - probably in 11.11.03 pre1 - will try to fix asap.
