### ISSUE TITLE
Question: Web API + JWT

### ISSUE THREAD

**Issue by Rodien** [2sic/2sxc#2318]
I just have question about the 2sxc Web API.

I am using the 2sxc blog app and I want to make crud api for external use. 
So, the user needs to be a Admin.

Can I verify that the user has an admin permission using JWT? 

I am trying to figure out how to access a 2sxc api which has admin permission.

![image](https://user-images.githubusercontent.com/50739829/103385914-be4f1580-4afc-11eb-85a3-ecabcb6f4f49.png)

**Comment by iJungleboy** [comment]
You have closed this issue - does it already work?

**Comment by Rodien** [comment]
Not really. 

I just wanted to know if someone have an idea on how to achieve this before I dive into it, so I don't have to waste a lot of time for no reason.

I will be looking into this the coming weeks.

**Comment by iJungleboy** [comment]
So I'm 90% sure it should just work, because 2sxc doesn't really care how the authentication works, it just asks DNN if the user is an admin.

**Comment by Rodien** [comment]
It was easy. 

I just had to add Authorization to the header with my Bearer token. 😅

I thought for some reason that I would have to do more than that😃

**Comment by iJungleboy** [comment]
Gongratulations, awesome! glad it works.
