### ISSUE TITLE
Bug: SuperUser / Administrators can't remove items from list

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2327]
[x] bug report

**...about**  
[x] edit experience / UI

**Current behavior**
I can't remove items from a list. Clicking on the "remove" minus icon prompts removal, but then nothing happens after confirming.

![Screen Shot 2021-01-18 at 11 14 53 AM](https://user-images.githubusercontent.com/8751936/104955082-70e8fa00-597e-11eb-930a-251bf4ba0cf7.png)

![Screen Shot 2021-01-18 at 11 15 01 AM](https://user-images.githubusercontent.com/8751936/104955093-747c8100-597e-11eb-887f-c2488ec00211.png)

No errors in the console appear.

**Expected behavior**
As usual, the item should be removed from the list

**Minimal reproduction of the problem with instructions**
1. Create a content module with a list of content
2. Add a couple of items to the list
3. Try to remove an item using the EditTag toolbar with the "remove" minus icon.

**What is the motivation / use case for changing the behavior?**

It's a bug.

**Please tell us about your environment:**

* **2sxc version(s):** 11.11.3  
* **Browser:** [all]
* **DNN:** [9.3.2 ] 
* **Language:** [English ]

**Anything you would like to add**
My content editor (a user in the Administrator role) first reported it. I confirmed the same issue with my SuperUser account.

**Comment by iJungleboy** [comment]
thx, will check.

**Comment by iJungleboy** [comment]
I cannot reproduce.
Using 11.11.03 pre (latest) - and the normal content-app Link-list. It just worked. Can you re-check your template?

**Comment by ajplopez** [comment]
I patched the module to the very latest https://github.com/2sic/2sxc/tree/v11.11.03-quick2

I updated the templates to use @inherits ToSic.Sxc.Dnn.RazorComponent and @Edit.TagToolbar(Content, actions: "edit,new,remove,instance-list,moveup,movedown,add-existing")

I even tried just using @Edit.TagToolbar(Content) just to see if it made any difference. I even changed the page skin back to Xcillion to rule anything out. I tried different lists to see if it was just one particular list. I tried incrementing the CDF (it's not composite or minified anyway), clearing cache, and restarting. 

But it still doesn't allow me to remove items. Every other toolbar control works as expected, just not "remove".

**Oddly**, I checked another DNN 9.3.2 with the same module version installed (perhaps quick1) and it does seem to work as expected.

I can't seem to find much difference between the two sites. Is there any other area that I can check?

**Comment by ajplopez** [comment]
FWIW: PlantAnApp is installed on this particular instance. Not sure if that makes any difference.

**Comment by ajplopez** [comment]
I just patched 2sxc to https://github.com/2sic/2sxc/releases/tag/v11.11.03-quick3 and now I'm getting an error in the console when I try to remove an item from a list.

<img width="1426" alt="Screen Shot 2021-01-19 at 10 16 13 AM" src="https://user-images.githubusercontent.com/8751936/105076045-6d697780-5a3f-11eb-8fb0-7fe8d32227f2.png">

**Comment by ajplopez** [comment]
More context.

![imgpsh_mobile_save](https://user-images.githubusercontent.com/8751936/105100328-0315fe80-5a62-11eb-8d9f-798a0324ba11.jpg)

![imgpsh_mobile_save-1](https://user-images.githubusercontent.com/8751936/105100339-07421c00-5a62-11eb-9040-8b3421de5b92.jpg)

**Comment by ajplopez** [comment]
Turns out to be the similar solution to https://github.com/2sic/2sxc/issues/2205. 

The solution is to add the following to your web.config. The best place is at the end of the Modules and Handles sections.

```
<system.webServer>
    <modules>
      <remove name="WebDAVModule" />
    </modules>
    <handlers>
      <remove name="WebDAV" /> 
    </handlers>
</system.webServer>
```

**Comment by iJungleboy** [comment]
ok, thx. Seems like the "DELETE" verb is causing a lot of trouble :(. 
We may have to reconsider using another verb for this :(
