### ISSUE TITLE
Install injects staticContent section a second time to webconfig

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#2334]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] Installation

**Current behavior**
Current web.config has already a staticContent section.
When 2sxc installs, it adds it a second time, breaking the server installation.

It is super easy to discover and to fix, and I already know that now for a too long time. 
Installing 2sxc and editing web.config was already part of my installation recipe.

Problem is this section in the manifest:
```xml
        <node path="/configuration/system.webServer" targetpath="/configuration/system.webServer/staticContent" action="update" collision="ignore">
          <staticContent>
            <remove fileExtension=".webp" />
            <mimeMap fileExtension=".webp" mimeType="image/webp" />
          </staticContent>
        </node>
```

**What is the motivation of this report**
I am going to submit a PR.

**Comment by iJungleboy** [comment]
awesome thx! I'll review asap.

**Comment by SCullman** [comment]
Dogfooding the new release, I must admit that it wasn't a success on production. 

It still injected a second section to the web.config:
```xml
      <staticContent>
        <remove fileExtension=".svg" />
        <mimeMap fileExtension=".svg" mimeType="image/svg+xml" />
        <remove fileExtension=".woff" />
        <mimeMap fileExtension=".woff" mimeType="font/x-woff" />
        <remove fileExtension=".webp" />
        <mimeMap fileExtension=".webp" mimeType="image/webp" />
      </staticContent>
      <staticContent />
```

But this doesn't happen on every server. I will follow up on that.

**Comment by SCullman** [comment]
It looks like the web.config of my broken server uses  [location  elements](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/b6x6shw7(v=vs.100)?redirectedfrom=MSDN) for `system.webServer`.  
DNN can usually [handle location elements](https://github.com/dnnsoftware/Dnn.Platform/blob/a9d2dd7258809aae9537390fa77077be85483543/DNN%20Platform/Library/Services/Installer/XmlMerge.cs#L373), but maybe this code could be optimized.

**Comment by iJungleboy** [comment]
Thanks, really appreciate it.

**Comment by iJungleboy** [comment]
Any improvements on this?

**Comment by iJungleboy** [comment]
any update on this? otherwise I'll close for now. 

Did your change introduce new problems, or just not fix what you had expected?

**Comment by SCullman** [comment]
My change doesn't fix the issue completely. It doesn't address the issue when [location  elements](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/b6x6shw7(v=vs.100)?redirectedfrom=MSDN) within web.config are involved.
For any further optimizations, it would require changes in the DNN core.

**Comment by iJungleboy** [comment]
That's a bummer, then I'll close this.

Do you think your patch introduced new problems, or can we leave it in?

**Comment by SCullman** [comment]
Please leave it in.  It is still the best practice and now in sync with dnn core.
And, if it still fails, there is only a single `<staticContent />` to remove, which is less noise and better to detect.
