### ISSUE TITLE
2sxc and dependencies

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#2336]
**I'm submitting a ...** 
[x] not sure

**...about**   
[x] other / unknown

**Current behavior**
DNN installs several assemblies into /bin/2sxc
Some of them are also part of the DNN distribution, e.g. `Microsoft.Extensions.DependencyInjection.dll`.
This is a quite old v1.1. DNN itself also installs the same assembly to /bin, but in version 2.1.1 for DNN9.8.

Thing is that 2sxc now also adds binding redirects, but not in the default way. It does it by manipulating web.config.
```xml
  <node path="/configuration/runtime/ab:assemblyBinding"
        action="update"
        collision="overwrite"
        targetpath="/configuration/runtime/ab:assemblyBinding/ab:dependentAssembly[ab:assemblyIdentity/@name='Microsoft.Extensions.DependencyInjection'][ab:assemblyIdentity/@publicKeyToken='adb9793829ddae60'][ab:bindingRedirect]"
        nameSpace="urn:schemas-microsoft-com:asm.v1"
        nameSpacePrefix="ab">
    <dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
      <assemblyIdentity name="Microsoft.Extensions.DependencyInjection" publicKeyToken="adb9793829ddae60" />
      <codeBase version="1.1.0.0" href="bin\2sxc\Microsoft.Extensions.DependencyInjection.dll" />
      <bindingRedirect oldVersion="0.0.0.0-1.32767.32767.32767" newVersion="1.1.0.0"/>
    </dependentAssembly>
  </node>
```
We can all be lucky that no one is using new functionality of dependency injection, as everything is redirected to that old version.

No one but me. My team build a new internal component, following best practices and targeting netstandard2.0. It used dependency injection and a few other assemblies which have also copies in older versions within 2sxc/bin.

If they would have been located in bin, they would have been replaced, and the dnn installer would have taken care to update the binding redirects, as my manifest included the version number of the assemblies.

Well, it did not work. My new module, which worked in several installations, failed in production. Unfortunately, error logging is bad during dependency injection.  It took a long time to detect the reason: 2sxc and it redirects. When I installed 2sxc also on a dev machine, I was finally able to reproduce the issue.

My workaround for going live: 
* Removed DI , at least for that release
* Switched to another nuget package that did not have the same dependencies as 2sxc had.

**Expected behavior**

2sxc knows its responsibility and respects the dependencies

**What is the motivation / use case for changing the behavior?**

Much frustration, and an accidental late-night installation of a prerelease of 2sxc that frustrated even more people. I do not wish anyone the same.

**Comment by SCullman** [comment]
An addition, as my words may sound harsh and attacking. I love 2sxc! and support is just awesome. 

And I am sure that the intention of placing the assemblies into a subfolder was guided by the wish of protection and isolation. 

Unfortunately, I don't have a constructive suggestion on how to address this either. I was also not able to straighten the binding redirects by hand. Then my module ran, but 2sxc did not :-(

Maybe it would be the best to update the dependencies to the same version as current dnn and to place them directly into bin. 
The hardest job is to clear up the binding redirects.

**Comment by iJungleboy** [comment]
Hi Stefan - sorry for the problems 😢

I understand your frustration. ATM 2sxc is stuck with these versions because they are the versions which work in DNN 7.4.2 and that's still supported in 2sxc 11. The DLL versions DNN includes require a newer .net standard and newer .net framework, so the only way to live side-by-side is to include the versions we need and put them in a subfolder. 

But I believe that if you use the same versions an DNN uses, your application will also just work - because DNN also uses it's DLLs and ignores the 2sxc DLLs. So side-by-side should just work - but yes, DLL hell can be ... hell. 

So as of now we cannot update our DLLs, but I hope you'll be able to use the DNN versions and it should just work. 

Unless I'm mistaken an DNN does actually use our DLLs, but I don't think it would run in that case.

**Comment by iJungleboy** [comment]
As of now I'm not sure if there is something specific we can do here, so I'll close this for now.
