### ISSUE TITLE
Edit.Toolbar/TagToolbar: item-history

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#2337]
**I'm submitting a ...** 
[x] bug report

**...about**
[x] Razor templating

**Current behavior**
Adding buttons for item-history no longer work

**Expected behavior**
Prior to some recent releases you could add a command to the Edit.Toolbar with item-history action. This action no longer seems to be supported and the button appears blank an no action is performed when clicked. I also tried adding this action to the Edit.TagToolbar but that also didn't work.

**What is the motivation / use case for changing the behavior?**
Ideally, existing code should work when 2SXC is upgraded but perhaps the action name was deprecated or has changed?

* **2sxc version(s):** 11.11.3
* **Browser:** All
* **DNN:** 09.08.00
* **Language:** Any

**Anything you would like to add**
 I've seen references to entity-history in some docs, but this action does not seem to work either.

**Comment by iJungleboy** [comment]
This functionality has moved. Now history is directly integrated into the edit dialog (top right area of the dialog).
