### ISSUE TITLE
Warn user early when installing on a non-standard SQL (with custom object qualifier)

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#234]
This is only an issue when installing it new (upgrades don't have this issue, as the first install was never possible). 

So in this case, the install-sql should actually start with 1-line checking if it has a custom object qualifier and if it does - it should already throw an error. "Your SQL installation is non-standard using a Custom Object Qualifier. 2sic uses the standard Microsoft Entity Framework which doesn't work well with this feature - installation aborted."

It would save a lot of support questions

**Comment by flinty** [comment]
Is there any way to get around this installation issue other than removing the object qualifier from the web config?

Also what might be the downsides of removing the object qualifier on the DNN installation?

**Comment by BeniGemperle** [comment]
See Mitchel Sellers Post for more details about the evil Object Qualifier in DNN: http://mitchelsellers.com/blogs/2010/03/23/the-dotnetnuke-object-qualifier-why-i-think-it-is-evil.aspx
