### ISSUE TITLE
Some errors after upgrading to 11.11.2

### ISSUE THREAD

**Issue by trouble2** [2sic/2sxc#2348]
**I'm submitting a ...** 
[x] bug report => search github for a similar issue before submitting 

**...about**  
[x] edit experience / UI

**Current behavior**
After upgrading on DNN 9.3.2  instance and going into edit mode I'm getting an error popup saying
Had an error talking to the server (status 400)
If you're an advanced user... blablabla...

So I tried again using ? debug=true

This gave me:
error: "Onjuiste aanvraag"
headers: t {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
message: "Http failure response for http://b2b/api/2sxc/app-content/9992aed3-0623-4a63-bf91-4bfe952f5a38/6119bc0d-b86a-49fc-ae2c-e12fe5541bcd/Image/items?subfolder=&usePortalRoot=false&appId=6: 400 Bad Request"
name: "HttpErrorResponse"
ok: false
status: 400
statusText: "Bad Request"
url: "http://b2b/api/2sxc/app-content/9992aed3-0623-4a63-bf91-4bfe952f5a38/6119bc0d-b86a-49fc-ae2c-e12fe5541bcd/Image/items?subfolder=&usePortalRoot=false&appId=6"

**Expected behavior**
A working edit mode without errors

**Minimal reproduction of the problem with instructions**
Well I upgraded on a DNN 9.3.2 with 2sxc 10.25.2. to 11.11.2

**What is the motivation / use case for changing the behavior?**
Just trying to help :-)

**Please tell us about your environment:**

* **2sxc version(s):** 11.11.2
* **Browser:** all
* **DNN:** 9.3.2
* **Language:** Dutch

**Anything you would like to add**

**Comment by trouble2** [comment]
Just tried the same upgrade on a DNN 8.0.4 and I kind of got the same error.
In the debug=true it had some more information:

n
error:
ExceptionMessage: "De objectverwijzing is niet op een exemplaar van een object ingesteld."
ExceptionType: "System.NullReferenceException"
Message: "Bad Request"
StackTrace: "   bij ToSic.Sxc.Dnn.Adam.DnnAdamFileSystem.DnnToAdam(IFolderInfo f) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\Dnn\Adam\DnnAdamFileSystem.cs:regel 193
↵   bij ToSic.Sxc.Dnn.Adam.DnnAdamFileSystem.Get(String path) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\Dnn\Adam\DnnAdamFileSystem.cs:regel 149
↵   bij ToSic.Sxc.Adam.AdamAppContext`2.Folder(String path, Boolean autoCreate)
↵   bij ToSic.Sxc.Adam.AdamOfBase`2.Folder()
↵   bij ToSic.Sxc.WebApi.Adam.AdamTransactionBase`3.ItemsInField(String subFolderName)
↵   bij ToSic.Sxc.Dnn.WebApi.AdamController.Items(Int32 appId, String contentType, Guid guid, String field, String subfolder, Boolean usePortalRoot) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.WebApi\Dnn\WebApi\Adam\AdamController.cs:regel 80
↵   bij lambda_method(Closure , Object , Object[] )
↵   bij System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
↵   bij System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
↵   bij System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
↵--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
↵   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   bij System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
↵--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
↵   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   bij System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
↵--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
↵   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   bij System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
↵--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
↵   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   bij System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
↵--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
↵   bij System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
↵--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
↵   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   bij System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
↵--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
↵   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   bij System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
↵--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
↵   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   bij System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
↵--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
↵   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   bij System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
↵--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
↵   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   bij System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
↵--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
↵   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   bij System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
↵--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
↵   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   bij System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
↵--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
↵   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   bij System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"
__proto__: Object
headers: t
lazyInit: ƒ ()
lazyUpdate: null
normalizedNames: Map(0) {}
__proto__: Object
message: "Http failure response for http://website/impact/desktopmodules/2sxc/api/app-content/09ad77bb-66e8-4a1c-92ac-27253afb251d/038c3057-9894-4d4e-8608-27e4db8af6af/Photo/items?subfolder=&usePortalRoot=false&appId=10: 400 Bad Request"
name: "HttpErrorResponse"
ok: false
status: 400
statusText: "Bad Request"
url: "http://website/impact/desktopmodules/2sxc/api/app-content/09ad77bb-66e8-4a1c-92ac-27253afb251d/038c3057-9894-4d4e-8608-27e4db8af6af/Photo/items?subfolder=&usePortalRoot=false&appId=10"
__proto__: t

**Comment by iJungleboy** [comment]
Since you're specifically using 11.11.02 which is neither an LTS nor the latest release, please update to the latest release (I believe 11.11.04 or 05) and check that.

**Comment by trouble2** [comment]
Looks like that solved it...
