### ISSUE TITLE
Comments in web.config caused by updates and binding redirects

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#2354]
**I'm submitting a ...** 

[x] not sure

**...about**   

I just updated 2sxc and the following error occurred:
![image](https://user-images.githubusercontent.com/5693190/109323970-5a26a480-7854-11eb-8883-18fe4602238d.png)

Web.config is just too big. And I checked the file and it happens because of just too many comments on binding redirects:

Example:
![image](https://user-images.githubusercontent.com/5693190/109324182-9ce87c80-7854-11eb-93ad-d7e6dc0d2094.png)

It is not just 2sxc,  just 50%. It happens the same for my custom modules which are frequently injected via a CI/CD pipeline.

I have no idea if anything can be done to prevent this. Feel free to close the ticket.

If anyone else runs into the issue:
 Open web.config with a decent editor like vs code and remove the comment lines. (And make a copy of the file before.)

**Comment by SCullman** [comment]
Too big: > 256 kb, after removing the comments the config file still had 79kb.

**Comment by iJungleboy** [comment]
Thanks for this. 
We are aware of it and don't really have a good solution. Especially because if anything does go wrong, you're glad you can see what was there before...but after many updates this is a problem. 
Can't solve ATM, so I'll close.
