### ISSUE TITLE
Missing Vertical Scrollbar on Add/Edit Data Item Form Causes Some Usability Issues

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#2358]
**I'm submitting a ...** 
[x] feature request

**...about**
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
When editing a data item, there is no vertical scrollbar for the user to navigate a long form.

**What is the motivation / use case for changing the behavior?**
Unfortunately not all users are as technically savvy as others and can't figure out how to scroll when editing data items. I have advised on using the mouse's scroll wheel (which not everyone has) or two fingers on a touchpad to scroll. I don't believe that every mouse has a scroll wheel and not everyone has a touch pad, and it may pose some challenges for users with disabilities. Furthermore, the arrow keys and page up/down buttons also do not scroll the form.

So perhaps you can remove the CSS class "u-hide-scrollbar" from the form? I could modify the stylesheets myself, but then we'd have to reapply it after every 2SXC upgrade. Thank you for your consideration!

* **2sxc version(s):** 11.11.4
* **Browser:** all
* **DNN:** all 
* **Language:** any/all

**Comment by iJungleboy** [comment]
I understand why you would want this. 

Basically many modern UIs - especially mobile ones - don't have scroll bars any more. Because of this I don't really think we'll change this behavior. 

Has anybody really run into problems because of this, or is it more a personal preference?

**Comment by tpperlman** [comment]
I understand your position, but most users I work with administering sites aren't using mobiles or tablets to do it. The Edit/Admin UI has some different needs than modern customer-facing interfaces.

Personally, I love the mouse-wheel and have no problem with it... but the story is different for desktop users without touch screens. If you try and use the Edit UI without a touchscreen, mouse wheel or touchpad it is basically impossible to scroll down.

TBH, I never even thought about it in all my years developing in 2SXC... but when some new users asked how to scroll down, it took me a minute to explain to them and I could sense a little frustration.

**Comment by iJungleboy** [comment]
Ok. but I don't think we'll do anything as of now, so I'll close this.

**Comment by tpperlman** [comment]
Can you at least advise on how users without touch screens or mouse wheels can scroll the form? Because the arrow keys or page up/down don't work either...

**Comment by iJungleboy** [comment]
This is a really weird question - how would they click on the edit-toolbar without a mouse? and what mouse exists without a wheel? I don't think that exists any more, unless it's a touch-mouse, where you have to move 2 fingers on the surface.

**Comment by tpperlman** [comment]
Not so weird, yes they have mice... but not all have mousewheels. I've explained to ones that have touchpads that they use two fingers, so yes this is a teaching moment for users. But still the only way to scroll the screen is with a mousewheel or touch, no other way. I use 2sxc with all types of businesses and users with all levels of capabilities, and just feel it would be nice to at least have a scrollbar or alternative ways to scroll with arrows or page up/down. Beyond that, I don't know if it is fully functional with users with disabilities (e.g. vision impairment) since we have to meet some strict ADA requirements here in the US.

**Comment by iJungleboy** [comment]
I understand this is frustrating. It's just that we cannot spend a few free hours to assist your customers that don't spend $20 to get a new mouse. AFAIK any mouse purchased the last 5 or 10 years have wheels, so I don't really think we should do anything here. 

BTW: I just tried it and page-up/down work. The cursor must be in a field for it to work, but it does actually work without a problem.
