### ISSUE TITLE
[Feature request] Prefill in public forms edit with cms.run

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2364]
**I'm submitting a ...**
[x] feature request

**...about** 
[x] JS development
[x] APIs like REST

**Expected behavior**
Following this post:
https://stackoverflow.com/questions/66624021/2sxc-cms-run-edit-with-prefill
I need to use prefill when editing entities with
```
$2sxc.cms.run(
    tag,
    {
        action: "edit", 
        entityId: eid,
        prefill: {
            LastEditedBy: "@Dnn.User.Username",
            LastEditedOn: "@DateTime.Now.ToString("yyyy-MM-dd")"
        }
    }
);
```

This is a simple example, but there are many others.

Is this doable?

**Comment by iJungleboy** [comment]
This doesn't look too exotic - it feels like it should already work. I assume you tried it and it doesn't work. Any idea at what level it stops? does the prefill not make it to the UI, or does the UI not apply it?

**Comment by eXistenZe** [comment]
It does not make it to the UI.

**Comment by eXistenZe** [comment]
Any insights on this issue?
Bad code on my part?
Or just not implemented yet?

**Comment by iJungleboy** [comment]
@PagnoDunadan could you look into this?

**Comment by PagnoDunadan** [comment]
Prefill only works when adding new items. Prefill when editing existing item was never a feature.

**Comment by eXistenZe** [comment]
There is a "feature request" in the topic :)

**Comment by eXistenZe** [comment]
If there is a waynto get current date and username with calculated fields, that would work for me.

**Comment by iJungleboy** [comment]
@eXistenZe just for understanding: you only want to apply these fields on edit? or on new and edit?

**Comment by eXistenZe** [comment]
Both.
But with new items I can use razor and js to put those values in.
With existing values there is no option that I known of (unless calculated
fields can pull this off).

**Comment by iJungleboy** [comment]
ok, gotcha.

BTW: the modified-info is already available on `.Modified` - just like `.Created`

Other stuff is still WIP, because we must be careful not to break existing functionality but still keep API clear.

**Comment by iJungleboy** [comment]
As of now you should be able to achieve this using prefill - and in combination with formulas (like resetting it to data.params.replaceTitle) etc. 
So I believe we can close this.
