### ISSUE TITLE
Cannot remove Failed App Install

### ISSUE THREAD

**Issue by BGillham** [2sic/2sxc#2385]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 
[x] admin experience UI
[x] Content Types or data management
[x] DNN parts
[x] other / unknown

**Current behavior**   
Installing 2sxcApp_Directory_02.02.01 and 2sxcApp_Visual-Query-Demos_09.11.05 fails and then unable to remove the orphaned Apps which show in the App Bar.

**Expected behavior**   
Clean delete of failed App Install.

**Instructions to Reproduce the Problem**

Install the Apps mentioned above.
**Why change the behavior?**  
Failed installs should be reversed out completely.
**Your environment**  
IIS v10 / DNN9.9.0 / 2sxci 11.12.0
* **2sxc version(s):** 11.X.X  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [all | 7.4.2 | 8.X.X | 9.X.X ] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**

**Comment by BGillham** [comment]
Sorry about the "Close"... My mistake...

**Comment by iJungleboy** [comment]
To me it sounds like some server file permission error. My guess is it removed all the data and then couldn't kill the folder, so it didn't delete the final app reference in the end. 

Please check if the folder is still there (in your Portals/xxx/2sxc) and if yes, delete the folder, then try to re-delete the app.

**Comment by BGillham** [comment]
Thank you for the response... I will try deleting the folders and see what happens...

**Comment by iJungleboy** [comment]
No problem. Note also that there may be issues where DNN thinks the folder still exists - so make sure to sync the DNN file system after deleting the folders manually.

**Comment by BGillham** [comment]
They folder did exist in the Adam Folder which I deleted and then I did resync the Site Assets Folder but the two orphaned Apps are still there... I did have a look at the DB but not knowing what the dependencies are, makes that a bit beyond me,,, Sorry to bother you nut I can give you a HOST login if you want to have a look?

- [ ]

**Comment by BGillham** [comment]
![Capture](https://user-images.githubusercontent.com/19285313/113321485-f0e2f700-9313-11eb-936c-be4609e4d9dc.JPG)
I have tried everything that you suggest and the problem prevails... If you cannot help further, I do understand... I will just have to look on the 'Net for Modules that are almost as good or similar in functionality... Thank you for trying and let me know if there is anything else I can do...

**Comment by BGillham** [comment]
I have gone into the settings and "Hidden" the offending Apps but that does not solve the problem... I guess I will have to reconsider the use of 2sxci in my Portals going forward... Pity...

**Comment by iJungleboy** [comment]
Just to verify I tried deleting an App on my system and it worked. I'll try to mail you directly...

**Comment by iJungleboy** [comment]
I found the reason :). 

Your IIS is configured for WebDav which prevents HTTP `DELETE` verbs. See https://github.com/2sic/2sxc/issues/2205
