### ISSUE TITLE
The folder did exist in the Adam Folder (none in the 2sxc folder)

### ISSUE THREAD

**Issue by BGillham** [2sic/2sxc#2386]
The folder did exist in the Adam Folder (none in the 2sxc folder)  which I deleted and then I did resync the Site Assets Folder but the two orphaned Apps are still there... I did have a look at the DB but not knowing what the dependencies are, makes that a bit beyond me,,, Sorry to bother you but I can give you a HOST login if you want to have a look?
[If I am in the wrong Forum then please direct me to the correct one]

- [ ]

_Originally posted by @BGillham in https://github.com/2sic/2sxc/issues/2385#issuecomment-811973529_

**Comment by iJungleboy** [comment]
After delete/sync you should be able to simply delete the app in apps management. to 99% that will do it.

**Comment by iJungleboy** [comment]
BTW: if you have anything to add, best add it to the original issue. Even if it's closed I'll get notified.
