### ISSUE TITLE
Bug: v11.20/21 has issues with Edit-View Configuration Dialog

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#2405]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI

**Current behavior**   

Bug - it only shows the GUID of the Content-Type when editing:

![bec12c66-2e24-4dbe-89bb-53e15f71779e](https://user-images.githubusercontent.com/5321186/115834482-92da9880-a415-11eb-800d-679d3074ed1f.jpg)

This is caused by performance optimizations in 11.20.

**Your environment**  

* **2sxc version(s):** 11.20/21

**Comment by PagnoDunadan** [comment]
Fixed
