### ISSUE TITLE
App.Data.Update Error in Task/Async Method using Shared CS File

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#2418]
**I'm submitting a ...**
[x] bug report

**...about**
[x] APIs like REST

**Current behavior**
We are writing an integration with ConstantContact API v3 which uses OAuth2 for authentication. We need to save a refresh-token to generate a new one for subsequent calls, so we need to store it in our system. We can call the PostAsync just fine and get a response, but when we go to update our data using App.Data.Update we get an "Object reference not set to an instance of an object." error. We are sure that the field names we are putting in are good, and that the Entity exists. Perhaps it has something to do with losing context somewhere in the call to the 2SXC API? This is the error detail:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=ToSic.Sxc.Dnn
  StackTrace:
   at ToSic.Sxc.Dnn.Run.DnnSite.get_DefaultLanguage()
   at ToSic.Sxc.Run.ImportExportEnvironmentBase.SaveOptions(Int32 zoneId)
   at ToSic.Eav.Apps.Parts.EntitiesManager.UpdateParts(IEntity orig, Dictionary`2 values, Nullable`1 draft)
   at ToSic.Eav.Apps.Parts.EntitiesManager.UpdateParts(Int32 id, Dictionary`2 values, Nullable`1 draft)
   at ToSic.Eav.Api.Api01.SimpleDataController.Update(Int32 entityId, Dictionary`2 values)
   at ToSic.Eav.Apps.AppData.Update(Int32 entityId, Dictionary`2 values, String userName)
   at ConstantContactOAuth.<GetAccessToken>d__2.MoveNext() in C:\...\ConstantContactOAuth.cs:line 51
```

**Expected behavior**
The call to App.Data.Update should update the entity with the specified EntityId and data.

**Instructions to Reproduce the Problem**
Having ConstantContact API access isn't required, as any async call returning data should suffice. Create a new content type to store the data, and then use the code below in a shared CS file to try to update it based on data returned from an external API:

```
public async Task<string> GetAccessToken()
{
    var accessToken = "";
    var refreshToken = "";

    try
    {
        var oAuth = AsList(App.Data["OAuth"]).FirstOrDefault();

        if (oAuth != null)
        {
            var request = "?refresh_token=" + oAuth.RefreshToken + "&grant_type=refresh_token";
            HttpContent httpContent = new StringContent("{}", Encoding.UTF8, "application/json");
            var response = await HttpClient.PostAsync(request, httpContent);

            if (response.IsSuccessStatusCode)
            {
                var responseString = await response.Content.ReadAsStringAsync();

                dynamic jsonResponse = JsonConvert.DeserializeObject(responseString);

                accessToken = jsonResponse.access_token.ToString();
                refreshToken = jsonResponse.refresh_token.ToString();

                var updateOAuth = new Dictionary<string, object>();
                updateOAuth.Add("AccessToken", accessToken);
                updateOAuth.Add("RefreshToken", refreshToken);
                
                // here is where the error occurs
                App.Data.Update(oAuth.EntityId, updateOAuth);

                var objEventLog = new EventLogController();
                objEventLog.AddLog("ConstantContactAPI", "Update access token successful", EventLogController.EventLogType.ADMIN_ALERT);
            }
            else
            {
                var objEventLog = new EventLogController();
                objEventLog.AddLog("ConstantContactAPI", "Bad response getting access token", EventLogController.EventLogType.ADMIN_ALERT);
            }
        }
        else
        {
            var objEventLog = new EventLogController();
            objEventLog.AddLog("ConstantContactAPI", "OAuth data missing", EventLogController.EventLogType.ADMIN_ALERT);
        }
    }
    catch (Exception exc)
    {
        Exceptions.LogException(exc);

        var objEventLog = new EventLogController();
        objEventLog.AddLog("ConstantContactAPI", "Error getting access token: " + App.Resources.SaveFailed, EventLogController.EventLogType.ADMIN_ALERT);
    }

    return accessToken;
}
```

**Why change the behavior?**
The call to App.Data.Update should update data if it exists.

**Your environment**  Windows/IIS

* **2sxc version(s):** 11.22.1
* **Browser:** Any
* **DNN:** 9.9.1
* **Language:** any

**Comment by tpperlman** [comment]
We decided to not use 2sxc for this integration.

**Comment by iJungleboy** [comment]
Just fyi: I believe the problem is the Dnn PortalSettings which are used to find the languages of the current portal - which is needed for saving data. Probably in the async it starts another thread and doesn't have the PortalSettings.Current. 

If you believe this is something that will be needed more, feel free to reopen, we would then investigate.

**Comment by tpperlman** [comment]
Thank you so much for the feedback. We figured it had something to do with context. We even tried creating a factory connection to the app, but even that didn't work.

**Comment by iJungleboy** [comment]
It's an old leftover of Dnn - using the static objects. I assume that way Async will probably never really work - unless someone has a good idea ;)

**Comment by tpperlman** [comment]
That's the funny thing, in other projects we are calling the same 2SXC method to update data and had no problem when it is through a WebAPI. It only seemed to happen with a shared CS file in an async void ButtonClick event.
