### ISSUE TITLE
Importing 4000 rows takes 27minutes

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2420]
**I'm submitting a ...** 
[x] not sure

**...about**
[x] Content Types or data management

**Current behavior** 

1. I created a content type with 4 entities (string and int only).
2. Created 2 demo items.
3. Exported.
4. Edited the data in excel, pasting 4000+ rows.
5. Imported back to 2sxc

The data took 27+ minutes to import.

**Expected behavior**  
Since a 500 item import takes like 30 seconds, I though a 4000 item import would take like 5-7 minutes top.

**Your environment**  

* **2sxc version(s):** 11.22.01
* **Browser:** [ Firefox ]
* **DNN:** [ 9.9.1 ] 
* **Language:** [ English ]
* 
This is a media center PC with a 4core ryzen 3200g.

**Comment by iJungleboy** [comment]
Thx, we'll investigate. Anything special in your setup - like multi-language or special settings during import?

**Comment by eXistenZe** [comment]
Nope. Single language.

**Comment by iJungleboy** [comment]
@eXistenZe fyi: we're going to review importing data again for v14, @tvatavuk is working on it.

**Comment by iJungleboy** [comment]
@eXistenZe just fyi, @tvatavuk found some ways to improve performance by factor 10-50. We'll release it in 14.02

Hope you love it ;)
