### ISSUE TITLE
Ability to Update an Entity's Fields without Creating History items

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2425]
**I'm submitting a ...**   
[x] feature request

**...about**
[x] Content Types or data management   ??
[x] other / unknown

**Current behavior**   
Currently when you update an entity a new History item is created. This happens via the UI or through the API.

So if have a Content Type named NewsTicks with the field NewsEntityId and Counter only and you do this:

```
    int currNewsEntityId = 1957; // in a real scenario you'd have this handy
    // note that NewsTicks already has this record, it was created when the News item was added
    int count = (int)AsList(App.Data["NewsTicks"]).Where(a => a.EntityId == currNewsEntityId).First().Counter;
    var fields = new Dictionary<string, object>();
    fields.Add("Counter", ++count);
    App.Data.Update(entityId: currNewsEntityId, values: fields);
```

and then allow something like this to happen every time the News article gets a page view, a History item is created. So this simple article view tracker ends up wasting space and doing unnecessary work.
![image](https://user-images.githubusercontent.com/653301/119587338-1af4ea80-bd94-11eb-9141-eddad1289dc3.png)

**Desired Behavior**
By adding a parameter to the .Update() method, this unnecessary/unwanted History item creation could be avoided. Something like `System.Bool  historySkip` with a default of `false`. So then we could do this:

```
    App.Data.Update(entityId: currNewsEntityId, values: fields, historySkip: true);
```

and only the one field would get updated.

**Why change the behavior?**  
If its not obvious the experiment was instigated by [this StackOverflood question](https://stackoverflow.com/questions/67469687/how-can-we-sort-news-by-top-news-in-2sxc) and the fact that I have been asked for Top News items by two different clients recently.
 
Also, once this option exists, it could later be added to the UI so that 2sxc based system managing larger amounts of data could have a Content-Type setting where History is not updated for record changes.

**Environment and versions don't really apply here,** but this feature request was tested on 2sxc 11.22.01.

* **2sxc version(s):** 11.22.01
* **Browser:** all
* **DNN:** all
* **Language:** any/all

**Comment by iJungleboy** [comment]
Enabling this as an API introduces the risk that we accidentally don't version stuff which should be versioned. So I'm not sure if this is the place to do this. 

An alternative might be to say a specific content-type is never versioned. That would probably play better with some future features we have anticipated. What would you think about that?

**Comment by jeremy-farrance** [comment]
Named params and defaults avoids that problem, though I assume you mean that a lot of people currently have code that didn't use named params. And you could always do a new/different method named, `Data.App.UpdateNoHistory()`. 
 
But, yes, a content-type setting would work. Though honestly, I'd prefer it was implemented BOTH at the content-type AND field level. There are a lot more use cases for this no history concept that go beyond performance and chewing up storage.
 
Also, note that I didn't even (yet) bring up the point about having to do two calls to do a simple increment. It sure would be nice if I didn't have to do the first `(int)AsList( ...)` to get the current value and instead had a way to simple trigger the number field to increment. :)
 
So thank you for the great response and I hope this blends in well with your planned future features in some way that makes it easy - as well as useful. Cheers!!
 
PS, while we are here. Is there a 2sxc, App, or Content-Type (level) setting so limit the number of History/Versioning items and also trigger some occasional cleanup?

**Comment by iJungleboy** [comment]
@jeremy-farrance As of now there is no clean-up system and it's also not a priority for us. We'd love to do it, but there are so many things we could do that we prioritize by whoever contributes / pays ;).

**Comment by jeremy-farrance** [comment]
Is there an easy way to access the Versioning history items of an Entity? Would there be a way to programmatically get a list of them and then possibly delete them?
 
```
var entityHistory = AsList(entity.HistoryItems);
```

**Comment by iJungleboy** [comment]
As of now no. It's all in a SQL table - so it would be easy to flush there, but there is no API for this.

**Comment by iJungleboy** [comment]
I've added this to the list of features needing sponsoring. Since I don't assume it will happen soon, I'll close this for now.

**Comment by jeremy-farrance** [comment]
If anyone ever comes back to this, two related items

1. If you edit an Entity and hit Save without making any changes, a new History item is created. This seems very unnecessary and should be detected (!dirty) so a new item is not created.
2. Each field of a Content-Type needs an option to NOT trigger the creation of a History item on Save. In other words, as an extended case of 1 (above), if the only fields with changes are all true for not creating a History item on save, then the changed fields ARE saved but no history item is created.

**Comment by iJungleboy** [comment]
@jeremy-farrance 
## 1 not save when not dirty
The not-dirty-not-save sounds interesting, but it's really hard to do. 

The UI can't do it, because it could be changed in the meantime, and when I save, it should be the latest state.

The backend would have a really hard time doing this, because internally it will get the update request, merge it with existing data (because the request could for e.g. only contain one language, and need to preserve the other languages).

Then it would need to do a delta and refuse to save.

This can of course be done, but there is always the risk that we miss something, and therefor don't save, even though there was some minor change - for example because a language-inherit rule was modified or a empty-string vs null comparison.

So hard to do, not a priority - probably won't happen any time soon. 

## 2 Setting to prevent history

Doing this sounds scary to me, as the history is usually a last-resort kind of thing to go back to. And disabling history sounds like something that will bite you in the end. Why would you need this?

Would it also be an option to disable history on the entire content-type? or do you have a frequent changing field, and you're afraid the DB will fill up?
