### ISSUE TITLE
The new 2sxc controls "glow" animation makes the controls hard to see and it clashes with site branding

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2426]
**I'm submitting a ...** 
[x] revert new design choice

**...about** 
[x] edit experience / UI

**Current behavior**   
The new glow animation style on the EditTagToolbar controls really clash with site styles and make the icons less usable.

![Screen Shot 2021-05-26 at 9 12 10 PM](https://user-images.githubusercontent.com/8751936/119765014-3da40380-be67-11eb-98d2-619e19a2d6e1.png)

**Expected behavior**
I think the previous white icon style was pretty good.

**Instructions to Reproduce the Problem**
Hover over an element to see the EditTagToolbar controls.

**Why change the behavior?** 
Usability and branding

**Your environment** 
Shared hosting

* **2sxc version(s):** 12.1.0
* **Browser:** [all ]
* **DNN:** [all] 
* **Language:** [any/all ]

**Anything you would like to add**

I often customize the Edit.TagToolbar and configure the colours to match the brand to make it look good, but to also differentiate controls for my content editors. For example, I might make a listing of cards use a green colour, but then the buttons inside the cards (sub-entities) would use the branding blue.

When I customize it, it looks like this:

![Screen Shot 2021-05-26 at 9 17 50 PM](https://user-images.githubusercontent.com/8751936/119765413-17329800-be68-11eb-8a04-8d8c388908a8.png)

Aside from not looking very good, it poses a bit of a usability problem. I know that I can add this to my skin to fix it but I would rather keep things simple.

```
.sc-menu a div {
animation: none !important;
}
```

**Comment by iJungleboy** [comment]
I understand. Would it be enough to disable the glow when a custom color is applied?

**Comment by ajplopez** [comment]
Absolutely. I think removing the glow for customized colours is a fair trade off.

**Comment by iJungleboy** [comment]
The glow was removed in v14, so it's done ;)
