### ISSUE TITLE
Error in page picker

### ISSUE THREAD

**Issue by trouble2** [2sic/2sxc#2431]
**I'm submitting a ...**   
[x] bug report

**...about**   
[x] edit experience / UI

**Current behavior**   
When using the page picker on a multilanguage site it gives us an error, and sometimes the pages do not appear:
ERROR TypeError: n.connectBridge is not a function
    at t.iframeLoaded (dnn-bridge.component.ts:43)
    at dnn-bridge.component.html:7
    at Go (core.js:15166)
    at i (core.js:15201)
    at HTMLIFrameElement.<anonymous> (platform-browser.js:582)
    at e.value (zone.js:407)
    at Object.onInvokeTask (core.js:27418)
    at e.value (zone.js:406)
    at t.value (zone.js:179)
    at t.value [as invoke] (zone.js:488)

**Expected behavior**   
No errors :-)

**Instructions to Reproduce the Problem**
Just tried to add a link to some content item

**Why change the behavior?**  
Well, we don't want bugs don't we?

**Your environment**  
* **2sxc version(s):** 11.22.1  
* **DNN:** [9.9.1 ] 
* **Language:** [English | Japanes (no joke) ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Hi @trouble2 thanks for reporting this. 

We completely replaced the page-picker in 2sxc 12. Previously it tried to iframe a built-in DNN functionality and the JS errors you show are somehow related to that. In 2sxc 12 we created our own page picker, so these issues should be gone. 

I don't know how multi-language will behave there, but we'll have to find out. At least this issue mentioned here is fixed.
