### ISSUE TITLE
v12.01 Installs Old Versions of Gallery App etc.

### ISSUE THREAD

**Issue by BGillham** [2sic/2sxc#2432]
**I'm submitting a ...
[x] bug report => search github for a similar issue before submitting 
[x] feature request
[x] support request => use stackoverflow and tag with 2sxc https://stackoverflow.com/questions/tagged/2sxc

**...about**   
[x] admin experience UI
[x] Content Types or data management
[x] DNN parts

**Current behavior**   
Adding v12.01 to a Portal for the first time installs the Gallery App v5 which does not workout-of-the-box
[This is the same for allupdated Apps]

**Expected behavior**   
Install Gallery App v6

**Instructions to Reproduce the Problem**

**Why change the behavior?**  
As above
**Your environment**  

* **2sxc version(s):** 12.0.1  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** 9.9.1 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**
Perhaps a fresh install should check for updated versions and current installations should have an option to "update" current installations including Module and Apps?

**Comment by BGillham** [comment]
I remedied the issue by first trying to install Gallery App v6 which did not work and then by deleting the v6 App and installing the v6 App.

**Comment by iJungleboy** [comment]
As of now this is still kind of on purpose. The new Apps are functionally the same as the previous ones, just using the new Hybrid approach which will let you run them on Oqtane - or in future you could export them and import them on Oqtane. 

As we're still finalizing some of the Hybrid APIs we want to wait a bit before making it the default install on Dnn.

**Comment by iJungleboy** [comment]
As reported in #2473 the gallery isn't quite ready yet. we'll auto-deploy it as soon as it's perfect. for now I'll close this issue.
