### ISSUE TITLE
Ensure 2sxc works without Portal-Setting "Use Custom Module Portal CSS Class"

### ISSUE THREAD

**Issue by efficiondave** [2sic/2sxc#244]
We are having strange issues with one of our sites and we've tried the install of 7.0.2 on both the live server and the beta server. We are getting an error on install (at the bottom of this post). Also, when we then add the module, we don't get the App selector option. We've uninstalled and reinstalled multiple times and have tried the default app setup as well as just installing the BlueImp Gallery app. Any idea what might be causing this?

Here's the error we're getting:
 Error: is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Access to the path '2sic_2SexyContent.dnn' is denied. ---> System.UnauthorizedAccessException: Access to the path '2sic_2SexyContent.dnn' is denied. at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound) at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost) at DotNetNuke.Modules.Admin.Extensions.Install.DeleteInstallFile() --- End of inner exception stack trace ---

**Comment by efficiondave** [comment]
We are also seeing this when we try to install apps: Access to the path 'App-Icon.png' is denied. (you might find more informations about the error in the DNN event log). I've double-checked permissions and everything seems correct.

**Comment by efficiondave** [comment]
I was able to solve the Install problems by giving IIS_IUSRS modify permissions. I uninstall, cleaned up all files and reinstalled with no errors. Then installed BlueImp Gallery but I'm still not seeing the app selector so there's no easy way for me to select the app. I also don't get the selector when I add the Content module. If I choose Change Template / Layout from the action menu, I get the following JS error in the console:
Uncaught TypeError: Cannot read property 'manage' of null$2sxc.getManageController @ 2sxc.api.manage.js?cdv=38:5window.$2sxc @ 2sxc.api.js?cdv=38:115changeLayoutOrContent @ 2sxc.DnnActionMenuMapper.js?cdv=38:6(anonymous function) @ VM1321:1

**Comment by iJungleboy** [comment]
@efficiondave Thanks for solving the first problem yourself :)

The second one also sounds like a permissions-configuration problem. The manage-property only exists in edit mode when additional javascripts are loaded. Please use fiddler to check what requests are denied by the server - and then check the folder permissions on those.

**Comment by efficiondave** [comment]
Thanks for the response. I took a look at the Network tab in the FireFox Dev Tools (which to my mind is the same as fiddler) and everything came back with 200 except for one that was a 302.

**Comment by efficiondave** [comment]
No, that file is not in the list of files being requested by the page. 2sxc.api.manage.js does get a 200.

**Comment by iJungleboy** [comment]
On another system which had the same issue, it turned out a host-setting was disabled - this usually is a default setting - so maybe you also disabled it? or does the new install not set this?

![image](https://cloud.githubusercontent.com/assets/5321186/7699416/14bdff40-fe18-11e4-89e8-00defa5e5be4.png)

Please try this and report back.

**Comment by iJungleboy** [comment]
Note that we'll try to change the new version to not need this. But please tell us if you had changed this or if this was a default in your installation.

**Comment by iJungleboy** [comment]
And if it fixed your issue - please upgrade the rating on codeplex to 5 stars - helps build trust with new users - thx!

**Comment by efficiondave** [comment]
That box was indeed unchecked and checking it did resolve the issue. Thanks!

David O'Leary
www.EfficionConsulting.com
314.329.3828
