### ISSUE TITLE
Ghost Error Reported via Toast - Possibly in Formulas?

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2448]
I'm submitting a [x] bug report about [x] edit experience / UI [x] admin experience UI [x] other / unknown

**Current behavior**   
Just changing settings in the View causes a "toast" popup about an error, though nothing shows up in the console. Best explained in this short video demo of it happening...

[Video Demo of Error](https://accuraty-my.sharepoint.com/:v:/p/jfarrance/ES3vCp1647dBvExjRGen-nkBqSkcgiyR29ZJE-slNmvChA?e=ZnKpdb)

**Expected behavior** 
Either don't display the error or provide more info details so that the source of the issue can be determined?

**Instructions to Reproduce the Problem**
See video linked above.

**Your environment**

* **2sxc version(s):** 12.02, just released less than an hour ago.
* **Browser: all/any
* **DNN: 9.01.01/any?
* **Language: any/all

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Thanks, I'll check!

**Comment by iJungleboy** [comment]
BTW: it won't break your data - there just seems to be some bug in the show/hide fields code.

**Comment by iJungleboy** [comment]
Ok, we figured it out. Was a side-effect of the date related work which accidentally threw undefined-checks. Already fixed, will be in 12.02.01 to be released ASAP.

**Comment by jeremy-farrance** [comment]
I am impressed. I felt really bad reporting an issue with almost no clues or error details. Thanks!
