### ISSUE TITLE
Issue: 413 error when importing an app

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2451]
**I'm submitting a ...** 
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] importing a custom app

**Current behavior**   
I made an app and exported it and it's 31MB. It's a really simple list and details app with text and images. When I try to import the app into a new site I get a popup error that says :

"Had an error talking to the server (status 413).

if you are an advanced user you can learn more about what went wrong - discover how on 2sxc.org/help?tag=debug"

I increased the file upload limit on my site via the web.config but I still get the error.

![Screen Shot 2021-06-11 at 1 25 10 PM](https://user-images.githubusercontent.com/8751936/121745492-37de2d00-cab9-11eb-8a33-bd06ef8120f7.png)

**Expected behavior**   
I expect the app to import smoothly.

**Instructions to Reproduce the Problem**
Make an app and export it and make sure that is over 30MB. Try to import it into a new site.

**Why change the behavior?**
Bug?

**Your environment** 
Pretty standard hosting.

* **2sxc version(s):** 12.02.01  
* **Browser:** [all ]
* **DNN:** [all | 9.3.2] 
* **Language:** [English ]

**Anything you would like to add**
Not sure if this is a bug or if it's just my setup. Feel free to close if it's not a bug.

**Comment by iJungleboy** [comment]
As a work around you could...

1. Put all the ADAM files in the target manually
2. Remove the adam files from the zip
3. re-import the much smaller zip

**Comment by ajplopez** [comment]
I had a PEBKAC error. I was uploading my web.config change to the wrong site. So it wasn't a problem at all with 2sxc, just that my site couldn't handle the file size. Sorry! Closing this out.
