### ISSUE TITLE
Bug: Instance-list icon throws pop-up error for subentities

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2455]
**I'm submitting a ...** 
[x] bug report 

**...about**   
[x] edit experience / UI

**Current behavior**   
I have an app that has listing and details view. On the details view, there is content. Most of it is content in the main content type, but I have a bunch of content that comes from an Entity Picker (subentities) of other content types.

I have customized the Edit Tag Toolbar for these subentities to allow direct editing of each subentity. Typically I used "edit,new,remove,instance-list,moveup,movedown". Everything works as expected except when I click the "instance-list" icon it popups open the Manage content-item lists modal but then it shows a pop-up error that says 400 error.

![Screen Shot 2021-06-13 at 4 49 47 PM](https://user-images.githubusercontent.com/8751936/121825529-d8724f80-cc67-11eb-885b-87ffc0336838.png)

**Expected behavior**   
To be able to edit the list of the sub-entitites so I can drag and drop.

**Instructions to Reproduce the Problem**
Customize the edit tag toolbar on some sub-entities to include instance-list.

![Screen Shot 2021-06-13 at 4 54 09 PM](https://user-images.githubusercontent.com/8751936/121825571-0a83b180-cc68-11eb-9fa4-76edf4612d31.png)

Then click on the instance-list and you'll probably see a pop-up error that says 400.

You can click the error away to reorder the items but then it refreshes the page. The change does get applied, however.

**Why change the behavior?**  
Bug

**Your environment**  
Nothing special on dedicated hosting. Affects shared hosting as well.

* **2sxc version(s):** 12.2.1
* **Browser:** [all ]
* **DNN:** [9.3.2] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**

I've noticed this on a few sites of varying 2sxc versions.

**Comment by iJungleboy** [comment]
This sounds like a bug, we'll look into it.

**Comment by iJungleboy** [comment]
Is this still an issue? I have a feeling that it may have fixed itself a few months ago with some API clean-up. 
Please verify.

**Comment by ajplopez** [comment]
This seems to work on 14.7.5
