### ISSUE TITLE
Add new element blue icon button for 'App' module not appearing for Registered Users with DNN Role to edit

### ISSUE THREAD

**Issue by denisjoconnor** [2sic/2sxc#2460]
**I'm submitting a ...** 
[x] bug report => similar to https://github.com/2sic/2sxc/issues/1575
[x] not sure

**...about**   
[x] edit experience / UI

**Current behavior** 
I have a user with a DNN role assigned and is a Registered User but is not an 'Administrator'. They have permissions to edit specific pages on a site. When they drop the 'App' module onto a page they have rights to edit there is no blue add new element icon button showing but when they drop the 'Content' module it is visible. If an 'Administrator' (DNN Role) drops the 'App' module it is visible and the Registered User is allowed to edit the content of this module but can not add new content items to it or any other additional edit features.

We have tried several permissions including giving app level permissions, data and view level permissions, using the exact template and security rules outlined in the public forms template (https://2sxc.org/en/blog/post/recipe-create-public-forms-with-2sxc) and enabling permissions by Group/Role and Permission for SecutityAccessLevel.view but can't get it to work.

**Expected behavior** 
After adding an app/content module, the Registered User with a non-admin DNN Role gets an option to select the app or content type and add additional content items to an existing module if they have been given rights to edit this page/module in DNN.

**Instructions to Reproduce the Problem**
Issue appears to be similar as reported here except for Registered Users with DNN Role to edit -  https://github.com/2sic/2sxc/issues/1575
Live site on v11.22 LTS but have also reproduced issue locally on v12.0

**Why change the behavior?**
Our customer/user has reported this only started to occur after recent upgrade to latest stable 11.22 LTS so maybe related to upgrade? Can't recall for sure if it was happening prior to upgrade. Attached are screenshots of the current setup.
![Enable App Features 1](https://user-images.githubusercontent.com/16110075/122038074-26549800-cdcd-11eb-858e-0c212451021b.png)
![Enable App Features 2](https://user-images.githubusercontent.com/16110075/122038078-26ed2e80-cdcd-11eb-81d8-98ba7c949ece.png)
![securityGroupFull](https://user-images.githubusercontent.com/16110075/122038079-26ed2e80-cdcd-11eb-89be-db6d2a788ac6.png)
![appNoIcon](https://user-images.githubusercontent.com/16110075/122038083-2785c500-cdcd-11eb-878e-13a0e5f5cfb7.png)
![editEnable](https://user-images.githubusercontent.com/16110075/122038086-281e5b80-cdcd-11eb-9eca-a05cdd27d0fd.png)

* **2sxc version(s):** 
2sxc 11.22 LTS
* **Browser:** 
Chrome | Firefox | Edge (all latest)
* **DNN:** 
DNN 9.9.1
* **Language:** 
English

**Comment by iJungleboy** [comment]
Hi @denisjoconnor 

I'm sorry that I won't be able to do a lot ATM - I'm on my way to Tanzania and will be mostly offline for ca. 7 weeks. https://2sxc.org/en/blog/post/volunteering-in-tanzania-till-mid-of-august

Just fyi: `@Edit.Enable` doesn't change edit permissions, it just adds resources / js etc. to the page so these things can work. but it doesn't change permissions.

For anything else I'm afraid you'll have to wait till end of August or ask someone else to help or fix this.

**Comment by denisjoconnor** [comment]
Hi @iJungleboy 

Thanks, no problem, when you are back can you confirm if this behavior (After adding an 'App' module, the Registered User with a non-admin DNN Role gets an option to select the app view/content item if they have been given rights to edit this page and module in DNN) is how the 'App' module should work by default as ATM we don't know if its an issue with our site, our version or a bug.

PS. Ref @Edit.Enable, we know this only adds js etc (read and followed documentation and blog posts) but wanted only to highlight we have no missing references or turned off features to eliminate these as potential causes.

Thanks

**Comment by iJungleboy** [comment]
@denisjoconnor I'm not sure if this is still open, so I'll close it for now. If it's still an issue (also with latest 2sxc) pls post and I'll reopen.

**Comment by david-poindexter** [comment]
@iJungleboy we are experiencing this exact issue on a new site.

Here is our scenario:

* DNN 9.10.2
* 2sxc 12.8.1
* Have a role called "Content Managers" and they have "Edit" rights on pages.
* Have applied "Can Deploy" to "Content Managers" for "App" extension.

A user belonging to "Content Managers" is able to add an "App" module to a page.  However, they do not have the ability to "Choose App" in 2sxc.

In 2sxc, I have tried enabling the Feature for `Permission by Group / Role`.  Then for the relevant app, I updated App Permissions to add a Security Rule for the appropriate RoleId (the one that matches the "Content Managers" role) and gave it `Edit (Create, Read, Update, Delete)` rights.  It still didn't work, so I even tried giving it `Full Control (usually host only)`.  That didn't work either.

Any other ideas?  What the heck am I missing?

I found this SO post helpful, but unfortunately, it just doesn't work for me.  ☹️  https://stackoverflow.com/questions/58293074/best-way-to-implement-basic-content-manager-permissions 

If you need this to be a new issue, just let me know and I'll be happy to submit as such.

**Comment by david-poindexter** [comment]
I went ahead and just opened a new issue since this one was closed, and to provide more details.  #2655
