### ISSUE TITLE
Entity Type Filter not working with App Datasource

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2472]
I'm submitting a [x] bug report about [x] Content Types or data management and [x] Visual Query.

**Current behavior**   
In my App, I created a new Query with the App Data Source configured for Zone 2, App 2 to get data from the Content App, When I hook that up to the Content-Type Filter, it doesn't work. There are no content types in the dropdown for the filter settings. Even if you type an appropriate value in to the field, it doesn't work, and doesn't seem to save it.

**Expected behavior**   
I should be able to Filter on Content-Types like Location or Person.

**Instructions to Reproduce the Problem**
Make the query as described above or see screenshot below.

**Why change the behavior?**  
Unless I misunderstand something, this seems like it should work.

**Screenshot**
![image](https://user-images.githubusercontent.com/653301/124048679-8017ad80-d9dc-11eb-969d-4e82b4a8ebb3.png)

**Your environment** 

**2sxc version(s):** 11.22.1 LTS
**Browser:** [all/all]
**DNN:** [9.09.01] 
**Language:** [any/all]

**Anything you would like to add**
As a workaround, I was able to use a Value Filter with EntityType == "Location" - though this worked, it also brings in 5+ other entities (Group/Content) stuff I think that I then have to do additional filters to remove by EntityId.

**Comment by iJungleboy** [comment]
We'll check.

BTW: A simpler way is to rename the `Default` stream on the App-source to `Location` - that only contains the items of the type `Location` 😉

**Comment by jeremy-farrance** [comment]
That works great, thanks!! I never picked up on that before, so I suggested an improvement to the docs just now. :)

**Comment by iJungleboy** [comment]
Now that I re-read it, I think you made a small mistake using the dropdown. 

We've encountered this a few times - the UX isn't perfect. Initially it's a search, unless you switch to text-mode, in which case you can type text to keep. This confuses people, but it's a separate issue. 

So I'll assume for now that it's resolved, and we'll try to fix the UX separately.
