### ISSUE TITLE
Gallery (Type: Many) Broke All Galleries on Site

### ISSUE THREAD

**Issue by BGillham** [2sic/2sxc#2473]
**I'm submitting a ...** 
[x] bug report =>
[x] support request => use stackoverflow and tag with 2sxc https://stackoverflow.com/questions/tagged/2sxc
[x] not sure

**...about**   
[x] Content Types or data management
[x] DNN parts
[x] other / unknown

**Current behavior**   
![errGallerry](https://user-images.githubusercontent.com/19285313/124735273-2fd9a780-df16-11eb-9743-7179eb6d2576.JPG)
I have tried to add a Gallery  of "Many" (I have v5) and did not add a Thumbnail or an Image to start and just saved it after entering the Title and a few words describing the Gallery. It saved and promptly broke the entire set of Galleries. Is there any way to resolve this issue? So far I have tried DELETING v5 and then adding v6 but to no avail... HELP PLEASE!

Error: System.Exception: Data is missing - usually when a site is copied but the content / apps have not been imported yet - check 2sxc.org/help?tag=export-import

**Expected behavior**   

**Instructions to Reproduce the Problem**

**Why change the behavior?**  

**Your environment**  

* **2sxc version(s):** 12.2.1  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** 9.9.1 
* **Language:** [any/all | English | German | other ]

**Comment by BGillham** [comment]
FYI: I have added a new page and have found that if you add a NEW 'Many' Gallery and do not add any Images, it just CRASHES.

Error: System.InvalidOperationException: Sequence contains no elements at System.Linq.Enumerable.First[TSource](IEnumerable`1 source) at ASP._Page_Portals_8_2sxc_Gallery_Fancybox3__Album_List_cshtml.Execute() in E:\DotnetNuke\httpdocs\Portals\8\2sxc\Gallery-Fancybox3\_Album List.cshtml:line 9 at System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) at ToSic.Sxc.Engines.RazorEngine.Render(TextWriter writer) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Razor\Engines\Razor\RazorEngine.cs:line 71 at ToSic.Sxc.Engines.RazorEngine.RenderTemplate() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Razor\Engines\Razor\RazorEngine.cs:line 81 at ToSic.Sxc.Engines.EngineBase.Render() in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Engines\EngineBase.cs:line 151 at ToSic.Sxc.Blocks.BlockBuilder.Render() in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Blocks\BlockBuilder_Render.cs:line 57

**Comment by iJungleboy** [comment]
Yes, it's a bug in the gallery 6 - the list-of-albums tries to get the gallery-main image, otherwise it uses `First()` on all the images in the gallery. We'll fix when I'm back from Tanzania. 

Workaround: 
1. You can either just add a primary image
2. add some images to the gallery so `First()` doesn't fail

**Comment by BGillham** [comment]
Do you gave any idea on how to fix my broken Galleries or do I have to delete them and start again? Would appreciate any help on this one...

**Comment by iJungleboy** [comment]
no, just go into the app admin and edit the album-data there - and add a cover image to the album

**Comment by BGillham** [comment]
> no, just go into the app admin and edit the album-data there - and add a cover image to the album
For the life of me, I cannot see how to do that... Do you have instructions for Stupid?
Sorry but I see the Image Gallery Admin but cannot work out how to add an Image to fix the broken Gallery.
![Capture](https://user-images.githubusercontent.com/19285313/125497975-ced04d71-0408-49a0-a159-f5ae3ec71fd9.JPG)

**Comment by BGillham** [comment]
Can SOMEBODY please assist... Obviously, I am not seeing what iJungleBoy is suggesting... I really need to fix this issue as I have nearly 100 Galleries... Thank you in advance...

**Comment by iJungleboy** [comment]
Just back from Tanzania... is this still an issue?

**Comment by BGillham** [comment]
I have installed v12.2.1 and have not tested it - I recovered my Portals from Backup from before the error occurred and have not attempted to repeat the error.

**Comment by iJungleboy** [comment]
ok. then best wait for another few days till we release an updated gallery app. I'll keep this issue open.

**Comment by BGillham** [comment]
Thank you - Appreciate your support... It is a great product.

**Comment by iJungleboy** [comment]
Just fyi: Fancybox released V4 without jQuery. We'll probably need a few days and then release it with that latest fancybox.
