### ISSUE TITLE
DNN SQL DataSource fails with ORDER BY command

### ISSUE THREAD

**Issue by PagnoDunadan** [2sic/2sxc#2475]
**I'm submitting a ...**
[x] bug report

**...about**
[x] admin experience UI
[x] Content Types or data management
[x] DNN parts

**Current behavior**

Generated SQL fails with ORDER BY command. Works fine with WHERE.

![2021-07-14 10_43_24-Content Management](https://user-images.githubusercontent.com/7113033/125592240-07b98d1a-96a9-4058-afe4-ae20b48a49f8.png)

![QueryError](https://user-images.githubusercontent.com/7113033/125592162-af0da6fa-eafb-418c-ab56-2e6810405a04.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/7113033/125592851-da389cf2-8b4d-4f13-be10-645e0cb292f7.png)

**Instructions to Reproduce the Problem**

Install Tests App and add VisualQueryTestTable to DNN database with provided script. Check DNN SQL DataSource in QueryTest query in Admin UI.

[2sxcApp_Tests_0.0.11.zip](https://github.com/2sic/2sxc/files/6814784/2sxcApp_Tests_0.0.11.zip)
[VisualQueryTestTable.zip](https://github.com/2sic/2sxc/files/6814788/VisualQueryTestTable.zip)

**Your environment**

* **2sxc version(s):** DEV
* **Browser:** all
* **DNN:** 7.4.2 
* **Language:** any

**Anything you would like to add**

**Comment by iJungleboy** [comment]
I did some research on this - it seems that it's a limitation in SQL 

It's discussed here: https://stackoverflow.com/questions/13844678/order-by-using-a-parameter-for-the-column-name
...and there doesn't seem to be a way to fix this. 

I suggest you simply leave the query as is without order-by, and do the ordering in another step using the ValueSort datasource https://docs.2sxc.org/api/dot-net/ToSic.Eav.DataSources.ValueSort.html
