### ISSUE TITLE
Importing Query sometimes fails to import DNN SQL DataSource

### ISSUE THREAD

**Issue by PagnoDunadan** [2sic/2sxc#2476]
**I'm submitting a ...**
[x] bug report

**...about**
[x] admin experience UI
[x] Content Types or data management

**Current behavior**   

Importing Query with DNN SQL DataSource fails to import query:

![image](https://user-images.githubusercontent.com/7113033/125595177-19dca48b-0060-4e6d-b2b9-20c2fcf50702.png)

![image](https://user-images.githubusercontent.com/7113033/125594567-2f7206bc-2838-49eb-b212-588aa65ed7b5.png)

**Expected behavior**

Import to match source:

![image](https://user-images.githubusercontent.com/7113033/125595729-6af8f26b-7ff0-4f4f-8240-4a4ae549ade2.png)

**Instructions to Reproduce the Problem**

Here is an example of a query that fails to import properly: [Query.DMX-Fetch.json.zip](https://github.com/2sic/2sxc/files/6814862/Query.DMX-Fetch.json.zip)

**Your environment**

* **2sxc version(s):** DEV
* **Browser:** all
* **DNN:** 7.4.2
* **Language:** any

**Anything you would like to add**

**Comment by iJungleboy** [comment]
@tvatavuk could you check, verify, probably fix?

**Comment by tvatavuk** [comment]
2sxc Query Import behavior is as expected. Query import checks if the import entity has languages that are not in the destination zone, and throw exception `Error: entity has languages which are not in zone - entity has 1 zone has 0 used-list: 'hr-hr'`.

The sample query has metadata attributes localized in the language ("hr-hr") that do not exist in the destination zone/portal.

**Comment by iJungleboy** [comment]
@tvatavuk I've noticed similar behavior before

I think we'll need to improve entity-import to better signal issues with languages not matching some day.

**Comment by tvatavuk** [comment]
Updated import error message in error message box (admin user expected).

![image](https://user-images.githubusercontent.com/2724850/130450700-fe7b6fac-ef1d-4326-9fec-132cfbe25335.png)

**Comment by iJungleboy** [comment]
ok. not the final solution, but at least this will make it clearer.
