### ISSUE TITLE
Content Block Loop when creating Content-Block inside a default-content

### ISSUE THREAD

**Issue by miguelvaz78** [2sic/2sxc#2486]
**I'm submitting a ...**  
[x] bug report 
[x] feature request

**...about**   
[x] Razor templating

**Current behavior**  
If we add a Content-block inside itself, the server gets stuck in a loop when rendering the blocks until it is shut down.
Is there any way to prevent Content Block looping? 
I Found about this because in one of the apps that I created I added the ability to add child content blocks inside the content.
My razor template for this is as follows.

```
<div class="sc-content-block-list" @Edit.ContextAttributes(Content, field:"AdditionalContent")>
                    @foreach(var cb in @Content.AdditionalContent) {
                        @Render.One(cb);
                    }
                </div>
```

This is working great until I added (by mistake) a new content block to the default (lorem ipsum) content item. This lead to that new content showing the default content and created a infinite loop because each default content added itself as child.

**Expected behavior**  
I would be perfect if the system could manage this and ensure that when rendering child content blocks, there was some kind of limit to the recursion depth.
Or some context variable having the recursion depth of the rendering engine so we could throw an if statement there to avoid looping.

**Instructions to Reproduce the Problem**
1. Create a content type with a content block field (named AdditionalContent);
2. Create a dummy item using this content type.
3. Create a view to show a single item;
4. For the newly created view, set the default item as the one created in step 2;
5. Edit the razor file so it renders the child content blocks as in the above code block;
6. Go to a page and add a new module for a 2sxc APP;
7. Select the app and view that we created above;
8. You should see the default item and a placeholder to add content-blocks;
9. In the Content-Blocks placeholder add a new app and again select this app and view;
10. By doing this, a loop is created because the default content will be adding itself as a child content-block.

**Why change the behavior?** 
Because it is something that is easily reproduced by a content editor and it breaks the app pool forcing it to stall and then restart.

* **2sxc version(s):** 12.X.X
* **Browser:** all
* **DNN:** 9.X.X 
* **Language:** any/all

**Comment by miguelvaz78** [comment]
Just a quick update.

I was able to minimize the number of times this occurs by hiding the ContentBlocks when item is the demo item. 
This was done by wrapping the code in a "@if(!Content.IsDemoItem){" like so:

```
@if(!Content.IsDemoItem){
<div class="sc-content-block-list" @Edit.ContextAttributes(Content, field:"AdditionalContent")>
                    @foreach(var cb in @Content.AdditionalContent) {
                        @Render.One(cb);
                    }
                </div>
}
```

This does not fix the recursive issue, but it minimizes the probability of an accident happening when editors add contentblocks before selecting or creating a content item.

**Comment by iJungleboy** [comment]
Cleaning up old tasks.
This is too low on our priorities to get handled any time soon, so we'll close this.
