### ISSUE TITLE
Bug: Template editor snippets sub-entity codes not expanding

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2487]
**I'm submitting a ...**   
[x] bug report 

**...about**  
[x] admin experience UI
[x] Razor templating

**Current behavior**  
When editing a template, on the left hand side, in the code snippets sidebar, the 3 dots to expand code examples for sub-entities is not expanding when the user clicks on it like they used to. Currently the dots flip around but nothing is expanded.

https://www.loom.com/share/deb3a7c2fd2b4b4ea7f9d90e0fcc7caf

**Expected behavior** 

It should expand the code snippets below.

**Instructions to Reproduce the Problem**

Open the template editor on an app that has sub entities and try to expand the snippets.

https://www.loom.com/share/deb3a7c2fd2b4b4ea7f9d90e0fcc7caf

**Why change the behavior?**

It's a bug.

**Your environment**

Nothing special.

* **2sxc version(s):** 12.2.1
* **Browser:** [all ]
* **DNN:** [9.8.1 and maybe all? ] 
* **Language:** [any/all  ]

**Anything you would like to add**

I've noticed this in some previous versions of 2sxc as well so it feels like a relatively new problem but not limited to 12.2.1

**Comment by PagnoDunadan** [comment]
This is fixed in dev.

![image](https://user-images.githubusercontent.com/7113033/129686872-1f5b2629-6333-4fcb-b03d-c87783c37f0b.png)
