### ISSUE TITLE
Add Comments/Notes Ability in VisualQuery Designer

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2490]
I'm submitting a [x] feature request about [x] admin experience UI 

**Current behavior**   

There is no way to add notes or comments or self-documentation to the VisualQuery Designer.

**Expected behavior**   
 
Add a new (Non-)DataSource that would simply allow you to leave some important info on the page so that when you come back to your query in the future and have to figure it out again, you can leave reminders, how-to info, or key details about what the query is doing, how or where it is being consumed, etc.

**Why change the behavior?**  

Logical progression as 2sxc becomes more useful, refined, and professional.

**Your environment**  

2sxc version(s): all thru 11.x/12.x
Browser, Dnn, Language: all

**Anything you would like to add**
 
Just a very simple text panel with a heading and body and the ability (drag) set its size; width and height.

**Comment by iJungleboy** [comment]
It's an interesting idea. 

Are you aware of the fact that you _can already_ add notes here: ?

![image](https://user-images.githubusercontent.com/5321186/129589473-f784eccd-6433-4d07-ace0-49837cbc1e7f.png)

**Comment by jeremy-farrance** [comment]
Yes, but 2 small text fields that show only 23 and 30 characters respectively, is simple not enough.

**Comment by iJungleboy** [comment]
Are you thinking of documenting 

1. a single source (like assigning notes to a source)
2. the entire query
3. something which is not tied to anything specific

**Comment by jeremy-farrance** [comment]
Definitely 2 is along the lines of what I am thinking. But the others make sense. And I am sure there are more use-cases beyond what I could think of.

**Comment by iJungleboy** [comment]
Would something in this area also do for what you're thinking of?

![image](https://user-images.githubusercontent.com/5321186/129591451-d0023c8f-8fed-47a7-b236-4c04fc4a97e3.png)

The reason I'm careful is that ATM printing a query is difficult, and we want to find a way to better print the query together with all the parts-configurations. So I don't want to introduce anything too creative ;)

**Comment by jeremy-farrance** [comment]
Yes, and to take that a step further, I cannot think of a reason why that space should not be showing the Pipeline Name and Description field from the Queries existing meta-data. Though it would be nice to edit it in place.

**Comment by iJungleboy** [comment]
I can see that this actually works already. 
![image](https://user-images.githubusercontent.com/5321186/147098258-5d838cd2-9373-49de-8144-8cae25ba3465.png)

Do we need anything else? WYSIWYG?

I'll close for now, but reopen based on what you write. thx

**Comment by jeremy-farrance** [comment]
This is fantastic, I had not noticed it got added, thank you!!
 
I definitely feel that it needs some or minimal formatting. Currently it strips CR/LF and encodes HTML.
 
![image](https://user-images.githubusercontent.com/653301/147126254-9f687666-ad1d-4aae-bdfe-e551fa53a10f.png)
 
Its too bad we don't have a simple option between plain text and WYSIWYG. Maybe you have plans for a Markdown (editor) input type with Write/Preview?
 
Anyhow, after playing for a bit, I definitely feel 
- plain text is adequate, but somewhat frustrating
- WYSIWYG is better
- Markdown would be best and perfect (someday)

**Comment by iJungleboy** [comment]
Ok, we'll review this.

**Comment by iJungleboy** [comment]
Just fyi: with the new #2671 feature you can already add notes to data sources etc. 

This doesn't resolve this request, but it's part of the challenge.
