### ISSUE TITLE
UI Bug: Single item sub-entities don't appear correctly in Edit dialog

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2507]
**I'm submitting a ...** 
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI

**Current behavior**   

Single item sub-entities don't show a label or even outline for the field when editing content. It only shows the plus until you actually use it.

![Screen Shot 2021-09-02 at 9 21 24 AM](https://user-images.githubusercontent.com/8751936/131885653-a7f9b75e-a2ef-4296-9997-41eb26e1a071.png)

**Expected behavior**   

**Instructions to Reproduce the Problem**
Create a content type that has a sub-entity, let's say "Image", and then add that sub entity to your content type as an entity picker. Then only allow 1 item to be added.

When you go to edit the content, you'll see a circle-plus icon "+" but you won't see anything else about it. So the content editor will get confused as to what field that is until they actually use it. This looks like a UI bug more than anything.

**Why change the behavior?**

Bug

**Your environment** 

N/A

* **2sxc version(s):** 12.2.1
* **Browser:** [all]
* **DNN:** [9.9.1] 
* **Language:** [any/all]

**Anything you would like to add**

I think I've noticed this on other recent versions.

**Comment by PagnoDunadan** [comment]
This is probably fixed in 12.04:

![image](https://user-images.githubusercontent.com/7113033/131975032-c81767cc-5eb5-485a-a0c5-ef453b571847.png)
