### ISSUE TITLE
Fails to upgrade from v6.6.6 to v7.1.1 on DNN 7.4 with SQL Azure database

### ISSUE THREAD

**Issue by STeveTeece** [2sic/2sxc#251]
HI there,

When updating on local development servers, all is good.

Live server is DNN v7.4 hosted as an Azure service with an Azure SQL database.

Attempting to update the live server generates an error:
![image](https://cloud.githubusercontent.com/assets/9351980/7746572/bf02a1ce-fff6-11e4-8492-56e740ea1c13.png)

After failed installation, Host/Extensions tab reports:
![image](https://cloud.githubusercontent.com/assets/9351980/7746604/17641398-fff7-11e4-9631-0d5248afe468.png)

Steve.

**Comment by iJungleboy** [comment]
@STeveTeece we were not able to look at this yet - but didn't get any other similar reports. Could it be that it was something specific to your installation? What's your status?

**Comment by STeveTeece** [comment]
@iJungleboy thanks for your reply.

I don't think there is anything specific in my installation that would cause this error.  The SQL is an Azure Web Service, and as such I have no control over it's configuration. The DNN is also installed in an Azure Web Service, so once again, I have limited control over config.

I have also run the installation file through the DNN EVS service (evs.dnnsoftware.com) and the report came back that even though the archive manifest contains the <AzureCompatible>True</AzureCompatible> tag, the extension is not azure compatible.

I will email you the results of the EVS check in a seperate email containing a .CSV file of the output.

Steve.

**Comment by iJungleboy** [comment]
The EVS test is not relevant for azure - this is confusing but it's true. Many people use 2sxc in azure - but we cannot pass the EVS test because we're using Entity Framework from Microsoft (which works in azure but won't pass EVS).
