### ISSUE TITLE
2sxc 7 issue with GroupContent

### ISSUE THREAD

**Issue by LeoTanoue** [2sic/2sxc#252]
Hi, I have noticed that on the newer version (7.02 and 7.1.1) of 2sxc some of the logic on the Edit List window must have changed. When I add a new App and click on Edit List it always display a empty (demo row):

![image](https://cloud.githubusercontent.com/assets/3587480/7750055/8f17405a-ff97-11e4-9c41-cd8e87c342d1.png)

 where I can start adding data, I instructed the marketing team to just click on it and start building content but since version 7 it gives them an error when doing this:

DotNetNuke.Services.Exceptions.PageLoadException: ContentGroup entity is null ---> System.Exception: ContentGroup entity is null
   at ToSic.SexyContent.ContentGroup..ctor(IEntity contentGroupEntity, Int32 zoneId, Int32 appId)
   at ToSic.SexyContent.EditContentGroupItem.get_ContentGroup()
   at ToSic.SexyContent.EditContentGroupItem.get_Entity()
   at ToSic.SexyContent.EditContentGroupItem.ProcessView()
   at ToSic.SexyContent.EditContentGroupItem.Page_Load(Object sender, EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   --- End of inner exception stack trace ---

Now, if I click on the Content.Toolbar pencil icon I can edit the content and that won't trigger the error, OR if I Add an Item before I go to the Edit List instead of trying to edit the default one it also works. It seems like the default (demo row) is null where before it used to create an instance of it as I clicked it. Any ideas if I'm on the right track? And is there any way someone can have that fixed?

Thank you,
Leonardo Tanoue

**Comment by iJungleboy** [comment]
I'm not quite sure I understand the problem
1. In the edit-list, if there are no items you get an error - correct?
2. In the normal mode (in-page) you don't get an error and can add - correct?

Your setup
* iis / azure?
* app or content
* template has a demo-item assigned or not?
* template has presentation or not, and if yes, has a default item or not?
* template has list-header or not, default...?
* template has list-presentation or not, default...?

**Comment by LeoTanoue** [comment]
Hi, I'm sorry if I wasn't clear.

1. Yes, that's correct. I update from 6.6.6 to 7.0.2 and I could edit the content of old Apps, but when I create a new one that has a list and go to Edit List it gives me that error.
2. Yes, if I just click on the pencil I can edit the content. OR if I click on Add Item before going into the Edit-list it also works.

as for my setup I have IIS, App, no demo-item, C# Razor Templates, no presentation. (DNN 07.03.02)
This happens to all my Apps that have list content. The ones that are simpler (like a text-image) work perfectly without throwing an error. Here's the example to a simple App for creating Breadcrumbs in different pages (I know the code isn't the best):

![image](https://cloud.githubusercontent.com/assets/3587480/7752260/17546f5e-ffa4-11e4-9769-b854f2ab5dd0.png)

Template:

![image](https://cloud.githubusercontent.com/assets/3587480/7752358/9d4d704c-ffa4-11e4-8dc5-8322faeb634c.png)

**Comment by iJungleboy** [comment]
Ok - so in summary
"Edit List Dialog fails when List has no items in it yet and no demo-item assigned"
Is this correct?

**Comment by LeoTanoue** [comment]
That's exactly it! Am I doing something wrong or were you able to duplicate this issue?

**Comment by iJungleboy** [comment]
I cannot duplicate the issue. Tried it with both
* Content
* App

I did this
1. In all cases I took an existing template, specified it to have no demo data but list support. 
2. Added the app/content and it showed the "no demo item exists" message. 
3. Clicked on edit list - saw the standard list functionality with (demo row) like in your screenshot

So the behavior I see is according to specs, no errors. 

Caution: could it be that this only happens on your home page? There are some really strange DNN bugs related to URLs on home.

**Comment by LeoTanoue** [comment]
Unfortunately it happens in all pages. I'll try to re-install the Module on my development website to see if it fixes it. (maybe something went wrong when I upgraded it?)

**Comment by iJungleboy** [comment]
Any update on this issue? If not I'll close it since we cannot duplicate it.

**Comment by LeoTanoue** [comment]
Hi, I wasn't able to fix the problem. This issue is more an annoyance other than something that is breaking or stopping my marketing team to enter content so I it isn't a huge deal. I will try to update to 7.1.2 and check if that fixes the issue.

**Comment by iJungleboy** [comment]
ok. keep me posted. I'll close this till further notice.
