### ISSUE TITLE
Import data into proper classes instead of dynamic objects

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2523]
**I'm submitting a ...** 
[x] feature request
[x] support request 

**...about**
[x] Razor templating
[x] Content Types or data management

**Current behavior**  
When we get data such as:
`var a = AsList(App.Data["EntityType"]);`
or
```
var q = App.Query["qName"];
var qAllCategories = AsList(q["stream"]);
```
It works for most operations in a view file.

However, when we need to pass these collections as parameters or even specify the type in any way, we need to use dynamic to do so, and the all hell breaks loose.

When I need to count it I get 'System.Array' does not contain a definition for 'Count' and 'object' does not contain a definition for 'Length'.

My question/suggestion is:
Is it possible to avoid dynamic and declare proper classes when importing App.Data or App.Query?

An example:

```
public class myCats {
    public string CatName {get;set;}
    public string CatDescription {get;set;}
    public int CatYear {get;set;}
    public string CatParent {get;set;}
}
```

When importing 
`AsList(App.Data["myCats"])`
It would get the data as a list of myCats

Is this possible?

**Comment by iJungleboy** [comment]
There are a few approaches to this, some which already work, some which would need extra implementation.

## What already works

### Custom conversion

You could create your own object and then convert a list to that, ca. like this

```
var typed = AsList(originalData).Select(d => new MyCats {
  CatName = d.Name,
  CatDescription = d.Description,
  // etc.
});
```

### Reader Object

You could create your type to provide this reading functionality, ca. like this:

```
public class MyCats {
    private dynamic _original;
    public MyCats(dynamic original) {
      _original = original;
    }
    public string CatName => _original.Name;
    public string CatDescription => _original.Description;
    public int CatYear => _original.Year;
    public string CatParent => _original.Parent;
}
var typed = AsList(originalData).Select(d => new MyCats(d));
```

### Using `EntityBasedType`

`ToSic.Eav.Data.EntityBasedType` is a base class meant for this - see [docs](https://docs.2sxc.org/api/dot-net/ToSic.Eav.Data.EntityBasedType.html?q=entitybasedtype). This is the approach we recommend when creating strongly typed code which is compiled (so not Razor, but DLLs which use 2sxc data. 

Here's an approx. code:

public class MyCats: ToSic.Eav.Data.EntityBasedType {

    public MyCats(IEntity original) : base(original) { }

    public string CatName => Get<string>("Name", "");
    public string CatDescription => Get<string>("Description", "");
    public int CatYear => Get<int>("Year", 0);
    public string CatParent => Get<IEnumerable<IEntity>>("Parent", null);
}
```

### Using JSON as intermediate step

This model would first create a simple json format (see [docs](https://docs.2sxc.org/api/dot-net/ToSic.Eav.DataFormats.EavLight.html) and then in a second step, convert to your typed object. This is not fully tested yet, as the `IJsonService` is new in 12.05 (not yet released ;). ca. code:

```
  var json = GetService<ToSic.Sxc.Web.IJsonService>();
  var typed = AsList(data).Select(d => json.To<MyCats>(json.ToJson(d)));
```

This version will lose references to other entities though, just fyi.

## What doesn't work

Fully automatic conversion is currently not implemented yet. For now I would use one of the above, as I'm not sure yet how to best fully automate this.

**Comment by iJungleboy** [comment]
I'll close this for now, as there are good options available, and anything else is too complex for the near-term roadmap.

**Comment by eXistenZe** [comment]
Could I ask you to provide some insight on this related issue?
https://stackoverflow.com/questions/72550598/casting-nested-ienumerable-dynamic-to-custom-classes
