### ISSUE TITLE
Need more specific error messages when a WebApi controller of an app fails to compile

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#253]
When a WebApi controller fails to compile, the WebApi responds with a general 500 error:

`{"Message":"An error has occurred."}`

We need more information here (exception type, line number, etc.) and probably also log it to the DNN event log. Maybe we can also add better exceptions when the webservice fails at runtime.

**Comment by iJungleboy** [comment]
duplicate with #991
