### ISSUE TITLE
Object reference error when doing App.Data.Update on entity with Empty field for grouping

### ISSUE THREAD

**Issue by Arno-p** [2sic/2sxc#2553]
**I'm submitting a ...**   
[x] bug report

**...about**   
[x] Content Types or data management
[x] APIs like REST

I have a list of items which i want to reorder with jquery and a 2sxc API call. When i have no Empty fields for grouping the App.Data.Update works perfectly. When i add an empty field for grouping of some fields the App.Data.Update gives an object reference error.

** Expected workings
When using Empty fields for grouping the App.Data.Update should save the data without giving an object reference error. 

**Instructions to Reproduce the Problem**
Create an entity with a few fields like name (string), order (number), details (empty), description (string) and required (bool). 

Create a view which shows the records of this entity and create a button to send a new integer for the order. The Web API should contain the following code:

public void ProcessReOrder(string elementguid, string order)
{
    var entityGuid = Guid.Parse(elementguid);
    decimal orderNr = Convert.ToDecimal(order);
    var tabId = Dnn.Tab.TabID;
    var modId = Dnn.Module.ModuleID;
    var block = ToSic.Sxc.Dnn.Factory.CmsBlock(tabId, modId);
    var dynCode = ToSic.Sxc.Dnn.Factory.DynamicCode(block);
    var formElement = dynCode.AsList(dynCode.App.Data["FormElements"]).Where(x => x.EntityGuId == entityGuid).FirstOrDefault();
    var converter = new EntitiesToDictionary();
    var data = converter.Convert(AsEntity(formElement));
data["Order"] = orderNr;
    dynCode.App.Data.Update(formElement.EntityId, data); <-- Throws the error when having a empty field for grouping
}

**Why change the behavior?**  
This should be changed so you can update entities with empty fields

**Your environment**  
Windows server 2012
IIS
DNN 9.10.1
2sxc 12.4.0
Language: dutch / English

**Comment by tvatavuk** [comment]
fix in https://github.com/2sic/eav-server/commit/bf5e707b56edf8267ae33a049cd0cf9e1191d94c
