### ISSUE TITLE
Wish for an AngularJS toolbar-helper

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#256]

**Comment by iJungleboy** [comment]
Thinking about it...

something like <sxc-toolbar /> would look about right, and would allow adding further options, maybe like

* <sxc-toolbar custom="{ ...} " />
* <sxc-toolbar for-id="17" />
* <sxc-toolbar for-id="17" actions="edit" />
* <sxc-toolbar for-content-type="Feedback" /> this would just give a new-button

must discuss...

**Comment by raphael-m** [comment]
Done and tested
