### ISSUE TITLE
Styles and Scripts dont load when adding a module on an empty page

### ISSUE THREAD

**Issue by ropalko** [2sic/2sxc#2565]
**I'm submitting a ...**   
[x] bug report

**...about**   
[x] edit experience / UI
[x] JS development

**Current behavior**   
When adding a module on an empty page, the styles and scripts dont load. You have to reload the page so that the files are loaded.
![image](https://user-images.githubusercontent.com/921493/138869742-eb39a7ba-b646-4a74-87ad-8b27f1a5ec06.png)
![image](https://user-images.githubusercontent.com/921493/138869749-4c2393c8-8cee-43ab-9644-90c03eece289.png)
![image](https://user-images.githubusercontent.com/921493/138869761-c6b641dd-9c92-4f62-af73-2d4c3b9677fb.png)

**Expected behavior**   
When adding a module the content should load via ajax and load all necessary files.

**Instructions to Reproduce the Problem**
Create a new page without any modules on it. Add an App or a Content Template

**Your environment**  

* **2sxc version(s):** 12.05.00 / 12.07.00
* **Browser:** [all]
* **DNN:** [9.1.1] 
* **Language:** [any/all]

**Comment by iJungleboy** [comment]
Now also resolved for non-jquery mode.
