### ISSUE TITLE
Couldn't add a field of type hyperlink (Image-Picker) to a Content-Type

### ISSUE THREAD

**Issue by dotnetgeek** [2sic/2sxc#257]
Hi,

I've a DNN 07.04.01 and the 7.1.1 of 2sxc installted (both is a fresh installation). I also installed the sample Content-Types and Templates.

I try to add a new Field to the Content-Type "Simple Content" as Hyperlink to be able to select an Image from the Image-Picker. 

The new field will be created and I can see the datatype "Hyperlink" in the list and also in the editor to add/edit the content. But the new Field didn't have a button to open the File/Image Explorer.  Only the label and an empty textfield is visible.

I didn't change the Templates because for my unterstanding these are only for the output of the website and has nothing todo with the content editing.

When I click on the "Hyperlink" (Manage Content Types => Design => Column Edit) the following exception will be thrown:

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:c5d4f9be-4f06-4058-858c-0acf94049c08
AssemblyVersion:7.4.1
PortalId:0
UserId:1
TabId:105
RawUrl:/page/ctl/eavmanagement/mid/549/AppID/5?popUp=true&ManagementMode=NewItem&AttributeSetId=121&keyNumber=338&keyGuid=&AssignmentObjectTypeId=2&ReturnUrl=http%3a%2f%2f%2fpage%2fctl%2feavmanagement%2fmid%2f549%2fA
Referrer: page/ctl/eavmanagement/mid/549/AppID/5?popUp=true&ManagementMode=ContentTypeFields&AttributeSetId=150
ExceptionHash:ySeLdIf7lMJZgi2LDcRCvg==
Message:Das Objekt mit Nullwert muss einen Wert haben.
InnerMessage:Das Objekt mit Nullwert muss einen Wert haben.
InnerStackTrace:
   bei System.Nullable`1.get_Value()
   bei ToSic.Eav.ManagementUI.EavManagement.OnInit(EventArgs e)
   bei System.Web.UI.Control.InitRecursive(Control namingContainer)
   bei System.Web.UI.Control.AddedControl(Control control, Int32 index)
   bei ToSic.SexyContent.EAVManagement.Page_Load(Object sender, EventArgs e)
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Whats going wrong? How can I add an Hyperlink-Field that become an Image-Picker?

I also try the Version 6.6.6 with the same behavior.

**Comment by iJungleboy** [comment]
Could it be that this only happens on your home page? there are issues with the url-provider of DNN. Please try from another page.

**Comment by dotnetgeek** [comment]
Hi, 

I did another test and it seems that it the Version 7.4.1 is the problem. I try it with brand new installed version 7.3.x  (DNN) and the module works fine. After I did an update to 7.4.1 the issue occurred.

Thanks,
Daniel

**Comment by iJungleboy** [comment]
great - but sorry I can't help :).
