### ISSUE TITLE
DNN 7.4.1 breaks various attribute-editing functions in 2sxc

### ISSUE THREAD

**Issue by nicpitsch** [2sic/2sxc#258]
Edit link in Content Type design ('Data Structure/Schema') of 'Content / Data' in 2sxc App tab leads to items listing instead to type metadata. I have installed 2sxc version 7.1.1. This issue is with DNN 7.4.1 but not with DNN 7.4.0. I have tested this with fresh DNN installations.
![2015-05-31_06-32-22](https://cloud.githubusercontent.com/assets/1652835/7900599/27091e8e-0762-11e5-8418-ba6d7c4eb581.jpg)

## Workaround till DNN is fixed
Note: It's a DNN bug and we have to wait. The main problem is that the URL - when in contains a return-url, gets confused by the parameters in the return URL. For a short workaround (I know it's ugly) - open the URL and remove the return-url. It will work that way.

**Comment by iJungleboy** [comment]
Sounds like an URL issue. Could you check with fiddler
- what url did the button try to open
- did the server maybe do a redirect or something?

Thanks

**Comment by nicpitsch** [comment]
Fiddler result (domains obfuscated):
**DNN 7.4.0**
- 302	/Home/ctl/eavmanagement/mid/2297/AppID/8?popUp=true&ManagementMode=ContentTypeFields&AttributeSetId=249&CultureDimension=%5BCultureDimension%5D
- 200	/Home/ctl/eavmanagement/mid/2297/AppID/8?popUp=true&ManagementMode=EditItem&EntityId=665&AssignmentObjectTypeId=2&ReturnUrl=http%3a%2f%2fwww.xxxx.ch%2fHome%2fctl%2feavmanagement%2fmid%2f2297%2fAppID%2f8%3fpopUp%3dtrue%26ManagementMode%3dContentTypeFields%26AttributeSetId%3d249%26CultureDimension%3d%5bCultureDimension%5d&CultureDimension=0
	
**DNN 7.4.1**
- 302	/Home/ctl/eavmanagement/mid/414/AppID/6?popUp=true&ManagementMode=ContentTypeFields&AttributeSetId=189
- 200	/Home/ctl/eavmanagement/mid/414/AppID/6?popUp=true&ManagementMode=EditItem&EntityId=625&AssignmentObjectTypeId=2&ReturnUrl=http%3a%2f%2fyyyy.ch%2fHome%2fctl%2feavmanagement%2fmid%2f414%2fAppID%2f6%3fpopUp%3dtrue%26ManagementMode%3dContentTypeFields%26AttributeSetId%3d189%26CultureDimension%3d%5bCultureDimension%5d&CultureDimension=0

There is no redirect (Fiddler).

**Comment by iJungleboy** [comment]
1. DNN has various URL issues - many of which go bad if the admin-dialog is opened on the home page. Could you try doing the same action from another page - just to confirm it is not this issue?

2. Are you really sure that the second URL on 7.4.1 (/Home/ctl/eavmanagement/mid/414/AppID/6?popUp=true&ManagementMode=EditItem&EntityId=625&AssignmentObjectTypeId=2&ReturnUrl=http%3a%2f%2fyyyy.ch%2fHome%2fctl%2feavmanagement%2fmid%2f414%2fAppID%2f6%3fpopUp%3dtrue%26ManagementMode%3dContentTypeFields%26AttributeSetId%3d189%26CultureDimension%3d%5bCultureDimension%5d&CultureDimension=0) opened the list of items? It doesn't really make sense. 

If you tested both cases and seem to think it's still a 2sxc issue, pls send me an admin-login to info...2sxc.org

**Comment by iJungleboy** [comment]
I can reproduce the issue. Sometimes I also don't get a list-view of the content-types but an error. We'll prioritize this; and I'll rename the issue.

**Comment by iJungleboy** [comment]
Posted to DNN, waiting for feedback...

**Comment by iJungleboy** [comment]
Found out more specifically the reason - URL rewriting in DNN is the issue (again :( ). 

![image](https://cloud.githubusercontent.com/assets/5321186/8008092/2aa56740-0ba0-11e5-818b-129c32e799b9.png)

**Comment by oellph** [comment]
New install and this issue still persists. Renders 2sxc unusable for me as I'm unable to edit data structure without it crashing website.

**Comment by iJungleboy** [comment]
@oellph very sorry :(. We've been trying to get DNN to fix this asap, but they are taking their time for the next release. We're also not sure, if they will fix in in 7.4.2, so we're migrating the ENTIRE UI to AngularJS to then not need the URL any more. This should be done in 2-3 weeks.

**Comment by oellph** [comment]
Thanks @iJungleboy, I'll look forward to that release and check back then.

**Comment by Frankwalraven** [comment]
I don't understand the workaround which nicpitsch describes. Can you explain the workarounds
I would be very happy. 2sxc is at this moment very useful for me in a 7.4.1 site

**Comment by iJungleboy** [comment]
The workaround: Basically take the url which is causing problems (it's a page in an IFrame) and remove everything behind the "returnurl" parameter.

**Comment by ech01** [comment]
Any update to this issue, either from DNN or 2sxc? An incremental workaround?

**Comment by iJungleboy** [comment]
@ech01 - dnn 742 should be out any day now - that should fix it for now. 
We're also in a big JS-refactoring, where we're making the module work without webforms. Once that's done, this problem will never occur again :)

**Comment by iJungleboy** [comment]
@all - the new version will be almost all JS UIs. We refactored just about everything we could think of :)
This of course also means risks that we forgot to implement something - because every possible feature which we had in webforms had to be duplicated in JS. 

We should have a beta out in about 10 days - and would really appreciate some testers. If you want to help, please ask to join https://www.facebook.com/groups/2sicSecretLab/

Love from Switzerland, Daniel

**Comment by oellph** [comment]
Really excited about this new version :)

**Comment by iJungleboy** [comment]
ready in beta 7.3 which comes today
