### ISSUE TITLE
How do I access the fields of an entity (allows multiple items) from a razor template?

### ISSUE THREAD

**Issue by hbuchel** [2sic/2sxc#260]
I have an event content type. In that content type, one of my fields is an entity field called "event_campus_location" that references my Campus content type, which allows multiple items (because events can occur on multiple campuses). In my Campus content type, the only field is campus_name.

I want to display those campus names the admin has selected for the event, but when I just use ```
```
@Content.event_campus_location
```
 in my razor template it outputs this text
```
System.Collections.Generic.List`1[ToSic.SexyContent.DynamicEntity]
```

I'm sure this is my lack of razor knowledge, but how do I output all of the campuses they may have selected in my razor template?

**Comment by iJungleboy** [comment]
please post general ussage questions on codeplex - because that's where other people will search and this is not an issue

Your solution is basically like
@foreach(var loc in @Content.event_campus_location) {
   <li>@loc.compus_name</li>
}
