### ISSUE TITLE
Error creating content in Oqtane 3 with 2sxc 12.08

### ISSUE THREAD

**Issue by CebiConRepo** [2sic/2sxc#2601]
I installed 2sxc in Oqtane 3.0 according to the instructions from Tonci Vatavuk (Youtube). So far everything is OK. However, if I want to create content (Image | Text) I get an error (see attachments). It looks as if everything is still on .NET 5.
(.NET 6 Libs are in the "refs" folder)

**Your environment**  

* **2sxc version(s):** 12.08.01  
* **Browser:** all
* **Oqtane:** 3.0
[ErrorMessage.log](https://github.com/2sic/2sxc/files/7587653/ErrorMessage.log)

<img width="1070" alt="Screenshot 2021-11-23 123618" src="https://user-images.githubusercontent.com/36736217/143017770-43ed6e8d-9aa1-4a35-871b-dfdbf8e4cda0.png">

**Comment by iJungleboy** [comment]
Oqtane 3 has some breaking changes. We'll release a matching 2sxc in a few days.

**Comment by CebiConRepo** [comment]
**WOW,**
super quick response!
Great, I'm excited and happy.

**Comment by iJungleboy** [comment]
All should work now with 12.10 :)
