### ISSUE TITLE
Link.To and multilanguage PageId

### ISSUE THREAD

**Issue by miguelvaz78** [2sic/2sxc#2610]
**I'm submitting a ...** 
[x] feature request
[x] not sure

**...about** 
[x] Razor templating

**Current behavior**   
When using Link.To in razor using the PageId parameter, the generated URL will always point to the specified page and language. 
Is there any way to get the language specific URL for the specified pageId but using the current UI culture? 

When using the content types Link field, I see this happening automatically. 
As an example, If I have a contacts (page:123) link, it will be correctly converted to the pageUrl using the current culture.
If I am in en-us => /en-us/contacts
If i am in pt-pt => /pt-pt/contactos

**Expected behavior**   
Is there any way to add this functionality in Link.To helper?
Example:
@Link.To(parameters: "id/" + item.EntityId, pageId: 123, *autoTranslate*: true)

When rendering the page in en-us culture => /en-us/contacts/id/1
When rendering the page in pt-pt culture => /pt-pt/contactos/id/1

I think I see something similar in:
https://github.com/2sic/2sxc/blob/f8e486dd257bc2d831ee94cc35dffad870c45077/Src/Dnn/ToSic.Sxc.Dnn/Dnn/Run/DnnValueConverter.cs
ToSic.Sxc.Dnn.Run.DnnValueConverter.ResolvePageLink(int id)

**Instructions to Reproduce the Problem**

**Why change the behavior?** 
More flexible razor templates without having to add additional complexity. 
Without this feature, i think the solution is to create a resource with the page ID if different languages.

**Your environment**  

* **2sxc version(s):** 11.X.X  
* **Browser:** [all]
* **DNN:** [all] 
* **Language:** [any/all ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
This is strange - I believe it always automatically links to the current language - that's the behavior we always intended. We'll have a look in a few days @tvatavuk

**Comment by miguelvaz78** [comment]
Hi guys,

Meanwhile I have overcome this issue by using resources. I created resources for my app using a URL / File type field configured to use pages picker. 
This way, the system automatically converts the page ID and renders the correct URL for this language dependent pages.
Here is the code that I used for rendering the link:

```
@inherits ToSic.Sxc.Dnn.RazorComponent
@using ToSic.Razor.Blade;

@{
  var item = PageData["Contact"];
  string detailLink = App.Resources.PersonDetailPage + "/id/" + item.EntityId+"";
}

<div class="contact-card-inner">
    <div class=" contact -card-body">
        <h6>@item.EntityTitle</h6>
        <div>
            <a class="text-primary" href='@detailLink'>@App.Resources.ViewProfile</a>
        </div>
    </div>
</div>
```

Although the initial situation is not resolved, I think this is a good enough solution to be considered as valid for this issue. So feel free to close this issue.
Thank you for the help!

**Comment by iJungleboy** [comment]
thx.
We still plan to improve it, so we'll leave it open for now.

**Comment by tvatavuk** [comment]
Possible that is just fixed as part of the recent commit yesterday... https://github.com/2sic/2sxc/blob/1bbd110862e4120c6124a1605dbfe78ebbbacc0b/Src/Dnn/ToSic.Sxc.Dnn.Core/Dnn/Web/DnnLinkHelper.cs#L32-L41

**Comment by iJungleboy** [comment]
@tvatavuk I don't think so - his need so to link to a page like contact - say tabid 42 - and it should automatically pick the FR version if he's on the FR page. 
I believe the value converter does this, so @content.Link resolves this, but link.to doesn't.

We would have to decide if we would change the default, or make it a special parameter

**Comment by iJungleboy** [comment]
... @tvatavuk my-bad. I think you're right, since you are passing it through the value converter. We may be actually changing the behavior this way in unintended manner. In 99% it should be ok, but if someone really wants to go to a specific page, this could lead to some surprises.

**Comment by tvatavuk** [comment]
Ups, You are 100% right👍. Great thinking👌.

**Comment by tvatavuk** [comment]
Better solution that by default preserve current behavior is commited.

To enable automatic translation of **PageId** to current language multilanguage **PageId**, in `Link.To` add new optional parameter `language: "current"` as in example bellow.

```cs
Link.To(pageId: 83, parameters: "details=" + post.UrlKey, language: "current");
```
