### ISSUE TITLE
Issue with Microsoft.Extensions.DependencyInjection

### ISSUE THREAD

**Issue by trouble2** [2sic/2sxc#2612]
**I'm submitting a ...**   
[x] bug report

**...about**   

[x] other / unknown

**Current behavior**   
tried to install 2sxc on my DNN environment and it gave me an error about the version of 
Microsoft.Extensions.DependencyInjection

**Expected behavior**   
NIce working module

**Instructions to Reproduce the Problem**
Try installing on DNN 9.10.1, don't know if it might be related to other modules which cause a version conflict.
But right now I solved it by adding multiple versions:

`<dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
        <assemblyIdentity name="Microsoft.Extensions.DependencyInjection.Abstractions" publicKeyToken="adb9793829ddae60" />
        <codeBase version="1.1.0.0" href="bin\2sxc\Microsoft.Extensions.DependencyInjection.Abstractions.dll" />
        <bindingRedirect oldVersion="0.0.0.0-1.1.0.0" newVersion="1.1.0.0" />
      </dependentAssembly>
      <dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
        <assemblyIdentity name="Microsoft.Extensions.DependencyInjection.Abstractions" publicKeyToken="adb9793829ddae60" />
        <codeBase version="2.2.0.0" href="bin\Microsoft.Extensions.DependencyInjection.Abstractions.dll" />
        <bindingRedirect oldVersion="1.1.0.1-32767.32767.32767.32767" newVersion="2.2.0.0" />
      </dependentAssembly>
      <dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
        <assemblyIdentity name="Microsoft.Extensions.DependencyInjection" publicKeyToken="adb9793829ddae60" />
        <codeBase version="1.1.0.0" href="bin\2sxc\Microsoft.Extensions.DependencyInjection.dll" />
        <bindingRedirect oldVersion="0.0.0.0-1.1.0.0" newVersion="1.1.0.0" />
      </dependentAssembly>
      <dependentAssembly xmlns="urn:schemas-microsoft-com:asm.v1">
        <assemblyIdentity name="Microsoft.Extensions.DependencyInjection" publicKeyToken="adb9793829ddae60" />
        <codeBase version="2.2.0.0" href="bin\2sxc\Microsoft.Extensions.DependencyInjection.dll" />
        <bindingRedirect oldVersion="1.1.0.1-32767.32767.32767.32767" newVersion="2.2.0.0" />
      </dependentAssembly>`

**Your environment**  
Local install

* **2sxc version(s):** 12.10.0  
* **Browser:** all 
* **DNN:**  9.10.1
* **Language:** any/all

**Comment by iJungleboy** [comment]
You are the first to report this, so I'm not sure if it's a 2sxc issue.

Note that we plan to release 2sxc 13 in ca. 10 days, where we will use the same DependencyInjection version as is used in DNN 9, so that should then resolve your issue. 

Because of this, I'll close this for now.
