### ISSUE TITLE
Error saving data on too quick clicking when uploading image

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [2sic/2sxc#2615]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] JS development
[x] Content Types or data management

**Current behavior**   
If you don't wait for an image to upload completely and click back in ADAM modal window while editing some entity with multiple properties (text and image types) then form doesn't work correctly. It might save entity with no text data and not let you save on edit next time.

**Expected behavior**   
Editing should work properly and average user shouldn't be able to break it by simply clicking things too fast. I'd suggest to disable back button in ADAM uploader until uploading is complete or canceled. Or probably you have better idea how to fix it.

**Instructions to Reproduce the Problem**

1. Add an instance of a 2sxc Gallery app to your page
2. Make sure that album entity has multiple fields including text type fields and thumbnail field and at least one text field like title is required and thumbnail is required and also you'll need url-key field
3. This was tested with a big image online so you might need maximum possible image file and also you might want to turn on throttling in dev tools befoe you proceed so that internet speed is slow enough for you to perform further steps on time
4. Press a button to create a new entity
5. Fill all the required fields except for thumbnail
5. Open ADAM to upload thumbnail (single image field)
6. Choose your big image to start uploading it
7. Press back button **before** image finishes uploading (this one should be quick enough or you'll be unable to reproduce a bug)
8. See that thumbnail text field is empty and has no text with image filename in it
9. Try to press save
10. See that save button is disabled and it says that you need to fix all the errors but doesn't give you text of error and no red fields
11. Check the thumbnail field which has empty textbox, which should contain filename
12. Open thumbnail editing ADAM modal window by clicking on a thumbnail field
13. See that image is still there but without deleting this image and uploading it again and waiting for it to complete upload you won't see image filename in a textfield and form won't work correctly

**Why change the behavior?**  
Because any impatient user with slow internet can break any application that uses image property for its entity.

**Your environment**  

* **2sxc version(s):** 11.11.2 (on production); 11.22.1 (on my local where I was testing it)
* **Browser:** Chrome Version 96.0.4664.45 (Official Build) (64-bit)
* **DNN:** v. 09.10.00 (0)
* **Language:** English

**Anything you would like to add**
By performing the same actions and using long text with special characters like double quotes and exclemation mark user also succeded in saving this form and entity was created but all the text fields were not saved and were empty. As result entity didn't have any title and url key so it was displayed in the list of entities but couldn't be opened by url because of missing url key in a url for it. Also when editing this last created entity after filling all the fields again it couldn't be saved because thumbnail is required and image was there but a filename was missing. It happened on production environment in users hands in front of my eyes and the error message just said "please fix all the errors:" and no error text was there. Also thumbnail field wasn't red it was just empty and gray placeholder even though image was still present inside. Personally I coulndn't reproduce it on my pc but I saw this situation happening. The only thing that was different at user's PC and production is that one of images inside album (not thumbnail) contained one cyrillic character which made album display images counter 1 more then amount of actual images it was showing because it couldn't generate correct url for a file with cyrillic characters. Could be another bug to replace non ascii characters for correct urls and images handling if that's still part of 2sxc module. We managed it by deliting file with cyrillic characters via admin site assets, renaming it locally and uploading again. But it could cause problems as well.
Also that cyrillic character containing image was among images before user performed actions with thumbnail described above. Probably that was a reason for empty entity. Not sure.
Saving almost empty entity just using admin side of module 2sxc is currently my main concern.

**Comment by PagnoDunadan** [comment]
The idea is that if you were to close ADAM before upload is finished, it would be ignored. I will check what happens here

**Comment by iJungleboy** [comment]
Cleaning up old issues.

I understand the problem but I believe we won't be investing any resources any time soon. 

If it's important to anybody, contributions are welcome.
