### ISSUE TITLE
2sxc.TemplateSelector.js causing multiple browser errors when saving 2sxc app item

### ISSUE THREAD

**Issue by grayspace** [2sic/2sxc#262]
When saving changes to a 2sxc app item, we have been experiencing browser alert errors. It will say "Error message: unknown" or something to that effect, then ask if I want to prevent this page from showing any more errors.

Here is the error message that gets logged in the console...

![capture](https://cloud.githubusercontent.com/assets/5733194/8007120/55136c34-0b5f-11e5-9c29-e8e0f3dd21ef.JPG)

**Comment by iJungleboy** [comment]
Could you check what the web-service is returning in the JSON? or if it's returning an error?
There had been a similar issue recently, and it turned out that the user was working on a secondary domain-alias, and the web-service calls went to the primary, so it was then a cross-domain issue. pls check, give feedback.

**Comment by grayspace** [comment]
I can't seem to find the JSON, but here is a bit more information. Hope it helps!

![error1](https://cloud.githubusercontent.com/assets/5733194/8058637/6c4ef93a-0e80-11e5-9dac-d63f86bf6c19.JPG)
![error2](https://cloud.githubusercontent.com/assets/5733194/8058638/6e1bcb1c-0e80-11e5-8b7d-1032b946789a.JPG)

**Comment by iJungleboy** [comment]
This doesn't help much :). 
Could you run fiddler - and then you'll see that a request is started to get a list of templates from the server. 
Or just send me a login to info ... 2sxc.org

**Comment by grayspace** [comment]
Sorry, this probably won't help much either, but if this is the right request there is no JSON coming in...

![error3](https://cloud.githubusercontent.com/assets/5733194/8059952/27126ba6-0e88-11e5-886f-4544ea56bb12.JPG)

**Comment by iJungleboy** [comment]
actually that's not the JSON call :). it's just a normal javascript
Could you send me a login?

**Comment by iJungleboy** [comment]
On your system I was able to reproduce the issue - thanks. I'm not quite certain yet what it is - but it's not JSON. I believe it has to do with the DNN-Iframe-concept. Give me another hour or so...

**Comment by iJungleboy** [comment]
Ok, I figured it out. It's a timing issue + something we should have done better. DNN does something funny with iframes, so the page is actually loaded at least 2x after pressing save. The first time it is reloaded again very quickly - and if the server is a bit slow, then a JSON request is cancelled. This was handled as if it were an error. 

I've fixed it and 2sxc 7.1.3 will have this, but your quick-fix is to just put the following code into the file

DesktopModules/ToSIC_.../JS/2sxc.ApiService.js
`
(function () {
    
    var module = angular.module('2sxc.api', []);

    module.factory('apiService', function ($http, $window) {

        return function (moduleId, settings) {

            var sf = $.ServicesFramework(moduleId);

            // Prepare HTTP headers for DNN Web API
            var headers = {
                ModuleId: sf.getModuleId(),
                TabId: sf.getTabId(),
                RequestVerificationToken: sf.getAntiForgeryValue()
            };

            settings.headers = $.extend({}, settings.headers, headers);
            settings.url = sf.getServiceRoot('2sxc') + settings.url;
            settings.params = $.extend({}, settings.params);

            var apiPromise = $http(settings);

            // Catch, log and show errors
            return apiPromise.catch(function (reason) {
                // 2015-06-10 2dm
                if(reason.status == 0)  // in this case the request was stopped by the browser; iframe closed or something
                    return;
                if ($window.console)
                    $window.console.log(reason);
                var error = "Error: ";
                error += (reason.data && reason.data.ExceptionMessage) ? reason.data.ExceptionMessage : "Unkown";
                error += "\r\nThe error has also been logged to the console.";
                $window.alert(error);
            });
        }
    });

})();
`

**Comment by grayspace** [comment]
Applied the quick-fix... works perfectly. Thanks, and our editors thank you, too!
