### ISSUE TITLE
ImageResizer not Working in 13.0.0

### ISSUE THREAD

**Issue by SteveChaba** [2sic/2sxc#2632]
**I'm submitting a ...**
[x] bug report

**...about**
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
On fresh installations of DNN and Oqtane, ImageResizer appears to be not working.  When removing the ImageResizer querystring parameters, the images load, however with them you receive:

Failed to load resource: the server responded with a status code of 500 ()

**Expected behavior**
ImageResizer works

**Instructions to Reproduce the Problem**
These are both fresh installations of DNN and Oqtane, I am unsure what is missing. 

**Why change the behavior?**
ImageResizer is unusable

**Your environment**
IIS

* **2sxc version(s):** 13.0.0 
* **Browser:** all
* **DNN:** 9.10.2
* **Oqtane:** 3.0.1 
* **Language:** any

**Comment by iJungleboy** [comment]
Could you give us more details on the 500 error?
Either from the Dnn logs or from the log4net logs?

Thx.

**Comment by SteveChaba** [comment]
Server Error in '/' Application.
Looking for "imageflow.dll" RID="win-x64", IsUnix=False, IsDotNetCore=False RelativeSearchPath="F:\slicksystems.ca.dnn9\bin"
Before searching: Unable to load DLL 'imageflow': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Error "The specified module could not be found" (126) loading imageflow from F:\slicksystems.ca.dnn9\bin\x64\imageflow.dll
> You may need to install the C Runtime from https://aka.ms/vs/16/release/vc_redist.x64.exe
Error "The specified module could not be found" (126) loading imageflow from F:\slicksystems.ca.dnn9\bin\imageflow.dll
> You may need to install the C Runtime from https://aka.ms/vs/16/release/vc_redist.x64.exe
Error "The specified module could not be found" (126) loading imageflow from F:\slicksystems.ca.dnn9\bin\runtimes\win-x64\native\imageflow.dll
> You may need to install the C Runtime from https://aka.ms/vs/16/release/vc_redist.x64.exe
File not found: F:\slicksystems.ca.dnn9\x64\imageflow.dll
File not found: F:\slicksystems.ca.dnn9\imageflow.dll
File not found: F:\slicksystems.ca.dnn9\runtimes\win-x64\native\imageflow.dll
File not found: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\552abc4f\2a927eb7\assembly\dl3\63b3c405\06d72c43_bbfcd701\x64\imageflow.dll
File not found: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\552abc4f\2a927eb7\assembly\dl3\63b3c405\06d72c43_bbfcd701\imageflow.dll
File not found: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\552abc4f\2a927eb7\assembly\dl3\63b3c405\06d72c43_bbfcd701\runtimes\win-x64\native\imageflow.dll
  at Imageflow.Bindings.NativeMethods.imageflow_context_create(UInt32 imageflowAbiVerMajor, UInt32 imageflowAbiVerMinor)
  at Imageflow.Bindings.NativeLibraryLoader.FixDllNotFoundException[T](String basename, Func`1 invokingOperation, IEnumerable`1 customSearchDirectories)
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.DllNotFoundException: Looking for "imageflow.dll" RID="win-x64", IsUnix=False, IsDotNetCore=False RelativeSearchPath="F:\slicksystems.ca.dnn9\bin"
Before searching: Unable to load DLL 'imageflow': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Error "The specified module could not be found" (126) loading imageflow from F:\slicksystems.ca.dnn9\bin\x64\imageflow.dll
> You may need to install the C Runtime from https://aka.ms/vs/16/release/vc_redist.x64.exe
Error "The specified module could not be found" (126) loading imageflow from F:\slicksystems.ca.dnn9\bin\imageflow.dll
> You may need to install the C Runtime from https://aka.ms/vs/16/release/vc_redist.x64.exe
Error "The specified module could not be found" (126) loading imageflow from F:\slicksystems.ca.dnn9\bin\runtimes\win-x64\native\imageflow.dll
> You may need to install the C Runtime from https://aka.ms/vs/16/release/vc_redist.x64.exe
File not found: F:\slicksystems.ca.dnn9\x64\imageflow.dll
File not found: F:\slicksystems.ca.dnn9\imageflow.dll
File not found: F:\slicksystems.ca.dnn9\runtimes\win-x64\native\imageflow.dll
File not found: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\552abc4f\2a927eb7\assembly\dl3\63b3c405\06d72c43_bbfcd701\x64\imageflow.dll
File not found: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\552abc4f\2a927eb7\assembly\dl3\63b3c405\06d72c43_bbfcd701\imageflow.dll
File not found: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\552abc4f\2a927eb7\assembly\dl3\63b3c405\06d72c43_bbfcd701\runtimes\win-x64\native\imageflow.dll
  at Imageflow.Bindings.NativeMethods.imageflow_context_create(UInt32 imageflowAbiVerMajor, UInt32 imageflowAbiVerMinor)
  at Imageflow.Bindings.NativeLibraryLoader.FixDllNotFoundException[T](String basename, Func`1 invokingOperation, IEnumerable`1 customSearchDirectories)


Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:


[DllNotFoundException: Looking for "imageflow.dll" RID="win-x64", IsUnix=False, IsDotNetCore=False RelativeSearchPath="F:\slicksystems.ca.dnn9\bin"
Before searching: Unable to load DLL 'imageflow': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Error "The specified module could not be found" (126) loading imageflow from F:\slicksystems.ca.dnn9\bin\x64\imageflow.dll
> You may need to install the C Runtime from https://aka.ms/vs/16/release/vc_redist.x64.exe
Error "The specified module could not be found" (126) loading imageflow from F:\slicksystems.ca.dnn9\bin\imageflow.dll
> You may need to install the C Runtime from https://aka.ms/vs/16/release/vc_redist.x64.exe
Error "The specified module could not be found" (126) loading imageflow from F:\slicksystems.ca.dnn9\bin\runtimes\win-x64\native\imageflow.dll
> You may need to install the C Runtime from https://aka.ms/vs/16/release/vc_redist.x64.exe
File not found: F:\slicksystems.ca.dnn9\x64\imageflow.dll
File not found: F:\slicksystems.ca.dnn9\imageflow.dll
File not found: F:\slicksystems.ca.dnn9\runtimes\win-x64\native\imageflow.dll
File not found: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\552abc4f\2a927eb7\assembly\dl3\63b3c405\06d72c43_bbfcd701\x64\imageflow.dll
File not found: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\552abc4f\2a927eb7\assembly\dl3\63b3c405\06d72c43_bbfcd701\imageflow.dll
File not found: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\552abc4f\2a927eb7\assembly\dl3\63b3c405\06d72c43_bbfcd701\runtimes\win-x64\native\imageflow.dll
   at Imageflow.Bindings.NativeMethods.imageflow_context_create(UInt32 imageflowAbiVerMajor, UInt32 imageflowAbiVerMinor)
   at Imageflow.Bindings.NativeLibraryLoader.FixDllNotFoundException[T](String basename, Func`1 invokingOperation, IEnumerable`1 customSearchDirectories)
]
   Imageflow.Bindings.LoadLogger.RaiseException() +2076
   Imageflow.Bindings.NativeLibraryLoader.FixDllNotFoundException(String basename, Func`1 invokingOperation, IEnumerable`1 customSearchDirectories) +274
   Imageflow.Bindings.JobContextHandle..ctor() +173
   Imageflow.Bindings.JobContext..ctor() +78
   Imageflow.Fluent.<FinishAsync>d__29.MoveNext() +489

[AggregateException: One or more errors occurred.]
   System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) +4761096
   ToSic.Imageflow.Dnn.Job.<ProcessUncached>d__25.MoveNext() +599
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   ToSic.Imageflow.Dnn.<<ProcessWithStreamCache>b__0>d.MoveNext() +245
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   Imazen.HybridCache.<<GetOrCreateBytes>b__0>d.MoveNext() +853
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   Imazen.Common.Concurrency.<TryExecuteAsync>d__5.MoveNext() +803
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   Imazen.HybridCache.<GetOrCreateBytes>d__35.MoveNext() +1109
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   Imazen.HybridCache.<GetOrCreateBytes>d__18.MoveNext() +236
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   ToSic.Imageflow.Dnn.<ProcessWithStreamCache>d__8.MoveNext() +411
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   ToSic.Imageflow.Dnn.<ImageflowRequestAsync>d__5.MoveNext() +574
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) +59
   System.Web.AsyncEventExecutionStep.InvokeEndHandler(IAsyncResult ar) +225
   System.Web.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar) +159

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3770.0

**Comment by SteveChaba** [comment]
I'm sorry, installed vc_redist.x64.exe and the issue is now gone.

**Comment by iJungleboy** [comment]
Ok. We'll monitor this - if more people have the same problem, we'll try to add better errors for people to find this. 

@tvatavuk just fyi.
