### ISSUE TITLE
Uncaught Can't find uiRoot

### ISSUE THREAD

**Issue by ropalko** [2sic/2sxc#2633]
**I'm submitting a ...**   
[x] bug report

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**   
As admin on a page without any 2sxc modules creating an error in console and the quick insert dont appear.
`Uncaught Can't find uiRoot - something went wrong, pls contact 2sxc.org`
![image](https://user-images.githubusercontent.com/921493/147655087-8f847089-4420-43d5-8d3a-4fcdebd6465c.png)

**Expected behavior**   
If there is no 2sxc module on the page the quick insert should appear.

**Instructions to Reproduce the Problem**

Unfortunately, I can't give any instructions for reproducing it, because it doesn't usually come to such an error.

* **2sxc version(s):** 12.10.00  
* **Browser:** all
* **DNN:** 9.6.1 
* **Language:** any

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Pls contact me directly so we can look at this :)

**Comment by iJungleboy** [comment]
This seems to be related to shared modules on all pages. Will look into it.

**Comment by iJungleboy** [comment]
Fixed in 13.01
