### ISSUE TITLE
Oqtane 3.02 - Error after select Content Text-Image (req. 2sxc 13.01)

### ISSUE THREAD

**Issue by CebiConRepo** [2sic/2sxc#2643]
Hi

unfortunately I can't get 2scx to run in Oqtane 3.0.2. I downloaded 2scx via ModuleManagement. And then restarted the app. So far everything is OK, but if I click on "Content|Image|Text" with the mouse, I get the following error (see image)

![22-01-2022 15-01-22](https://user-images.githubusercontent.com/36736217/150641676-aba14f6c-5f75-4da1-a05e-3ca84204f0d1.jpg)

am i doing something wrong?

**Comment by iJungleboy** [comment]
@tvatavuk can you please give guidance? If it's a common issue, we need to add it to the docs.

**Comment by tvatavuk** [comment]
@CebiConRepo please can You tell us more info?

So your Oqtane is latest version 3.0.2. Did You install Oqtane 3.0.2 **release version** from install zip [Oqtane.Framework.3.0.2.Install.zip](Oqtane.Framework.3.0.2.Install.zip) or you installed **[Source code](https://github.com/oqtane/oqtane.framework/archive/refs/tags/v3.0.2.zip) version** (or eg. cloned oqtane git repo and using master branch)?

What version of 2sxc module you installed in Oqtane. Is it version 12.8.0? That one is last on https://www.oqtane.net/.

![image](https://user-images.githubusercontent.com/2724850/150752123-14c20930-00aa-4e4d-9016-5c3f68f8ceef.png)

On what version of Windows You are running Oqtane web site?

What version of MS SQL Server you are using?

Please can You check that you have oqtane razor **[refs](https://github.com/2sic/oqtane-razor-refs)** folder in right place?
a. For release zip install of Oqtane 3.0.2 on .NET 6.0, adding refs is explained here [Install refs for Oqtane 3.0.0 on .NET6.0](https://azing.org/2sxc/r/nQjqJ_Wr).
b. For source code install of Oqtane 3.0.2 on .NET 6.0, for Debug build, please add **refs** folder in your `...\oqtane.framework\Oqtane.Server\bin\Debug\net6.0\`

![image](https://user-images.githubusercontent.com/2724850/150753915-fe4a8dee-f975-4491-b13c-67e52e99a8dc.png)

**Comment by CebiConRepo** [comment]
# Installing 2sxc

here is a detailed list of the steps up to the error.

## Environments:

- Windows 10 Pro: 21H2 x64
- SQL Express: 2019 15.0.2080
- SQL Server Management Studio: 18.10
- Visual Studio Enterprise 2022: 17.0.5
- Browser = Chrome: 97.0.4692.99 x64

## Steps to errors:

1. Download Source oqtane.framework-master.zip V 3.0.2
2. unzip the zip file
3. start Oqtane.sln
4. VS - Start without debugging
5. Config Wizard (_Wizard-Config.jpg_)
6. Login as "host"
7. Select "Admin Dashboard" - "Module Management"
8. Select "Install Module"
9. Select "Download" - "2sxc CMS and App (Plugin) Engine" (_Install-Module.jpg_)
10. After downloading modules, select "Install"
11. Message: Module Installed Successfully. You Must Restart Your Application To Apply These Changes.
12. Restart Application...
13. verify installation... (_InstallSuccess.jpg_)
14. Goto "MyPage"...
15. Select Module for page installation... (_InsertModule.jpg_)
16. Warning: The "refs" folder is missing...
17. Download "net6.0-refs.zip" and unzip file...
18. Copy folder to my "Debug\net6.0" installation... (_InstallRefs.jpg_)
19. "MyPage" after restarting the application (_InstallRecommended.jpg_)
20. Select "install recommended content package" (_BrowserMessage.jpg_)
21. after Install.. (_AfterInstall.jpg_)
22. Select first Icon "Basic Content", after 2 Second show this Error on Page (_ErrorPage.jpg_)

that's it...

---

![Wizard-Config](https://user-images.githubusercontent.com/36736217/150767918-ab1bb63b-eb41-40ee-9dc9-0ff370b79945.jpg) _WizardConfig.jpg_

---

![Install-Module](https://user-images.githubusercontent.com/36736217/150767920-2370e9d7-b918-4d12-ba85-6b78401c645c.jpg)_Install-Module.jpg_

---

![InstallSuccess](https://user-images.githubusercontent.com/36736217/150767935-14d8cf84-d2f4-4717-82d6-ca84998ab5bc.jpg)_InstallSuccess.jpg_

---

![InsertModule](https://user-images.githubusercontent.com/36736217/150767941-94107c3b-e87e-432e-9b8d-7048b61485db.jpg)_InsertModule.jpg_

---

![InstallRefs](https://user-images.githubusercontent.com/36736217/150767952-4470223f-01a4-477f-8597-d7ad190e0afa.jpg)
_InstallRefs.jpg_

---

![InstallRecommended](https://user-images.githubusercontent.com/36736217/150767958-a0f55b6f-0b26-45e1-aee1-04f10818b8db.jpg)_InstallRecommended.jpg_

---

![BrowserMessage](https://user-images.githubusercontent.com/36736217/150767961-2aacb810-2f20-42ed-9ec0-f890edb6178b.jpg)_BrowserMessage.jpg_

---

![AfterInstall](https://user-images.githubusercontent.com/36736217/150767964-f41d5445-45fe-4f54-bf26-346902a8abe8.jpg)
_AfterInstall.jpg_

---

![ErrorPage](https://user-images.githubusercontent.com/36736217/150767901-2f1c3ac3-ab5b-4851-9bbf-a59c25476871.jpg)
_ErrorPage.jpg_

**Comment by tvatavuk** [comment]
Dear Andreas, thx for your perfect detail info 👌.
I reproduced issue.

Situation is:
- First, I'm sorry, but 2sxc offered for download is old version, that is not working in Oqtane 3+. Here is latest info on [Oqtane and 2sxc Version Compatibilities](https://docs.2sxc.org/basics/platforms/oqtane/install.html#oqtane-and-2sxc-version-compatibilities). We missed publishing for download, several newest 2sxc module versions because of latest changes in oqtane module publish process, that we still need to adopt. All versions are published here https://github.com/2sic/2sxc/releases.
- For Oqtane 3.0.0 (but not 3.0.1 or 3.0.2) you can install 2sxc [12.10.0](https://github.com/2sic/2sxc/releases/download/v12.10.00/ToSic.Sxc.12.10.0.nupkg) or [13.0.0](https://github.com/2sic/2sxc/releases/download/v13.00.00/ToSic.Sxc.13.0.0.nupkg).
- For your Oqtane 3.0.2 you need to wait next release of 2sxc v13.1.0.
- Also please take a care that, there is Hot Reload Issue with source code version of Oqtane 3+ and 2sxc in VS2022 on .NET 6.0 that You can avoid in following way  https://r.2sxc.org/oqt-hr.

**Comment by iJungleboy** [comment]
Will re-open till wi release 13.01 as others may run into this too.

**Comment by CebiConRepo** [comment]
OK, danke für das Feedback...

**Comment by iJungleboy** [comment]
Just released 13.01 to solve this issue
