### ISSUE TITLE
Install recommended content package - Add Guidance if auto-install fails

### ISSUE THREAD

**Issue by CebiConRepo** [2sic/2sxc#2647]
Hi there,
first of all thanks for the new update 13.01.

## Environments:

- Windows 10 Pro: 21H2 x64
- SQL Express: 2019 15.0.2080
- SQL Server Management Studio: 18.10
- Visual Studio Enterprise 2022: 17.0.5
- Browser = Chrome: 97.0.4692.99 x64
- Oqtane 3.0.2 (Source Code - master, hot reload-disabled)
- Download 2sxc (13.01) over Module Management...

unfortunately I get a console error message when trying to select "Install recommended content package".

```javascript
Failed to load resource: the server responded with a status of 400 (Bad Request)
http://localhost:44357/api/sxc/sys/install/RemotePackage?packageUrl=https://gettingstarted.2sxc.org/Packages/hybrid12/2sxcApp_Content_13.00.00.zip
```
![Error](https://user-images.githubusercontent.com/36736217/150957070-6ef49f60-9178-458e-a4c7-17e4c190455e.jpg)

**Comment by iJungleboy** [comment]
@CebiConRepo Just some background: basically the server must get this file:
https://gettingstarted.2sxc.org/Packages/hybrid12/2sxcApp_Content_13.00.00.zip
 from our server and install it. 

Could it be that you have a firewall or something that blocks you from doing this?

We'll try to find a better way to detect a problem and give you guidance what you can do.

**Comment by iJungleboy** [comment]
@tvatavuk Please

1. Try to detect the problem when loading
2. Give the UI a clear message about this
3. Then update the inpage-code to capture this message and show a link to a checklist how to manually install content-templates.  https://azing.org/2sxc/r/0O4OymoA 
4. if necessary, update the checklist to have newer screenshots ;)

**Comment by iJungleboy** [comment]
@CebiConRepo in case our guess is correct, please use the checklist to install content-templates manually: https://azing.org/2sxc/r/0O4OymoA

**Comment by iJungleboy** [comment]
@tvatavuk is this done? I'm not sure any more?

**Comment by tvatavuk** [comment]
@iJungleboy sorry but not yet. I'm planning to do it after the other 2 tasks with higher priority.
