### ISSUE TITLE
Improve entity data type for linq querying

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2656]
**I'm submitting a ...**
[x] feature request
[x] not sure

**...about**  
[x] Razor templating
[x] Content Types or data management

**Current behavior**  
If you have a data type named "Companies" and another named "Employees", you can create one entity field in Companies labeled "CompanyEmployees" where you select the employees for that company (I believe you can understand the relation type one-to-many).

When you loop through Companies, sometimes it would be really helpful if you could use linq that specific data fetching, like:

```
foreach(var c in Companies) {
    <h1>@c.CompanyName</h1>
    <h3>Male employees</h3>
    foreach(var e in Companies.Employees.Where( a => a.Gender == "Male" )) {
        <p>@e.EmployeeName</p>
    }
}
```

But this will immediately generate:
"Cannot use a lambda expression as an argument to a dynamically dispatched operation without first casting it to a delegate or expression tree type"
The same for .Count() which is amazingly useful.

Can this entity data type be improved to use linq directly in it?

**Comment by iJungleboy** [comment]
Yes, best check up on the LINQ Razor tutorials https://2sxc.org/dnn-tutorials/en/razor#linq

This is not a LINQ problem, but related to the Razor compiler and the way LINQ works with C# Extension Methods. The safest fix is if you have something that's not working well, to

```
  // eg. Companies.Employees isn't working well
  var empList = AsList(Companies.Employees);
  @empList.Count()
```
In some cases this is not enough, in that case you must add "as object" like this

```
  var empList = AsList(Companies.Employees as object);
```

This is just a weakness in dynamically typed, live-compiled code like Razor. Not perfect, but it's the best we could come up with.
