### ISSUE TITLE
Oqtane-Error: Empty path name is not legal (happen on App & Content)

### ISSUE THREAD

**Issue by erw13n** [2sic/2sxc#2664]
**I'm submitting a ...**   
[x] bug report

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**   
When adding App/Content, after choosing template it throw error:
```
Error: System.AggregateException: One or more errors occurred. (Empty path name is not legal. (Parameter 'path')) ---> System.ArgumentException: Empty path name is not legal. (Parameter 'path') at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize) at System.IO.File.OpenRead(String path) at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RazorReferenceManager.CreateMetadataReference(String path) at System.Linq.Enumerable.SelectListIterator`2.ToList() at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RazorReferenceManager.GetCompilationReferences() at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory) at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RazorReferenceManager.get_CompilationReferences() at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.LazyMetadataReferenceFeature.get_References() at Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors() at Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument) at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(RazorCodeDocument codeDocument) at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document) at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.ProcessCore(RazorCodeDocument codeDocument) at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Process(RazorProjectItem projectItem) at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.CompileAndEmit(String relativePath) at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.OnCacheMiss(String normalizedPath) --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath) at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage) at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromPath(String executingFilePath, String pagePath, Boolean isMainPage) at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.GetView(String executingFilePath, String viewPath, Boolean isMainPage) at ToSic.Sxc.Razor.RazorCompiler.FindView(ActionContext actionContext, String partialName) at ToSic.Sxc.Razor.RazorCompiler.CompileView(String partialName, Action`1 configure) at ToSic.Sxc.Razor.RazorRenderer.RenderToStringAsync[TModel](String partialName, TModel model, Action`1 configure) at ToSic.Sxc.Razor.RazorEngine.RenderTask() --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) at System.Threading.Tasks.Task.Wait() at ToSic.Sxc.Razor.RazorEngine.RenderTemplate() at ToSic.Sxc.Engines.EngineBase.Render() at ToSic.Sxc.Blocks.BlockBuilder.RenderInternal()
```

But the Admin functionality (App configuration) is working fine.
Error happen only when App/Content is displaying on front-page.

**Instructions to Reproduce the Problem**

- Install [Oqtane.Framework.3.0.2.Install.zip](https://github.com/oqtane/oqtane.framework/releases/download/v3.0.2/Oqtane.Framework.3.0.2.Install.zip) to IIS
- Install 2sxc App 13.01.00 using Module Management
- Restart
- Add 2sxc App/Content module into the page
- Get warning about refs - Install and extract refs into root folder
- Restart
- Install all App/Content
- Choose any template/content
- Error show immediately

**Why change the behavior?**  

**Your environment**  

* **2sxc version(s):** 13.01.00  
* **Browser:** [Chrome]
* **Oqtane:** [3.0.2] 

**Screenshot**
![image](https://user-images.githubusercontent.com/792847/153920238-4c9132bb-bb4d-4327-a1a6-ce3cb80e1d17.png)

![image](https://user-images.githubusercontent.com/792847/153920401-e04a1356-09de-4c49-b315-d34dcecdfac0.png)

**Comment by erw13n** [comment]
Testing again with fresh installation for Oqtane and 2sxc, which is running well.
Perhaps there's a mistake I did during installation.

**Comment by ghhv** [comment]
Yeah, also got the same issue on a test install.. Prior to this problem I did have hot re-load enabled and the install would always fail. I guess I'll try a fresh install as well.

**Comment by ghhv** [comment]
Worked on fresh install - but hot-reload magically turned on again which stopped the initial install.

**Comment by iJungleboy** [comment]
The next release of 2sxc should have some warnings and guidance when the system is in hot-reload. We hope this will alleviate the problem.

**Comment by tvatavuk** [comment]
> Worked on fresh install - but hot-reload magically turned on again which stopped the initial install.

There are several ways to disable hot-reload in VS2022. The most simple one is explained here https://r.2sxc.org/oqt-hr.

@ghhv please can You check in `Oqtane.Server\Properties\launchSettings.json` that you have `"hotReloadEnabled":false`.
