### ISSUE TITLE
Improve Script-Extractor to also respect defer and other attributes

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#2669]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 
[x] feature request

**...about**   
[x] Razor templating
[x] JS development

**Current behavior**   

ATM scripts get extracted from the HTML and added to the page header/footer. But the extraction seems to lose some properties, like `defer`. See also https://stackoverflow.com/questions/71301935/script-link-in-header-enableoptimizations-strips-attributes

**Expected behavior**   

Ideally the behavior would be smarter, and preserve the parts that can be preserved and provided to Dnn/Oqtane. 

* **2sxc version(s):** 13.03

**Comment by tvatavuk** [comment]
2sxc is enhanced to capture additional attributes in script extraction and provide this attributes within script resources in dnn and oqt.

Related commits: https://github.com/2sic/2sxc/compare/d4610a3da4...5d29900ff5

**Comment by iJungleboy** [comment]
Should be fixed, thx to @tvatavuk
