### ISSUE TITLE
URL keys in view settings stopped working in v13

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2679]
**I'm submitting a ...** 
[x] bug report

**...about**
[x] admin experience UI
[x] Razor templating

**Current behavior** 
If you set a URL key (Name on url path) on the view settings to /Something it does not activate the correct view when you access site/page/Something
This only happened after updating from v12 to v13.

**Expected behavior** 
View is activated

**Your environment** 

* **2sxc version(s):** 13.03.00
* **Browser:** [all]
* **DNN:** [all | 9.10.1] 
* **Language:** [English]

**Comment by iJungleboy** [comment]
I verified that it actually works. Just as an example: the 2sxc blog https://2sxc.org/en/blog uses this too and it works. 

I'm pretty sure something is wrong with your configuration, so I'll close this for now.

**Comment by eXistenZe** [comment]
Please reopen.
Replying to the github e-mail doesn't seem to send the answer to the topic anymore.

Blog and other apps use the format siteurl/page/querystring/.* 
This format works as intended, but is only useful for getting values from the url into the visual query or the view template.

The format I need is siteurl/page/UrlKeyToActivateTheTemplate
This worked for the last years, but it is no longer the case after v13.

**Comment by iJungleboy** [comment]
Just to verify - normally subpages are activated when it's a key/value combination. so /page/key/value. Is this not working, or is it only /page/key that's not working?

**Comment by eXistenZe** [comment]
I'll be blunt about this. If it was a bug/non intended feature, it was one of the best bugs ever.

I used this in a dozen apps or more. Creating a new DNN page for every view I need within an app is just nonsense. Slow, poor performance, hours to setup, hours to optimize.

I use one app, one data model, several views for managing and viewing data. The logical way to accomplish this is with one page and several views linked by a home page menu or a menu button in each view.

This way, site/dnnpage/viewurl makes all sense and has several usecases. And you could even complement it with viewurl/whatevervalue because it worked quite well.

site/dnnpage/key/value only has one usecase: list and details apps.

Please reconsider this request.

**Comment by iJungleboy** [comment]
Maybe I don't understand the problem you're describing.

My understanding is, that you added `something` to the view params, instead of `something/.*` - if that's all - then you can just add `/.*` to the view configuration and it fixes everything. 

What am I missing?

**Comment by eXistenZe** [comment]
Blog uses the page/stringkey/.* fotmat. That still works.

I was refering to the page/stringkey format.

All my apps stopped working after v13 because of this.
