### ISSUE TITLE
Formula on DateTime Field Bug

### ISSUE THREAD

**Issue by jtherrien-accuraty** [2sic/2sxc#2680]
**I'm submitting a ...**   
[ x ] bug report => search github for a similar issue before submitting 

**...about**   
[x] JS development
[x] Content Types or data management
[x] other / unknown

**Current behavior**   
When you edit an entity with a DateTime field that has it's value as the target of a formula the value returned by the formula is converted to local time while being treated as UTC. Every time the entity is edited and saved the DateTime value is adjusted by the UTC offset which eventually changes the date accordingly. In my case being CST every time the entity is edited and saved the DateTime field is adjusted by -6 hours. This happens whether the "Use Time-Picker" option is enabled or not.

**Expected behavior**   
When editing an entity containing a DateTime field whose value is being targeted by a formula it should show the current DateTime value being returned by the formula without timezone adjustment.

**Instructions to Reproduce the Problem**

1. Add a DateTime field to an entity with "Use Time-Picker" turned on so you can see the time update. Note: whether "Use Time-Picker" is enabled or not didn't appear to have any impact on the bug from my testing. 
2. Add a formula to the DateTime field with a target of "Field Value" leaving everything else default.
3. Add a new Entity and set the DateTime field, and remember the DateTime being set. 
4. Save the entity.
5. Open the new entity to edit and check the DateTime field and it will be adjusted by the UTC offset.

**Why change the behavior?**  
Without a fix then value targeting formulas are unusable on DateTime fields. For a case where a formula would be necessary: I have a DateStart and DateEnd for an event, and if DateEnd is empty I want to set it to the same day being selected for DateStart. I can get this to work, but from then on every time the entity is updated the DateEnd is moved up 6 hours since I am in CST. Since the time is set to midnight when "Use Time-Picker" is false that means the first time the entity is edited the DateEnd field is updated to the day before the actual value.

**Your environment**  
Tested on a site running on Windows Server 2019 Standard with Dnn v9.10.2 and 2sxc v13.2.00 and v13.3.00, as well as a local site on Windows 10 with Dnn v9.8.1 and 2sxc v13.1.00 

* **2sxc version(s):** 13.1.00, 13.2.00, 13.3.00  
* **Browser:** tested on Chrome 98.0.4758.102, Firefox 98.0, and Edge 99.0.1150.36
* **DNN:** 9.8.1 and 9.10.2
* **Language:** English

**Anything you would like to add**

**Comment by iJungleboy** [comment]
@PagnoDunadan could you verify what he's describing, then discuss fix w/me?

**Comment by PagnoDunadan** [comment]
The idea is that if formula provides Date object, we will adjust for time zone offset and convert to UTC:

`v1 (data, context) { return new Date(); }`

If formula provides UTC time, we will not adjust it:

`v1 (data, context) { return new Date().toJSON(); }`

Value correction runs immediately after user's formula is finished, before value gets to the form. Form only works with UTC time.

**Comment by jtherrien-accuraty** [comment]
Adding .toJSON() does fix the issues for me. Is this in the docs or noted anywhere? If not I believe it should be as I would expect to be able to leave the default `v1(data, context) { return data.value; }` as is and have it work appropriately without having to update it to `v1(data, context) { return data.value.toJSON(); }` to prevent it from being converted again.

**Comment by iJungleboy** [comment]
@PagnoDunadan could you verify again? because return data.value should have a non-change. I believe that is the case isn't it?

**Comment by PagnoDunadan** [comment]
Formula update happened because backend and frontend ISO strings did not match:

Frontend: 2022-03-30T16:20:21.000Z
Backend: 2022-03-30T16:20:21Z

and value correction assumed these are different values. This will now be ignored.

Thank you @jtherrien-accuraty for finding this bug.
