### ISSUE TITLE
Commas in a Query Name cause display glitch in Field Settings

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2681]
I'm submitting a 
[x] bug report 

**...about**
[x] admin experience UI

Entity field type > Input Type = Query based entity/item-picker

**Current behavior**  
If you use a comma in a Query Name like, "Lookups - Entity, Dropdown by Query"
 
In the entity field's settings, when you select that Query from the dropdown, it splits the result in to two items so it looks "glitchy" like this:

![image](https://user-images.githubusercontent.com/653301/158077925-da96f441-4efe-4293-95e5-fb71f6ff5a93.png)
 
**Expected behavior**  
Either prevent us from putting commas in the Query Names or adjust the UI to handle commas.

**Your environment**  

* **2sxc version(s):** 13.03.00 (latest)
* **Browser:** all
* **DNN:** 9.10.02
* **Language:** any/all

**Comment by iJungleboy** [comment]
Just a heads-up: we'll look at it and try to fix, but it's not high priority, so it may take some time.

**Comment by iJungleboy** [comment]
@PagnoDunadan Let's do this one quickly, simply by using a strange separation character for this dropdown like `§` paragraph sig or something which we can expect to never be in a title ;)
