### ISSUE TITLE
v13 performs really bad on browser

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2683]
**I'm submitting a ...**  
[x] not sure

**...about**
[x] other / unknown

**Current behavior** 
2sxc v12 was blazing fast on all browsers.
Since I updated to v13, the browser hangs for a second or two every now and then. Both on firefox and chrome. Both on the 2sxc guid when editing items, or the view where toolbars are present. This is noticeable when scrolling or when typing.

* **2sxc version(s):** 13
* **DNN:** [ 9.10.2 ] 
* **Language:** [ English ]

**Comment by iJungleboy** [comment]
Are you rereferring to speed on the page, or in the edit-ui?

**Comment by iJungleboy** [comment]
Maybe you could record a short video?

**Comment by eXistenZe** [comment]
Please close for now. I can replicate this is other pages with no 2sxc apps.
