### ISSUE TITLE
Run Action contentitems throws an unexpected error

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2689]
**I'm submitting a ...**  

[x] bug report  

**...about**

[x] edit experience / UI
[x] JS development
[x] Content Types or data management

**Current behavior**  
We are using Role (group ID) permissions, the Feature (Core/PermissionCheckGroups) is on and most things appear to work. So the user encountering the error is not an Administrator. They  are in the Role (ID=7) of Data Manager. In the App Settings, we've added a Permission Configuration:

Title: Data Managers CRUD/Approve All Content
Permission Type: Content-Type Permissions
Identity: 7,8
Condition: Edit
Grant: All Content (CRUD + Approve)
 
So the page is set to All Users: View

The module (our 2sxc App) has permissions set to inherit view permissions from page and then both Roles (7 and 8) are added and Edit is checked.

There is a Content Type named "Lookups" (only 3 text fields) and on the page we have a New button and a Manage button. The New button works fine, Display the add item form and successfully saves the new one.
    `onclick="$2sxc(this).manage.run({ action: 'new', contentType: 'Lookups' })"`
 
However, the Manage button **throws an error**, its onclick is:
    `onclick="$2sxc(this).manage.run({ action: 'contentitems', contentType: 'Lookups' })"`

The error looks like below and the console has:
    `(x)  GET https://===url===/api/2sxc/admin/type/get?appId=5&contentTypeId=Lookups 401   zone.js:2863`

![image](https://user-images.githubusercontent.com/653301/159377819-950c02df-ad9c-4bde-b250-0c7f2519700a.png)

**Expected behavior**  
Given my understanding of the permissions, the user should be able to open the full content-type Edit Data dialog and manage all the records.

**Instructions to Reproduce the Problem**
I believe there is enough info above to reproduce the error.

**Your environment**  

* **2sxc version(s):** 13.30 
* **Browser:** all/any (same results in both Chrome and Edge)
* **DNN:** 9.10.2 
* **Language:** any/all

**Anything you would like to add**
I have tried a number of other Permissions settings on the Lookups content-type, e.g. I gave it Grant=Full Control and I still get the same error.
 
Note that if I change the PAGE permissions so that the 2 roles have **Edit for the whole page,** it is fixed, the full edit data dialog popups up. However, that is no good because it gives the user access to Page Settings and the ability to add modules/content etc., which we do not want.

**Comment by iJungleboy** [comment]
Did you upgrade a site or create a new one?

If you did upgrade, v13.03 changed how features are activated - you used to do this in an iframe and now it happens in real-time, but since the way the features are activated is stored differently, you must do it again. Can you verify?

Would the same app work in 2sxc v12?

Could you create a simple demo-app showing the issue?

**Comment by iJungleboy** [comment]
I re-read the issue and I think you must also add permissions to read the schema (it's a separat permission). I believe that call is failing. 

I'm very sure this will fix it, so I'll close the issue unless you report it's still not working.

**Comment by jeremy-farrance** [comment]
See screenshot below, added, but it did not fix it. Cleared cache, recycled the apppool, etc. Logged the in-role users out and back in and still, same error as screenclipped above.
 
I even tried "Full Control (usually host only)" at the App level and that did not fix it.
 
Also, I am confused on the App permissions. What does Permission-Type actually do? It seems to have no affect on anything I've tried. I thought maybe it was changing the available options in the Grant dropdown, but haven't seen (or missed) that happening.

![image](https://user-images.githubusercontent.com/653301/160134588-3d29c3e2-63be-4520-9708-c4a71c225b16.png)

**Comment by jeremy-farrance** [comment]
I also have to stress the point that I find it odd that I have to give Page-level edit permissions to get it to work. Giving the role Module-level edit permissions does NOT work. Strange, no?

**Comment by iJungleboy** [comment]
The `Permission-Type` has no technical functionality. It just hides some fields in cases where it doesn't make sense. 
In future we plan to have a better guidance to entering this data, as it is confusing. But we just haven't found the time for this yet. For example, it should change what options are available, but we're just not there yet. 

Maybe if you post your app I can have a quick look.
