### ISSUE TITLE
Delete of item with an assigned child fails

### ISSUE THREAD

**Issue by maaaximum-at-2sic** [2sic/2sxc#2691]
**I'm submitting a ...** 
[x] bug report

**...about** 
[x] APIs like REST

**Current behavior**  
When performing a delete of an item which has an assigned child, the operation fails and requires a force to succeed.

**Expected behavior**  
When deleting an item with an assigned child the operation should succeed without a force.

**Instructions to Reproduce the Problem**

1. Create a content type with an existing entity as child:

![image](https://user-images.githubusercontent.com/89256748/159497435-c92f0415-6d01-41ca-b77b-316201684013.png)

2. Create an item with an existing entity as child:

![image](https://user-images.githubusercontent.com/89256748/159497801-75be6ea0-42e9-496c-90fb-00e4c5a918dd.png)

3. Delete the item:
![image](https://user-images.githubusercontent.com/89256748/159497898-9b7ec532-e760-4d13-9013-83abb75b94a1.png)

4. Error occurs:
![image](https://user-images.githubusercontent.com/89256748/159497998-db074bbb-cae5-4d04-8c79-adce8c276b83.png)

Request endpoint:
http://ipa-entwicklung.dnndev.me/en-us/api/2sxc/admin/entity/delete?contentType=3671ef7c-fccd-4441-997f-2a1ab1df94ef&id=3504&appId=4&force=false

Error Message:
Can't delete Item 3504. It is used by others. Found 1 entities which are assigned children: BlogPost.
Type: System.InvalidOperationException
StackTrace:
at ToSic.Eav.Apps.Parts.EntitiesManager.BatchCheckCanDelete(Int32[] ids, Boolean force, Boolean skipIfCant, Nullable`1 parentId, String parentField) in C:\\Projects\\2sxc\\eav-server\\ToSic.Eav.Apps\\Parts\\Entity\\EntitiesManager_Delete.cs:line 70\r\n   at ToSic.Eav.Apps.Parts.EntitiesManager.Delete(Int32[] ids, String contentType, Boolean force, Boolean skipIfCant, Nullable`1 parentId, String parentField) in C:\\Projects\\2sxc\\eav-server\\ToSic.Eav.Apps\\Parts\\Entity\\EntitiesManager_Delete.cs:line 37\r\n...

5. Force delete (succeeds):
![image](https://user-images.githubusercontent.com/89256748/159498104-74601293-23c0-4b33-bd9b-597fc043e9f5.png)

Request endpoint:
http://ipa-entwicklung.dnndev.me/en-us/api/2sxc/admin/entity/delete?contentType=3671ef7c-fccd-4441-997f-2a1ab1df94ef&id=3504&appId=4&force=true

**Why change the behavior?** 

- Force not yet implemented in JS API 
- Bug

**Your environment** 
OS: Windows 11 Pro

* **2sxc version(s):** 13.04.00
* **Browser:** Chrome (Version 99.0.4844.74)
* **DNN:** 09.10.02
* **Language:** any

**Comment by iJungleboy** [comment]
should be fixed in 13.05
