### ISSUE TITLE
Null Object Reference on WebResources Breaking App

### ISSUE THREAD

**Issue by jtherrien-accuraty** [2sic/2sxc#2692]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**   
In the App settings under the System Settings for the App (not site or Global) there is a "Web Resources" set that is pointing to a record that doesn't exist anymore resulting in all instances of modules that call GetService<ToSic.Sxc.Web.IPageService>().Activate() to throw the error "System.NullReferenceException: Object reference not set to an instance of an object. at ToSic.Eav.Data.PropertyStackNavigator.GetResultOfChild(String field, String[] dimensions, ILog logOrNull, Boolean treatEmptyAsDefault". Since the record doesn't exist, the field in the Admin interface just shows (item not found) without any controls or options to remove/edit/add new to fix the issue. Here is a screenshot of the issue with the panel:
![chrome_lE7AZkKhXg](https://user-images.githubusercontent.com/62106757/159583154-9cc65307-db3c-4300-8352-68954b38341a.png)

**Expected behavior**   
The field should still have an option to delete the link, or at least replace it with a new one.

**Instructions to Reproduce the Problem**

The steps that caused the issue were: 

1. In a custom app go to Admin the app
2. Go to the "App" tab
3. Under "Settings" under the "System Settings" column click on the edit pencil in the first row that has the same name as the custom app (aka not "Site" or "Global")
4. Expand "Web Resources", and add a record
5. Enter a name and a code snippet, and save.
6. Save the "System Settings"
7. Open the "System Settings" again
8. try to delete the record, but for me it failed to delete.
9. Close the "System Settings", and go to the "Data" tab.
10. Change the scope to "Configuration (Views etc.)
11. Open "WebResource", and delete the record that was added. The views of the app that end up calling GetService<ToSic.Sxc.Web.IPageService>().Activate are now all broken showing only the NullReferenceException error message. 
12. Go back to admin the app, and go back to the "App" tab
13. Click on the edit pencil under the "System Settings" column of the "Settings" section.
14. Expand "Web Resources" and it will only say "(item not found)" without any options or controls to fix it. The only thing that you can get is if you hover over "(item not found)" it will open a tooltip showing the GUID it is looking for.

**Why change the behavior?**  
Without a change there is an unfixable error that completely breaks the app.

**Your environment**  

* **2sxc version(s):** 13.3.0  
* **Browser:** all [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** 9.10.02 [all | 7.4.2 | 8.X.X | 9.X.X ] 
* **Language:** English [any/all | English | German | other ]

**Anything you would like to add**
Is there any way for me to fix this without restoring a backup from last night?

**Comment by iJungleboy** [comment]
We created a pre-release of 13.05 just for you. 

[2sic_2SexyContent_13.05.00_Install.zip](https://github.com/2sic/2sxc/files/8332529/2sic_2SexyContent_13.05.00_Install.zip)

1. Please download and install.
2. Then login as super user and go edit the data. It will look like before.
3. Then activate debug mode, and you should now have more buttons like delete (to remove the null-entry) which were not available before

**Comment by jtherrien-accuraty** [comment]
That worked perfectly, and allowed me to remove the broken link so the app is working again. There is still an issue though, even with the update. I am unable to delete the record being added to "Web Resources" under System Settings unless I delete the entity from Data>Scope: Configuration causing the app to break, and using the new feature in the pre-release you sent to remove the link to the missing record and fix the app. When I try to remove the record the proper way I get this error:
![chrome_BeMxRejByq](https://user-images.githubusercontent.com/62106757/159721601-a4f31d01-099f-4c10-bf60-3214f4750882.png)

While trying to get information for this issue I found a few thing that may help diagnose the issue, or may be issues themselves. The "Web Resources" section of the app's System Settings only lets you add a single item, and the record is created in the Configuration section of Data under "WebResource". There is a "WebResources" content-type here as well that appears to be a multi-entity wrapper for "WebResource", and I am guessing that this is what the "Web Resources" in System Settings is supposed to be pointing to. I added a resource here name "Test", and the "Settings Identifier" shows "WebResources.Test" as pointed out in the following screenshot: 
![chrome_JaWd1hN9R5](https://user-images.githubusercontent.com/62106757/159722936-d0598c0b-8022-4cc5-822e-8cf3dfc08486.png)

Here is a screenshot of the "Analyze Combined Settings" output pointing out that it added my entry to both Settings.WebResources without any name, and to a new key in Settings with the appropriate name "Test":
![DFMX8tEEGJ](https://user-images.githubusercontent.com/62106757/159724031-8d638646-6df5-4322-a870-5e4e31eef9bb.png)

Now with all that in place nothing appears to happen when I call `GetService<ToSic.Sxc.Web.IPageService>().Activate("Test");`, so it seems like even though the record is being added something isn't configured correctly to then use the added record.

**Comment by jtherrien-accuraty** [comment]
That works for me, thank you!

**Comment by iJungleboy** [comment]
My guess is that the normal delete has trouble because of the emoji in the type name. 

We added this to clearly distinct the settings types from any others, and make them appear at the end in the data-types list. 

We'll check...

@PagnoDunadan could you check this - basically I think removing/deleting the system-typed-item from the edit-UI, where the typename has the gear or culture emoji seems to fail, and my guess is it's not correctly encoded in the API call.

**Comment by PagnoDunadan** [comment]
System Settings for current App:

![image](https://user-images.githubusercontent.com/7113033/159890019-d027b04f-b0e7-4fb4-9625-da03929e03bf.png)

is in Data > Configuration > System Settings and you can always delete it there if stuff fails again @jtherrien-accuraty .

Deleting Web Resource indeed fails because of the emoji in ContentTypeName.

Possible solutions:
- if backend allows request body on delete, then ContentTypeName can be stored there or
- decoding ContentTypeName on the backend or
- figuring out GUID for this ContentTypeName and using it in delete url

**Comment by iJungleboy** [comment]
Encoding / Decoding sounds about right. @PagnoDunadan  is it encoded correctly?

**Comment by PagnoDunadan** [comment]
Ecoding/decoding in the url might not be the issue here. WebResource is the only one with different emoji:

![image](https://user-images.githubusercontent.com/7113033/159904894-4fd61813-616f-4017-94aa-d4f3a9a65975.png)

**Comment by PagnoDunadan** [comment]
I've tested GoogleMaps and yes, it works

```
api/admin/entity/delete?contentType=%E2%9A%99%EF%B8%8FGoogleMaps&id=35416&appId=3105&force=false&parentId=35415&parentField=EntityTest
```

**Comment by iJungleboy** [comment]
This does indeed seem to be a different gear-character, one is ⚙, the other is ⚙. In some systems, they look the same, in others not: 
![image](https://user-images.githubusercontent.com/5321186/159927867-0dca9003-8276-4b6a-8602-084c3f0537e9.png)
I'll fix asap.
