### ISSUE TITLE
Page picker not allowing pages to be picked under a redirected parent

### ISSUE THREAD

**Issue by garyfrater** [2sic/2sxc#2694]
**I'm submitting a ...**
[x] bug report

**...about** 
[x] edit experience / UI

**Current behavior**
If a page is set as a redirect to another page but has child pages under it the page picker doesn't allow the child pages to be selected.

**Expected behavior** 
Page picker should allow selection of the child pages of redirected parents

**Instructions to Reproduce the Problem**
For example in the following the Working at NOA page is being redirected to the Vacancies page, but the client would like to link to the United Teaching child page that sits underneath it:

![image](https://user-images.githubusercontent.com/21355016/160106022-d8288022-654c-4aa0-a011-85512499e37f.png)

However the Working at NOA page doesn't show in the page picker:

![image](https://user-images.githubusercontent.com/21355016/160107468-7ee820c7-ae50-483c-a243-16883a24a9d5.png)

**Your environment**

* **2sxc version(s):** 13.4.0
* **Browser:** all
* **DNN:** 9.X.X 
* **Language:** all

**Comment by iJungleboy** [comment]
Should be fixed in v15.06 to be released today or tomorrow.Should be fixed in v15.06 to be released today or tomorrow.
