### ISSUE TITLE
Core Features cannot be enabled

### ISSUE THREAD

**Issue by rockgobo** [2sic/2sxc#2695]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 
[] feature request
[] support request => use stackoverflow and tag with 2sxc https://stackoverflow.com/questions/tagged/2sxc
[] security issue => do not submit here but on https://2sxc.org/en/contact
[] not sure

**...about**   
[] edit experience / UI
[x] admin experience UI
[] Razor templating
[] JS development
[] Content Types or data management
[] APIs like REST
[x] DNN parts
[x] other / unknown

**Current behavior**   
I tried to enable the public forms as described in https://2sxc.org/en/blog/post/new-features-management-in-2sxc-9-30 but in the core license section any option is disabled telling me that the "license is not active". In the reason column for any option i can read "unlicensed". I would like to add a costum button for non admins to edit some data and if i am right i need to enable "public forms" in order to use Edit.Enable() bringing up the edit api for non admins.
in the configuration folder i can find a features.json which tells me that the feature is anabled, but the UI and the behaviour on the website tells me that it is not. I also can not find any license file.

**Expected behavior**   
Core Features can just enabled as the license is free and the webside tells, that the core license is added automatically. 

**Why change the behavior?**  
It seems that the license model introduced in 13.2 is missing something.

**Your environment**  

* **2sxc version(s):** 13.4  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [all | 7.4.2 | 8.X.X | 9.X.X ] 
* **Language:** [any/all | English | German | other ]

**Comment by iJungleboy** [comment]
All core features should just work and allow toggling.

There is a bug in 13.03 and 13.04 which seems to always reset all toggles which are not set to true explicitly. 

It is fixed in 13.05, should be released today or tomorrow.
