### ISSUE TITLE
C# WebApi - Possible Breaking Change for SaveInAdam

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#2706]
**I'm submitting a ...**
[x] bug report
[x] not sure

**...about** 
[x] APIs like REST

**Current behavior**
Similar to our other issue #2696 when upgrading from 2SXC v13.1.0, it appears that when we try and save a file in ADAM using SaveInAdam within a private c# method in WebAPI like this:

```
public class StripeWebhookController : Custom.Dnn.Api12
{
     ...
     private void UpdateBoatSlips(dynamic owner, int propertyId, dynamic boatSlips)
     {
                    ...
                    SaveInAdam(
                        stream: ms,
                        fileName: file,
                        contentType: "Watercraft",
                        guid: watercraftGuid,
                        field: "RegistrationPhoto");
                    ...
     }
}
```

...we get the following error message:

> can't save in ADAM - Features https://2sxc.org/r/f/79b9f5f8-d104-458b-8e8f-9f4a11c5935e not enabled - see also https://2sxc.org/help?tag=features

This has been working previous to the upgrade. Have permissions in c# WebAPI changed as well, and do we now need to enable the public upload feature and change permissions on the data field?

**Expected behavior**
The file should be saved since it should be bypassing user context security using c# WebAPI.

* **2sxc version(s):** 13.5.0
* **Browser:** all
* **DNN:** 09.10.02
* **Language:** all

**Comment by iJungleboy** [comment]
feature configuration has changed in v13. Unfortunately this means they must be re-activated to work again. 
It's easier than before, but unfortunately this is necessary. 

we'll try to see if we can do something but for now just re-activate the feature in the new ui.

I'll create a separate task for the upgrade path.

**Comment by tpperlman** [comment]
Thank you  @iJungleboy. We disabled/re-enabled "Public use of Edit Form", "Public Upload of Files" and "SaveInAdam API" which did the trick!
