### ISSUE TITLE
Cannot create a new DataPipline in DNN7.4.1

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#271]
It must be an url issue. 
The pipeline designer is called with this url which causes  an "Object reference not set to an instance of an object" Exception  

http://localhost/dnt/2sxc?mid=521&popUp=true&AppId=10&ctl=editcontentgroup&AttributeSetId=284&AssignmentObjectTypeId=4&prefill=%7B%22TestParameters%22%3A%22%5BModule%3AModuleID%5D%3D521%22%7D&editMode=New&ReturnUrl=%2Fdnt%2F2sxc%2Fctl%2Fpipelinemanagement%2Fmid%2F521%3FReturnUrl%3D%25252fdnt%25252f2sxc%25252fctl%25252fWebApiHelp%25252fmid%25252f521%25252fAppId%25252f10%25253fpopUp%25253dtrue%26popUp%3Dtrue%26AppId%3D10

If I remove the returnUrl Parameter, it continues as expected:
http://localhost/dnt/2sxc?mid=521&popUp=true&AppId=10&ctl=editcontentgroup&AttributeSetId=284&AssignmentObjectTypeId=4&prefill=%7B%22TestParameters%22%3A%22%5BModule%3AModuleID%5D%3D521%22%7D&editMode=New

The content of the form gets saved, however it will not open the pipeline designer.

If you start the Pipeline Manager again, the new Pipline can be edited in the designer.

**Comment by SCullman** [comment]
Well, even if the designer opens it is not useable. You always get blank forms when you try to edit properties..

**Comment by iJungleboy** [comment]
Yes, sorry. It's a dnn 7.4.1 bug - see also #258 
It's in dnntracker but at the moment we're powerless :(
Hope that DNN 7.4.2 comes out in ca. 10 days...

**Comment by iJungleboy** [comment]
Duplicate bug, so I'll close it for now.
