### ISSUE TITLE
Epic: Create CSP ContentSecurityPolicy Framework

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#2710]
**I'm submitting a ...**   
[x] epic request

**...about**   
[x] crazy enhanced security

**Current behavior**   

Dnn has nothing to do CSP in the box. We want to change this. 

* **2sxc version(s):** 13

**Comment by Tychodewaard** [comment]
CSP as I know it means Content Security Policy. As in https://report-uri.com/home/generate
Is that what you mean as well or is ClientSecurityPolicy something else?

**Comment by iJungleboy** [comment]
I wrote the title wrong ;). Fixed. 
That's a neat tool BTW, once I have something running, will probably link that too. thx.
