### ISSUE TITLE
ImageFlow Throws Errors on Images with a side Greater Than 10,000px

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2728]
**I'm submitting a ...**   
[x] bug report 

**...about**   
[x] Large Images and ImageFlow (ADAM?)

**Current behavior**   
If you try to upload and use an image with more than 10,000 pixels width or height, errors are throw. The image does not output.

**Expected behavior**  
You should be able to just use any image, even if "huge."

**Instructions to Reproduce the Problem**
Download this image at Original Size (12800 x 9600) from Unsplash to your local machine and then try to use it in 2sxc.
[https://unsplash.com/photos/_tF3vug2FhQ](https://unsplash.com/photos/_tF3vug2FhQ)

**Why change the behavior?** 
Because 2sxc is awesome and it should just work. :)

**Your environment**  
Server is Windows 2019, .NET Framework 4.8, everything up to date.

* **2sxc version(s):** 13.10 LTS
* **Browser:**  Any/All (Chrome 101)
* **DNN:** Any? I am running v9.10.02 
* **Language:** [any/all]

**Anything you would like to add**

If you are local, you can see the error:

```
Server Error in '/' Application.

ArgumentInvalid: SizeLimitExceeded: Frame width 12799 exceeds max_frame_size.w 10000 at
imageflow_core\src\flow\execution_engine.rs:270:28
https://github.com/imazen/imageflow/blob/1f6dc67eef41132d5d3300676daa5d42ae7f8941/imageflow_core\src\flow\execution_engine.rs#L270
imageflow_core\src\flow\execution_engine.rs:400:89
https://github.com/imazen/imageflow/blob/1f6dc67eef41132d5d3300676daa5d42ae7f8941/imageflow_core\src\flow\execution_engine.rs#L400
imageflow_core\src\context.rs:419:59
https://github.com/imazen/imageflow/blob/1f6dc67eef41132d5d3300676daa5d42ae7f8941/imageflow_core\src\context.rs#L419
imageflow_core\src\context_methods.rs:50:68
https://github.com/imazen/imageflow/blob/1f6dc67eef41132d5d3300676daa5d42ae7f8941/imageflow_core\src\context_methods.rs#L50

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.
```

**Comment by iJungleboy** [comment]
I totally agree that it should work ;)

We are using https://www.imageflow.io/ in the background, and are reliant to what that can do. 

If you feel that this should be addressed, please open an issue there - we would of course update our code as soon as it's fixed.

Since we cannot do anything on our side for now, I'll close the issue.

**Comment by jeremy-farrance** [comment]
Is 2sxc using ImageFlow .NET Framework or Standard? or?

**Comment by jeremy-farrance** [comment]
Also, it looks like something you can configure for.

[https://docs.imageflow.io/json/introduction.html](https://docs.imageflow.io/json/introduction.html)

[https://github.com/imazen/imageflow/blob/1f6dc67eef41132d5d3300676daa5d42ae7f8941/docs/src/json/security.md](https://github.com/imazen/imageflow/blob/1f6dc67eef41132d5d3300676daa5d42ae7f8941/docs/src/json/security.md)
