### ISSUE TITLE
New code editor does not wrap text

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2738]
**I'm submitting a ...**  
[x] bug report
[x] not sure

**...about** 
[x] Razor templating

**Current behavior**
The new Visual Studio Code / Monaco editor does not wrap the text, which makes it very hard to read in some situations.

**Expected behavior**
Wrap the text by default or give the user some configuration possibilities within 2sxc.

**Why change the behavior?**
Code should never be hidden.
Even in the 2sxc news page you can see the code overflowing:

`https://2sxc.org/en/blog/post/vs-code-built-into-2sxc-13-monaco-editor`

**Comment by iJungleboy** [comment]
As of now I don't think we'll fix this.

The main reason is that some people may want it, others not - which introduces a whole set of problems how to manage such settings etc. 

In general it's best practice to keep the characters per line short, and wrap the code. If this is observed, the feature isn't needed. 

But the main reason is the settings-management for different preferences which would be so much work that we cannot focus on this ATM.
