### ISSUE TITLE
Pipeline Clone/Delete fails with HTTP 404

### ISSUE THREAD

**Issue by BeniGemperle** [2sic/2sxc#274]
http://mydnn/DesktopModules/2sxc/API/EAV/PipelineDesigner/ClonePipeline?appId=3
http://mydnn/DesktopModules/2sxc/API/EAV/PipelineDesigner/DeletePipeline?appId=3

Using 2sxc 7.1.2.0 with EAV 4.0.1.0

**Comment by iJungleboy** [comment]
Was able to reproduce. Reason is the pipeline id is missing in the url. Same call with 
http://localhost:28049/DesktopModules/2sxc/API/eav/PipelineDesigner/ClonePipeline?appId=25&id=3872

worked.

**Comment by iJungleboy** [comment]
Reason was Id-renaming in JSON from EntityId to Id. Updated code, fixed.

**Comment by iJungleboy** [comment]
forgot to merge before, now merging int 7.2.3
