### ISSUE TITLE
Fresh Install 2sxc on Oqtane 3.1.1

### ISSUE THREAD

**Issue by AndreasDecke** [2sic/2sxc#2743]
**[x]** bug report => search github for a similar issue before submitting 
**[x]** not sure

I'm trying to install 2sxc on Oqtane 3.1.1 (SQL local db). Unfortunately, I can't get past the point "install recommended content package". See the attached pictures.

**Instructions to Reproduce the Problem**

- After install fresh Oqtane 3.1.1
- Module Management - Install 2sxc
- Restart Application
- Create new "Test" Page
- Add "Content" from 2sxc
- Click Buttton "install recommended content package"
- see images

**Your environment**  

* Windows 10 Pro
* VS 2022 17.2.x
* **2sxc version(s):** 13.11.0
* **Browser:** Chrome XX | Firefox XX | Edge XX
* **Language:** English

Information: The direct call in the browser from "https://gettingstarted.2sxc.org/Packages/hybrid12/2sxcApp_Content_13.10.02.zip" works...

![SystemInfo](https://user-images.githubusercontent.com/45657628/168045684-8de30b9f-a91b-4ce3-83f4-4758765d5499.jpg)
![ModuleManagement](https://user-images.githubusercontent.com/45657628/168045681-7b4af39b-6c51-465b-891a-363f982d1fbd.jpg)
![TestPage](https://user-images.githubusercontent.com/45657628/168045690-2b65ea1f-5407-47af-8a73-9060afa5fb69.jpg)
![InstallStep-1](https://user-images.githubusercontent.com/45657628/168045671-10c5e6ab-6429-4979-954b-566f74f81790.jpg)
![InstallStep-2](https://user-images.githubusercontent.com/45657628/168045679-d87c45ca-3d41-49cb-9a71-15035ec32e85.jpg)

### thanks for any kind of help...

**Comment by tvatavuk** [comment]
Hi @AndreasDecke, on your last screenshot is alert message related to [Hot Reload](https://r.2sxc.org/oqt-hr) that need to be DISABLED in `Oqtane.Server\Properties\launchSettings.json` during installation of Content templates (or App templates).

This is required on for Oqtane Framework source code developer version only while running in Visual Studio 2022. 

How to do that is explained here: [https://r.2sxc.org/oqt-hr](https://r.2sxc.org/oqt-hr).

**Comment by AndreasDecke** [comment]
Hello,

sorry I turned off HotReload in VS 2022. Thanks for the tip! Now everything works great.
