### ISSUE TITLE
WebAPI - Api Controller Finder Error

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#2753]
**I'm submitting a ...**
[x] bug report => search github for a similar issue before submitting 

**...about**
[x] APIs like REST

**Current behavior**
We recently updated from 2SXC v13.06 because the Core Features (e.g. public forms/uploads) kept disabling with each app recycle.

After upgrading, we're now experiencing an error with every WebAPI endpoint using the 2sxc manager like this:

`$2sxc(mid).webApi.post("MyController/MyEndpoint", {}, data, true);`

The following error is returned:

```
Message:Api Controller Finder Error: Trying to find app name, unexpected error - possibly bad/invalid headers. Check event-log, code and inner exception.

StackTrace:

InnerMessage:Tried to auto detect app by name '', url params or block context, all failed.

InnerStackTrace:

   at ToSic.Sxc.Context.ContextResolver.AppNameRouteBlock(String nameOrPath) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Context\ContextResolver.cs:line 94
   at ToSic.Sxc.Apps.AppFolder.GetAppFolder() in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Apps\AppFolder.cs:line 14
   at ToSic.Sxc.Dnn.AppFolderUtilities.GetAppFolder[T](IServiceProvider sp, HttpRequestMessage request, ILog log, Func`3 wrapLog) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.WebApi\Dnn\AppFolderUtilities.cs:line 47
```

Note that we are including the jQuery/JS services like this in the razor file:

```
GetService<IPageService>().Activate("2sxc.JsCore");
GetService<IPageService>().Activate("jQuery");
```

* **2sxc version(s):** 13.11
* **Browser:** All
* **DNN:** 09.10.02
* **Language:** All

**Anything you would like to add**

**Comment by iJungleboy** [comment]
We just spotted this today, and should release a 13.12 fixing this in about an hour...

**Comment by tpperlman** [comment]
@iJungleboy BAM! You guys are faaaast! Thank you!!

**Comment by iJungleboy** [comment]
@tpperlman thanks - that's what happens when we dogfood - we're victims of our own work ;)
