### ISSUE TITLE
2sxc 13.12.00 LTS built with older version of Content

### ISSUE THREAD

**Issue by skarpik** [2sic/2sxc#2756]
**I'm submitting a ...**   

[x] bug report => search github for a similar issue before submitting 

**...about**   

[x] admin experience UI

**Current behavior**   

13.12.00 LTS is built using Content 13.10.02 

**Expected behavior**   

The most recent version of Content is v13.10.03 which has a bugfix for issue #2742

**Instructions to Reproduce the Problem**

Built a DNN v9.10.2 test website to test v13.12.00 and noticed the old version of Content.

**Why change the behavior?**  

Content v13.10.03 fixes a bug present in v13.10.02

**Your environment**  

DNN 9.10.2
2sxc 13.12.00 LTS
Browser: all
Language: English

**Anything you would like to add**

I am guessing that the build instructions inadvertently pointed to Content 13.10.02

**Comment by iJungleboy** [comment]
@getBlup @maaaximum-at-2sic pls check - seems auto-content-installer gives old content-release

**Comment by maaaximum-at-2sic** [comment]
@skarpik thank you for reporting this bug. The latest content-release is now available on the 2sxc auto-installer.
