### ISSUE TITLE
Extensions/Features - Enabled features resetting on app recycle

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#2758]
**I'm submitting a ...**
[x] bug report

**...about**
[x] admin experience UI

**Current behavior**
We have enabled Extensions/Features for Public Forms and Public File Uploads using the new licensing mechanism, but each time we recycle the app the enabled features become disabled. This is causing all customer forms to fail with an error similar to below in the logs and preventing the launch of a new customer site:

`Message:can't save in ADAM - Features https://2sxc.org/r/f/79b9f5f8-d104-458b-8e8f-9f4a11c5935e not enabled - see also https://2sxc.org/help?tag=features`

We originally thought this might be a result of using a dnndev.me domain for local development, but it also happens on our publicly accessible server.

**Expected behavior**
The enabled Extensions/Features should persist beyond app recycles.

**Instructions to Reproduce the Problem**
Register a new license, enable one or more Extensions/Feature (e.g. public forms/uploads), note they function as expected. Recycle the app pool and return to the Extensions/Features panel and note the enabled features are disabled again.

**Additional information**
We noticed this behavior also in v13.06 but upgraded to see if it would resolve the issue. For whatever reason, these Core/Core+ features are reset after each app pool recycle.

* **2sxc version(s):** 13.12
* **Browser:** All
* **DNN:** 09.10.02
* **Language:** All

**Comment by tpperlman** [comment]
Here's what we have in that folder:

![Screenshot 2022-05-25 120109](https://user-images.githubusercontent.com/1871915/170306646-6584df67-c800-454f-b22b-ed0265cf7bc3.jpg)

**Comment by iJungleboy** [comment]
you should also have a `features.json` file

at least once you toggle stuff. pls check

Note: i'll be offline for a few days till monday.

**Comment by iJungleboy** [comment]
BTW: To me it feels like the system can't store the features as they change. 

Maybe try to check the insights on web-api calls as you toggle - see if you see something unusual.

**Comment by tpperlman** [comment]
No features.json file is being created any time we activate/renew a license or if we enable/disable features.

It is weird, on 2sxc versions prior to 13.06 (e.g. 13.01) we were not having a problem with Extensions/Features. Off-hand, it seems to have started with 13.06, but we'd have to look through all our previous sites.

**Comment by tpperlman** [comment]
Insights are enabled, and this is what we see as we toggle some settings. If there is somewhere else you want us to look, we can.. but happy to provide access to you as a host user if it will help diagnose.

![Screenshot 2022-05-25 124725](https://user-images.githubusercontent.com/1871915/170317563-24964df8-6f60-450d-aa56-3d04e3cc8c89.jpg)

**Comment by tpperlman** [comment]
Single feature toggle in insights shows this:

![Screenshot 2022-05-25 125326](https://user-images.githubusercontent.com/1871915/170318462-81157e85-0731-45cc-b245-1a1d3d942a48.jpg)

**Comment by tvatavuk** [comment]
I reproduced this issue in local 2sxc dev env. Until is fixed, there should be simple workaround.
@tpperlman please can You test the following in you installation?
1. download [features.zip](https://github.com/2sic/2sxc/files/8777869/features.zip) and unzip `features.json`.
1. copy this `features.json` to your `DesktopModules\ToSIC_SexyContent\.data-custom\configurations\` folder, so you will have 2 files there.
![image](https://user-images.githubusercontent.com/2724850/170458919-acdef4a4-ec6b-4ea2-ac1c-3e7d9c1afda0.png)
1. test

**Comment by iJungleboy** [comment]
@tvatavuk if this is a bug in the LTS, we need to release a 13.12.01. could you apply the fix to that branch too? versions/13 or something

**Comment by tvatavuk** [comment]
> @tvatavuk if this is a bug in the LTS, we need to release a 13.12.01. could you apply the fix to that branch too? versions/13 or something

[fix ](https://github.com/2sic/eav-server/commit/40e165d20eb185025ce68beb47b48bfb3beb01ed) is also added and tested in branch `version/13` (in code for v13 LTS).

**Comment by tpperlman** [comment]
@tvatavuk than you! The features.json file worked and the settings persisted after app restarts. 

Should we change the fingerprint to match the server's registration?

**Comment by tvatavuk** [comment]
> @tvatavuk than you! The features.json file worked and the settings persisted after app restarts.
> 
> Should we change the fingerprint to match the server's registration?

Thx. You are good. It is not required to update fingerprint in features.json.
Btw in next v13 LTS, after change of configuration, fingerprint will be auto updated to correct one, so no need for You to do it manually at this moment.
