### ISSUE TITLE
Improve Edit-Content on Skin-Rendered Modules

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#2762]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 
[x] feature request

**...about**   
[x] Razor templating

**Current behavior**   

Developers can add modules to a theme/skin. But in some cases editing fails, because the page-id and module-id don't match the real module. Goal is to ensure this is passed through, so that the page-id isn't the one we are looking at, but the one which has the original module. 

I believe @ajplopez requested this once as well. 

**Your environment**  

* **2sxc version(s):** 14.00

**Comment by ajplopez** [comment]
Yes, precisely.

**Comment by iJungleboy** [comment]
it will work in 14.01 ;)
