### ISSUE TITLE
2sxc JavaScript demo - documentation error and/or 2sxc bug

### ISSUE THREAD

**Issue by skarpik** [2sic/2sxc#2783]
**I'm submitting a ...** 
[x] bug report
[x] not sure

**...about** 
[x] Razor templating
[x] JS development

**Current behavior**  

Working through the JavaScript demo "Get Data from the Backend using JS":

https://2sxc.org/dnn-tutorials/en/razor/js200/page

I found that the code works if logged in as an Admin but fails if you are not logged in (2sxc not found). 

I did find the solution:

https://github.com/2sic/2sxc/issues/1347

which works fine. However, some people may encounter this situation and do not know about Issue 1347 and consequently, they may assume that 2sxc is broken.

**Expected behavior** 

The demo code should work as published for all users - Admin or not.

**Instructions to Reproduce the Problem**

Create DNN test site and app to implement the demo code ("Get Data from the Backend using JS"). Tested as both Admin and anonymous users.

**Why change the behavior?**  

The demo code should work for both Admin and anonymous users otherwise people may think there is a problem with 2sxc. 

Suggested fixes:

1. Change how 2sxc works (this might be hard and may not be necessary)
2. Make a small edit to the demo to instruct people to add the code:

`<script src="/desktopmodules/tosic_sexycontent/js/2sxc.api.min.js"></script>`

**Your environment** 

Local IIS installation on Windows 11

* **2sxc version(s):** 14.01
* **Browser:** all
* **DNN:** 9.10.2
* **Language:** English (did not test for other languages)

**Anything you would like to add**

This issue is not really a bug but some people might perceive it as one.

**Comment by maaaximum-at-2sic** [comment]
@skarpik Thank you for reporting this :smile:. This issue has been fixed and will be published with the next release.

The current best practice for adding 2sxc JS APIs is to activate them through the PageService.
See this example:

```
@using ToSic.Sxc.Services;

@{
  // Tell the page that we need the 2sxc Js APIs
  GetService<IPageService>().Activate("2sxc.JsCore"); 
}
```
