### ISSUE TITLE
Online Code Editor Nonfunctional

### ISSUE THREAD

**Issue by jtherrien-accuraty** [2sic/2sxc#2790]
I'm submitting a ...
[x] bug report

...about
[x] edit experience / UI
[x] DNN parts
[x] other / unknown

Current behavior
When you use the tag toolbar or the view admin panel to open the online code editor for a view file the page just pops up an alert saying an error has occurred:
![chrome_EfF5qAPwyT](https://user-images.githubusercontent.com/62106757/174169120-29826179-0d76-4b72-935b-c4bdc99f381c.png)

Expected behavior
Opening the online code editor through the tag toolbar or view admin panel should work.

Instructions to Reproduce the Problem
Upgrade a site with DNN 9.10.02 and 2sxc 14.01.x or 13.12.1LTS to 2sxc v14.02.00 and the problem is immediate.

Your environment

2sxc version(s): 14.02.00
Browser: all/any
DNN: only tested on 9.10.2

**Comment by iJungleboy** [comment]
Thx for finding this. Already fixed, will be in 14.03 to be release ca. tuesday, when we also fix #2789
