### ISSUE TITLE
Clash with Plant an app

### ISSUE THREAD

**Issue by Tychodewaard** [2sic/2sxc#2798]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] other / unknown

**Current behavior**   
I can install 2SXC on DNN. I can install Plant an app on DNN. But I can not install Plant an app when there is already 2SXC installed. And I can not install 2SXC when Plant an app is already installed.

![image](https://user-images.githubusercontent.com/9091997/175511176-45c1517e-08af-4808-ba53-fce0332e9adf.png)

**Expected behavior**   
In an ideal world, the install won't crash.

**Instructions to Reproduce the Problem**
install 2sxc and the app builder of plant an app.

I already submitted the bug/issue to Plant an app as well.

**Comment by iJungleboy** [comment]
Hi @Tychodewaard 

Someone already reported something similar and it appears we made a mistake in the installers from ca. v13.4 to 14.1. It's fixed in v14.2. 

See also #2782
