### ISSUE TITLE
Routing loads list page instead of details page when view's name in url path is "/.*".

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [2sic/2sxc#2816]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] other / unknown

**Current behavior**   
I'm talking about list-details website structure like one that is used in a 2sxc Blog app.
As specified [here](https://2sxc.org/en/docs/feature/feature/4680)

> you can also write Details/.* - this means that if the URL contains Details and another parameter of any value, it will also enable the Details view. 

So I've used `/.*` as a value for url key in a details page view so that url "https://domain.com/myrecords" would lead to a list of records, while url "https://domain.com/myrecords/record-url-key" would lead to a single record with a url key "record-url-key". It worked in version 12.10.0. But after update to version 14.7.3 it stoped working and url "https://domain.com/myrecords/record-url-key" also loads a page with a list of records.

**Expected behavior**   
When `/.*` is used as a value for url key in a details page view, then any additional parameter after slash in a url should lead to a details page instead of a page with a list of records.

**Instructions to Reproduce the Problem**

1. install 2sxc module and Blog4 app to your website to avoid manual creation of list-details logic
2. create at least one post of no posts after installation
3. go to settings of Blog4 app
4. go to views
5. click the view for details page
6. edit "Name in Url Path" to value "/.*"
7. save it
8. go to any blog post url but delete "details" part
9. it should open this post of your choice but instead it will load a list of posts

**Why change the behavior?**  
Because it's basic routing problem.

**Your environment**  
Windows 10
Visual Studio 2019 (& 2022)
DNN.Platform 9.10.2

* **2sxc version(s):** 14.7.3  
* **Browser:** [Chrome 103.0.5060.114 (Official Build) (64-bit)]
* **DNN:** [ 9.10.2 ] 
* **Language:** [English]

**Anything you would like to add**

**Comment by Constantine-Ketskalo** [comment]
I've already fixed it via C#, but thanks for a suggestion of rewrite.
So it's not urgent for me personally. But I would suggest that you consider this feature in future at all, because I've seen such urls at multiple websites and I think it's a very useful thing to have.

**Comment by iJungleboy** [comment]
We'll review this some time later. 

are two other feature that we must figure out first though: module-level parameters as well as only switching from certain views. so stay tuned ;)
