### ISSUE TITLE
Error in Image Gallery (2sxc v14.07.04)

### ISSUE THREAD

**Issue by skarpik** [2sic/2sxc#2817]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] other / unknown

**Current behavior**   
Setup new DNN v9.10.2 website to test 2sxc v14.07.04. Installed all Content modules and all Apps (except for People Directory V4.3Hybrid which threw a 500 error). On first use of Photo Gallery, I got this error message for a single gallery:

Error: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'ToSic.Sxc.Adam.File<int,int>' does not contain a definition for 'Toolb' at CallSite.Target(Closure , CallSite , Object ) at ASP._Page_Portals_0_2sxc_Gallery7_bs5__Album_cshtml.Execute() in d:\Websites\2sxc14en\Website\Portals\0\2sxc\Gallery7\bs5\_Album.cshtml:line 100 at System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) at ToSic.Sxc.Engines.RazorEngine.Render(TextWriter writer) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Engines\Razor\RazorEngine.cs:line 117 at ToSic.Sxc.Engines.RazorEngine.RenderTemplate() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Engines\Razor\RazorEngine.cs:line 125 at ToSic.Sxc.Engines.EngineBase.Render() in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Engines\EngineBase.cs:line 135 at ToSic.Sxc.Blocks.BlockBuilder.RenderInternal() in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Blocks\BlockBuilder_Render.cs:line 120

**Expected behavior**   

Should not have thrown this error.

**Instructions to Reproduce the Problem**

1) Create DNN v9.10.2 website.
2) Remove Telerik
3) Install 2Shine Bootstrap theme
4) Create a blank page. Install Content modules. Add 50% text, 50% image Content to page. All OK.
5) Create another blank page. Install all Apps. The first time I tried this, I got a 500 error for People Directory V4.3Hybrid. So I started over with a brand new website but this time unselected the People Directory. All seems OK.
6) Added a Gallery to the blank page, selected the Single Gallery option. Clicking the "checkmark" to confirm my choices, 2sxc runs into trouble. See screen capture.

![Screenshot 2022-07-08 012540](https://user-images.githubusercontent.com/3846223/177922962-3cb744c8-2abc-4ea6-85ac-b259384f94dd.jpg)

**Why change the behavior?**  

Cannot create a photo gallery with this bug in the way.

**Your environment**  

2sxc v14.07.04
DNN v9.10.2
Browser: MS Edge
Language: English (US)

**Anything you would like to add**

I don't know if the problem installing the People Directory is related to the bigger problem with the Gallery. I suspect it they are totally unrelated but I thought I had better mention the People Director problem just in case there is a connection.

**Comment by iJungleboy** [comment]
@getBlup

**Comment by getBlup** [comment]
@skarpik thank you for submitting the bug report. The issue with the Image Gallery is fixed in the release [07.03.01](https://github.com/2sic/app-gallery/releases/tag/v07.03.01).

While the issue with the people directory app was unrelated it is fixed now too.
