### ISSUE TITLE
Feature request - Optionally Store Visual Queries in JSON files.

### ISSUE THREAD

**Issue by reteid** [2sic/2sxc#2818]
**I'm submitting a ...**   
[x] feature request

**...about**   
[x] Content Types or data management

**Why change the behavior?**  

**Anything you would like to add**

It would be nice to have a toggle setting at application level . If enabled , the App stores the App's visual queries in separate JSON files within the App , like the API controller files.   eg. Portals/0/2sxc/App/Queries/query1.json

And when the Visual Query is altered, the JSON file automatically updates. 
Likewise, if the JSON file changes, the Visual Query imports the change.

So that when a dev makes a change to a Visual Query on his environment, then commits the change, the change can be stored in a repo and the other developers will get the change when they do a pull on the repo.

This will help with Continuous Integration

**Comment by iJungleboy** [comment]
Interesting idea, and I understand the need. 

We'll look into this. after summer ;)
