### ISSUE TITLE
Content Type / Content Items Permissions using Role Permissions

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#2819]
**I'm submitting a ...**
[x] bug report

**...about**
[x] Content Types or data management

**Current behavior**
Similar to issues #1023 and #2689, we're trying to add the content-items toolbar for users by role. We created a new role named "Content Admin", turned on the optional security by role features, and added a toolbar button like this:

```
<div class="propertiesContainer sc-element" @Edit.TagToolbar(Content, toolbar: new [] { 
	"new?contentType=Properties",
	"contentitems?contentType=Properties"
})>
```

We've set the permissions on the App, View and Content Type all to Full Control for testing purposes, but when a user in the role clicks the button a 401 error is returned for each of the following API calls:

```
https://somedomain.void/api/2sxc/admin/type/get?appId=6&contentTypeId=Properties
https://somedomain.void/api/2sxc/admin/entity/list?appId=6&contentType=Properties
https://somedomain.void/api/2sxc/admin/field/all?appId=6&staticName=Properties
```

We also tried adding permissions for the schema on the content type and the error persists. Thank you for looking into this!

**Expected behavior**

If the user has permissions on the content type, they ought to be able to view all content items.

* **2sxc version(s):** 14.7.4  
* **Browser:** all
* **DNN:** 09.10.02
* **Language:** all

**Comment by iJungleboy** [comment]
The content-type permissions are primarily meant for REST use or public editing of data by non-admins using the form. 

The admin-UI uses other endpoints and needs additional data to work, so this has never been implemented in this way. 
I'm also not sure that we could do this quickly, as it would open up new security risks on existing sites. 

I believe if you gave the user/group edit-permissions on the module this would already work. Is this an option?

**Comment by iJungleboy** [comment]
No input for a long time, so I'll close for now.
