### ISSUE TITLE
ADAM rename, delete files programmatically; custom validation of fields in form before saving values to ADAM

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [2sic/2sxc#2821]
**I'm submitting a ...**   
[x] feature request

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] JS development
[x] Content Types or data management

**Current behavior**   
Currently it's possible to upload files to ADAM with any name. But some characters like cyrillic and probably some other valid file name characters can cause problems. For instance such file can't be later downloaded from server via FTP. It might also cause some other problems I haven't stumble upon so far.
I could solve this either by custom validation before saving or by formula that calls api and renames file but ADAM doesn't have any method that would allow either delete or edit file programatically. Also 2sxc module doesn't have custom validation **before** saving value available. It's possible to add regex validation of file id/url to disable option of url insersion. But file name can't be validated in any possible way for now, except for extension filtering.

**Expected behavior**   
I suggest both features implemented since it would allow better customization of 2sxc module. Also there's another option that could solve this problem: custom list of valid characters for file names and all the invalid characters would be replaced by the character that customer chooses. I saw that in one of previous issues you've been solving a bug with "+" character renaming in file name which was causing some problems. So probably slight adjustment of that code could add solving of any characters in file names problems?

**Instructions to Reproduce the Problem**

1. Edit any entity with property of type link/file.
2. Upload file with cyrillic characters in the name.
3. Connect to your server via FileZilla.
4. Try to copy files (you can copy only adam folder to make things quicker).
5. All the files with cyrillic names will be skipped during copy process.

**Why change the behavior?**  
Customers can upload files with any possible characters in file names which cause some technical problems. Extentions filter is not enough.

**Your environment**  
Windows 10
Visual Studio 2019 & 2022

* **2sxc version(s):** 14.7.3  
* **Browser:** [Chrome Version 103.0.5060.114 (Official Build) (64-bit)]
* **DNN:** [9.10.02 ] 
* **Language:** [English]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Will close as it won't be on our priorities any time soon - unless someone contributes the code or sponsors the change.
