### ISSUE TITLE
2sxc- Adam image upload within 2sxc fails with a misleading error

### ISSUE THREAD

**Issue by cristel77** [2sic/2sxc#2827]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management

**Current behavior**   
I was trying to upload an image file using Adam within 2sxc, but the upload fails and display a misleading error. It shows that the upload fails because the file is too large than the maximum upload size even though it's not.

**Expected behavior**   
The image should be uploaded as the file is not larger than the maximum upload size. 

**Instructions to Reproduce the Problem**

1. In 2sxc, upload an image using Adam which is not larger than the upload maximum size.
2.  It will throws an error that upload failed because the file is too large and it's more than the upload maximum size.
![image](https://user-images.githubusercontent.com/106718937/182798904-ac7bb2cb-c15f-4950-89fe-9cef72bf9e5f.png)

**Why change the behavior?**  
1. The image should be uploaded as the file is not larger than the maximum upload size. 
2. Display the correct error message why the upload fails.

**Your environment**  

* **2sxc version(s):** 12.18.0  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** 08.04.02
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**

**Comment by tvatavuk** [comment]
Hi @cristel77, thx for reporting this issue.
I will close it because it is related to already known UI issue (better user notification in UI on ADAM file upload exceptions). 
It is expected to be fixed in future 2sxc versions.

**Comment by tvatavuk** [comment]
We are tracking this issue as https://github.com/2sic/2sxc/issues/2825.

**Comment by tvatavuk** [comment]
Hi @cristel77,
please take a look at https://github.com/2sic/2sxc/issues/2825#issuecomment-1216193662.
In case that web.config configuration had system.web/httpRuntime/@maxRequestLength >= 2097152 there was int overflow in our file size check. If this is also Your case, for v13.12.01 LTS (and v14.07.04 LTS) as workaround, it is best to set value maxRequestLength="2097151" as max.
