### ISSUE TITLE
2sxc doesn't work without an internet connection

### ISSUE THREAD

**Issue by ElBafo** [2sic/2sxc#2851]
**I'm submitting a ...** 
[x] support request
[x] not sure

**...about** 
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
We are using 2sxc for a secure site that doesn't have access to internet. We've managed to remove all references to outside sourceMapping but we've noticed that it doesn't work correctly. It seems the modules is loading angular scss from webpack and those are not loaded when we cut off the internet access. The result is that the content editors cannot work since the dialogs are not displayed correctly. We haven't passed this point yet to check if additional work is required to make this happen.

**Expected behavior**
Even without internet, there should be css loaded for the content editors

**Instructions to Reproduce the Problem**
Turn off your router, click to edit a 2sxc content in a localhost environment

**Why change the behavior?** 
I love 2sxc but most of my biggest clients do not allow internet access from the production environments. It would be nice if it worked.

**Your environment** 
Windows Server VM

* **2sxc version(s):** latest
* **Browser:** all
* **DNN:** 8.0.2
* **Language:** Greek | English

**Comment by iJungleboy** [comment]
Hi @ElBafo 

Just to clarify: does the server seem to need internet access, or the browser? 

We're not aware of any features requiring internet access, except for these:

1. The code editor uses VS Code (Monaco) which it loads from a CDN in the _browser_ - so the server doesn't need connection. If the browser doesn't have connection, you cannot edit source files online. 
2. Source maps for debugging - again loaded in the _browser_ and only relevant for debugging - shouldn't affect functionality
3. Automatic license activation would require access by the server - but that can be done manually 
4. In the App-Settings-Dialog it will usually load an iframe to tell the admin about the App, Upgrades and security issues - but without internet (on the _browser_) it will just show a blank iframe

I believe even tinyMCE is included, and icons in the UI are also in the source code. 

So I'm not aware of anything in 2sxc that comes from outside during normal use. To continue, I need you to:

1. find out what file is missing? I really cannot guess what could cause this
2. verify if it's server-internet-access that's the problem, or client (browser)

**Comment by ElBafo** [comment]
Hi @iJungleboy , had to schedule a meeting with their IT.

With regards to your questions:
- They are forbidding internet access from both server and browser
- We believe it's the webpack:\\ that doesn't load.

In the image below you can see both the error we are getting as also how the modal is not displaying correctly:
![Screenshot 2022-09-14 162448](https://user-images.githubusercontent.com/29287122/190166332-3f6c0c6b-ff06-4cb0-8474-78bcbd0320eb.jpg)

**Comment by iJungleboy** [comment]
My guess is that it's actually NOT the internet that's the problem. My guess is DNN is configured incorrectly, and because of this 2sxc is trying to get files (which would come from the local server) from the wrong domain. 

Can you get a screenshot of the F12 Network list with the red ones?

And possibly click on a red entry and also print-screen that?

**Comment by iJungleboy** [comment]
Great :) - let's call this closed then.
