### ISSUE TITLE
Not able to get a licence after registration

### ISSUE THREAD

**Issue by rockgobo** [2sic/2sxc#2855]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 
[x] not sure

**...about**   
[x] admin experience UI

**Current behavior**   
Try to follow the recipe for public forms https://2sxc.org/en/blog/post/recipe-create-public-forms-with-2sxc to enable the feature "public forms". I register the website using the button on the manage apps ui. On the patreon site the registration ends with the sentence "To import the license to 2sxc, press the import-license button in the features-tab". This button does not exist anymore or i can not find it. What I see is a button "retrieve licence" but this ends in a 500 error. 
I also downloaded the licence and copied it in "\DesktopModules\ToSIC_SexyContent\.data-custom\configurations" path. Still 500. 
I also renamed the file default.licence.json... still 500

I have the feeling that the API call /Retrieve tries to call the external patreon website, which is not allowed in our firewall. Does the webserve need access to the website. Or what is the idea to licence a website? 

**Expected behavior**   
Can use core plus features after copying the licence.json

**Instructions to Reproduce the Problem**

**Why change the behavior?**  
I want to register the website to use the core plus features.

**Your environment**  
Windows Server, Webserver is not allowed to make external HTTP requests

* **2sxc version(s):** 14.07.3  
* **Browser:** all 
* **DNN:** 9.6.1 
* **Language:** any/all

**Comment by iJungleboy** [comment]
So first: sorry you didn't have a positive, streamlined experience. We'll try to improve this. 

You are using 14.07.03 - the final LTS is 14.07.04. I'm not sure if we had to patch something here, but before spending any more time I recommend going that small step and upgrading. 

Second: we need to know what 500 error you're talking about. Is the patron-site returning a 500? or is it your site?

**Comment by rockgobo** [comment]
Thanks for the hind with the LTS version. I thought we are on the LTS version... which we will in a second. 

The 500 was from our server, because the button "retrive license" makes a api call back to the local server with the Route ..../Retrieve.

After waiting for a day the licence somehow appeared. I am now able to enable features like the public forms. 

The original Result looks like this:
![2sxc_licence](https://user-images.githubusercontent.com/3286890/191732862-b88fceee-2b03-4228-9aab-06ded8284297.png)
![2sxc_publicforms](https://user-images.githubusercontent.com/3286890/191732885-1cb237ce-2014-4458-bb6a-0d3c0fb59cf8.png)

I close the issue as you want to improve the workflow anyways. Thanks for the super fast feedback 👍
