### ISSUE TITLE
Scrollbar disable for edit fields on an item

### ISSUE THREAD

**Issue by ufoloko** [2sic/2sxc#2856]
**I'm submitting a ...**  
[x] bug report 

**...about** 
[x] edit experience / UI
[x] admin experience UI

**Current behavior**  

When you edit an item you open popup scrollbar is hidden for fields space. This is not a problem when you use a Mac, but in Windows, you dont have an option to scroll down between fields. I noticed class u-hide-scrollbar class is being used but this should be removed to avoid this problem

**Expected behavior** 

You should be able to see the scrollbar for any browser to allow scroll in fields.

**Comment by ufoloko** [comment]
This is the edit popup for chrome in windows 11, with an old 2sxc versión. You can see all the time the scrollbar at right
<img width="805" alt="image" src="https://user-images.githubusercontent.com/1165122/191825200-6dd6d252-0c17-48ef-9be4-a0a72d551d36.png">

And this is the edit popup for same chrome browser but for the most recent 2sxc version. The scrollbar is not present
<img width="805" alt="image" src="https://user-images.githubusercontent.com/1165122/191825628-1cad759e-9256-4651-9571-0e02d2fda9b8.png">

If you have a mouse with roller you can scroll around, but if you dont, you are not able to scroll down to see all the fields.

As a patch, I searched the class u-hide-scrollbar in 2sxc style asset and removed the display:none attribute, this allow me to show the scrollbar all the time and with that im able to scroll down using the scroll arrows or scroll track.

You don't have the issue on Mac computer, because you have to use gestures by default to scroll down or scroll up. So, is not a problem.

I hope to be more clear about the issue.

**Comment by iJungleboy** [comment]
So I think I understand what you describe. 

Why would you need a scrollbar? Everybody else uses the wheel or a touch-screen - which is also why all modern and mobile UIs don't show the scroolbar.

**Comment by iJungleboy** [comment]
as there has been no feedback and it's unclear if something should be done, I'll close this for now. feel free to add something and then I would reopen.
