### ISSUE TITLE
Can't load App or Content - Uncaught (in promise): m: {"headers":{"normalizedNames":{},"lazyUpdate":null}

### ISSUE THREAD

**Issue by 10poundgorilla** [2sic/2sxc#2858]
**I'm submitting a ...**   
[x] bug report 

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management
[x] APIs like REST
[x] DNN parts
[x] other / unknown

**Current behavior**   
Started in version 11.22. Not sure when it began but am getting this anywhere 2sxc lives on the website: 
Something went really wrong in view.ascx - check error logs

Try and add an app or content and you will get this error:

Failed to load resource: the server responded with a status of 400 (Bad Request) /api/2sxc/cms/block/App?appId=11:1 
vendor.cfc42572e9c3bc97.js:1 ERROR Error: Uncaught (in promise): m: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":400,"statusText":"Bad Request","url":"api/2sxc/cms/block/App?appId=11","ok":false,"name":"HttpErrorResponse","message":"Http failure response for api/2sxc/cms/block/App?appId=11: 400 Bad Request","error":{"Message":"Bad Request","ExceptionMessage":"Object reference not set to an instance of an object.","ExceptionType":"System.NullReferenceException","StackTrace":"   at DotNetNuke.Services.Tokens.BaseCustomTokenReplace.ReplaceTokens(String sourceText)\r\n   at DotNetNuke.Services.Tokens.TokenReplace.ReplaceTokens(String sourceText)\r\n   at ToSic.Sxc.Dnn.LookUp.DnnTokenReplace..ctor(Int32 instanceId, PortalSettings ps, UserInfo userInfo) in C:\\Projects\\2sxc\\2sxc\\Src\\Dnn\\ToSic.Sxc.Dnn.Core\\Dnn\\LookUp\\TokenReplaceDnn.cs:line 24\r\n   at ToSic.Sxc.Dnn.LookUp.DnnLookUpEngineResolver.GenerateDnnBasedLookupEngine(PortalSettings portalSettings, Int32 moduleId) in C:\\Projects\\2sxc\\2sxc\\Src\\Dnn\\ToSic.Sxc.Dnn.Core\\Dnn\\LookUp\\DnnLookUpEngineResolver.cs:line 46\r\n   at ToSic.Sxc.Dnn.LookUp.DnnLookUpEngineResolver.GetLookUpEngine(Int32 moduleId) in C:\\Projects\\2sxc\\2sxc\\Src\\Dnn\\ToSic.Sxc.Dnn.Core\\Dnn\\LookUp\\DnnLookUpEngineResolver.cs:line 34\r\n   at ToSic.Eav.DataSources.DataSourceFactory.GetPublishing(IAppIdentity app, Boolean showDrafts, ILookUpEngine configProvider)\r\n   at ToSic.Eav.Apps.Parts.AppRuntimeBase`1.get_Data()\r\n   at ToSic.Sxc.Apps.ViewsRuntime.ViewsDataSource()\r\n   at ToSic.Sxc.Apps.ViewsRuntime.GetAll()\r\n   at ToSic.Sxc.Dnn.Run.DnnModuleUpdater.SetAppId(IModule instance, Nullable`1 appId) in C:\\Projects\\2sxc\\2sxc\\Src\\Dnn\\ToSic.Sxc.Dnn.Core\\Dnn\\Run\\DnnModuleUpdater.cs:line 65\r\n   at ToSic.Sxc.Blocks.Edit.BlockEditorForModule.SetAppId(Nullable`1 appId)\r\n   at ToSic.Sxc.WebApi.InPage.AppViewPickerBackend.SetAppId(Nullable`1 appId)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()"}}
    at ee (polyfills.117ea2657fbac8c5.js:1:17523)
    at ee (polyfills.117ea2657fbac8c5.js:1:17042)
    at polyfills.117ea2657fbac8c5.js:1:18383
    at D.value (polyfills.117ea2657fbac8c5.js:1:8153)
    at Object.onInvokeTask (vendor.cfc42572e9c3bc97.js:1:278167)
    at D.value (polyfills.117ea2657fbac8c5.js:1:8074)
    at I.value (polyfills.117ea2657fbac8c5.js:1:2332)
    at O (polyfills.117ea2657fbac8c5.js:1:10467)
    at D.value [as invoke] (polyfills.117ea2657fbac8c5.js:1:10136)
    at N (polyfills.117ea2657fbac8c5.js:1:22337)

In admin logs the error is this:

Message:Error - can't find 2sxc instance configuration. Probably trying to show an app or content that has been deleted. Or you may have EnterpriseCMS features enabled but are missing the license activation.

StackTrace:

InnerMessage:Error - can't find 2sxc instance configuration. Probably trying to show an app or content that has been deleted. Or you may have EnterpriseCMS features enabled but are missing the license activation.

InnerStackTrace:

   at ToSic.Sxc.Dnn.Install.DnnReadyCheckTurbo.EnsureSiteAndAppFoldersAreReadyInternal(IBlock block, Lazy`1 appFolderInitializerLazy) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\Install\DnnReadyCheckTurbo.cs:line 54
   at ToSic.Sxc.Dnn.Install.DnnReadyCheckTurbo.EnsureSiteAndAppFoldersAreReady(PortalModuleBase module, IBlock block, Lazy`1 appFolderInitializerLazy, ILog log) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\Install\DnnReadyCheckTurbo.cs:line 34
   at ToSic.Sxc.Dnn.View.<>c__DisplayClass13_0.<Page_Load>b__1() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\View.ascx.cs:line 80
   at ToSic.Sxc.Dnn.View.TryCatchAndLogToDnn(Action action, LogCall timerWrap) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\View.ascx.Errors.cs:line 22

**Expected behavior**   

Load the 2sxc without an error. 

**Instructions to Reproduce the Problem**

Found similar issue reported for DNN 9.10 and installed the pre-release 14.07.05 added to that now closed bug. 

**Why change the behavior?**  

**Your environment**  

* **2sxc version(s):** 14.07.05  
* **Browser:** [all ]
* **DNN:** [9.10.1 ] - upgraded to 9.10.2 same problem. 
* **Language:** [any/all ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
I cannot guess anything at the moment. 

It seems to fail at the token replace, but I'm not sure. Can you tell me more?

1. Is this a razor or token template?
2. Does it happen consistently or randomly?
3. Only on one specific app, or everythere?
4. Is it something special - like a view which uses a query?

**Comment by 10poundgorilla** [comment]
1. Not sure - it is all default apps and content installed I believe around v2 for most of them
2. Happens on every app which does load the choices to select, and content you can't even get it to load the content types, error occurs instantly on trying to select 2sxc content module to add to page - before you can choose a view
3. All apps / content
4. Nothing special - all default apps but I don't know if they were modified at some point when originally built but were default apps initially at least and some certainly have never been modified and still error occurs. You can't even get to manage apps. 

Not much help likely. Was hoping that error meant something to you.

**Comment by iJungleboy** [comment]
@10poundgorilla so this only happens on freshly added modules, not on existing? or on both?

Note that I have a feeling that something is wrong in the JS call which adds the module. Does this happen when adding with quickE, adding using the slow edit-page-add-module, or both?

My guess is something is wrong with the request which asks for saving the module. Could you compare the JS request which tries to save the module/app which was selected with such that are successful?

**Comment by 10poundgorilla** [comment]
All existing 2sxc modules show "Something went really wrong in view.ascx - check error logs" and I did a video to show you when trying to add a new app or content module. App at least pulls up list of apps, Content doesn't even pull up any Content Types / Views to select. We've tried default theme Xillion, removed all other modules form the page. I wish I could say I knew when this occurred has the site was upgraded to 9.10.1 almost a year ago and don't know if this has been like this for that long and no one noticed or if it was recent. 

https://www.loom.com/share/28488008c7524361b535e73d398336d1

**Comment by iJungleboy** [comment]
It seems to be a DNN internal issue. 

After closer review of the logs it actually fails inside DNN when DNN is trying to apply token replace on the site. 

Object reference not set to an instance of an object.","ExceptionType":"System.NullReferenceException","StackTrace":" at DotNetNuke.Services.Tokens.BaseCustomTokenReplace.ReplaceTokens(String sourceText)\r\n at DotNetNuke.Services.Tokens.TokenReplace.ReplaceTokens(String sourceText)\r\n at ToSic.Sxc.Dnn.LookUp.DnnTokenReplace..ctor(Int32 instanceId, PortalSettings ps, UserInfo userInfo) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\LookUp\TokenReplaceDnn.cs:line 24\r\n at

So our TokenReplaceDnn hands off to DNN to get tokens, and then it fails inside DNN. That's completely out of the control of 2sxc, DNN is stuck on something. 

My guesses are

1. DNN isn't configured correctly
2. You have something adding / overriding the token replace (maybe MyTokens or something) which might have been uninstalled or something. 

Just a guess, but almost certainly not a 2sxc issue. 

I'll close this for now, but if you have more findings which indicate 2sxc could still be responsible, I'll reopen.
