### ISSUE TITLE
Could not import the app / package: this app requires eav/2sxc version 14.09.00, installed is 14.8.0

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2859]
**I'm submitting a ...**  
[x] bug report 

**...about**
[x] admin experience UI

**Current behavior** 
When installing any app from the 2sxc catalog, I get the message:
Could not import the app / package: this app requires eav/2sxc version 14.09.00, installed is 14.8.0. cannot continue. see also 2sxc.org/en/help?tag=app

**Your environment**

* **2sxc version(s):** 14.8
* **Browser:** [ all ]
* **DNN:** [ 9.10.2 ] 
* **Language:** [ English ]

**Comment by iJungleboy** [comment]
Hi @eXistenZe 

We did make some changes to the format for 14.09. But to fix this, I need to know which app, and where you got it. was it from auto-installer or download?

**Comment by eXistenZe** [comment]
Downloaded from the 2sxc apps website. First two apps I tried. Blog and faq.

**Comment by iJungleboy** [comment]
Reason is this: https://docs.2sxc.org/abyss/releases/history/v14/change-in-app-zip-package.html

We'll improve the UI in the app catalog to make it easier for people to figure out. But for now, please just scroll down, there you can see the list of previous releases, incl. the one which is the compatible one with pre 14.09

**Comment by iJungleboy** [comment]
![image](https://user-images.githubusercontent.com/5321186/192207634-002a9553-12ae-43c4-be29-c1c38e22d066.png)

@ropalko 

Problem is that the default download will only work in the latest version (which isn't even released yet).

1. Pls change "Download App" label to "Download latest"
2. For now, please add a button "Other releases" which jumps down to the list of versions.

**Comment by eXistenZe** [comment]
Would't it be easier to release 14.09?

**Comment by iJungleboy** [comment]
we need to do both of course ;)

**Comment by iJungleboy** [comment]
v14.09 also release now, we can close this.
