### ISSUE TITLE
Something wrong with the fields to configure Value Filter

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#286]
For some reason, some dialogs have 3 fields (on systems that were upgraded), some 2 - the problem is that 
![image](https://cloud.githubusercontent.com/assets/5321186/8425280/77cadad8-1f04-11e5-968e-1ea98b3874fe.png)
![image](https://cloud.githubusercontent.com/assets/5321186/8425301/a8bca98c-1f04-11e5-87eb-d043a557afdd.png)

AttributeHelperTools apparently is the right field to write the field name in (which should be "Attribute"). Pls find out how this went wrong, and make sure it doesn't

**Comment by raphael-m** [comment]
In the EAV upgrade code, I can see that the field `AttributeHelperTools` is created. But nowhere in the code a field `Attribute` is created. Could it be that the third field only exists on our sites (like 2sxc.org and dev installations)?

**Comment by raphael-m** [comment]
7.2.2 solves this issue by
- Removing duplicate attribute (if both `AttributeHelperTools` and `Attribute` exists, `Attribute` will be removed)
- Renaming the `AttributeHelperTools` back to `Attribute`
- The ValueFilter uses `Attribute` now
