### ISSUE TITLE
Permissions Issues On Sub-Portal

### ISSUE THREAD

**Issue by michaelcunningham1974** [2sic/2sxc#2862]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**   
Have a primary site and a subsite. 2SXC runs fine on primary, on secondary site 2SXC displays properly to end user but throws a 403 error trying to access the API https://www.primary.com/SUBSITE/api/2sxc/cms/edit/load?appId=12 and user is immediately logged out.

The same happens if the user adds a 2sxc module to the page.

2SXC functions normally for SuperUsers AND for users that have accounts on both sites.

**Expected behavior**   

2SXC should operation normally for subsite editors and admins.

**Instructions to Reproduce the Problem**

**Why change the behavior?**  

**Your environment**  

* **2sxc version(s):** 14.7.4 
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX 
* **DNN:** [ 9.10.2 ] 
* **Language:** [English]

**Anything you would like to add**
Thanks!

**Comment by iJungleboy** [comment]
I believe this was fixed in 14.08.

Pls try. If it's still there, I'll reopen the issue.

**Comment by michaelcunningham1974** [comment]
Confirmed,  issues was resolved with 14.08 Thx.
