### ISSUE TITLE
Bug Report: Creating List items create more than one item.

### ISSUE THREAD

**Issue by haydentomas** [2sic/2sxc#2869]
I am submitting a bug report about admin experience relating to 2SXC and any list-type app.

This bug is present in the 2SXC content apps that are included with 2SXC and our own custom apps.

[x] edit experience / UI
[x] admin experience UI
[x] Razor templating
[x] Content Types or data management

**Current behavior**   

When you use a list app, pressing the + button to create a new item, will create 2 items instead of 1. This means you need to delete the 2nd item each time. I have attached a screencast to this post

**Expected behavior** 

Only 1 item should be created, not 2. Else we have to keep deleting the 2nd item every time we add an item, which is not a great UX.

**Why change the behavior?** 
It is not the expected behavior, if you click add, you want 1 item! (Sorry, this is my first time completing this form!)

Microsoft Azure
2SXC 14.7.3
9.10.2
All browsers

https://user-images.githubusercontent.com/108055327/194507728-281c031f-33ed-45ae-b9b0-227754cf5a09.mp4

**Comment by iJungleboy** [comment]
@haydentomas I believe we already fixed this. It's either already in 14.08 or then in the soon to be release 14.09

**Comment by haydentomas** [comment]
Much appreciated! Its not in 14.08 so I look forward to the next release!

**Comment by haydentomas** [comment]
Just want to add to this hopefully it will help!

The issue with extra list items appearing does not happen if the list contains only strings. It appears to happen if the list item contains an image. I have 2 lists type apps that work perfectly and contain only text strings. I hope that makes sense :)
