### ISSUE TITLE
Option to disable formulas when editing a field

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2875]
**I'm submitting a ...**  
[x] feature request

**...about** 
[x] admin experience UI
[x] JS development
[x] Content Types or data management

**Current behavior**  
I use many fields with formulas to create stuff when I create or edit a record using the 2sxc ui.
Things such as current date, calculated fields, new guids, etc.

**Expected behavior**
I know I can add a simple line of code to the formula to run only if the value is empty or similar checks, but they have other undesirable effects.
There could be a shortcut somewhere (shift + click on the data lista or something) to prevent the formulas from running at all.

**Comment by iJungleboy** [comment]
I don't think we can add this by default, as it would allow normal users to circumvent formulas, which should be solid. 

So if the developer has a formula, he should never expect users to be able to go around it. 

For your use case I suggest you add a rule that if debug-mode don't run formula or something, so you as a developer can do this. 

Normal users can't enter dev-mode, so it's safe.

**Comment by eXistenZe** [comment]
How would I perform that check? Something related to context debug?

**Comment by iJungleboy** [comment]
yes, but you would have to look at the F12 to see the values you get there. probably debug==true or something.
