### ISSUE TITLE
Add username to context.user

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2877]
**I'm submitting a ...** 
[x] feature request

**...about**
[x] JS development
[x] Content Types or data management
[x] APIs like REST

**Current behavior** 
In formulas, we are still lacking a simple way to get the user name.

**Expected behavior**
Add a context.user.username

**Comment by iJungleboy** [comment]
I extended it to add even more values https://github.com/2sic/2sxc/issues/2882

**Comment by iJungleboy** [comment]
will be in 14.09
