### ISSUE TITLE
When you add an image through adam in the content templates, resizing creates a blank image

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2903]
**I'm submitting a ...**
[x] bug report 

**...about** 
[x] edit experience / UI

**Current behavior** 
I add a content to a page (image/text), edit the content, add an image.
When viewing the page, the image shows blank (white).
When I click the image it animates into the proper image.

2sxc creates this link for the image:
/Portals/0/adam/Content/Mpky4rMWdUeGKjtnlyKbeg/Image/image.png?w=700&h=432&quality=75&mode=crop&scale=both

If I remove "&scale=both" the image will load, so something is not working for image cropping.

![image](https://user-images.githubusercontent.com/26518879/196801280-78213ffa-af26-4abf-be9b-6856662085ff.png)

**Your environment**

* **2sxc version(s):** 14.10

**Comment by iJungleboy** [comment]
We are not aware of a problem as of now.
Does this happen with many images, or just one specific one?

**Comment by eXistenZe** [comment]
A few notes on this after some reseach in several sites:
1. The content module is not the same in all sites, even if the 2sxc version is the latest in all. In one site I have old code, with no fancybox enabled and no &mode=crop&scale=both on the links. On another I have a newer version with @inherits Custom.Hybrid.Razor14, fancybox and polymorph. And it loads the crop options.
2. In this same site (the newer version), if I try to delete an image in the adam manager I get the error at the bottom.
3. After reuploading the image, it works fine now. Perhaps some server issue was corrupting the images in the day I reported.

Perhaps this issue can be closed for now and a new one created for this (when I try to delete images in adam):

ERROR TypeError: Cannot read properties of undefined (reading 'toString')
    at S.deleteItem (adam.service.ts:53:21)
    at i.del (adam-browser.component.ts:151:22)
    at adam-browser.component.html:111:66
    at Uh (core.mjs:15014:16)
    at o (core.mjs:15058:22)
    at HTMLElement.<anonymous> (platform-browser.mjs:466:38)
    at T.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:25574:33)
    at T.invokeTask (zone.js:405:60)
    at I.runTask (zone.js:178:47)

**Comment by iJungleboy** [comment]
note that this shows a JS error - which must be in the UI. 

I believe it's because the file didn't exist, so I don't think this is a real issue. I'll close for now.
