### ISSUE TITLE
In the Query Editor, no longer able to Drag a New Out-Connection from Source/App

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2906]
**I'm submitting a ...**
[x] bug report 

**...about** 
[x] edit experience / UI

**Current behavior**   
If you add a Source/App to the Query, you can no longer "Drag an Out-Connection" from the up-chevron in the upper right of object. The little orange up triangle appears on hover, but instead of dragging out a connector, it just moves the whole object instead.

Video demo
https://accuraty-my.sharepoint.com/:v:/p/jfarrance/ESkHbqEpCUFPheL_agE_UvoB03dZzZCN3SlNvXClciA6rA?e=fTn89n
 
Also note that on hover, there is a "ghost-box" visible that is probably a clue, something in the wrong place?
![image](https://user-images.githubusercontent.com/653301/197782399-d3d27b7a-7d57-4d62-aa17-f271cda068d2.png)

**Expected behavior**   
It should work the way it always has, hover and grab the triangle, then drag out a connector.

**Instructions to Reproduce the Problem**
Go to App admin, Queries tab, create a new Query, give it a name, save
Click to Edit (new tab/ui), 
Note that on the _CMS Block you can_ drag-out new connections
Switch to Add/Sources, the click App 
Hover in the upper-right area, triangle appears, but doesn't work as expected

**Your environment**  
* **Win Server 2019**, etc.
* **2sxc version(s):** 14.10.0 
* **Browser:** all
* **DNN:** 9.10.02 
* **Language:** any/all

**Anything you would like to add**

This was a 2sxc upgrade from v13.12.1 LTS directly to v14.10.0.

**Comment by iJungleboy** [comment]
@jeremy-farrance thanks, this is important. probably related to our changes with icons...

**Comment by iJungleboy** [comment]
found and fixed, will be in 14.11
