### ISSUE TITLE
Formulas improvements.

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [2sic/2sxc#2913]
**I'm submitting a ...**   
[x] feature request

**...about**   
[x] edit experience / UI
[x] admin experience UI
[x] JS development
[x] Content Types or data management
[x] APIs like REST

**Current behavior**   
Currently there is no way to request 2sxc api from a formula and wait for the request to finish and disable saving form while request is in progress.
Here is an example of situation where it was needed:
user can upload an image using any characters, including cyrillic, for instance. But it causes issues on the website so I need programmatic file name normalization (transliteration + special characters replacement).
Also I needed to make minified version of an image on upload. Reason is that I need minified version of an image for metadata (social networks and messengers). Minification via url parameters is not working good as some messengers/social networks can't display image if its url has query string parameters. So we've decided to do that programmatically one time on file upload and generate url to that minified file without any parameters.

And here's the real problem:
since I can't manage file before it's sent to server I need to send request to a custom 2sxc api to make minification there. But formula's js function doesn't wait for that method to finish. It just returns new value, form makes request to back, updates preview and url and then request to back is finished. And I can't use promises here since js function can't be async here. As result I have to make request to a custom 2sxc api and then inside `then` function I have to make a selection of that image property on the page and update preview image path and url image path manually, because 2sxc module has already generated those and after that I've been editing file name on the backend.

Selecting text field is also very tricky: context.target.Name contains property name, but page contains only display label for that property, so it's either hardcoded label text in some constant for input type text with "file:1234" data, or it's request to back that sends property name and back code gets label from `entity.Type[requestData.TargetPropertyName]` and then `attribute.Metadata.GetBestValue<string>("Name")` but this one requires entity object, so it won't work if there are no entities created yet.

Besides in this case with an image minification original image is only renamed to a proper name without file changes. And minified image is saved with a default suffix in the name at the same directory. But since all this is happening after 2sxc have already updated data on file upload, it doesn't display that minified image in the list of files under that property until form is reloaded.

Also I have an issue to disable saving form while request to back is in progress. I've been disabling save button during that time but firstly, it's selection is a quest itself. Secondly it's not a good solution since Ctrl+S and closing form plus clicking "Save changes" in a prompt window are still working because 2sxc module has no idea about formula js still doing something.

**Expected behavior**   
I suggest that you implement possibility to use promises inside formulas for a better customization (or even better if you'd provide some simple method that would await for 2sxc api request to finish, that would implement a promise already) and also give possibility to access any property on the page within the formula js code, update its value, trigger its update (e.g. trigger iframe window to update preview, url and list of images in the folder for particular property) and temporarily disable some property and saving form in general while request to server is in progress.

Currently the only way to disable saving form properly that I see is to make target property required, disable it via js in a formula code, empty it, do whatever's needed and then in order to enable editing this property and saving form, to write value back to property and enable that input. But it's quite a crutchy solution...

If there was also some animation of a loader on top of disabled and grayed out property that is being worked on - that would be really perfect and visually understandble.

Separate customizable file names normalization on upload and edit would be also really helpful, since any non-ascii characters could cause problems on many websites. This could be implemented for properties of type file/reference. But what I've described above could already give developers possibility to do that on their own and actually even much more.

I know that it would cause some delays in work of editing form but it's still faster and more reliable then manual images editing.

**Instructions to Reproduce the Problem**

- create formula for your property of type file/reference
- make a custom 2sxc api request inside your formula's code
- see that a code doesn't wait for api request to finish and promises are not available to be used here
- try to select your target property input inside then functioni after 2sxc api request - quite a challenge, no provided way to do that
- try to disable both input and save form functionality before sending that request - another challenge that has no functionality
- update uploaded image file name in your backend code during your custom 2sxc api request
- see that file preview and url are not updated so image is not displayed any more since it doesn't exists at that old path any more
- also create another image file at the same directory where this property's files are stored inside your api controller during request to your custom 2sxc api
- click image preview to open another modal with the list of all files binded with this property (since they are in the same folder)
- see that your newly created file is not here since form was not updated after your api request has finished

**Why change the behavior?**  
These changes could really unlish the potential of 2sxc formulas. Currently their possibilities are still very limited.

**Your environment**  

* **2sxc version(s):** 14.7.3
* **Browser:** [ Chrome Version 107.0.5304.88 (Official Build) (64-bit) ]
* **DNN:** [ 9.10.02 ] 
* **Language:** [ English ]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
You may be in luck - at least the wait-to-finish-formula is covered. I'm not 100% sure if it cover everything, but let's start with what's possible...

What's important to know is that formulas must run on every form change, and since a formula could modify a field - which would need another formula to run, they sometimes run a few times until the result "settles down". As such, they are currently not able to be async, as that would introduce a big complexity of handling async events as well. 

BUT: we have an API to re-trigger formulas after data has returned, using `context.form.runFormulas()` - see https://docs.2sxc.org/js-code/edit-form/formulas/context.html

**Comment by Constantine-Ketskalo** [comment]
Wow. Thanks a lot. Didn't know that.

**Comment by iJungleboy** [comment]
I hope this solves everything for you, so I'll close this issue now ;)
