### ISSUE TITLE
Setting app icon / template icon via content type and template settings respectively has no effect

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2926]
**I'm submitting a ...**   
[x] bug report 

**...about**   
[x] admin experience UI

**Current behavior**  

If you try to set an app icon or template icon (used in the app chooser toaster tiles) via their respective settings dialogs, it doesn't update the tiles in the chooser. It seems the only way to get app-icon.png and _template.png icons to work is to upload them directly to the folder.

**Expected behavior**

Admin users should be able to drag and drop app-icon.png and _template-name.png directly to the edit modals to set the preview tile image.

**Instructions to Reproduce the Problem**
For app-icon, go to a content type and click it's edit pencil. Under "More Settings like Icon, Notes, etc" add an icon.

For template icon, go to Views > View Configuration of a template, and toggle "Use Custom Icon" and drag and drop an icon here.

**Why change the behavior?**  

Seems like a bug or its misconfigured. If it's working in some ways but needs a certain naming scheme, that should be updated in the help text.

**Your environment**

* **2sxc version(s):** 14.0X.X 
* **Browser:** [all ]
* **DNN:** [all  ] 
* **Language:** [any/all ]

**Anything you would like to add**
Jeremy tested this in the latest version and it is still a problem.

**Comment by iJungleboy** [comment]
The appicon.png is a convention, that cannot be changed as of now. I believe there's also no place in the UI to change this. 

The template/view should be configurable...let me check...

**Comment by jeremy-farrance** [comment]
I just tried it on 2sxc v14.12.00 (just upgraded) and I was not able to set the Icon for the View via the UI.
![image](https://user-images.githubusercontent.com/653301/201191168-07239319-f747-4a19-a8d0-8a6e2a955708.png)

**Comment by ajplopez** [comment]
What is this Icon for?
![Screenshot 2022-11-10 at 1 32 23 PM](https://user-images.githubusercontent.com/8751936/201210288-f1019c9a-b822-442a-bc13-08219994a3b7.png)

**Comment by iJungleboy** [comment]
@ajplopez On one hand drop should work...I will look into it. 

But I actually urge you to use `[App:Path]/somepath/file.png` instead because that way the file remains in the app folder and is included on export import. See also https://docs.2sxc.org/basics/app/icons.html

**Comment by ajplopez** [comment]
Ah ok! Will do.

**Comment by iJungleboy** [comment]
I found the cause and fixed it. 

I also added warnings and encouragements to the UI to push people in the right direction ;)
