### ISSUE TITLE
App ADAM shared folders (eg. for re-used images/packshots)

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#2941]
**I'm submitting a ...**
[x] feature request

**...about** 
[x] Content Types or data management
[x] other / unknown

**Current behavior**
ADAM only allows file upload to a folder specific for that entity.

**Expected behavior**
ADAM could be configured to use app level files (files shared between all entities on an app).
A simple toggle would do the trick (entity files/app files).
In entity mode, adam will upload to appfolder/entityid/whatever
In app mode, adam will upload to appfolder/
As a bonus, new folders within the app folder could be created.

This would allow several entities to select the same files over and over.
I'm creating an app where I need sources for all fields. If I upload the same file for all the fields, I will end up with dozens of repeated uploads.

**Comment by iJungleboy** [comment]
Just to ensure we're talking about the same thing: I believe you would like to have one or more "shared" folders in the ADAM which you would use on certain fields. 

Eg. the field "Packshot" would not manage it's data by itself, but get it from `/adam/packshots` to ensure more reuse.

If this is what you would like I understand the need but it will take a few days of work to do well, so it won't be on our priorities. 

I have a guess though that even though you may have multiple fields my guess is they always go together. So you probably have a bundle of images such as `Packshot` and `Sample` which go together. In this case you may rather have an entity `SystemAssets` or something and reuse that.

**Comment by iJungleboy** [comment]
Will close as it won't be on our priorities any time soon - unless someone contributes the code or sponsors the change.
