### ISSUE TITLE
Metadata in adam files

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#2942]
**I'm submitting a ...** 
[x] feature request

**...about** 
[x] Content Types or data management

**Expected behavior** 
ADAM files could have metadata, such as alt text, labels or misc info.

**Comment by iJungleboy** [comment]
They actually do, but I do understand if this isn't super-easy to figure out. 
I'll have to review if we improve the APIs to make it easier, or just document more...

**Comment by iJungleboy** [comment]
this has been implemented ca. v17 with the new image stuff.
