### ISSUE TITLE
Empty Slot in Entity Picker

### ISSUE THREAD

**Issue by ropalko** [2sic/2sxc#2943]
**I'm submitting a ...**   
[x] bug report

**...about**   
[x] other / unknown

**Current behavior**   
The bug has been noticed in the Swiper. After initializing and adding a new image, the error appears. An "Empty Slot" element without data appears in the Entity Picker list.

**Instructions to Reproduce the Problem**
Here are some screenshot to reproduce the bug:
Initialize
![image](https://user-images.githubusercontent.com/921493/204212492-7608b78f-6411-41b5-918b-1204099bd3e7.png)
Add Element
![image](https://user-images.githubusercontent.com/921493/204212502-a06d2bfb-865c-4cf6-901d-39776ab60b36.png)
After Saving
![image](https://user-images.githubusercontent.com/921493/204212514-7af3c8f9-ba0c-4d97-a9c3-14c3bd5c3870.png)
Empty Slot in Entity Picker
![image](https://user-images.githubusercontent.com/921493/204212525-3bfe5e5c-d300-47ae-945b-dde245a280ad.png)

**Your environment**  

* **2sxc version(s):** 14.12.1
* **Browser:** all
* **DNN:** 9.6.1 
* **Language:** all

**Anything you would like to add**

**Comment by iJungleboy** [comment]
fixed ;)
