### ISSUE TITLE
Bug in image cropping for bilingual websites

### ISSUE THREAD

**Issue by skarpik** [2sic/2sxc#2951]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] Razor templating
[x] other / unknown

**Current behavior**   
In a bilingual website (en-ca and fr-ca with en-ca as the site default), it is not possible to set the image cropping for a Text | Image Content module independently for each language. The crop setting for the en-ca image is forced upon the fr-ca image.

**Expected behavior**   
As a for instance, I should be able to set "Default Crop" for then en-ca image and "Don't Crop" for the fr-ca. This is not possible.

**Instructions to Reproduce the Problem**

1. Create a generic DNN v9.11.00 website and install 2SXC v14.12.02 LTS.
2. Add a page to the English side of the website. To this page add a Text | Image module. Populate the Text | Image module with English text and an image. Using the Image properties, set a caption for the image.
3. Using the localization control panel, create the companion fr-ca webpage (copying all of the modules)
4. Go to the fr-ca page and set the Text | Image module to "Translate All". Then go to the Image properties and select "Translate All".
5. The image for the en-ca and fr-ca sides of the module will be left the same. We now can set a caption for the English and French versions of the image separately (for instance, "My beautiful image" and "Ma belle image"). However, I cannot choose different cropping for the English and French versions. Whatever I set for the English is pushed onto the side (so selecting, "Do not crop" on the English side automatically sets the cropping to that value on the French side).

**Why change the behavior?**  

It is almost always the case that French text is longer than its English equivalent. I would like to specify the "Default Crop" for the English and "Do not crop" for the French so that the respective image sizes and text lengths balance nicely for both languages.

**Your environment**  

OS: Windows 11 and Windows Server

* **2sxc version(s):** 14.12.02
* **Browser:** [all]
* **DNN:** [9.11.00] 
* **Language:** [Engish-French bilingual]

**Anything you would like to add**

If it would be helpful, I can test 2sxc v14.12.03 but I expect the behavior will be the same.

**Comment by iJungleboy** [comment]
Thanks for this and the detailed explanation. 
Just to be sure: I believe you mean the crop-settings on a _specific_ image, so hitting the small "target" button, correct? or could you include a print-screen of the setting you are referring to?

**Comment by skarpik** [comment]
Here is an example of the module with the "target" button that I press:

![Content Module (with button)](https://user-images.githubusercontent.com/3846223/205655784-3e752550-6348-4c51-a056-658d995d4fad.jpg)

This brings up the ImageDecorator control panel for this Text | Image module instance:

![Image Decorator](https://user-images.githubusercontent.com/3846223/205655974-a5c84c91-2100-4b02-9533-4c62bd698de4.jpg)

Both the French and English reference the same image. I can set the image caption to be different for English and French. However, the cropping for both is tied to the value selected for the English.

**Comment by iJungleboy** [comment]
Will be fixed in v15
