### ISSUE TITLE
Missing Material icons in admin 2SXC

### ISSUE THREAD

**Issue by haydentomas** [2sic/2sxc#2971]
**I'm submitting a ...
[x] bug report => search github for a similar issue before submitting 

**...about**  
[x] edit experience / UI
[x] admin experience UI

**Current behavior**   

There are missing icons in the editor, I believe they are the material icons

![image](https://user-images.githubusercontent.com/108055327/208132983-52e03646-a143-41d8-bafe-bf113e108215.png)

**Expected behavior**   icons!

**Instructions to Reproduce the Problem**

I am using the latest 2SXY and the 2shine theme

**Your environment**  

Azure

* **2sxc version(s):** 14.2.3
* **Browser:** all
* **DNN:** 9.11.0
* **Language:**

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Please check your F12 Network tab, it appears some requests to the font-files are failing. 
Please check and first check if you somehow disabled woff-files on your IIS, otherwise post a screenshot of the error in the console and network.

**Comment by haydentomas** [comment]
Thank you for helping with this, it got me to where I needed!

I had to enable woff2 in azure, inside teh cofig file I added the following

  <mimeMap fileExtension="woff" mimeType="application/font-woff" />
  <mimeMap fileExtension="woff2" mimeType="application/font-woff2" /> 

This is for anyone else that comes across this issie

**Comment by ajplopez** [comment]
I'm still having this issue in a non-Azure environment. I tried working with the hosting to include those mime types but that didn't make any difference. We tried restarting the application pool and clearing cache and incrementing CDF but it's still not working.

Is my best best to uninstall and go to an earlier version of 2sxc? If so, what version would work? Or is there another thing I could try?
