### ISSUE TITLE
Images will not display

### ISSUE THREAD

**Issue by cerullo** [2sic/2sxc#2977]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   

[x] other / unknown

**Current behavior**   
Images will not display in the content AND when editing words are overlaying each other and cant be read. I also can not change layouts without deleting the module from the page.

**Expected behavior**   
images display, no double words

**Your environment**  
14.12.3 with DNN 9.10.2

**Anything you would like to add**
![image](https://user-images.githubusercontent.com/49730999/209403432-f922feb2-8f8b-4c1c-ad15-09f24883a7ea.png)
![image](https://user-images.githubusercontent.com/49730999/209403464-9162309a-5df2-42e9-9996-f3c3b1800fdc.png)

**Comment by iJungleboy** [comment]
@cerullo I have a guess here, because your icons are not showing up either...

Could it be that you're running on azure, and that maybe `woff2` and `webp` are not allowed? See for eg. https://github.com/2sic/2sxc/issues/2971

**Comment by cerullo** [comment]
No I have my own servers it’s on. Yes I noticed the icons are not displaying too


Thanks,
Renee

 Integrated web design, digital marketing and technology solutions for the busy entrepreneur.
-----
Renee Cerullo
RLComputing is WBE Certified
President, RLComputing<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.rlcomputing.com%2F&data=04%7C01%7Cklaiken%40buffalo.edu%7Cd4afe08d49414af0c25c08d8adf7eec4%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637450628220607108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=boyhZPZ3jpBjSjXNJi10VZElquhSK7WxafeQN1Uf%2F4A%3D&reserved=0>
HELP DESK – ***@***.******@***.***>
Phone: 716.656.8958
Fax: 1.866.375.3393
Hours of Operation: Monday thru Friday 8am - 5pm EST

**Comment by cerullo** [comment]
Is there any suggestions here? None of my developers will touch this since they keep telling me the module is corrupt. We need to get this fixed so its usable. I fixed the images but the titles are all doubled up and I cannot change templates. I added w00f2 to the web config but that made no difference at all.

Uninstalling and re-installing made no difference at all. I can’t try a different version either. Lower versions says there a files preventing the install since they are newer versions.


Thanks,
Renee

 Integrated web design, digital marketing and technology solutions for the busy entrepreneur.
-----
Renee Cerullo
RLComputing is WBE Certified
President, RLComputing<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.rlcomputing.com%2F&data=04%7C01%7Cklaiken%40buffalo.edu%7Cd4afe08d49414af0c25c08d8adf7eec4%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637450628220607108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=boyhZPZ3jpBjSjXNJi10VZElquhSK7WxafeQN1Uf%2F4A%3D&reserved=0>
HELP DESK – ***@***.******@***.***>
Phone: 716.656.8958
Fax: 1.866.375.3393
Hours of Operation: Monday thru Friday 8am - 5pm EST

**Comment by cerullo** [comment]
I now have two sites completely messed up by installing this module. Something is just not right with your latest edition. None of the icons show and everything is text on top of each other. Only thing I can do is restore one site from backup which is crazy to have to do. What is missing here?

Thanks,
Renee

 Integrated web design, digital marketing and technology solutions for the busy entrepreneur.
-----
Renee Cerullo
RLComputing is WBE Certified
President, RLComputing<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.rlcomputing.com%2F&data=04%7C01%7Cklaiken%40buffalo.edu%7Cd4afe08d49414af0c25c08d8adf7eec4%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637450628220607108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=boyhZPZ3jpBjSjXNJi10VZElquhSK7WxafeQN1Uf%2F4A%3D&reserved=0>
HELP DESK – ***@***.******@***.***>
Phone: 716.656.8958
Fax: 1.866.375.3393
Hours of Operation: Monday thru Friday 8am - 5pm EST

**Comment by iJungleboy** [comment]
@cerullo  Any progress on this? AFAIK 2sxc is doing it's job as is.

I'll close this for now, but feel free to pot any findings if there really is an issue w/2sxc.

Note that it's running in production - eg. https://blazor-cms.org/ and https://blazor-cms.org/blog

**Comment by cerullo** [comment]
Nope never got it to work at all. Tried 3 different sites and no luck. I went back to v11 and it kind of works. Still bugs since I can’t delete anything but it functional to the client. I gave up. Spent way too much time trying to figure out the bugs


Thanks,
Renee

 Integrated web design, digital marketing and technology solutions for the busy entrepreneur.
-----
Renee Cerullo
RLComputing is WBE Certified
President, RLComputing<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.rlcomputing.com%2F&data=04%7C01%7Cklaiken%40buffalo.edu%7Cd4afe08d49414af0c25c08d8adf7eec4%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637450628220607108%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=boyhZPZ3jpBjSjXNJi10VZElquhSK7WxafeQN1Uf%2F4A%3D&reserved=0>
HELP DESK – ***@***.******@***.***>
Phone: 716.656.8958
Fax: 1.866.375.3393
Hours of Operation: Monday thru Friday 8am - 5pm EST
