### ISSUE TITLE
P3.2 Implement all text fields features

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#298]
1. Single-Line, Multi-Line --> ok
2. WYSIWYG --> ok 
3. Drop-Down - with fields to choose from etc. --> ok
4. Automatic validation reg-ex -- PENDING

WYSIWYG will not use telerik...so we'll have to rely on ck editor AND give an error if it's not installed

Dropdown
1. Originals-list (in the correct language) 
2. use keys / values where saved as such

**Comment by raphael-m** [comment]
As discussed, the dialog will still use Telerik RadEditor (or whatever is registered as HtmlEditorProvider in DNN).

**Comment by raphael-m** [comment]
Added regex validation to string fields. To discuss: it currently uses ValidationRegExJavaScript, the server side regex is not used.
