### ISSUE TITLE
v15 shows error in user profile datasource

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2980]
**I'm submitting a ...**
[x] bug report 

**...about**
[x] APIs like REST
[x] other / unknown

**Current behavior**  
As soon as I try to load a view or run a query with user profiles data source I get the following error:

Error: System.InvalidOperationException: Unable to resolve service for type 'ToSic.Sxc.Dnn.DataSources.DnnUserProfile+Dependencies' while attempting to activate 'ToSic.Sxc.Dnn.DataSources.DnnUserProfile'. at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider) at ToSic.Lib.DI.IServiceProviderExtensions.Build[T](IServiceProvider serviceProvider, Type type) in C:\Projects\2sxc\eav-server\ToSic.Lib.Core\DI\IServiceProviderExtensions.cs:line 24 at ToSic.Eav.DataSources.DataSourceFactory.GetDataSource(Type type, IAppIdentity app, IDataSource upstream, ILookUpEngine lookUps) in C:\Projects\2sxc\eav-server\ToSic.Eav.DataSources\DataSourceFactory.cs:line 71 at ToSic.Eav.DataSources.DataSourceFactory.GetDataSource(String sourceName, IAppIdentity app, IDataSource upstream, ILookUpEngine lookUps) in C:\Projects\2sxc\eav-server\ToSic.Eav.DataSources\DataSourceFactory.cs:line 55 at ToSic.Eav.DataSources.Queries.QueryBuilder.BuildQuery(QueryDefinition queryDef, ILookUpEngine lookUpEngineToClone, IEnumerable`1 overrideLookUps, Boolean showDrafts) in C:\Projects\2sxc\eav-server\ToSic.Eav.DataSources\Queries\QueryBuilder.cs:line 152 at ToSic.Eav.DataSources.Queries.Query.CreateOutWithAllStreams() in C:\Projects\2sxc\eav-server\ToSic.Eav.DataSources\Queries\Query.cs:line 107 at ToSic.Eav.DataSources.Queries.Query.get_Out() in C:\Projects\2sxc\eav-server\ToSic.Eav.DataSources\Queries\Query.cs:line 38 at ToSic.Eav.DataSources.DataSource.GetStream(String name, String noParamOrder, Boolean nullIfNotFound, Boolean emptyIfNotFound) in C:\Projects\2sxc\eav-server\ToSic.Eav.DataSources\DataSources\DataSourceBase_Connections.cs:line 34 at ToSic.Eav.DataSources.DataSource.get_List() in C:\Projects\2sxc\eav-server\ToSic.Eav.DataSources\DataSources\DataSourceBase_Connections.cs:line 54 at ToSic.Sxc.Code.DynamicCodeRoot.AsList(Object list) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Code\DynamicCodeRoot_As.cs:line 105 at ASP._Page_Portals_0_2sxc_NewDrugs__farmacos_adultos_cshtml.Execute() in c:\inetpub\vhosts\pensaremsaude.pt\httpdocs\Portals\0\2sxc\NewDrugs\_farmacos_adultos.cshtml:line 32 at System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) at ToSic.Sxc.Engines.RazorEngine.Render(TextWriter writer) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Engines\Razor\RazorEngine.cs:line 117 at ToSic.Sxc.Engines.RazorEngine.RenderTemplate() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Engines\Razor\RazorEngine.cs:line 125 at ToSic.Sxc.Engines.EngineBase.Render() in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Engines\EngineBase.cs:line 136 at ToSic.Sxc.Blocks.BlockBuilder.RenderInternal() in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Blocks\BlockBuilder_Render.cs:line 121

**Your environment**

* **2sxc version(s):** 15
* **DNN:** [ 9.11 ]

**Comment by iJungleboy** [comment]
thanks for spotting this, will be fixed in 15.01

**Comment by eXistenZe** [comment]
I use profiles in all my apps for custom access and coded ids, so I'll test v15 on the other sites when the update gets released.

**Comment by eXistenZe** [comment]
@iJungleboy Do you you could release a quick fix for this issue?
