### ISSUE TITLE
Item History no longer working in v15.01.00

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2997]
### I'm submitting a ...
 
[x] bug report 

### ...about

[x] edit experience / UI
[x] admin experience UI

### Current Behavior 
 
When you open an entity/item and click on Item History (previous versions)

![image](https://user-images.githubusercontent.com/653301/216207512-dd9ecfb1-7f18-403d-b20c-56186afd427d.png)

you get this error:
 
```
[site url] says

Had an error talking to the server (status 400).
Message: Bad Request
Detail: Invalid column name 'CJson'.
```
 
![image](https://user-images.githubusercontent.com/653301/216207537-ad1e71b9-c998-4db8-93ca-d465c59f85f3.png)
 
### Expected Behavior

The list of history items should display.

This site is a clone of a production site still running v14.12.03 where the Item History is still working. It clearly stopped working after the upgrade to 15.01.

### Your environment**

* **2sxc version(s):** 15.01.00 - - just upgraded from v14.12.03
* **Browser:** all |
* **DNN:** v9.10.02
* **Hosting platform:** IIS, Windows Server 2019 (not-azure)
* **Language:** any/all

**Comment by iJungleboy** [comment]
This looks bad. Basically this implies that some upgrade SQL didn't run, because we had to rename some columns in the DB which should be installed on v15.00 - of course also on 15.01. I assume you did a direct upgrade from 14.12.x to 15.01.

@tvatavuk could you look into this ASAP?

**Comment by tvatavuk** [comment]
@jeremy-farrance for quick fix your 2sxc v15.01.00 please use **SQL Console** to:
1. Upload this file [fix-15.00.01.SqlDataProvider.txt](https://github.com/2sic/2sxc/files/10566649/fix-15.00.01.SqlDataProvider.txt)
2. Run Script.

![image](https://user-images.githubusercontent.com/2724850/216269238-9f45895b-2fce-4abc-be23-cd60bfaeb9d7.png)

This SQL script is made in a way that you can run it many times without issues.

**Comment by iJungleboy** [comment]
@jeremy-farrance Thanks for catching this.

You can either use the quick fix from @tvatavuk above or wait for 15.02 which should be released today.

**Comment by jeremy-farrance** [comment]
Fantastic!! I really appreciate the quick fix option, thank you!

**Comment by jeremy-farrance** [comment]
I did the quick fix (SQL) and it worked. Thanks again!!
