### ISSUE TITLE
(Octane) Error on any 2sxc module I add

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#3000]
### I'm submitting a ...
[x] bug report 
[x] not sure

### ...about
[x] admin experience UI

### Current Behavior / Expected Behavior
When I add a content or app module to a page, I get:

```
An Unexpected Error Has Occurred In {ModuleDefinitionName}: {Error}

An Unexpected Error Has Occurred In ToSic.Sxc.Oqt.Content, ToSic.Sxc.Oqtane.Client: Object reference not set to an instance of an object.

System.NullReferenceException: Object reference not set to an instance of an object.
   at ToSic.Sxc.Oqt.App.Index.Initialize2SxcContentBlock() in C:\Projects\2sxc\2sxc\Src\Oqtane\ToSic.Sxc.Oqt.Client\App\Index.razor.cs:line 95
   at ToSic.Sxc.Oqt.App.Index.OnParametersSetAsync() in C:\Projects\2sxc\2sxc\Src\Oqtane\ToSic.Sxc.Oqt.Client\App\Index.razor.cs:line 63
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

{"ModuleDefinitionName":"ToSic.Sxc.Oqt.Content, ToSic.Sxc.Oqtane.Client","Error":"Object reference not set to an instance of an object."}
```

### Instructions to Reproduce the Problem
I installed octane 3.3.1 and installed on a win11 test machine.
I update the Oqtane.Server.runtimeconfig.json for .net core 7.0.2 (not sure if this matters).
Installed 2sxc 15.01 with manual file placement.
Nothing else changed.

**Comment by iJungleboy** [comment]
@eXistenZe just fyi: Oqtane 3.3.1 introduced a breaking change, which we only fixed in 15.02. Pls try that.

**Comment by eXistenZe** [comment]
No change.

**Comment by iJungleboy** [comment]
> I installed octane 3.3.1 and installed on a win11 test machine. I update the Oqtane.Server.runtimeconfig.json for .net core 7.0.2 (not sure if this matters). Installed 2sxc 15.01 with manual file placement. Nothing else changed.

This looks fishy - you should not upgrade .net to 7.x as of now, Oqtane 3.3 is still on .net 6. Could you reset this and try again?

**Comment by eXistenZe** [comment]
Yep. That solved it.
oqtane install documentation is still very fresh.
It links to the newest .net package, but never mentions supported version.

**Comment by iJungleboy** [comment]
thanks for closure ;)
