### ISSUE TITLE
C# WebAPI - Potential App.Data Caching Issue Across Many Releases

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#3005]
### I'm submitting a ...
[x] bug report

### ...about
[x] Content Types or data management
[x] APIs like REST

### Current Behavior / Expected Behavior
We have a WebAPI that queries/updates many data types, and some of our datatypes have many records (insights says 5,138 total items in cache across multiple types in the app).

When we run the WebAPI the first time following an application reset/cache clear, some of the "AsList(App.Data["DataType"]).Where()" statements return values others do not on the first run when matching relationships on EntityId. On a second run, they work as expected which leads us to believe that all the items may not be cached. We've also done cache resets in insights, but that has not resolved the issue.

As a test, we modified the endpoint and commented out all the App.Data.Create() or App.Data.Update() lines. Then we uncommented them and re-ran the same endpoint and it functioned as expected.

We're not sure if this relates to a previous issue like #2127 but since we have many APIs across the whole app we're not sure where else it may pop up.

Here is a brief example on our WebAPI:

```
public class MembersController : Custom.Dnn.Api12
{
	...
	public HttpResponseMessage AssessMaintenanceFees()
	{
		...
		var propertyBoatSlips = AsList(App.Data["BoatSlips"]).Where(k => k.Assignment != null && k.Assignment.Count > 0 && k.Assignment[0].EntityId == p.EntityId);

		if (propertyBoatSlips.Any())
                {
			foreach (var s in propertyBoatSlips)
			{
				var w = AsList(App.Data["Watercraft"]).FirstOrDefault(ww => s.Watercraft != null && s.Watercraft.Count > 0 && ww.EntityId == s.Watercraft[0].EntityId);
				var f = AsList(App.Data["SlipFees"]).FirstOrDefault(ff => w != null && w.SlipFeeLength != null && w.SlipFeeLength.Count > 0 && ff.EntityId == w.SlipFeeLength[0].EntityId);	
			}
		}
		...
	}
}
```

On first run after a recycle, "propertyBoatSlips" sometimes returns data or doesn't. And on first run, "w" and "f" mostly never return data. Only when we re-run the endpoint after uncommenting the Create/Updates does it function as expected.

We're in the process updating DNN/2SXC and testing it on our development server for a priority update. We've been able to replicate this issue on DNN 9.8 with 2SXC 13.1 all the way up to DNN 11 with 2SXC 15.2 across various tests.

### Your environment**
* **2sxc version(s):** Any releases greater than v13.1
* **DNN:** 9.8 & 9.11
* **Hosting platform:** IIS

**Comment by iJungleboy** [comment]
It it possible to provide a sample app so that we can investigate efficiently? either upload here or mail to info@

**Comment by tvatavuk** [comment]
@tpperlman I need your test app, and test case to reproduce it, so we can follow on it.
I created test app with 50.000 entities, with multiple parent, child, grandchild relations and web api code that returns 30 of it.
I did try many tests with dnn restart or similar but never noticed that 30 entities are missing in web api response.
It is not effective to spend more time chasing, so please prepare something for me, so I can reproduce it on my side, so we can see what we need to fix.

**Comment by tpperlman** [comment]
Hi @tvatavuk, sorry for not getting back earlier but we were away.

We'll close this for now since we had to refactor our razor code to get the customer launched and broke it out into multiple routines.
