### ISSUE TITLE
Bug: Users DataSource returns RoleIds as Array, which is a non-standard value - should be string

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#3011]
### I'm submitting a ...
[x] bug report => search github for a similar issue before submitting

### ...about
[x] Content Types or data management

### Your environment**

* **2sxc version(s):** 15.00 - 15.02

**Comment by jeremy-farrance** [comment]
This appears to fix #2440.

I plan to test and confirm, either way, thanks for this!

**Comment by iJungleboy** [comment]
@jeremy-farrance 
Absolutely. And it's the better place to be here, than in the user profile :)
