### ISSUE TITLE
App.Data Caching Issue When Accessing Data from External C# Code

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#3021]
### I'm submitting a ...

[x] bug report

### ...about
[x] App.Data caching from External C#
[x] Razor templating
[x] other

### Current Behavior
The code works and gets the data (to display) as expected. However, once the data is retrieved, it won't update as expected unless you do a full DNN (app pool) Restart Application.
 
You can see in this screenshot, after editing the item and adding "UPDATED" to the Title and changing the background-color from yellow to red, the normal save and module/app update shows the changes immediately. But even after multiple page reloads, the full "alert" at the top of the page does not change. I even came back after an hour, did a page refresh from another computer/browser and the "alert" was still showing the old, unchanged item.

(1) is the same alert, the top one (yellow) is the output from the theme/skin (code below). The one below it (red) is the output in the module app used to manage the data (Notifications).
![image](https://user-images.githubusercontent.com/653301/221721158-0a914b2b-c528-43f7-9ba1-a0d3683c90c5.png)
 
Here is what it looks like after the restart and an extra page reload. Note that DNN Clear Cache does NOT update it.
![image](https://user-images.githubusercontent.com/653301/221724222-f9bb87bd-a3c9-4edb-ae43-cbc4a4e1fb01.png)
 
### Expected Behavior
Each time you add a new item (Entity in the Content-Type) or edit an existing one, your changes should be visible on the next page (re)load. 

### Instructions to Reproduce the Problem
Here is the code I am using in the theme (.ascx) file. Maybe I am doing something wrong? I have tried a number of variations based on the two reference links to your docs (in comments below)

```
<!-- included from _header.ascx -->
<%@ Import Namespace="Microsoft.Extensions.DependencyInjection" %>
<%@ Import Namespace="ToSic.Sxc.Services" %>
<%@ Import Namespace="DotNetNuke.Common.Extensions" %>

<%
// Reference: https://docs.2sxc.org/net-code/external/dotnet-external-use.html
// Reference: https://docs.2sxc.org/abyss/releases/history/v13/dnn-factory/index.html
var appId = 28; // Notification App on Accu4 is 28
var ServiceProvider = HttpContext.Current.GetScope().ServiceProvider;
var codeSvc = ServiceProvider.GetService<IDynamicCodeService>();
var dynCode = codeSvc.OfApp(appId: appId);
var stream = dynCode.App.Data["Notification"];
var Notifications = dynCode.AsList(stream)
  .Where(n => n.NoticeActive)
;
%>

<% foreach (var item in Notifications) { %>
  <div id="notification-wrapper-<%=item.EntityId %>" class="container-fluid p-0">
    <div class="d-flex alert alert-<%=item.NoticeClass %> alert-dismissible fade show" role="alert">
      <!--Icon-->
      <i class="<%=item.NoticeIconStyle %> <%=item.NoticeIcon %> fa-2xl p-3 pr-5"></i>
      <span class="flex-grow-1">
        <span class="lead font-weight-bold"><%=item.NoticeTitle %></span> &ndash; 
        <span><%=item.NoticeStart.ToString("ddd, MMM d - h:mm tt") %></span><br>
        <span><%=item.NoticeDesc %></span>
      </span>
      <!--Close Notification-->
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">
          <i class="fa-solid fa-times"></i>
        </span>
      </button>
    </div>
  </div>
<% } %>
```

### Your environment
* **2sxc version(s):** 15.03.00, 15.02.00, and 14.12.03
* **DNN:** 9.11.01 and 9.10.02
* **Browser:** all/any
* **Hosting platform:** IIS on Win Server 2019 (VPS)
* **Language:** any/all

**Comment by iJungleboy** [comment]
We'll look at this in the next few days...

**Comment by iJungleboy** [comment]
@tvatavuk could you try to reproduce? I can't really imagine the cause, but maybe the service scopes are different, resulting in different AppStates being loaded/used?

**Comment by tvatavuk** [comment]
I reproduce it. 

Core issue is related to lookup of `ZoneId` when only `AppId` is provided.

First workaround is to use [`OfModule(int pageId, int moduleId)`](https://docs.2sxc.org/api/dot-net/ToSic.Sxc.Services.IDynamicCodeService.html#ToSic_Sxc_Services_IDynamicCodeService_OfModule_System_Int32_System_Int32_) with `PortalId` and `ModuleId`.
```cs
var pageId = 1737;
var moduleId = 4110;
var dynCode = codeSvc.OfModule(pageId, moduleId);
```

Other workaround is to find `ZoneId` (eg. in System dialog) and provide it to `OfApp`.

![image](https://user-images.githubusercontent.com/2724850/227017055-96c07c96-0ff0-4226-be66-8fe92f538f23.png)

```cs
var zoneId = 1052;
var appId = 2644;
var dynCode = codeSvc.OfApp(appStates.IdentityOfApp(zoneId, appId));
```

Here are 2 not recommended ways to find `ZoneId` using 2sxc internal appis.
```cs
var zoneMapper = ServiceProvider.GetService<ToSic.Eav.Run.IZoneMapper>();
var zoneId = zoneMapper.SiteOfApp(appId).ZoneId;
var dynCode = codeSvc.OfApp(zoneId: zoneId, appId: appId);
```

```cs
var appStates = ServiceProvider.GetService<ToSic.Eav.Apps.IAppStates>();
var dynCode = codeSvc.OfApp(appStates.IdentityOfApp(appId));
```

**Comment by iJungleboy** [comment]
Should be in 15.05 - today or tomorrow.
