### ISSUE TITLE
Missing icons in admin screens on fresh install of 15.3.0

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#3034]
### I'm submitting a ...
[x] bug report

### ...about
[x] admin experience UI

### Current Behavior / Expected Behavior

On a fresh install, I'm seeing this issue where icons are missing and the text is displaying oddly in the Admin modals.

![Screenshot 2023-03-10 at 10 52 11 AM](https://user-images.githubusercontent.com/8751936/224402299-79a94c7d-4855-42bd-9088-d23f87dc5745.png)

The console seems to show some errors like this:

GET https://domain.com/desktopmodules/tosic_sexycontent/dist/ng-edit/material-icons-outlined.woff2 > Status 404 Not Found

Normal admin screens.

Bug

It's on DNN 9.7.2

CDF was enabled when I installed but I've since:

1. Turned off composite files and minification
2. Incremented CDF version
3. Cleared cache
4. Restarted site

### Instructions to Reproduce the Problem
I just installed 15.3.0 fresh to a DNN 9.7.2 website that, to my knowledge, never had 2sxc on it before.

### Your environment

* **2sxc version(s):** 15.3.0  
* **Browser:** all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari
* **DNN:** 9.7.2
* **Hosting platform:** all
* **Language:** English / French

**Comment by iJungleboy** [comment]
This is a problem because we moved the icon fonts to be included in 2sxc (to not load from google - because of GDPR). It seems some web servers - especially on azure - need woff2 to be configured. You'll find similar issues in the closed issues for this with the fix.

We're working on this, because it has occured too often, and we need a way to default back to the CDNs, but still allow easy switching to local...

**Comment by ajplopez** [comment]
Good to know, thanks. I tried the methods mentioned in the other ticket but no luck.

Is there something I can try to get it working?

If not, what's the best version to go to that doesn't have the problem but is still a solid, recent (LTS) release?

**Comment by ajplopez** [comment]
I have verified that it's trying to load WOFF2 but it fails. I used the same StaticContent section from a DNN 9.11 that includes the woff2 mimeMap line but that doesn't seem to make a difference.
