### ISSUE TITLE
Page picker missing subpage levels

### ISSUE THREAD

**Issue by ArankaBond** [2sic/2sxc#3040]
### Current Behavior / Expected Behavior
We have enabled Multilanguage on the website, now the Page Picker on the default language is not complete.
It only shows the main page level and one sub level but not the 2nd, 3rd or 4th level of pages.
Now our client can't select the correct pages for links.
There was not a problem before we enabled the Multilanguage.

### Instructions to Reproduce the Problem
When you add a link in the text you can select a DNN page. This page picker only show a fraction of the pages it needs to show.
We also notice a "page" Missing Parent was added, we are not sure why this shows.
![image](https://user-images.githubusercontent.com/28566983/226573074-c4571060-5667-43e0-b853-5b4b62f12b1c.png)

But it does not show the subpages of "Wat is Kinderpalliatieve Zorg" for example, here you can see it does exsist in the DNN pages.
![image](https://user-images.githubusercontent.com/28566983/226573201-78f00271-7045-4874-af14-46933139bba5.png)

### Your environment
* **2sxc version(s):** 15.2.0 
* **Browser:** all
* **DNN:** 9.11.00
* **Hosting platform:** azure
* **Language:** Dutch | English | Polish | Arabic

**Comment by iJungleboy** [comment]
Should be fixed in v15.06 to be released today or tomorrow.
