### ISSUE TITLE
WYSIWYG - files from site are missing (only files from current item ADAM)

### ISSUE THREAD

**Issue by miguelvaz78** [2sic/2sxc#3041]
### I'm submitting a ...
[x] bug report

### ...about
[x] edit experience / UI

### Current Behavior / Expected Behavior
After Upgrading to v15, the default wysiwyg editor is missing the link to DNN file toolbar that was present in the version I was using previously.
![image](https://user-images.githubusercontent.com/38688079/226699519-e242e543-4b26-424d-ac2a-1401ad0aa02c.png)

After investigating this I learned that the new system allows different configurations to be made in the field config UI so I have selected the new option to use the "Rich Media - With Images and Layout (for Blogs, News etc.)" configuration for the field.

This resulted in having an extended toolbar with the option I needed in the inline editor.
![image](https://user-images.githubusercontent.com/38688079/226700292-710938e3-8274-4321-9827-f7321b03d6e0.png)

Now when the fullscreen editor or the advanced editor mode is used, the toolbar loses the commands to add images and links (second line in the previous image):
![image](https://user-images.githubusercontent.com/38688079/226701429-032f0c9a-ce70-4bfa-b9d4-990333db7bbc.png)

I still can select the file to where I want to link to or the image i want to insert into the content, but the toolbar to select this options disapears.

Another side effect is the change of options available when trying to resize an image added to the content.
In the default editor I see thye options 100%, 70%, .. up to 10% as in the following image:
![image](https://user-images.githubusercontent.com/38688079/226702200-9bd1ed79-3757-4be2-9260-184773749773.png)

When using the new configuration to allow Rich Media, I get a different ser of options:
![image](https://user-images.githubusercontent.com/38688079/226702394-f46777d6-039b-48f3-9963-e302a21bef68.png)
When using a localized version (portuguese) pt-PT of the site, this options do not show the correct labels:
![image](https://user-images.githubusercontent.com/38688079/226702556-4885e846-3532-468a-b4e4-955cae443545.png)

How to I revert to using the previous version of the wysisyg editor where can I see the configuration used for the Rich Media mode so I can copy-it and extend it?

### Your environment
* **2sxc version(s):** 15.0X.X 
* **DNN:** 9.11.01
* **Hosting platform:** IIS
* **Language:** English | Portuguese

**Comment by iJungleboy** [comment]
These modes are still in preview / beta.
Rich mode needs some extra work to get it going.
The thing you are seing is a bug in 15.03 and will be resolved in 15.04 tomorrow. 

But don't use rich mode yet, it's still under construction...

**Comment by miguelvaz78** [comment]
Thanks for the super fast feedback,. 

Will check the next for the missing command to create a link to a DNN file that was available in the advanced mode.

**Comment by iJungleboy** [comment]
we'll check

**Comment by iJungleboy** [comment]
buttons will be back in 15.06 - today or tomorrow.
