### ISSUE TITLE
Edit UI Showing Wrong Date, Adding 1 Day After Daylight Savings (US, CST)

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#3049]
### I'm submitting a ...
[x] bug report 

### ...about
[x] edit experience / UI

### Current Behavior
If you enter a date in a date field, when you TAB out of the field, it adds a day (e.g. 12/31/2022 shows as 1/01/2023). 

Similar issue #2982 - Edit UI Showing Wrong Date by Two Days

**Important to note, unlike the prev issue, this time the WRONG DATE IS STORED**
 
### Expected Behavior
Dates in the Edit UI should be stored as entered.

### Instructions to Reproduce the Problem

I have included a video so you can see the issue in action:
https://accuraty-my.sharepoint.com/:v:/p/jfarrance/EedcTR2-PWpBo7OHNOID0KEBbTgjuHv-7vKfXxF5XoxjKA?e=51CzjA

### Your environment**
* **2sxc version(s):** 15.05.00
* **Browser:** all (tried in Chrome 111 and Edge 110, same)
* **DNN: tried in 9.10.02 and 9.11.01
* **Hosting platform:** IIS on Windows Server 2019 
* **Language:**  tried on English only

### Comments

This was not happening prior to our recent change (spring forward) to Daylight Savings Time, [see CDT](https://www.timeanddate.com/time/zones/cdt). 

If you use the Date Picker, this problem does NOT happen.

This is happening on all Content Types with dates whether or not they have a time 
It happening to CTs with and without any formulas. 
There are no console errors and no errors being logged anywhere that I can find.

**Comment by iJungleboy** [comment]
Note that as a temporary workaround, please just use the picker.
We should have a solution out for 15.06 today/tomorrow.
