### ISSUE TITLE
Unable to Add Entity Relationships Through Code

### ISSUE THREAD

**Issue by jtherrien-accuraty** [2sic/2sxc#3050]
### I'm submitting a ...

[x] bug report => search github for a similar issue before submitting

### ...about

[x] Content Types or data management
[x] APIs like REST

### Current Behavior / Expected Behavior

Trying to add entities to a relationship field no longer works, at least with doing it through an API controller using a list<int> or a list<Guid> as the object portion of the Dictionary<string, object> that is passed to App.Data.Create/Update. 

Able to add entities to a relationship field through App.Data.Create/Update using a list of EntityIds or EntityGuids

Had a custom app for importing records working while on 2sxc v15.03.00 including creating entities with filled-out entity-relationship fields while on 2sxc v15.03.00 that stopped working after the update to v15.05.00. 

### Instructions to Reproduce the Problem

Before updating to v15.5.0 in order to add relationships to a field in an API controller I would create a List<int>, add the EntityIds of the items in the relationship to it, add the list as the object in a Dictionary<string, object> with the string part being the relationship field, and then call App.Data.Create/Update using the dictionary. After Updating now it throws the error: `"System.InvalidCastException: Unable to cast object of type 'ToSic.Eav.Data.Value'1[System.Collections.Generic.IEnumerable'1[ToSic.Eav.Data.IEntity]]' to type 'ToSic.Eav.Data.IValue'1[System.String]'`

Trying to use EntityGuids throws the same error. Converting the list to an array also throws the same error. Converting the list to a string stops the error from being thrown, but results in it just being ignored/having no effect. 

### Your environment

* **2sxc version(s):** 15.05.0  
* **Browser:** NA
* **DNN:** 9.11.01
* **Hosting platform:** Server 2022 IIS
* **Language:** English

**Comment by iJungleboy** [comment]
This must have been introduced as we refactored the entire system to be immutable. But we should fix it asap. @jtherrien-accuraty can you send some sample code, thx!

**Comment by iJungleboy** [comment]
fixed in 15.06 to be released today.
