### ISSUE TITLE
Error: Can't install any type of App or Content app

### ISSUE THREAD

**Issue by ArankaBond** [2sic/2sxc#3052]
I'm submitting a bug report

### ...about
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management
[x] other / unknown

### Current Behavior / Expected Behavior
Adding the content app to the portal and some 2sxc apps without issue. Using the function 2sxc gives when no apps are installed yet.

### Instructions to Reproduce the Problem
We have a new portal added in a exsisting installation.
There we want to configure base Content Apps and for example the FAQ app but all types give a error while installing.
It can't find the install package.
![image](https://user-images.githubusercontent.com/28566983/228156672-ac4a7df2-b3c4-4113-9dea-c23ecd8414cb.png)

### Your environment
* **2sxc version(s):** 15.02.0 
* **Browser:** all
* **DNN:** 9.11.00
* **Hosting platform:** azure
* **Language:** any/all

**Comment by ArankaBond** [comment]
When opening the admin of 2sxc I see this error:
![image](https://user-images.githubusercontent.com/28566983/228225073-57548040-8307-4d09-98e5-44d599fcc15e.png)

**Comment by iJungleboy** [comment]
I assume this is already fixed, because we've done extensive install testing on 15.04/15.05. 
I recommend you wait for 15.06 to be released in a few hours, and then verify.
