### ISSUE TITLE
PagePicker doesn't see Pages of type "Existing", "URL" and "File" anymore

### ISSUE THREAD

**Issue by a-git-hub** [2sic/2sxc#3054]
I'm submitting a ...
[x] bug report

...about
[x] edit experience / UI
[x] admin experience UI

**Current Behavior / Expected Behavior**

PagePicker in 2sic V.12 and older versions was able to see Pages of all four available types: "Standard", "Existing", "URL" and "File". PagePicker in 2sic V.14 sees only one page type: "Standard". 

**For example**: 
Under the standard parent page "Über uns" I have five child pages of type "URL":

| ![image](https://user-images.githubusercontent.com/20930019/228336078-4d3639e4-4f56-493c-96dc-148d6c18c80b.png) |
|-|

**PagePicker in 2sic V.12 and older sees them all**:
| ![image](https://user-images.githubusercontent.com/20930019/228352414-a7877911-e35c-4bf5-a504-ad47143605ca.png) |
|-|

**Now, PagePicker in 2sic V.14 sees only Pages of the type "Standard"**:  
| ![image](https://user-images.githubusercontent.com/20930019/228351363-c29bf993-e012-4918-ae20-44072d67de79.png) |
|-|

Which means an editor or an admin cannot pick any of these five child pages anymore as they are not in the PagePicke-tree anymore.

Environment:
* **2sxc version(s):** 14.12.3 
* **DNN:** 9.10.xx
* **Hosting platform:** IIS 
* **Language:** any/all

**Comment by iJungleboy** [comment]
Related to #3040

**Comment by iJungleboy** [comment]
Should be fixed in v15.06 to be released today or tomorrow.
