### ISSUE TITLE
Image Settings - Crop Behavior Doesn't Work with Image Manager

### ISSUE THREAD

**Issue by bmusgrove-accuraty** [2sic/2sxc#3057]
### I'm submitting a ...
[x] bug report

### ...about
[x] edit experience / UI

### Current Behavior / Expected Behavior
**Current Behavior 1 =** If I add images to the Site Assets (Resource Manager) and locate one of those uploaded images to place into my basic content module on the site I am not allowed to use the "Image Settings" for the Image. Which doesn't allow me to use the cropping features.

**Current Behavior 2 =** However, if I drag and drop the image I want to use in a basic content module into the Image field, the "Image Settings" are available to me.

**Expected Behavior =** Have both methods above trigger the "Image Settings". It shouldn't matter which route you take and the "Image Settings" should be available when dealing with any image no matter the upload method. I have worked with clients that like to add many photos at once within a topic folder in the "Resource Manager" in "Site Assets" and then go to pages to select them with the "Image Manager" tool. But doing this method makes it so they cannot use the crop tool as intended. They then have to resort to drag and drop which eliminates their organizational structure within the "Resource Manager".

### Instructions to Reproduce the Problem
Reproduce Current Behavior 1:

1. Add an image to Site Assets - Resource Manager
2. Add Basic Content Module to the page
3. In the Image field, click on the apple icon > more > Image manager > uploaded photo from step 1
4. The Image settings do not become active
![image-settings-bug-image-added-in-resource-manager](https://user-images.githubusercontent.com/68243808/228622014-02c48d48-2490-4f3f-9288-356764c744e7.png)

Reproduce Current Behavior 2:

1. Add Basic Content Module to the page
2. In the Image field, drag and drop an image
3. The Image settings are now active
![image-settings-bug-image-added-by-drag-and-drop](https://user-images.githubusercontent.com/68243808/228622052-f4c6e983-353f-4f14-896c-fc6a0d2ded51.png)

###My environment

* **2sxc version(s):** 15.5.0
* **Browser:** Chrome was the browser in use
* **DNN:** 9.11.01
* **Hosting platform:** Windows server 2022
* **Language:** English

**Comment by iJungleboy** [comment]
As of now this is _by design_

Reason is that we differentiate between:

1. **Personal** images which "belong" to the current entity
2. **Global** images which don't belong to the current entity

The reason for this is that crop settings etc. are part of the image file and if it's reused anywhere else, the settings would apply there as well. We believe this could confuse the user, since two users could keep on undoing the others settings because they are only focused on how they use it - and get frustrated because they come back a few days later and it's been changed again by the other user - and nobody knows why this is happening.

That's why the current behavior is like this. 

Could you describe your setup more, so we can figure out how to "loosen" this a bit, without running into the other problem?

**Comment by bmusgrove-accuraty** [comment]
Hi Daniel! Understood, and that makes sense after seeing what you have said about the two options.

For the most part, our setup is 2sxc Content out of the box. The module I want to edit the photo for is using the 2sxc Content > Basic Content > Image | Text view.

It seems like there could be an image metadata field per individual item so that it can be assigned those crop features on that particular item ID.

**Comment by jeremy-farrance** [comment]
I think the easy way forward here is to allow the user/editor to still use the Image Settings but automatically copy the image from its Global location in to Personal. Then the original still exists and the modified version only exists one-off for the entity.
 
Then as an additional wishlist item, it would be nice if the (Personal) entity image knew about the original and offered the option to Revert back to the original (if it is still there).

**Comment by iJungleboy** [comment]
@jeremy-farrance I believe copying the file would be against the idea of having a shared location, as replacing the file in the shared location would then not replace the copies created in the meantime.

An alternative is to simply show a warning that the setting is for a shared file, and the user should be aware of it.

**Comment by iJungleboy** [comment]
Will try to introduce the ability to set this for all files, but show a warning if it's a shared file...
