### ISSUE TITLE
DNN Page Link does not create a link

### ISSUE THREAD

**Issue by ArankaBond** [2sic/2sxc#3066]
### I'm submitting a ...
[x] bug report 

### ...about
[x] edit experience / UI
[x] DNN parts

### Current Behavior / Expected Behavior
Using the DNN page link selector I want to make a simple link in the editor.
![image](https://user-images.githubusercontent.com/28566983/229795114-61f37f04-3667-4dea-8b5f-ce9ee43a3b03.png)

Selecting some text and proceeding to press this button and selecting a DNN page should create a link

### Instructions to Reproduce the Problem
When selecting text, pressing the button to select a page nothing happens, no link was added. 
But we do see an error in the Inpector.
![image](https://user-images.githubusercontent.com/28566983/229795516-d4fb8eb8-afc6-4e07-8993-347bbbfd7574.png)

### Your environment

* **2sxc version(s):** 15.06.0
* **Browser:** all
* **DNN:** 9.11.00
* **Hosting platform:** Azure
* **Language:** any/all

**Comment by iJungleboy** [comment]
@DujeVatavuk pls have a look
probably due to changes in wysiwyg, but should be easy to fix

**Comment by iJungleboy** [comment]
Planned in 1-3 days :)
Just want to wait if any other bugs pop up, so we don't make a release for each issue ;)

**Comment by ArankaBond** [comment]
No problem! Thanks for the update!
