### ISSUE TITLE
Can't edit item when created as hidden

### ISSUE THREAD

**Issue by miguelvaz78** [2sic/2sxc#3070]
### I'm submitting a
[x] bug report => search github for a similar issue before submitting

### ...about
[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management

### Current Behavior / Expected Behavior
When creating an item and setting status as hidden, item is saved but cannot be edited.

### Instructions to Reproduce the Problem
1. Create a new item and set its status as Hidden.
![image](https://user-images.githubusercontent.com/38688079/233388266-da6984ca-ac27-45cc-a76d-4b1c3910dcda.png)

2. Locate the new item in the list:
(Id is missing) 
![image](https://user-images.githubusercontent.com/38688079/233389180-8f45cd3f-ddbf-4211-8ff9-b48067b1c6d7.png)

3. There is a JS error in the console:
![image](https://user-images.githubusercontent.com/38688079/233389379-cdab946a-c27a-4e34-af08-1dbbf7fc9534.png)

### Your environment

* **2sxc version(s):** 15.06.0  
* **Browser:** all 
* **DNN:** 9.11.01
* **Language:** any/all

**Comment by iJungleboy** [comment]
@tvatavuk could you look into this asap?

**Comment by tvatavuk** [comment]
Issue happens in this case because PublishedEntityId (int?) is stored with value 0, while usually it is stored as NULL. 
Current fix converts 0 to NULL while entity is saved to db and compensate for this situation if 0 is already stored in db.

https://github.com/2sic/eav-server/commit/93d05914b58217bf29fd86161ed8347c7d95a3a4

**Comment by miguelvaz78** [comment]
Thanks!

Just to manage my cliente expectations, when can we expect this fix to be included in a release?

Cheers!

**Comment by iJungleboy** [comment]
You should expect it today ;) - it is May the 4th after all ;)

**Comment by miguelvaz78** [comment]
In you, strong the force is!

many thanks!!
