### ISSUE TITLE
Admin: Show list of items missing translations (feat/wish)

### ISSUE THREAD

**Issue by ArankaBond** [2sic/2sxc#3071]
### ...about

[x] edit experience / UI
[x] admin experience UI
[x] Content Types or data management

### Current Behavior / Expected Behavior
One of our multilanguage sites is quite large and is completely build of off 2sxc content and apps.
The translation function is perfect but we do struggle to see what items are translated and which are not.
Is there an option to see what is translated and what not?
For example a list of items that do not contain (all) translations or maybe a icon in the Data list so its visible that some items have not been translated yet.

I'd like to see what the possibilities are.

### Your environment
* **2sxc version(s):** 15.0X.X  
* **Browser:** all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari
* **DNN:** all | 9.6.1 | 9.xx.xx
* **Hosting platform:** all | IIS | azure | other
* **Language:** any/all | English | German | other

**Comment by iJungleboy** [comment]
I believe what you are asking for is one or all of the following:

1. When on a page (eg in English), see which items have been translated or not
2. When on a list of items in Admin (eg all Blog Posts) see which ones have been translated

Could you confirm which one etc.?

Note that I believe this will be challenging and require further discussions. For example:

1. When is something translated? eg. if 2 of 27 field are translated, does this count as translated?

**Comment by ArankaBond** [comment]
I believe the highest priority is the admin list, this way we can have a clear overview which in turn we can discuss with our clients.

For the "When is something translated" part, ideally you would be able to make priorities for this in the data types.
For example in the Content type making the Title and Text the required check for translation.
So if those two fields are translated in all languages that its complete.

But if that is not possible I think if a field is translated in all the languages then it would be considered translated.

Does this help you?

**Comment by Rodien** [comment]
Hi, guys,

Can we expect any updates regarding this in the coming weeks?

**Comment by iJungleboy** [comment]
@Rodien As of now it's not on our priorities.

I don't know if it will become a priority any time soon, as other aspects are currently in our focus for Q2 and Q3. 
If someone contributes it, that would of course be welcome.

**Comment by iJungleboy** [comment]
I'll close this for now, as it won't be tackled any time soon unless contributed or sponsored.
