### ISSUE TITLE
Feat: Improve Sort-Items UI

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#3077]
### I'm submitting a
[x] feature request

### ...about
[x] edit experience / UI

### Current Behavior / Expected Behavior

The edit-items list is simple, but there are wishes to add features such as

* remove
* add
* add from existing

### Your environment

* **2sxc version(s):** 16.0

**Comment by iJungleboy** [comment]
@renderfarmer this is the issue for https://github.com/2sic/2sxc/discussions/2478

It's done - should be in 16.01

**Comment by iJungleboy** [comment]
Related to #3087 

Pre-release for testing [ToSic.Sxc.Dnn.16.01.00_Install.zip](https://github.com/2sic/2sxc/files/11527256/ToSic.Sxc.Dnn.16.01.00_Install.zip)

@renderfarmer could you verify?

**Comment by renderfarmer** [comment]
Nice 👌
