### ISSUE TITLE
Numeric input allows string chars but dos not store the value

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3079]
### I'm submitting a
[x] bug report 

### ...about
[x] Content Types or data management

### Current Behavior / Expected Behavior
If you create a data type "Numeric", it allows you to fill the value "abc" and save the form. The value will not be stored.
I can see the up/down arrows on the right of the field, indicating a numeric type.

Before this but was found, numeric fields prevented the insertion of letters except "e".

### Your environment
* **2sxc version(s):**  latest v15

**Comment by iJungleboy** [comment]
@DujeVatavuk could you check / fix?

**Comment by iJungleboy** [comment]
@enfJoao we can't reproduce the issue.

could you check if your F12 is showing errors? or please provide more details/samples - a short video showing the field settings and then the input would be helpful. 

browser?

**Comment by enfJoao** [comment]
After double checking, this issue is firefox specific. Not sure if you want to close the ticket, or if something can be improved.
