### ISSUE TITLE
Install incorrect

### ISSUE THREAD

**Issue by Tychodewaard** [2sic/2sxc#3097]
### I'm submitting a
[x] bug report => search github for a similar issue before submitting

### ...about
[x] edit experience / UI
[x] admin experience UI

### Current Behavior / Expected Behavior
After installing on a fresh DNN portal, there are no images showing to manage 2SXC.
![image](https://github.com/2sic/2sxc/assets/9091997/78bb78ef-93de-43b9-9271-5dd1472430a1)

Not in the selection of apps at the bottom, not in the apps itself.

If I open up the console I get a lot of 500 errors
![image](https://github.com/2sic/2sxc/assets/9091997/2183376d-af7e-4678-8760-ac67ccf8d45d)

I would be able to add an app to a page

-->

### Your environment

2sxc 16
Chrome latestt
DNN 9.10.1

In the same host there were some modules installed besides the vanilla DNN
- Easy DNN
- Live content
- Live Forms

**Comment by iJungleboy** [comment]
This is a very unusual issue. 
Can you try to open an image URL directly to find out what the 500 error is?

My guess is that you may have multiple image resizers fighting each other, or a FIPS issue.

**Comment by Tychodewaard** [comment]
[FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.]
   ToSic.Imageflow.Dnn.DependencyInjection.Resolve() +0
   ToSic.Imageflow.Dnn.ImageflowModule.PrepareHybridCacheDependencies() +46
   ToSic.Imageflow.Dnn.<ImageflowRequestAsync>d__5.MoveNext() +177
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) +59
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +510
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +220
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +134
   
   
I guess some version issue

**Comment by Tychodewaard** [comment]
Was a matter of cleaning up some old DependencyInjection binding. All good now

**Comment by iJungleboy** [comment]
thx for closure ;)
