### ISSUE TITLE
2sxc v16.0 - Swiper v2.5.1 - possible new slide bug?

### ISSUE THREAD

**Issue by skarpik** [2sic/2sxc#3112]
### I'm submitting a

[x] bug report => search github for a similar issue before submitting

### ...about

[x] edit experience / UI
[x] admin experience UI

### Current Behavior / Expected Behavior

My previous experience is with Swiper v1.0.3 (2sxc 14.12.3). When I click on the "+", I get a dialog like:

![Screenshot 2023-06-20 015846](https://github.com/2sic/2sxc/assets/3846223/34ed12a5-f376-4e4c-8a16-ac9c0b52aa30)

In the Swiper that ships with v16.1, clicking on the "+" pops up a dialog box that does not offer anywhere to upload the file:

![Screenshot 2023-06-20 020152](https://github.com/2sic/2sxc/assets/3846223/33ee9fd5-82cc-4612-93c5-da2e5eeae731)

Quite possibly I am missing something and there is some other way to add the images to the slider. Based on my previous experience, the "+" should have done the job.

I cannot see how to add images.

### Instructions to Reproduce the Problem

New DNN v9.11.02 website with 2sxc v16.1.0 and 2shine theme. Clicked on "+" to add first image but the dialog does not seem to offer that possibility.

### Your environment

* **2sxc version(s):** 16.1.0
* **Browser:** all 
* **DNN:** 9.11.2
* **Hosting platform:** IIS
* **Language:** English

**Comment by iJungleboy** [comment]
I believe if you use the admin-UI you can edit it, but not from the toolbar, correct?

**Comment by skarpik** [comment]
> I believe if you use the admin-UI you can edit it, but not from the toolbar, correct?

I'm not sure. I can add an image but other fields are missing (but quite possibly I don't know what I'm doing).

**Comment by dnndiva** [comment]
@iJungleboy, this happens in simpler templates as well. Toolbar within a foreach for entity list. It can be edited via the parent toolbar.
![image](https://github.com/2sic/2sxc/assets/4634602/e6cdf214-a9b7-4be3-b97e-5a0cd62efe57)
![image](https://github.com/2sic/2sxc/assets/4634602/6d624e11-26c0-4fed-b93d-1349a19287d4)

**Comment by iJungleboy** [comment]
Fixed in 16.02 - to be released today.
