### ISSUE TITLE
Language sensitive date picker

### ISSUE THREAD

**Issue by trouble2** [2sic/2sxc#3114]
### I'm submitting a
[x] feature request

### ...about
[x] edit experience / UI

### Current Behavior / Expected Behavior
The date picker for a date field uses american notation (MM/dd/yyyy). Since Im not american, this is confusing.
I would like the date format to be --in my case-- dd-MM-yyyy so perhaps it should respond/vary according to the language setting of the app. This will give a better overall user experience.

**Comment by DujeVatavuk** [comment]
Thank you for noticing this. Datetime formats vary according to languages chosen in DNN and 2sxc for couple of more popular languages. We have now added a bunch of new languages (Dutch included) so probably after next release you will see dd-MM-yyyy format.
