### ISSUE TITLE
Edit Modal doesn´t have any affordance to scroll

### ISSUE THREAD

**Issue by rockgobo** [2sic/2sxc#3122]
### I'm submitting a
[x] feature request

### ...about
[x] edit experience / UI

### Current Behavior / Expected Behavior
The edit Modal doesn´t have any visual feedback that the form is longer than visible and can only be scrolled with the help of a mouse wheel. The UI has no affordance that it can be scrolled

### Instructions to Reproduce the Problem
Some of our users don´t see any reason to scroll and report that they can "see" the form elements they want to chance, like uploading a new profile image. Some users also seems to have a device without a mouse, which makes it impossible to scroll for them, because they can not touch any scrollbar.
I tried to set a "overflow: scroll" for any div i see in the modal, but it doesn´t bring any scrollbar that can be touched. Is there any way to make the scrollbar visible for the edit modal? 

<img width="411" alt="image" src="https://github.com/2sic/2sxc/assets/3286890/1f015457-6436-47b4-8afd-510933cfa018">

### Your environment

* **2sxc version(s):** 16.0X.X  
* **Browser:**  Chrome XX | Edge XX 
* **DNN:**  9.6.1

**Comment by iJungleboy** [comment]
As of now there is no such feature. 

Can you explain more about the use case - since a scrollbar would also need a mouse to operate.
What kind of device is this? What browser?
How many users are affected? 

...and could a simple note on top of the form fix the issue?
