### ISSUE TITLE
Extending new WYSIWYG modes.

### ISSUE THREAD

**Issue by michaelcunningham1974** [2sic/2sxc#3136]
### I'm submitting a

[x] feature request
### ...about

[x] edit experience / UI

### Current Behavior / Expected Behavior

**Ability to add additional WYSIWYG modes to stock WYSIWYG edit controls.**

The ability to have preset editors with limited controls is great but it would be nice to add to the presets provided.  We can already kind of do this with custom edit controls but it would be preferable to extend the standard control.

### Your environment

* **2sxc version(s):** 16.0X.X  
* **Browser:** all
* **DNN:** 9.xx.xx
* **Hosting platform:** all 
* **Language:** any/all

**Comment by iJungleboy** [comment]
Hi @michaelcunningham1974 

We know that this is a wish, but ATM we don't have the resources to get this going, so it won't be happening for quite a while, unless someone else sponsors the work.

**Comment by iJungleboy** [comment]
Will close as it won't be on our priorities any time soon - unless someone contributes the code or sponsors the change.
