### ISSUE TITLE
Problems creating custom WYSIWYG in v16.

### ISSUE THREAD

**Issue by michaelcunningham1974** [2sic/2sxc#3137]
### I'm submitting a

[x] bug report

### ...about
[x] JS development

### Current Behavior / Expected Behavior
Adding a custom WYSIWYG following directions at:
https://2sxc.org/dnn-tutorials/en/razor/ui241/page

Upon calling the control getting the following error:
Uncaught TypeError: Cannot read properties of undefined (reading 'Mode')
    at Re.getSettings (wysiwyg-configuration-manager.ts:35:57)
    at De.buildOptions (tinymce-configurator.ts:68:48)
    at Qe.tinyMceScriptLoaded (editor.ts:108:43)
    at editor.ts:98:14
    at e (load-scripts.helper.ts:15:5)
    at Sd.loadScript (connector-instance.model.ts:46:9)
    at Qe.connectedCallback (editor.ts:90:20)
    at T.invoke (zone.js:372:26)
    at I.runGuarded (zone.js:144:47)
    at Qe.<anonymous> (zone.js:128:29)
    
  Assuming that this the new WYSIWYG editor needs the "mode" passed to it. Is there documentation on how to do this or is it a bug?

### Instructions to Reproduce the Problem
 Basic Content data type.

Set string edit control to WYSIWYG mini as setup up in tutorial.

![2023-07-24_16-51-57](https://github.com/2sic/2sxc/assets/30292918/4018fd51-c095-42cc-a4f2-4f548803ea69)
![2023-07-24_16-54-37](https://github.com/2sic/2sxc/assets/30292918/a8052bc3-13bd-4dc6-b521-2d924051bd85)

-->

### Your environment

* **2sxc version(s):** 16.2
* **Browser:** all | Chrome 
* **DNN:** all | 9.6.1 | 9.xx.xx
* **Hosting platform:** IIS
* **Language:** English

**Comment by iJungleboy** [comment]
We can reproduce the problem and are looking into it.

@DujeVatavuk  any ideas?

**Comment by iJungleboy** [comment]
will be in 16.06
