### ISSUE TITLE
2sxc DNN Content and Admin interface not displaying after Migration from Evoq

### ISSUE THREAD

**Issue by zsmithy44** [2sic/2sxc#3161]
### I'm submitting a

[x] bug report => search github for a similar issue before submitting
[x] not sure

### ...about

[x] edit experience / UI
[x] admin experience UI
[x] APIs like REST
[x] DNN parts
[x] other / unknown

### Current Behavior / Expected Behavior

Upon a whole site migration from Evoq 9.11 to DNN 9.11.01, when reviewing the new environment our 2sxc modules were yellowed out and had a button to upgrade the extension to a supported version before the content would be able to be displayed. Our 2sxc version at the time of the move is 14.12.3 and was then promptly upgraded to 16.1 when the move to DNN occurred. When the module is upgraded the content does not display, and gives an Authorization error that can be resolved by setting the optimizeCompilations setting in web.config from true to false - which will show the content, but then will not be able to display any of the settings within the admin interface. Uninstalling and then reinstalling does fix, but we lose all of our content within the configured modules. 

Content displays as expected and admin settings function as expected.

The vendor who helped with the migration mentioned that we may need to upgrade 2sxc before completing some of the finishing steps. I am not too familiar with it all but was wondering if anyone had run into a similar issue. 

### Instructions to Reproduce the Problem

If the current behavior is a bug or you can illustrate your feature request better with an example, 
please provide the *STEPS TO REPRODUCE* and/or a *MINIMAL DEMO* like a screenshot or screen cast.
*STEPS TO REPRODUCE* 
Migration from Evoq 9.11->DNN 9.11.01 
2sxc modules are yellowed out with a button that says 'Complete Upgrade Version'
Click the button
Extension is updated, but no content is displayed
Set the optimizeCompilations setting in web.config from true to false
Content Displays
Admin interface does not display

### Your environment

DNN v9.11.01 migrated from Evoq Engage v9.11

2sxc version before Complete Upgrade Version is clicked: 14.12.3
2sxc version after Complete Upgrade Version is clicked: 16.1

2 Webservers running in azure VM on Windows Server 2022

* **Browser:** all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari
* **DNN:**  9.xx.xx
* **Evoq.** 9.xx.xx
* **Hosting platform:** | IIS | azure
* **Language:** any/all | English

**Comment by iJungleboy** [comment]
Hi @zsmithy44 

I don't think we can help based on these infos. I recommend you book 2-4h of support; I'm pretty sure we can help fix this.

https://2sxc.org/en/contact

**Comment by iJungleboy** [comment]
BTW: You could also - to check if it's a version issue - try to upgrade to a newer version.

Otherwise please contact us, as the description above cannot be used to determine if it's a 2sxc issue or something in your installation etc. 

So we'll close this for now; it's probably best if you get direct support.
