### ISSUE TITLE
Feature Request: Keep Older Major Version Documentation Online

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#3163]
### Current Behavior 
Documentation for old versions keeps vanishing. We maintain and modify code (Views) written across the last 5+ years. There is 2sxc code written as early as v9.4x and we had a project recently where we needed to make some changes involving Toolbars. We were unable to find the docs for the old syntax we were using and even though we upgraded 2sxc as far as v13.12.1, we were not willing to invest the time needed to rewrite things in a flavor where the docs were still findable (and also 2 versions behind modern).

### Expected Behavior
Many projects (Bootstrap is a good example) keeps multiple versions of their docs online (examples [v3.4.x](https://getbootstrap.com/docs/3.4/), [v4.6.x](https://docs.2sxc.org/api/dot-net/ToSic.Sxc.Data.IMetadata.html?q=IMetadata), [v5.1.x](https://docs.2sxc.org/api/dot-net/ToSic.Sxc.Data.IMetadata.html?q=IMetadata)).
 
Is there any chance 2sic could - even with NO further maintenance - put back online a version or 2 of the old docs? I realize this might no be possible or easy. But at least add it to your list of things to think about moving forward. The recent difference between Razor14 and RazorTyped (Razor16) certainly warrants a long term Razor14 reference staying online. I could be wrong, but I also think this might save you some work since you seem to put a lot of effort in to keeping the various changes side-by-side. 

Quote from a fellow DNN/2sxc person named Steve: "I have run into the same problem. I've got new code, medium old code and ancient code. Accessing the appropriate documentation is a skill that I'm working on."
 
Anyhow, I hope you consider doing something like the Bootstrap docs. **Thank you in advance for any level of consideration you give this!!**

**Comment by iJungleboy** [comment]
I understand the need for this.

Basically we do work very hard to not remove any old docs, but actually keep mentioning where they are relevant and what not. 

Is there something specific that got "lost"?

Note that if you're really desperate, you can always go to the docs repo [which contain](https://github.com/2sic/2sxc-docs) which contains all the docs ever generated these last ca. 5 years, and turn back the time on the git there. The published docs are always generated into the `docs` folder.

**Comment by iJungleboy** [comment]
I will close this right now, as we won't address it any time soon, and we do invest a lot of energy into keeping the old docs there.

If anybody wants to tackle this feel free to comment below. I would then contact you to discuss how we should proceed.
