### ISSUE TITLE
Replace ImageFlow with permissive licensed module

### ISSUE THREAD

**Issue by rosenzweigv** [2sic/2sxc#3168]
### I'm submitting a
[x] bug report => search github for a similar issue before submitting
[x] not sure

### ...about
[x] DNN parts
[x] other / unknown

### Current Behavior / Expected Behavior
During the install of 2sxc, we were made aware that there is a process to replace the ImageFlow/ImageResizer dependency with a non-copyleft (non-AGPLv3) dependency:

> Everything in 2sxc is free open source :) 2sxc itself is released under the MIT license. It also uses many other open source components with different open-source licenses, from AGPL to X11. If you want to know more, read our [license](http://2sxc.org/License) page. It also contains instructions how to switch from the really cool, copyleft AGPL image resizer to the simpler one with an Apache license. Be sexy - give back to the community or [to those less fortunate](https://www.kiva.org/invitedby/ijungleboy). Contribute your work, support others - share the love.

However, the linked license page does not have any instructions to replace the dependency. Is this no longer possible to do, or is this information available elsewhere?

### Instructions to Reproduce the Problem
1. Install 2sxc
2. Click the link in to the license page during install
3. Observe that the page ends in "read on..." with no more information

### Your environment

* **2sxc version(s):** 16.05.00
* **Browser:** Chrome
* **DNN:** 9.12.00
* **Hosting platform:** IIS
* **Language:** English

**Comment by iJungleboy** [comment]
Good catch :)

To be honest, you're the first person to ask in more than 5 years, so we won't update the docs for now. 

You can always install the older Image Resizer and make sure you deactivate the web.config parts of the new ImageFlow resizer; and you're good to go. As far as I remember you'll also need to disable the disk-cache feature in the web.config.
