### ISSUE TITLE
[Feature Request] Built in editor support for custom CRUD api

### ISSUE THREAD

**Issue by rosenzweigv** [2sic/2sxc#3169]
### I'm submitting a
[x] feature request

### ...about
[x] edit experience / UI
[x] Razor templating
[x] JS development
[x] Content Types or data management
[x] APIs like REST

### Current Behavior / Expected Behavior
Users like their UI to look the same across the board. To accommodate this, we like to use the built-in toolbars/edit UIs of 2sxc as often as possible.

However, in some cases, apps we make are designed to interact with external data/APIs. We would like to be able to use the built in toolbars and editors to allow users to add/edit/delete data from external sources, but running the built in system only allows these editors to write Data of Content-Types.

The desired feature would be to be able to have Content data types whose CRUD functions are able to be written by us similar to the Web API, allowing the built in editor to be used but allowing us to store the data elsewhere/handle external API calls.

### Instructions to Reproduce the Problem
N/A

### Your environment

* **2sxc version(s):** 16.05.00
* **Browser:** Chrome
* **DNN:** 9.12.00
* **Hosting platform:** IIS
* **Language:** English

**Comment by iJungleboy** [comment]
I'm not 100% sure I understand your need, but you can add custom JS code to toolbar buttons. Is this what you're looking for?

**Comment by rosenzweigv** [comment]
I am aware of the custom JS -- through the `code` command, correct?

However, what I'm proposing is allowing the `edit` command to result in a call to some custom C# code on save rather than the normal headless CRUD api.

I guess in other words, this would be content-types that do not get stored by 2sxc, but rather the developer defines the CRUD endpoints for retrieval/drafting/publishing, etc.

In this example, we are creating a 2sxc app to allow our admin users to manage push notifications sent to a mobile application. The goal for the user was to make it appear the same as editing/adding content on other pages, using the same toolbar and dialogues/modals that 2sxc uses for editing content.

**Comment by iJungleboy** [comment]
So I think what you're suggesting is the ability to have custom schema/data providers, where the edit-ui would load data from another source (eg SQL or something super-custom), show the UI, and on save, use that provider again. Is that kind of correct?

**Comment by rosenzweigv** [comment]
Yes, that's correct.

**Comment by iJungleboy** [comment]
That would be quite a huge effort. 
Basically it would need 

1. an abstraction layer for reading and writing data (2-4 weeks of work)
2. an implementation of this layer for SQL (ca. 1 week)
3. Mechanisms to configure a content-type that it's from elsewhere
4. mechanisms so the abstraction layer can limit what it's able to do (eg no versioniong, no ML, etc. as this affects what the UI can do) - ca. 1 week

All in all quite a big lift. A cool technical challenge (drooling already 😉) but resource-intensive. I don't think this will happen any time soon, unless someone volunteers or sponsors.

**Comment by iJungleboy** [comment]
Will close for now, as I don't presume anybody is sponsoring / contributing to this any time soon.
