### ISSUE TITLE
Open graph headers not working in oqtane

### ISSUE THREAD

**Issue by tvatavuk** [2sic/2sxc#3172]
### I'm submitting a
[x] bug report

### ...about
[x] Razor templating
[x] other / unknown

### Current Behavior / Expected Behavior
2sxc BLOG6 app has implemented open graph headers. Open graph headers are visible in DNN but are missing in Oqtane. 

Open graph headers should be in html header of Oqtane also.

The implementation of open graph headers is crucial for any website wanting to share links on social media platforms in a more visual and engaging manner. Having this feature not working limits the capability of Oqtane site to reach a wider audience effectively.

### Your environment

* **2sxc version(s):** 16.05.00  
* **Browser:** all
* **Oqtane:** 4.0.3
* **Hosting platform:** all
* **Language:** any/all

**Comment by iJungleboy** [comment]
thx :)
