### ISSUE TITLE
2sxc Import Error: trying to resolve guids for this relationship, but can't, because the lookupList is not available

### ISSUE THREAD

**Issue by ZacharyCPC** [2sic/2sxc#3176]
### I'm submitting a

[x] support request (submitted a [ticket ](https://stackoverflow.com/questions/77113353/2sxc-import-error-trying-to-resolve-guids-for-this-relationship-but-cant-bec)to StackOverflow, but was told to submit an issue here)
[x] bug report

### ...about

[x] Content Types or data management (import/export)

### Current Behavior / Expected Behavior

I exported several 2sxc entities of a content type called "Series" that I wish to modify and reimport to the same system. I was able to successfully modify the data in Excel and export to a new XML file for reimport. However, when I try importing the data in the XML file, 2sxc throws the following error:

> Had an error talking to the server (status 400).
> Message: Bad Request
> Detail: trying to resolve guids for this relationship, but can't, because the lookupList is not available

After several attempts to modify and adjust the data being imported, I finally tried reimporting a completely unmodified version of one existing entity (in the site's default language). Even that resulted in the error.

I also tried digging into the 2sxc logs, but I was unable to find anything helpful in solving the issue. See the following screenshot which depicts a portion of the save-data log where the error was generated.

![lZWpa](https://github.com/2sic/2sxc/assets/97461952/37d3d79a-bae6-4d9b-917f-fcdc8d437451)

At this point, it doesn't seems like the issue is in my XML file, so what do I need to do so that 2sxc will import my data? Is there something wrong with my 2sxc instance?

### Instructions to Reproduce the Problem

I'm unsure of how one would reproduce this issue in their own environment, but I am willing to provide additional information if requested.

### Your environment

* **2sxc version(s):** 14.11.00  
* **Browser:** all
* **DNN:** 09.11.00
* **Hosting platform:** Rackspace
* **Language:** any/all

**Comment by iJungleboy** [comment]
I just noticed that you're using a fairly old version of 2sxc. Please try it on a new version (updates have been seamless for years now) as we wouldn't invest any resources in such an old release.

**Comment by ZacharyCPC** [comment]
The issue has been identified and resolved. If localized entity relationship fields are imported into 2sxc with any value other than "[]", the import will fail with the above-mentioned error. These fields **must** inherit from the default language for the import to work.

**Comment by iJungleboy** [comment]
thanks for closure
