### ISSUE TITLE
[Feature request]Implement optional checkboxes for multiple items data types

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3179]
### I'm submitting a
[x] feature request

### ...about
[x] Content Types or data management

2sxc currently uses it's own UI to select multiple items in a field, such as entity data type. This allows nice features such as retaining order.
It's also very slow and complex because you need  to enter a new menu to select the items in a dropdown environment, one by one.

One alternative, optional and configurable would be a good old checkboxes. Stored in the exact same way that the string dropdown or entity are.

**Comment by iJungleboy** [comment]
I feel like this could be useful. 

We've been working in the background for a completely new "Picker" infrastructure as we see a lot of things we could improve there. I assume we'll release that in ca. 8 weeks and maybe this could make it as well :).

**Comment by iJungleboy** [comment]
just released v19 which has this new feature ;)
