### ISSUE TITLE
[Feature request]Select the same item more than once in multiple items selection

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3180]
### I'm submitting a
[x] feature request

### ...about
[x] Content Types or data management

When using an entity data type or similar with select multiple items enabled, the ui will forbid selecting the same item more than once. This will fit most uses, but in some cases it can be useful to select the item multiple times. Like selecting steps for a procedure, or instructions for a road path.

**Comment by iJungleboy** [comment]
This is possible using the new `picker` input types in 17.03 :)

Still in beta, but most things such as this work - needs some docs though...
