### ISSUE TITLE
Bug: Exception editing items in DNN subportal with multiple portal aliases

### ISSUE THREAD

**Issue by tvatavuk** [2sic/2sxc#3188]
### I'm submitting a

[x] bug report => search github for a similar issue before submitting

### ...about

[x] edit experience / UI
[x] DNN parts

### Instructions to Reproduce the Problem
In DNN, set up a site with multiple portal aliases, each having different hosts and folder paths (subsites):
1. host1.dnndev.me/subsite1 (not primary)
1. host2.dnndev.me/subsite2 (primary)
Ensure portal alias redirection is set to "none".
Add a Content module to the homepage of host1.dnndev.me/subsite1.
Attempt to edit a content item.

### Expected Result:
Content item should be editable without any issues.

### Actual Result:
An exception is thrown with the following details:

```csharp
{
    "Message": "An error has occurred.",
    "ExceptionMessage": "Object reference not set to an instance of an object.",
    "ExceptionType": "System.NullReferenceException",
    "StackTrace": "   at DotNetNuke.Web.Api.Internal.DnnContextMessageHandler.SetupPortalSettings(HttpRequestMessage request) in D:\\a\\1\\s\\DNN Platform\\DotNetNuke.Web\\Api\\Internal\\DnnContextMessageHandler.cs:line 41\r\n   at DotNetNuke.Web.Api.Internal.DnnContextMessageHandler.ProcessRequest(HttpRequestMessage request, CancellationToken cancellationToken) in D:\\a\\1\\s\\DNN Platform\\DotNetNuke.Web\\Api\\Internal\\DnnContextMessageHandler.cs:line 24\r\n   at System.Net.Http.MessageProcessingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"
}
```
### Additional Notes:

The issue seems to be originating from the DnnContextMessageHandler class in the DNN Platform.

### Your environment

* **2sxc version(s):** 16.07.0  
* **Browser:** all
* **DNN:** all | 9.6.1 | 9.13.0
* **Hosting platform:** IIS
* **Language:** any/all

**Comment by tvatavuk** [comment]
Method [GetSiteRoot](https://github.com/2sic/2sxc/blob/fe61a3600b5521030b46a84edc8e2d9af1c823d9/Src/Dnn/ToSic.Sxc.Dnn/dist/CachedPageBase.cs#L72) in **CachedPageBase.cs** returns wrong value.

**Comment by iJungleboy** [comment]
@tvatavuk I think the solution is risky. eg if the alias has a different casing it will probably fail, and if something else causes trouble it should IMHO just take the first one - otherwise we run the risk of it failing for unexpected reasons.

What do you think? or maybe just for safety reason add a fallback?

**Comment by tvatavuk** [comment]
Thx, your concern about the alias casing and unexpected issues is valid 👌. 
Just updated code to be more fault-tolerant, with case insensitive string comparison and multiple fallbacks.

**Comment by iJungleboy** [comment]
thx.
