### ISSUE TITLE
Feat: Stable Field/Attribute Identifier which doesn't change on field rename

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#3196]
### I'm submitting a

[x] feature request

### ...about

[x] Content Types or data management

### Current Behavior / Challenges

Entities have Attributes such as `FirstName` or `Tags`. These are identified by their string name. When stored in the DB the data integrity is ensured through IDs. When exported to JSON the name is used as a reference. 

This works for most scenarios, but lacks in the following cases:

1. If a entity was edited, the history JSON uses the name. Now if the field is renamed, it's not possible to restore the value as the names have changed.
2. If entities are stored in the file system as JSON, and the underlying (json based) type would rename the field, the reference would also fail. This is a fairly advanced, untypical scenario, but it restricts us from renaming fields which change their purpose over time.
3. A future feature #3192 would require very stable references to other field definitions, where renames could cause a lot of trouble.

### Expected Behavior

We should define a stable field identifier such as a GUID which doesn't change on rename. 
This could then be used for such "long term references" instead of the string-name, which may change.

### Steps to implement

* [x] Extend the in-memory attribute definitions to have a `Guid` as well as further `SysSettings` similar to Apps @iJungleboy 
* [x] Ensure that import/export of content-types and attribute definitions to JSON preserve this @iJungleboy 
* [x] Extend DB table `ToSIC_EAV_Attributes` with `Guid` _nullable_ and `SysSettings` _nvarchar(max), nullable_ @tvatavuk 
* [x] Extend DB table `ToSIC_EAV_AttributeSets` with `SysSettings` _nvarchar(max), nullable_ for future features @tvatavuk 
* [x] Extend Entity Framework Model with these new fields @tvatavuk 
* [x] Improve data loading from SQL to load this information into memory (but not do anything with it yet) @tvatavuk 
* [x] Include `AttributeMap` on IEntity JSON for all attributes with GUIDs @iJungleboy 
* [ ] Implement restore-from-history/import despite renamed fields @tvatavuk 
* [x] Continue on shared-field config scenario @iJungleboy 
* [x] plan next steps @iJungleboy 

### Your environment

* **2sxc version(s):** 16.07

**Comment by tvatavuk** [comment]
https://github.com/2sic/eav-server/commit/b68a74
