### ISSUE TITLE
Experimental: Ability to modify raw HTML before using ICmsService.Html(...)

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#3197]
### I'm submitting a

[x] feature request

### ...about

[x] Razor templating

### Current Behavior / Expected Behavior

ATM you can do things such as `item.Html("FieldName")` which will generate a best-possible HTML. 

But there are rare cases where you must change the HTML first which is in that field, for example to replace placeholders. 
We're not yet sure about the API, as there are various options

* ability to modify a field (or create a new one to remain functional) - but then use the `ICmsService`
* option to provide another value in the call, eg `.Html("FieldName", contents: "...")`
* option to provide a callback for modification eg `.Html("FieldName", modify: (orig) => orig.Replace("...", "..."))`
* option to provide a more complex / generic pre-/post-processing object

We're not yet sure how to do this, so for now we'll run some experiments on internal APIs and the re-eval later on.

### Your environment

* **2sxc version(s):** 16.07 LTS

**Comment by iJungleboy** [comment]
prototype created, not sure how important this is so for now we'll close this to not fill up the issues-list with experimental features which are not complete.

**Comment by jeremy-farrance** [comment]
If the performance was good, this would be a great addition. We have a few different situations where output either needs to conditionally switch templates and/or replace tokens. The 3rd syntax above seems promising. :) I'd love to see this type of thing as a consistent option. Maybe follow the same pattern(s) as tweak: on the ToolbarButtons so more features could be added in the future?
