### ISSUE TITLE
Minified file not actually minified: dist/inpage/inpage.min.js

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#3200]
### I'm submitting a 
[x] (somewhat trivial) bug report 

### ...about
[x] edit experience / UI
[x] admin experience UI

### Current Behavior / Expected Behavior
This file `inpage.min.js` started bogging down (disk-read) performance on our server on an Intranet project**. We were suprised the file was so large and noticed that even though the file has ".min." in it, it was not minified. So, shouldn't it be? Maybe its worth checking something in your build for release process? It over 3/4s of a MB as is (in v16.07.00).

**  because we unnecessarily had Kit.Page.Activate("2sxc.something") happening on a page with a custom form (Activate was needed for editors, but not all users). Fixed it so it only loaded when needed AND got it to cache (it wasn't).
 
![image](https://github.com/2sic/2sxc/assets/653301/b8c362b6-c3a2-4cbf-a0a8-f77968dcf6c6)

### Your environment
* **2sxc version(s):** 16.06.00
* **Browser:** all/any
* **DNN:** all | 9.13.00 | 9.11.02
* **Hosting platform:** IIS
* **Language:** any/all

**Comment by iJungleboy** [comment]
I can confirm this issue.
@tvatavuk could you check / fix?
