### ISSUE TITLE
Installing 7.2.2 from scratch misses the DataPipeline Attributes

### ISSUE THREAD

**Issue by mrdotnet** [2sic/2sxc#322]
When installing version 7.2.2. the entries needed in the AttributeSets for the DataPipeline don't get created. The problem is manifested in a few ways: installing an app will return an error saying the AttributeSet was not found and the visual query designer fails to lauch.
A bit of investigation shows that those entries are created during an upgrade from version 6 but apparently nowhere else. 
Installing version 6 first and the doing the upgrade solves the problem but clearly the installer process for version 7.2.2 needs to ensure the DataPipeline attribute sets get configured.

**Comment by iJungleboy** [comment]
Thanks - we'll look into it...

**Comment by iJungleboy** [comment]
Verified. This bug was introduced in 7.2.2 - previous version worked. But we changed install in 7.2.2. We'll try to release a fix tomorrow.

**Comment by raphael-m** [comment]
Fixed in 7.2.3. An upgrade from 7.2.2 to 7.2.3 will create the missing content types.
