### ISSUE TITLE
Support for a Character Count on Text Inputs

### ISSUE THREAD

**Issue by mitchelsellers** [2sic/2sxc#3223]
### I'm submitting a
[x] feature request

### ...about
[x] edit experience / UI
[x] Content Types or data management

### Business Use Case

When constructing an object I may want to suggest to the user a preferred length of content.  While users are editing information it would be valuable for them to see a total number of characters that they have typed.

A use case for this is allowing users to supply metadata fields such as descriptions or otherwise where there is a suggested length in characters.  It is only a suggestion so we cannot use the RegEx or other option to limit this as we don't want to step them, just give them a visual reminder combined with the field information to tell them how we SUGGEST they fill out the data element.

I don't believe this is needed or possible for the Rich Text fields only standard text fields.

**Comment by iJungleboy** [comment]
This can already be done using a formula.

Create a formula for the validation and return a `warning`. This will show on the field in a less aggressive color, and still allow saving. 

https://docs.2sxc.org/js-code/edit-form/formulas/targets-and-return.html#formulas-for-validation
