### ISSUE TITLE
After Upgrade to v17.01.00, Kit.Toolbar throws error in previously working Razor14 code

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#3256]
### I'm submitting a
[x] bug report 

### ...about
[x] Razor templating
[x] other / unknown

### Current Behavior 
After upgrading from 16.09 to 17.01 the following code stopped working and I do not understand why.

Here is the error, code in my View is below.
```
Error: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'ToSic.Razor.Markup.RawHtmlString' does not contain 
a definition for 'Edit' at CallSite.Target(Closure , CallSite , Object , Object , <>f__AnonymousType0`2 ) at 
ASP._Page_Portals_0_2sxc_AccuTrack__Backup__List__basic_cshtml.Execute() in 
C:\HostingSpaces\ ... \www\Portals\0\2sxc\AccuTrack\_Backup__List--basic.cshtml🎯:line 130 at 
System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at 
System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, 
WebPageRenderingBase startPage) at ToSic.Sxc.Dnn.Razor.DnnRazorEngine.Render(RazorComponentBase page, TextWriter writer, 
Object data) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Dnn\Razor\DnnRazorEngine.cs:line 103
```
The code, note that Line 130 is `@(Kit.Toolbar.Empty()`:
```
@inherits Custom.Hybrid.Razor14
...
    @foreach(var bu in AsList(App.Data["Backup"]))
    {
      string expireDate = bu.Expiration == null ? "" : bu.Expiration.ToString("d");
      <tr>
        @* if we have a project, show it, otherwise, show the client *@
        @if(bu.Project.EntityId > 0)
        {
          <td title="@bu.Project.Description, @bu.Project.Notes [EntityId: @bu.Project.EntityId]"
130:        @(Kit.Toolbar.Empty()
              .Edit(bu, ui: new { color = "DarkBlue", title = "Edit Backup" })
              .Edit(bu.Project, ui: new { color = "Purple", title = "Edit Project" })
              .Edit(bu.Client, ui: new { color = "DarkGray", title = "Edit Client" })
              .Code("openLink"
                , ui: new { color = "black,white", icon = "fa-brands fa-github", title=$"Open GitHub link, '{bu.Project.GitHub}'" }
                , parameters: new { link = $"{bu.Project.GitHub}" }
              )
              .Code("openLink"
                , ui: new { color = "gray,white", icon = "fa-duotone fa-arrow-up-right-from-square", title=$"Open Project link, '{bu.Project.DomainAlias}'" }
                , parameters: new { link = $"https://{bu.Project.DomainAlias}" }
              )
            )
          >
            @bu.Project.Name
          </td>
        }
        else
        {
          <td title="@bu.Client.Name @(Text.Has(bu.Client.Notes) ? $"- {bu.Client.Notes}" : "") [EntityId: @bu.Client.EntityId]"
```

### Expected Behavior
After upgrading Razor14 based code that worked, should continue working.

Kit.Toolbar is IToolbarService interface which has a method .Empty(), which returns an IToolbarBuilder which has a method .Edit(). So why is the error saying `RawHtmlString` does not have a .Edit()?

### Your environment
* **2sxc version(s):** v17.01.00 upgraded from 16.09.00
* **Browser:** all/any
* **DNN: v9.13.02
* **Hosting platform:** IIS
* **Language:** any/all

**Comment by iJungleboy** [comment]
Thanks.
This is a side effect of us hardening internal APIs. 
Just solved it.
I'll release a patch today.

**Comment by jeremy-farrance** [comment]
Any chance this one is related and possibly fixed by the type of recent fixes you've been doing in situations like this? 

#3234

**Comment by jeremy-farrance** [comment]
I found another very similar example, fluent Toolbar worked before:
```
@Kit.Toolbar.Default(link).Layout("-")
```
Error after upgrading to v17.01, manually fixed it like this
```
@Kit.Toolbar.Default().Layout("-").For(link)
```

Can you confirm its the same issue and fixed? Also, both syntaxes should work, right?

**Comment by iJungleboy** [comment]
Yes, the Toolbar Builder was affected too. Should be fixed in release in the next few minutes ;)

**Comment by jeremy-farrance** [comment]
Working again, thanks for the quick turnaround on 17.01.01!
![image](https://github.com/2sic/2sxc/assets/653301/d7376802-a916-461c-9ae0-e4793e0d82ce)

**Comment by iJungleboy** [comment]
thx for closure ;)
