### ISSUE TITLE
Images Display Differently (Zoomed) After Upgrading to 2sxc v17.x (thru v17.1.3)

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#3268]
### I'm submitting a
[x] bug report

### ...about
[x] other / unknown?

Seems to be an issue between the Settings stack(s), recipes, and .Img() or .Picture() methods.

Note: this is not a problem with the Slider app, we've seen this affect in multiple apps, but not all cases. But I felt this example provided the most complete and repeatable example.

### Expected Behavior Prior to v17
With these settings (see image below) and each slide/image set to all defaults, images (screenshots from a mobile phone; full screen default portrait); things worked as expected.
![image](https://github.com/2sic/2sxc/assets/653301/a24f42d0-87d9-444e-a366-016a829db827)

### Current Behavior
After installing v17.0.0 (and upgrading through v17.1.3), the images immediately (on next page load) end up zoomed. In the example below, the originals are fairly large, so its an extreme change:
![image](https://github.com/2sic/2sxc/assets/653301/b9f32952-320c-4a3e-a8d8-03461311a2a6)

Another clue is the "work-around". You can fix this by going to each slide/image (all 4 in our case), Image Settings, and changing the Image Cropping/Crop Behavior from Default Crop (default) to Don't Crop:
![image](https://github.com/2sic/2sxc/assets/653301/e9e31c69-ba5c-41f8-b91b-4fa1be5dfc4b)

### Instructions to Reproduce the Problem

Using the Slider/Swiper app on 2sxc, any version prior to v17, take 4 different screen shots with your phone. Setup the app as you see above with the Effect: Cube - Default. 300px default and then look up your phone's default aspect ratio (mine was 9:20). Add the 4 screen shots. Once its working as expected, upgrade to 2sxc to v17.1.3. Come back to your cube rotator and the images will now be zoomed.

### Your environment
* **2sxc version(s):** 17.0.0 through 17.1.3
* **Browser:** all/any
* **DNN:** 9.13.02 (but I assume all/any)
* **Hosting platform:** IIS on Windows Server 2022 or Windows 11
* **Language:** any/all

**Comment by iJungleboy** [comment]
ATM I can't reproduce.

If I add an image which is just too large, it scales correctly without making any settings/changes. 

Could you give me another example / instructions or a sample picture which would fail?

**Comment by jeremy-farrance** [comment]
Sorry, I thought I responded to this already. If you think it might be something with the images themselves, you can find them here; https://accuraty.com/services/mobile-app-development/central-illinois
  
I'll see if I can come up with a way to reproduce with steps and specific versions. Thanks!

**Comment by iJungleboy** [comment]
Could you give me the resize-url before you made manual changes to the image settings? (eg undo the setting, reload, etc.)

Because I still can't see how an upgrade would change things, so I would like to see the generated url.

**Comment by jeremy-farrance** [comment]
Okay, I see how that might help, first here is the corrected one with Cropping set to Don't Crop (not zoomed)
```
<picture sxc-toolbar="[&quot;toolbar=empty&quot;, ... ... Q==?entityId=1665&quot;]" data-2sxc-tagtoolbar="true" sxc-toolbar-hover="" data-tagtoolbar="468-468-26">
  <source type="image/png" srcset="/Portals/0/adam/Swiper2/5Jd5eoZiIU-Y_L7U6mrpGw/Image/MicrosoftTeams-image.png?w=630&amp;quality=75&amp;mode=max&amp;scale=both">
  <img src="/Portals/0/adam/Swiper2/5Jd5eoZiIU-Y_L7U6mrpGw/Image/MicrosoftTeams-image.png?w=630&amp;quality=75&amp;mode=max&amp;scale=both" loading="lazy" alt="" class="img-fluid" width="630">
</picture>
```

And here is the same image with Default Cropping (zoomed now, but was not before v17)
```
<picture sxc-toolbar="[&quot;toolbar=empty&quot;, ... ... Q==?entityId=1665&quot;]" data-2sxc-tagtoolbar="true" sxc-toolbar-hover="" data-tagtoolbar="468-468-31">
  <source type="image/png" srcset="/Portals/0/adam/Swiper2/5Jd5eoZiIU-Y_L7U6mrpGw/Image/MicrosoftTeams-image.png?w=630&amp;h=389&amp;quality=75&amp;mode=crop&amp;scale=both">
  <img src="/Portals/0/adam/Swiper2/5Jd5eoZiIU-Y_L7U6mrpGw/Image/MicrosoftTeams-image.png?w=630&amp;h=389&amp;quality=75&amp;mode=crop&amp;scale=both" loading="lazy" alt="" class="img-fluid" width="630"></picture>
```

**Comment by jeremy-farrance** [comment]
I have not had this happen again and can no longer reproduce.
