### ISSUE TITLE
v17 - Entity data type with multiple items hide the title after 3 items in the form

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3269]
### I'm submitting a
[x] bug report 

### ...about
[x] Content Types or data management

### Current Behavior / Expected Behavior
This is kind of hard to explain with text, but easy with a couple images.
If you set an entity data type with multiple items, the form used to show them all until there was no room on the line.
Now it shows 3 and stops.

![image](https://github.com/2sic/2sxc/assets/26518879/f3ae1951-d34a-403c-a501-1890c65dba98)

### Your environment
* **2sxc version(s):** 17

**Comment by iJungleboy** [comment]
thx, @DujeVatavuk is working on it

**Comment by iJungleboy** [comment]
should be fixed in 17.01.05
