### ISSUE TITLE
v17 - Content App: WYSIWYG Link a Page from the Current Site Broken

### ISSUE THREAD

**Issue by bmusgrove-accuraty** [2sic/2sxc#3276]
### I'm submitting a
[x] bug report

### ...about
[x] edit experience / UI

### Current Behavior / Expected Behavior
On 2sxc version 17, when using the WYSIWYG editor field, the Link tool dropdown "Link a page from the current site" does not display the list of pages from the website. 

On 2sxc version 16, the WYSIWYG editor field link dropdown does provide all the parent and child pages from the entire website.

### Instructions to Reproduce the Problem
Version 16.9.0 - working example

1. Add Content App module to the page
2. Choose Basic Content and select any default view
3. In the Text WYSIWYG field, add some lorem ipsum and highlight a word to link it to another page on the website
4. Click on the Link's chevron dropdown and select the Link a page from the current site option
5. This will bring up a pop-up with a full list of the pages on the website, select one
6. Save

![chrome_7ahuHQZPwl](https://github.com/2sic/2sxc/assets/68243808/63bdc7d9-bede-4f81-8785-3f308338e364)

_____________

Version 17.1.4 - broken example
1. Repeat steps 1-4 above
2. The pop-up that appears is blank and does not provide the list of pages on the website. The search also does not acknowledge the full list of pages.

![chrome_EKRsjBOYnC](https://github.com/2sic/2sxc/assets/68243808/c6129065-017d-40e9-8834-0ce235bbcd71)

### Your environment

* **2sxc version(s):** 17.1.4
* **Browser:** Chrome 121 | Firefox 122.0 | maybe all?
* **DNN:** 09.13.02
* **Hosting platform:** IIS
* **Language:** English

**Comment by iJungleboy** [comment]
Great catch!

The bug was just introduced in v17.01.04 because of a url param.

FYI @DujeVatavuk 

Fixed in 17.01.05
