### ISSUE TITLE
Edit Template in Dnn Action Menu No Longer Works in v17+

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#3280]
### I'm submitting a
[x] bug report 

### ...about
[x] edit experience / UI
[x] admin experience UI

### Current Behavior 
When you try to use the DNN Action menus dropdown list for the Edit Template command, it doesn't work. Just installed and tested this on v17.1.5 and confirmed its still not working.

[Here is a video](https://github.com/2sic/2sxc/assets/653301/e85fde68-df02-40f7-be40-0b788566fdb2), when hovering on the Edit Template option, I am click a few times. As you can see, the Admin option works. And you can still get to Edit Template from the Toolbar buttons.

Also, when you click on Edit Template, the following output appears in the console:
![image](https://github.com/2sic/2sxc/assets/653301/f8dc1f65-10a3-4b96-9bb9-ea9872f8cc35)

Also-also, pressing Ctrl-Click or Shift-Click doesn't work either (but does on the Toolbar button).
 
### Expected Behavior
It should work like it used to and open the template for editing in a new tab. Just a guess, but it probably started when the Ctrl- and Shift- click options were added (to open in new window).

### Instructions to Reproduce the Problem
Happens in all apps, including the Content App.

### Your environment
* **2sxc version(s):** v17. thru v17.1.5
* **Browser:** all/any
* **DNN:** v9.13.02
* **Hosting platform:** IIS
* **Language:** any/all

**Comment by bmusgrove-accuraty** [comment]
I tested on a project that is still on version 16.9.0 and the dropdown > Edit Template is working.
