### ISSUE TITLE
In multi-selection fields, sometimes the options show the guid instead of the title

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3296]
### I'm submitting a
[x] bug report 

### ...about
[x] Content Types or data management

### Current Behavior / Expected Behavior
When I use an entity data type to link another field, and I create a new item in that entity using the sub-form, sometimes the item Title is replaced by the guid, and the edit icon goes missing.
Returning to the main form does not fix this. Closing the main form and reentering does fix it.

This seems completely random. Also happens after editing an item.

After I create the item
![image](https://github.com/2sic/2sxc/assets/26518879/5284b0f6-7634-4e52-8a4c-239a438c72d0)

After I close and reopen all forms
![image](https://github.com/2sic/2sxc/assets/26518879/4577257e-1cfd-46fc-8826-84d19e444cae)

* **2sxc version(s):** 17

**Comment by iJungleboy** [comment]
should be fixed in 17.03
