### ISSUE TITLE
DNN V. 07.04.02(beta) - 2sxc 07.02.03 (Visual Query Designer)

### ISSUE THREAD

**Issue by S-Staab** [2sic/2sxc#331]
Fresh install of DNN 7.4.2 (beta)
Install 2sxc 7.2.3
Create content type 
Add sample values
Create a template 
Create a new pipeline
________________________________
So far, no problems
________________________________

but if you open your pipeline and create ne new data source, it's not configurable

![example](https://cloud.githubusercontent.com/assets/14276625/9898587/b089b5e2-5c53-11e5-80b6-8f44d297d9d5.png)

The same process with the versions  DNN 7.4.0 / 2sxc 7.2.3 and it works.

In the "nitghtly Version  07.04.02  " , the Bug is fix. 
Thanks

**Comment by iJungleboy** [comment]
Yes, very sorry. Bug in dnn 741 - same as #258
