### ISSUE TITLE
Content: Import Export xml does not work

### ISSUE THREAD

**Issue by ech01** [2sic/2sxc#332]
1. Create a content type and view/template
2. Export the xml
3. Import xml on another instance

No error in event log. Hope that helps

![image](https://cloud.githubusercontent.com/assets/3790873/9914770/1921906e-5c79-11e5-966a-65931d2ba53d.png)

![image](https://cloud.githubusercontent.com/assets/3790873/9914777/20d9f544-5c79-11e5-8013-e89d2346f643.png)

**Comment by ech01** [comment]
Choosing the partial export seems to work.

**Comment by iJungleboy** [comment]
How is the status on this in the newest 2sxc?

**Comment by iJungleboy** [comment]
Stale - close for now. Please reopen if still an issue...
