### ISSUE TITLE
Trojan: Wacatac.B!ml

### ISSUE THREAD

**Issue by BGillham** [2sic/2sxc#3326]
### I'm submitting a Security Issue...
Microsoft Defender reports a Trojan: Wacatac.B!ml in the Source of thisBuild!

**Comment by iJungleboy** [comment]
@BGillham Never had this, and I'm pretty sure it's a false positive.

Can you give me more details as to where it found it? was it a zip download, or is it supposed to be in the source code?

**Comment by BGillham** [comment]
It was not in the Install Zip but it was found in the 17.03 Source Zip

**Comment by iJungleboy** [comment]
I just found out that `!ml` seems to be a shorthand for machine-learning. 

So I guess MS is trying to detect viruses using some guesswork. Pls try to find a way to submit for review. thanks!

**Comment by BGillham** [comment]
I suggest you look at the Source Zip File and submit the file for analysis...

**Comment by iJungleboy** [comment]
@BGillham we did look at it - meaning we let another AV check it and no problems detected. 

I remember a similar problem about 4-5 years back, then the user just submitted it for review and then it somehow got whitelisted...

We can't submit it to defender, as we're not using the product which raised the alarm. So please help and submit it through defender - however that is done.

**Comment by BGillham** [comment]
This is what I found...
https://answers.microsoft.com/en-us/windows/forum/all/how-can-i-know-if-wacatacbml-is-a-false-positive/33107e01-d390-4579-aa94-625a3402d26a

**Comment by iJungleboy** [comment]
I think we should backlog this for now - unless others report the same problem - and await the next release.

My guess is whatever was in the source that triggered the detection will be sufficiently different that it won't trigger again.

**Comment by skarpik** [comment]
I downloaded 2sxc-17.04.00.zip and checked it with Defender. Nothing found. Completely clean.
<img width="599" alt="Screenshot 2024-03-19 021543" src="https://github.com/2sic/2sxc/assets/3846223/6f7ec410-3792-4547-97d4-29c0459e23cd">

**Comment by iJungleboy** [comment]
@skarpik thanks! Glad to hear this.

So either MS fixed the false positive, or the Defender on @BGillham is doing something unique, which doesn't affect other users. 

I'll close this for now, thanks ya'll
