### ISSUE TITLE
Improve dropdown string fields text management

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3332]
### I'm submitting a
[x] bug report => search github for a similar issue before submitting
[x] feature request

### ...about
[x] edit experience / UI
[x] Content Types or data management

### Current Behavior / Expected Behavior
![image](https://github.com/2sic/2sxc/assets/26518879/7da6a7b3-2aa1-4a8a-a9e8-5564958027bf)

1st issue: Dropdown string fields have terrible text management, as shown in the image above.
2nd issue: When you switch to free text mode, there is no line height configuration, so you are left with one line. Could you implement the same line count management from the simple string fields?
3rd issue: If the text exceeds 1 line and a half, it will be left out. Could you adjust the line height in dropdown fields to always show all the text needed? In the example bellow it only shows half.
![image](https://github.com/2sic/2sxc/assets/26518879/9046cf52-e452-4b9a-a12f-1f2d4e744dd0)

### Your environment
* **2sxc version(s):** 17

**Comment by iJungleboy** [comment]
I believe this is fixed in 18.01
