### ISSUE TITLE
Problem with App creation template (2sxc v17.05.00)

### ISSUE THREAD

**Issue by skarpik** [2sic/2sxc#3336]
### I'm submitting a

[x] bug report => search github for a similar issue before submitting

### ...about

[x] admin experience UI

### Current Behavior / Expected Behavior

Creating a new App with the "App Template Empty with some instructions" creates spurious data in the new app.

The newly created App should have no data associated with it (this was the case in v17.04.00).

There appears to be a bug in the App creation routine (for empty App creation). I have not tested the "naked" app option or the "example app".

Screen Shot of App creation:

<img width="519" alt="Screenshot 2024-03-27 235411" src="https://github.com/2sic/2sxc/assets/3846223/e9363d0b-ac5b-4c20-8d01-198f8ec5d9d8">

Spurious created data:

<img width="981" alt="Screenshot 2024-03-27 235616" src="https://github.com/2sic/2sxc/assets/3846223/9f8d7703-d9fb-4fc0-81e4-a6ce8ae2618e">

### Instructions to Reproduce the Problem

- created DNN v9.13.3 instance
- installed 2sxc 17.05.00
- created one page with 2SXC content
- created one page with Image Gallery
- create a new app called Awards (which has data in it that should not exist)

I ran though the same steps in v17.04.00 and got an empty app (as expected):

<img width="1056" alt="Screenshot 2024-03-28 001045" src="https://github.com/2sic/2sxc/assets/3846223/4bc88562-1e2c-40ea-a546-ab605fb4ca9c">

### Your environment

* **2sxc version(s):** 17.05.00 
* **Browser:** all 
* **DNN:** 9.13.3
* **Hosting platform:** IIS
* **Language:** English

**Comment by iJungleboy** [comment]
Actually it's a different bug - but it will be fixed today.

The app is empty, but if you access it through another app (eg. start on app "Content" but go through all-apps, then open the second app, it shows the data of "Content")
