### ISSUE TITLE
Pipeline editor unavailable

### ISSUE THREAD

**Issue by ech01** [2sic/2sxc#334]
I installed the employee directory app, made some modifications, and when I go to the pipeline editor to change the sort order of the listing, the pipeline editor is not present (or the page is blank)

I tried this on a 7.4.1 website, results = blank. 
On a 7.3.4, error that AppId is missing, though it is clearly in the URL.

Is there an easy way to change this query sort order without the visual data tool?

**Comment by ech01** [comment]
I was able to load the query editor by passing in a skin parameter in the url. Could be an issue on my end. 

However, the editor doesn't seem to "do" anything. Cannot change the sort condition.

**Comment by iJungleboy** [comment]
@ech01 I'm guessing it's the url issue because nobody else reported it. 

If not, it's probably JS. could you if you get a js error?
We should release a beta of 2sxc 7.3 where so much changed (refactoring) that we we'll focus on fixes on this branch. Care to help us test in a few days?

**Comment by iJungleboy** [comment]
@ech01 we just released 7.3 beta which works without asp.net and probably fixes most bugs. wanna give it a try? I'll close this for now.

**Comment by ech01** [comment]
Where can one find this beta?

**Comment by iJungleboy** [comment]
https://github.com/2sic/2sxc/releases
