### ISSUE TITLE
Configure app specific / not instance specific

### ISSUE THREAD

**Issue by S-Staab** [2sic/2sxc#335]
Is it possible configure "app instance" specific configurations/parameters, i.e. each time the app is placed on a page new parameters can be configured. 

I know your "App config" concept but this seems to be app specific and not instance specific. 

In other words: 
All instances of the app share the same configuration which does not meet our requirements. 
In simple terms, we would like to configure the number of items the app should show each time we use the app. On one page the app should show 10 items, on another page only 5 items should be shown.

**Comment by iJungleboy** [comment]
Yes, this is very simple to do and has always worked :). 

The config is usually in the list "header" or the list "presentation" settings. Check those out :)

**Comment by S-Staab** [comment]
Thanks for your fast answer.
Can you show me an example?

**Comment by iJungleboy** [comment]
Sure - check out the timelinejs app - it has settings related to start-date, zoom-adjust etc. which are "module level" - http://2sxc.org/en/Apps/Details?AppGuid=58c02a22-9e89-42c0-a2d7-7cd8db105de5

**Comment by S-Staab** [comment]
Oh yes ok thanks.
Only one question to your example. 

The command:   $2sxc($attrs.moduleid).data.on('load', function (source, data) {
                           var content = data.in.Default.List;

are bulid in Js.

I have an controller in c# Just as in ather examples.
 
How are these command:
$2sxc($attrs.moduleid).data.on('load', function (source, data) {
                           var content = data.in.Default.List; 

in c# ?

**Comment by iJungleboy** [comment]
I'm confused. 

Typically you would do something like var list = Data["Default"]. But server is much simpler than JS, so I'm not sure why you're starting with a JS-code sample....

Maybe you could re-explain what you're trying to do.

**Comment by S-Staab** [comment]
I would like to access the contents from the tool bar with my controller.
Now I search the order in addition.

Example: 
var "ContantFromToolbar" = Dnn.Module.ModuleId.Toolbar;     (or words to that effect)
Sorry my English is not so good. 
Like in German.

Ich hab eine App gebaut die mir Daten aus einer Liste von Inhalten Filtern soll, 
in meiner Toolbar in der App selbst, 
möchte ich nun über einen „Content“ Filtern können.
Im Backend läuft die Filterung über einen Controller der auf C# Aufbaut. 
Ich versuche wie in deinem Beispiel nun auf die Variable der Toolbar zuzugreifen um diese in meinen Controller zum Filtern nutzen zu können. 

In JS. ist mir das durch dein Beispiel gelungen (mit dem Befehl siehe oben), aber den Befehl in c# kenne ich nicht.

In der Praxis: 
Später soll ein Admin, meine App auf seine Seite ziehen(und auf Unterseiten), in der Toolbar einen Parameter angeben und die App Filtert alle Inhalte nach genau diesem in der Toolbar eingegebenen Parameter.
Da der Parameter sich in einer neuen Instance nicht verändert, muss ich diesen Nutzen. Auch wenn mein erster Lösungsansatz über die „App Settings“ ging, dann aber leider nur für eine Instanz, sonst würde man auf jeder Seite denselben Inhalt sehen.

**Comment by S-Staab** [comment]
Hallo, 
Ok über list = Data["Default"] bekomme ich meine Werte, diese sind aber nun da in der Instanz die Tabelle "Default" heißt nicht mehr von der ModulId abhängig und damit für mehrere Seiten gleichzeitig nicht zu gebrauchen. 
Kann ich dies durch ein zusätzliches Statement erreichen ?

**Comment by iJungleboy** [comment]
Hallo S-Staab

Ich verstehe immer noch nicht, was du versuchst zu erreichen - da deine Frage sehr vieles annimmt, dass vieles schon stimmt und nur noch ein Detail fehlt. Ich kann dir daher nur beschränkt helfen. Falls deine Frage aber ist, wie kriege ich alle vom Typ X dann...

var list = AsDynamic( App.Data["Person"] ); // this gets everything of the type person
