### ISSUE TITLE
v7.3.0 appId error

### ISSUE THREAD

**Issue by oellph** [2sic/2sxc#337]
Hi,

Just trying v7.3.0 beta, on a fresh install and also an upgrade from v7.2 and when trying to edit a new or existing app, I'm getting this error:

![image](https://cloud.githubusercontent.com/assets/5494863/10341326/28fdab6e-6d0c-11e5-884d-511cb705cc50.png)

The link which generates this is missing the appid: http://localhost/desktopmodules/2sxc/api/app/system/dialogsettings?appId=

**Comment by iJungleboy** [comment]
Reason is that you don't have an app installed yet - install one, and it will work. 
Bug already fixed in Beta 2 (next Monday)
