### ISSUE TITLE
"You do not have permission to view this directory or page." when trying to edit or admin 2sxc in any way

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#3447]
### I'm submitting a

[x] bug report
[x] not sure (might be environmental issue)

### ...about
[x] edit experience / UI
[x] admin experience UI
[x] other / unknown

### Current Behavior / Expected Behavior

When a content editor or administrator goes to edit an item by clicking on the Edit icon, or goes to the Module Actions, and then clicks "Apps Management", we see an error overlaying the page: "You do not have permission to view this directory or page."

![Screenshot 2024-07-29 at 9 34 09 AM](https://github.com/user-attachments/assets/64021a2e-a1ee-4eb6-9e3a-b67a9bcf8c61)

This is the error we see in the Console:

![Screenshot 2024-07-29 at 9 34 57 AM](https://github.com/user-attachments/assets/167de055-83d9-4cfe-b965-5dca0f6562e1)

It points to this file for the edit:

"/desktopmodules/tosic_sexycontent/dist/ng-edit/?pageId=21&sxcver=18.0.0.1722019009&portalId=0"

And this file for when you click on Apps Management:

/desktopmodules/tosic_sexycontent/dist/ng-edit/?pageId=21&sxcver=18.0.0.1722019009&portalId=0 403 (Forbidden)

It's on Azure. We had this issue back when we first installed DNN and 2sxc. At the time, the versions were 9.12 and 16.1.0. I'm not sure how it was resolved but it eventually was fixed by someone else on my team but we can't recall what the solution was. It's been fine for about 10 months but now the issue is appearing again on the staging site. We upgraded to DNN 9.13.2 and 2sxc 18.0.0 and the issue is there.

### Instructions to Reproduce the Problem
I'm not sure you can reproduce as it seems to be an environmental issue and has spanned across DNN versions and 2sxc versions. We've tried clearing cache and restarting and it doesn't have any effect.

### Your environment
Azure

* **2sxc version(s):** 18.0.0 (previously 16 as well)
* **Browser:** all 
* **DNN:** all | 9.13.02
* **Hosting platform:** azure
* **Language:** any/all | English

**Comment by iJungleboy** [comment]
I can't contribute much to this since we don't actively use azure (too expensive, too many surprises, too many changing parts).

But I would be grateful if you document the solution once found. 

I'm pretty sure it's not a 2sxc issue, but most likely a firewall "protecting" the you. I guess it may help if you could post the entire HTTP response as it probably says which subsystem is blocking the request.

**Comment by iJungleboy** [comment]
I'm going to close this as it's 3 weeks old and I assume you've figured it out in the mean time.
