### ISSUE TITLE
Admin Edit UI shows wrong values in Multilanguage

### ISSUE THREAD

**Issue by ropalko** [2sic/2sxc#3450]
### I'm submitting a
[x] bug report => search github for a similar issue before submitting

### ...about

[x] edit experience / UI
[x] admin experience UI

### Current Behavior / Expected Behavior
With a Multilanguage page, the correct values are saved during translation, but sometimes the wrong language is displayed. When fetching the data, you will find the correct translation
![image](https://github.com/user-attachments/assets/fba92d4c-0df4-4ff4-95cb-76d6b19788ac)

### Instructions to Reproduce the Problem
Sometimes 
In our example, we have a small content type with only 3 fields. We fill the content in one language and then in the other. When saving, the correct content is sent, but when reopening, the content from the currently selected language is displayed.
![image](https://github.com/user-attachments/assets/25efe606-157a-40a7-a542-1ab6272b8e06)

### Your environment

* **2sxc version(s):** 18.00.00  
* **Browser:** all
* **DNN:** 9.13.00
* **Language:** any/all

**Comment by iJungleboy** [comment]
should be fixed in 18.01
