### ISSUE TITLE
Bug: Content-Type Field with data type Entity using input of Query Based Entity Picker Does Not Save

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#3461]
### I'm submitting a
[x] bug report 

### ...about
[x] edit experience / UI

#### Summary: selecting an entity using the qyery based entity/item picker does not save.

Working in 2sxc LTS (17.10.00), I have a content type named Portfolio and added a Field named Album, Type: Entity, with Input: Query-based Entity/Item Picker.

![image](https://github.com/user-attachments/assets/69e0e550-60a6-4235-a0e2-465244874a14)

The query is named Image Gallery Album. It uses the Source/App and is set to app switch to the 2sxc Image Gallery app v7.17.0 and the out Stream is renamed to Album to select that content type. It runs properly and shows all the Albums in the Image Gallery.

![image](https://github.com/user-attachments/assets/0f0ae47a-4693-4396-8559-0c48f21d41e7)

So back in the Portfolio content type, the Album field has its Query based item picker settings all default and Query set to "Image Gallery Album" selected from the drop down. This works in the UI, the dropdown shows correctly the Albums in the Gallery app. 
 
![image](https://github.com/user-attachments/assets/49e97459-dd0b-46c1-b6f2-d94373355917)

**However, after selecting an item and then hitting Save, the Album field is still blank when opened again.**

Also verified this in dev mode (Ctrl-Shift-Alt-Click), in the Data tab you can see the GUID.
```
        },
        "Album": {
          "Values": [
            {
              "Value": [
                "718368a1-44d3-478a-9cef-3212f48f0ddc"
              ],
              "Dimensions": [
                {
                  "Value": "*"
                }
              ]
            }
          ],
          "Type": "Entity"
        },
```

But after save and re-open, "Value": is null again. 

### Instructions to Reproduce the Problem
I believe I included enough detail above to reproduce the problem.
 
Also, we redid this on a different DNN instance in a similar project (above was Portfolio for an architect and each project has an Image Gallery, the other was an Apartments app (Properties, Units, and also an Image Gallery for each unit). _After repeating the setup, we encountered the exact same bug._

### Your environment
Cloud hosted Windows Server 2022 on IIS, ASP.NET, SQL 2019, etc.

* **2sxc version(s):** 17.10.00
* **Browser:** any, not relevant
* **DNN:** only tested on v9.13.04
* **Language:** any/all

**Comment by jeremy-farrance** [comment]
Also upgraded one of the projects just now to 2sxc v18.00.00 (latest) and same issue. Nothing has changed. Though I did not feel this type of problem needed me to go through the setup again.

**Comment by iJungleboy** [comment]
I'll check.

There has been a LOT of activity around the pickers in the edit-UI. So it could be that this accidentally was introduced.

**Comment by jeremy-farrance** [comment]
Nope, still broken. Please re-open. It says (below) that I do not have permission to do so.

Let me know if you spot anything in this video that falls short or if you need more info.
https://accuraty-my.sharepoint.com/:v:/p/jfarrance/EWd_WJhv91JMoemO2VNgzHwBwF_4satgBjWRKdOCTM_uIA?e=8ZLcF9

**Comment by iJungleboy** [comment]
thx.

**Comment by iJungleboy** [comment]
Ok, I think I see the problem in the video.

I believe you're using an entity-field (not a string field) to store the data. 
![image](https://github.com/user-attachments/assets/15cc74b3-3b7e-4dd0-aca9-c40ff7a3c84e)


Internally, entity-fields have a relationship so eg. in Razor you can do `@someItem.Album` but for this to work, the entities referenced must be in the _same App_. Otherwise the data layer would not be able to ensure the data integrity.

Now it seems you want to store a reference to another piece of data _outside_ of your App. 

As a reference this is not possible, since the internal data layer couldn't retrieve the entity for you.

Solution:

1. Switch to an string-query field
2. Update the code displaying the album to then retrieve the data from the other App using that guid.

**Comment by jeremy-farrance** [comment]
Thanks, that is not how I think. Doesn't matter to me that you cannot get to the record. I simple wanted it to save the GUID so I could use it in the View. Still seems like a bug to me. 

Think about our use case: we have our own portfolio/project app  and each project needs a gallery. The existing Gallery App does everything we need. So we want to link 1 album from the Gallery App per portfolio. I would not expect to be able to directly access the Entity, but (seriously) - why not save the GUID from my query picker?
 
Anyhow, thank you for the workaround. I hope you rethink this and see that my use-case makes sense. (It certainly does to me.)

**Comment by iJungleboy** [comment]
Your use case does make sense.

But the data model is required to enforce data integrity, which is why you must save it as a string ;)
