### ISSUE TITLE
Custom Search Index Controller UI Displaying Wrong Files

### ISSUE THREAD

**Issue by 6TELOIV** [2sic/2sxc#3468]
### I'm submitting a
[x] bug report

### ...about
[x] edit experience / UI
[x] admin experience UI
[x] DNN parts

### Current Behavior / Expected Behavior
The view configuration UI shows cshtml files instead of cs files. This prevents use of custom mappings for the DNN search crawler.

### Instructions to Reproduce the Problem
1. Make a custom search mapping cs file for an app
2. Observe that it will not show in the view configuration UI
![image](https://github.com/user-attachments/assets/7217d9f7-cb34-4ad3-aced-35e6b63fe3f1)

Example: [2sxcApp_App1_0.17.0.zip](https://github.com/user-attachments/files/16945293/2sxcApp_App1_0.17.0.zip)

### Your environment
* **2sxc version(s):** 17.09
* **Browser:** all
* **DNN:** 09.13.03
* **Hosting platform:** IIS
* **Language:** English

**Comment by 6TELOIV** [comment]
Sniffing around in the code, this seems to possibly be an issue with the formula which is supposed to set the template type to "C# Search". Digging further now into the formula v1 for what may have broken...

**Comment by 6TELOIV** [comment]
Nevermind, doesn't seem to hold the answers as far as I can tell...

**Comment by 6TELOIV** [comment]
Changing the formula for View Configuration > ViewController > File type to:
```js
v2((data) => { return 'C# Search'});
```
or
```js
v2((data) => { return 'Token'});
```
had no effect, so the breakdown seems like it has to be on the frontend in EAV-ui.

**Comment by iJungleboy** [comment]
Thanks for this - really was a bug. fixed in 18.02 to be release this week...

**Comment by 6TELOIV** [comment]
Awesome! Is there any way we can get an LTS update for this? Not sure how long it will take for 18 to get to LTS and we are hoping we can get our search working sooner if possible.

**Comment by iJungleboy** [comment]
ATM we're doing so much on certain features that it would not be reasonable to call it LTS for another 4-10 weeks.

But since you seem skilled in formulas, I suggest you just create a formula on the Value property to quickly "overwrite" the value ;)
