### ISSUE TITLE
Typo in "Help / Instructions" Help.

### ISSUE THREAD

**Issue by 6TELOIV** [2sic/2sxc#3469]
### I'm submitting a
[x] bug report => search github for a similar issue before submitting

### ...about
[x] edit experience / UI

### Current Behavior / Expected Behavior
There is a small typo present in the help text for the "Help / Instructions" notes field. It says "helpfull" instead of "helpful" in 2 places
![image](https://github.com/user-attachments/assets/07f7f714-a093-4688-b311-8c6b40b3c526)

### Instructions to Reproduce the Problem
Edit a data type, and see the typo.

### Your environment

* **2sxc version(s):** 17.09.00
* **Browser:** all
* **DNN:** all
* **Hosting platform:** all
* **Language:** English

**Comment by iJungleboy** [comment]
thx. will be in the next 18 release.

**Comment by 6TELOIV** [comment]
Created a pull request #3470 some further typos
