### ISSUE TITLE
Edit UI - Entity Dropdowns Show All, instead of the Expected Content-Type Items

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#3476]
### I'm submitting a
[x] bug report 

### ...about
[x] edit experience / UI
[x] admin experience UI

### Current Behavior / Expected Behavior
This appears to be happening all over the Admin UI. Whether trying to select from Settings or in a View Configuration (the example I am writing this from). I feel sure this first occurred after upgrading to v18.01.00 (from either v17.10.00 or v18.00.00).

In a View Configuration, under List Settings, turn on Enable list. Then select a Header Content Type. Next, when you use the dropdown for the Demo Item for the Header, you see all Entities (any Content-Type).

Normally/previously you would only see items from the (just assigned) Header Content-Type.

In the screenshot below you can see highlighted Items from 2 other content types and there is only one record so far in Header (the name of my content type) so you can see the scrollbar is showing MANY (all?) items.

![image](https://github.com/user-attachments/assets/d89a5517-be03-4a40-a1ec-615fbdc03719)

### Addition / Related?

Also, this is happening when you are in Settings and trying to select things from dropdown. FURTHER, once you do find and select the right thing, **clicking ADD/EDIT does nothing.** Though in View Config, after selecting an item, Edit does work.

### Instructions to Reproduce the Problem

I believe there is enough detail above to easily reproduce this problem. I have it happening right now on 3 projects in front of me. 2 were upgraded to v18.01 a few days ago. The 3rd was upgrade just now and did not have this issue before the upgrade from v17.10.

### Your environment

* **2sxc version(s):** only 18.01.00 (I think)
* **Browser:** all/any (working on Chrome)
* **DNN:** 9.13.04
* **Hosting platform:** IIS, Win Server 2022 (VPS)
* **Language:** any/all | English

**Comment by iJungleboy** [comment]
Thanks for this.

We have been doing major reworks of how these pickers work, because there was just too much duplicate and confusing code. 

My guess is that we introduced a timing problem, as the picker relies on selection of the previous picker and maybe something isn't quite right with how it handles the result of the query...

Will look into it ASAP.

**Comment by iJungleboy** [comment]
Found and fixed in 18.02
