### ISSUE TITLE
Oqtane - Strong typed data in Html.Partial fails with error CS0246: The type or namespace name 'x' could not be found

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3479]
### I'm submitting a
[x] bug report 
[x] not sure

### ...about
[x] Razor templating
[x] other / unknown

### Current Behavior / Expected Behavior
This is a working code from a DNN app

Template A:
```
@inherits Custom.Hybrid.RazorTyped
@using AppCode
@using AppCode.Data

@Html.Partial("shared/_B.cshtml", new { Units = true, Years = true, Months = true })
```

Template B:
```
@inherits Custom.Hybrid.RazorTyped

@{
    var tB= App.Data.GetAll<x>();
 }
```

Results in CS0246: The type or namespace name 'x' could not be found

Adding 
```
@using AppCode
@using AppCode.Data
```
to Template B results in CS0234: The type or namespace name 'Data' does not exist in the namespace 'AppCode'

### Your environment

* **2sxc version(s):** 18.01.00
* **Oqtane:** 5.2.3
* **Hosting platform:** IIS

**Comment by iJungleboy** [comment]
This can't work. What should `x` be?

The correct setup would have a class like `BlogPost` in the `AppCode.Data`.

Then your file B would look like this:

```razor
@inherits Custom.Hybrid.RazorTyped
@using AppCode
@using AppCode.Data

@{
    var tB= App.Data.GetAll<BlogPost>();
 }
```

**Comment by enfJoao** [comment]
Sorry. When copying the code from my template I abbreviated too much. "x" is my datatype, so BlogPost for example.

Everything else is still valid.
The class exists:
![image](https://github.com/user-attachments/assets/41ac3629-5acd-4f6f-b11e-eef5baf2a48c)

**Comment by enfJoao** [comment]
Updated the original example.

**Comment by enfJoao** [comment]
To clarify:

Template A:
```
@inherits Custom.Hybrid.RazorTyped
@using AppCode
@using AppCode.Data

@Html.Partial("shared/_B.cshtml", new { Units = true, Years = true, Months = true })
```

Template B:
```
@inherits Custom.Hybrid.RazorTyped
@using AppCode
@using AppCode.Data

@{
    var tUnits = App.Data.GetAll<zDepartments>()
 }
```

Results in CS0234: The type or namespace name 'Data' does not exist in the namespace 'AppCode'

**Comment by enfJoao** [comment]
Yes. I picked a DNN app and I'm trying to make it work in Oqtane. The current issue is in Oqtane.

**Comment by tvatavuk** [comment]
Thank you for reporting this issue! We identified that inconsistent path formatting was causing the problem, which has now been addressed by ensuring uniform path formatting for reliable comparisons. This fix will be included in the next release.
