### ISSUE TITLE
Oqtane - MyModel does not work with html partial

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3480]
### I'm submitting a

[x] bug report

### ...about
[x] Razor templating

### Current Behavior / Expected Behavior

This is a working DNN app I'm trying to migrate to Oqtane.

Template A:

```
@inherits Custom.Hybrid.RazorTyped
@using AppCode.Data
...
    @Html.Partial("shared/_B.cshtml", new { Units = true, Years = true, Months = true })
...
```

Template B:

```
@inherits Custom.Hybrid.RazorTyped
...
@MyModel.Units
...
```

Results in:
`error CS1061: 'ITypedModel' does not contain a definition for 'Units' and no accessible extension method 'Units' accepting a first argument of type 'ITypedModel' could be found`

### Your environment
* **2sxc version(s):** 18.01.00
* **Oqtane:** 5.2.3
* **Hosting platform:** IIS

**Comment by iJungleboy** [comment]
I think what you're trying to do is use a typed model.

For that you would need to create the class in your AppCode, and then change the `@inherits` ca. like this:

`@inherits MyCode.Razor.AppRazor<MyModel>`

Then you could use `Model.Unite` (not `MyModel`) 

The MyModel is for any kind of data, so you would need to do 

```c#
var uniteRequired = MyModel.Bool("Unite");
var uniteOptional = MyModel.Bool("Unite", fallback: false);
```

**Comment by enfJoao** [comment]
So the example from here:
https://2sxc.org/dnn-tutorials/en/razor/tut/razor-partial/variant/strong

Would also need the custom class in AppCode?
![image](https://github.com/user-attachments/assets/80fd824f-3b7d-4e5d-99cb-db45d235c966)

**Comment by iJungleboy** [comment]
The example above works without a custom model. So it uses `MyModel.String(...)`.

The samples at the bottom of the linked page show a strong typed model as well, there you use the `Model` object.
