### ISSUE TITLE
Code editor - Snippets titles missing

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3481]
### I'm submitting a
[x] bug report

### ...about
[x] Razor templating

### Current Behavior / Expected Behavior
![image](https://github.com/user-attachments/assets/2102a1ac-18f4-4173-8562-5f6af842fc90)

Not sure if related:
![image](https://github.com/user-attachments/assets/9715c1c3-fd55-49f6-b879-5ffabc3aac8c)

### Your environment

* **2sxc version(s):** 18.01.00
* **DNN:** 9.13.04

**Comment by paulpietzko** [comment]
Translations in the code editor are now loaded correctly.
