### ISSUE TITLE
HotBuild: Improve caching & performance on restart and IIS re-awake

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#3482]
### I'm submitting a

[x] feature request

### ...about

[x] Performance
[x] HotBuild

### Current Behavior / Expected Behavior

In certain scenarios the AppCode is recompiled. We think this happens a bit too often, and that if nothing changes, it should not rebuild. Because of this, we want to include some extra checks:

#### Generate a Hash from

1. All relevant code files
2. 2sxc version
3. Dnn version

and use it in the file name, to be reused in certain scenarios where it would otherwise recompile (which can take 1-5 seconds)

### Your environment

* **2sxc version(s):** 18.01

**Comment by 6TELOIV** [comment]
Very excited to try this out! Sounds like a good solution to the issue.

**Comment by iJungleboy** [comment]
@6TELOIV do try it ;)

ATM it would affect the `appcode.dll` but if it proves to work as expected, we'll also try to improve the razor compiling as well.
