### ISSUE TITLE
Feat: Support Ctrl/Shift Click in Admin UIs

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#3496]
### I'm submitting a

[x] feature request

### ...about

[x] edit experience / UI
[x] admin experience UI

### Current Behavior / Expected Behavior

The Admin-UI will use Angular Routing to do things.
New windows cannot be opened, since some information is passed to the initial URL which is then stored in the `sessionStorage`, so the visible link cannot be opened in another window.

But in many cases it would be nice to be able to open a new window. Examples are when you're working on content-types and want a window with a new item open etc.

Goal is that many buttons in Angular will be able to be ctrl+clicked and they will open an new window.

* [x] rework the routing URL so it contains all important parameters to work
* [x] rework Apps-Management to be able to open an App using a link (supporting ctrl+click)
* [ ] rework App-Management so most link also open a new window
* [x] implement new full-route mechanism on all other windows such as `query`, `code`, `versions`, etc.

### Your environment

* **2sxc version(s):** 18.02

**Comment by iJungleboy** [comment]
Many done in 18.03...

**Comment by paulpietzko** [comment]
The dialogs inside Data, Queries, Views, and App now navigate using links, allowing nearly all dialogs to be opened in a new tab.
