### ISSUE TITLE
Failing to build after 2sxc install

### ISSUE THREAD

**Issue by DiegelB** [2sic/2sxc#3503]
### I'm submitting a
[x] bug report => search github for a similar issue before submitting

### ...about
[x] other / unknown

### Current Behavior / Expected Behavior

I have a brand new dev build of Oqtane in VS. I connected it to SQL Server and then installed the 2sxc module. It runs fine after the initial restart when installing a new module. Then when I try to exit and build again, it fails to build and keeps telling me 'The type or namespace name 'ToSic' could not be found. 

It should build just fine after exiting and coming back. 

I could be doing something wrong, but after installing the module, restarting, it works fine. Then as soon as I stop debugging and try to build again, it fails.

### Your environment

* **2sxc version(s):** 16.0X.X  
* **Browser:**  Edge 
* **Oqtane
* **Hosting platform:** VS
* **Language:** English

**Comment by iJungleboy** [comment]
This is odd.

Could you update the issue with the Oqtane and 2sxc versions so we can decide how to proceed?

**Comment by DiegelB** [comment]
Thanks for the response! I am using Oqtane Version 5.2.4 and 2sxc Version 18.02.00. I wonder if I'm using the incorrect version of 2sxc

**Comment by DiegelB** [comment]
Just did a test with Oqtane version 5.2.0 and the same 2sxc version. It seems like everything runs and build fine, until I download the recommended Content packages. The things that let you add text and pictures. Then when I exit and try to rebuild, this is what I'm seeing.  

![image](https://github.com/user-attachments/assets/5d423a64-61b8-4ba3-8971-3ce9e0869d60)

**Comment by iJungleboy** [comment]
Your versions are all correct, and this is the recommended scenario for today.

What you're seeing is that the Razor files are of course referencing 2sxc DLLs, but it seems like they are not loaded. 

@tvatavuk any ideas?

**Comment by tvatavuk** [comment]
We can manually add the following to the `Oqtane.Server.csproj` file to exclude files and directories from being compiled, etc.

```xml
<ItemGroup>
  <!-- Exclude all files in directory and its subdirectories from being compiled. -->
  <Compile Remove="2sxc\**" />
  <Compile Remove="App_Data\**" />
  <Compile Remove="Content\**" />
  <Compile Remove="wwwroot\Modules\ToSic.Sxc.Oqtane\**" />
  <!-- Exclude all content files (like .html, .css, .js) from being included in the build output. -->
  <Content Remove="2sxc\**" />
  <Content Remove="App_Data\**" />
  <Content Remove="Content\**" />
  <Content Remove="wwwroot\Modules\ToSic.Sxc.Oqtane\**" />
  <!-- Exclude all files from being embedded as resources in the assembly. -->
  <EmbeddedResource Remove="2sxc\**" />
  <EmbeddedResource Remove="App_Data\**" />
  <EmbeddedResource Remove="Content\**" />
  <EmbeddedResource Remove="wwwroot\Modules\ToSic.Sxc.Oqtane\**" />
  <!-- Exclude files that are not otherwise included in any other item group (e.g., documentation files). -->
  <None Remove="2sxc\**" />
  <None Remove="App_Data\**" />
  <None Remove="Content\**" />
  <None Remove="wwwroot\Modules\ToSic.Sxc.Oqtane\**" />
  <!-- Exclude all files from being watched by the dotnet watch tool. -->
  <Watch Remove="2sxc\**" />
  <Watch Remove="App_Data\**" />
  <Watch Remove="Content\**" />
  <Watch Remove="wwwroot\Modules\ToSic.Sxc.Oqtane\**" />
  <!-- Exclude all TypeScript files in this directory and subdirectories -->
  <TypeScriptCompile Remove="2sxc\**" />
  <TypeScriptCompile Remove="App_Data\**" />
  <TypeScriptCompile Remove="Content\**" />
  <TypeScriptCompile Remove="wwwroot\Modules\ToSic.Sxc.Oqtane\**" />
</ItemGroup>
```

This configuration explicitly defines exclusions for the `2sxc`, `App_Data`, `Content`, and `wwwroot\Modules\ToSic.Sxc.Oqtane` directories.

**Comment by iJungleboy** [comment]
i'll close this for now, assume it's fixed.

If not, just post again and I'll reopen.
