### ISSUE TITLE
Oqtane - Getting started frame triggering DNN cookies errors?

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3507]
### I'm submitting a
[x] not sure

### ...about
[x] other / unknown

### Current Behavior / Expected Behavior
![image](https://github.com/user-attachments/assets/65b654fd-dc47-4472-8331-3bd885b46c48)

### Your environment

* **2sxc version(s):** 18.02.00
* **Browser:** Firefox
* **Oqtane:** 5.2.4
* **Hosting platform:** IIS

**Comment by iJungleboy** [comment]
so these are cookies set by DNN. 

I don't think we'll be able to do anything soon, because it will require DNN - and the .net Framework 4.8 - to support CHIPS.

**Comment by enfJoao** [comment]
This is in Oqtane cms, not DNN...

**Comment by iJungleboy** [comment]
The IFrame is loaded from a DNN site, and contains normal DNN cookies.

That's what's triggering the warnings in your new chrome browser.

**Comment by iJungleboy** [comment]
I will close this for now.

It doesn't affect behavior, and fixing it requires changes to Chrome and/or DNN - incl. .net framework, so for this kind of adjustment we will have to wait quite a long time.
