### ISSUE TITLE
2sxc v18.04.00 breaks the visual Query editor

### ISSUE THREAD

**Issue by skarpik** [2sic/2sxc#3513]
### I'm submitting a

[x] bug report => search github for a similar issue before submitting

### ...about

[x] edit experience / UI
[x] admin experience UI
[x] Razor templating

### Current Behavior / Expected Behavior

Whether one starts with an earlier 2sxc version and upgrades to 2sxc v18.04.00 or starts with a fresh 2sxc v18.04.00 installation, the visual Query editor is broken (i.e. clicking on a query to open the visual editor does nothing). The bug produces a JavaScript error in the console. The issue is not limited to specific apps but rather appears manifest itself in all apps (standard 2sxc and custom) that use queries.

In 2sxc version v18.03.00, the visual Query editor works perfectly. Some change in 2sxc v18.04.00 seems to have broken the visual Query editor. I should see an interface like:

**Query Editor in 2sxc v18.03.00**
![Screenshot 2024-11-25 235909](https://github.com/user-attachments/assets/ffa14931-f357-4308-ad95-7422a509b642)

With the visual Query editor broken, one cannot either edit or create new queries.

If one starts with a 2sxc v18.03.00 website and upgrades to v18.04.00, queries function properly but editing queries or adding new queries is impossible.

The bug is present in both DNN v13.04.00 and DNN v13.06.00 websites.

### Instructions to Reproduce the Problem

1. In a 2sxc v18.03.00 DNN v9.13.04 website, wrote a simple 2sxc app with data and a query for the data.
2. Exported the app as a Zip file and then imported the app into a 2sxc v18.04.00 website. Verified that the app (which uses queries) works properly.
3. Tried to edit a query and the following error appears in the JavaScript console:

![Screenshot 2024-11-25 234124](https://github.com/user-attachments/assets/be987c3c-4dec-448b-9ab6-cb27f95d4a99)

4. If you don't want to go to the trouble of writing an app, you can simply go to any of the standard 2sxc apps (like News, for example) and try to edit the query - you will see a similar error to my screenshot above. If you would like a copy of my test app, I'm happy to send a Zip file to anyone (but it really isn't very interesting).

**Text of the error:**
vendor.b9a093fb1a423776.js:1  ERROR Ct: NG04002: '2/v2/383/383/2/apps/list/query/2949'
    at Gr.noMatchError (http://2sxc-18-04-00.dnndev.me/desktopmodules/tosic_sexycontent/dist/ng-edit/vendor.b9a093fb1a423776.js:1:662865)
    at http://2sxc-18-04-00.dnndev.me/desktopmodules/tosic_sexycontent/dist/ng-edit/vendor.b9a093fb1a423776.js:1:663691
    at http://2sxc-18-04-00.dnndev.me/desktopmodules/tosic_sexycontent/dist/ng-edit/vendor.b9a093fb1a423776.js:1:16450
    at D._error (http://2sxc-18-04-00.dnndev.me/desktopmodules/tosic_sexycontent/dist/ng-edit/vendor.b9a093fb1a423776.js:1:15924)
    at D.error (http://2sxc-18-04-00.dnndev.me/desktopmodules/tosic_sexycontent/dist/ng-edit/vendor.b9a093fb1a423776.js:1:5413)
    at D._error (http://2sxc-18-04-00.dnndev.me/desktopmodules/tosic_sexycontent/dist/ng-edit/vendor.b9a093fb1a423776.js:1:5656)
    at D.error (http://2sxc-18-04-00.dnndev.me/desktopmodules/tosic_sexycontent/dist/ng-edit/vendor.b9a093fb1a423776.js:1:5413)
    at D._error (http://2sxc-18-04-00.dnndev.me/desktopmodules/tosic_sexycontent/dist/ng-edit/vendor.b9a093fb1a423776.js:1:5656)
    at D.error (http://2sxc-18-04-00.dnndev.me/desktopmodules/tosic_sexycontent/dist/ng-edit/vendor.b9a093fb1a423776.js:1:5413)
    at D._error (http://2sxc-18-04-00.dnndev.me/desktopmodules/tosic_sexycontent/dist/ng-edit/vendor.b9a093fb1a423776.js:1:5656)
handleError @ vendor.b9a093fb1a423776.js:1
next @ vendor.b9a093fb1a423776.js:1
next @ vendor.b9a093fb1a423776.js:1
_next @ vendor.b9a093fb1a423776.js:1
next @ vendor.b9a093fb1a423776.js:1
(anonymous) @ vendor.b9a093fb1a423776.js:1
D @ vendor.b9a093fb1a423776.js:1
next @ vendor.b9a093fb1a423776.js:1
emit @ vendor.b9a093fb1a423776.js:1
(anonymous) @ vendor.b9a093fb1a423776.js:1
invoke @ polyfills.60d1977d3000bf7b.js:1
run @ polyfills.60d1977d3000bf7b.js:1
runOutsideAngular @ vendor.b9a093fb1a423776.js:1
onHandleError @ vendor.b9a093fb1a423776.js:1
handleError @ polyfills.60d1977d3000bf7b.js:1
runGuarded @ polyfills.60d1977d3000bf7b.js:1
t.microtaskDrainDone @ polyfills.60d1977d3000bf7b.js:1
K @ polyfills.60d1977d3000bf7b.js:1
invokeTask @ polyfills.60d1977d3000bf7b.js:1
E.invoke @ polyfills.60d1977d3000bf7b.js:1
T.d.args.<computed> @ polyfills.60d1977d3000bf7b.js:1
setTimeout
T @ polyfills.60d1977d3000bf7b.js:1
scheduleTask @ polyfills.60d1977d3000bf7b.js:1
onScheduleTask @ polyfills.60d1977d3000bf7b.js:1
scheduleTask @ polyfills.60d1977d3000bf7b.js:1
scheduleTask @ polyfills.60d1977d3000bf7b.js:1
scheduleMacroTask @ polyfills.60d1977d3000bf7b.js:1
xe @ polyfills.60d1977d3000bf7b.js:1
(anonymous) @ polyfills.60d1977d3000bf7b.js:1
t.<computed> @ polyfills.60d1977d3000bf7b.js:1
(anonymous) @ vendor.b9a093fb1a423776.js:1
(anonymous) @ vendor.b9a093fb1a423776.js:1
next @ vendor.b9a093fb1a423776.js:1
_next @ vendor.b9a093fb1a423776.js:1
next @ vendor.b9a093fb1a423776.js:1
(anonymous) @ vendor.b9a093fb1a423776.js:1
D @ vendor.b9a093fb1a423776.js:1
next @ vendor.b9a093fb1a423776.js:1
emit @ vendor.b9a093fb1a423776.js:1
(anonymous) @ vendor.b9a093fb1a423776.js:1
invokeTask @ polyfills.60d1977d3000bf7b.js:1
onInvokeTask @ vendor.b9a093fb1a423776.js:1
invokeTask @ polyfills.60d1977d3000bf7b.js:1
runTask @ polyfills.60d1977d3000bf7b.js:1
invokeTask @ polyfills.60d1977d3000bf7b.js:1
Z @ polyfills.60d1977d3000bf7b.js:1
x @ polyfills.60d1977d3000bf7b.js:1
U @ polyfills.60d1977d3000bf7b.js:1

### Your environment

* **2sxc version(s):** 18.04.00  
* **Browser:** all 
* **DNN:** all
* **Hosting platform:** IIS
* **Language:** English

**Comment by jeremy-farrance** [comment]
I have experienced this too. Query I made about a week ago, working and could edit on 18.03. Upgraded to 18.04, query still works, can't edit. DNN is v9.13.04.

**Comment by iJungleboy** [comment]
not good, we'll try to fix ASAP.

@paulpietzko could you verify this? probably related to the changes with the links in the admin section.

**Comment by paulpietzko** [comment]
It works if you open the App Configurations in a new tab (Ctrl + click).

![26-11-2024_10-41-36](https://github.com/user-attachments/assets/39439d3f-bd58-4def-a01b-1cbdda683698)

For some reason, it doesn't work when opened normally (in the same tab).

In the Dev version this issue no longer persists because it got refactored allready.

**Comment by paulpietzko** [comment]
@skarpik, @jeremy-farrance

In the next release, the queries will work as usual again.
