### ISSUE TITLE
Runtime error after installing 2sxc 18.04.00 in Oqtane version 6 which makes oqtane unusable

### ISSUE THREAD

**Issue by patrickjlee** [2sic/2sxc#3515]
### Discussed in https://github.com/2sic/2sxc/discussions/3514

<div type='discussions-op-text'>

<sup>Originally posted by **patrickjlee** December  1, 2024</sup>
hi - I have watched the various videos today about 2sxc and am very excited to try it out. 
But I've now tried twice to get it running with my (so far local, i.e. running in debug) Oqtane 6 (.NET 9) installation, but each time I get run time errors.

E.g. I've just done a clean install of Oqtane 9, and then went to Module Management and installed the 2sxc 18.04.00 module from there.  I restarted Oqtane 9, and then created two new pages.  For the first of these I added a Content module, for the second I added an App module.
But when I go to either age I get a run time error:

Can't find uiRoot - something went wrong, pls contact 2sxc.org

When I click on F5 to continue I then get a second error (perhaps not surprisingly given the first one):

Can't load pageid, moduleid, etc. and $ is not available. 
You must either include jQuery on the page or inject the jsApi parameters to prevent auto-detection.

Any idea how I can solve this please?
</div>

**Comment by patrickjlee** [comment]
From the discussion: the solution to the above was to switch off Hot reload, but that exposed a more serious problem:

I've tried adding 2sxc several times now in different Oqtane version 6 fresh installs locally, and each time (with the hotReloadEnabled set to false) I can only get as far as installing the module, but after adding either Content or an App to a page, when I rebuild the site it has build errors (in fact it had 1159 such errors after installing the 23 popular apps).

Unfortunately this then makes Oqtane unusable.

**Comment by iJungleboy** [comment]
@patrickjlee this is very odd, and we would love to look into it directly if you have time, so see what's different on your environment - since we must of course assume others would have this challenge as well.

Would you take time to have a look at this? @tvatavuk could do a teams call with you if you have time.

**Comment by patrickjlee** [comment]
Many thanks @tvatavuk : adding that to the Oqtane.Server.csproj file seems to have solved the problem!  (I suggest that these steps be added to the installation instructions.)
