### ISSUE TITLE
Error upon adding content module or managing new app

### ISSUE THREAD

**Issue by ICATT** [2sic/2sxc#374]
I'm getting the attached error after adding a content module or an app module to a page. The issue has something to do with the field 'frGettingStarted'.

I also got a similar issue after adding an app module, creating a new app and then clicking on 'manage' in the app management view.

The page I'm adding the module to doesn't have any other modules. I've already tried to reinstall the module.

DNN version: 07.03.04
Module version: 7.2.3

![19-10-2015 17-30-19](https://cloud.githubusercontent.com/assets/9265746/10582302/7775c66c-7687-11e5-9c03-8043121a92fb.png)

**Comment by iJungleboy** [comment]
I remember seeing this before - I think it's a .net version issue of the framework v4 vs. v4.5. @raphael-m do you have a quick-fix to recommend?
