### ISSUE TITLE
CK Editor content not saving in 8.00.+ (and it's too small)

### ISSUE THREAD

**Issue by joshgk00** [2sic/2sxc#411]
I'm running a fresh install of DNN 7.4.2 and 2sxc 8.00.02. I have a content type setup to use the WYSIWYG editor for one of the fields. When I added a sample item for the content I filled in data for the WYSIWYG but the data isn't saving. The Description is empty and consequently nothing shows in the template either
![image](https://cloud.githubusercontent.com/assets/13650025/10828184/6b9367a4-7e49-11e5-97f8-dde48237afee.png)

**Comment by iJungleboy** [comment]
We have others using the CK editor which works - could you verify that this is still an issue?

**Comment by nicpitsch** [comment]
I can verify this is still an issue. 
Environment:
- Completely fresh DNN 7.4.2 installation.
- 2sxc 08.00.06.
- CKEditor-Provider_02.01.03 (from [Codeplex](https://dnnckeditor.codeplex.com/)).

Switch from CKEditor to RadEditor and the content gets saved.

I can give you admin access to the DNN installation, if you like.

**Comment by BravoSierra** [comment]
Yes we confirm, still an issue.

**Comment by joshgk00** [comment]
Any chance this fix will make it into the next release? I can't really use the new version because my sites use the CK Editor and the content still isn't saving.

**Comment by iJungleboy** [comment]
Our current priority is actually to get rid of the dnn wysiwyg because there are so many things that are wrong with it it's hard to list them all. We're just postponing it because there is currently no good JS-based file picker in DNN, but as we're enhancing ADAM this will probably become unnecessary. 

If this is very important to you, do you think you could contribute - or sponsor - the fix?

**Comment by joshgk00** [comment]
Do you have an idea of what it would take in terms of sponsoring a fix?




On Wed, Dec 23, 2015 at 12:02 AM -0800, "iJungleboy" <notifications@github.com<mailto:notifications@github.com>> wrote:


Our current priority is actually to get rid of the dnn wysiwyg because there are so many things that are wrong with it it's hard to list them all. We're just postponing it because there is currently no good JS-based file picker in DNN, but as we're enhancing ADAM this will probably become unnecessary.

If this is very important to you, do you think you could contribute - or sponsor - the fix?

-

**Comment by iJungleboy** [comment]
My guess is 2-3 hours at 160.- per hour

Mail, Tel and more: http://2sic.com/dm
Sent from mobile

On 23 Dec 2015, at 10:51, joshgk00 <notifications@github.com<mailto:notifications@github.com>> wrote:

Do you have an idea of what it would take in terms of sponsoring a fix?




On Wed, Dec 23, 2015 at 12:02 AM -0800, "iJungleboy" <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Our current priority is actually to get rid of the dnn wysiwyg because there are so many things that are wrong with it it's hard to list them all. We're just postponing it because there is currently no good JS-based file picker in DNN, but as we're enhancing ADAM this will probably become unnecessary.

If this is very important to you, do you think you could contribute - or sponsor - the fix?

-
Reply to this email directly or view it on GitHub<https://github.com/2sic/2sxc/issues/411#issuecomment-166830430>.

�

**Comment by joshgk00** [comment]
That sounds good. I will sponsor that fix. Let me know what you need from me to get started. Thank you!





On Wed, Dec 23, 2015 at 2:56 AM -0800, "iJungleboy" <notifications@github.com<mailto:notifications@github.com>> wrote:

My guess is 2-3 hours at 160.- per hour

Mail, Tel and more: http://2sic.com/dm
Sent from mobile

On 23 Dec 2015, at 10:51, joshgk00 <notifications@github.com<mailto:notifications@github.com>> wrote:

Do you have an idea of what it would take in terms of sponsoring a fix?




On Wed, Dec 23, 2015 at 12:02 AM -0800, "iJungleboy" <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Our current priority is actually to get rid of the dnn wysiwyg because there are so many things that are wrong with it it's hard to list them all. We're just postponing it because there is currently no good JS-based file picker in DNN, but as we're enhancing ADAM this will probably become unnecessary.

If this is very important to you, do you think you could contribute - or sponsor - the fix?

-
Reply to this email directly or view it on GitHub<https://github.com/2sic/2sxc/issues/411#issuecomment-166830430>.

?
Reply to this email directly or view it on GitHub<https://github.com/2sic/2sxc/issues/411#issuecomment-166849840>.

-

**Comment by iJungleboy** [comment]
This sounds great, we'll get it into the next release. Note: The holidays have just started, so we'll be mostly offline for about 2 weeks. This should make it into 08.00.12 on January 6th.

**Comment by iJungleboy** [comment]
@joshgk00 pls contact me on http://2sxc.org/en/Contact and send me your contact details so we can coordinate billing.

**Comment by joshgk00** [comment]
Sounds good. Thanks!

**Comment by joshgk00** [comment]
I send the details through the contact form. Just send me a message to let me know if the information came through. Thanks an happy holidays!

**Comment by raphael-m** [comment]
Done in 8.0.12, please try it.

**Comment by joshgk00** [comment]
Initial tests look good! Thank you!

**Comment by BravoSierra** [comment]
Yes, all this is much better, thanks Joshgk00 and raphael-m.

However, the external Window (2sxc) embedding the CKE window is too small, which results in 1.user must scroll Inside CKEditor for long texts, and 2.- button Save when saving an image in not visible, the users tends to Save the whole content and misses saving the picture, resulting in support requests that images are not saved.

Suggestions: 1. Enlarge the external 2scx popup, or 2.- make it resizable (as was before in v7 i think)

**Comment by joshgk00** [comment]
I’m seeing this as well. http://screencast.com/t/a9VFmuw0

I’m also seeing on some sites that the editor is showing the full page layout including the menu which makes the window really large
http://screencast.com/t/drZqE40Y

**Comment by iJungleboy** [comment]
@joshgk00 Do you have popups disabled? that's a core problem because we need to be skinless to iframe it. 

@BravoSierra could you give a screenshot so we know what you mean? Is it like @joshgk00 screenshow where the length isn't corrected?

**Comment by joshgk00** [comment]
I did re-enable popus, cleared the cache and it still seems as showing the entire page with the menu like the screenshot.


On Thu, Jan 7, 2016 at 2:34 PM -0800, "iJungleboy" <notifications@github.com<mailto:notifications@github.com>> wrote:


@joshgk00<https://github.com/joshgk00> Do you have popups disabled? that's a core problem because we need to be skinless to iframe it.

@BravoSierra<https://github.com/BravoSierra> could you give a screenshot so we know what you mean? Is it like @joshgk00<https://github.com/joshgk00> screenshow where the length isn't corrected?

-

**Comment by iJungleboy** [comment]
@joshgk00 could you check what url is actually used within the iframe (so after all the redirects happened, what url is actually displayed)? I'm guessing popUp=true is either missing or wrongly rewritten, or it's there but disabled.

**Comment by joshgk00** [comment]
Found the issue. The url for the iframe was being redirected to an all lowercase version which was incorrect, so I a regex that would exclude those from being redirected to the lowercase version. Thank you!

**Comment by BravoSierra** [comment]
Yes iJungle you are correct, it's the uppercase U in popUp that is the problem. Our URLs are lowercased for SEO Customer requirement. Will you fix it so that it is case neutral or lowercase? Thanks

**Comment by joshgk00** [comment]
I had the same issue on a customer site as well. I just added a regular expression that looks for ctl=webformsbridge and set it not to redirect urls that contain the aforementioned. That way all other urls are lowercase and the editor field works as it should.

**Comment by BravoSierra** [comment]
@joshgk00 Thanks for the workaround
@iJungleboy regarding the respective size of the  embedded Windows: it seems that it dépends on the skin and the CKE settings, so that on the website that we are working on currently we have found a good tradeoff and it displays quite nicely.

But below is an example on my sandbox with everything as 'by default' as possible  and as you can see any non-tech user would probable clic on the 2sxc 'Save' before they ever relize that there is a CKE save for the picture they've inserted
![insertpic](https://cloud.githubusercontent.com/assets/5261858/12200756/eef0ca6a-b620-11e5-85cd-eaad5f400eb8.JPG)

**Comment by BravoSierra** [comment]
Maybe the best would be to wait until there are more feedbacks on various configurations? Anyway thanks for the current implementation, it's really cool to have CKE

**Comment by iJungleboy** [comment]
So just fyi: the popUp (with large U) is a DNN issue. So the workaround with the don't-rewrite-rule is the correct one. 

@joshgk00 if I understand it correctly we can close this? pls confirm.

**Comment by joshgk00** [comment]
Yes I believe we can close this issue


On Sun, Jan 10, 2016 at 11:24 PM -0800, "iJungleboy" <notifications@github.com<mailto:notifications@github.com>> wrote:


So just fyi: the popUp (with large U) is a DNN issue. So the workaround with the don't-rewrite-rule is the correct one.

@joshgk00<https://github.com/joshgk00> if I understand it correctly we can close this? pls confirm.

-

**Comment by BravoSierra** [comment]
So if it is a DNN issue, should we open an issue in DNN's Jira?

**Comment by iJungleboy** [comment]
In general yes. It's 2 bugs of 2 system.

1. dnn bug which requires popUp to be case sensitive
2. usually causes real problems when the url is rewritten - by other components

but yes, if dnn wasn't picky about popUp and would also accept popup, none of these problems would occur. a jira would be great, thx!

**Comment by iJungleboy** [comment]
@joshgk00 thx, I'll close this now.

**Comment by BravoSierra** [comment]
https://dnntracker.atlassian.net/browse/DNN-8305

 

Benoît SARTON

 <http://www.bsi.fr/> www.bsi.fr

04 66 30 00 00

 

De : iJungleboy [mailto:notifications@github.com] 
Envoyé : lundi 11 janvier 2016 14:46
À : 2sic/2sxc
Cc : BSI
Objet : Re: [2sxc] CK Editor content not saving in 8.00.+ (and it's too small) (#411)

 

In general yes. It's 2 bugs of 2 system.

1.	dnn bug which requires popUp to be case sensitive
2.	usually causes real problems when the url is rewritten - by other components

but yes, if dnn wasn't picky about popUp and would also accept popup, none of these problems would occur. a jira would be great, thx!

**Comment by BravoSierra** [comment]
For information:
DNN Platform /  DNN-8305 
"DNN requires the U in popUp to be uppercase"
Fix Version/s:	DNN Platform 8.0.1

**Comment by iJungleboy** [comment]
Cool. That would be somewhere in March...
