### ISSUE TITLE
Whole site in notes field 8.00.2?

### ISSUE THREAD

**Issue by ech01** [2sic/2sxc#412]
Any time there is a wysiwyg field the entire webpage is framed in. Makes the admin almost unusable because the "notes" field is taking 98% of the modal. 

![image](https://cloud.githubusercontent.com/assets/3790873/10831176/2523af0a-7e52-11e5-9efe-41f56bd4bd65.png)

latest version of evoq

**Comment by ech01** [comment]
Another example editing a Content field (String, wysiwyg)
![image](https://cloud.githubusercontent.com/assets/3790873/10831244/86e5f1d0-7e52-11e5-9e0a-ffbefb9fb829.png)

**Comment by iJungleboy** [comment]
this is a bit strange. did you use any special setting like disable dnn popups? 
Could you check the URL which is actually retrieved? it should contain a popUp=true in the url...

**Comment by ech01** [comment]
I ended up ditching 8.0.2 and reverting back to 7. Popups annoy me, so yes they are turned off.

**Comment by iJungleboy** [comment]
For the moment we cannot solve this. Unfortunately the editor needs the dnn-wrapper to work. We're looking into pure JS-editors but adding page-links or image-links would have to be developed first, so it's a resource issue :( 
If you would have time :) - then we could speed this up...
