### ISSUE TITLE
After upgrade from 7 >> 8.00.2 Field Types not set

### ISSUE THREAD

**Issue by ech01** [2sic/2sxc#413]
Uppgraded from 7 to 8.00.2 and all the field types for our content data did not carry over. 

![image](https://cloud.githubusercontent.com/assets/3790873/10831338/0a9640a2-7e53-11e5-874e-d3058bd45c30.png)

**Comment by iJungleboy** [comment]
This is by design. The old inner field type will still behave correctly, but the new setting field-type has not been configured yet. once you configure it, it will be known.
