### ISSUE TITLE
Unable to set estimated number of lines for Text contents

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#416]
In earlier versions it was possible to set an estimated height for Text edit textboxes, depending on the number of lines specified. This has disappeared.

**Comment by raphael-m** [comment]
Do I understand you correctly: You know where to configure the line number, but the field always has one line (2sxc does not respect the setting)?

**Comment by BravoSierra** [comment]
This one is solved, thanks

 

Benoît SARTON

 <http://www.bsi.fr/> www.bsi.fr

04 66 30 00 00

 

De : Raphael [mailto:notifications@github.com] 
Envoyé : lundi 9 novembre 2015 16:46
À : 2sic/2sxc
Cc : BravoSierra
Objet : Re: [2sxc] Unable to set estimated number of lines for Text contents (#416)

 

Do I understand you correctly: You know where to configure the line number, but the field always has one line (2sxc does not respect the setting)?
