### ISSUE TITLE
Importing an App : input type data not imported

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#417]
input type data are lost when importing an App. The field is empty

**Comment by iJungleboy** [comment]
@raphael-m pls check and fix

**Comment by raphael-m** [comment]
This only occurs when importing apps from a previous version. It's the same issues as #413. The fields should still work as before, but the 'Input Type' column is empty.

**Comment by iJungleboy** [comment]
We'll add additional information so that this doesn't confuse people any more #436
