### ISSUE TITLE
RadEditor adds breaks when saving and reopening entity edit dialog

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#420]
Before save (with closing and reopening the edit dialog):
![before save](https://cloud.githubusercontent.com/assets/5171884/10881752/df836c62-8165-11e5-94a5-90341ceccdd6.png)

After save:
![after save](https://cloud.githubusercontent.com/assets/5171884/10881753/e27a1902-8165-11e5-92fc-f34eb9cd8481.png)

**Comment by raphael-m** [comment]
Only happens when switching to HTML view between saves.

**Comment by iJungleboy** [comment]
Sounds like a dnn-bug. Does in NOT happen in normal html-modules (so only in 2sxc) or always when using telerik...?

**Comment by iJungleboy** [comment]
Not important enough, seems only to hit when switch between html & design mode; close
