### ISSUE TITLE
Deleting fields does not work

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#425]
Deleting fields from an existing content type seems to fail on a new installation.

**Comment by raphael-m** [comment]
Can't reproduce on a new installation.

**Comment by c42705** [comment]
just happened to me.

**Comment by iJungleboy** [comment]
@c42705 could you give an exact example -which app, which content-type and which field

**Comment by iJungleboy** [comment]
Stale, no more feedback, close for now...
