### ISSUE TITLE
Re-Ordering of fields should be drag-drop and work correctly

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#431]
Sometimes when moving a field up or down, it jumps multiple positions instead of one.

**Comment by iJungleboy** [comment]
If you touch this, you may want to actually just implement drag-and-drop

**Comment by BeniGemperle** [comment]
I just created a new content type, added 3 fields, deleted the one on top, added another one and wanted to change their order. Somehow now two fields have the same SortOrder of 2.
 I'm using 2sxc 8.4.8.

**Comment by raphael-m** [comment]
Done with https://github.com/2sic/2sxc/commit/c25d2b74ae45da3a9be2055bbe7493a4407d3127
