### ISSUE TITLE
Module Settings fail to open because old controls are still registered

### ISSUE THREAD

**Issue by dougcsicam** [2sic/2sxc#432]
Ver 8.0.2
When clicking on settings for the module I receive this error.
500 - Internal server error.
There is a problem with the resource you are looking for, and it cannot be displayed.

**Comment by dougcsicam** [comment]
The upgrade did not remove the settings.ascx from the module definitions. When removed manually it works fine.  I assume the settingswrapper.ascx should be removed also.

**Comment by iJungleboy** [comment]
@dougcsicam - do I understand you correctly that this fixed the 500 error?

**Comment by iJungleboy** [comment]
Stale thread - close for now. Please reopen if still an issue.

**Comment by dougcsicam** [comment]
Once I changed the module definitions to delete the settings.ascx it works fine.  Since this was an upgrade from 7 the settings.ascx was still in the module definitions.

**Comment by iJungleboy** [comment]
@raphael-m  could you check? I believe the mod-definitions get cleared...?

**Comment by iJungleboy** [comment]
Note: I was able to reproduce it and had 2-3 similar feedbacks.
