### ISSUE TITLE
Upgrade message needs to be updated

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#435]
"When upgrading from v6 to v7 the process may take so long that a timeout occurs on server restart."
Update the message to 'v8' if necessary

**Comment by BravoSierra** [comment]
It’s a very minor detail, but I didn’t see any change when ugrading from v8.0.3 to 8.0.4 I still read:

When upgrading from v6 to v7 the process may take so long that a timeout occurs on server restart.

Thanks for the release anyway

 

Benoît SARTON

**Comment by iJungleboy** [comment]
This was closed on the wrong set - it is implemented in 8.00.5

**Comment by BravoSierra** [comment]
Done in 8.0.5, thanks
