### ISSUE TITLE
On click sort button to sort items 500 error

### ISSUE THREAD

**Issue by Frankwalraven** [2sic/2sxc#439]
version 8.0.3
![500-error-sort-button](https://cloud.githubusercontent.com/assets/13934402/11163305/f348b064-8ac9-11e5-97d2-b762afd92e7d.jpg)
This happens not on all places. On a few places you get the correct pop-up. But on the most places this error occurs

**Comment by Frankwalraven** [comment]
From javascript console:
GET http://www.perfocusdemo.nl/desktopmodules/2sxc/api/app/contentgroup/itemlist?appId=13&guid=33625301-9907-49b5-beb6-35002fc5d3a3 500 (Internal Server Error)(anonymous function) @ set.min.js?sxcver=08.00.02:3p @ set.min.js?sxcver=08.00.02:3j @ set.min.js?sxcver=08.00.02:3(anonymous function) @ set.min.js?sxcver=08.00.02:3m.$eval @ set.min.js?sxcver=08.00.02:4m.$digest @ set.min.js?sxcver=08.00.02:3m.$apply @ set.min.js?sxcver=08.00.02:4(anonymous function) @ set.min.js?sxcver=08.00.02:2e @ set.min.js?sxcver=08.00.02:2g @ set.min.js?sxcver=08.00.02:2_ @ set.min.js?sxcver=08.00.02:2a.bootstrap @ set.min.js?sxcver=08.00.02:7(anonymous function) @ 2sxc4ng.annotated.js:31d @ set.min.js?sxcver=08.00.02:4Ha.c @ set.min.js?sxcver=08.00.02:2
2sxc.api.js:186 Object {data: Object, status: 500, config: Object, statusText: "Internal Server Error"}config: Objectdata: Objectheaders: (c)status: 500statusText: "Internal Server Error"__proto__: Object

**Comment by Frankwalraven** [comment]
2sxc.api.js:186 
Object {data: Object, status: 500, config: Object, statusText: "Internal Server Error"}

**Comment by Frankwalraven** [comment]
also with the function replace content at list level and item level I get the same error

**Comment by iJungleboy** [comment]
Could we look at your implementation to help figure out the issue? you could send us a login to info 2sxc org

**Comment by Frankwalraven** [comment]
I send the login of the test site

**Comment by Frankwalraven** [comment]
wrong button :-)

**Comment by joinsaturn** [comment]
Maybe can help.
Happen for me whene I use the function "add demo" from [Content:Toolbar] and next I try to sort with the function "Re-order list of content-items".

**Comment by iJungleboy** [comment]
@joinsaturn thanks, will check that

**Comment by Frankwalraven** [comment]
I found out that when the titel field of a content type is empty the error occurs. If we put data in the title field the error does not occur on the sort button. Its still there for the replace button. I think the reason is that there are (many)records in the tabel with empty titel fields, and this function looks in the total table

**Comment by Frankwalraven** [comment]
we have with a query the title field filled everywhere. Now the replace button works well also. So both errors occur when the titel field of an entity is not filled

**Comment by iJungleboy** [comment]
That's great feedback. So the core issue seems to be that these features fail when the title is blank or null, correct?

**Comment by Frankwalraven** [comment]
Yes. When there is a title that is involved in the function that is empty we get an error. When all the titles that are involved in the function have data the functions operate as excepted.

**Comment by Frankwalraven** [comment]
Looks like the title can't be null. When we empty a title again the functions still work

**Comment by Frankwalraven** [comment]
When you add like @joinsaturn says with the add a item with the add demo button the title field get not read or  = null and you get the error again. when you edit the records and save its OK again. 

Looks like that converted records from the 7 version with empty data are null. When you add a record with the normal + new function and save the title field is empty. With the add demo button the title field = null. Also when the title field in the demo record is filled

**Comment by iJungleboy** [comment]
Was able to reproduce... both on replace and sort, but not on the in-page sort, only in the dialog-sort.

**Comment by iJungleboy** [comment]
I created separate issue for replace and fixed that... #456
