### ISSUE TITLE
Review changes in Azure SQL 14

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#440]
Pls review w/2bg

**Comment by iJungleboy** [comment]
Reopen because apparently it's not working yet - see http://sexycontent.codeplex.com/discussions/649879#post1458918

Maybe it's just the installation routine which doesn't work yet, not sure.

**Comment by kingjordan** [comment]
Just for some context, I am getting the error listed in the linked codeplex discussion when i try to update an item in my content apps and when I try to upgrade to 8.0.12

**Comment by iJungleboy** [comment]
@kingjordan we're pretty sure we know what it is - we've actually solved it on an evoq-in-the-cloud installation 2-3 months ago. But we thought it's already part of the distribution, there must be something missing or an old install SQL which still tries to implement the SQL 12 stuff.

**Comment by kingjordan** [comment]
great, you guys are the best, I'll wait for the update

**Comment by kingjordan** [comment]
hello, anyway I can bump this fix, I have a couple production sites that are block by this in a sql azure environment.  Or if you can explain what needs to be done can I do it and submit a pull request?

**Comment by iJungleboy** [comment]
Sorry about that, but it's almost impossible to have you do it, or more precisely, it would take us more time to help you get it right (reliably enough to allow distribution) than to fix it ourselves. My estimate is that it will take us about 2, max 4 hours. If you want to sponsor it, we'll prioritize it to do it within 3-5 days.

**Comment by kingjordan** [comment]
I see, thanks for the follow up, how much would it cost to sponsor the
issue?

Jordan

On Tue, Feb 9, 2016 at 11:56 AM, iJungleboy <notifications@github.com>
wrote:

> Sorry about that, but it's almost impossible to have you do it, or more
> precisely, it would take us more time to help you get it right (reliably
> enough to allow distribution) than to fix it ourselves. My estimate is that
> it will take us about 2, max 4 hours. If you want to sponsor it, we'll
> prioritize it to do it within 3-5 days.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/2sic/2sxc/issues/440#issuecomment-182003563>.
>



-- 
Jordan King
*KRISIS KONCEPTS*
*Owner / Lead Developer*

jordan@krisis.ca
*WWW.KRISIS.CA <http://WWW.KRISIS.CA>*


*Twitter: KrisisKoncepts <https://twitter.com/KrisisKoncepts>*

*Facebook: KrisisKoncepts <http://www.facebook.com/KrisisKoncepts>*
*Pinterest: KrisisKoncepts <http://www.pinterest.com/KrisisKoncepts/>*

**Comment by iJungleboy** [comment]
@kingjordan check http://2sxc.org/en/Contact

**Comment by vohedge** [comment]
When do you plan to work on this ticket ?
We want to try this mdule our new DNN sites on Azure.

**Comment by iJungleboy** [comment]
@vohedge sometime soon - but I can't give you any date since nobody is currently commited (to do or pay it).

**Comment by nikki2820** [comment]
Also having many issues with Azure and 2sxc. I was able to get 8 to install (after getting this same error), but get different errors and am unable to add any templates. I'm thinking the two are related.

**Comment by iJungleboy** [comment]
this is possible. the error is actually fairly trivial and has to do with keeping versions of changes in a separate table for future restore. We had fixed it a while back but forgot that in cases where the old install still runs, it will have commands in it not supported any more. We'll try to prioritize...

**Comment by iJungleboy** [comment]
Good news guys - it's almost done...

**Comment by iJungleboy** [comment]
Done, will be in release 08.04.00j or newer 
Please test and give feedback, very, very important. 

I also wrote a blog about this, for other, non-standard upgrade paths
http://2sxc.org/en/blog/post/moving-existing-2sxc-installations-from-azure-sql-12-to-azure-sql-14

**Comment by iJungleboy** [comment]
Sorry, wrong link
http://2sxc.org/en/blog/post/moving-existing-2sxc-installations-from-azure-sql-11-to-azure-sql-12

**Comment by kingjordan** [comment]
Fantastic! I will test tomorrow morning and let you know how it goes.
Thanks.

On Mon, Apr 18, 2016 at 12:20 AM, iJungleboy <notifications@github.com>
wrote:

> Sorry, wrong link
>
> http://2sxc.org/en/blog/post/moving-existing-2sxc-installations-from-azure-sql-11-to-azure-sql-12
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/2sic/2sxc/issues/440#issuecomment-211223581>
>



-- 
Jordan King
*KRISIS KONCEPTS*
*Owner / Lead Developer*

jordan@krisis.ca
*WWW.KRISIS.CA <http://WWW.KRISIS.CA>*


*Twitter: KrisisKoncepts <https://twitter.com/KrisisKoncepts>*

*Facebook: KrisisKoncepts <http://www.facebook.com/KrisisKoncepts>*
*Pinterest: KrisisKoncepts <http://www.pinterest.com/KrisisKoncepts/>*

**Comment by kingjordan** [comment]
I followed the blog and updated my dnn 2sxc.  It all works now.  I added, edited and created content all without errors on my azure environment.  Great job and thanks.  I wish I could give you a high five!

**Comment by iJungleboy** [comment]
Awesome, thanks for the feedback :+1:
