### ISSUE TITLE
App management freeze with Firefox and ie11

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#444]
After App Management -> Manage Apps in this Zone (Portal)
There is a list of apps to manage,
clicking on the name or the folder links freezes the page with IE11 or Firefox
It works fine with Chrome

**Comment by BravoSierra** [comment]
That's for 8.0.4

**Comment by BravoSierra** [comment]
And still true in 8.0.5

**Comment by iJungleboy** [comment]
Could you test if it's a popup issue? enable popups or something and/or check JS errors?

**Comment by iJungleboy** [comment]
Seems to relate to #407 - pls check & give feedback about the popup-question

**Comment by BravoSierra** [comment]
Please read : 'No this is not the reason; my popups ARE permitted...'

**Comment by iJungleboy** [comment]
Could reproduce, working on it...

**Comment by iJungleboy** [comment]
This was very tricky! Problem was that IE and FF didn't parse the ui.html any more as it was already in the page somewhere. Nasty! Had to add a timestamp to ensure it works...
