### ISSUE TITLE
custom tokens don't show up in Edit HTML Template

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#445]
There is a handy list of the tokens that can be used in the template editor, but the custom tokens are missing.
There was a list of custom tokens above 'Additional content tokens' in v.7+
It was very convenient to copy and paste them into the Template during editing

**Comment by iJungleboy** [comment]
Yes, I understand. The problem is that this is one of the "old" dialogs not converted yet. Will look into it...

**Comment by iJungleboy** [comment]
same as #400
