### ISSUE TITLE
Export icon in Apps management always exports the first App

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#450]
In App management, the export icon on the row of any App will always export the first App in the list. 
(note : fortunately, the Delete icon works correctly and prompts the confirmation to delete the correct App).

**Comment by BravoSierra** [comment]
Obviously there is something special with my sandbox machine. I cannot reproduce either on a more stable environment. Please consider the below if it helps;, discard / close otherwise, I'll report after further investigations

I have 3 different behaviors depending on the browner:

- Google tries to export the first App in my list (as reported above), with the path below (with wrong AppId): 
http://dnndev.me/fr-fr/Page2sic/Page1/mid/1410/ctl/appexport/appid/1002?popUp=true

- Firefox developper throws a path error :  http://dnndev.me/Default.aspx?tabid=1086&error=Impossible+de+trouver+une+partie+du+chemin+d%27acc%C3%A8s+%27C%3a\inetpub\wwwroot\dnn742\Portals\0\2sxc\Secondaire%27.

- IE freezes

**Comment by iJungleboy** [comment]
I wasn't able to reproduce this either, so I'll close it.
