### ISSUE TITLE
Export parts of an App XML File missing the closing '>'

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#451]
</AttributeSets>
  <Entities />
  <PortalFiles />
</SexyContent

Expecting '>'

**Comment by BravoSierra** [comment]
Note: it can also end fewer words like  </SexyCo and I even got a file ending with </Sex

**Comment by iJungleboy** [comment]
Sounds very strange and unusual - especially if it's just missing some characters. Any idea what causes it?

**Comment by BravoSierra** [comment]
I've just done it 11 times and no XML file gets the closing tag  '>'
I've done it from different machines, with Chrome and Firefox
Any given App gives the same result. On 2 of them I always get a final  </SexyContent and on another I get just the </SexyCo part
Looks likes the file was sent before it gets closed or some missing EOF or something weird like this

**Comment by raphael-m** [comment]
I'm not able to reproduce this but I think a `Response.Flush()` is missing. I'll add it, please test it again in the next release.
