### ISSUE TITLE
Permission with user with only edit module right in DNN

### ISSUE THREAD

**Issue by manthoine** [2sic/2sxc#459]
Hi.
I have an issue with a user which has only permission to edit 2sxc module.
When we click on edit item (or even other like add...), we get an horrible popup that prompt us for enter credentials.
It's seems to be related to the EntitiesControllers and his [DnnModuleAuthorize(AccessLevel = SecurityAccessLevel.Admin)] tag.
Maybe I'm not understanding very well, but maybe "not admin user" can't edit content ?
By the way I'm on v8.0.5.0
It was working in precedent version (7.xxx)

![image](https://cloud.githubusercontent.com/assets/483723/11338707/f7ba8b30-91f5-11e5-93cf-46f584e46bff.png)

![image](https://cloud.githubusercontent.com/assets/483723/11338754/38003dc0-91f6-11e5-8bba-047ab10af974.png)

**Comment by iJungleboy** [comment]
Probably a security mistake - it should be editable for normal users.

**Comment by iJungleboy** [comment]
...should be fixed in 1-2 days... :)

**Comment by manthoine** [comment]
awesome !
