### ISSUE TITLE
Could not import the app / package: Sequence contains more than one matching element

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#460]
This is a message I get when trying to import an entire App with multiple Content-types and Templates.  If I create a new App, and then make a partial Import with the  App.xml that is extracted from the ZIP, it works but does not import the templates.  

"Sequence contains more than one matching element" is typically an error when a FirstOrDefault query retrieves more than one entity? Unfortunately the the message is not verbose, could we get a bit more info on what is blocking the entire App import? Thanks
  
The workaroung is to make a partial import into a fresh App and to manually copy the templates.

**Comment by raphael-m** [comment]
I tested the import / export with a few apps and can't reproduce this. Could you send us the app zip which is causing the problem?

**Comment by BravoSierra** [comment]
example

 

Benoît SARTON

 <http://www.bsi.fr/> www.bsi.fr

04 66 30 00 00

 

De : Raphael [mailto:notifications@github.com] 
Envoyé : mercredi 2 décembre 2015 09:21
À : 2sic/2sxc
Cc : BSI
Objet : Re: [2sxc] Could not import the app / package: Sequence contains more than one matching element (#460)

 

I tested the import / export with a few apps and can't reproduce this. Could you send us the app zip which is causing the problem?

**Comment by iJungleboy** [comment]
Since we had some issues with exporting related entities this may be fixed. Pls re-export and re-try, then give feedback. Otherwise we'll assume it's fixed.
