### ISSUE TITLE
Template location selector is not enabled (in edit template)

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#462]
in Edit Template the Template location is inactive. This is what the help says:
Portal File System: The template file is located in the current portal folder
Default File System: The template file is located in the /Portals/_default folder.

Only the default 'Portal File System' is possible. Any way to activate the second option for _default folder? Any chance to set that in the database if not in the UI? Thanks

**Comment by iJungleboy** [comment]
You can do it in the EAV - just [enter debug-mode](http://2sxc.org/en/Blog/post/advanced-dynamic-data-content-understanding-content-type-scopes) and look at the scope "2SexyContent-System" - there you'll find the template defining entities....
![image](https://cloud.githubusercontent.com/assets/5321186/11390091/bc6001f8-9346-11e5-861d-e743977d86cb.png)
