### ISSUE TITLE
Can't access module settings after update to v8.0.5.0

### ISSUE THREAD

**Issue by manthoine** [2sic/2sxc#463]
Hi.
Since my update to v8.0.5.0 I get an error message when I try to access module parameters.

![image](https://cloud.githubusercontent.com/assets/483723/11361910/c7d13dc4-9290-11e5-8ad9-903c06fc11b9.png)

**Comment by manthoine** [comment]
Maybe it's related to the lack of module settings in the last build ?
I can't see settings.ascx in the last solution and in my dnn there is a definition for it.
Perhaps a procedure to remove it during the upgrade is missing.

![image](https://cloud.githubusercontent.com/assets/483723/11364012/b3781df4-929d-11e5-996e-673e0133c4b4.png)

**Comment by manthoine** [comment]
I confirm that if I remove the settings definition in the module, the error disapear.

**Comment by iJungleboy** [comment]
thanks - what do you mean "access module parameters" - what exactly are you doing?

**Comment by manthoine** [comment]
I mean DNN module paramters like permissions, etc 

![image](https://cloud.githubusercontent.com/assets/483723/11370461/29b7e97e-92c4-11e5-9f08-31a05259d16d.png)

**Comment by iJungleboy** [comment]
Gotcha - module settings :)

**Comment by manthoine** [comment]
yes ! settings was the RIGHT word ;)
Sorry ^^'

**Comment by Frankwalraven** [comment]
here the same

**Comment by iJungleboy** [comment]
Can confirm - same...

**Comment by iJungleboy** [comment]
Same as #432 - will close this
