### ISSUE TITLE
Discuss: Ghost Content-type not exported in Full App export

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#464]
Ghost content type is not exported, but its attributes in the AssignmentObjectType are, so when importing there are messages like 'AttributeSet not found'.

Suggested behavior : export Ghost Content-type as well as real ones in a full export.

**Comment by iJungleboy** [comment]
I would recommend a slightly different behavior - as this is only important for ghost-content-types which are not automatically added by the system. So only ghosts of a type which doesn't have "AutoCreate" enabled should be exported along - but only as an anchor (so without the definition).

**Comment by BravoSierra** [comment]
What I would expect is a line like this one - nothing more:

<AttributeSet StaticName="04663000-9896-bbbb-0000-000000000003" Name="Article3" Description="" Scope="2SexyContent"  UsesConfigurationOfAttributeSet = "401"  />

In SQL language that would translate as:
INSERT INTO ToSIC_EAV_AttributeSets VALUES ('04663000-9896-bbbb-0000-000000000003', 'article3', '2SexyContent', 'description of Ghost CT', 1, xxx(appid), yyy(attributesetid original),0)

What is interesting here is that the linked attributeSetId can belong to an Appid of another Zone, which means that the content type definition can be shared accross DNN Portals. 

For security this probably means that Portal 0 (or any other) should be owned by Host and only serve the purpose to register Content-Type définitions, so a portal admin could not delete the master and leave Gosts orpheans

Does that make sense for you?

**Comment by BravoSierra** [comment]
Note : there is a Relationship FK_ToSIC_EAV_AttributeSets_ToSIC_EAV_AttributeSets so I suppose that it is not possible to delete a master CT if there are Ghosts accross portals, which is a good thing.

**Comment by iJungleboy** [comment]
@raphael-m must discuss

**Comment by iJungleboy** [comment]
Replaced by #475
