### ISSUE TITLE
View Image Link in Editor Causing "Required Parameter Missing from URL" Errors

### ISSUE THREAD

**Issue by grayspace** [2sic/2sxc#468]
Just started testing 2sxc 8.0.5 in our dev environment (DNN 7.4.2), and noticed when you click on the view image link below an image input field...

![view-image](https://cloud.githubusercontent.com/assets/5733194/11370141/f791714a-9287-11e5-8976-1ec39a4e29df.jpg)

It causes a series of JavaScript errors:

![errors](https://cloud.githubusercontent.com/assets/5733194/11370195/3bef1c34-9288-11e5-8768-482222a4ee5b.jpg)

The link then opens another window pointing to "/desktopmodules/tosic_sexycontent/dist/dnn/ui.html".

8 is looking great btw!

**Comment by grayspace** [comment]
This is also happening with URL fields as well.

**Comment by iJungleboy** [comment]
@raphael-m you assumed that if the module isn't registered any more, it's removed. It seems not to be the case. Here's an (old) forum post about it - maybe there is something newer, but if not, then it needs code... http://www.dnnsoftware.com/forums/threadid/435181/scope/posts/module-manifest-remove-a-control
