### ISSUE TITLE
FR language pack in v8.0.5.0 install

### ISSUE THREAD

**Issue by manthoine** [2sic/2sxc#469]
I am a new user of bower, so I can't see why these files are not include in the dist.
![image](https://cloud.githubusercontent.com/assets/483723/11371743/5f2fe600-92ca-11e5-8f1c-848d8316b8cf.png)

**Comment by iJungleboy** [comment]
I'm pretty certain you're confusing something. FR is ready and will be in 08.00.06 - to be release today or next Monday.

**Comment by manthoine** [comment]
Ok, I'm looking forward to test this new version.
I would like to take this opportunity to congratulate you for your module.
I can not conceive a new instance of DNN without it.
Also thank you for your responsiveness :)
