### ISSUE TITLE
Editing window much too small in v8 for text editing with rich text editor

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#470]
Our users are very happy with the new v8 UI for editing! One downside tough, the size of the popup to edit long texts is much too small and cannot be resized. This quickly leads to the double vertical scrollbar (popup + editor) with a very small editing space)
![capture](https://cloud.githubusercontent.com/assets/5261858/11373485/caa0ff5c-92d2-11e5-972b-ef817de25b30.JPG)

**Comment by BravoSierra** [comment]
We have an iframe with only 156 pixel vs 400 pixels before. Most probably on our side (CSS or CKEditor customisation). Please discard until we report the cause. Most probably you can close then. Sorry.

**Comment by BravoSierra** [comment]
It seems that the problem comes from the iframe container for the WYSIWYG CKeditor. With the DNN RAD editor the container adapts nicely and the iframe takes a correct height. But with CKEditor it does not, no matter the settings of CKE. Not sure where it takes the value of 156 pixels from.

**Comment by iJungleboy** [comment]
So to ensure we're talking about the same thing:
1. Working with rad-editor works
2. working with CK works (you can edit/save) but it causes the iframe to be too small, so it's not practical

**Comment by BravoSierra** [comment]
That's correct.
Another detail that can help is that we have a slight height difference beetween Firefox and Chrome. It is unpractical and too small in both cases, but I assume that the browser is trying something (in vain) to adjust the necessary height required by the editor.

**Comment by BravoSierra** [comment]
It's worse than we tought: not only is the iframe too small, but even worse the content is lost after editing so practically, CKEditor does not work with 2sxc. I think that this is a priority issue, thanks.

**Comment by iJungleboy** [comment]
Ok, thx!
Will merge with #411
