### ISSUE TITLE
Do various small facelifts from user feedback

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#471]
1.	Ensure ng-invalid without ng-untouched shows up on input fields
 ~~a.	Red border~~
b.	Maybe red exclamation icon on title
2.     ~~Reduce input left / right padding (8px) - done...~~
~~4.	Disabled Boolean-switch must be gray (not light-green…)~~
~~5. Rework disabled - maybe meke it less impressive / less visible, dim down titles etc.~~

**Comment by raphael-m** [comment]
Disabled elements:
```opacity: 0.3;
    -webkit-filter: grayscale(100%); filter: grayscale(100%);```
