### ISSUE TITLE
Wrong names group identifiers enduser edit box

### ISSUE THREAD

**Issue by Frankwalraven** [2sic/2sxc#472]
<img width="949" alt="schermafbeelding 2015-11-25 om 18 51 07" src="https://cloud.githubusercontent.com/assets/13934402/11405081/f07b9b8c-93a5-11e5-9cf4-3b67cfaf596c.png">
I think a language problem again

**Comment by iJungleboy** [comment]
This is new since 08.00.06, right?
This would be a new use case (a bit difficult to explain) - do the in-page toolbar-buttons translate, or do you see similar texts in the mouse-over?

**Comment by Frankwalraven** [comment]
![labels](https://cloud.githubusercontent.com/assets/13934402/11407772/2098855a-93b5-11e5-9746-c6d0042a7030.png)
Looks like the mouse over of the bleu content toolbar has also wrong mouse over labels. The other ones looks OK

**Comment by iJungleboy** [comment]
Figures. We only introduced in-page translations (which affect the entity-titles on the edit-dialog) in 08.00.06. Could you check 2 more things?
1. does your /dist/i18n/   correspond with https://github.com/2sic/2sxc/blob/master/src/i18n/inpage-en.json - specifically does it contain the section "Toolbar"
2. does your browser try to retrieve the en-version, or does it skip that?

**Comment by Frankwalraven** [comment]
<img width="857" alt="schermafbeelding 2015-11-25 om 21 20 15" src="https://cloud.githubusercontent.com/assets/13934402/11408600/8b5cffb0-93ba-11e5-9d94-88cb3da7b05c.png">
Don't see /inpage-en.json

**Comment by Frankwalraven** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found)
2sxc.api.js:186 Object
2sxc.api.js:190 just fyi: failed to load language resource; will have to use default
tooltipbootstrapper.js:1 tooltipBootstrapper.cs: tt_process got a response of false
2sxc4ng.min.js:3 creating sxc service for id: 589

**Comment by Frankwalraven** [comment]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2sxc.api.min.js:3 [object Object]
2sxc4ng.annotated.js:123 creating sxc service for id: 563

**Comment by Frankwalraven** [comment]
I mailed the credentials of the site again so you can login and see
http://www.perfocusdemo.nl/inloggen
