### ISSUE TITLE
ImageResizer is awfully slow on some servers

### ISSUE THREAD

**Issue by bktoday** [2sic/2sxc#474]
Hi,

I'm currently investigating an issue with the ImageResizer being awfully slow on some machines.
You can even see the same effect on http://2sxc.org/learn-extensions/ImageResizer , where each ImageResizer-image takes about 2000 ms to load - with the images visually popping in one after the other.

This may have to do with the IIS version or the TinyCache plugin. I tested on two separate servers, one running IIS 7.5, the other one running IIS 8.5 with almost identical hardware and configuration.. 

In the original DNN installation on the IIS 7.5 server, everything's running fine: Each image is rendered and supplied in about 100-160 ms by 2sxc/ImageResizer (original image size ~200kb) - I guess they come from the TinyCache. When I mirror/copy the exact same DNN installation to the IIS 8.5 server, the same images suddenly take around 1000-1500 ms to render and load (each), obviously not cached.

To further investigate the issue, I disabled all compression and IIS caching on both servers. The performance difference between the two installations stayed the same. Since there are only three images used on the entire site, I doubt that the 30 MB (?) TinyCache is full.

Bug or feature? :-) I'd be happy about any hint...

**Comment by iJungleboy** [comment]
It looks like you discovered some kind of important issue. Not sure if it's configuration (maybe the cache isn't even in use), missing code or bug. I would appreciate it if you would research it more.

**Comment by iJungleboy** [comment]
What's a bit strange btw is that the link you sent does feel slow (even on 2sxc.org), but on other pages like http://2sxc.org/en/Blog it feels ok.

**Comment by bktoday** [comment]
Wow, you're right. That makes the effect even stranger - a different behavior even across the same installation..!

I tried to narrow the issue down by comparing the measureable effects on both installations I'm testing on. Disappointingly, I got nothing so far: The ImageResizer.Plugins.TinyCache.dll seems to be running on both machines, the tiny_cache.cache file is being written and is properly restored/rewritten as soon as one deletes it manually, at least after a couple of page loads. The size of the tiny_cache.cache is the same on both machines. So far, I can see no differences - except for the described effect in the loading time.

To make it worse: Even when I delete ImageResizer.Plugins.TinyCache.dll from the \bin directory, delete tiny_cache.cache from \App_Data and restart the whole DNN Application in IIS on the faster installation (in this case there should be zero caching here), I still get load times around 140ms on the faster machine. In the meantime I doubt, that it has to do with the caching at all. Still I wonder if TinyCache is really running at all, when it's deletion makes no measureable difference, at least in this scenario here...

I guess I'll have to dive a little deeper in the next few days... Please keep me updated when you find any clues on your site.

**Comment by raphael-m** [comment]
The issue is probably a bug in the TinyCache plugin. I installed the DiskCache on 2sxc.org which solves the problem, all images are processed very fast after the initial request.

**Comment by iJungleboy** [comment]
We'll review including the powerful cache in the future, as it's now fully open source. It's just that the AGPL might bother some people, but for 2sxc it would be awesome and no license issue. 
Will close for now.
