### ISSUE TITLE
Get Ghost-content types to export and import if they are not "auto-inherit" (paid)

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#475]
Or review scenario with auto-inherit --> discussed, auto-inherit not an option

Concept

1. Export an xml-tag, but refer to the original using the original Guid (not the record-id)
2. Import would look for the content-type with that guid, and not having an "use..." itself (so it's a master)
3. Import would check if the master exists and use that. if it finds many, it will use the first, and display a warning

**Comment by BravoSierra** [comment]
Questions and suggestions:

1. How does the export know if we want a Ghost or a Real CT? We can assume that if the CT is already a Ghost, the export will export as Ghost, but how to create the first Ghost? (i.e. there is no Ghost yet in the AttributeSets table for that CT, we want to create the first one) That can be easily done manually in the DB but need to think about an option in the interface.

2. Would it make sense to only allow Masters in the  default zoneid (or Appid 1?). This would avoid cross Portals issues, e.g. what if an admin deletes a master CT in a portal other than DNN's _default

3. Should Ghost Content-types share their templates entities and values, or each have their own. Example : a Content-type has a String Attribute with a Dropdown input type, this dropdown contains values. Should these values considered metadata attached to the Content-type and shared, or per-content type instances individual values

**Comment by iJungleboy** [comment]
@BravoSierra since ghost-content-types are a very advanced feature hey basically don't work in a normal app-export-import but will usually be very installation specific - because as you noted the ghost won't work unless the original exists. Since it's impossible to cover all use cases (not even with 100h budget :). we'll assume that ghost-export/import is 

1. needed on a multi-portal scenario where users want to duplicate a kind of app in every portal
2. when migrating such a scenario to another system

So that's what we're going for. There will be no "first ghost" as the master is a very normal content-type. So the export only differentiates between normal or ghost-without-auto-distribute. That's it. They share the master configuration.

**Comment by BravoSierra** [comment]
I agree, thanks

**Comment by raphael-m** [comment]
Done for [8.0.7](https://github.com/2sic/2sxc/releases/tag/v08.00.07). One thing to notice: When you add or remove attributes to / from a master content-type, the changes won't be reflected to the inheriting content-types until the DNN application is restarted (the reason is that each 2sxc app has its own cache).
