### ISSUE TITLE
Think of a way to allow both language (fr) and culture (fr-be) to be internationalized

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#479]
Background: currently our language packs are `[package]-[2-letter-code].js`. And the fallback is `[package]-en.js`

Better would be if it would try first `[package]-[2-lang]-[2cult].js` and if that fails, use `[package]-[2lang].js` and if that fails, then `[package]-en.js`.

Core problem is that it shouldn't try to download all these and cause loads of http-404 errors. There are various approaches I can think of

1. try to load the package-fr-be.js and then try to load the package-fr.js and then load the package-en.js. This is the basic form but IMHO sucks. Would require some changes to angular-translate as it only forsees a 1-language fallback?
2. include a list of existing languages in angular-translate so it only tries to retrieve the translated languages if it exists (probably a good idea)
3. pre-create language packs like merging a `-fr-be.json` (containing just a few keys or nothing at all) with the `-fr.json` to ensure all sub-cultures have a language pack...

...still not quite solved...

**Comment by BravoSierra** [comment]
I'm not sure if there's a real use case to have to different language packs with same language and  different culture (I know that Potatoe does not translate the same in Germany and Austria but is that a real issue for a 2sic admin?) . The discussions we have with our customers about cultures are all about flags and how letters are displayed, but I've never had problems with the translation itself (The Swiss speak more slowly but that doesn't affect language packs :)

**Comment by iJungleboy** [comment]
I think @BravoSierra is right and that it's not important for now, close.
