### ISSUE TITLE
Required parameter (portalroot) missing from url - cannot continue with pipeline editor

### ISSUE THREAD

**Issue by nicpitsch** [2sic/2sxc#480]
The error 'Required parameter (portalroot) missing from url - cannot continue' raises when trying to open the Pipe designer within 'Visual Queries / Pipelines'. The url is http://mydomain.com/desktopmodules/tosic_sexycontent/dist/dnn/ui.html#dialog=pipeline-designer&appId=3&pipelineId=559&zoneid=2&tid=55&mid=415&lang=en-us&langpri=en-us&langs=[{%22key%22:%22en-us%22,%22name%22:%22English%20%28United%20States%29%22}].
Environment:
- Completely fresh DNN 7.4.2 installation.
- 2sxc 08.00.06.
Same error also with other DNN installations where 2sxc was updated from earlier versions 08.00.06.

**Comment by iJungleboy** [comment]
Just a quick question: which url module are you using? the old or the new one from dnn 7?

**Comment by nicpitsch** [comment]
It's just a fresh DNN 7.4.2 installation, no changes to any system settings. What do you mean with *url module*? I see this library-extension installed *DotNetNuke Corporation URL Management module 7.4.2*.

**Comment by iJungleboy** [comment]
Ok, thx. There is an old url-provider out there so I wasn't sure if that was the issue. I'll look into it...

**Comment by nicpitsch** [comment]
Same problem is discussed here: http://sexycontent25.rssing.com/chan-22595164/latest.php. Was that ever solved?

**Comment by nicpitsch** [comment]
Further Testing:
- Completely fresh DNN 7.4.2 installation.
- Install 2sxc 07.02.03.
- Import App 2sxcApp_News-Simple_01.00.01.zip.
- Open Visual Query Designer.. Open Designer for All News Sorted pipe. Alert: Please specify an AppId.
![2015-12-04_14-28-37](https://cloud.githubusercontent.com/assets/1652835/11590933/2c6b0f0c-9a94-11e5-98de-e8a5b755f5b2.jpg)

**Comment by iJungleboy** [comment]
@nicpitsch thanks for the detailed testing. was able to reproduce and fix in next version.
