### ISSUE TITLE
Telerik-RadEditor (wysiwyg) blocks invalid content - so save not possible

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#483]
[problem-wysiwyg-text with vertical-tab.txt](https://github.com/2sic/2sxc/files/47217/problem-wysiwyg-text.with.vertical-tab.txt)
Had a content which was copy-pasted from one-note. It contained a vertical tab which I didn't see (here in notepad):
![image](https://cloud.githubusercontent.com/assets/5321186/11470426/c85b4362-975d-11e5-95da-a11f49e34509.png)

It appears that in this case - and maybe other invalid-html-cases - the editor doesn't return the content to formly, so saving is either impossible or blank or old. In my case the value didn't exist in the posted JSON, so the server returned an error

**Comment by raphael-m** [comment]
In my tests the value is correctly posted to the server, but when the server tries to convert the entity to XML (for the entity history) it fails because of this value.

**Comment by raphael-m** [comment]
Possible solution: Remove invalid XML characters from every EAV value passed to the database. http://stackoverflow.com/a/14323524
