### ISSUE TITLE
html editor view - whole website loaded

### ISSUE THREAD

**Issue by dnastone** [2sic/2sxc#486]
hello,
when i click on edit content i see the html editor + my whole site gets loaded too at the overlay window.

best regards

michael

**Comment by iJungleboy** [comment]
This is a dnn-setting. We're forced to load the wysiwy as a popup in the iframe. You must have popups disabled, then dnn redirects the iframe to a full page. Pls enable popups.

**Comment by dnastone** [comment]
i looked into my site settins - but the checkbox for the pop pups are checked.

**Comment by iJungleboy** [comment]
could you check the urls which are being loaded? like to see if it first tries to load a ...?...popUp=true and then redirects to another url? using fiddler...

**Comment by dnastone** [comment]
i have no expirience with fiddler. i'm using at google chrom for debugging.

there i get some 404 error for files:
http://new8.aevo.at/desktopmodules/tosic_sexycontent/dist/i18n/sxc-admin-de.js 404 (Not Found)

http://new8.aevo.at/desktopmodules/tosic_sexycontent/dist/i18n/edit-de.js 404 (Not Found)

http://new8.aevo.at/desktopmodules/tosic_sexycontent/dist/i18n/sxc-admin-de.js 404 (Not Found)

**Comment by iJungleboy** [comment]
those are the translation files - not interesting for now. you should have a dnn-url like /yourpage?ctl=...bridg...&loads of params

**Comment by dnastone** [comment]
you mean the url from the frame (lay over window):

http://new8.aevo.at/desktopmodules/tosic_sexycontent/dist/dnn/ui.html#zoneId=2&appId=4&tid=55&mid=451&lang=de-de&langpri=de-de&langs=%5B%7B%22key%22:%22de-de%22,%22name%22:%22Deutsch+(Deutschland)%22%7D%5D&portalroot=http:%2F%2Fnew8.aevo.at%2F&websiteroot=%2F&approot=%2FPortals%2F0%2F2sxc%2Fp-performance%2F&dialog=edit&mode=edit&items=%5B%7B%22Group%22:%7B%22Guid%22:%222091c2f7-5a8b-4a35-8b5b-eb7f6512a4e9%22,%22Index%22:0,%22Part%22:%22content%22,%22Add%22:false%7D,%22Title%22:%22EditFormTitle.Content%22%7D,%7B%22Group%22:%7B%22Guid%22:%222091c2f7-5a8b-4a35-8b5b-eb7f6512a4e9%22,%22Index%22:0,%22Part%22:%22presentation%22,%22Add%22:false%7D,%22Title%22:%22EditFormTitle.Presentation%22%7D%5D

**Comment by iJungleboy** [comment]
that's the first one. but the iframe (where you have the wysiwyg) has a url too. and probably loads/redirects so probably more than 1 url

**Comment by dnastone** [comment]
that's the url from the wysiwyg editor:
new8.aevo.at/handler/testseite/ctl/webformsbridge/mid/458/type/wysiwyg?popup=true

**Comment by iJungleboy** [comment]
There is something just a tiny bit wrong with the url. Did you copy-paste or type it? DNN has a bug which requires popup to be written as popUp - how is it written on your system?

**Comment by dnastone** [comment]
i copied the url from the site - right mouse click - frame source.

i don't know what do mean with that:
"how is it written on your system"

**Comment by iJungleboy** [comment]
so it really says "popup=" and not "popup="?

**Comment by dnastone** [comment]
how can i test it - "popup=" and not "popup="?, cause it's your code from your module?

**Comment by iJungleboy** [comment]
Sorry, spelling mistake. The question is if the Up has a large "U" or not. so p o p u p is wrong, p o p U p is right. You can see what request is being made.

**Comment by dnastone** [comment]
i installed fiddler and keep the sessoin:

at fiddler the request looks like this:

GET /?tabid=55&ctl=webformsbridge&mid=451&popUp=true&type=wysiwyg HTTP/1.1

**Comment by dnastone** [comment]
i found another request too:

GET /home/ctl/webformsbridge/mid/451/type/wysiwyg?popup=true HTTP/1.1

**Comment by iJungleboy** [comment]
That answers it! Darn !!!!
Is it correct (just need to verify) that the first popUp has a large U, the second one a small U?
Could you do a quick test and type in these two addresses in a browser window (after login) to verify...
[yourdomain]//home/ctl/webformsbridge/mid/451/type/wysiwyg?popup=true - should show the entire page
[yourdomain]/home/ctl/webformsbridge/mid/451/type/wysiwyg?popUp=true - should work correctly because of the large U

**Comment by dnastone** [comment]
i typed this url's in google chrom:
http://new8.aevo.at/home/ctl/webformsbridge/mid/451/type/wysiwyg?popup=true - i see the wysiwyg editor at the whole page

with that url:
http://new8.aevo.at/home/ctl/webformsbridge/mid/451/type/wysiwyg?popUp=true

i only see the wyswyg editor

**Comment by dnastone** [comment]
i have a other question: 
do you have a forum for 2sexycontent where i can ask question when i need help with building templates?

**Comment by iJungleboy** [comment]
@dnastone for your last question, this is currently the codeplex forum http://sexycontent.codeplex.com/ - we would like something better, but don't have it yet

**Comment by iJungleboy** [comment]
@dnastone do you have a special module to configure lower-case URLs? Because most installations don't seem to do what yours does.

**Comment by iJungleboy** [comment]
Could you try the following url for me (I'm hoping it doesn't get rewritten)
[yourdomain]/default.aspx?tabid=55&ctl=webformsbridge&mid=451&popUp=true&type=wysiwyg

**Comment by dnastone** [comment]
i'm using for all my portals this open source module:
https://dnnurlmanagement.codeplex.com/

there i configure - "Convert DNN URLs To Lower Case"

**Comment by dnastone** [comment]
i put htis url at my browser:
http://new8.aevo.at/home/ctl/webformsbridge/mid/451/type/wysiwyg?popup=true 

but the editor gets loaded with the whole site.

**Comment by dnastone** [comment]
when i turn off the option at the url management module it works with that url

http://new8.aevo.at/Home/ctl/webformsbridge/mid/451/type/wysiwyg?popUp=true

**Comment by dnastone** [comment]
i found a configuration at the module:
Prevent Lowercase: 
there i put the pattern "/webformsbridge/" and then it works too.

**Comment by iJungleboy** [comment]
thanks for that feedback. Just a question - before you made it work by adding the exception, did you try the url with default.aspx like 
`[yourdomain]/default.aspx?tabid=55&ctl=webformsbridge&mid=451&popUp=true&type=wysiwyg`
? that would help to see if this would prevent the redirector or not.

**Comment by dnastone** [comment]
i cleared the pattern /webformsbridge/
and put this url in the browser:
http://new8.aevo.at/default.aspx?tabid=55&ctl=webformsbridge&mid=451&popUp=true&type=wysiwyg
it gets redirected to this and the whole site + editor are shown:
http://new8.aevo.at/home/ctl/webformsbridge/mid/451/type/wysiwyg?popup=true

**Comment by iJungleboy** [comment]
ok, thx. Could you create the exception on the popup-parameter (instead of the webformsbridge) - because all dialogs with popup shouldn't be rewritten and try that?

**Comment by dnastone** [comment]
i create a pattern with "/ctl/"
i think you need that parameter for every change?

**Comment by iJungleboy** [comment]
We do, yes. But other dialogs also need the popup, so I would recommend that as the marker.
