### ISSUE TITLE
"Add item" does not work without reloading page after inserting a module

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#488]
When a new module is inserted, the "add item" button is not visible (even if the template is a list template). It works after a page reload.

**Comment by iJungleboy** [comment]
Reason: in the module-header there are various infos like IsList etc. which are outside of the ajax-reloaded template. This would have to be refreshed for the toolbar to pick it up.

**Comment by reaxx999** [comment]
its very confusing to my customers.pls prio :)

**Comment by iJungleboy** [comment]
this is now solved in 8.4
