### ISSUE TITLE
Entering DNN Module settings on a 2sxc module : server error 500 

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#494]
Critical issue after migration from v7 to v8 (currently v 8.0.6)
After migrating from v7 to v8 we cannot enter the DNN module settings (error 500) on 2sxc modules.
All other modules have module settings right.
This has been observed on 3 different DNN instances.
This issue does not appear on a fresh install so it might be an upgrade issue.
 
 
AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:28959da8-6c96-4ab0-8477-0a9b25c909fa

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

ExceptionHash:dg6wfwUoovZv4Y68h1NADw==

Message:Could not load type 'ToSic.SexyContent.Settings'.

**Comment by BravoSierra** [comment]
Any idea how to correct the 'ToSic.SexyContent.Settings' to fix this critical issue afterwards?
Thanks!

**Comment by iJungleboy** [comment]
Quick fix is documented in #432, but will be fixed in next release.
