### ISSUE TITLE
Cannot delete an item in Data management

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#506]
server status 500
![capture](https://cloud.githubusercontent.com/assets/5261858/11587545/88e1b14c-9a7a-11e5-83d1-2907fe4ce6d4.JPG)

**Comment by iJungleboy** [comment]
Very often this item is in use - could you check the message in fiddler / js-console to see what the error is?

**Comment by iJungleboy** [comment]
Presume fixed in 8.1; close.
