### ISSUE TITLE
2sxc includes Angular in "no-edit" mode if user can edit the module

### ISSUE THREAD

**Issue by janjonas** [2sic/2sxc#519]
Due to the changes in https://github.com/2sic/2sxc/issues/391 2sxc includes Angular and a lot of other JavaScript resources even if the user is not in edit mode which breaks existing websites that also include Angular and maybe need to include another Angular version (for example due to browser compatibility reasons). This problem is similar to #382. 

Are there any plans to change this behavior to make 2sxc more compatible to other modules, skins and whatever?

**Comment by iJungleboy** [comment]
We would love to change it - but need someone to contribute some resources :)

**Comment by iJungleboy** [comment]
So if anybody would sponsor this - I believe it's about 1.5 days of work. Then 2sxc would only run in various iframes in the page and would not include any angularjs any more.

**Comment by janjonas** [comment]
@iJungleboy: I sent you a message using your contact form (http://2sxc.org/en/Contact). Please contact me with more details :).

**Comment by iJungleboy** [comment]
I was on vacation and don't read my e-mails :). Just wrote back this morning

**Comment by iJungleboy** [comment]
Will be implemented in 8.4, angular now only in iframe, so no more version conflicts
