### ISSUE TITLE
MultiLanguage: Click on Translate-Icon should do the default action "translate (unlink)"

### ISSUE THREAD

**Issue by reaxx999** [2sic/2sxc#521]
By now (8.0.0 till v8.0.9) the user always has to enter the popup menu and click on "translate (unlink)". It would be a more direct way if he could just unlink it by clicking on the symbol (like in 2sxc v6/v7), especially because this is the probably most used action.

![2sxc translate action](https://cloud.githubusercontent.com/assets/12188254/11712108/3b8760d0-9f2b-11e5-9712-cd55104adfcd.png)

**Comment by raphael-m** [comment]
Done, will behave as in previous versions in the next release.
