### ISSUE TITLE
no token list for a new content type/template  -BUG-?

### ISSUE THREAD

**Issue by c42705** [2sic/2sxc#522]
after i add a new app, a content type, their fields, a template, use the content type, and add my first item, everything is ok, until comes the time to customize the template file, there is no list of available tokens to use (see screenshot),  the tokens works, but its a drag not to have it handy... 

i think version 7 was better (more stable) this is visually nicer, **but v8 still a bit green, dont you think?**

![image](https://cloud.githubusercontent.com/assets/12698462/11726414/1bcd3c60-9f44-11e5-9fe0-0a7e93f1c2a7.png)

**Comment by iJungleboy** [comment]
This is same as #400

**Comment by c42705** [comment]
then, is this "old" template file not being trasnlated, is included in some other version arround?

**Comment by iJungleboy** [comment]
Not yet - we have to rework it to angular and didn't get to it yet - sorry :(.
