### ISSUE TITLE
js errors after upgrade to 8.0.11

### ISSUE THREAD

**Issue by dnastone** [2sic/2sxc#533]
i'm getting this errors after i upgraded from 8.0.9 to 8.0.11

Failed to load resource: the server responded with a status of 404 (Not Found)
2sxc.api.js:186 Object
http://new8.aevo.at/template-selector/template-selector.html Failed to load resource: the server responded with a status of 404 (Not Found)
2sxc.api.js:186 Object
http://new8.aevo.at/template-selector/template-selector.html Failed to load resource: the server responded with a status of 404 (Not Found)
2sxc.api.js:186 Object
http://new8.aevo.at/template-selector/template-selector.html Failed to load resource: the server responded with a status of 404 (Not Found)
2sxc.api.js:186 Object
http://new8.aevo.at/template-selector/template-selector.html Failed to load resource: the server responded with a status of 404 (Not Found)
2sxc.api.js:186 Object
http://new8.aevo.at/template-selector/template-selector.html Failed to load resource: the server responded with a status of 404 (Not Found)
2sxc.api.js:186 Object
inpage.js:5 Uncaught TypeError: Cannot read property 'vm' of undefined

**Comment by dnastone** [comment]
i installed the module again and now the error are gone.

**Comment by iJungleboy** [comment]
Thx. Will close for now
