### ISSUE TITLE
After picking an item from Popup the label is shown as data (should be the empty value)

### ISSUE THREAD

**Issue by KosVos37** [2sic/2sxc#534]
My Key / Value pairs

```
None:
Default line:<br /><hr /><br />
Line with three blocks 1:<br /><div class="dividers_1"><span></span></div><br />
Line with three blocks 2:<br /><div class="dividers_7"><span></span></div><br />
```
If I pick the default line or the lines with the blocks all works fine. If I pick "None" None will be displayed as the Value. Is my syntax wrong or what is going on?

I use the version 8.0.11, but it also went wrong with version 8.0.04 and 8.0.10
I now fixed it with:
```
None:<span></span>
```
Maybe filtering with if (value == "None") then value = String.Empty
is better
It also can have to do something with converting the data for the "old" way of storing popup values in 2sxc and the new data structure. It May kept there the values None:None. I'm just guessing...

**Comment by iJungleboy** [comment]
Probably our mistake. Did you try 
"None: " (with a space at the end)?

**Comment by raphael-m** [comment]
Done in 2sxc 08.01.03
