### ISSUE TITLE
What happens if a Content module is copied by DNN content localisation, and "DNN unlinked"

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#541]
2scx should handle localization internally and does not need the duplication mechanism of DNN.
What happens if an admin "unlinks" the translation in DNN rather than in the 2sxc module? Is there a way to prevent and/or correct this mistake?

**Comment by raphael-m** [comment]
Localization in DNN is handled with the import / export (`IPortable`) interface. When a module is *copied* to another language by DNN's localization process, it is being exported and imported again. For most modules the resulting module is a full copy of the default language module.

2sxc uses another approach. It stores a unique identifier (the *content group* guid) in the module settings which tells 2sxc what the module should display. The DNN localization process automatically copies this setting to the modules in other languages - it's the same guid for the DE, EN, FR, ... module. It does not make a difference whether a module is *linked* to the default language or if it's *unlinked*, the guid will always be the same. 2sxc looks up the current language and outputs the values accordingly.

This is the reason, by the way, why 2sxc does not implement IPortable. If you try to duplicate a 2sxc module to another page, it will still reference the same content (no independent copy).

**Comment by iJungleboy** [comment]
@BravoSierra This is a follow-up issue because of the changes we made for you :). I believe we should fix it within the same package, but here's a quick workaround for you:

1. When you create the original page (from a template or something) it doesn't have the ContentGroup yet, because this is delayed till it's needed...
2. ...so after creating thepage, click on an edit button and the close the popup dialog again. This will create the content-group but still show the default content.
3. Now create the translated pages.

@raphael-m we should change the behaviour of creating a contentgroup-guid. Basically when it is being created, the system should check if there are ANY sister-clones of the module, and register the contentgroup-guid there as well. I believe we can do this in about 2h.

**Comment by iJungleboy** [comment]
Note: The holidays have just started, so we'll be mostly offline for about 2 weeks. This should make it into 08.00.12 on January 6th.

**Comment by BravoSierra** [comment]
Thanks Raphael-m for this explanation.

The problem is the statement: "It does not make a difference whether a module is linked to the default language or if it's unlinked [in DNN localization]". In fact, it does, in the case where you Copy the module (i.e. you add it to the localized page), before you insert any content. In this case, the 2sxc module is duplicated (not shadowed). For example, in the case of a bilingual website, you end up with 4 distinct values.   

This scenario happens when the person who creates the site is not the same than the content manager, and she wants to prepare the multilingual module before any content is published.

There are 2 workarounds but none of them is very intuitive:

1. Insert fake or demo values as soon as the new module is placed onto the page, and before DNN localization
2. If it is too late, then the author will probably find that the behavior is very, very, strange, because the content she will see is a combination of the language page + the 2sxc language tab. Then the solution is to go back to DNN localization page and DNN-LINK the module.

**Comment by raphael-m** [comment]
Done in 8.0.12, please try it.

**Comment by BravoSierra** [comment]
No we do not see any change. in 8.0.12. I add a content module, I insert some text in french, I DO NOT SAVE and switch the the English tab, insert text in English, SAVE (believing it will save both french and English as it usually does when editing an existing module). And boom no way to get back edit the french dimension (because in fact it never got a value in the database).

**Comment by raphael-m** [comment]
I believe you are referring to issue #540 - this issue was not about saving the language. Could you verify this?

**Comment by BravoSierra** [comment]
You are correct, I was referring to #540, my bad. So #541 is fixed, and #540 is not. Thanks.

**Comment by iJungleboy** [comment]
Perfect :). So this is closed.
