### ISSUE TITLE
Content versioning and history

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#542]
If I remember well, it was possible to keep the history of  Content changes in v7? 
In v8 there is still a Staging / publish but is it still possible to rollback to a previous content?

**Comment by iJungleboy** [comment]
Yes and no. The data is there and all versions are being archived, we simply haven't gotten round to creating the UI for view/restore yet.

**Comment by BravoSierra** [comment]
Cool. The most important is the staging / publish steps and that seems to work fine. Thanks.

**Comment by TheDeadlyBulb** [comment]
Hello 2sxc,
Do you have rough date when the staging/publish UI will available again? That's a feature we use quite often.

**Comment by iJungleboy** [comment]
Staging / publish work well, that's always been ok. It's the view-history which is currently missing.

**Comment by TheDeadlyBulb** [comment]
Sorry I wasn't clear.  Stage / publish are peachy.  Just wondering about the view-history UI.

**Comment by iJungleboy** [comment]
We probably have a sponsor for this, I'll keep you posted...

**Comment by iJungleboy** [comment]
We have a sponsor, and are working intensively on this. We are planning to release a version very soon.

**Comment by iJungleboy** [comment]
Implemented :)

**Comment by BravoSierra** [comment]
Cool, thanks

 

Benoît SARTON

 <http://www.bsi.fr/> www.bsi.fr

04 66 30 00 00

 

De : iJungleboy [mailto:notifications@github.com] 
Envoyé : jeudi 6 juillet 2017 16:36
À : 2sic/2sxc
Cc : BSI; Author
Objet : Re: [2sic/2sxc] Content versioning and history (#542)

 

Implemented :)
