### ISSUE TITLE
Support for DNN8

### ISSUE THREAD

**Issue by jaxuk** [2sic/2sxc#546]
Is anyone working on support for DNN8 yet? 

I've found a few things which are broken (in DNN8 Beta1) and am going to have a dig through the source to see if I can address a couple of items.

**Comment by iJungleboy** [comment]
We're currently not working on it yet and would be very grateful if you could help fix them

**Comment by iJungleboy** [comment]
In general always assume that DNN8 is a first release and hard to recommend in a live environment. Give it 2 months for a larger patch to come out - we're currently trying to motivate DNN to release bi-weekly updates but the QA (Quality) is too expensive so they don't want to do that. 

So atm let's wait at least 2-3 weeks and see if DNN8 is even usable, then we'll go to it. First we'll release 2sxc 8.1 which will be pretty awesome. if you want to help then pls join us on our secret labs in fb - https://www.facebook.com/groups/2sicSecretLab/

**Comment by jaxuk** [comment]
I decided last week to go back to 7.4.2 for this project as it's becoming time sensitive and also because of basically what you just said!

I'll take a look at the group... I've got to say my first experiences of 2sxc are really positive - it's a great module - DNN's DCC is going to have to go a long way to compete with it!

**Comment by iJungleboy** [comment]
DCC: It's actually almost impossible, just wait till you see 8.1 :)
I've told them to use 2sxc - but I guess they are afraid of depending on external parties - something that has burned them again and again.

**Comment by iJungleboy** [comment]
I'll close this for now till we get real issues related to the real, released DNN 8 :)
