### ISSUE TITLE
Autosave generates strange message relating to versioning

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#547]
Occasionaly it happens that the user entering content editing is warned with a message that there was already a previously saved version, and he his offered either to discard or to compare versions.

It seems that the editor is comparing the content with an autosaved version of itself, that is almost similar, as if there where 2 different versions.

This is weird for the users who do not feel like they had a previous version (even if technically there is one from a few seconds ago). They do not understand the meaning of this warning.

I'm not sure how to reproduce, it does not happen all the time.

Maybe some extra condition somewhere  should consider an autosave as a temporary content, and not as a real former version?

Probably needs more feedback if the developer cannot reproduce. Have others notice this?

**Comment by iJungleboy** [comment]
Could you provide a screenshot? I can't remember having such a message in 2sxc. Maybe it's from another browser plugin?

**Comment by iJungleboy** [comment]
Since we don't have auto-save nor version-compare, I will continue to assume this is not a 2sxc issue and close this. Pls reopen if I'm wrong.
