### ISSUE TITLE
Not all fields are grayed out when disabled

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#559]
Does not work for file fields:

![2016-01-12_08-06-13](https://cloud.githubusercontent.com/assets/5171884/12257077/741e6d70-b903-11e5-96fc-8853cfc18c65.png)

**Comment by iJungleboy** [comment]
@raphael-m could you re-check this and fix/close?

**Comment by raphael-m** [comment]
I checked quickly on a file field and it seems to work now.
