### ISSUE TITLE
Turning the Publish switch "off" creates an error when there is only demo data

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#562]
The user does not want to edit the content now, there is only demo data, so they turn off "Publish"
This creates an error
![capture](https://cloud.githubusercontent.com/assets/5261858/12270394/3653ac0a-b956-11e5-9042-d05724095601.JPG)

**Comment by iJungleboy** [comment]
this was the same #937 - which was just resolved and will be in 8.7.1
