### ISSUE TITLE
Black pencil for Edit only works with Chrome.

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#563]
Need to use the blue pen to 'Edit' with other browsers.
![capture](https://cloud.githubusercontent.com/assets/5261858/12270526/c435ef2e-b956-11e5-8de5-a77dda5d198f.JPG)

**Comment by BravoSierra** [comment]
Note that this is related with #562 in the sense that after an error caused by #562, then #563 leaves no way to correct for a IE or Firefox user, because there are no blue admin buttons anymore and the black and yellow ones do not work.

**Comment by iJungleboy** [comment]
Could you check if this is fixed in 8.1?

**Comment by BravoSierra** [comment]
Not quite for FF :

 

2sxc 8.1 

 

Item/browser                  Firefox 43.0.4    IE 11.0.9600        Chrome 47.0.2526

Edit                                       HS                          OK                         OK

Change template           OK                          OK                         OK

Edit template                   HS                          OK                         OK

Admin                                 OK                         OK                         OK

 

 

 

Benoît SARTON

 <http://www.bsi.fr/> www.bsi.fr

04 66 30 00 00

 

De : iJungleboy [mailto:notifications@github.com] 
Envoyé : lundi 25 janvier 2016 14:58
À : 2sic/2sxc
Cc : BSI
Objet : Re: [2sxc] Black pencil for Edit only works with Chrome. (#563)

 

Could you check if this is fixed in 8.1?

**Comment by iJungleboy** [comment]
Ok, this seems to be a firefox-event-object issue.

**Comment by iJungleboy** [comment]
Found it, will be fixed in the next release...
