### ISSUE TITLE
Views/templates not working in DNN v8.0.0 RC (build 800) because of bugs in DNN :(

### ISSUE THREAD

**Issue by tvatavuk** [2sic/2sxc#564]
Add any sample 2sxc App to page in DNN v8.0.0.800 results in error in template:

_There was an error while rendering the template: System.IO.FileLoadException: Could not load file or assembly 'System.Web.WebPages, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) File name: 'System.Web.WebPages, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' at ToSic.SexyContent.Engines.RazorEngine.InitWebpage() at ToSic.SexyContent.Engines.RazorEngine.Init() at ToSic.SexyContent.Engines.EngineBase.Init(Template template, App app, ModuleInfo hostingModule, IDataSource dataSource, InstancePurposes instancePurposes, SexyContent sexy) at ToSic.SexyContent.SexyViewContentOrApp.ProcessView(PlaceHolder phOutput, Panel pnlError, Panel pnlMessage) WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog]._

It is becase of wrong assembly binding in DNN web.config:

      <dependentAssembly>
        <assemblyIdentity name="System.Web.WebPages" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-2.0.0.0" newVersion="2.0.0.0" />
      </dependentAssembly>

OK, I change it to what it was initialy in vanila web.config:

      <dependentAssembly>
        <assemblyIdentity name="System.Web.WebPages" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>

Now, I have another error:

_There was an error while rendering the template: System.Web.HttpCompileException (0x80004005): c:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\733c34c2\e29d969\App_Web__simple list of questions.cshtml.b95d1344.72m95s1t.0.cs(28): error CS0234: The type or namespace name 'DynamicContentViewer' does not exist in the namespace 'Dnn.Modules' (are you missing an assembly reference?) at System.Web.Compilation.AssemblyBuilder.Compile() at System.Web.Compilation.BuildProvidersCompiler.PerformBuild() at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound) at System.Web.Compilation.BuildManager.GetCompiledType(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetCompiledType(String virtualPath) at ToSic.SexyContent.Engines.RazorEngine.CreateWebPageInstance() at ToSic.SexyContent.Engines.RazorEngine.InitWebpage() at ToSic.SexyContent.Engines.RazorEngine.Init() at ToSic.SexyContent.Engines.EngineBase.Init(Template template, App app, ModuleInfo hostingModule, IDataSource dataSource, InstancePurposes instancePurposes, SexyContent sexy) at ToSic.SexyContent.SexyViewContentOrApp.ProcessView(PlaceHolder phOutput, Panel pnlError, Panel pnlMessage)_

**No fun in DNN v8.0.0 RC tonight :(**

**Comment by iJungleboy** [comment]
Thanks for this. 

The first one we'll look at when dnn is stable - they have it https://dnntracker.atlassian.net/browse/DNN-8312

But the second one obviously wants to get Dnn.Modules.DynamicContentViewer - which was removed by DNN. Did you do an upgrade from an earlier version - then it's https://dnntracker.atlassian.net/browse/DNN-8237?jql=text%20~%20%22DynamicContentViewer%22.
If not (new install) pls post an bug on the DNN tracker.
