### ISSUE TITLE
version 8.1 beta

### ISSUE THREAD

**Issue by dnastone** [2sic/2sxc#572]
hello,

the font icons doesn't work. i only see white outlines from a rectangle

best regards

michael

**Comment by nicpitsch** [comment]
This could be your webserver (IIS) which hasn't registered the woff font mime-type. More information [here](http://www.dnnsoftware.com/forums/threadid/509046/scope/posts/missing-font-file).

**Comment by iJungleboy** [comment]
@dnastone could you tell me what browser you're using? We decided to only deliver woff because 2sxc requires IE9+ (IE8 isn't supported by current versions of angular) and woff works on all these browsers http://caniuse.com/#feat=woff. Are you using an exotic browser - or is your server not delivering it as @nicpitsch wrote?

**Comment by BravoSierra** [comment]
Same issue than dnastone, + Adam and Love are in Kanji
just drop files here -  Ada
![capture](https://cloud.githubusercontent.com/assets/5261858/12352480/ae91de12-bb86-11e5-98f8-972b92ccef6b.JPG)
![capture2](https://cloud.githubusercontent.com/assets/5261858/12352484/b45766be-bb86-11e5-8ba1-e12717838430.JPG)

m is sponsored with  by 2sic.com
Tested with IE11 and Chrome

**Comment by iJungleboy** [comment]
Chrome and IE11 have both been working. Could you help me corner the issue
1. what URL is the browser requesting - it should be the correct .../dist/lib/fonts/inpage-icons.woff
2. is that the correct desktop_modules or is something wrong with that?
3. what's the respons? 404?
2. do you have a sub-path dnn installation? so is the root in domain/ or is it in domain/dnn7/

**Comment by dnastone** [comment]
hello, i test it at a local installation and there i forgott to add the mime types for woff and woff2
now t works for me. i'm using google chrom as browser.

**Comment by iJungleboy** [comment]
@dnastone perfect - so your's was a dev-environment issue.

**Comment by dnastone** [comment]
the new editor is realy nice. it would be great if you could create this as a dnn editor too :)

**Comment by iJungleboy** [comment]
@dnastone thanks :) please post that line on facebook to help others discover it

**Comment by dnastone** [comment]
i have no facebook account

**Comment by BravoSierra** [comment]
Sorry, me too it was the IIS WOFF, problem solved, thanks

**Comment by iJungleboy** [comment]
perfect, let's close this :)
