### ISSUE TITLE
Razor script broken in DNN8

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#582]
While token scripts are ok, razor scripts will raise an exception in DNN8:

There was an error while rendering the template: System.Web.HttpCompileException (0x80004005): c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\dnn8\a94fe329\59dd3aeb\App_Web__gallery.cshtml.67f23212.9wawbwsg.0.cs(28): error CS0234: Der Typ- oder Namespacename 'DynamicContentViewer' ist im Namespace 'Dnn.Modules' nicht vorhanden. (Fehlt ein Assemblyverweis?) at System.Web.Compilation.AssemblyBuilder.Compile() at System.Web.Compilation.BuildProvidersCompiler.PerformBuild() at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound) at System.Web.Compilation.BuildManager.GetCompiledType(VirtualPath virtualPath) at ToSic.SexyContent.Engines.RazorEngine.CreateWebPageInstance() at ToSic.SexyContent.Engines.RazorEngine.InitWebpage() at ToSic.SexyContent.Engines.RazorEngine.Init() at ToSic.SexyContent.SexyViewContentOrApp.ProcessView(PlaceHolder phOutput, Panel pnlError, Panel pnlMessage)

**Comment by iJungleboy** [comment]
Thanks. Any idea why? It looks like the DynamicContentViewer is probably a DCC component which was removed. Any idea why DNN is still trying to look for it? Is your install an upgrade from a beta, or is it a new install?

**Comment by iJungleboy** [comment]
I did a quick install myself and must confirm - it fails.

**Comment by iJungleboy** [comment]
Found core issue - it's a web.config in the portals folder:

https://github.com/dnnsoftware/Dnn.Platform/blob/7d76df0d26f4ebb5de778e69ff1e9de273087ce7/Website/Portals/Web.config#L17

But commenting it out creates new bugs. So not solved yet.

**Comment by iJungleboy** [comment]
Ok, I found it. Either

1. Delete / rename the web.config in /Portal/Web.Config
2. Change the content and comment out 2 areas, like this:

```
<?xml version="1.0"?>
<configuration>  
  <configSections>
    <sectionGroup name="system.web.webPages.razor" type="System.Web.WebPages.Razor.Configuration.RazorWebSectionGroup, System.Web.WebPages.Razor">
      <section name="host" type="System.Web.WebPages.Razor.Configuration.HostSection, System.Web.WebPages.Razor" requirePermission="false" />
      <section name="pages" type="System.Web.WebPages.Razor.Configuration.RazorPagesSection, System.Web.WebPages.Razor" requirePermission="false" />
    </sectionGroup>
  </configSections>
   <system.web.webPages.razor>
<!--     <host factoryType="System.Web.Mvc.MvcWebRazorHostFactory, System.Web.Mvc"/>
 -->    <pages pageBaseType="DotNetNuke.Web.Mvc.Framework.DnnWebViewPage">
       <namespaces>
        <add namespace="System.Linq"/>
        <add namespace="System.Web.Mvc"/>
        <add namespace="System.Web.Routing"/>
<!--          <add namespace="DotNetNuke.Web.Mvc.Helpers"/>
         <add namespace="Dnn.Modules.DynamicContentViewer.Helpers"/>
 --> </namespaces>
    </pages>

 </system.web.webPages.razor>
</configuration>


```
I'll also try to post it in jira to get it done, but you can solve your problems like this. Pls test/confirm.

**Comment by iJungleboy** [comment]
So all in all there were 2 issues

1. A DNN bug with a faulty web.config - posted to the DNN Tracker as https://dnntracker.atlassian.net/browse/DNN-8356 - but I can't wait for them to fix it, so I added a dummy class into the correct namespace, so now this bug doesn't pop up any more
2. An issue where the razor engine expected a generic type, I created one to make it happy

So now it works - I'll release a Beta 4 in a few hours...
