### ISSUE TITLE
Visibility of Toolbars indenpendent from edit mode

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#583]
The 2sxc Toolbars are displayed also in normal mode, no edit mode required. 

Affected versions: 8.0.x, 8.1.0 beta

**Comment by iJungleboy** [comment]
This is a feature in 8.0 +
It's 10x faster and if you create templates with the mouseover effect it has no negative impact.

**Comment by SCullman** [comment]
Ok, this makes sense.
