### ISSUE TITLE
Template Editor is broken

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#584]
After upgrading 2sxc 8.0.x to 8.1.0 B3 directly, the template editor is missing or is not registered.

Instead, a JS dialog open up telling me: "trying to open an unknown dialog (developer). Will close again".

**Comment by iJungleboy** [comment]
probably JS caching. if your template editor doesn't open in a new window, then the in-page js was cached. 

pls ctrl-f5 the dnn page, and the new window then too

**Comment by SCullman** [comment]
Ok, crt-f5 did not work in chrome, however after clearing cache in developer tools. editor was back.

**Comment by iJungleboy** [comment]
:)
