### ISSUE TITLE
Feature request: Let me edit a template directly from views grid.

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#585]
Currently I can only modify its settings.

**Comment by iJungleboy** [comment]
I think this is fairly dangerous - as it's easy to break a template (cause errors) and if I do it from the admin-UI it's likely that I'll miss seeing the result. What do you think?

**Comment by SCullman** [comment]
Yep, might be harmful. However it would allow me to view/ compare different views and to make small changes. Maybe this request makes only sense if the scripts are also versionised.

**Comment by iJungleboy** [comment]
ok. I'll keep it in mind but close this for now.
