### ISSUE TITLE
Feature Request: (Generic) SQL Data Source

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#587]
I often have more sql connections configured in web config than just the dnn sql connection. Would be nice to be able to query them within a 2sxc pipeline. 
This should be like DnnSqlDatasource, but with an additional field for the connection name.

**Comment by iJungleboy** [comment]
This exists :)
But for now we're hiding it from the visual designer, because we're afraid of security concerns. what do you think about that?

**Comment by SCullman** [comment]
Well, both DNNSqlDatasource and a generic SQL DataSource should only be available to host users.
I just checked that an ordinary administrator can edit the sql in DnnSqlDatasource.

Maybe the whole designer should be host only? It is as dangerous as editing razor files.

**Comment by iJungleboy** [comment]
Actually the vision is to provide the pipeline editor to admin-users who can create very advanced apps with tokens / JS and never need to write server code. 

So splitting the data sources into various security categories is possible, but we don't have any resources for that in the near future.
