### ISSUE TITLE
TinyMCE: Image by "Link DNN file" not working

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#588]
If I try to insert an existing image from dnn file system, rad Document manager pops up and I can select the file. However it won't insert it as an image.
If text was selected before, alink is created. However, src is "file:undefined".

I am also missing a possibility to link to an existing file, for example a pdf.

ADAM works as expected.

(tested with 8.1.b3)

**Comment by iJungleboy** [comment]
Thx, this looks like something we missed...
