### ISSUE TITLE
Editing lists

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#591]
If a template for a list doesn't include a content toolbar, it is quite difficult to maintain that list.
In 7.x there was a possibility to maintain the list directly from module actions.

Usecase: A list of items (think of 50) in a content rotator. The order of that list is always created randomly. Editing a a special item can then make you mad.

**Comment by iJungleboy** [comment]
At the moment there is the sort-dialog, but it doesn't have an edit. Will review it...

**Comment by iJungleboy** [comment]
I'll add edit again.
