### ISSUE TITLE
Allow bypass 2sxc4ng $http interceptors for specifc http-requests

### ISSUE THREAD

**Issue by BeniGemperle** [2sic/2sxc#595]
For some HTTP-Request I want to handle HTTP-errors by my own. Currently 2sxc always shows an alert which I don't want.

From my research the best solution would be to configure $http requests like
```javascript
$http.get('/foo/bar', {no2sxcIntercept: true})
```

For implementation samples see http://stackoverflow.com/a/31257683/4049371 or http://stackoverflow.com/a/19954545/4049371

**Comment by iJungleboy** [comment]
I'll create an ignoreErrors property.

**Comment by iJungleboy** [comment]
Note that I added the ignoreErrors but couldn't test yet, pls test and confirm...
