### ISSUE TITLE
8.1.1 when I choosse in administration Export this entire App get only empty pop-up

### ISSUE THREAD

**Issue by Frankwalraven** [2sic/2sxc#602]
when I choosse in administration Export this entire App get only empty pop-up

url empty pop-up says
http://www.perfocusaccept.nl/home/mid/567/ctl/appexport/appid/13?popUp=true

further nothing happens no zip

**Comment by iJungleboy** [comment]
I quickly tried it and cannot reproduce it. We also didn't change anything here AFAIK. Anything else you could discover? Like does it only happen on home (a common dnn bug).

**Comment by iJungleboy** [comment]
Can't reproduce, will assume was something else. Close for now. Pls reopen if still an issue.
