### ISSUE TITLE
Colorpicker in TinyMCE

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#605]
Great integration of TinyMCE. It seems that we cannot change the text color tough. Is that part of the shortcomings of the initial integration?

**Comment by iJungleboy** [comment]
As of now the common use cases we planned for should not re-color the text. This usually leads to very nasty results when the user improvises with colors. So ATM this is by design. 

Do you have a professional use case where the user should actually apply colors freely?

**Comment by BravoSierra** [comment]
We are waiting for the users feedbacks after the update. They certainly did not realize yet. Then we'll also pretend that it desapeared by design ;) Since they still can copy and paste whatever patchwork they want, this is no critical issue. 

I agree than colorizing is often childish. The right way should be to allow to select a color, from a list of permitted CSS classes.

**Comment by iJungleboy** [comment]
In our case we really always disable color and font selection. If the design requires color choice, then we provide an option for this in the template-presentation settings - and we don't use color names, but let's say schema or theme names - like "Product, AboutUs, Contact" which then applies CSS classes. 

Will close.
