### ISSUE TITLE
Template editor doesn't (always) save content

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#607]
I was working on a token template with 2sxc 8.1.1/ dnn7.4.2 and noticed that my changes were not saved. If i click on save, the "saved" toast appears, though the template remains unchanged in file system. This happens most the time, I cant detect a pattern.

And yes, I did CRTL+ F5 before, tested with IE and Chrome

**Comment by SCullman** [comment]
Ok, it looks like changes to an existing line remain undetected.
Once a new line is added, the _former_ changes will be saved, but not he new line with new content.

**Comment by iJungleboy** [comment]
Thanks - possibly a bug in the ACE editor. Could it be that it's only if you click-add a snippet, or does it also happen when you type?

**Comment by SCullman** [comment]
It is independent from snippets.

**Comment by iJungleboy** [comment]
Thanks, will review.

**Comment by iJungleboy** [comment]
Seems to be a known angular-ui-ace bug - https://github.com/angular-ui/ui-ace/issues/133 - will have to wait for a fix

**Comment by iJungleboy** [comment]
I was able to reproduce it, but only on snippets. To aid in debugging I added an advanced mode to the dialog (enter with ctrl-Click) - which shows the view-model as is. When i'm using snippets, they don't appear till I type some more. But if I just type, it's always updated. 

Could you confirm this when we release 8.1.3?

**Comment by iJungleboy** [comment]
made a workaround...
