### ISSUE TITLE
Template editor: Wrong snippets

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#608]
2sxc 8.1.1, 

**Razor template, just content, no presentation, no list enabled....:**

* Snippets for _List and List Presentation_ with Header general (@List.Toolbar) and Repeater doesn't fit here.
* @Content.ToolBaris missing under _Content and Content presentation_

**Razor template, just content, no presentation, _list enabled_ ....:**
*  In Snippets for _List and List Presentation_ Header general (@List.Toolbar) and Repeater is missing.

**Intellisense is nice, thanks :-)**

**Comment by iJungleboy** [comment]
thx, will check.
