### ISSUE TITLE
Cannot create new Out connections in Visual Query Designer

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#609]
Steps to reproduce:

1. Open a Visual Query Designer.
2. Add a App Data source - this Data Source has by default no Out connection
3. Click on the orange **+** and drag to create a new Out connection

The whole datasource box is dragged instead of just a new out connection. 

_if you move the box to the target, the connection is created. So the title of this issue is not 100% correct._

**Comment by iJungleboy** [comment]
Thanks. 

1. Just one browser or multiple browsers?
2. Is it a preview-problem (so no line appearing during drag)? If I understand you correctly, it drags, but the entire box (so not the + and not the line), correct?

**Comment by SCullman** [comment]
1.) Multiple browsers (chrome, ie edge
2.) correct

**Comment by iJungleboy** [comment]
Can fully reproduce, also with updated jsplumb (2.0.7). Very hard to find out, either related to angular+jsplumb issue or something with drag-drop...
