### ISSUE TITLE
Better error message when deleting an item in the data backend fails

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#610]
Background:

Often deleting will fail because an entity is still in use in a module. This error should be better visible.

**Comment by iJungleboy** [comment]
This was related to #623 but now not so important any more, as that was actually a bug. 

Must still find a good way to show an error if the item is in use though...

**Comment by iJungleboy** [comment]
Close for now...

**Comment by iJungleboy** [comment]
Will re-open and try to find a better way to inform where the entity is in use...

**Comment by tpperlman** [comment]
The only way that data can be deleted is to delete the content type, which then causes the error in issue reported in #449. This leads to confusing and unnecessary zombie entries.
