### ISSUE TITLE
Enhancement Request: Optimize Window Title 

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#611]
Each template editor or visual pipeline editor window has the same title: "Content Editing UI".
This could be optimized, e.g. _Editor:Item List.cshtm_  or _Pipeline:Filtered Items_
This would help if you have multiple windows open at the same time.

**Comment by iJungleboy** [comment]
too low priority to keep open, will close. 

If someone would like to optimize, feel free to contribute.
