### ISSUE TITLE
Apps and demo items

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#613]
After placing an app to a page and choosing a template, it will first ask me to edit/add an item.
However I don't want an item here, for example because my template renders all items of an entity. 
In that case, I will certainly not add a new one and publish it.

**Comment by SCullman** [comment]
I will not be asked for an item if the template has no content type. However, than I cannot add new items  to the list, as the  + will be missing in the toolbar.

**Comment by iJungleboy** [comment]
That's correct. You need to specifically put an Add-Toolbar in your template where you want it. I'll see if I can give you a quick demo tomorrow.

**Comment by iJungleboy** [comment]
Basically the solution is to create a small toolbar wherever you want it, with just the "new" button - like this:

`<ul class="sc-menu" data-toolbar='{"action":"new", "contentType": "Category"}'></ul>`

**Comment by SCullman** [comment]
@iJungleboy, there is still one caveat. I want my editor to be able to delete an item. As the list display all (filtered) items of a list, an item can't be removed. 
I am already thinking of adding a field "hidden" to the entity, but I guess there must be a simpler way.

**Comment by iJungleboy** [comment]
Let's make a new issue for that #618

**Comment by iJungleboy** [comment]
I'm having some non-technical issues i must solve first. Pls join the conversation on #618
