### ISSUE TITLE
Sources are stacked on save/query

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#614]
My nice pipeline:
![1 before](https://cloud.githubusercontent.com/assets/5693190/12610775/c34f0dcc-c4e9-11e5-95ad-ce5700eff53a.PNG)

looks like this when I save it or run a query
![2 after](https://cloud.githubusercontent.com/assets/5693190/12610776/c35322f4-c4e9-11e5-89f9-36466484acd0.PNG)

It still works, and I can clean it up again
![3 cleanupagain](https://cloud.githubusercontent.com/assets/5693190/12610777/c35370ec-c4e9-11e5-8059-a8c89278de59.PNG)

**Comment by iJungleboy** [comment]
Ok, strange. thx. Could you tell me what browser?

**Comment by SCullman** [comment]
Chrome

**Comment by SCullman** [comment]
Same with Edge. 

Test environment: DNN8, 2sxc8.1.1

**Comment by SCullman** [comment]
Same with Firefox on DNN 7.4.2

**Comment by iJungleboy** [comment]
Seems to be an issue with an old jsPlumb. I'm working on updating it, but it's quite a task....
