### ISSUE TITLE
Multiple test parameters, no result.

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#615]
I created a new pipeline, with default test parameter [Module:ModuleID]=421.
Pipeline is simple: cache - Publishing Filter- EntityTypeFilter - ValueFilter - Target.

If I set the filter set to "yeah", query result returns one result, which fits to my data.

Than I add a new testparameter [QueryString:name]=Yeah in a new line.
Filter is now changed to [QueryString:name], result is now **empty**.

If I delete the unused testparameter [Module:ModuleID]=421, the query woks as expected.

It doesn't matter which testparameter comes first.
![image](https://cloud.githubusercontent.com/assets/5693190/12611639/212416fa-c4ee-11e5-9b6e-984a55db88dc.png)

**Comment by iJungleboy** [comment]
Note that your ValueFilter says `2. Value=Yeah =421`

I'm not 100% sure, but believe the ValueFilter Settings have something special there OR the param injection is actually adding everything after the "=" incl. the following lines (which would be bad).

Could you tell me what the valuefilter has for the value-field - is it "[QueryString:name]" or is it something more complicated?

Could you also try it with 3-4 test-params (unused ones) like

[QueryString:name]=yeah
[QueryString:age]=27
[QueryString:kids]=Nathan

and see if it assembles them all in the valuefilter which only wants one of these?

**Comment by SCullman** [comment]
![image](https://cloud.githubusercontent.com/assets/5693190/12615179/6dbd946c-c504-11e5-8a31-a2caeb5c2f20.png)

**Comment by iJungleboy** [comment]
Super, thx! that helps.
