### ISSUE TITLE
Add entity-delete button to in-page toolbar (in addition to the list-remove)

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#618]

**Comment by iJungleboy** [comment]
Important: if delete fails (this happens very often) then the error must be clearer - so it's related to #610

**Comment by iJungleboy** [comment]
I can see that it's technically very, very easy to implement. BUT I don't like the security implications. 

Basically if a web-service would allow deleting any entity just because a user has edit-permissions on a module, that would open many holes. So what do others think about this? I think I'll have to impose the following limitations:

1. Only allow delete entities of the current module...
2. If the current user has DNN edit-permissions on the module
3. I could also impose that the this role has 2sxc-content-type permissions to delete items of this content-type (if he's not a host-user). This would ensure that the app-designer really wanted to give delete permissions. 

The content-type security would also make sure that the normal user wouldn't delete the AppSettings entity or similar, which he otherwise could if "delete entity 500 of App 3" would just be processed. 

Any thoughts / suggestions?

**Comment by SCullman** [comment]
1. doesn't help if you have a list of all enitities.
2. to weak. DNN Module edit permissions should imply Add/ Edit permissions,  but not Delete

I would go with 3. / Content type permissions. Sounds perfect.
