### ISSUE TITLE
the drop-down editor changes "&#58;" in ":"

### ISSUE THREAD

**Issue by Frankwalraven** [2sic/2sxc#624]
In the drop-down editor we use `"&#58;"` for an `":"` in code 
like
`links:<p style= "text-align&#58; left"></br>`

The new editor saves an `"&#58;"`  as `":"` and that is not what we want
so this get saved
`links:<p style= "text-align: left"></br>`

This results in that the HTML we insert get corrupt
When 2sxc sees an ":" it throw everything away after the ":"
so in the example this get replaced in the html for the token  
`<p style= "text-align`

this happens
![schermafbeelding 2016-01-29 om 15 11 33](https://cloud.githubusercontent.com/assets/13934402/12677665/dc11bdf2-c69a-11e5-90ce-f0bbc5e9fe5a.png)
after the data get saved and we ask the info again we see this
![schermafbeelding 2016-01-29 om 15 11 06](https://cloud.githubusercontent.com/assets/13934402/12677670/e1159382-c69a-11e5-81f5-7e46e6dfabe3.png)

**Comment by raphael-m** [comment]
Done in 2sxc 08.01.03
