### ISSUE TITLE
Template Editor: Selecting text with mouse might cause loss of changes

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#625]
![image](https://cloud.githubusercontent.com/assets/5693190/12711124/87d3fd84-c8bd-11e5-9353-a93da1506561.png)

If you mark text within the editor, in that case from the right to the left and accidentally raise the mouse button left of the dialog, you can say goodbye to all your changes and history. Regardless how you answer the question of the upcoming dialog, it will result in a blank page afterwards.

This is not the only way to break it - it happens a lot to me, sometimes it is caused by keystrokes - however I am most times to surprised to  remember the exact sequence to reproduce.

Please find a way to remove the surrendering, unnecessary dialog.

**Comment by SCullman** [comment]
Any selections of text by mouse which ends at a position out of the dialog causes loss of changes.

**Comment by iJungleboy** [comment]
thx, will look into it
