### ISSUE TITLE
ADAM: Drag and drop upload not working in Safari on Mac OSX

### ISSUE THREAD

**Issue by pascalmoser** [2sic/2sxc#626]
Drag'n'drop upload does not work, the browser just opens the image in a new tab.

**Comment by iJungleboy** [comment]
Pls clarify: does this only happen in the WYSIWYG, or also on the file/hyperlink field?

**Comment by pascalmoser** [comment]
It happens in the WYSIWYG and also on the file/hyperlink field with Safari 5 (http://whatsmybrowser.org/b/4OM5ZPK).
Safari 9 with 2sxc 8.1.3 works.

**Comment by pascalmoser** [comment]
It's not important to support Safari 5. Apple released Safari 5 on June 7, 2010.
I close this issue.
