### ISSUE TITLE
Review export/import of the & character

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#633]
We made a change in 08.01.03 which doesn't un-encode the & character when importing from XML any more. 

This may have side effects which we'll have to review/mitigate, but we'll have to check them first. It's about things like

1. `http://www.2sic.com/?x=z&y=3` --> this would be exported as `http://www.2sic.com/?x=z&amp;y=3`. If we re-import it without correcting this, it will then be stored as `http://www.2sic.com/?x=z&amp;y=3`
2. So the next export would convert `http://www.2sic.com/?x=z&amp;y=3` to `http://www.2sic.com/?x=z&amp;amp;y=3`; re-importing it would leave it this way, breaking the link...

Also check with
* >
* <
* "
* ' = `&apos;`
* & = `&amp;`
* already encoded &: `&amp;amp;` so the url `&amp;name=xyz` should be `&amp;amp;name=xyz` in the xml, but resolve back to `&amp;name=xyz` after import

**Comment by raphael-m** [comment]
I tested the xml import / export and everything works as it should (both the app and the xml import export).
