### ISSUE TITLE
2XSC v8.1.3 - Default data values not appearing when adding data

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#637]
I created two numeric fields and set a default value. When I go to add new data, the default values are not appearing.

![default value 1](https://cloud.githubusercontent.com/assets/1871915/13008838/eef39d56-d166-11e5-8a61-656ae7974397.JPG)

![default value 2](https://cloud.githubusercontent.com/assets/1871915/13008839/f51a35aa-d166-11e5-91c0-b6079f090754.JPG)

**Comment by iJungleboy** [comment]
This is related to #543
