### ISSUE TITLE
2XSC v8.1.3 - Resorting Attributes in a Content Types from Toolbar Causes API 404 Error

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#638]
Resorting Content Types in the admin screen works fine, but when using Toolbar.ContentType a 404 error occurs on the API because it is missing the contentTypeId parameter:

No HTTP resource was found that matches the request URI
'http://dnndev.me/desktopmodules/2sxc/api/eav/contenttype/reorder?appid=2&attributeId=369&direction=up'.

Here is one of the URLs from the admin screen for the same action that works:

http://dnndev.me/desktopmodules/2sxc/api/eav/contenttype/reorder?appid=2&attributeId=369&contentTypeId=91&direction=up

**Comment by iJungleboy** [comment]
Thanks, will look into this

**Comment by iJungleboy** [comment]
I tried to reproduce it but realized that you were probably trying to sort the attributes inside a content-type, so I'm updating the title of this issue. 

I can reproduce the bug in the normal admin-dialog, but I'm not sure as to where it does work. Could you help me on this?

**Comment by iJungleboy** [comment]
Ok, I think I undestand it now

1. when I go through app-admin > data > fields I can sort, 
2. when I go through the in-page toolbar to the fields button, I can't

correct?

**Comment by tpperlman** [comment]
I think we are on the same page, thanks!
