### ISSUE TITLE
2XSC v8.1.3 - WYSIWYG - DNN Standard Issue

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#639]
When the "Enable Pop-Ups" checkbox in Portal Settings is unticked, DNN's built-in WYSIWYG editor appears within the portal's skin:

![html editor](https://cloud.githubusercontent.com/assets/1871915/13013910/79accc98-d17f-11e5-8d82-4104cc358424.JPG)

It should not be showing the skin. It works as expected when "Enable Pop-Ups" is enabled, although there is an overflow issue causing a scrollbar:

![html editor 2](https://cloud.githubusercontent.com/assets/1871915/13013916/80ffdf62-d17f-11e5-9bdf-ce4424c5f874.JPG)

**Comment by iJungleboy** [comment]
We're aware of this issue and as you realized it's a DNN problem. There are only 2 known ways to include an iframe to a dnn-module (we need the module to ensure that the context with security etc. is all respected).

1. With a simple mid=moduleid&popUp=true (the current solution)
2. using a custom skin we would supply and change the link to override the iframes skin to the blank skin

It would be nice if someone worked on this, but for us in the core-team it has no priority as we all prefer the new WYSIWYG. So contributions would be welcome, but we in the core team won't address this for now.

**Comment by iJungleboy** [comment]
I think I found a solution thanks to Bogdan / Dnn-Sharp...

**Comment by iJungleboy** [comment]
original: 
![image](https://cloud.githubusercontent.com/assets/5321186/13815854/7f2c5388-eb8c-11e5-8f03-7bef0ce76bd0.png)


new solution :)

![image](https://cloud.githubusercontent.com/assets/5321186/13815860/85068c42-eb8c-11e5-8c0f-609b79b1a43a.png)
