### ISSUE TITLE
Adam Images are shown as thumbnails after edit

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#651]
I have content with images stored in adam. If I _open _this content edit in edit form, the image is now returned with a thumbnail size of 46 x 46 pixels in all other places.

I need either wait a few minutes  or iI have to recycle app domain to get the original size back.

**Comment by iJungleboy** [comment]
this is strange, and probably a bug in the image-resizer. We'll bundle a new version in 08.02 within a few days...It's already prepared, so I'll close this...
