### ISSUE TITLE
Add possibility to add a wysiwyg.css to style paragraph and headings in the editor

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#653]
- maybe inject `/Portals/[...]/wysiwyg.css` that RadEditor picked up?
- check how DNN solves this with TinyMCE

**Comment by iJungleboy** [comment]
TinyMCE has such a functionality, but I'm not sure if it works in DIV-mode; and we can't use IFrame mode because of mouse-events, drag-drop etc. 

So you can run some tests, but new issues will arise - where to set / use the config. At portal-level, at App-level, at field-level, etc.?

**Comment by iJungleboy** [comment]
I believe this was never followed up and I think it's not as important as originally believed, so I'll close this for now.
