### ISSUE TITLE
2sxc resolves file path with portal of current module instead of portal of the file

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#659]
When an app uses data from another portal, `File:...` links are resolved with the current portals home directory instead of the home directory of the source file.

The `ResolveHyperlinkValues` method should create a `PortalSettings` instance of the files portal. 

Use something like `new PortalSettings(fileInfo.PortalId)` instead of `ownerPortalSettings.HomeDirectory` here:
https://github.com/2sic/2sxc/blob/master/SexyContent/SexyContent.cs#L1194

**Comment by iJungleboy** [comment]
Found the problem. We had duplicate code for resolving hyperlinks - just fixing it...
