### ISSUE TITLE
Google translate problems

### ISSUE THREAD

**Issue by mconta** [2sic/2sxc#66]
The translate feature using google translate seems to have problems.

On a english-italian dnn web site (07.03.02 (109)), when the user clicks on the "Google Translate from English" the server responfs with the message : "an error occurred while translating text.please try again."

The browser make a request to http://query.yahooapis.com/v1/public/yql, the server answer is : 
{"error":{"lang":"en-US","description":"Table XML Parse Error for jsonpost [line 1:1 Premature end of file.]"}}

Note: I found a really simple translation service, here is a request example :   http://mymemory.translated.net/api/get?q=Help%20us&langpair=en|it.
It responds in json and I think it's worth a look. It should be also beautiful to have the translation url configurable.

Here is the complete trace of the yahooapis request:

Remote Address:98.137.200.255:80
Request URL:http://query.yahooapis.com/v1/public/yql?format=json&q=use%20%27https%3A%2F%2Fraw.github.com%2Fyql%2Fyql-tables%2Fmaster%2Fdata%2Fjsonpost.xml%27%20as%20jsonpost%3B%20select%20*%20from%20jsonpost%20where%20url%3D%27http%3A%2F%2Ftranslate.google.de%2Ftranslate_a%2Ft%27%20and%20postdata%3D%27client%3Dt%26text%3DCustomers%26hl%3Den%26sl%3Den%26tl%3Dit%26ie%3DUTF-8%26oe%3DUTF-8%26multires%3D1%26otf%3D2%26ssel%3D0%26tsel%3D0%27&_=1412780666664
Request Method:GET
Status Code:400 Bad Request
Request Headersview source
Accept:/
Accept-Encoding:gzip,deflate,sdch
Accept-Language:it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Host:query.yahooapis.com
Origin:http://xxx.xxx.com
Referer:http://xxx.xxx.com/it-it/Clienti/ctl/editcontentgroup/mid/3429/SortOrder/0/ContentGroupID/3429?popUp=true&ReturnUrl=%2fit-it%2fClienti%2fctl%2feditlist%2fmid%2f3429%2fContentGroupID%2f3429%3fpopUp%3dtrue&CultureDimension=3
User-Agent:Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36
Query String Parametersview sourceview URL encoded
format:json
q:use 'https://raw.github.com/yql/yql-tables/master/data/jsonpost.xml' as jsonpost; select * from jsonpost where url='http://translate.google.de/translate_a/t' and postdata='client=t&text=Customers&hl=en&sl=en&tl=it&ie=UTF-8&oe=UTF-8&multires=1&otf=2&ssel=0&tsel=0'
_:1412780666664
Response Headersview source
Access-Control-Allow-Origin:*
Age:0
Connection:keep-alive
Content-Type:application/json;charset=utf-8
Date:Wed, 08 Oct 2014 15:09:14 GMT
Server:ATS
Transfer-Encoding:chunked
X-Content-Type-Options:nosniff
X-YQL-Host:engine6.yql.bf1.yahoo.com

**Comment by mconta** [comment]
Sorry if I stress on this issue..., but doesn't exists a simple fix to this problem ? Am I the only one who reported this problem or it's a non working feature? 

We are localizing some 2sic apps and this functionality could be really useful.

**Comment by iJungleboy** [comment]
So far we have no further requests on this and we're not prioritizing this if there is no sponsor.

**Comment by iJungleboy** [comment]
Never heard about this any more? still an issue? will close for now, if still relevant, pls open new relevant to 2sxc 8+
