### ISSUE TITLE
Feature Request: Shuffle entities data source

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#664]
More or less a data source which
1. Has an In
2. Delivers the same items in a different order in the Out
3. You can set how many items you want, so that it doesn't re-sort everything when it only needs 3

**Comment by SCullman** [comment]
Simplest approach in razor templates:

        List.OrderBy(x => Guid.NewGuid())

**Comment by iJungleboy** [comment]
I researched this quite a bit, and the GUID approach seems to have many downsides. Apparently there's a guy called Fisher-Yates who figured out a low-overhead sorting mechanism which I'll try to go for...

**Comment by iJungleboy** [comment]
Note that the feature is ready now, but there is a setting which is not surfaced yet - which is the "Take" setting. Means for very, very large data sets (10'000 items + to shuffle) it will be a bit slow, but I assume that's a rare scenario. 

Code can set the `Take` property, so it's easy to work around.
