### ISSUE TITLE
Have the installer remove protobuff & tinycache from existing installations...

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#665]
I just updated one of my sites and received the error below, which I traced to the missing DLL of protobuf-net.dll:

DotNetNuke.Services.Exceptions.Exceptions - DotNetNuke.Services.Exceptions.PageLoadException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'DotNetNuke.ExtensionPoints.ExtensionPointManager' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'protobuf-net, Version=2.0.0.668, Culture=neutral, PublicKeyToken=257b51d87d2e4d67' or one of its dependencies. The system cannot find the file specified.

**Comment by iJungleboy** [comment]
I thought it isn't needed any more - but I'll check, I think only the (not enabled ) tinycache needs it.

Mail, Tel and more: http://2sic.com/dm
Sent from mobile

On 18 Feb 2016, at 17:50, Phil <notifications@github.com<mailto:notifications@github.com>> wrote:


I just updated one of my sites and received the error below, which I traced to the missing DLL of protobuf-net.dll:

DotNetNuke.Services.Exceptions.Exceptions - DotNetNuke.Services.Exceptions.PageLoadException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'DotNetNuke.ExtensionPoints.ExtensionPointManager' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'protobuf-net, Version=2.0.0.668, Culture=neutral, PublicKeyToken=257b51d87d2e4d67' or one of its dependencies. The system cannot find the file specified.

�

**Comment by tpperlman** [comment]
I had first installed v8.1 yesterday, then uninstalled it because I ran into an API error in 2SXC. I then installed v8.2 that you released today fresh to see if it fixed some of the issues that I had reported. When I went to login, that is when the error appeared. There was no error for unauthenticated users. Maybe there is still a file reference somewhere?

BTW, thank you for your dedication and efforts.... as well as for your awesome responsiveness.

**Comment by iJungleboy** [comment]
Basically protobuff is used by the tinycache of imageresizer. 
Starting in 8.2 it shouldn't needed any more, because we switched over to DiskCache, which doesn't use protobuff. Pls check your web config, it should have some kind of 

```
<plugin>
    <... "DiskCache">
    <... "Simple...">
    <... "Advanced...">
</plugin>
```
section, but it should never mention tiny cache.

**Comment by iJungleboy** [comment]
Ok, I ran some tests. 

If you delete the ImageResizer.TinyCache.dll + the pdb, you're fine. I'll change this in the distribution...

**Comment by tpperlman** [comment]
Not sure if you still needed this or not, but this was in the web.config:

  <resizer>
    <plugins>
      <add name="DiskCache" />
      <add name="SimpleFilters" />
      <add name="AdvancedFilters" />
    </plugins>
  </resizer>

**Comment by iJungleboy** [comment]
That last part is needed :) - that's the new, really, really great resizer...
