### ISSUE TITLE
Edit template settings (views) ERR_TOO_MANY_REDIRECTS 8.2.1

### ISSUE THREAD

**Issue by Frankwalraven** [2sic/2sxc#670]
When i thry to edit the template settings in views I get a  error
This webpage has a redirect loop
ERR_TOO_MANY_REDIRECTS

**Comment by iJungleboy** [comment]
Could you provide more details, because this could also be a DNN issue. 

What URL are you looping on (I recommend to use fiddler to debug)?

Does this happen on all templates, or just on one?

**Comment by Frankwalraven** [comment]
This happens on all templates

**Comment by Frankwalraven** [comment]
![schermafbeelding 2016-02-19 om 12 57 12](https://cloud.githubusercontent.com/assets/13934402/13175111/79e2b22a-d708-11e5-96ce-5c483b27416a.png)
When clicking here

**Comment by Frankwalraven** [comment]
bprvisie.com/Default.aspx? tabid=195&amp;mid=651&amp;ctl=edittemplate&amp;appid=4&amp;popUp=true&amp;templateid=618

cannot be opend to many redirects

**Comment by Frankwalraven** [comment]
has resulted in too many redirects. This problem may be solved if delete your cookies for this site or allowing third-party cookies. If not, then it may be a problem with the server configuration and not a problem with the computer.
doesnt help

**Comment by Frankwalraven** [comment]
GET http://bprvisie.com/Default.aspx?tabid=55&mid=646&ctl=edittemplate&appid=4&popUp=true&templateid=618
301 Redirect to http://bprvisie.com/Default.aspx?tabid=55&mid=646&ctl=edittemplate&appid=4&popUp=true&templateid=618

**Comment by Frankwalraven** [comment]
GET http://bprvisie.com/Default.aspx?tabid=55&mid=646&ctl=edittemplate&appid=4&popUp=true&templateid=618 HTTP/1.1
Host: bprvisie.com
Connection: keep-alive
Cache-Control: max-age=0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en,nl;q=0.8,en-US;q=0.6,de;q=0.4
Cookie: .ASPXANONYMOUS=k77emaGh0QEkAAAAZGY0OWY3NDctOTVjZS00YmM2LTg3YjktOGFlZGM1ODU3Mjk50; OriginalReferrer=http://bprvisie.com/; LandingPage=http://bprvisie.com/projecten; __RequestVerificationToken=1lNrr0V1jdYV-JA1VIixWr1IpZuUcCfINova3mtMLF33DNcX8inCNBCiYSb4V1EnqeqgpnbLWmD5oAp7mpbF12BljBMO9Mwslqa4UIhyN9avHxYfMZS1sAu2SLc1; USERNAME_CHANGED=; authentication=DNN; .DOTNETNUKE=D6B127EDB4FB03D2092F479A3ACBCF4B680704F40021CAEE6898027C8A26DCFD761C53BD96250766CAFFA0075FAAFACFAB592D7B1CC0BA5A3FC3BECA6E66EEC8FF9D6E708D49D17C98D76C9A619F6419607094405C523AFE0D636D4A6738D35863236D0D4FDFD97C576B761F; LastPageId=0:55; language=nl-NL; dnn_IsMobile=False


HTTP/1.1 301 Moved Permanently
Cache-Control: private
Location: http://bprvisie.com/Default.aspx?tabid=55&mid=646&ctl=edittemplate&appid=4&popUp=true&templateid=618
Server: Microsoft-IIS/8.0
X-Redirect-Reason: Wrong Portal Alias Requested
Set-Cookie: dnn_IsMobile=False; path=/; HttpOnly
Date: Fri, 19 Feb 2016 12:39:14 GMT
Content-Length: 237

<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="http://bprvisie.com/Default.aspx?tabid=55&amp;mid=646&amp;ctl=edittemplate&amp;appid=4&amp;popUp=true&amp;templateid=618">here</a>.</h2>
</body></html>

**Comment by iJungleboy** [comment]
I believe the core cause is this message:

```
X-Redirect-Reason: Wrong Portal Alias Requested
```

My guess is that your DNN portal aliases are not configured quite correctly, or the languages. We've also had similar issues if your search-page or your home-page is not defined properly in DNN. Please check all this, to 99% this is the reason.

**Comment by iJungleboy** [comment]
I'll close this for now, because it's almost certainly not a 2sxc issue.

**Comment by Frankwalraven** [comment]
we don't use languages, the protals are configured normal, is nearly a new installation, with the 8.2.0 everything worked correct. It look like it happens after the quickfix in [https://github.com/2sic/2sxc/issues/449](url)

**Comment by Frankwalraven** [comment]
changed a view times the main alias of the portal and now it works agian. Strange
