### ISSUE TITLE
Add Item to List throws error

### ISSUE THREAD

**Issue by ech01** [2sic/2sxc#671]
I set up a new list. When adding a new item through the module menu, nothing happens. I looked in the console and saw this error in the response code.

"Violation of PRIMARY KEY constraint 'PK_ToSIC_EAV_EntityRelationships'. Cannot insert duplicate key in object 'dbo.ToSIC_EAV_EntityRelationships'.
 The statement has been terminated."

DNN 7.4.2
2sxc 8.1.3

FYI: This is a multi-lingual site.

**Comment by iJungleboy** [comment]
What appears to be happening is that you're adding the same item to the list again. I'm not sure if we ever tested such a scenario...

**Comment by iJungleboy** [comment]
Just so I understand the use-case - why would you need the same item multiple times in a list?

**Comment by ech01** [comment]
I'm not adding the same item. I'm just attempting to add an item through
the module menu Add Item. If I use the 2sxc toolbar, I do not have the same
issue.

**Comment by iJungleboy** [comment]
Ok, thanks for that clarification. So basically

1. Adding a demo-item through the in-page toolbar works
2. Adding a demo-item through the dnn-menu fails

Is this correct? Please make sure that it is only this that causes the difference, not that the list was different before you added the item(s).

**Comment by ech01** [comment]
You are correct. 

Also, this may be related, but if you look at the list (clicking the button in the toolbar)
![image](https://cloud.githubusercontent.com/assets/3790873/13229231/7c9f091e-d965-11e5-9312-89b9432a5cf1.png)

You can see a bunch of empty entries.

If you look at the data, it tells a different story...
![image](https://cloud.githubusercontent.com/assets/3790873/13229249/93f924aa-d965-11e5-89c4-db3d207ea62e.png)

Let me know what we need to do to troubleshoot. I can either send you a host login, or do an export.

**Comment by iJungleboy** [comment]
Ok, got it. I have a fairly good guess but I would appreciate a short login - admin is fine - sent to info 2sxc org and the exact page/module where I can experience this.

**Comment by iJungleboy** [comment]
just sent you a likely fix...

**Comment by iJungleboy** [comment]
Any news on this?

**Comment by iJungleboy** [comment]
Will close for now - I guess it's fixed, but haven't gotten any feedback yet @ech01 is probably on vacation. 

Pls give feedback when you can, re-open if necessary...
