### ISSUE TITLE
Modal dialogs close when dragging and releasing the mouse outside dialog

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#678]
When a user selects text on an edit dialog and releases the mouse outside of the modal window, the "Do you really want to exit" message appears.

We should be able to change the modal exit action to `mouse down` which solves this problem.

**Comment by raphael-m** [comment]
A bootstrap upgrade might solve this: https://github.com/twbs/bootstrap/issues/13816

**Comment by reto-f-999** [comment]
this happens again in 2sxc 9.32.01
