### ISSUE TITLE
Exception opening table -> Admin->DATA

### ISSUE THREAD

**Issue by KosVos37** [2sic/2sxc#682]
The exception ( LINE number 21 ) happens only at one data-structure in request GetAllTypeForAdmin. Other tables work well.

As you can see the ERROR says that I am missing parameter "Path1". Can you tell me what I supposed to provide and how I can do that. Thanks in advance.

![2sxc-data-error](https://cloud.githubusercontent.com/assets/15049570/13221236/9fdaf63a-d97a-11e5-9ee1-11ab8a1b6abd.JPG)

**Comment by Frankwalraven** [comment]
We get this error when we try to go to all the records of one content type in the admin tab Content -Types and Data. Its only with one content type. The others work correct. We also can't export this content type that gives the error. 
With the button replace, we can replace records of the content type normaly. 
Is there a way to resolve this problem
We would be happy
I don't know of the reason is that there is a record missing with this GUID
e31d266d-8c6c-4faa-8892-b4cb976b0aff 
It would be nice when you can help us



Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2sxc.api.min.js:3 Objectconfig: Objectdata: Objectheaders: (c)status: 500statusText: "Internal Server Error"__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: get __proto__()set __proto__: set __proto__()
set.min.js?sxcver=08.02.02:93 GET http://www.bprvisie.com/projecten/desktopmodules/2sxc/api/eav/entities/GetAllOfTypeForAdmin?appId=4&contentType=e31d266d-8c6c-4faa-8892-b4cb976b0aff 500 (Internal Server Error)(anonymous function) @ set.min.js?sxcver=08.02.02:93q @ set.min.js?sxcver=08.02.02:89g @ set.min.js?sxcver=08.02.02:86(anonymous function) @ set.min.js?sxcver=08.02.02:118n.$eval @ set.min.js?sxcver=08.02.02:133n.$digest @ set.min.js?sxcver=08.02.02:130n.$apply @ set.min.js?sxcver=08.02.02:133(anonymous function) @ set.min.js?sxcver=08.02.02:252Hf.c @ set.min.js?sxcver=08.02.02:35
2sxc.api.js:186 Object {data: Object, status: 500, config: Object, statusText: "Internal Server Error"}config: Objectdata: Objectheaders: (c)status: 500statusText: "Internal Server Error"__proto__: Object

**Comment by iJungleboy** [comment]
Please add more server errors - this is just the js-stack, but that's a consequence because the http return an error. 

Please post the http-response which you get - you can see it in the web developer tools of the browser (section: network) or using fiddler.

**Comment by iJungleboy** [comment]
My guess is that you have a file/hyperlink-field which was added later on, and therefor has null-values. 

Could both @Frankwalraven and @KosVos37 do an upgrade to newest version 08.02.03 (just released a few minutes ago)? It contains pdb files which give is exact line numbers where the error occurred.

**Comment by Frankwalraven** [comment]
Where can I find this pdb files

**Comment by iJungleboy** [comment]
@Frankwalraven they are in the newest install packages by default - but apparently not distributed by default yet - will try to fix asap. but you can just go into the zip, then open the resources.zip inside it, go to /bin and copy the pdb-files. Note that you need the same version as installed of course :)

**Comment by Frankwalraven** [comment]
This is in the network section
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [],
    "entries": [
      {
        "startedDateTime": "2016-02-24T13:54:07.280Z",
        "time": 55.999999996856786,
        "request": {
          "method": "GET",
          "url": "http://www.bprvisie.com/projecten/desktopmodules/2sxc/api/eav/entities/GetAllOfTypeForAdmin?appId=4&contentType=e31d266d-8c6c-4faa-8892-b4cb976b0aff",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "TabId",
              "value": "55"
            },
            {
              "name": "Pragma",
              "value": "no-cache"
            },
            {
              "name": "RequestVerificationToken",
              "value": "abcdefgihjklmnop"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, sdch"
            },
            {
              "name": "Debugging-Hint",
              "value": "bootstrapped by 2sxc4ng"
            },
            {
              "name": "Host",
              "value": "www.bprvisie.com"
            },
            {
              "name": "Accept-Language",
              "value": "en,nl;q=0.8,en-US;q=0.6,de;q=0.4"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
            },
            {
              "name": "Cookie",
              "value": "StayInEditMode=NO; .ASPXANONYMOUS=BwP8z-Kj0QEkAAAANGM2N2ExNTYtZjNhNi00ZWUzLWI3NDUtZWUyZmZlYzFkMTky0; __RequestVerificationToken=PzktyBAB8uATleKlwH9qXQqboFTarJx67qS_9RF1OgT-XB0UxTUkeNH6jpr_NClp0jIOVzF9_aK0EriE0FF9pVsmUl_11aeiFdFyTQGOqRvCtfG3Vump6yxlsXw1; OriginalReferrer=http://www.bprvisie.com/projecten/inloggen; LandingPage=http://www.bprvisie.com/projecten/; USERNAME_CHANGED=; authentication=DNN; LastPageId=0:55; .DOTNETNUKE=E1263CD0BC276293C22A5E2CC1B5D5FD61DB1C1A3DE1F547555A754F9AE0422BB2FD2760B0A7BA1FABB9F2433561DC83D34D54BDECD6B08BB4D39CE3DE2923B01C5CA45248B09CB4C7CB6D17035C82B05A9564AFD5223DFA095B83391B2FB903892B7C680D4F64F2EDFAB8A6; dnn_IsMobile=False; language=nl-NL"
            },
            {
              "name": "Accept",
              "value": "application/json, text/plain, */*"
            },
            {
              "name": "Cache-Control",
              "value": "no-cache"
            },
            {
              "name": "Referer",
              "value": "http://www.bprvisie.com/desktopmodules/tosic_sexycontent/dist/dnn/ui.html"
            },
            {
              "name": "ModuleId",
              "value": "646"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            }
          ],
          "queryString": [
            {
              "name": "appId",
              "value": "4"
            },
            {
              "name": "contentType",
              "value": "e31d266d-8c6c-4faa-8892-b4cb976b0aff"
            }
          ],
          "cookies": [
            {
              "name": "StayInEditMode",
              "value": "NO",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": ".ASPXANONYMOUS",
              "value": "BwP8z-Kj0QEkAAAANGM2N2ExNTYtZjNhNi00ZWUzLWI3NDUtZWUyZmZlYzFkMTky0",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "__RequestVerificationToken",
              "value": "PzktyBAB8uATleKlwH9qXQqboFTarJx67qS_9RF1OgT-XB0UxTUkeNH6jpr_NClp0jIOVzF9_aK0EriE0FF9pVsmUl_11aeiFdFyTQGOqRvCtfG3Vump6yxlsXw1",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "OriginalReferrer",
              "value": "http://www.bprvisie.com/projecten/inloggen",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "LandingPage",
              "value": "http://www.bprvisie.com/projecten/",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "USERNAME_CHANGED",
              "value": "",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "authentication",
              "value": "DNN",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "LastPageId",
              "value": "0:55",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": ".DOTNETNUKE",
              "value": "E1263CD0BC276293C22A5E2CC1B5D5FD61DB1C1A3DE1F547555A754F9AE0422BB2FD2760B0A7BA1FABB9F2433561DC83D34D54BDECD6B08BB4D39CE3DE2923B01C5CA45248B09CB4C7CB6D17035C82B05A9564AFD5223DFA095B83391B2FB903892B7C680D4F64F2EDFAB8A6",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "dnn_IsMobile",
              "value": "False",
              "expires": null,
              "httpOnly": false,
              "secure": false
            },
            {
              "name": "language",
              "value": "nl-NL",
              "expires": null,
              "httpOnly": false,
              "secure": false
            }
          ],
          "headersSize": 1377,
          "bodySize": 0
        },
        "response": {
          "status": 500,
          "statusText": "Internal Server Error",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Pragma",
              "value": "no-cache"
            },
            {
              "name": "Date",
              "value": "Wed, 24 Feb 2016 13:53:50 GMT"
            },
            {
              "name": "Server",
              "value": "Microsoft-IIS/8.0"
            },
            {
              "name": "Content-Type",
              "value": "application/json; charset=utf-8"
            },
            {
              "name": "Cache-Control",
              "value": "no-cache"
            },
            {
              "name": "Set-Cookie",
              "value": "dnn_IsMobile=False; path=/; HttpOnly"
            },
            {
              "name": "Set-Cookie",
              "value": "dnn_IsMobile=False; path=/; HttpOnly"
            },
            {
              "name": "Set-Cookie",
              "value": "language=nl-NL; path=/; HttpOnly"
            },
            {
              "name": "Content-Length",
              "value": "36"
            },
            {
              "name": "Expires",
              "value": "-1"
            }
          ],
          "cookies": [
            {
              "name": "dnn_IsMobile",
              "value": "False",
              "path": "/",
              "expires": null,
              "httpOnly": true,
              "secure": false
            },
            {
              "name": "dnn_IsMobile",
              "value": "False",
              "path": "/",
              "expires": null,
              "httpOnly": true,
              "secure": false
            },
            {
              "name": "language",
              "value": "nl-NL",
              "path": "/",
              "expires": null,
              "httpOnly": true,
              "secure": false
            }
          ],
          "content": {
            "size": 36,
            "mimeType": "application/json",
            "compression": 0
          },
          "redirectURL": "",
          "headersSize": 371,
          "bodySize": 36,
          "_transferSize": 407
        },
        "cache": {},
        "timings": {
          "blocked": 4.00000000081491,
          "dns": 0.9999999892897904,
          "connect": 6.0000000084983,
          "send": 0,
          "wait": 43.9999999944121,
          "receive": 1.0000000038416843,
          "ssl": -1
        },
        "connection": "11420"
      }
    ]
  }
}

**Comment by iJungleboy** [comment]
1. Pls always post your code as code - that's three of these funny apos-characters - easier to read
2. these are only the headers. I need the message body of this request coming back

**Comment by iJungleboy** [comment]
@KosVos37 I believe your error occurs here

```
            return Path.Combine(new PortalSettings(fileInfo.PortalId).HomeDirectory, fileInfo.RelativePath);
```
https://github.com/2sic/2sxc/blob/master/SexyContent/EAV/Implementation/ValueConverter/SexyContentValueConverter.cs#L96

If I am right, then it doesn't get a home directory for the portalsettings. The reason you only experience this on one content-type will be because you only have valid resolvable file:### links on this content-type - which fail. I could just add a try/catch around it but I don't like to do that if it's not the core problem. Could you also try the PDBs and see what exactly the issue is?

**Comment by iJungleboy** [comment]
Just fyi: I made you a quick, very personal release which changes the Path.Combine. Could you give it a try and get me feedback?

https://github.com/2sic/2sxc/releases/tag/untagged-1bf0c93bc3ca2a7d6a36

**Comment by Frankwalraven** [comment]
The release is not linked we get a 404 error when we click on the link

**Comment by KosVos37** [comment]
Hi iJungleboy, I am sorry but the link https://github.com/2sic/2sxc/releases/tag/untagged-1bf0c93bc3ca2a7d6a36 returns a 404 error. I also tried walking through the repository but could not find the resource

**Comment by KosVos37** [comment]
Wrong button. Reopened

**Comment by iJungleboy** [comment]
sorry, was still protected...

**Comment by KosVos37** [comment]
and I think it still is ...
Can you re-check if the resource can be downloaded

**Comment by iJungleboy** [comment]
ok.

**Comment by Frankwalraven** [comment]
The problem is solved. No error anymore after the update

**Comment by iJungleboy** [comment]
@kosvos37 your status?

**Comment by KosVos37** [comment]
Thanks a lot iJungleboy it works again.
