### ISSUE TITLE
Adam image picker does not work in non-latin page names 

### ISSUE THREAD

**Issue by BravoSierra** [2sic/2sxc#685]
Adam's image picker does not work if the page name contains non-latin characters and no alternate URL has been set. Looks like there is an Url encoding missing, or something similar. Issue reported with a Cyrillic alphabet.

Workaround: setting a latin page URL in the page properties solves the problem.

**Comment by iJungleboy** [comment]
Thx - also for the quick workaround solution. We'll try to reproduce and fix...

**Comment by iJungleboy** [comment]
I tried this with an adam-field (a library, not a link) and used a page called Grün. I could not reproduce the issue. Could you give me more details?

**Comment by iJungleboy** [comment]
No feedback so far, will close for now, pls re-open if it's still an issue.

**Comment by BravoSierra** [comment]
Apologies for not giving feedback on this issue.

The fact is that they learnt to rewrite all URL in the page settings, with latin characters, so they have a workaround

 

But I’ve just retried and I cannot reproduce either, so kind of mystery

I’ll let you know if I can give you a precise page to observe.

Thanks

 

Benoît SARTON

 <http://www.bsi.fr/> www.bsi.fr

04 66 30 00 00

 

De : iJungleboy [mailto:notifications@github.com] 
Envoyé : mardi 15 mars 2016 11:10
À : 2sic/2sxc
Cc : BSI
Objet : Re: [2sxc] Adam image picker does not work in non-latin page names (#685)

 

No feedback so far, will close for now, pls re-open if it's still an issue. 

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/2sic/2sxc/issues/685#issuecomment-196753054Image supprimée par l'expéditeur.
