### ISSUE TITLE
"Auto-Configure 2sxc" message shows up on "change layout" when ContentType and all templates of 2sxc app are hidden

### ISSUE THREAD

**Issue by reaxx999** [2sic/2sxc#690]
If you use "change layout/template" and the content type and template in use are hidden, the "auto-configure 2sxc" message shows up.
This message should not show up, because there is no need to autoconfigure 2sxc.

Reproduction steps:
1. Insert 2sxc app module
2. use any app with any content type
3. hide content type, hide all templates
4. use "change layout/(template" function

**Comment by iJungleboy** [comment]
@reaxx999 this is related to a new change we did, where we're moving functionality previously on the server to the client. Right now the client-logic checks if there are any templates and if not, shows the selector. 

Could you tell me why you're hiding all the templates, just so I can understand if this is a common scenario?

**Comment by reaxx999** [comment]
@iJungleboy if I have i.e. a News App which is in use but the customer should have no possibility to change the layout (because are no other templates). 

In this case, if the content type and all related templates are hidden and the user clicks on "change layout" button, the message shows up. So this is a more or less common scenario for me. 

Another approach would be the possibility, to tell the app to show/hide the "change layout" button.

**Comment by iJungleboy** [comment]
But if there is only one template, you could leave that visible - so the user can't change it anyhow. Or am I wrong?

**Comment by reaxx999** [comment]
erm, i think no because in some cases I have an app with 3 templates (like with News App: short list full list, and detail view), and all of them are in use, and i don't want the customer to change one instance or add new instances with one of these.

**Comment by iJungleboy** [comment]
Ok. I'll try to find a way to solve this, but it may take a while. 

As a short workaround, you can "cheat": the template selector only shows you templates which have matching content-type configuration, based on 

1. Main content-type
2. Presentation type
3. List-Content type
4. List presentation type

I assume you have a list of news-items, so you want to have hat the same across everything. But if you add a unique (not needed) list-presentation or something, then the other templates won't be shown to switch to.

**Comment by reaxx999** [comment]
Ok thx for your workaround suggestion!

**Comment by iJungleboy** [comment]
Will close, unless more people are affected...
