### ISSUE TITLE
TinyMCE and Icon Fonts

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#702]
Icons, e.g. from font awesome entered in source view, will be removed.  Doesn't matter whether em, i or span tags are used.

Example:
`<i class="text-success fa-li fa fa-check"></i>`
will be removed completely.

Tested with 8.2.2

**Comment by iJungleboy** [comment]
Is everything removed, or only the fa-classes?

is it removed when changing to html/back, or when saving?

**Comment by SCullman** [comment]
- The whole tag gets removed.
- It is already removed if you close the source window.
- If you entered it with  _wysiwyg DNN _standard before, open and save will remove it too.

**Comment by SCullman** [comment]
Looks like a well known problem: [https://www.google.de/search?q=tinymce+font+awesome](url)

**Comment by iJungleboy** [comment]
Will close this for now, as it seems to be a tinymce issue which may be fixed some day by tinymce, but is out of scope for 2sxc.
