### ISSUE TITLE
PageID-values outputting wrong URLs (affects 8.3.0 & 8.3.1)

### ISSUE THREAD

**Issue by reaxx999** [2sic/2sxc#710]
Content fields with Page IDs creating wrong URLs on output, like this:

**since 8.3.x:** //Level1/Level2
**before 8.3.x:** http://www.domain.com/Level1/Level1

This is a very critical bug, because - depending on the 2sxc content type setup - it leads to several 404s.

**Comment by iJungleboy** [comment]
thank you - i'll check...

**Comment by iJungleboy** [comment]
Was able to reproduce, thanks for the feedback
