### ISSUE TITLE
Toolbar "Warnings"

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#711]
If I click on any icon in a toolbar, a JS Dialog tells me _Required parameter (sxcver) missing from url - cannot continue_, however if I click on OK, it works as expected.

Tested in 8.3.1

**Comment by iJungleboy** [comment]
This is odd - we changed something to ensure that the ui.html is never cached on an update, so the version is now part of the url. Pls shift-click on an edit-button, you should have ?sxcver in the url like in this image

![image](https://cloud.githubusercontent.com/assets/5321186/13496405/4c469500-e150-11e5-8d1f-dc91532b7f5d.png)

is this not the case?

**Comment by SCullman** [comment]
Hmm, not always. Not _every_ template / toolbar includes the parameter sxcver. I can't recognize a pattern though.

**Comment by iJungleboy** [comment]
Could you check - the script picks up the property config.version from a JSON which is in an html-attribute called data-2sxc in a <div> which wraps your module. Do you see the json? does it have the property, or is something missing?

**Comment by iJungleboy** [comment]
The way I see the script, it should always fail, or always work on an entire module.

**Comment by SCullman** [comment]
You are right. It works or fails depending on page, not module.

I see the json within the data-2sxc for any module, regardless whether it fails or not. It also always includes config.version.

**Comment by iJungleboy** [comment]
Then my guess is that something on this page breaks the JS. do you see errors in the js console?

**Comment by SCullman** [comment]
No errors here in JS console

**Comment by iJungleboy** [comment]
Could you try some JS debugging? just add ?debug=true to the dnn page and the JS will be loaded in un-minified. You can then step-through (in-page.js) it to see what happens...

**Comment by SCullman** [comment]
Did that - and it did not un-minify because client resource management was enabled :-(

I turned off client resource management, stepped through in-page.js and could reproduce the issue. All warnings disappeared. Enabling it again AND increasing _site version_ solved the problem.

I guess I should do that after ANY serious update.

**Comment by iJungleboy** [comment]
thx!
