### ISSUE TITLE
Enable a Save&Continue button without closing the Edit dialog

### ISSUE THREAD

**Issue by mconta** [2sic/2sxc#72]
On the Edit Item dialog, the SAVE button causes the content to be saved and the Dialog is closed, returning to the "Edit List" dialog.

It's should be useful to change some values and test the layout without closing the "Edit Item" dialog.

This could be accomplished changing the "Save" button in "Save and Close" and 
adding a new button "Save" that doesn't close the dialog and that executes the save using an ajax request.

Another option is to name the new button "Save & Continue" and to leave the Save button unchanged.

**Comment by iJungleboy** [comment]
implemented in newest version :).
