### ISSUE TITLE
ADAM cannot be disabled on hyperlink fields (should be configurable)

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#726]
By now (2sxc 8.x. - 8.3.4.) ADAM is integrated automatically on every hyperlink field. Depending on the purpose of the field, this can be confusing for the editor. 

It should be possible to configure wether any hyperlink field offers the ADAM function or not, maybe the same way like it is possible to choose the page picker, image manager, ... ?

**Comment by BeniGemperle** [comment]
+1

Same issue. I need a hyperlink-field where users can only select a DNN-Page (not a file).
