### ISSUE TITLE
Date fields should also offer other data formats (like DMY) than just standard format (YMD)

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#727]
By now (sxc 8.x. - 8.3.4.) date fields can only contain the ISO date format (yyyy-mm-dd). It should be possible to define which scheme date fields are using.

This affects the editor, because if his culture uses another format than standard, he cannot type dates like he is accustomed.

Suggestion: offer the 3 worldwide most popular schemes (see table here: https://en.wikipedia.org/wiki/Date_format_by_country )

[x] YMD (yyyy-mm-dd)
[ ] DMY (dd-mm-yyyy)
[ ] MDY (mm-dd-yyyy)

**Comment by reaxx999** [comment]
Update: it would be great if it would be possible to define with which weekday the week in date picker starts (Sunday or Monday). 
(Because Northamericans use Sunday, Europeans use Monday as weeks starting day.)
