### ISSUE TITLE
"Getting Started" panel appearing when a template is hidden

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#732]
When a template is hidden and can't be changed (because the current content type has only one template), the Auto-Configure dialog appears although there are many templates configured in the portal.

**Comment by iJungleboy** [comment]
Note: this is the second time someone reports this, so we probably should look at it.

**Comment by iJungleboy** [comment]
Note in case you're working on it - I think the version of tonight 08.03.05 actually doesn't show the app-getting-started any more, even in a new portal. So something in the "needs autostart" detection fails as of 2016-03-14 22:22

**Comment by iJungleboy** [comment]
as discussed we'll implement an additional check server-side when the JS wants to know the getting-started url
