### ISSUE TITLE
2SXC 8.3.4 - Manage Apps Admin - Browser Freezes When Clicking to Edit an App

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#736]
Issue #444 seems to have appeared again in the latest build. Verified in latest version of FF and IE11.

**Comment by iJungleboy** [comment]
I didn't try to reproduce yet but it's very likely that you're right. We changed something to prevent ui.html-caching, but this changed the URL a bit, which probably broke the extra-workaround-for-IE-and-FF. Will check

**Comment by iJungleboy** [comment]
ok, fixed...
