### ISSUE TITLE
Localized admin

### ISSUE THREAD

**Issue by ech01** [2sic/2sxc#739]
When switching to another language to add content, the admin is also localized. I think there should be an option to ovveride that with the default language or inherit from the DNN option pictured below.
![image](https://cloud.githubusercontent.com/assets/3790873/13780635/4c5134a0-ea8e-11e5-8527-f84ebcc05c63.png)

**Comment by iJungleboy** [comment]
I have no idea what this would take - so anybody wanting to do this / sponsor it ok, ATM low priority.

**Comment by ech01** [comment]
Fair enough. The person entering translated text may not be fluent in the localized content. Would be nice to have 2sxc match DNN core functionality.

**Comment by ech01** [comment]
Can you provide an estimate on adding this feature? You can email me.

**Comment by iJungleboy** [comment]
sorry, I don't know what person is behind the avatar :)
brief estimate: 

1. ca. 2h to review and determine all affected / relevant parts
2. ca. 2-4h to implement
3. ca. 2h testing
4. ca. 2-4h follow up bugs which we missed - could be date-format or other unexpected stuff
5. some reserves

In total 8-16h total time to really do it right - http://2sxc.org/en/Contact
