### ISSUE TITLE
ADAM - Cleanup

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#741]
This may be related to #515, but it would be nice if there was a utility to cleanup ADAM folders. Whenever data items are deleted, the ADAM files remain. This can become an exponentially expensive problem in instances where we are paying for storage and/or backup blobs.

Just imagine users uploading galleries of megapixel photos from their mobile phones, then the automatic resizing and caching on top of that. If the gallery images are deleted, they still remain forever.

Is it possible to create a built-in utility to identify unlinked entities and either have them removed automatically when launched by an admin or triggered by a scheduled task? And maybe the manual cleanup could show a thumbnail of the images before they are deleted and give the admin the ability to unmark certain folders and/or images for deletion.

**Comment by iJungleboy** [comment]
Anybody welcome to contribute this :)
