### ISSUE TITLE
Delete button (-) in button bar does not work

### ISSUE THREAD

**Issue by Frankwalraven** [2sic/2sxc#750]
The delete (-) button in the button bar does not doing anhything (8.3.6 version). The other buttons work correct
![schermafbeelding 2016-03-18 om 13 01 18](https://cloud.githubusercontent.com/assets/13934402/13877316/40d5fe3e-ed0a-11e5-97ee-71924a0900b0.png)

**Comment by iJungleboy** [comment]
thanks - pls give a few more details

1. Content or App-Module
2. I assume a list of items, correct?
3. were you removing a real content-item, or a demo-item (the preview-item)?

thx

**Comment by Frankwalraven** [comment]
Content
Its a list of items
I can't delete a demo item and can't delete a real item

**Comment by reaxx999** [comment]
I have the same issue in 8.3.6

1. Content module
2. list of items
3. removing a demo item as well as a real item does not work

**Comment by reaxx999** [comment]
this is very critical, because in my eyes there is no other possibility (workaround) to remove items from a specific list in this app.
