### ISSUE TITLE
8.3.6 Uninstall leaves pdb files in bin folder

### ISSUE THREAD

**Issue by jncraig** [2sic/2sxc#752]
Seems to leave a pile of .pdb files in /bin

**Comment by iJungleboy** [comment]
This is correct - I'm not sure if there is a good solution, as pdb files are important, but not really supported by dnn. I'm guessing it has no effect, just not a perfect clean up. 
 Is there a negative side-effect you are aware of?

**Comment by jncraig** [comment]
No, just noticed it.

**Comment by iJungleboy** [comment]
Ok thx. I'll close this for now, since it's not an urgent issue that we'll track actively. I'll keep in on our large list of tiny-todo.
