### ISSUE TITLE
Questions after upgrading to 8.3.6

### ISSUE THREAD

**Issue by jncraig** [2sic/2sxc#755]
I have a question after upgrading from a very old version (6.6.0) to 8.3.6.

I no longer have an Edit List on the Module Settings.  I don't want/need floating toolbars everywhere.  But I do need to exit the items in a list.  How?

Many thanks.

**Comment by iJungleboy** [comment]
as of now there is no alternative - we're moving away from the dnn-edit-buttons because they are extremely slow and cause various problems. Can you tell me why you want to avoid the in-line buttons, so that we can figure out a good way to handle your kind of use-case?

**Comment by iJungleboy** [comment]
Note: Please use descriptive titles, not just "question related to xyz" but something like "can't do this and than in such a scenario" or something.

**Comment by jncraig** [comment]
I found a better place to place the control.  I'm happy with that.
