### ISSUE TITLE
Removing a template fails if it is (or was) in use

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#759]
... even when the module using it has been removed.

**Comment by raphael-m** [comment]
The problem is that entities can't be deleted when there are relationships pointing to them. We need a way to "force" the removal of an entity even if there are relationships.

**Comment by ech01** [comment]
This would be great. Orphaned templates are cluttering up the admin for us.

**Comment by iJungleboy** [comment]
Note: in 08.04.02 a force-delete of entities is now possible. so at least it's possible to do it in the admin-ui, even if it's not available in the normal editing-ui yet.

**Comment by raphael-m** [comment]
As of now, a simple workaround exists - to implement it better, we must firt remove the asp.net webforms edit UI

**Comment by iJungleboy** [comment]
@raphael-m status today is that the webforms dialog is gone. So we could proceed on this.
