### ISSUE TITLE
delete entry

### ISSUE THREAD

**Issue by dnastone** [2sic/2sxc#763]
hello,

i can't delete an entry i always get this error message. i'm using the latest version.
i don't understand the child relationsshop between 659 and 658 cause i have no entry with the ID 658 only with 659.

AbsoluteURL:/desktopmodules/2sxc/api/eav/entities/delete
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:4fdd981a-215f-49cf-890d-3e3c1c8ef04f
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:EAwk8e4i58AWjUnePygjWA==
Message:An error occurred while executing the request. Please consult the event log for details.
StackTrace:
InnerMessage:Item 659 cannot be deleted. It is used by other items: found 1 child relationships: 658.
InnerStackTrace:
   bei ToSic.Eav.WebApi.EntitiesController.Delete(String contentType, Int32 id, Nullable`1 appId) in C:\Projects\eav-server\ToSic.Eav.WebApi\EntitiesController.cs:Zeile 310.
   bei ToSic.SexyContent.EAVExtensions.EavApiProxies.EntitiesController.Delete(String contentType, Int32 id, Int32 appId) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\WebApi\EavApiProxies\EntitiesController.cs:Zeile 217.
   bei System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClassf.b__9(Object instance, Object[] methodParameters)
   bei System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   bei System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func`1 func, CancellationToken cancellationToken)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server-Name: rs216170

**Comment by iJungleboy** [comment]
@dnastone thanks for this feedback. I'm guessing that it may be something we didn't solve perfectly, but I guess it would help if you had more information about the relationship which is preventing the delete. 

So I guess we should somehow improve the error-reporting, to ensure that you can better corner the issue, and maybe provide a "delete anyhow" feature. 

Just to help you on the short term: could you have a peek into your DB and check what content-type the entity 658 has? I'm guessing it's a hidden type needed to bind your item to a module (type ContentGroup) but I could be wrong. 

If it is this, then your quick workaround would be to show the hidden types - see http://2sxc.org/en/blog/post/advanced-dynamic-data-content-understanding-content-type-scopes and manually removing either the parent-item, or just the relationship.

**Comment by dnastone** [comment]
hello,

i looked into the dbase but idon't understand the structure of your module.
in which table i have to look for the ID 658?

i'm using for all my templates only th standard field types. i didn't created a new one.

**Comment by iJungleboy** [comment]
Check out the Eav_Entities

```
/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 1000 [EntityID]
      ,[EntityGUID]
      ,[AttributeSetID]
      ,[ConfigurationSet]
      ,[AssignmentObjectTypeID]
      ,[KeyNumber]
      ,[KeyGuid]
      ,[KeyString]
      ,[SortOrder]
      ,[ChangeLogCreated]
      ,[ChangeLogDeleted]
      ,[IsPublished]
      ,[PublishedEntityId]
      ,[ChangeLogModified]
      ,[Owner]
  FROM [2flex 2Sexy Content].[dbo].[ToSIC_EAV_Entities]
  Where EntityId = 658
```

**Comment by dnastone** [comment]
with ypur script i got one result row

658	4de7d1a8-b7f0-469f-a22a-74069b71b121	139	 	1	 	 	 	0	299	 		 	301

what does this mean to me?
thanks

**Comment by theJRK** [comment]
Any update on this?  We're having the same issue on Evoq 8.4.  Running the Eav_Entities query returns a single row.

**Comment by theJRK** [comment]
We did some digging and have successfully resolve the issue in our environment.  Your mileage may vary.  

The GUI error when deleting a row was being triggered by the key restraint on ParentEntityID in the [ToSIC_EAV_EntityRelationships] table. The delete function inside of the EntitiesController.cs appears to be the culprit. After that restraint is removed we were able to successfully remove the row via the GUI without error. We isolated the entity IDs (1410 and 1413) that we couldn't delete, then ran the following to remove them.

DELETE FROM ToSIC_EAV_EntityRelationships WHERE ParentEntityID = 1250 AND ChildEntityID IN (1410,1413)

Using this we can let the GUI do its job with minimal SQL manipulation.

**Comment by iJungleboy** [comment]
@theJRK Could you give some more details - because I believe this is something we really should look into. If I understand you correctly, the issue was that our target entities (1410 and 1413) were referred to in the entity 1250, deleting wasn't possible. Your solution was to remove the relationship from the parent, after which it was possible to delete the items that you wanted to get rid of. 
Correct?

**Comment by iJungleboy** [comment]
To all: I'm working on it and also discovered an error in the "can delete" check. I'll try to get it fixed this weekend.

**Comment by theJRK** [comment]
@iJungleboy That sounds correct. Let me know what info would be useful. I'll be available most of the weekend also and can get you a copy of the site and data prior to our data fix if that helps. Two pieces of info that might be helpful are that we upgraded 2sxc when upgrading from evoq 8.2 to 8.4, and that our solution uses angular and EF6 so we comment out the EF4 section in 2sxc web.config on each update.

**Comment by iJungleboy** [comment]
@theJRK thx for that info. Just an info back: we're sticking to ef4 for now, but once ef7 comes out we'll re-eval the situation.

**Comment by iJungleboy** [comment]
Ok :) just finish implementing optional force-delete - hope you'll love it...

**Comment by theJRK** [comment]
Thank you!
