### ISSUE TITLE
Wish: Advanced search/display features when using content-items in the entity-picker

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#764]
Please add dynamic titles which are calculated to the fly, eg.

```
   [ColumnName1] - [ColumnName2]
```

or even better

```
  [ColumnName1] + " - " +  [ColumnName2]
```

**Comment by iJungleboy** [comment]
I'll have to think about this a bit - let me just drop some thoughts

1. such a "calculated field" should probably not be limited to the title, but may be re-used in various places
2. Such kind of field may have different cases when it should be calculated. In some cases, you may want to only do this once (like the url-field) and never re-calc it again; in other cases you may want to continue to change it whenever data changes
3. the kinds of calculations needed / used may grow quickly, like requiring some math or date-manipulations - like "yyyy-MM-dd [[Category]] - [[Name]]" etc. - to cover these cases, it's probably best to support some kind of JavaScript notation - giving a lot of freedom and our system would just run it through an eval
4. Such a js-mechanism could also be used to pre-fill some fields even if not related to another field

suggestions?

**Comment by SCullman** [comment]
"Calculated Columun" was one of the the most powerful.tools within FnL.
However 2sxc is different, devs can do nearly anything they want inside razor scripts; it is quite easy to do do any projection on data and to render great views.

The situation is different as _editor_. Entities are often difficult to distinguish.Selecting the right _demo item_, building up _relationships_, managing big lists of data...

One stupid simple example:

field 1 | field 2
------|----
false | false
false | true
true | false
true | true

Neither field 1 nor field 2 would be a good candidate for a title column. In that case, a title column would be required:

title|field 1 | field 2
---|------|----
false-false|false | false
false-true|false | true
true-false|true | false
true-true|true | true

Currently I setup these title columns and educate (?) the editors to fill them correctly.
I already played with the new url-field as a replacement. Yes, pre-calculations could work.

For existing bigger lists, this would mean that all entities have to be edited and saved to fill that column - at least that's the way url-field is working. This is the main reason why I am asking for dynamic calculations on the fly. It could also work by rendering the content column triggered by changes of the definition for computing its data.

**Comment by iJungleboy** [comment]
So your use case is focused on picking an entity in a selection sometime?

Because for that, an alternate solution would be providing a more tabular / search UI when picking an entity, showing more details. Would that serve the purpose as well?

**Comment by SCullman** [comment]
It is not only the picking.
The information must remain also _after_ picking.  The important dates must be shown also directly in edit form. Think of a dictionary for super heroes. You want to be sure that the identity (realized as field of type Enitity) of Spiderman points to Peter Parker, and not to Ben or May.

**Comment by iJungleboy** [comment]
I understand. So if the list of selected entities had a few more columns, and the search-ui also had more functionality, that would work as well.

**Comment by iJungleboy** [comment]
Just an update to this - it's still in focus. The newest entity-picker already implements a kind of div-table in the background to display the items so the groundwork is laid. Theres just more complexity to it, for example in managing the settings etc. I believe we would need settings like

1. Table-Design for selected entities (with fields, maybe field-formatting etc.)
2. Table-Design for search-list
3. Fields to search in (necessary so that the server-api can do the search properly)

Another option would be to open a completely standalone search-ui for advanced searching, maybe the standard items-table without edit-functions. 

BTW: I'll rename the issue so it's clear that it's not about dynamic titles.
