### ISSUE TITLE
ADAM: Max file size

### ISSUE THREAD

**Issue by pascalmoser** [2sic/2sxc#766]
Image upload fails when image size > 10mb

![image](https://cloud.githubusercontent.com/assets/7426193/14142383/ae787b0e-f685-11e5-972c-ba4a14585ff9.png)

**Comment by iJungleboy** [comment]
We'll have to discuss what to do. I believe a reasonable limit would be good, so just increasing it or setting it to the DNN volume is not a good idea, as users will simply not use their brains when uploading.

**Comment by raphael-m** [comment]
duplicate with #897

**Comment by BeniGemperle** [comment]
There seems to be still a limit of 100 MB which is not coming from maxRequestLength in web.config. I changed that to 150 MB and the DNN file-manager uploads a file of 125 MB successfully. But ADAM doesn't even send the file to the server.

![100mb limit](https://cloud.githubusercontent.com/assets/6669093/21989788/8f9fa9b0-dc0c-11e6-86c4-cdeee86d1ef7.png)

**Comment by iJungleboy** [comment]
Created new issue, as it's not the same one #1092
