### ISSUE TITLE
Missing slash in path

### ISSUE THREAD

**Issue by nicpitsch** [2sic/2sxc#777]
Hello
Installed 2sxc 08.04.00b on a completely new DNN 7.4.2 (on localhost). After adding 2sic App it raises error:
![2016-04-11_14-25-07](https://cloud.githubusercontent.com/assets/1652835/14426890/f2488b10-fff1-11e5-9702-1a8ca2606e15.jpg)
The error within the console shows that there is a missing slash before 'DesktopModules'. C:\Projects\2Sexy... isn't my path.
Thanks a lot.

**Comment by iJungleboy** [comment]
thx - will look into it. We changed a lot of how the dialogs are called, because we removed angular from in-page and are running it in an iframe now. seems like we missed a detail about the paths...
