### ISSUE TITLE
New numeric type "Color"

### ISSUE THREAD

**Issue by mconta** [2sic/2sxc#78]
It's pretty common to configure colors in a template. 

The actual solution is to configure a string field and leave the responsibility to the end user on what hexadecimal code insert, with the obvious problems that may arise.

Colors are numbers, so a nice solution could be to add a new numeric InputType "color" with a color picker javascript dialog,a feture like the GPS input type.

This will help end users on selecting the right color without using external tools / web pages.

**Comment by iJungleboy** [comment]
@mconta now it is fairly easy to implement this using a custom input-type. If you have any questions go ahead, but otherwise just create it :). If you would share it, even better :).
