### ISSUE TITLE
App content not being returned in search

### ISSUE THREAD

**Issue by nokiko** [2sic/2sxc#781]
In the latest version 08.03.07 installed on dnn 7.4.2. The app content is not searchable. I made a test setup where i added 3 pages one with an app with list content , one with an app with just one item content and another tab with the content module. 

I put in some sample content and tried searching for it, both in the app list and the app content nothing could be found. 

The content in the content module ( not app ) however could be found and was returned. So the issue only seems to be with content in apps.

the same also happens in dnn8

**Comment by iJungleboy** [comment]
We'll have to look into it. AFAIK we just fixed this issue in 8.3.5 (see #644) but from what you are writing, it's still an issue in 8.3.7.

**Comment by iJungleboy** [comment]
Please try newest release 08.04.00i or higher and give feedback

**Comment by jncraig** [comment]
I have a site that is DNN 7.4.2 and 2sxc 8.4.2.

I have configured search to include App as a content type.

Search results are not being returned for 2sxc Apps, but search is working for the rest of the site.  Unique content (in HTMLmodules) on the pages that contain 2sxc modules is returned.

I believe that search works correctly on another site that is DNN8 and 2sxc 8.4.2.

I do not (right now) have the option of updating the 7.4.2 site to DNN 8.

**Comment by iJungleboy** [comment]
@jncraig AFAIK everything should work. I recommend that you do some further debugging to corner the issue. Also check http://2sxc.org/en/docs/tag/search

**Comment by jncraig** [comment]
Any suggestions re debugging?  Is there something in the Lucene files that might help uncover this?

**Comment by iJungleboy** [comment]
I recommend to focus on the 2sxc part. add the methods I linked to to your template and log whatever happens, so that you can see if search is arriving, and what it would want to index. my guess is your code does something unexpected (maybe need a request object) which doesn't exist when search is running.
