### ISSUE TITLE
source-editor-snippets-de.js missing

### ISSUE THREAD

**Issue by mcshorty** [2sic/2sxc#782]
Module version: 8.3.7
DNN version: 7.4.2
Portal language: de-DE

The source editor searches for the file source-editor-snippets-de.js - which is not available.

**Comment by iJungleboy** [comment]
Does it cause an error for the user, or are you mainly observing the http-traffic?

**Comment by mcshorty** [comment]
![error_source-editor-snippets-de js_20160415](https://cloud.githubusercontent.com/assets/6585915/14560209/5dd6b338-030e-11e6-8448-7d3703162862.png)

**Comment by iJungleboy** [comment]
ok, that's odd. It should auto-fallback to EN in the labels if it's missing. Will check.

**Comment by mcshorty** [comment]
No more problem in
Module version: 8.4.0
DNN version: 8.0.1
Portal language: de-DE
