### ISSUE TITLE
Provide Quick-Insert for DNNEmptyPane

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#787]
Concept
1. when the control is included
2. add a rule which makes the DNNEmptyPane with:auto
3. provide documentation, how to handle in in case web designers were using the "invisible pane" to perform layouting

idea: also include a comment with a link to documentation...

**Comment by thomassen88** [comment]
Hi, the "quick-insert" is an awesome feature :) but how do i disable it? i dont want the feature to be active for one of my customers.

**Comment by iJungleboy** [comment]
We're still working on that - whenever we add complexity and enable/disable we want to be sure we thought of all use cases. So for now please just use your fix, there are some really awesome use cases which need the quick-insert, so we can't standardize disabling yet.

**Comment by iJungleboy** [comment]
Documentation ready on http://2sxc.org/en/blog/post/quick-edit-to-add-content-and-app-modules-in-1-2nd-one-second

**Comment by tpperlman** [comment]
Hi folks. I'd like to disable this too for admins. Maybe you can have it hidden if the Portal's Extension setting forbids Admins from deploying the app?
![capture](https://cloud.githubusercontent.com/assets/1871915/15894003/58494b48-2d51-11e6-9d8b-27d5ac93a0ea.JPG)

**Comment by iJungleboy** [comment]
Sound like a good idea, but would take a few hours of working through - contributions welcome :)
