### ISSUE TITLE
Add a Top/Bottom link on the Manage Content Types

### ISSUE THREAD

**Issue by mconta** [2sic/2sxc#79]
On the Manage Content Types (Data Structure/Schema) window when the fields are numerous (>10) it's pretty uneasy to move the new fields to the top of the list (or bottom).
Adding Top/Botton links to the Up/Down links may help. 

So the last column in the "Data Structure/Schema" could change from "Up-Down" to "Top-Up-Down-Bottom".

**Comment by iJungleboy** [comment]
The ui is much faster now that it's JS :) - I assume this is not important any more, will close.
