### ISSUE TITLE
Provide some kind of edit / edit-template buttons in-page if the template doesn't provide any with a toolbar

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#791]

**Comment by iJungleboy** [comment]
Very tricky. Tried it, but @Content.Toolbar breaks, because there is often no content-item yet (if no demo was assigned).

**Comment by SCullman** [comment]
How about placing the edit button into the view selector?
![image](https://cloud.githubusercontent.com/assets/5693190/14845579/4abbae84-0c5f-11e6-9b4c-9f64cc1f806f.png)
