### ISSUE TITLE
Field names with spaces in them

### ISSUE THREAD

**Issue by ech01** [2sic/2sxc#792]
If you setup a field with a space in the name, razor fails. Ex: "@Content.My Field" 

Either you should be able to use field names with spaces or the admin should disallow it.  Preference would be to allow it and replace the space with an underscore when using the token ex: @Content.My_Field.

**Comment by iJungleboy** [comment]
The concept is to not allow it - including also umlauts and things like that. There's too much guesswork how to do it properly, and we know how the SharePoint solution (which allows this kind of stuff) causes loads of problems downstream. 

So nope: not allowed. But I admit, the admin-ui should prevent the incorrect initial naming.

**Comment by iJungleboy** [comment]
I just implemented field-rename :)
