### ISSUE TITLE
can not install 2sxc 08.04.01 on azure dnn platform 8.0.1

### ISSUE THREAD

**Issue by kingjordan** [2sic/2sxc#795]
here is the error I get when trying to instal the extension in my site:

StartJob	Starting Installation
... other stuff
Info	Executing 02.00.00.SqlDataProvider
Info	Start Sql execution: 02.00.00.SqlDataProvider file
Failure	

> SQL Execution resulted in following Exceptions: System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'IsCurrent'. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) 

The sql error is very large so I added it to an attached text file:
[2sxc_instal_error.txt](https://github.com/2sic/2sxc/files/229199/2sxc_instal_error.txt)

This is a v12 sql azure database

I had successfully updated 2sxc on a different dnn site on the same sql server, but that site version is still 7.0.4

**Comment by kingjordan** [comment]
I uninstalled the partially installed 2sxc and then tried to go back and install 2sxc 8.4.0,

I got the same error

**Comment by iJungleboy** [comment]
thx, will prioritize!

**Comment by iJungleboy** [comment]
Just before I invest too much time...did you read my blog about this? it's important when upgrading

http://2sxc.org/en/blog/post/moving-existing-2sxc-installations-from-azure-sql-11-to-azure-sql-12

**Comment by iJungleboy** [comment]
My tests seem to work (aside from the upgrade-issue which is explained in the blog). I'll close this for now.

**Comment by kingjordan** [comment]
Hello,

I did read the blog, However, 2sxc was never installed in this DNN instance until after the dnn instance was upgraded to 8.0.1.  So I don't think that I needed to do any preparation before installing the module

**Comment by iJungleboy** [comment]
So basically you are correct - if it was never installed, no worries. BUT - if it had been installed/uninstalled, the odds are great that some tables / stored procedures are still in the system, in which case unexpected things could happen. 

It's also the case that if an installation ever blows, there is no clean way to clean-up in DNN, it just fails there. So again there are cases where stuff is left over, which can hurt you later on. 

Please
1. Go to the DB and remove all tables related to 2sxc
2. try again :)

**Comment by kingjordan** [comment]
okay, will do and let you know,

On Thu, Apr 21, 2016 at 6:47 AM, iJungleboy <notifications@github.com>
wrote:

> So basically you are correct - if it was never installed, no worries. BUT
> - if it had been installed/uninstalled, the odds are great that some tables
> / stored procedures are still in the system, in which case unexpected
> things could happen.
>
> It's also the case that if an installation ever blows, there is no clean
> way to clean-up in DNN, it just fails there. So again there are cases where
> stuff is left over, which can hurt you later on.
>
> Please
> 1. Go to the DB and remove all tables related to 2sxc
> 2. try again :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/2sic/2sxc/issues/795#issuecomment-212902593>
>



-- 
Jordan King
*KRISIS KONCEPTS*
*Owner / Lead Developer*

jordan@krisis.ca
*WWW.KRISIS.CA <http://WWW.KRISIS.CA>*


*Twitter: KrisisKoncepts <https://twitter.com/KrisisKoncepts>*

*Facebook: KrisisKoncepts <http://www.facebook.com/KrisisKoncepts>*
*Pinterest: KrisisKoncepts <http://www.pinterest.com/KrisisKoncepts/>*

**Comment by kingjordan** [comment]
Update, so not sure why the first attempted install failed, but I cleaned out all existing 2sxc database objects and tried again and everything seems to be working.

Thanks again
