### ISSUE TITLE
Cannot always cancel edits in 8.4.2

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#803]
When you open an entity for edit, it is sometimes not possible to cancel editing, as the button "Not save" doesn't work all the time and you cannot close the edit form again. 
![image](https://cloud.githubusercontent.com/assets/5693190/14790078/f76d363a-0b0f-11e6-886b-0b499054da46.png)
In my tests it wasn't possible to cancel "direct" edits started with a toolbar action.

**Comment by iJungleboy** [comment]
I can't reproduce. Could you try to debug some more?

* do you have JS errors? 
* does it only happen if you try to close very quickly?
* does it only "not work" the first time but does work if you do it again?

**Comment by iJungleboy** [comment]
was able to reproduce - it feels a bit random. can't figure out the cause yet.

**Comment by iJungleboy** [comment]
ok, figured it out. the click-check doesn't work if you hit the icon, only if you hit the text of the button. must fix...
