### ISSUE TITLE
no collapsed titles 8.4.4

### ISSUE THREAD

**Issue by Frankwalraven** [2sic/2sxc#828]
Upgrade from a site from 8.4.2 to 8.4.4 . It sayed the upgrade was succesfull
In this site I can't set the collapsed titles. And the language stays english. Its says its upgraded to 8.4.4

Did a restore of the site and tryed it again and no luck

With another site I did the same and I could set the collapsed titles. With this site I got after the upgrade an message: Error: System.Exception: Module upgrade did not complete (read more). Click to complete:. I didn't got this message to convert data with the other site, where the collapsed tittles don't work. 

Looks like the conversion of the first site does not the data conversion. Bot sites don't have the dutch language

**Comment by Frankwalraven** [comment]
There is some dutch. But its a mix of english and dutch

**Comment by Frankwalraven** [comment]
With some other sites also no settings to set titles to be collapsed. The site where it works is not there anymore - was test. So of it somewhere can work I don't know

**Comment by iJungleboy** [comment]
just fyi: dutch is only translated for the content-editor. the UI is not translated. 

Please check - is the App showing this new setting? 
![image](https://cloud.githubusercontent.com/assets/5321186/15090666/60656388-142f-11e6-88ca-861064f24435.png)

**Comment by Frankwalraven** [comment]
Noop
![titel](https://cloud.githubusercontent.com/assets/13934402/15090694/7211f2f8-1430-11e6-9ed9-e3606e526c83.png)

**Comment by Frankwalraven** [comment]
dont't find the screen you show. The templates are not realy inside an app.
Have only the field settings. 
![titel](https://cloud.githubusercontent.com/assets/13934402/15090711/7733058c-1431-11e6-8f2f-10663e2ba553.png)

**Comment by Frankwalraven** [comment]
![schermafbeelding 2016-05-07 om 08 56 28](https://cloud.githubusercontent.com/assets/13934402/15090718/aaccdd0a-1431-11e6-950d-f57d5cced8fc.png)
![schermafbeelding 2016-05-07 om 08 56 28](https://cloud.githubusercontent.com/assets/13934402/15090725/0ab86dec-1432-11e6-99e9-c04346b49472.png)

**Comment by Frankwalraven** [comment]
Also in the edit dialog not everything is translated.
![schermafbeelding 2016-05-07 om 09 03 07](https://cloud.githubusercontent.com/assets/13934402/15090743/d72c2c9c-1432-11e6-85cf-8cb3de73ab76.png)
The names of the sections: 
Content = inhoud
Presentations settings = Opmaak instellingen

When you choose the cross in the right upper corner
![schermafbeelding 2016-05-07 om 09 03 57](https://cloud.githubusercontent.com/assets/13934402/15090749/389482b8-1433-11e6-93ba-64fc58b5e464.png)
save = opslaan
not save = niet opslaan

**Comment by iJungleboy** [comment]
Ok, let's quickly split the issues as this two in one will be confusing. 

New issue: 
* NL language pack is missing some end-user translations #829

I'll clean up the stuff in this issue, which is not related to the missing fields

**Comment by iJungleboy** [comment]
So please follow up on the language parts in #829. I'll follow up on this.

did you do anything special in the upgrade?

Could you delete the desktopmodules/2sxc.../Upgrade/Log/08.04.04.rsources and restart your dnn? this should force 2sxc to re-apply the last xml-import.

**Comment by iJungleboy** [comment]
I think I found the issue - there was something wrong with some version numbers in the installer of 08.04.04. I'll try to fix in in 08.04.05.

So 08.04.03 added it, but if you went directly to 08.04.04 from anything lower, it skipped it.
