### ISSUE TITLE
NL language pack is missing some end-user translations

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#829]
Created to split the issue #828 which was two issues in one.

**Comment by iJungleboy** [comment]
Copied stuff from Frank on the issue #828 

Also in the edit dialog not everything is translated.
![schermafbeelding 2016-05-07 om 09 03 07](https://cloud.githubusercontent.com/assets/13934402/15090743/d72c2c9c-1432-11e6-85cf-8cb3de73ab76.png)
The names of the sections: 
Content = inhoud
Presentations settings = Opmaak instellingen

When you choose the cross in the right upper corner
![schermafbeelding 2016-05-07 om 09 03 57](https://cloud.githubusercontent.com/assets/13934402/15090749/389482b8-1433-11e6-93ba-64fc58b5e464.png)
save = opslaan
not save = niet opslaan

**Comment by iJungleboy** [comment]
The headings of the edit-dialog were currently this in the language file

```
  "EditFormTitle": {
    "Content": "Content",
    "Presentation": "Presentatie instellingen",
    "ListContent": "Lijst Header Content",
    "ListPresentation": "Lijst Presentatie Instellingen",
    "Metadata": "Toevoegen / Bewerken Metadata"
  },
```
is it correct, to change it to
```
  "EditFormTitle": {
    "Content": "Inhoud",
    "Presentation": "Opmaak instellingen",
    "ListContent": "Lijst Header Content",
    "ListPresentation": "Lijst Opmaak Instellingen",
    "Metadata": "Toevoegen / Bewerken Metadata"
  },

```

**Comment by iJungleboy** [comment]
Could you also translate
```
{
  "General": {
    "Note2Translator": "these are the main keys for buttons and short messages, used in various dialogs",
    "Buttons": {
      "Add": "add",
      "Cancel": "cancel",
      "Copy": "copy",
      "Delete": "delete",
      "Edit": "edit",
      "ForceDelete": "force delete",
      "NotSave": "not save",
      "Permissions": "permissions",
      "Refresh": "refresh",
      "Rename": "rename",
      "Save": "save",
      "System": "advanced system functions"
    },
    "Messages": {
      "Loading": "loading...",
      "NothingFound": "no items found",
      "CantDelete": "can't delete {{target}}"
    },
    "Questions": {
      "Delete": "are you sure you want to delete {{target}}?",
      "DeleteEntity": "delete '{{title}}' ({{id}})?",
      "Rename": "what new name would you like for {{target}}?",
      "SystemInput": "This is for very advanced operations. Only use this if you know what you're doing. \n\n Enter admin commands:",
      "ForceDelete": "do you want to force delete '{{title}}' ({{id}})?"
    },
    "Terms": {
      "Title": "title"
    }
  }
}
```

**Comment by Frankwalraven** [comment]
`{
  "General": {
    "Note2Translator": "these are the main keys for buttons and short messages, used in various dialogs",
    "Buttons": {
      "Add": "Toevoegen",
      "Cancel": "Annuleren",
      "Copy": "Kopiëren",
      "Delete": "Verwijder",
      "Edit": "Bewerken",
      "ForceDelete": "Geforceerd verwijderen",
      "NotSave": "Niet opslaan",
      "Permissions": "Rechten",
      "Refresh": "Verversen",
      "Rename": "Naam veranderen",
      "Save": "Opslaan",
      "System": "Geavanceerde systeem functies"
    },
    "Messages": {
      "Loading": "Laden...",
      "NothingFound": "geen items gevonden",
      "CantDelete": "kan {{target}} niet verwijderen"
    },
    "Questions": {
      "Delete": "Weet je zeker dat je {{target}} wilt verwijderen?",
      "DeleteEntity": "Verwijder '{{title}}' ({{id}})?",
      "Rename": "Welke nieuwe naam wil je voor {{target}} instellen?",
      "SystemInput": "Dit is voor zeer geavanceerd gebruik. Gebruik deze functionaliteit alleen indien je weet wat je doet! . \n\n Geef admin commando's:",
      "ForceDelete": "Wil je  '{{title}}' ({{id}}) geforceerd verwijderen?"
    },
    "Terms": {
      "Title": "Titel"
    }
  }
}`

**Comment by Frankwalraven** [comment]
`"EditFormTitle": {
    "Content": "Inhoud",
    "Presentation": "Opmaak instellingen",
    "ListContent": "Lijst basis inhoud",
    "ListPresentation": "Lijst opmaak instellingen",
    "Metadata": "Toevoegen / Bewerken Metadata"
  },
`

**Comment by iJungleboy** [comment]
awesome :) 

fyi - if you use three apos characters and a new line, then the code can be multi-line formated - I just fixed your other comment.

**Comment by iJungleboy** [comment]
just released - pls try :)

**Comment by Frankwalraven** [comment]
Looks like this one is not updated - or not working
"EditFormTitle": {
    "Content": "Inhoud",
    "Presentation": "Opmaak instellingen",
    "ListContent": "Lijst basis inhoud",
    "ListPresentation": "Lijst opmaak instellingen",
    "Metadata": "Toevoegen / Bewerken Metadata"
  },

**Comment by Frankwalraven** [comment]
The colapsed titel works :-)

**Comment by iJungleboy** [comment]
yea :)!

**Comment by iJungleboy** [comment]
Language: 
what language labels to you see on button mouseovers? 
![image](https://cloud.githubusercontent.com/assets/5321186/15108841/7cbb5060-15d8-11e6-9bce-36b2a1f226b9.png)

**Comment by Frankwalraven** [comment]
english ones

**Comment by iJungleboy** [comment]
Ok, so your in-page JS assumes you're using EN, not NL. That's the core issue. The in-page is also the part which hands the titles into the edit-dialog. I'll have to review why it's picking up the wrong in-page language...

**Comment by iJungleboy** [comment]
BTW: it seems that in the current versions, the other ui languages also don't detect correctly...

**Comment by iJungleboy** [comment]
Seems to be an issue with PortalSettings.CultureCode...

**Comment by iJungleboy** [comment]
Should be fixed in https://github.com/2sic/2sxc/releases/tag/v08.04.05-01

**Comment by Frankwalraven** [comment]
there is no installer

**Comment by iJungleboy** [comment]
ok, available now, sorry.

**Comment by Frankwalraven** [comment]
Installed the update, but the part is still english

**Comment by iJungleboy** [comment]
could I have a quick look at your system so I don't have to setup an NL system? maybe send me url and login to info ... 2sxc.org

**Comment by iJungleboy** [comment]
Thanks for the access, I was able to fix it. Will be in the next release this week...
