### ISSUE TITLE
Template name not visible in selector dropdown if template is hidden

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#831]
If a template is set to hidden but used somewhere, the selector UI shows a blank select (no options). Make sure the template name is visible.

**Comment by iJungleboy** [comment]
Is this a real problem? I can reproduce the situation but the dropdown is disabled (is that maybe different when other possible templates apply?

**Comment by iJungleboy** [comment]
must be done in 8.5.2 because the server api now delivers all templates and content-types (hidden too) to the UI. So now the js must be adsjusted...
