### ISSUE TITLE
Can not select newly created app

### ISSUE THREAD

**Issue by kingjordan** [2sic/2sxc#832]
Hello,

I have a 7.3.4 DNN platform running in MS azure with 2sxc 8.4.5

I tried to create a new app,  I was able to create the app, create some content with fields and even a demo item.  I then tried to create a view for the app and selected the demo item and marked the view as supporting lists.  This worked without error

When I return to the page where the app is installed, my newly created app is the default selected app because it is the only app in this portal. and when I click the check mark next to the app list the page throws a dialog error.

The following is the error logged in the site's event viewer:

RawURL:/cherylmuth/DesktopModules/2sxc/API/view/module/savetemplateid?templateId=0&forceCreateContentGroup=false&newTemplateChooserState=false
AbsoluteURL:/cherylmuth/DesktopModules/2sxc/API/view/module/savetemplateid
InnerException:The given key was not present in the dictionary.
Method:System.Collections.Generic.Dictionary`2.get_Item
StackTrace:
Message:
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ToSic.SexyContent.ContentBlock.ContentGroupReferenceManagerBase.SaveTemplateId(Int32 templateId, Boolean forceCreateContentGroup, Nullable`1 newTemplateChooserState) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ContentBlock\ContentGroupReferenceManagerBase.cs:line 54
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass13.<GetExecutor>b__c(Object instance, Object[] methodParameters)
   at System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func`1 func, CancellationToken cancellationToken)

Not sure what is going on here as I can confirm the creation of the app, the template and the content and items.

Any idea what is going on?

Thanks in advance

Jordan

**Comment by kingjordan** [comment]
when I log in with ftp I can see the 2sxc file in the portal and the folder name of the app as well as the template.html that I created.

**Comment by kingjordan** [comment]
I tried importing an app from the 2sxc.org app catalog.  I used the new blog app.  After it imported I tried to select it and click the check mark.  I got the same error, but the page reloaded and the app appeared.  So I then tried to select the app I created and it now works.  

I still periodically get this error appearing but I seem to be able to switch apps if I switch back and forth a couple times.

This is probably an issue with my environment, but I thought I would post this to see if it helps.  If not feel free to remove this issue.

**Comment by iJungleboy** [comment]
Thanks for this. I have an idea what it is. Could it be that the error appears only if you open the dialog coming from a different app then the one you checkboxed?

**Comment by iJungleboy** [comment]
Could you include a screenshot of what button you clicked?

**Comment by kingjordan** [comment]
Hello,

I attached a screen shot.  I got the error in the following way:
- I opened the creat app admin window
- I created the app and content etc...
- I closed the admin window for adding new apps and attempted to click the "check" (highlighted in the screen shot)
- The error appears as soon as I click the "check" to confirm the app choice for this module.

**Comment by iJungleboy** [comment]
That helped a lot - thanks :)

I'm almost certain the UI is somehow confused because it doesn't have a template to show in the template/view-picker. OR it's confused because you only have 1 app or 1 template. could you do a few more tests with this and give me feedback?

**Comment by kingjordan** [comment]
Hello Daniel,

I have made a video that shows these errors being generated in a portal that I have not used 2sxc in before.  This time it let me add the template and confirm the app eventually.  You will see what I mean.  I used wetransfer.com to send the video to you (to you @sic.org email).  I hope that is okay as the video is too large to post here

**Comment by iJungleboy** [comment]
Perfect, the screencast has helped :)
Could you also say what tool you used - I may use it once :)

I believe the issue is something fairly deep, which uses the app-id of the original page-state when getting the view-list. As you didn't have an app-id (nothing was selected yet) it showed the error. I'll have to check that. I assume once you picked the app and went to admin again, everything worked. correct?

**Comment by kingjordan** [comment]
Yes, the issue goes away once there is one or more apps with one or more
views for each app.  The tool i used is called icecream screen recorder.
Its free ware but works for simple screen captures like the one I sent you.



On Thu, May 12, 2016 at 9:17 AM, iJungleboy <notifications@github.com>
wrote:

> Perfect, the screencast has helped :)
> Could you also say what tool you used - I may use it once :)
>
> I believe the issue is something fairly deep, which uses the app-id of the
> original page-state when getting the view-list. As you didn't have an
> app-id (nothing was selected yet) it showed the error. I'll have to check
> that. I assume once you picked the app and went to admin again, everything
> worked. correct?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/2sic/2sxc/issues/832#issuecomment-218789781>
>



-- 
Jordan King
*KRISIS KONCEPTS*
*Owner / Lead Developer*

jordan@krisis.ca
*WWW.KRISIS.CA <http://WWW.KRISIS.CA>*


*Twitter: KrisisKoncepts <https://twitter.com/KrisisKoncepts>*

*Facebook: KrisisKoncepts <http://www.facebook.com/KrisisKoncepts>*
*Pinterest: KrisisKoncepts <http://www.pinterest.com/KrisisKoncepts/>*
