### ISSUE TITLE
Serializer: _2SxcEditInformation node is only appended if in EditMode

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#834]
The serializer (`Sxc.Serializer.Prepare(...)`) should append `_2SxcEditInformation` when someone has edit rights (the same condition that decides whether to show toolbars or not). Currently, the edit information is only appended in edit mode, which causes JS-toolbar actions to fail if not in edit mode.

Affected are all custom JS toolbars (including the AngularJS sxc-toolbar directive) that handle entities loaded from WebApi or a different way with `Sxc.Serializer.Prepare`.

**Comment by iJungleboy** [comment]
Some things I discovered
1. Using the "in-page" method with GetContentBlockData (the $2sxc.data) always delivers the _2sxcEditInfo - but this bypasses the eav serializer and return a string created with jsonconvert
2. there is a check for the the edit-state which we'll have to look at
3. additionally it seems that the simple Prepare-statement doesn't even do the expected prepare, but route directly to the eav.prepare (which doesn't know about the _2sxcEditInfo...

**Comment by iJungleboy** [comment]
Was able to reproduce the basic issue with a query-designer pipeline...

**Comment by iJungleboy** [comment]
I made some changes but @raphael-m  will have to test/verify...

**Comment by iJungleboy** [comment]
Confirmed, fixed.
