### ISSUE TITLE
Entity Picker fails when a default value is set

### ISSUE THREAD

**Issue by pascalmoser** [2sic/2sxc#835]
When a GUID from an valid entity is set as default value, the correct entity is assigned after saving, but the Entity-Picker fails:

![image](https://cloud.githubusercontent.com/assets/7426193/15175614/73fb3f36-1767-11e6-8f67-913a390b25d1.png)
(The field office has data-type "Entity" with the default value "75e331ba-f316-4bc1-9a96-e6093c4dd8d7" set in the General Settings)

**Comment by iJungleboy** [comment]
Note: I'll also have to check prefill - might have the same effect...

**Comment by iJungleboy** [comment]
Fixed. Note that various formats are supported:

1. aoeuaou-aoueaou-aoeuaou-aoeuau
2. {aoeuaou-aoueaoue-aoeuaou-aoeuaou}
4. [{aoeuaoeu-aoeuaoue-aoeuaoue},{aouaou-aoeuaoue-aoeuaou}]
