### ISSUE TITLE
In-ValueProvider - Visual Query Designer

### ISSUE THREAD

**Issue by pircjernej** [2sic/2sxc#842]
When I try to make app from start like in:
http://2sxc.org/en/Docs-Manuals/Feature/feature/4544

The In-Value Provider seems that allways is null and return fallback value.
QueryString part work OK.

Tested with different DataSources : ValueSort, RelationshipFilter
Tested with string and entity input types

dnn :  08.00.02
2sxc : 08.04.05

**Comment by pircjernej** [comment]
Also if I download ind install:
2sxcApp_TutorialQuery-DiscoverVisualQuery_01.00.00.zip
from 
http://2sxc.org/en/apps/app/tutorial-query-discover-the-visual-query-designer-for-2sxc-dnn-dotnetnuke

tested view : Tutorial Query - Discover Visual Query
work OK

But when in designer and try to run query error is displayed:
[error screenshot](http://asnm.dnd.si/filter2.jpg)

**Comment by iJungleboy** [comment]
To 95% probability your test-values are wrong, so the query then runs into problems. I'm assuming you're using it to provide a module-level item to the query as a parameter. 

Remember that

1. The test-value for the module-id must be a real module which would contain the data that you need

if you installed an existing app, then it will work, but when you test it in the query designer it still has the original module-id in the test-list (which is not your module id)

**Comment by pircjernej** [comment]
Yes you are 100% right...
Now this work OK
I did not know how this test parameter work, now i know this.

But this don't solve my problems about In-ValueProvider,
only the yours sample work. Any idea what I do wrong in my module,
that cant recive In-ValueProvider data?

**Comment by iJungleboy** [comment]
I can only guess. Remember that after "In:" comes the name of the stream which delivers attributes. So if your module has values (remember to check that) and your passing it to the query as "Module" or whatever, that's what the In should be like, like "[In:Module:SortOrder]"
