### ISSUE TITLE
Rendering of Inner Content Block not showing data

### ISSUE THREAD

**Issue by joshgk00** [2sic/2sxc#843]
I'm using 2sxc 08.04.05 and I'm trying to use the Inner content blocks. I have my template setup similar to the demo/blog 

http://screencast.com/t/LlePZ941Xbc

I've setup everything else the way the blog suggests, but nothing is being rendered. The HTML on my page looks like this screenshot below. It looks as though the placeholder is there but no content.
http://screencast.com/t/u6MhtkWIhJB

The console in chrome is showing that it found the one content block that I have setup
http://screencast.com/t/i7zkwuiQN

Am I missing something else?

**Comment by iJungleboy** [comment]
The comment you see appears when you render a content-item which is not a content-block-reference. You probably added a content-item manually in the edit dialog. 

You are certainly missing the Context-Attributes in the div around your content-blocks. these are necessary, so the UI can help the user add items. Try inserting the loop from the sherlock-snippet, that should fix everything.
