### ISSUE TITLE
Error (400) - Copy Query command - In Administration / Query

### ISSUE THREAD

**Issue by pircjernej** [2sic/2sxc#844]
When I try to copy Query error popup is displayed.
Tested with clean dnn 8.0.2 and 2sxc 8.4.5

**Comment by iJungleboy** [comment]
Could you add screenshots and maybe a pic of the original query you wanted to copy? Additional info like the exact error in fiddler and/or the js console would also help.

**Comment by pircjernej** [comment]
I posted app source on StackOverflow with screenshot of error.
[LINK](http://stackoverflow.com/questions/37243596/error-at-copying-query-in-my-app-for-2sxc-dnn-module)

**Comment by iJungleboy** [comment]
Seems to be an issue, will re-open.
