### ISSUE TITLE
v8.4.6: TinyMCE-WYSIWYG missing in IE 11 (Win 10)

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#846]
the editor field acts like a normal text field. The TinyMCE toolbar does not get visible on Internet Explorer 11 on a Windows 10 machine. It works on Chrome. 

This is the 2nd installation with 2sxc 8.4.6 where this problem appeared.
This problem did not happen directly before the update with v8.4.2. (verified)

**Comment by iJungleboy** [comment]
I can reproduce it, but have no idea why this is...there is a JS error in the console of tinyMCE. Note that Edge also seems to be affected...
