### ISSUE TITLE
affects v8.4.6: Publish changes "previous value disappears"-bug

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#849]
strange issue with publish changes. the title disappears, if you use the previous title again after unpublished save.

you can easily reproduce it with the following steps:
1. edit existing entity with title i.e. "A" to i.e. "AB", do unpublished save
2. now publish the unsaved changes 
3. change title "AB" back to old title "A", do publishing save

Now the title is not visible anymore (not in frontend nor in edit view). 

It won't help if you re-do step 3. If you want "A" as title back, you have to… 
1. enter a title that is different to "A" (like "AZY", or also "AB"), do publishing save
2. change the title back to "A", do publishing save

**Comment by iJungleboy** [comment]
Are we talking about the DNN-module title, or the entity-title?

**Comment by reto-f-999** [comment]
entity-title, but in fact it can be any field of the content-type.

**Comment by iJungleboy** [comment]
should be fixed with publish-fixes in 08.08
