### ISSUE TITLE
JS API Calls are unauthorized.

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#850]
I can't get calls 
 $2sxc(moduleId).data 
to work, it always returns a 401/ (unauthorized), "publish data" is enabled.

As the same happens here: http://2sxc.org/dnn-app-demos/en/Apps/JS-API-and-JSON-Demos ,
I expect that this is a bug in 8.4.6.

**Comment by iJungleboy** [comment]
This is strange. The reason seems to be that the AJAX call doesn't seem to include the ModuleId and TabId...

**Comment by iJungleboy** [comment]
Strange: on another system it works (with 2sxc 8.5 beta), but I never changed anything afaik...

**Comment by SCullman** [comment]
At least you can reproduce the issue. Thank you for checking quickly.

**Comment by iJungleboy** [comment]
it's somehow a dnn problem, but I'm not sure why. The SF (services framework) isn't adding the tabid, antiforgery etc. headers. Maybe a timing issue with document.ready or something. 

I won't be able to look at this in the next few days, but would appreciate if you could figure out the full cause.

**Comment by SCullman** [comment]
It was still working in 8.3.7 and starts failing beginning with 8.4.0.

**Comment by iJungleboy** [comment]
Ok, figured it out. One example (the one using knockout) was not in a document.ready - because of this, the DNN services-framework did something strange for all following calls. I'll fix it and re-publish the demo-app.

**Comment by SCullman** [comment]
...and I took the KO example as starting point for my own spike. 
Wrapping the js script in $(function () { }) as usual fixed it.

Strange that it has ever worked in earlier versions.

**Comment by iJungleboy** [comment]
I believe something in 2sxc changed a bit, so maybe it's faster now - causing the differenc in behaviour.

fixed and republished 
http://2sxc.org/en/apps/app/javascript-api-and-json-demos
