### ISSUE TITLE
save data takes in one site arround 30 seconds

### ISSUE THREAD

**Issue by Frankwalraven** [2sic/2sxc#852]
We have a site where saving data in 2sxc cost arround 30 seconds. In other sites less than 1 second. When you look to the network log it hangs more then 24 seconds at this command:

```
POST /desktopmodules/2sxc/api/eav/entities/savemany?appId=13 HTTP/1.1
Host: www.perfocus.nl
Connection: keep-alive
Content-Length: 5146
TabId: 94
Pragma: no-cache
RequestVerificationToken: abcdefgihjklmnop
Origin: https://www.perfocus.nl
Debugging-Hint: bootstrapped by 2sxc4ng
ContentBlockId: 589
Content-Type: application/json;charset=UTF-8
Accept: application/json, text/plain, */*
Cache-Control: no-cache
ModuleId: 589
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Referer: https://www.perfocus.nl/desktopmodules/tosic_sexycontent/dist/dnn/ui.html?sxcver=8.4.6.38257
Accept-Encoding: gzip, deflate
Accept-Language: en,nl;q=0.8,en-US;q=0.6,de;q=0.4
Cookie: .ASPXANONYMOUS=wpQzw-3Esm-X7hdxnXXC_r3ZP7FR6gWUs4FcSLvyfAEAkIlJjkfuJzeW0LlqiqIRqd661w-3bnKb1zDjLw0aYI7Lcr5cyn_7Jy48PQ5Xd01RjT8p0; OriginalReferrer=--; LandingPage=http://www.perfocus.nl/; __RequestVerificationToken=fN3bvfrgTdUjWillC38V_0nZUJeWBYKb_r33ZhhswrMi0OX2lEGzyJrM_hiEluC2XPJqWg2; __utmt=1; __utma=19051577.922156937.1463823977.1464013200.1464021627.6; __utmb=19051577.2.10.1464021627; __utmc=19051577; __utmz=19051577.1463823977.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); DotNetNukeAnonymous=b833745d-441f-4a9b-b9a5-0536b7547af9; USERNAME_CHANGED=; authentication=DNN; .DOTNETNUKE=78F8FC2C9F4F9A5EF5471B4908412F8FFBF435EDB0ACBCA6F977DCCF95E38858DF2517CC13ECDFC305342CCA43F462DACF937BFE48587C3709C48FF6EA4C40922478B13389DC0E0D22C029A1; LastPageId=0:94; StayInEditMode=NO; dnn_IsMobile=False; language=nl-NL


```

When you go over the command you see it goes to
https://www.perfocus.nl/desktopmodules/2sxc/api/eav/entities/savemany?appId=13

But in the sitestructure there is no "/desktopmodules/2sxc" directory. I don't know or this may be the cause. Do you have any clue
Thanks

**Comment by iJungleboy** [comment]
This is the normal save-api for the edit dialog. That "2sxc" is routed to the web-api is a routing configuration, so there is no folder for this. 

Regarding the timing issue, please provide more details. Like is it a complex content-type? what version of 2sxc / dnn?

Maybe some screenshots would help - just so I can better guess what's going on.

**Comment by iJungleboy** [comment]
I'll close this for now, as I assume it's not a 2sxc issue but something with your environment, in which case it's best to continue this in stackoverflow - http://2sxc.org/en/blog/post/moving-discussions-from-codeplex-to-stack-overflow
