### ISSUE TITLE
Inner Content Block error

### ISSUE THREAD

**Issue by pircjernej** [2sic/2sxc#856]
If I try to add Blog App as Inner Content Block to my module I get error:

`Error: System.Exception: Error getting List of Stream. Stream Name: Default DataSource Name: ModuleDataSource ---> System.Exception: Looking up ContentGroup failed because ModuleId is null. at ToSic.SexyContent.DataSources.ModuleDataSource.get_ContentGroup() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\DataSources\ModuleDataSource.cs:line 42 at ToSic.SexyContent.DataSources.ModuleDataSource.GetContent() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\DataSources\ModuleDataSource.cs:line 62 at ToSic.Eav.DataSources.DataStream.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataStream.cs:line 87 --- End of inner exception stack trace --- at ToSic.Eav.DataSources.DataStream.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataStream.cs:line 98 at ToSic.Eav.DataSources.BaseDataSource.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\BaseDataSource.cs:line 127 at ToSic.SexyContent.AppAndDataHelpers..ctor(SxcInstance sexy) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\AppAndDataHelpers.cs:line 46 at ToSic.SexyContent.Engines.RazorEngine.InitHelpers(SexyContentWebPage webPage) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 95 at ToSic.SexyContent.Engines.RazorEngine.InitWebpage() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 115 at ToSic.SexyContent.Engines.RazorEngine.Init() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 27 at ToSic.SexyContent.Engines.EngineBase.Init(Template template, App app, ModuleInfo hostingModule, IDataSource dataSource, InstancePurposes instancePurposes, SxcInstance sexy) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Engines\EngineBase.cs:line 57 at ToSic.SexyContent.SxcInstance.GetRenderingEngine(InstancePurposes renderingPurpose) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\SxcInstance.cs:line 242 at ToSic.SexyContent.SxcInstance.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\SxcInstance.cs:line 200`

The error is displayed only if i chose "Tag Cloud - Automatic"
if I chose some simple content or different view of Blog everything work OK

I also have this problem in some my test modules, but can't find why this error is displayed for some views but for some (simple modules) work OK.

dnn 8.00.02
2sxc 8.04.07

**Comment by iJungleboy** [comment]
This is a guess, but most likely you are adding an 

1. inner content-block 
2. which uses a query / pipeline
3. ...which expects a module as a wrapper

but I'm not sure. Could you spend more time drilling down what happens? like creating another view which uses a different data source to corner the issue?

**Comment by iJungleboy** [comment]
Anthing new on this? I'm assuming you already fixed it in the meantime, so I'll close this for now.
