### ISSUE TITLE
Title of referenced entities are not delivered in the correct language with JSON

### ISSUE THREAD

**Issue by tobias2sic** [2sic/2sxc#859]
When I request entities referencing another entity, JSON does NOT return the 'Title' property of the referenced entity in the correct language. The title is in the default language always. I detected this by requesting data with JSON.

Code to change (I guess):
ToSic.Eav.WebApi/Serializers/Serializer.cs Line 131

**Comment by tobias2sic** [comment]
Need that for Manor.

**Comment by raphael-m** [comment]
Duplicate of #895

**Comment by iJungleboy** [comment]
Note that there are actually two bugs which both will cause this

1. The serializer.cs which didn't ML the title in some cases as mentioned in #895 
2. a DNN bug which causes all web-api-calls to set the language-cookie to the main language, so following ajax-calls will use the wrong language...
