### ISSUE TITLE
ImageResizer - Let the user use the precise crop by himself.

### ISSUE THREAD

**Issue by dannybrouwer** [2sic/2sxc#863]
Right now using the ImageResizer extension, it's possible to use the precise crop by "&anchor=middleleft (or topleft, topcenter, topright, middle)".

Now one of my costumers wants to do it by himself, so without code. I just heard from Reto that it's not possible yet. Would be really usefull. 

Thanks in advance.

**Comment by iJungleboy** [comment]
I believe this is a basic feature of image resizer and also works inside 2sxc. I just tried it
http://2sxc.org/Portals/0/Content/Home/Slider/CreateDNN.jpg?w=200&h=500&mode=crop&anchor=topright

So there's nothing in your way - go ahead :)
