### ISSUE TITLE
Install of 2sxc content module crashes DNN sites

### ISSUE THREAD

**Issue by PostalMike** [2sic/2sxc#865]
This has occurred on 2 sites.  I trusted the module, installed it on live and it made an entry into <httpmodules> tag that didn't yet exist in /bin.  Didn't want to try to remove the entry and restart the install, per the instructions.

Instructions say to just re-run the install but the error message makes me worry.

If someone wants to do a look-in via Join Me or Go To Meeting I'm game but my hours are 5 or so behind you Swiss folks.  When I'm off work and home at the earliest possible time it's already 20:00 + for you folks.

I emailed 2sxc support with the issue as well.

**Comment by iJungleboy** [comment]
What version of dnn / 2sxc?

Most common issue is when people already had a different version of image resizer - because then some DLLs conflict. 2sxc doesn't really care which one you use (you can keep the old one if you want to). 

Did you have image resizer in before?

**Comment by PostalMike** [comment]
DNN is 07.02.01 (367).  Version of 2sxc is 8.4.7.

 

We did not have image resizer before.

 

This is our first install ever for 2sxc.

 

Michael Durthaler

 

A veteran is someone who, at some point in his life wrote a blank check made Payable to “The United States of America” for an amount ‘up to and including my life.’  That is Honor, and there are way too many people who no longer understand it.

**Comment by iJungleboy** [comment]
Please be more specific about how your site crashed. What were the symptoms etc.

**Comment by PostalMike** [comment]
When I installed the module, there was an SQL error that had as part of it to run the install again.  Trying to navigate back to the Host | Extensions page to reinstall the module wouldn’t work however.  I can do this again but it will mean crashing the site to get you a snapshot of what is happening.

 

Michael Durthaler

 

A veteran is someone who, at some point in his life wrote a blank check made Payable to “The United States of America” for an amount ‘up to and including my life.’  That is Honor, and there are way too many people who no longer understand it.

**Comment by iJungleboy** [comment]
@PostalMike There are two things about this

1. if an install failed - for whatever reason - then there are still some tables etc. in the system which must be removed manually. this is a weakness in DNN installation as a failed install cannot clean up after itself. so if you try a re-install, check first that the tosic... tables are all gone
2. based on this level of information it's impossible to help you further. If you would like further assistance, it's best to create ac opy of your system on your pc / dev-machine, and run the install there again (after cleaning up the sql tables in case there are any left)

**Comment by andyduo** [comment]
I've just had this happen to me DNN 8.0.3. This is from an upgrade of the module to 8.4.8 rather than a fresh install. Could not load imageresizer error crashed the site... If it happens again I'll post it here.

**Comment by andyduo** [comment]
Had the error again and I removed ImageResizer.Plugins.DiskCache.dll from the bin folder and the site came back up.
