### ISSUE TITLE
Entity Picker is sorted as string even if the title field is a number

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#867]
i have a content type with 1 field to select a value from another entity (entity field).
The other entity has a number-field as title (see screenshot).

**image 1:** the title from the other entity is a number:
![entity-number-title](https://cloud.githubusercontent.com/assets/12188254/16038819/1e49c4f6-3227-11e6-9c7d-3ce62ae35a75.jpg)

---

Nonetheless in the entity picker the title gets sorted as string instead of a number: 
1, 10, 11, ..., 2, 20, 21, ..., 3, 4
instead of 1, 2, ..., 10, 11, ...

**image 2:** string order instead of numeric order
![string-order instead of numeric](https://cloud.githubusercontent.com/assets/12188254/16038812/188639dc-3227-11e6-9134-048ed79f442c.jpg)

---

It would be nice if the entity picker would sort by number if the entity title is a numeric field.

**Comment by iJungleboy** [comment]
This is a fairly specific wish - to do it architecturally correct would mean quit a lot of changes. 2-4h minimum; low priority.

**Comment by iJungleboy** [comment]
I don't expect this ever to be implemented, as it's very specific and mainly "impractical" but probably never a show stopper. I'll put it as "closed but not implemented" - if a sponsor ever appears, we can re-activate it.
