### ISSUE TITLE
When I try to chang a list record with imported record with empty field - error

### ISSUE THREAD

**Issue by Frankwalraven** [2sic/2sxc#868]
When i want to swop a list record and there is a list record (imported) without data I get a 400 error.

This was befor also the case with swopping content records but this was solved.

**Comment by iJungleboy** [comment]
I'm having trouble following what is wrong; not sure what you mean with a list-record. could you be more specific, maybe 2-3 screenshots?

**Comment by Frankwalraven** [comment]
This is the same issue as  #439 but now when you try to swop an list item. When there is one title field in the database empty the error ocurs
![error](https://cloud.githubusercontent.com/assets/13934402/16266109/7d2fddc2-3883-11e6-9256-f8c14f3767bf.jpg)
Its imported data from another module. We filled the titels in the background and the error occurs anhymore. When you make the titel filed empty again there is not error anhymore. Only after importing.

**Comment by iJungleboy** [comment]
Ok, thanks for that info.
