### ISSUE TITLE
Upgrade fails with error

### ISSUE THREAD

**Issue by andyduo** [2sic/2sxc#869]
I have a site which was running DNN 7.4.2. I upgraded the site to 8.0.3 just fine. I then went to upgrade the 2sxc module from an older v5 to the latest 8.4.8 but the upgrade crashed the site with an ImageResizer error so I rolled the site back to the 7.4.2 version and started again. I then tried upgarding to 2sxc 6.1.5 which worked fine but I cannot get the upgrade to work any further. Now when I try to upgrade the 2sxc 2sxc 6.1.5 version I constantly get the following error during the install:

`Error loading files from temporary folder - see below.
StartJob	Starting Installation
Info	Starting Installation - 2SexyContent
Info	Starting Installation - Script
Info	Begin Sql execution
Info	Creating backup of previous version - SqlDataProvider\06.02.01.SqlDataProvider
Info	Created - SqlDataProvider\06.02.01.SqlDataProvider
Info	Executing 06.02.01.SqlDataProvider
Info	Start Sql execution: 06.02.01.SqlDataProvider file
Failure	SQL Execution resulted in following Exceptions: System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.AutoLogAllChangesToTimeline_Apps'. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script) ClientConnectionId:e60c579a-4133-486c-bb98-f6fc787e6150 Error Number:208,State:6,Class:16 -- make sure sql rolls back automatically in case of error. SET XACT_ABORT ON BEGIN TRANSACTION SexyContentUpdate; -- Create Table ContextInfo for SQL Azure Compatibility EXEC('CREATE TABLE [dbo].[ToSIC_EAV_ContextInfo] ( [ContextInfo] varbinary(128) not null, [ChangeID] nvarchar(128) not null, [UpdatedAt] datetime NOT NULL, CONSTRAINT [PK_ToSIC_EAV_ContextInfo] PRIMARY KEY CLUSTERED ([ContextInfo] ASC) )') -- Update ToSIC_EAV_ChangeLogSet for SQL Azure Compatibility EXEC('ALTER PROCEDURE [dbo].ToSIC_EAV_ChangeLogSet @ChangeID int AS SET NOCOUNT ON -- Remove all context items older than an 5 minutes ago DELETE FROM [dbo].[ToSIC_EAV_ContextInfo] WHERE [UpdatedAt] < DATEADD(mi, -5, GETUTCDATE()) IF SERVERPROPERTY(''edition'') <> ''SQL Azure'' BEGIN DECLARE @b varbinary(128) SET @b = CONVERT(varbinary(128),newid()) EXEC sp_executesql @statement=N''SET CONTEXT_INFO @b'',@params=N''@b varbinary(128)'',@b=@b print @b END DECLARE @ContextInfo varbinary(128) SELECT @ContextInfo = CONTEXT_INFO() IF EXISTS (SELECT * FROM [dbo].[ToSIC_EAV_ContextInfo] WHERE [ContextInfo] = @ContextInfo) UPDATE [dbo].[ToSIC_EAV_ContextInfo] SET [ChangeID] = @ChangeID, [UpdatedAt] = GETUTCDATE() WHERE ContextInfo = @ContextInfo ELSE INSERT INTO [dbo].[ToSIC_EAV_ContextInfo] ([ContextInfo], [ChangeID], [UpdatedAt]) VALUES (@ContextInfo, @ChangeID, GETUTCDATE());') -- Add ToSIC_EAV_ChangeLogGet EXEC('CREATE PROCEDURE [dbo].[ToSIC_EAV_ChangeLogGet] AS SET NOCOUNT ON DECLARE @ContextInfo varbinary(128) SELECT @ContextInfo = CONTEXT_INFO() DECLARE @ChangeID int SET @ChangeID = 0 SELECT @ChangeID = [ChangeID] FROM [dbo].[ToSIC_EAV_ContextInfo] WHERE [ContextInfo] = @ContextInfo RETURN @ChangeID') /****** Object: Trigger [dbo].[AutoLogAllChangesToTimeline_Apps] Script Date: 28.08.2014 09:04:35 ******/ EXEC('SET ANSI_NULLS ON') EXEC('SET QUOTED_IDENTIFIER ON') EXEC('ALTER TRIGGER [dbo].[AutoLogAllChangesToTimeline_Apps] ON [dbo].[ToSIC_EAV_Apps] AFTER INSERT,DELETE,UPDATE AS BEGIN -- SET NOCOUNT ON added to prevent extra result sets from -- interfering with SELECT statements. SET NOCOUNT ON; -- Insert statements for trigger here Declare @table nvarchar(250) ,@rowID int ,@rowGuid uniqueidentifier ,@rowTextKey nvarchar(250) ,@operation nchar(1) ,@sysCreated datetime ,@sysLogID int ,@newData xml EXEC @sysLogId = [dbo].[ToSIC_EAV_ChangeLogGet] IF @sysLogId = 0 BEGIN RAISERROR (''ChangeLogID is not set'', 0, 1) RETURN END -- Automatically get the table name where this trigger is attached Select @table = OBJECT_NAME(parent_id) FROM sys.triggers WHERE object_id=@@PROCID Select @sysCreated = GetDate() -- Find out if insert, update or delete -- Note: here you would adapt things to our table if you re-use this trigger -- 1. Ensure you use a valid field in both IF EXISTS queries (the SysCreated might not exist everywhere) -- 2. Ensure you get the right keys (this example uses @rowID, but you could also use @rowGuid, @rowTextKey) -- 3. if you have a logid, also set the @sysLogId -- Note: don''t know how to get the LogID in there when deleting... IF EXISTS (SELECT * FROM Inserted) BEGIN Select @rowID = AppID From inserted Select @newData = (Select * From Inserted For XML Auto) Set @operation = ''I'' IF EXISTS (SELECT * FROM deleted) Begin SET @operation = ''U'' End END ELSE BEGIN Select @rowID = AppID From deleted SET @operation = ''D'' END -- Add the stuff... Exec dbo.ToSIC_EAV_LogToTimeline @table, @rowID, @rowGuid, @rowTextKey, @operation, @sysCreated, @sysLogId, @newData END') /****** Object: Trigger [dbo].[AutoLogAllChangesToTimeline_AssignmentObjectTypes] Script Date: 28.08.2014 09:08:32 ******/ EXEC('SET ANSI_NULLS ON') EXEC('SET QUOTED_IDENTIFIER ON') EXEC('-- ============================================= -- Author:	Daniel Mettler -- Create date: 2013-01-28 -- Description:	Automatically log all changes to the DataTimeline -- ============================================= ALTER TRIGGER [dbo].[AutoLogAllChangesToTimeline_AssignmentObjectTypes] ON [dbo].[ToSIC_EAV_AssignmentObjectTypes] AFTER INSERT,DELETE,UPDATE AS BEGIN -- SET NOCOUNT ON added to prevent extra result sets from -- interfering with SELECT statements. SET NOCOUNT ON; -- Insert statements for trigger here Declare @table nvarchar(250) ,@rowID int ,@rowGuid uniqueidentifier ,@rowTextKey nvarchar(250) ,@operation nchar(1) ,@sysCreated datetime ,@sysLogID int ,@newData xml EXEC @sysLogId = [dbo].[ToSIC_EAV_ChangeLogGet] IF @sysLogId = 0 BEGIN RAISERROR (''ChangeLogID is not set'', 0, 1) RETURN END -- Automatically get the table name where this trigger is attached Select @table = OBJECT_NAME(parent_id) FROM sys.triggers WHERE object_id=@@PROCID Select @sysCreated = GetDate() -- Find out if insert, update or delete -- Note: here you would adapt things to our table if you re-use this trigger -- 1. Ensure you use a valid field in both IF EXISTS queries (the SysCreated might not exist everywhere) -- 2. Ensure you get the right keys (this example uses @rowID, but you could also use @rowGuid, @rowTextKey) -- 3. if you have a logid, also set the @sysLogId -- Note: don''t know how to get the LogID in there when deleting... IF EXISTS (SELECT * FROM Inserted) BEGIN Select @rowID = AssignmentObjectTypeID From inserted Select @newData = (Select * From Inserted For XML Auto) Set @operation = ''I'' IF EXISTS (SELECT * FROM deleted) Begin SET @operation = ''U'' End END ELSE BEGIN Select @rowID = AssignmentObjectTypeID From deleted SET @operation = ''D'' END -- Add the stuff... Exec dbo.ToSIC_EAV_LogToTimeline @table, @rowID, @rowGuid, @rowTextKey, @operation, @sysCreated, @sysLogId, @newData END') /****** Object: Trigger [dbo].[AutoLogAllChangesToTimeline_AttributeGroups] Script Date: 28.08.2014 09:09:11 ******/ EXEC('SET ANSI_NULLS ON') EXEC('SET QUOTED_IDENTIFIER ON') EXEC('-- ============================================= -- Author:	Daniel Mettler -- Create date: 2013-01-28 -- Description:	Automatically log all changes to the DataTimeline -- ============================================= ALTER TRIGGER [dbo].[AutoLogAllChangesToTimeline_AttributeGroups] ON [dbo].[ToSIC_EAV_AttributeGroups] AFTER INSERT,DELETE,UPDATE AS BEGIN -- SET NOCOUNT ON added to prevent extra result sets from -- interfering with SELECT statements. SET NOCOUNT ON; -- Insert statements for trigger here Declare @table nvarchar(250) ,@rowID int ,@rowGuid uniqueidentifier ,@rowTextKey nvarchar(250) ,@operation nchar(1) ,@sysCreated datetime ,@sysLogID int ,@newData xml EXEC @sysLogId = [dbo].[ToSIC_EAV_ChangeLogGet] IF @sysLogId = 0 BEGIN RAISERROR (''ChangeLogID is not set'', 0, 1) RETURN END -- Automatically get the table name where this trigger is attached Select @table = OBJECT_NAME(parent_id) FROM sys.triggers WHERE object_id=@@PROCID Select @sysCreated = GetDate() -- Find out if insert, update or delete -- Note: here you would adapt things to our table if you re-use this trigger -- 1. Ensure you use a valid field in both IF EXISTS queries (the SysCreated might not exist everywhere) -- 2. Ensure you get the right keys (this example uses @rowID, but you could also use @rowGuid, @rowTextKey) -- 3. if you have a logid, also set the @sysLogId -- Note: don''t know how to get the LogID in there when deleting... IF EXISTS (SELECT * FROM Inserted) BEGIN Select @rowID = AttributeGroupID From inserted Select @newData = (Select * From Inserted For XML Auto) Set @operation = ''I'' IF EXISTS (SELECT * FROM deleted) Begin SET @operation = ''U'' End END ELSE BEGIN Select @rowID = AttributeGroupID From deleted SET @operation = ''D'' END -- Add the stuff... Exec dbo.ToSIC_EAV_LogToTimeline @table, @rowID, @rowGuid, @rowTextKey, @operation, @sysCreated, @sysLogId, @newData END') /****** Object: Trigger [dbo].[AutoLogAllChangesToTimeline_Attributes] Script Date: 28.08.2014 09:10:17 ******/ EXEC('SET ANSI_NULLS ON') EXEC('SET QUOTED_IDENTIFIER ON') EXEC('-- ============================================= -- Author:	Daniel Mettler -- Create date: 2013-01-28 -- Description:	Automatically log all changes to the DataTimeline -- ============================================= ALTER TRIGGER [dbo].[AutoLogAllChangesToTimeline_Attributes] ON [dbo].[ToSIC_EAV_Attributes] AFTER INSERT,DELETE,UPDATE AS BEGIN -- SET NOCOUNT ON added to prevent extra result sets from -- interfering with SELECT statements. SET NOCOUNT ON; -- Insert statements for trigger here Declare @table nvarchar(250) ,@rowID int ,@rowGuid uniqueidentifier ,@rowTextKey nvarchar(250) ,@operation nchar(1) ,@sysCreated datetime ,@sysLogID int ,@newData xml EXEC @sysLogId = [dbo].[ToSIC_EAV_ChangeLogGet] IF @sysLogId = 0 BEGIN RAISERROR (''ChangeLogID is not set'', 0, 1) RETURN END -- Automatically get the table name where this trigger is attached Select @table = OBJECT_NAME(parent_id) FROM sys.triggers WHERE object_id=@@PROCID Select @sysCreated = GetDate() -- Find out if insert, update or delete -- Note: here you would adapt things to our table if you re-use this trigger -- 1. Ensure you use a valid field in both IF EXISTS queries (the SysCreated might not exist everywhere) -- 2. Ensure you get the right keys (this example uses @rowID, but you could also use @rowGuid, @rowTextKey) -- 3. if you have a logid, also set the @sysLogId -- Note: don''t know how to get the LogID in there when deleting... IF EXISTS (SELECT * FROM Inserted) BEGIN Select @rowID = AttributeID From inserted Select @newData = (Select * From Inserted For XML Auto) Set @operation = ''I'' IF EXISTS (SELECT * FROM deleted) Begin SET @operation = ''U'' End END ELSE BEGIN Select @rowID = AttributeID From deleted SET @operation = ''D'' END -- Add the stuff... Exec dbo.ToSIC_EAV_LogToTimeline @table, @rowID, @rowGuid, @rowTextKey, @operation, @sysCreated, @sysLogId, @newData END') /****** Object: Trigger [dbo].[AutoLogAllChangesToTimeline_AttributeSets] Script Date: 28.08.2014 09:11:17 ******/ EXEC('SET ANSI_NULLS ON') EXEC('SET QUOTED_IDENTIFIER ON') EXEC('-- ============================================= -- Author:	Daniel Mettler -- Create date: 2013-01-28 -- Description:	Automatically log all changes to the DataTimeline -- ============================================= ALTER TRIGGER [dbo].[AutoLogAllChangesToTimeline_AttributeSets] ON [dbo].[ToSIC_EAV_AttributeSets] AFTER INSERT,DELETE,UPDATE AS BEGIN -- SET NOCOUNT ON added to prevent extra result sets from -- interfering with SELECT statements. SET NOCOUNT ON; -- Insert statements for trigger here Declare @table nvarchar(250) ,@rowID int ,@rowGuid uniqueidentifier ,@rowTextKey nvarchar(250) ,@operation nchar(1) ,@sysCreated datetime ,@sysLogID int ,@newData xml EXEC @sysLogId = [dbo].[ToSIC_EAV_ChangeLogGet] IF @sysLogId = 0 BEGIN RAISERROR (''ChangeLogID is not set'', 0, 1) RETURN END -- Automatically get the table name where this trigger is attached Select @table = OBJECT_NAME(parent_id) FROM sys.triggers WHERE object_id=@@PROCID Select @sysCreated = GetDate() -- Find out if insert, update or delete -- Note: here you would adapt things to our table if you re-use this trigger -- 1. Ensure you use a valid field in both IF EXISTS queries (the SysCreated might not exist everywhere) -- 2. Ensure you get the right keys (this example uses @rowID, but you could also use @rowGuid, @rowTextKey) -- 3. if you have a logid, also set the @sysLogId -- Note: don''t know how to get the LogID in there when deleting... IF EXISTS (SELECT * FROM Inserted) BEGIN Select @rowID = AttributeSetID From inserted Select @newData = (Select * From Inserted For XML Auto) Set @operation = ''I'' IF EXISTS (SELECT * FROM deleted) Begin SET @operation = ''U'' End END ELSE BEGIN Select @rowID = AttributeSetID From deleted SET @operation = ''D'' END -- Add the stuff... Exec dbo.ToSIC_EAV_LogToTimeline @table, @rowID, @rowGuid, @rowTextKey, @operation, @sysCreated, @sysLogId, @newData END') /****** Object: Trigger [dbo].[AutoLogAllChangesToTimeline_AttributesInSets] Script Date: 28.08.2014 09:11:48 ******/ EXEC('SET ANSI_NULLS ON') EXEC('SET QUOTED_IDENTIFIER ON') EXEC('-- ============================================= -- Author:	Daniel Mettler -- Create date: 2013-01-28 -- Description:	Automatically log all changes to the DataTimeline -- ============================================= ALTER TRIGGER [dbo].[AutoLogAllChangesToTimeline_AttributesInSets] ON [dbo].[ToSIC_EAV_AttributesInSets] AFTER INSERT,DELETE,UPDATE AS BEGIN -- SET NOCOUNT ON added to prevent extra result sets from -- interfering with SELECT statements. SET NOCOUNT ON; -- Insert statements for trigger here Declare @table nvarchar(250) ,@rowID int ,@rowGuid uniqueidentifier ,@rowTextKey nvarchar(250) ,@operation nchar(1) ,@sysCreated datetime ,@sysLogID int ,@newData xml EXEC @sysLogId = [dbo].[ToSIC_EAV_ChangeLogGet] IF @sysLogId = 0 BEGIN RAISERROR (''ChangeLogID is not set'', 0, 1) RETURN END -- Automatically get the table name where this trigger is attached Select @table = OBJECT_NAME(parent_id) FROM sys.triggers WHERE object_id=@@PROCID Select @sysCreated = GetDate() -- Find out if insert, update or delete -- Note: here you would adapt things to our table if you re-use this trigger -- 1. Ensure you use a valid field in both IF EXISTS queries (the SysCreated might not exist everywhere) -- 2. Ensure you get the right keys (this example uses @rowID, but you could also use @rowGuid, @rowTextKey) -- 3. if you have a logid, also set the @sysLogId -- Note: don''t know how to get the LogID in there when deleting... IF EXISTS (SELECT * FROM Inserted) BEGIN Select @rowID = AttributeSetID From inserted Select @newData = (Select * From Inserted For XML Auto) Set @operation = ''I'' IF EXISTS (SELECT * FROM deleted) Begin SET @operation = ''U'' End END ELSE BEGIN Select @rowID = AttributeSetID From deleted SET @operation = ''D'' END -- Add the stuff... Exec dbo.ToSIC_EAV_LogToTimeline @table, @rowID, @rowGuid, @rowTextKey, @operation, @sysCreated, @sysLogId, @newData END') /****** Object: Trigger [dbo].[AutoLogAllChangesToTimeline_Dimensions] Script Date: 28.08.2014 09:12:22 ******/ EXEC('SET ANSI_NULLS ON') EXEC('SET QUOTED_IDENTIFIER ON') EXEC('-- ============================================= -- Author:	Daniel Mettler -- Create date: 2013-01-28 -- Description:	Automatically log all changes to the DataTimeline -- ============================================= ALTER TRIGGER [dbo].[AutoLogAllChangesToTimeline_Dimensions] ON [dbo].[ToSIC_EAV_Dimensions] AFTER INSERT,DELETE,UPDATE AS BEGIN -- SET NOCOUNT ON added to prevent extra result sets from -- interfering with SELECT statements. SET NOCOUNT ON; -- Insert statements for trigger here Declare @table nvarchar(250) ,@rowID int ,@rowGuid uniqueidentifier ,@rowTextKey nvarchar(250) ,@operation nchar(1) ,@sysCreated datetime ,@sysLogID int ,@newData xml EXEC @sysLogId = [dbo].[ToSIC_EAV_ChangeLogGet] IF @sysLogId = 0 BEGIN RAISERROR (''ChangeLogID is not set'', 0, 1) RETURN END -- Automatically get the table name where this trigger is attached Select @table = OBJECT_NAME(parent_id) FROM sys.triggers WHERE object_id=@@PROCID Select @sysCreated = GetDate() -- Find out if insert, update or delete -- Note: here you would adapt things to our table if you re-use this trigger -- 1. Ensure you use a valid field in both IF EXISTS queries (the SysCreated might not exist everywhere) -- 2. Ensure you get the right keys (this example uses @rowID, but you could also use @rowGuid, @rowTextKey) -- 3. if you have a logid, also set the @sysLogId -- Note: don''t know how to get the LogID in there when deleting... IF EXISTS (SELECT * FROM Inserted) BEGIN Select @rowID = DimensionID From inserted Select @newData = (Select * From Inserted For XML Auto) Set @operation = ''I'' IF EXISTS (SELECT * FROM deleted) Begin SET @operation = ''U'' End END ELSE BEGIN Select @rowID = DimensionID From deleted SET @operation = ''D'' END -- Add the stuff... Exec dbo.ToSIC_EAV_LogToTimeline @table, @rowID, @rowGuid, @rowTextKey, @operation, @sysCreated, @sysLogId, @newData END') /****** Object: Trigger [dbo].[AutoLogAllChangesToTimeline_Entities] Script Date: 28.08.2014 09:13:02 ******/ EXEC('SET ANSI_NULLS ON') EXEC('SET QUOTED_IDENTIFIER ON') EXEC('-- ============================================= -- Author:	Daniel Mettler -- Create date: 2013-01-28 -- Description:	Automatically log all changes to the DataTimeline -- ============================================= ALTER TRIGGER [dbo].[AutoLogAllChangesToTimeline_Entities] ON [dbo].[ToSIC_EAV_Entities] AFTER INSERT,DELETE,UPDATE AS BEGIN -- SET NOCOUNT ON added to prevent extra result sets from -- interfering with SELECT statements. SET NOCOUNT ON; -- Insert statements for trigger here Declare @table nvarchar(250) ,@rowID int ,@rowGuid uniqueidentifier ,@rowTextKey nvarchar(250) ,@operation nchar(1) ,@sysCreated datetime ,@sysLogID int ,@newData xml EXEC @sysLogId = [dbo].[ToSIC_EAV_ChangeLogGet] IF @sysLogId = 0 BEGIN RAISERROR (''ChangeLogID is not set'', 0, 1) RETURN END -- Automatically get the table name where this trigger is attached Select @table = OBJECT_NAME(parent_id) FROM sys.triggers WHERE object_id=@@PROCID Select @sysCreated = GetDate() -- Find out if insert, update or delete -- Note: here you would adapt things to our table if you re-use this trigger -- 1. Ensure you use a valid field in both IF EXISTS queries (the SysCreated might not exist everywhere) -- 2. Ensure you get the right keys (this example uses @rowID, but you could also use @rowGuid, @rowTextKey) -- 3. if you have a logid, also set the @sysLogId -- Note: don''t know how to get the LogID in there when deleting... IF EXISTS (SELECT * FROM Inserted) BEGIN Select @rowID = EntityID From inserted Select @newData = (Select * From Inserted For XML Auto) Set @operation = ''I'' IF EXISTS (SELECT * FROM deleted) Begin SET @operation = ''U'' End END ELSE BEGIN Select @rowID = EntityID From deleted SET @operation = ''D'' END -- Add the stuff... Exec dbo.ToSIC_EAV_LogToTimeline @table, @rowID, @rowGuid, @rowTextKey, @operation, @sysCreated, @sysLogId, @newData END') /****** Object: Trigger [dbo].[AutoLogAllChangesToTimeline_EntityRelationships] Script Date: 28.08.2014 09:13:24 ******/ EXEC('SET ANSI_NULLS ON') EXEC('SET QUOTED_IDENTIFIER ON') EXEC('-- ============================================= -- Author:	Daniel Mettler -- Create date: 2013-01-28 -- Description:	Automatically log all changes to the DataTimeline -- ============================================= ALTER TRIGGER [dbo].[AutoLogAllChangesToTimeline_EntityRelationships] ON [dbo].[ToSIC_EAV_EntityRelationships] AFTER INSERT,DELETE,UPDATE AS BEGIN -- SET NOCOUNT ON added to prevent extra result sets from -- interfering with SELECT statements. SET NOCOUNT ON; -- Insert statements for trigger here Declare @table nvarchar(250) ,@rowID int ,@rowGuid uniqueidentifier ,@rowTextKey nvarchar(250) ,@operation nchar(1) ,@sysCreated datetime ,@sysLogID int ,@newData xml EXEC @sysLogId = [dbo].[ToSIC_EAV_ChangeLogGet] IF @sysLogId = 0 BEGIN RAISERROR (''ChangeLogID is not set'', 0, 1) RETURN END -- Automatically get the table name where this trigger is attached Select @table = OBJECT_NAME(parent_id) FROM sys.triggers WHERE object_id=@@PROCID Select @sysCreated = GetDate() -- Find out if insert, update or delete -- Note: here you would adapt things to our table if you re-use this trigger -- 1. Ensure you use a valid field in both IF EXISTS queries (the SysCreated might not exist everywhere) -- 2. Ensure you get the right keys (this example uses @rowID, but you could also use @rowGuid, @rowTextKey) -- 3. if you have a logid, also set the @sysLogId -- Note: don''t know how to get the LogID in there when deleting... IF EXISTS (SELECT * FROM Inserted) BEGIN Select @rowID = ParentEntityID From inserted Select @newData = (Select * From Inserted For XML Auto) Set @operation = ''I'' IF EXISTS (SELECT * FROM deleted) Begin SET @operation = ''U'' End END ELSE BEGIN Select @rowID = ParentEntityID From deleted SET @operation = ''D'' END -- Add the stuff... Exec dbo.ToSIC_EAV_LogToTimeline @table, @rowID, @rowGuid, @rowTextKey, @operation, @sysCreated, @sysLogId, @newData END') /****** Object: Trigger [dbo].[AutoLogAllChangesToTimeline_Values] Script Date: 28.08.2014 09:13:52 ******/ EXEC('SET ANSI_NULLS ON') EXEC('SET QUOTED_IDENTIFIER ON') EXEC('-- ============================================= -- Author:	Daniel Mettler -- Create date: 2013-01-28 -- Description:	Automatically log all changes to the DataTimeline -- ============================================= ALTER TRIGGER [dbo].[AutoLogAllChangesToTimeline_Values] ON [dbo].[ToSIC_EAV_Values] AFTER INSERT,DELETE,UPDATE AS BEGIN -- SET NOCOUNT ON added to prevent extra result sets from -- interfering with SELECT statements. SET NOCOUNT ON; -- Insert statements for trigger here Declare @table nvarchar(250) ,@rowID int ,@rowGuid uniqueidentifier ,@rowTextKey nvarchar(250) ,@operation nchar(1) ,@sysCreated datetime ,@sysLogID int ,@newData xml EXEC @sysLogId = [dbo].[ToSIC_EAV_ChangeLogGet] IF @sysLogId = 0 BEGIN RAISERROR (''ChangeLogID is not set'', 0, 1) RETURN END -- Automatically get the table name where this trigger is attached Select @table = OBJECT_NAME(parent_id) FROM sys.triggers WHERE object_id=@@PROCID Select @sysCreated = GetDate() -- Find out if insert, update or delete -- Note: here you would adapt things to our table if you re-use this trigger -- 1. Ensure you use a valid field in both IF EXISTS queries (the SysCreated might not exist everywhere) -- 2. Ensure you get the right keys (this example uses @rowID, but you could also use @rowGuid, @rowTextKey) -- 3. if you have a logid, also set the @sysLogId -- Note: don''t know how to get the LogID in there when deleting... IF EXISTS (SELECT * FROM Inserted) BEGIN Select @rowID = ValueID From inserted Select @newData = (Select * From Inserted For XML Auto) Set @operation = ''I'' IF EXISTS (SELECT * FROM deleted) Begin SET @operation = ''U'' End END ELSE BEGIN Select @rowID = ValueID From deleted SET @operation = ''D'' END -- Add the stuff... Exec dbo.ToSIC_EAV_LogToTimeline @table, @rowID, @rowGuid, @rowTextKey, @operation, @sysCreated, @sysLogId, @newData END') /****** Object: Trigger [dbo].[AutoLogAllChangesToTimeline_ValuesDimensions] Script Date: 28.08.2014 09:14:12 ******/ EXEC('SET ANSI_NULLS ON') EXEC('SET QUOTED_IDENTIFIER ON') EXEC('-- ============================================= -- Author:	Daniel Mettler -- Create date: 2013-01-28 -- Description:	Automatically log all changes to the DataTimeline -- ============================================= ALTER TRIGGER [dbo].[AutoLogAllChangesToTimeline_ValuesDimensions] ON [dbo].[ToSIC_EAV_ValuesDimensions] AFTER INSERT,DELETE,UPDATE AS BEGIN -- SET NOCOUNT ON added to prevent extra result sets from -- interfering with SELECT statements. SET NOCOUNT ON; -- Insert statements for trigger here Declare @table nvarchar(250) ,@rowID int ,@rowGuid uniqueidentifier ,@rowTextKey nvarchar(250) ,@operation nchar(1) ,@sysCreated datetime ,@sysLogID int ,@newData xml EXEC @sysLogId = [dbo].[ToSIC_EAV_ChangeLogGet] IF @sysLogId = 0 BEGIN RAISERROR (''ChangeLogID is not set'', 0, 1) RETURN END -- Automatically get the table name where this trigger is attached Select @table = OBJECT_NAME(parent_id) FROM sys.triggers WHERE object_id=@@PROCID Select @sysCreated = GetDate() -- Find out if insert, update or delete -- Note: here you would adapt things to our table if you re-use this trigger -- 1. Ensure you use a valid field in both IF EXISTS queries (the SysCreated might not exist everywhere) -- 2. Ensure you get the right keys (this example uses @rowID, but you could also use @rowGuid, @rowTextKey) -- 3. if you have a logid, also set the @sysLogId -- Note: don''t know how to get the LogID in there when deleting... IF EXISTS (SELECT * FROM Inserted) BEGIN Select @rowID = ValueID From inserted Select @newData = (Select * From Inserted For XML Auto) Set @operation = ''I'' IF EXISTS (SELECT * FROM deleted) Begin SET @operation = ''U'' End END ELSE BEGIN Select @rowID = ValueID From deleted SET @operation = ''D'' END -- Add the stuff... Exec dbo.ToSIC_EAV_LogToTimeline @table, @rowID, @rowGuid, @rowTextKey, @operation, @sysCreated, @sysLogId, @newData END') /****** Object: Trigger [dbo].[AutoLogAllChangesToTimeline_Zones] Script Date: 28.08.2014 09:14:33 ******/ EXEC('SET ANSI_NULLS ON') EXEC('SET QUOTED_IDENTIFIER ON') EXEC('ALTER TRIGGER [dbo].[AutoLogAllChangesToTimeline_Zones] ON [dbo].[ToSIC_EAV_Zones] AFTER INSERT,DELETE,UPDATE AS BEGIN -- SET NOCOUNT ON added to prevent extra result sets from -- interfering with SELECT statements. SET NOCOUNT ON; -- Insert statements for trigger here Declare @table nvarchar(250) ,@rowID int ,@rowGuid uniqueidentifier ,@rowTextKey nvarchar(250) ,@operation nchar(1) ,@sysCreated datetime ,@sysLogID int ,@newData xml EXEC @sysLogId = [dbo].[ToSIC_EAV_ChangeLogGet] IF @sysLogId = 0 BEGIN RAISERROR (''ChangeLogID is not set'', 0, 1) RETURN END -- Automatically get the table name where this trigger is attached Select @table = OBJECT_NAME(parent_id) FROM sys.triggers WHERE object_id=@@PROCID Select @sysCreated = GetDate() -- Find out if insert, update or delete -- Note: here you would adapt things to our table if you re-use this trigger -- 1. Ensure you use a valid field in both IF EXISTS queries (the SysCreated might not exist everywhere) -- 2. Ensure you get the right keys (this example uses @rowID, but you could also use @rowGuid, @rowTextKey) -- 3. if you have a logid, also set the @sysLogId -- Note: don''t know how to get the LogID in there when deleting... IF EXISTS (SELECT * FROM Inserted) BEGIN Select @rowID = ZoneID From inserted Select @newData = (Select * From Inserted For XML Auto) Set @operation = ''I'' IF EXISTS (SELECT * FROM deleted) Begin SET @operation = ''U'' End END ELSE BEGIN Select @rowID = ZoneID From deleted SET @operation = ''D'' END -- Add the stuff... Exec dbo.ToSIC_EAV_LogToTimeline @table, @rowID, @rowGuid, @rowTextKey, @operation, @sysCreated, @sysLogId, @newData END') -- Fix some Key-Names to match Name-Schema EXEC('EXEC sp_rename ''dbo.PK_Ext_AssignmentObjectTypes'', ''PK_ToSIC_EAV_AssignmentObjectTypes''') EXEC('EXEC sp_rename ''dbo.PK_Attachments'', ''PK_ToSIC_EAV_Attachments''') EXEC('EXEC sp_rename ''dbo.PK_Ext_Keys'', ''PK_ToSIC_EAV_Attributes''') EXEC('EXEC sp_rename ''dbo.PK_Ext_Extensions'', ''PK_ToSIC_EAV_AttributeSets''') EXEC('EXEC sp_rename ''dbo.PK_ToSIC_EAV_Types'', ''PK_ToSIC_EAV_AttributeTypes''') EXEC('EXEC sp_rename ''dbo.PK_Ext_ValueSets'', ''PK_ToSIC_EAV_Entities''') EXEC('EXEC sp_rename ''dbo.PK_Ext_Values'', ''PK_ToSIC_EAV_Values''') -- Commit the transaction COMMIT TRANSACTION SexyContentUpdate; --ROLLBACK TRANSACTION SexyContentUpdate;
Info	End Sql execution: 06.02.01.SqlDataProvider file
Info	Finished Sql execution
Failure	Installation Failed - Script
Info	Installation Failed - 2SexyContent
Info	Starting Installation - 2SexyContent-App
Info	Starting Installation - Module
Info	Module registered successfully - 2sxc-app
Info	Component installed successfully - Module
Info	Starting Installation - File
Info	Creating backup of previous version - icon-app.png
Info	Created - icon-app.png
Info	Component installed successfully - File
Failure	Package Installation aborted
Info	Installation Failed - 2SexyContent-App
Info	Deleted temporary install folder
EndJob	Installation Failed`

I realise the "Error loading files from temporary folder" part would generally point to a permissions issue but I have check this and cannot see any. I can upgrade the DNN install and I can install other modules.

This is a site with 5 portals all using the module on various pages. 

Any thoughts on why this occurs? Not being able to upgrade the module has a major impact on the project.

Also i have upgraded the DNN core to 8.0.3 due to the major security issue with previos 7.x.x versions.

Thanks!

**Comment by iJungleboy** [comment]
Info 1 - someone had a similar issue and I believe it's resolved - #865 

The second aspect sounds like a very specific issue to your installation, related to doing various kinds up up-downgrades. I'm guessing a stored procedure is missing - which you could manually copy from another working installation. But that's just a guess; this is probably something which would better be handled by support - http://2sxc.org/en/Contact

**Comment by iJungleboy** [comment]
Since I haven't heard any more, I'll close this. Feel free to re-open if it's a system problem, or continue the discussion on stackoverflow.com if it's a issue specific to your installation.

**Comment by andyduo** [comment]
Sorry I meant to get back sooner, I ended up doing a fresh install of DNN 8.0.3 and latest 2sxc and copied portals across as all 4 site are being rebuilt at the moment. This all seem to be working fine. If the install of the old sites is bugged better to start fresh.
