### ISSUE TITLE
Improve handling of edit-dialog on apps/views with no content-type

### ISSUE THREAD

**Issue by BeniGemperle** [2sic/2sxc#874]
If I have a view which has no content-type assigned and click on _Edit_, I receive a useless dialog without any information:

![2016-07-04_14-03-18](https://cloud.githubusercontent.com/assets/6669093/16559967/c3b1f19c-41f0-11e6-8988-d199f94e4b92.png)

**Comment by iJungleboy** [comment]
I'll close this for now. Not sexy, but no priority.
