### ISSUE TITLE
Improve initialization of 'add field' dialog. Loading-indicators are shown for 20 seconds.

### ISSUE THREAD

**Issue by BeniGemperle** [2sic/2sxc#875]
When I open the dialog to add new fields, I get lots of loading indicators (_wird geladen..._). They're always shown for 20 seconds but the UI seems to be fully loaded already. I think they should disappear earlier.

![2016-07-04_14-10-52](https://cloud.githubusercontent.com/assets/6669093/16560150/db1d4a6a-41f1-11e6-92fa-87162a339efb.png)

**Comment by iJungleboy** [comment]
I believe it's gone in the latest version, though I don't know why...
will close for now.
