### ISSUE TITLE
Fix Mouse-Hover-Issue in App Configuration Dialog

### ISSUE THREAD

**Issue by BeniGemperle** [2sic/2sxc#879]
When I mouseover on _App Resources_ or _App Package Definition_ the icons move to the right. Maybe a css-clear is missing. It just looks unprofessional.

![2016-07-06_10-07-00](https://cloud.githubusercontent.com/assets/6669093/16611477/cf3dfc50-4361-11e6-900c-e946c9ff9d29.png)

**Comment by iJungleboy** [comment]
Could you quickl see what must be done?

**Comment by BeniGemperle** [comment]
[The class `clearfix` should be applied to the parent container element](http://stackoverflow.com/a/16260576/4049371):

```html
<div class="clearfix">
    <div class="pull-left btn-group-vertical"> ... your buttons ... </div>
    <div> ... your text ...</div>
</div>
```

**Comment by BeniGemperle** [comment]
There's another issue: for some reason buttons sometimes have a `margin-top: -1px` on mouseover. defined in this css selector: `.btn-group-vertical>.btn+.btn`. I thing this negative margin-top doesn't make sense at at all and sould be removed.
