### ISSUE TITLE
List items: "move down" for last item leads to error - should not show up at all

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#882]
On any list, the last item gets the "move down" function, which is useless because it is the last item. 
If you click on it, you get an error. The button should not show up at all.

![last-item-move-down](https://cloud.githubusercontent.com/assets/12188254/16725507/d6869b44-4757-11e6-85e4-ab6541e7c002.jpg)

**Comment by iJungleboy** [comment]
This is fairly difficult to do, needing 2-3 hours to do right and test everything, so unless someone sponsors it, we won't do it. Will close for now.
