### ISSUE TITLE
CSS issues inside Edit Popup on 8.5.0

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#883]
- Firefox: some (?) fonts are missing
- IE 11 / Firefox: some text values are cutted (see screenshot)

![css-issues](https://cloud.githubusercontent.com/assets/12188254/16731137/cd1a0c48-4776-11e6-930f-5ba7262df385.jpg)

**Comment by raphael-m** [comment]
Fixed with https://github.com/2sic/eav-ui/commit/f9c3fcc9a92676e1949d4d4683d606ff06f51325
