### ISSUE TITLE
Failure loading data items when WYSIWYG contained {{{Xxx}}} placehloder

### ISSUE THREAD

**Issue by tobias2sic** [2sic/2sxc#884]
I tried to edit data items having one WYSIWYG field (Project > FormTemplates). One field value contained placeholder like {{{Xxx}}}, what confused AngularJS. So AngularJS did not load the data items. I had to change the field value in the database to fix the issue temporarly.
![2016-07-12_15-08-46](https://cloud.githubusercontent.com/assets/6668437/16768186/8864fa0e-4843-11e6-9b38-3fec208d1165.png)

**Comment by raphael-m** [comment]
Duplicate with #738 and #903
