### ISSUE TITLE
Exporting the wrong app

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#887]
![image](https://cloud.githubusercontent.com/assets/5693190/16872319/6f660fde-4a8c-11e6-98af-f2b977cb5dc1.png)
The export button inside the list **always** export only the app which opened the popup window.

Tested with 2sxc8.4.8 and 2sxc8.5.0

**Comment by SCullman** [comment]
Workaround is simple: open app, go to app tab and export there

**Comment by iJungleboy** [comment]
I tried to quickly fix it, but it's fairly complex because the parameter is using dependency injection, and this is really hard to override in a clean architecture. So for now, I'll just hide the button :( to prevent wrong use / suprises. sorry bout that.
