### ISSUE TITLE
Don't show JavaScript-alert when a xhr-request is canceled (status -1)

### ISSUE THREAD

**Issue by BeniGemperle** [2sic/2sxc#888]
Sometimes I receive an alert with status -1. I guess this is when my Browser cancels a xhr-request because I already navigated away from that page and it won't make sense to keep loading the xhr-request. But that annoying alert forces me to confirm.

**Alert message:**
_Had an error talking to the server (status -1). if you are an advanced user you can learn more about what went wrong - discover how on 2sxc.org/help?tag=debug_

**Comment by reto-f-999** [comment]
:+1: i think this is the same problem a lot of customers reported to me (but I was never able to reproduce it)
