### ISSUE TITLE
Add instructional text to empty ContentType-Picker in the page-dropdown

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#889]
A lot of users do not understand what they should do after they inserted a module. 

They should choose their desired content type, but they do not realise that they should use the dropdown as the next step.

![contentpicker](https://cloud.githubusercontent.com/assets/12188254/16950934/f0db829a-4dc2-11e6-94c0-ecd5209108ed.jpg)

**Suggestion**: add a text like "-- select content type --" // "-- Inhaltstyp wählen --"

**Comment by iJungleboy** [comment]
this was actually solve a while back.
