### ISSUE TITLE
Fix: TinyMCE WYSIWYG Editor reports content changed even if it didn't (Confirmation Dialog only if dirty)

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#890]
If a form is closed without saving, a confirmation dialog appears. 
This drives one of my power users nuts. She asks whether it would be possible to track for changes, and that the dialog only appears if the data is dirty.

**Comment by iJungleboy** [comment]
It actually does a dirty-check, but something isn't perfect with the tiny-mce wysiwyg integration, which reports dirty even if not manually changed. So I'm guessing that this is the real problem. Could you test / verify and then maybe change the issue to fix-dirty-checking on tiny-mce?

**Comment by raphael-m** [comment]
Had a look at it - the angular-ui-tinymce directive always reports a dirty value: https://github.com/angular-ui/ui-tinymce/issues/238. The issue has been closed, but it doesn't seem to work as expected.

**Comment by iJungleboy** [comment]
Let's wait & see what angular-ui says. We'll postpone this for a few days...

**Comment by iJungleboy** [comment]
Posted a new issue https://github.com/angular-ui/ui-tinymce/issues/315

**Comment by christophbuehler** [comment]
'ui-tinymce' has to be updated!
https://github.com/angular-ui/ui-tinymce/issues/315#issuecomment-291504652

I have not succeeded in overwriting this behavior, so we have to wait for an answer.

**Comment by iJungleboy** [comment]
I'm not sure if this is still an issue, so I'll close for now.
