### ISSUE TITLE
issue with Newtonsoft.Json

### ISSUE THREAD

**Issue by sunblognuke** [2sic/2sxc#891]
Hey guys,

I just installed this awesome module and would like to have a try the feature "Visual Queries / Pipelines".

Added one and click to edit the DataSource, it always throws 400 exceptions below:

Message: bad request.
Detail: 'Newtonsoft.Json.Linq.JObject' does not contain a definition for 'DataSource'.

Appreciated any help :)

**Comment by iJungleboy** [comment]
Just a guess - could you check the dll version of newtonsoft on your system compared to the one in the 2sxc installation zip?

**Comment by iJungleboy** [comment]
Nothing was added to this request, so I'll close it now. Please re-open if it's still important.
