### ISSUE TITLE
Toolbar not shown on a new Content module untill page is refreshed

### ISSUE THREAD

**Issue by BeniGemperle** [2sic/2sxc#892]
When you add a 2sxc Content module on a page, select a content type and a template the template-preview just appears as it should, but edit-toolbars are not shown. After I refresh the page the toolbar appear.
2sxc Version 8.5.0 RC

**Comment by mangiove** [comment]
this is happening for me too. Clicking on refresh command in the edit tool bar doesn't work too. Just hitting an F5 help with it, anche then you can see the edit/edit template commands..
