### ISSUE TITLE
Collapse expand not working on first form-title

### ISSUE THREAD

**Issue by BeniGemperle** [2sic/2sxc#896]
If a content-type has a form-title (empty-field) as first field, collapse doesn't work. The region just doesn't collapse, instead an empty div (about 10px height) is collapsed/expanded.

![2016-08-04_10-58-43](https://cloud.githubusercontent.com/assets/6669093/17397155/fe155924-5a36-11e6-8647-42fa0e989b0d.png)

This is the empty div which is wrongly collapsed/expanded:

``` HTML
<div ng-if="!to.collapseGroup" style="padding: 5px;" ng-bind-html="to.description" class="ng-binding ng-scope"></div>
```

Affected Versions: 8.4.8, 8.5.0 RC

**Comment by iJungleboy** [comment]
Was able to reproduce, but it's not the div that's the problem. that one exists after each group, but in this case the remaining fields don't seem to feel like they should go away....working on it...
