### ISSUE TITLE
Edit list dialog does not allow removing and adding items

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#899]
In some cases toolbars can't be added inline (because for example, the items are shuffled or filtered, or displayed very small). The edit list dialog is the only way to see all items and edit them, but it does not offer buttons for removing and adding items.

**Comment by andyduo** [comment]
I think this is the issue i face where i use the module to create a slideshow or slider for example but adding the toolbar into the layout within the repeated region breaks the functionality or it is not possible to see the toolbar. This is where the Edit List option the action menu used to be very handy where we could edit/reorder or delete an item from the list.

**Comment by iJungleboy** [comment]
Old issue, maybe not fixed, but nobody else seems to need it. will close.
