### ISSUE TITLE
Enhancement : enable multiple row editing on Items grid

### ISSUE THREAD

**Issue by mconta** [2sic/2sxc#90]
Scenario: the same app is used on N pages (30+)  and is binded with different items. 
If you need to change some data in all the items this operation will be really time consuming:
- click on the single item "Edit" link
- edit fields
- save and close

It would be nice to have a "batch edit" mode in the items grid, something like this control:

<a href="http://demos.telerik.com/kendo-ui/grid/editing">http://demos.telerik.com/kendo-ui/grid/editing</a>

or here :

<a href="http://demos.telerik.com/aspnet-ajax/grid/examples/data-editing/batch-editing/defaultcs.aspx">http://demos.telerik.com/aspnet-ajax/grid/examples/data-editing/batch-editing/defaultcs.aspx</a>

The editor may change all the items without closing and opening N pages. For Html content a simple text field is ok, WYSIWYG editor is best solution.

**Comment by iJungleboy** [comment]
As this has a low priority and nobody else seems interested i'll close it for now. If someone would sponsor it it would be 1-2 days of work.

**Comment by iJungleboy** [comment]
close till someone sponsors it.
