### ISSUE TITLE
'ASP._Page_Portals_0_2sxc_Blog_App__library_cshtml' does not contain a definition for 'LinkToPageNumber'

### ISSUE THREAD

**Issue by seadubya** [2sic/2sxc#902]
When there are more than 10 content items, I am getting this paging error. If I delete content back down to 10 or less, the posts show. Otherwise, I get the error. I don't see any problems in the code and haven't made any changes except to css styling and removing the second column with the tags/author info to make it a 1 column list.

> Error: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'ASP._Page_Portals_0_2sxc_Blog_App__library_cshtml' does not contain a definition for 'LinkToPageNumber' at CallSite.Target(Closure , CallSite , Object , Int32 ) at ASP._Page_Portals_0_2sxc_Blog_App__pager_cshtml.Execute() in \wwwroot\Portals\0\2sxc\Blog App\_pager.cshtml:line 18 at System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) at ASP._Page_Portals_0_2sxc_Blog_App__1_Main_blog_view_1col_cshtml.Execute() in \wwwroot\Portals\0\2sxc\Blog App\_1 Main blog view-1col.cshtml:line 23 at System.Web.WebPages.WebPageBase.ExecutePageHierarchy() at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) at ToSic.SexyContent.Engines.RazorEngine.RenderTemplate() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 76 at ToSic.SexyContent.Engines.EngineBase.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Engines\EngineBase.cs:line 90 at ToSic.SexyContent.SxcInstance.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\SxcInstance.cs:line 206

**Comment by iJungleboy** [comment]
I believe this issue is related to the blog-app, not 2sxc. It is also clearly something missing around line 18 or in the lines before. 

I'm going to close this issue - because other users won't benefit from it on the 2sxc project. You can continue to write your details and I'll answer them anyhow. 

Please give more information as to which version of the blog app you're using, and please post the code of the ...pager.cshtml and the ...main...view.cshtml.

**Comment by seadubya** [comment]
App: DNN Blog App (v. 02.01.04) 

_pager code:
`@using System.Linq
@{var lib = CreateInstance("_library.cshtml"); }

@* Paging Bar *@
@{
	// retrieve paging infos from the data-stream called "Paging"
    var pageInfo = AsDynamic(Data["Paging"]).First();
    int pageNumber = (int)pageInfo.PageNumber;
    int itemCount = (int)pageInfo.ItemCount;
    int pageSize = (int)pageInfo.PageSize;
    int pageCount = (int)Math.Floor((decimal)(itemCount + pageSize - 1) / pageSize);
}

@if (itemCount > pageSize)
{
<nav>
    <ul class="pagination">
        <li @Html.Raw(pageNumber < 2 ? "class='disabled'" : "")>
            <a href="@lib.LinkToPageNumber(pageNumber - 1)" title="Zur&uuml;ck">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        @for (var i = 0; i < pageCount; i++)
        {
            <li @Html.Raw(pageNumber == (i + 1) || (pageNumber == 0 && i == 0) ? "class='active'" : "")>
                <a href="@lib.LinkToPageNumber(i + 1)">@(i + 1)</a>
            </li>
        }
        <li @Html.Raw(pageNumber == pageCount ? "class='disabled'" : "")>
            <a href="@lib.LinkToPageNumber(pageNumber == 0 ? 2 : pageNumber + 1)" title="Weiter">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>
}
@functions {
	// generate a paging-link number, preserving current tag/author parameters
    public string LinkToPageNumber(int pageNumber){
        string url = Link.To(parameters: 
            (!String.IsNullOrEmpty(Request.QueryString["tag"]) ? "tag=" + Request.QueryString["tag"] : "") 
            + (!String.IsNullOrEmpty(Request.QueryString["author"]) ? "author=" + Request.QueryString["author"] : "")
            + "page=" + pageNumber
            );
        return url.ToLower();
    }
}`

_1 main blog_view-1col code:
`<link rel="stylesheet" data-enableoptimizations="true" href="@App.Path/assets/style.css" />
@* this will show an "add" button if the current user is an editor *@
@Edit.Toolbar(actions: "new", contentType: "BlogPost")

@{
    // get all posts as delived from the standard query
	var postsToShow = AsDynamic(Data["Default"]);
	
	// only apply this filter for non-editors
	if (!Permissions.UserMayEditContent) {
		postsToShow = postsToShow.Where(p => p.PublicationMoment <= DateTime.Now);
	}
}

<div class="app-blog">
	@* the posts *@
	@foreach(var post in postsToShow)
	{
		@RenderPage("_list-item-1col.cshtml", new { Post = post })
	}

	@* Paging Bar *@
	@RenderPage("_pager.cshtml")
</div>`

And here is _library code:
`@using System.Dynamic
@functions {
	// this is a fairly complex workaround to deliver a anonymous type, because 
	// razor doesn't fully support anonymous types, so I must create an expando instead
	public dynamic unknownAuthor = ToExpando(new Dictionary<string, object>() 
		{
			{ "FullName", "Unknown" },
			{ "Image", "unknown.jpg" },
			{ "ShortBio", "bio unknown" }
		}); 
	
    public static dynamic ToExpando(Dictionary<string, object> anonymousDictionary)
    {
        IDictionary<string, object> expando = new ExpandoObject();
        foreach (var item in anonymousDictionary)
            expando.Add(item);
        return (ExpandoObject)expando;
    }

}`

Thanks for taking a look.

**Comment by seadubya** [comment]
Here, that formatting is terrible on that code and it wouldn't let me upload cshtml files...try these.

[_1 Main blog view-1col.txt](https://github.com/2sic/2sxc/files/421880/_1.Main.blog.view-1col.txt)
[_library.txt](https://github.com/2sic/2sxc/files/421882/_library.txt)
[_pager.txt](https://github.com/2sic/2sxc/files/421881/_pager.txt)

**Comment by iJungleboy** [comment]
The code has an obvious bug - I don't know if you caused it or if it's in the published blog app. 

Line 19 tries to call a function in the lib `@lib.LinkToPageNumber(pageNumber - 1)`

but the function is not in the lib file, it's in the same file. This mistake is also in the original code, sorry. 

Could you try to...
1. move the function from the pager to the library file
2. if it works, tell me, so I can upgrade the app?

**Comment by iJungleboy** [comment]
Actually don't do that :). 

Just shorten the @lib.Link... to @Link...

That should do it - pls try and tell me if it worked, thx

**Comment by seadubya** [comment]
I'm 100% certain I didn't add the 'lib.' 

But that fixed it. No error, the posts appear correctly, and the paging links work.

Thank you.

**Comment by seadubya** [comment]
FYI, there were 3 instances of the lib. prefix so I removed all three.
