### ISSUE TITLE
Using EntityPicker should be possible 2-way (Parent-Child and Child-Parent)

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#906]
Example: 
1. you have a content type named "Article"
2. you have a content type named "Tag"
3. in CT "Article" you have an entity picker for picking Entities out of "Tag"
4. BUT in CT "Tag" you can't create an entity picker for picking Entities out of "Article" (reverse way). You just can do it "1-way", not 2-way

Another Example where this would be helpful:
- Person / Function (or also Player / Team)
- (there are definately much more scenarios :) )

**Comment by raphael-m** [comment]
Very, very hard to implement in a good way. Will only do it if we have a sponsor - at least 2-4 days work with concept, design, implementation....
