### ISSUE TITLE
Icon-Picker: Some icon fonts conflict with icon- classes in 2sxc admin CSS

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#907]
There are several icon fonts (including the custom fonts generated with Fontello) which use `.icon-` as prefix. Those CSS rules conflict with the custom font included in EAV / 2sxc admin when using them in the font picker. This results in wrong (or no) icons being displayed in the font picker.

**Comment by iJungleboy** [comment]
Steps to fix
1. Re-export the icon-font with prefix eav-icon
2. do search and replace in the eav-ui project
3. do search and replace in the 2sxc-project
4. test result
