### ISSUE TITLE
Save-and-keep-editing creates extra item if used on initial creation

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#911]
steps to recreate
1. random content type with list function
2. create new item with "+"-Symbol
3. Use save-and-keep-editing button
4. Save it finally (save-and-quit-editing)
5. now you have 2 list items instead of one

affects: 2sxc v8.4.8

**Comment by iJungleboy** [comment]
Thx, we'll look into it.

**Comment by iJungleboy** [comment]
I did a review. It looks like it only creates 1 content-item, but it adds it to the list multiple times, correct?
