### ISSUE TITLE
Toolbars for App.Settings / App.Resources

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#912]
customers sometimes need the possibility to edit App.Resources and sometimes also App.Settings of a specific app. I was told to use these snippets below, but they don't work (no output at all):

@App.Settings.Toolbar -> Toolbar for App.Settings
@App.Resources.Toolbar -> Toolbar for App.Resources

Is 2sxc missing something?

(affects 2sxc v8.4.8.)

**Comment by iJungleboy** [comment]
This syntax was never official or anything. So as of now, there is no official way to do this. 

We have a plan for adding these buttons to the standard toolbar, but as of now, it's not part of the system. So the above example isn't meant to work. 

I'll close this for now.
