### ISSUE TITLE
Content Versioning after upgrade

### ISSUE THREAD

**Issue by ech01** [2sic/2sxc#914]
Upgraded from 7.3.x to 8.4.8. The process went smooth, but the editors are wondering where to get to the content history and load a previously saved version.  It looks like from the github issue log that this was noted, but doesn't look like it has been addressed as of yet. Is this coming soon or should we just forget about this feature?

**Comment by iJungleboy** [comment]
Related to #542 and #19 
Content is technically still versioned, but the UIs and some APIs for review/restore are still missing. For the next few ca. 8 weeks we will focus on documentation like the https://github.com/2sic/2sxc/wiki and the learn section, as well as fixing minor bugs and things like that. 

So basically the feature will be returned, but as of now it's not a high priority.
