### ISSUE TITLE
Some help links on fields to 2sxc.org or 2sic.com are missing http:// and fail to work

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#917]
Help texts have often a link which leads to 2sxc.org, but without using http://, so the link leads to something like:

http://whatever.xy/desktopmodules/tosic_sexycontent/dist/dnn/2sxc.org/help?tag=field-hyperlink

i.e. here
![2016-09-05_10-06-40](https://cloud.githubusercontent.com/assets/12188254/18241341/d462ce26-7350-11e6-981e-e954e29f59a3.jpg)

or also at ADAM 2sic sponsor link

**Comment by iJungleboy** [comment]
Thanks. Can you assemble a full list of the affected items?

**Comment by iJungleboy** [comment]
Never got a list of affected items, so will close for now.
