### ISSUE TITLE
Feature Request: Implement DNN 8 Workflow for 2sxc

### ISSUE THREAD

**Issue by iJungleboy** [2sic/2sxc#918]
Basic wish is to implement the Evoq / DNN 8 Worflow for 2sxc. This was voiced by 2 parties (status 2016-09-05). 
### Some background to the DNN WF:
1. DNN 7+ has a workflow engine, but it is well hidden; in Evoq it is +/- the default when editing. 
2. This WF engine used to be just part of HTML-Pro, but it's now also part of the page-editing cycle. The code in the background is still tied to the HTML-Pro (setting HTML-Pro to premium on a portal messes up all the workflows). 
3. The WF has various UI consequences - from creating draft-updates (which should be stored but not shown) to also some "review previous versions of the page"
### Things I don't know:
1. AFAIK there is no API documentation and no sample code which works
2. There is a blog post from Scott Wilkinson about this, but that's about it http://www.dnnsoftware.com/community-blog/cid/155185/implementing-workflow-in-a-custom-dnn-module
3. Since the WF is strongly tied to the HTML-Pro, there's probably still some dirty stuff to fight through...
4. ...and since almost nobody is using this, there is a very high risk that there will be large issues that simply haven't surfaced yet, but it would cost us a lot of time to find these things and work around them
### Things I know
1. 2sxc has a draft-system, allowing data-items to be drafted - so that's easy
2. 2sxc could also draft most of the module-instance changes (so adding/removing further content items...) - this should work, but would need some coding
### Not part of Workflow, but potentially expected
1. Version-Rollback isn't really a workflow thing, but possibly expected. The preview of older versions would require us to finish implementing history-lookup (see #580), and probably at an advanced level - because the data-schema could change, making a historic-rollback impossible. It's not clear how this would be handled, or if it's required (as it's not really a workflow issue)
### Steps necessary to implement this
- [ ] get full documentation OR production grade, working code 
- [ ] feasibility study: review and create a concept for this - this would take 1-2 days of work
- [ ] if it can be done, implement in probably 2-4 days of work

**Comment by classmaxx** [comment]
I would prefer a small solution asap. A possibility to restrict a DNN-Usergroup of Content-Editors to only create unpublished content and a possibilitiy for another DNN-Usergroup to publish these content.
This would make my life a lot easier ;-)

**Comment by iJungleboy** [comment]
@classmaxx are you sure this would solve your concerns? because the user would probably still have to create page, add modules and things like that - which basically requires full edit permissions on a page. Or am I missing something?

**Comment by classmaxx** [comment]
The scenario we often have, is as i described. There are Content editors, which create the content, but they doesn't have the rights to publish it. Then there is a chief editor, who looks at the unpublished content, perhaps edit it and then publish it. I don't know at the moment, how to realize that. For our Customers it's a key feature... 
I think the publish/unpublish function must be seperated from the other permissions.

**Comment by iJungleboy** [comment]
Just if we "only" add a "can't publish" right, then the user would still create pages with dnn-modules showing a 2sxc, just the data-items in it wouldn't be published. That doesn't seem like a good solution. 

If on the other hand, your editors only need to edit/add data in existing modules (like adding new news, but not publishing them), then it would make sense. What's your scenario?

**Comment by classmaxx** [comment]
ok, i understand, what you mean. I have a talk with customers later this day and i tell you the results.

**Comment by classmaxx** [comment]
I've talked with some of our customers. They all said, the functionality to Create Pages, Add Modules etc. are Adminstrator functions. The Content Editor only need to edit/add data in existing modules (like adding new news, but not publishing them). 

So it were fine, if 2sxc had the possibility to support this feature.

**Comment by iJungleboy** [comment]
@classmaxx ok, we can look into it. It will likely cost about 1d-1.5d work to do right, and it has no priority for us. So if you want it within any reasonable time, you'll need to find out if someone will sponsor it. See also http://2sxc.org/en/Contact

**Comment by iJungleboy** [comment]
close for now till we find a sponsor
