### ISSUE TITLE
V.8.5.1 Fieldtype Entity: Enable Remove item doesn't work anymore

### ISSUE THREAD

**Issue by classmaxx** [2sic/2sxc#924]
I've multiple Fields of Fieldtyp Entity to select one or more Content-Items. Since V.8.5.1 i can't no more Remove an Item. There is no icon to remove any more.

**Comment by iJungleboy** [comment]
Probably something that slipped in with the Material-Design - will check.

**Comment by reto-f-999** [comment]
had the same issue in 8.5.1, and the problem seams to be solved in 8.5.2.
The problem were the missing icons https://github.com/2sic/2sxc/issues/925 

> solved in 8.5.2
> close
