### ISSUE TITLE
Unpublish single (non-list) item leads to error

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#937]
If I use the new "unpublish" function on a content type & template that is _not_ using the list function, the system sais "error rendering template". (I can't see the full error message, because when logged as admin in the item is normally visible.)

If I have a list with just 1 item, and I choose unpublish item, it works normally.

**Comment by iJungleboy** [comment]
I believe this is the same as #562

**Comment by reto-f-999** [comment]
had a customer reporting an "error rendering template" issue. Turned out that it was this bug, so I had to delete the modules (or hide it by module permissions).

**Comment by reto-f-999** [comment]
Steps to reproduce:
1. insert module with a non-list-template (e.g. simple content)
2. insert any data
3. save it with publish state "hide" / "element ausblenden"
4. log off from DNN
5. result: instead of a hidden module you see the error message "error rendering template"

**Comment by reto-f-999** [comment]
if I do the steps above on v8.8.0. i get the following result:
=> instead of a hidden module the visitor sees the demo data for this content type.

**Comment by iJungleboy** [comment]
this is correct - it's just like the data was never added.

**Comment by reto-f-999** [comment]
I see that this is the most useful scenario for a logged in admin, but for any public user it should be visible in "demo state".  Because its very confusing if you see the demo entry as a normal visitor (it looks like something is wrong with the website).

**Suggestion**: if the demo item would be automatically "not visible to public users", both scenarios (for admins & public users) would be perfect. I tested it manually by defining the demo entry as "not visible", and it worked perfectly.
