### ISSUE TITLE
Change entity after selecting entity

### ISSUE THREAD

**Issue by EzraM** [2sic/2sxc#942]
Hello,

Question about the entity picker in the 8.5 material ui:
1. Create a content type with an entity
2. Create instance of that content type.
3. Choose an entity from the dropdown for the entity field.
4. Choose a different entity for the entity field (<= how do you do this?)
 
Thanks!

**Comment by iJungleboy** [comment]
I'm sorry, I don't understand the question and I've read it 3x. Please do the following:

1. use real objects, in your question like "book", "author" etc. so I understand which content type and which entity is meant in which point
2. post it in stackoverflow, as that's where user questions should be placed http://2sxc.org/en/blog/post/moving-discussions-from-codeplex-to-stack-overflow

thx!

**Comment by EzraM** [comment]
Yes, that's not clear. Posted better version to StackOverflow:
http://stackoverflow.com/questions/39520506/2sxc-8-5-entity-picker-change-a-selected-entity

Thanks.
