### ISSUE TITLE
V.8.5.3: Create new App creates no folder for App...

### ISSUE THREAD

**Issue by classmaxx** [2sic/2sxc#949]
Just a small issue. When i create a new app and Import some Content-Types into the new app, there is no folder for the new app in Filesystem. I must manually create the folder to copy the existing templates from the other app.

**Comment by iJungleboy** [comment]
At the moment this folder is created when you create the first template. As of now, I don't think we should change this. i'll close this, ok?

**Comment by classmaxx** [comment]
It's ok. ;-)
