### ISSUE TITLE
Feature: News with Lightbox

### ISSUE THREAD

**Issue by kirkseyc** [2sic/2sxc#950]
New-Simple with a gallery lightbox display.  Attempted 3 times but haven't been able to call it in the new page.  It's useful and sxc.

**Comment by iJungleboy** [comment]
i don't understand the request - is this about an existing app, do you want a new app, do you need a feature in 2sxc?

**Comment by kirkseyc** [comment]
News Feature I suppose.

I’m attempting to incorporate a photo gallery in the Simple News.  However, I don’t find an easy way to do it with the tokens.  I’ve added the App Parameter to visual query but nothing renders.   I’m able to add the Gallery entity to the Simple News app, but I can’t get it to display.

[logo-b]

Carmen A. Kirksey
Web Designer
Harris County Information Technology Center
Carmen.Kirksey@itc.hctx.net<mailto:Carmen.Kirksey@itc.hctx.net>
713-274-7678
1310 Prairie, 15th floor
Houston, TX

**Comment by kirkseyc** [comment]
This is what I’m attempting to do:



[logo-b]

Carmen A. Kirksey
Web Designer
Harris County Information Technology Center
Carmen.Kirksey@itc.hctx.net<mailto:Carmen.Kirksey@itc.hctx.net>
713-274-7678
1310 Prairie, 15th floor
Houston, TX

**Comment by kirkseyc** [comment]
News Feature I suppose.

I’m attempting to incorporate a photo gallery in the Simple News.  However, I don’t find an easy way to do it with the tokens.  I’ve added the App Parameter to visual query but nothing renders.   I’m able to add the Gallery entity to the Simple News app, but I can’t get it to display.

**Comment by iJungleboy** [comment]
@kirkseyc I presume you're fairly new to github. Please post without your entire e-mail footer and all, as it makes this issue impossible to skim.

I believe what you really want to do is "put a gallery into the news-details-view" - right? For that, the best way  ever (and it is very cool) is to use the content-blacks feature, which let's you embed more content-blocks and apps into a details-view :) 

The blog app has this built in already (so you can copy-paste stuff from there, + you can read about it here http://2sxc.org/en/blog/post/designing-articles-with-inner-content-blocks-new-in-8-4-like-modules-inside-modules

**Comment by kirkseyc** [comment]
Sorry. So to confirm I’ll need the blog app or does the same code apply?  Right now it’s generating errors in the simple news when I just copy and paste the cod from the link below.

**Comment by iJungleboy** [comment]
#1 please don't respond by e-mail - the online view becomes unmanageble :(

**Comment by iJungleboy** [comment]
Number 2 yes, the demo from blog applies to any app - it's just easier to get going with a working code sample :)

**Comment by classmaxx** [comment]
this thread maybe help you: http://stackoverflow.com/questions/39597894/combining-apps-in-2sxc/39618723?noredirect=1#comment66649231_39618723
