### ISSUE TITLE
v8.5.4. - force/allow break on label text (to avoid collision with input fields)

### ISSUE THREAD

**Issue by reto-f-999** [2sic/2sxc#960]
**problem:** if the systems uses field labels without spaces or hyphens (so the browser can't break them), they collide with the content input fields. 

---

**example:**
![colliding](https://cloud.githubusercontent.com/assets/12188254/18833658/12e5d880-83f2-11e6-957a-a99c3d5e4487.jpg)

---

**possible solution**: allow browser to break words, i.e. with word-break property (tested - works)
http://caniuse.com/#feat=word-break 

.responsive-optional .eav-label {
word-break:break-all;
}

---

![works](https://cloud.githubusercontent.com/assets/12188254/18833816/deb9af0e-83f2-11e6-9530-a6ee36ad15d6.jpg)

**Comment by iJungleboy** [comment]
I would rather recommend ellipsis (with a ...)
