### ISSUE TITLE
EntityGuid no longer available?

### ISSUE THREAD

**Issue by mryckman** [2sic/2sxc#961]
It looks like the EntityGuid used to be available as a filter field, but after my last update, it went away. Is it possible to filter on the GUID anymore?

**Comment by iJungleboy** [comment]
There was no planned breaknig change, so if something like this fails, we'll look at it. Can you be more specific as to what failed, because I'm not sure if I understood it.

**Comment by iJungleboy** [comment]
I think I found it - if it's an issue with related to the ValueFilter...

**Comment by mryckman** [comment]
Thanks Daniel - sorry I missed this before it was closed... and yes, it was with the Value Filter. Thanks for getting it squared away. I'm always blown away with how fast things get fixed with 2sxc.

**Comment by iJungleboy** [comment]
You're welcome :) - release probably tomorrow or Monday
