### ISSUE TITLE
Required Entity Picker Shows as Invalid on Edit

### ISSUE THREAD

**Issue by mryckman** [2sic/2sxc#967]
I have a field "Location" that is an Entity type where the user chooses a location of possible buildings. I've noticed that, when I edit an existing item, I cannot save until I re-choose the location field. It gives a warning that the location is required. But, the location is already selected and was loaded with the other fields.

**Comment by iJungleboy** [comment]
Just so understand the issue correctly:

1. if you have a required-entity-field
2. at it has something in it, but wasn't actively "touched" when opening the edit-dialog
3. then the dialog thinks that the "required" is not fulfilled, and doesn't let you save it

correct?

**Comment by reto-f-999** [comment]
same issue here 👍 
the 3 steps you mentioned are correct
