### ISSUE TITLE
ClientDependency includes do not work when using SxcInstance.Render

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#975]
JavaScript- and CSS files are not included when rendering a 2sxc module with `ToSic.SexyContent.Environment.Dnn7.Factory.SxcInstanceForModule(...).Render()` that has script or style includes with `data-enableoptimizations="true"`.

**Comment by iJungleboy** [comment]
Cannot reproduce - I tried this razor to load another module

```
<p>intro text</p>

@ToSic.SexyContent.Environment.Dnn7.Factory.SxcInstanceForModule(1199, 470).Render()

<p>extro text</p>
```

which successfully included that instance and added the js/css as desired. The command was run from inside a 2sxc razor, but I believe it doesn't make a difference. Please re-open if you find otherwise.
