### ISSUE TITLE
Allow ClientDependency integration to use DnnFormBottomProvider

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#976]
The ClientDependency framework allows specifying a provider which basically defines where in the HTML the includes are added (head, body, at the end of the form tag, ...). Currently, 2sxc includes the assets in the default provider which includes files in `<head>`. We need a way to configure this as most of the times, the assets should be placed at the end of the document (performance gain).

**Comment by iJungleboy** [comment]
There had been an issue like this before, and we then reviewed this internally and the last review was that it won't help much, because most script-intense apps would almost always be at the page beginning. Let's discuss...

**Comment by iJungleboy** [comment]
Reviewed it internally, decided it would probably make sense just to offer this as an option.

Note that soon with http2, more options will emerge. So whatever we add here, we must be aware that there might be a 3rd or 4th variation sometime in the future. 

As of now, the syntax is as follows:
<link rel="stylesheet" href="[App:Path]/Sexy Feature List/Assets/style.css" data-EnableOptimizations="true" />

The code which picks this up is https://github.com/2sic/2sxc/blob/94fa8256a975152f9fc1ec6361bee5f3334f99fb/SexyContent/Engines/EngineBase.cs#L93-L164

What we could do

1. add another attribute, like `includeposition="bottom"`
2. change the value so it can be `"true"`, `"false"`, `"footer"`
3. enhance the value  (currently "true" or "750") with an additional info, like `"true:footer"` or `"750:footer"`
4. go complex and assume that additional features will emerge, so we would create a more complex json here like `enableoptimizations="{ enable: true, priority: 750, method: 'footer'}"`

I recommend we do 2 and 3. Your thoughts?

**Comment by raphael-m** [comment]
I also recommend 2 and 3, but I'd rename `footer` to `bottom` (because there is no actual footer element in the page, `DnnFormBottomProvider` just places the includes before the closing form tag).

**Comment by iJungleboy** [comment]
I'm just implementing it, but did notice a downside in special cases

IF someone creates a new template in a new 2sxc and uses this feature, and _then_ re-uses the template in an older version (copy/paste or app-export-import) then in the older version, client-dependency will be as if disabled, because the old pattern-detection only checks for number ### or for "true", but would skip anything like "403:body" etc. I believe we can live with this.

**Comment by iJungleboy** [comment]
Ok, the syntax is now as follows

## Defaults
* Position of JS: body
* Position of CSS: head
* Default Priority of JS: `FileOrder.Js.DefaultPriority` = 100
* Default Priority of CSS: `FileOrder.Css.DefaultPriority` = 100

1. any number like `250` - behave as till now, default position
2. `true` - behave as till now, priority = 100, default pos
3. `body`, `head`, `bottom` - default priority, at these positions
4. `true:body`, `true:...` - same, default prio, set only position
5. any number + position like `200:body` set prio and position

**Comment by iJungleboy** [comment]
Todo: 
[ ] snippets
[ ] documentation

**Comment by iJungleboy** [comment]
Todo: 
- [ ] snippets
- [ ] documentation
