### ISSUE TITLE
Can't Populate Content Item Drop Down from DnnSqlDataSource (Visual Query Designer)

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#977]
Hopefully I'm just missing something, but I've looked through all the demo apps and docs and can't find a way to populate a drop-down for a new Content Item from a DnnSqlDataSource aside from Custom Input Types.

Most of the examples I see can populate adrop-down from another Content Item in the same app, but I'd like to have the items come from a query. Following the docs for DnnSqlDataSources, I created a query that returns an EntityId and EntityTitle to do this.

Is Custom Input Types the  only way to do this? If so, it seems like quite a bit of steps to jump through for a relatively simple task where SQL is doing the heavy lifting.

Thanks!!!

**Comment by iJungleboy** [comment]
In short: not implemented yet. 
You're not the first to wish this, or a similar feature for "dropdown populated by a json from somewhere". Both cases simply haven't been implemented and we're just waiting for someone to volunteer - hint hint :)

BTW: it would have to be a string-... input field, as the resulting ID(s) would never be an entity. 

If you would volunteer, we could spend some time ensuring the specs are globaly workable (like remembering multi-selections, etc.) interested?

**Comment by tpperlman** [comment]
Thanks, Daniel. So if I understand you correctly, Custom Input Types can not be used for this?

If it were to be implemented, the stored field would ideally need to be an ID (would probably have to be stored in 2SXC as JSON though, especially for multi-select) because the text may change but the ID would be fixed.

I might be able to pitch in, but at the moment I have two huge DNN projects that are prepping for beta testing. As a one-man show I can only do so much... I think I will also need to familiarize myself with the new scripting platforms you are using first.

**Comment by iJungleboy** [comment]
You have two options:

1. Custom Input Types + string-field - this works perfectly for your need - and you would decide what data-type to store in a string field. 
2. Custom Data Type + Custom Input Type - this works as well, but has a few advantages. 

I'd love to go into more details when you have time, so just get back to me if you see a time slot (or a paying customer) ready for this :)

**Comment by iJungleboy** [comment]
Releasing 2sxc 9.11 in a few hours. There we have a new string-dropdown-query, which will be just for this :)
