### ISSUE TITLE
No portal files in app export since 2sxc 8.5.2

### ISSUE THREAD

**Issue by pascalmoser** [2sic/2sxc#978]
The folder /Apps/Content/PortalFiles is missing in the exported zip file.
Versions checked:
8.5.6 no files
8.5.4 no files
8.5.3 no files
8.5.2 no files
8.5.1 works
8.4.8 works
8.4.7 works

**Comment by iJungleboy** [comment]
Ok, thx. Hat glaub mit unserem Github “.data” update zu tun…

**Comment by iJungleboy** [comment]
Found problem - was because we changed the sequence of some code, so the file-list for export was still empty when the files were copied to the temp folder.

**Comment by iJungleboy** [comment]
Did a micro "nightl" release for this here: https://github.com/2sic/2sxc/releases/tag/v08.05.06.10

with further bugs I'll then release an 08.05.07...
