### ISSUE TITLE
V8.9.0 Error 404 or 400 after editing and save entitypicker contenttyp

### ISSUE THREAD

**Issue by classmaxx** [2sic/2sxc#987]
I've an error 404 after editing and save an entitypicker fields contenttyp.

Szenario: Contentyp article has an entitypicker field for Contentyp chapter. Wenn i edit an article, i can also edit a chapter. When i now change something in chapter and save it, i get an error 404, though the changes are saved. This happens on every field i'm editing in chapter. 

This is the output from ff-console
![error 404](https://cloud.githubusercontent.com/assets/22051626/19557771/8fe7306c-96c7-11e6-9ac5-f7bab23b0ab5.PNG)

**Comment by iJungleboy** [comment]
This doesn't really make sense. Could you help corner it a bit more?

- does it happen on all content-types, or just this one type?
- does it happen on various portals, or just this one?
- do you see any difference between the calls that return a 404, and those that don't?

**Comment by reto-f-999** [comment]
I encountered the same issue. I can reproduce it like this:

1. if you have a content type "book" with an entity field "author"
2. and you edit the "author" entity out of the content type "book" 
3. and now you save the entity with the save button (!not with quick save & close, this won't drop the error message)
4. you get an error message 404


Your questions:
does it happen on all content-types, or just this one type?
-> it seems to happen on all content types with this setup (tried about 3)
does it happen on various portals, or just this one?
-> there is just one portal
do you see any difference between the calls that return a 404, and those that don't?
-> can't properly answer that question - maybe @classmaxx can tell?

**Comment by classmaxx** [comment]
@reto-f-999 explained it clearly. It happens on ALL content types, which have one or more entity fields and you edit the "child" content out of this content. But only in edit mode, not if i create a new item. it doesn't happen, if i only edit the "parent" content.

**Comment by iJungleboy** [comment]
This is very good feedback, thank you

**Comment by classmaxx** [comment]
Are there any news about this issue? My customers are not so amused with this error...

**Comment by iJungleboy** [comment]
Nothing new - nobody volunteered to pick this up yet. You are free to review the code and submit the fix - most likely the edit-button is passing the wrong information to the dialog which opens, or after the saving something wrong happens.

**Comment by classmaxx** [comment]
I have some new information about this issue:
The error only occurs, if the **called** (child)contenttype has min. 1 Entitypicker-field. If there is no entitypicker-field in the childcontenttype, everything is fine.

**Comment by iJungleboy** [comment]
@classmaxx awesome - this could help track it down. sound like a global variable getting changed...

**Comment by classmaxx** [comment]
I think, i have one solution, which solve the problem. I post it in an hour.

**Comment by iJungleboy** [comment]
I believe I found the problem. The "re-load entities" command is by default called to load everything, but there's a callback-case where it receives the just-edited item as parameter, and it's not expecting that. It then uses the parameter in the load-url, but that's not how it should be. I have to check if 

1. there ever is a case where the parameter does make sense
2. if I remove it, what are the consequences

...

**Comment by iJungleboy** [comment]
found and fixed
