### ISSUE TITLE
DateTime picker not showing time pick

### ISSUE THREAD

**Issue by mangiove** [2sic/2sxc#990]
Hi, besides not being custom culture configurable the datetime picker (I see another issue already open about this) I enabled the timepicker in the field configuration but it does not show it...

https://snag.gy/DOc10d.jpg
https://snag.gy/K9SJeC.jpg

**Comment by mryckman** [comment]
I've had this same problem for a little while. IIRC, I noticed it show up a few upgrades ago, though I failed to report it - sorry about that.

**Comment by mangiove** [comment]
I'm using the latest released version "2sxc 08.05.06 With Hotfixes" and it has the issue :(

**Comment by raphael-m** [comment]
Fixed with https://github.com/2sic/eav-ui/commit/69ea4a91bbdb1f1c52e89dfb95d5e9a9222582c3
