### ISSUE TITLE
 Edit UI no longer appears

### ISSUE THREAD

**Issue by joshgk00** [2sic/2sxc#993]
My DNN site is running 7.4.2 and I'm running the latest 2sxc, 08.05.06. I have this strange issue where when I try to edit any content items, instead of displaying the edit dialog, it's now just displaying a bunch of javascript.

Before: 
<img width="578" alt="before" src="https://cloud.githubusercontent.com/assets/13650025/19830601/38690640-9dc9-11e6-8cfb-1a794fb93b44.png">

After: 
<img width="670" alt="after" src="https://cloud.githubusercontent.com/assets/13650025/19830604/42a46b7c-9dc9-11e6-806b-70ea39c1f78b.png">

As far as I know nothing has been deliberately changed on the site and I'm not seeing any errors in the browser console related to the module. No errors are showing in the Event Log either. I've tried reinstalling the latest release overtop to try to repair anything that may have been corrupt or missing but that didn't solve the issue. Any ideas what might be happening here?

**Comment by iJungleboy** [comment]
I recognize the script, but of course it shouldn't show. It's part of the ui.html, the main page which runs the JS showing the dialogs. To me it looks like that file is defect, so the script is treated as HTML and shown instead of run. Could you check that?

Try to : shift-click on edit (will open new window). now you can inspect the html better.

**Comment by joshgk00** [comment]
When I Shift-Click the dialog opens a new window and it just shows the html from the file. This is a partial view of what I'm seeing. 

![image](https://cloud.githubusercontent.com/assets/13650025/19892920/98798892-a01d-11e6-8753-17a68a67e7e7.png)

**Comment by iJungleboy** [comment]
It seems that your browser wants to show this html-file as if it's a text file. Could it be that your server is delivering an incorrect mime-type? pls check with fiddler or with F12-debug.

I believe this is very specific to your system, so I'll close this, but I'll keep answering follow-up posts.

**Comment by joshgk00** [comment]
I found the issue. There was a conflict with the URL provider as it was setup to handle the .html extension. I added a rule to skip the processing of ui.html and now the functionality has returned to normal. Thanks for your help!

________________________________
