### ISSUE TITLE
Beta 08.06 to have extensive new customize-the-toolbar features

### ISSUE THREAD

**Issue by denisjoconnor** [2sic/2sxc#994]
The current beta 08.06 will have extensive new customize-the-toolbar features. In 08.05 it's not possible yet. Ability to add new action button features to existing ones in 'inpage.js' file and to be able to customize '@Edit.Toolbar(Content)' plugin.

**Comment by iJungleboy** [comment]
Will be in the next release. Current beta documentation (still undergoing work) is already in the wiki...

https://github.com/2sic/2sxc/wiki/Html-Toolbars-Custom-Code

You'll see a beta 08.06 release in a few days :)
