### ISSUE TITLE
Feat Input-Type: Time Only Field

### ISSUE THREAD

**Issue by mryckman** [2sic/2sxc#996]
Hello,

I'm wondering about a good way to create a "time only" field. 2sxc implies this might be possible as the date field says "date and/or time", but I can't see a way to use only time. Is this available?

Thanks,

Mike

**Comment by iJungleboy** [comment]
At the moment it's not quickly possible yet. You could 

1. enhance the existing one and share the code (contribute the feature)
2. create an own input-type and again share :)

**Comment by iJungleboy** [comment]
As we're going to a new angular 6/7 UI, this will be different. I'll close for now, anybody needing this or wanting to contribute pls post it here.
